### ISSUE TITLE
We probably should've have kept triplea-test-1 around

### ISSUE THREAD

**Issue by djensen47** [triplea-game/triplea#1]
We had some good conversations going. It would have been nice to capture the details of some of those. 

I guess we have the emails for each one so we can work from there?

**Comment by veqryn** [comment]
weird, i only saw emails for one of the conversations (the one about naming the organization).
i did not see any other conversations...

**Comment by djensen47** [comment]
Oh, you had to participate to see the emails. I may no have all of the conversations after all. Oh well.

**Comment by veqryn** [comment]
oh.  is there a way to be notified of any and all conversations/tickets/issues/etc?

**Comment by DanVanAtta** [comment]
"Watching the repo" it tells me: "You’re receiving notifications because you’re subscribed to this repository."

Participants should for certain get email notification. I think the wiki would have been best captured ;), but let's move forward.

**Comment by ron-murhammer** [comment]
Yeah it depends on your github settings. I mentioned a few times that the old repo would probably be deleted so it would be better to have had to conversations in the forum still :)

Anyways I think I have just about all the emails so can resurrect if needed since I watch the repo and get notifications for everything.

**Comment by DanVanAtta** [comment]
True, I think the expectation was to allow the 'old' github issues to drain away when the new one was pulled up. If you have a copy of the refactoring wiki list, that would be useful since some effort was put into that. The questions I think have mostly been recreated and we mostly still remember the context (so spilled big at this point IMO)

**Comment by DanVanAtta** [comment]
Should we close this issue?
