### ISSUE TITLE
Remove Serialization + Reflection

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1036]
An issue to consolidate communication around the topic. Catalog usages of reflection and serialization here, discuss ways we can solve the problems here as well.

Background:
- The reflection and java RMI usage makes code versions not compatible with enough. Due to the technology, very minor changes such as private variable name changes can break this compatibility. 

Solutions so far:
- Serialization proxy pattern can be used to alleviate  serialization problems. The pattern can be used to remove 'GameData' objects from being passed around (TODO: add link of PR that added the pattern, also need a link to the associated interface file as well)

**Comment by RoiEXLab** [comment]
@DanVanAtta As discussed before - in order to achieve this, we may use a format like json/yaml (or Xml?) to save the game state. I personally prefer JSON over yaml, but since triplea is already using a yaml parser, yaml might be the easiest choice. XML would be an option too, but I heard in many forum posts, that xml parsing is slow compared to the othet choices... 
Of course there is no need to keep the savegamefile in textform - we could easily gzip (or any other compression algorithm) the file to save disk space. 
No matter what we do, I'd highly recommended to change the triplea Savegame extension when this is changed to avoid any confusion and problems.(Also TripleaSaVeGame tsvg might be read as svg - scalable vector graphics file)

**Comment by DanVanAtta** [comment]
I don't think we'll be able to successfully go from serialization for saves to a custom format. Using serialization proxy pattern first I think will let us get there in a two step approach. The proxy pattern will allow for different versions to be compatible regardless of updates, but it also removes the GameData dependency throughout. After removing that dependency, we'll be in better shape to do custom format for saves. Yaml would probably be more preferred format over XML or JSON, but we have plenty of time to review that choice.

For reflection, we need to do some cataloging work, figure out where it all is, and work to remove that.

**Comment by DanVanAtta** [comment]
closing for now. Serialization and reflection are used for different features in TripleA and replacing them each is a project in their own right. This discussion for now is a bit settled at least that we want to remove usages of Serialization and reflection  from TripleA.
