### ISSUE TITLE
Lobby Game Stats + User Profile Pages

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1042]
Effectively keep track of some stats for each player. Allow those stats to be available from a right click 'profile' menu for example, or a hover over action.

How important is this to people? What types of things would be interesting to track (and out of those, which ones _can_ we track?)

**Comment by ron-murhammer** [comment]
I think it would be useful to at least see things like:
- When account was created
- Number of games played or hours played or something
- Game preferences (revised, WaW, etc)

It would be harder to create any real 'record' or 'rating' without a major overhaul of the ladder so I'll leave that for another topic.

**Comment by yamamot0** [comment]
Hi,

+ when an account is created would be great for all player (and the mods: would solve some problems). This is very importent for a lot of player, who wants to play against experienced player and also very helpfull because we have problems with some trolls who changes they name each week abandon games, offend players and mods.
+ game preferences would ok too, if possible. But I dont think this is neccesary: people finds they games in the lobby,
+ best of all would be elo-point, wenn the ladder is working and win of tournament/participation in tournaments


From my experiences I would say the following info doesnt help very much.
- number of games: most games dont finish and the number is easy to influence (just starting games or making funny games) 
- hours of played could be "abused" too: some player are 24h online not playing. You could do that "playing" a game too.
I dont think the two last items would "helpfull"

**Comment by RoiEXLab** [comment]
Well we could limit wins/hours etc. to online Lobby battles...

**Comment by DanVanAtta** [comment]
Backlogging: https://github.com/triplea-game/triplea/wiki/Feature-Back-Log/, will re-open if this is picked back up, still more details to work out here.
