### ISSUE TITLE
TripleA-2.6.796 display of Players & Bottom Unit Bar

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#10506]
A recent version of TripleA has caused, the number of players to be duplicated, but in a different order.
There should be 16 displayed starting with Minor and ending with Joseon.
But it continues and duplicates starting with Otomo then Ikko-Ikki etc.

This happens on the following maps;
The Shogun Advanced
The Shogun, 3 months old
Sengoku (Sengoku - Nippon Warring States), over 6 months old

The commonality, all my maps 🙄 I have tried a few other maps not by me, but cannot replicate it.  
I do make use of random owned territories and randomly placed units, but that could be misleading.
The 3 maps above do have politics and my other random maps that work as intended do not.

**Bottom Unit Bar**   (The Bottom Unit Bar is not really a problem)
As can be seen from the image below, I like other map makers use the territoryEffect space to display a graphic with the actual numbers of the territory effect and this reduces the space for the units.
But I would like it **all**, Resources, territoryEffect, Terrirtory name & PU, **Units**, Error Message

Can the truncation be removed, so that units can flow along the whole status bar and when there is an error messages, it is displayed, but pushes the current status bar to the left, meaning that Resources are pushed off the screen?

![image](https://user-images.githubusercontent.com/71022517/170448506-004ad364-22fd-4293-bcb8-1598220fc4b6.png)

**Comment by asvitkine** [comment]
Thanks, I will take a look. Agree that we can probably omit the space reserved for the status message when there isn't one.

**Comment by asvitkine** [comment]
The bottom of the player list shows alliances. You have the following alliances set on that map:

```
    <alliance player="Amago" alliance="Amago"/>
    <alliance player="Azai" alliance="Azai"/>
    <alliance player="Bessho" alliance="Bessho"/>
    <alliance player="Date" alliance="Date"/>
    <alliance player="Hojo" alliance="Hojo"/>
    <alliance player="Ikko-Ikki" alliance="Ikko-Ikki"/>
    <alliance player="Joseon" alliance="Joseon"/>
    <alliance player="Miyoshi" alliance="Miyoshi"/>
    <alliance player="Mori" alliance="Mori"/>
    <alliance player="Oda" alliance="Oda"/>
    <alliance player="Otomo" alliance="Otomo"/>
    <alliance player="Shimazu" alliance="Shimazu"/>
    <alliance player="Takeda" alliance="Takeda"/>
    <alliance player="Uesugi" alliance="Uesugi"/>
    <alliance player="Wako" alliance="Wako"/>
```

They happen to have the same names as players.

**Comment by asvitkine** [comment]
However, I confirm that the ordering of alliances that are displayed is arbitrary. We should probably change that ordering to be deterministic, maybe just alphabetical.

**Comment by TheDog-GH** [comment]
With 2.5 my maps display as intended, that is just the order of the players.

The maps have a mix of Victory conditions they use Allied Political Alliances and use just one player, can I mix them?
Triggered Victory - based on Allied Political Alliances using alliedOwnershipTerritories
Projection of Power - I thought Alliances had to be defined for this to work
Economic Victory - I thought Alliances had to be defined for this to work
I will do some testing.

**Comment by asvitkine** [comment]
https://github.com/triplea-game/triplea/pull/10508 makes the status message area not visible when there's no status message.

**Comment by TheDog-GH** [comment]
I can confirm that Alliances **have** to be defined for the following to work;
Projection of Power
Total Victory
Economic Victory

In 2.5 my mixed victory maps did not show the alliance factions/players list in the Players tab.

Is the way to solve the above, sto how the players list in turn order (not alphabetical) followed by the combined player Alliances that are hard coded in the xml, eg like 2.5 currently does?  Eg Axis and Allies

Could the combined player Alliances be in bold, to make them stand out?
PUs, Production, Units, TUV be right aligned?
Only if your near that code 😉

As an aside the Technology table could be displayed in the Players tab and could have its own Ctrl+T panel.

**Comment by asvitkine** [comment]
Sent https://github.com/triplea-game/triplea/pull/10516 to make alliances bold.

**Comment by Cernelius** [comment]
@asvitkine Rather or other than making them bold, I think alliances should be a footer for any "player" which is of that alliance, with a bolded line as separation. This will make the list unable to show the turns order, but that is not even spelled out at all (that currently the listing order of the players is their turns' order). I believe communicating to what alliance each player belongs is more important than communicating the turns' order (especially since it is not explicitely communicated anyway).
It's not a big deal for the usual Axis and Allies games (as everyone knows who the "good guys" are), but it may be a big problem to know who's part of what alliance (and, if the game has politics, also the "Politics Panel" won't be telling about the actual alliances).
The turns order should rather be communicated by an additional "Turns Order Panel" screen via the "Help" menu, even though some games (like "World At War") take care simply to have a table in the notes about it.

For example, instead of:
Russians
Germans
British
Japanese
Americans
**Allies**
**Axis**

It would better be:
Russians
British
Americans
**Allies**
\-\-\-
Germans
Japanese
**Axis**

**Comment by asvitkine** [comment]
That does sound like it would be a good improvement. However, since it would be a bigger change, I don't think it's something I'll get to, since I have a few other changes I'd like to complete before I won't have as much free time anymore in about a month.

**Comment by beelee1** [comment]
Is there an on/off switch for the Bottom bar ? Just for the units ? I occasionally use the PU value for Sea Zones that have value and aren't shown in the actual Sea Zone. I could see where it might be handy for a cluttered Territory though. That's why it's be nice for a in game switch. With the added units, I find it slightly annoying because of the increased flickering when I'm scrolling through the map. 

I think before all it had was PU value ? so I didn't really notice it. Same reason I always turned off the "Units to move"  in 2.5, which was actually more distracting. I see that's not on 2.6

Anyway, not a huge issue

**Comment by TheDog-GH** [comment]
@beelee1 
Try this 
View> Show Units in Status Bar (Untick)

**Comment by beelee1** [comment]
@TheDog-GH  Thanks :)

**Comment by asvitkine** [comment]
I'm closing this as a number of improvements have landed. Feel free to file follow up issues for anything specific that hasn't been addressed.
