### ISSUE TITLE
Issue Ploriferation

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1057]
I'm sorry, I know that most developers prefer the many issues system, I guess as self-mementos maybe, but is there a system for tracking obsolete / forgotten issues?

I have the feeling that many issues get open, also by the developers, and just stay there forever, and then others are opened, and others, and others. Is there a system for like tracking what is waiting for development soon and what is just forgotten or wish list or was just opened for somewhat keeping track?

As a non-developer (no-skill) I just feel lost in GitHub by the so many issues that often also developers open but then stay there, so it is hard to figure what the developers actually want to do (I assume they can't be wanting to do everything or even most of what gets opened, since it is so much), when so many issues are opened by them and other more are opened, while so many already are there waiting. I mean nothing wrong about that, I guess, but there are soo many...

Why to open many issues and leave them there? How can other people know what of all those many things are the things that are supposed to get actually done shortly (because there is actually a developer behind determined to push it soon) and what not?

Shouldn't be better to open issue only on what you are determined to tackle relatively soon or on a few things you strongly think are priority, thus limiting a bit the issue quantity?

Maybe a time limit that if the issue doesn't get upped or referenced for a while it gets auto-closed?

I just fear that many forgotten issues might drown up old issues that are still good.

What about a special tag to tag all issue that the opener itself doesn't seriously intend to push forward anytime soon, but are more like just opened to sort of keep record of this or that issue or idea or maybe hoping somebody else would get interested and pick it up?

I'm just saying that I sort of feel lost and don't really know what the developers actually intend to do of the so many things they or other people opened, but maybe this is not a problem at all and it is just me feeling it strange.

How can you know what the developers are on it and wish to get done and what they just opened for future reference, if this is the case of the many opened issues that stay there, while many other more are opened?

Maybe adding a tag for the issue that are just suggestions / memento and there is not really a determination from anyone to tackle them anytime soon, and then you remove the tag when anyone volunteers to pick it up and get it done?

I guess that the "Assignees" or "High Priority" are supposed to do that, but, for example, the "WarClub Bunker Forum Alternatives" is open and with no Assignees nor High Priority; how can anybody know if that is something getting done soon, or not, instead of the other like 100 issues with no Assignees and no High Priority, as well?

Is "Ice Box" supposed to mark all issues that are indefinitively on hold? Anyways, I see only 3 issues now have the "Ice Box".

Thanks and sorry if I'm not making sense, feel totally free to close this issue if I'm just ranting. I'm just being a bit puzzled by seeing also developers opening so many issues after issues, and I think it is not easy to understand what it is really rolling, just that.

Maybe it's all fine and it's just me getting lost, but just wanted to say that I think it feels very dispersive and it is very hard for outsiders to even know what the developers are on or intend to do (I just guess not everything, due to the sheer quantity) or what they are strongly determined to push forward or it is just up there as a possibility (maybe this is what the Discussion tag is for, but only few issues have that tag).

Or is the "Feature Request" supposed to mark all issues that nobody really intends to work over, and it is just requesting / wishing others to do it, and it gets removed when a developer volunteers for actually doing it?

What I mean is that I think at the moment if like somebody not into TripleA wants to take a look at GitHub to know what the hell the TripleA developers intend to do, it is not easy to get a clue, just that.

Maybe an "official" To-Do list like the old Veqryn's one?:
http://tripleadev.1671093.n2.nabble.com/Development-To-Do-list-tp7582044.html

Thanks, and sorry if I'm being pointless (not a developer, so just saying).

**Comment by Cernelius** [comment]
I mean, it sort of feels like Issues are opened and that's it, then others are opened and that's it, etc. etc..

I mean, that's fine, I guess, but I think it would be good to clearly highlight what are the issues that are being opened just for future reference, with no clear intention to even push / develop them anytime soon or ever, especially when opened by developers, and what are the ones a developer is actually struggling behind at the moment or soon.

Also maybe distinguish issues opened by a developer from those opened by people with no developing skills?

Just that.

If this is just regular and I'm seeing problems that don't exist or I'm missing something obvious, I'm sorry and just close this issue, please.

**Comment by ron-murhammer** [comment]
@Cernelius Right now we are kind of using labels on the issues to have a kind of organization on them. As the number of issues grows, this may be difficult to manage and new tools might be needed. The idea would be to use a tag to mark what issues we'd like to plan for each release. This was done for 1.9 though most of these are closed now.

**Comment by ron-murhammer** [comment]
We are going to try use ZenHub to better organize issues: #1059

**Comment by DanVanAtta** [comment]
We need to discuss how we are going to handle issues a bit. 

@Cernelius , some context which you might be missing, there are an additional 300+ items in the source forge bug and feature request queue which are not tracked in Github.  The problems you are referring to were even worse there. Github issues is a replacement for those two queues.

My thinking on labels is that they are effectively ad-hoc categories, similar to what you find in the forums: "general" "development" "maps", etc..  

Whenever any one topic gets too large, say more than 20 items, we look at the items and see if we can split up the categories, or add an additional meta tag to group up the additional items. For example, if you want to view all bugs:
https://github.com/triplea-game/triplea/issues?q=is%3Aissue+is%3Aopen+label%3ABug

All bugs relating to gameplay rules: https://github.com/triplea-game/triplea/issues?q=is%3Aissue+is%3Aopen+label%3A%22Game+Rules%2FPlay%22

Bugs relating to the UI displa: https://github.com/triplea-game/triplea/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3ABug%20label%3A%22UI%20Related%22%20


One downside of tracking issues in github is that only admins can add/manage labels. Ideally we would have an issue admin help with the intake of issues, and to take care of making sure that things are followed up on.


Some quick descriptions of what labels are intended to mean:
- bug -> just a known gam ebug
- feature request -> a proposed update to the game that would be good to have. Anybody can pick these up
- in progress -> someone is actively working on this issue (or if the issue is assigned, we should probably prefer to assign issues)
- ice box -> no plans to work on the issue anytime soon, or we cannot for one reason or another (too many other issues being a reason)

- regression -> something that worked in the last game release, but no longer works now. A relatively hard rule is that anything that used to work, must continue working (or be replaced in a reasonable fashion)

**Comment by DanVanAtta** [comment]
Also of note, the outcome from this issue should be some documentation, preferably on the github triplea-game  README

**Comment by DanVanAtta** [comment]
Re-summarizing in #1061, please follow up there.

@Cernelius  That was a LOT of text. Please be respectful of our time and spend some serious time refining what you type so it is concise and to the point. It's fair that the topics are complex and not familiar, but it took way too long for you to simply ask what "feature request" means as a label. 

In general, a problem with this game/project is the way it is set up requires far too much manual work and overhead. So much so that even a single full time developer is almost not enough. We have additional problems that developers are stuck being admin of certain processes. Until recently, developers had to do everything to make sure that a map zip is available in the game. We just successfully had the tutorial map be developed without any developer assistance beyond initial setup (which is mostly scripted).

My point is, please save us time by being to the point. Surely you want us working on the game and not reading/understanding what you write and then spending all our time just responding .

**Comment by DanVanAtta** [comment]
Update: see #1059  for the latest on this topic
