### ISSUE TITLE
Prerelease is full

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#10624]
I noticed that prerelease.triplea-game.org seems to have run out of disk space, causing the automatic deployment to fail for a while now.
@DanVanAtta Do you think there's a way to make space somehow or do we need a larger hard drive?

**Comment by DanVanAtta** [comment]
Needing a larger drive implies we have a growing data requirement. Unless the space usage is coming from database, presumably we are failing to clean up or rotate old data.

I'm working to remove the prerelease server entirely. Previously the space issue came from each new version of lobby & bot creating new folders. We are somewhat low on space on the prerelease server due to the map download for bots, so these extra versions fill up our extra disk pretty readily. So, we'll want to take care that we overwrite the latest version in production rather than add a new installation. If we do that, this should be a mooted issue.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/pull/10634 removes the deployment actions to deploy to the prerelease server.
