### ISSUE TITLE
Github.io + WarClub websites, relationship and responsibilities

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1070]
We have two websites, github.io: http://triplea-game.github.io/, and the warclub site: http://tripleawarclub.org/

To discuss here, what content will belong on which site. 

---

I suggest we can sister the two sites, namely by linking one to the other in their respective navigation headers. The warclub would be more the community part of the website, while the github.io will host the download page and static content such as rule books. Github.io will also be a good tech stack for showing a maps page, with info on each map pulled from standard locations.

Having github host the download page is really nice for at least this reason:
- no extra dependency for the download page to be available, either github or is not, does not make a difference if the server crashes or is being migrated, etc..

The static content on github.io is also very nice since we get versioning of it. It's also content that we do not have to manage on a server.

**Comment by ron-murhammer** [comment]
@DanVanAtta Short term I agree. Long term I'd prefer to merge the 2 sites. However we merge them the code for the website should live in github even if we are deploying it to a server rather than github pages.

**Comment by DanVanAtta** [comment]
Let's get Zjelco's feedback on this one, @RoiEXLab, any thoughts?

(I vote it's time to mark Zjelco a contributor so we can and assign issues to him :grin: )

**Comment by RoiEXLab** [comment]
@DanVanAtta I Agree with @ron-murhammer

**Comment by ZjelcoP** [comment]
Main issue i believe is that the amount of users of TripleA is vastly bigger than active members of the community. 
One of the main causes of this is people coming to download the game do not see the community.
-Currently (1.8.0.9) most go through sourceforge that to many users is some absolutely boring looking tech forum where people talk about stuff those users don't care about or even understand. 
-IO-website: Already looks better, but is essentially still a completely dead space. No community to be seen anywhere unless they actively search for it on the site. Am currently linking it as the TripleA site from the Facebook-page (also experimenting a bit with adds) but not very happy about it because of this reason.

To grow the community i think we should force everyone through the community (players +development) website with 2 effects:
1: increase amount of users. (I believe many already quit before even downloading and trying the game just by the impression they get(boring/techy/where the hell are the users?)
2; increase community participation by those users.

Also i think going through the website and wanting to access any information, resulting in many times being forwarded to an other website results in bad user experience.

**Comment by DanVanAtta** [comment]
There is a lot of documentation in the warclub forum. Forum posts are not really appropriate for documentation. PRs are nice because you can get line by line commentary and the commentary goes away after the changes are agreed upon. Regardless, does seem to me that we should be migrating static documentation content out of both forums, and put on a static Github IO webpage.  

The Github IO page could use more of a community emphasis. There was an effort to first showcase all the community maps, but the project was not quite completed. Any efforts along these lines are certainly welcome.

**Comment by ZjelcoP** [comment]
Agree documentation should preferably not be in forum posts. Currently looks very messy and disorganized taking you all over the web or in the case of Warclub being spread over many forums.

But redirecting traffic away from Warclub this way should IMO be prevented for the sake of coherence, user experience and well possible, disapproval by Mods. 

I assume you can have the Warclub display the static content (documentation) without actually sending you over to Github IO webpage? Thus the user still sees the Warclub environment and buttons. So for the user it seems to be in Warclub while actually living, being written and maintained on Github IO webpage, or it actually is copied to Warclub but that could be cumbersome.
Would seem like a nice solution to me until final merger of the 2 sites (definitely my preference as well)

Should the documentation be written in Markdown and can this in a later stage be embedded in any new website of the future? As that is it's final destination when merging. Or does the format/language need further definition?

**Comment by DanVanAtta** [comment]
To be a bit more direct, rules/documentation posts in forums is too damn scattered. And for better or worse we do have a github.io website. Wishing that to go away does not help, since it covers gaps which the warclub website DOES not cover. Before we had a website in sourceforge that served the same purpose as the github.io website, so it's not even the case that we had parity before. In addition it was even worse since we had docs in both forums, which already is not the right place for rules/docs.

**Comment by ron-murhammer** [comment]
So it seems like we are pretty much in agreement that long term we want 1 site (@ZjelcoP described the reasoning for this well) so just need to figure out how to make the 2 sister sites work for the short term.

In the short term, my thought is to treat the github.io page as the intro to TripleA and downloading it. Its kind of a bunch of static pages that link to other areas and give an overview of the game. Essentially convince people to download it and then link them to warclub.

Warclub we will use for the forum and ladder/tournaments. This for now will kind of the the hub for the community.

For documentation we have 3 areas that each should be used appropriately:
1. github - use wiki for anything related to developers, code, builds, technical, etc
2. github.io pages site - anything related to introducing TripleA, downloading, installing, overview, links, etc
3. warclub - we will pin forum posts for information that players/mods/etc need to know and try to keep these well organized and up to date (development roadmap, bot management, lobby rules, etc)

**Comment by DanVanAtta** [comment]
Some quick comments, for 1 - github, I've found the wiki to not be a very good place for docs. It gets convoluted easily and hard to navigate, a series of README pages works better. For example, the maps project has a pretty effective readme IMO that links to sub-readmes in different folders for more in-depth details per topic. This level of organization is difficult / not possible with wiki.

For 3. IMO anything that is pinned probably should be a static document page unless it is temporary in nature. For example, a post advertising a tourney should be a pinned topic. A post requesting help or volunteers is a good pin. A post that explains what the rules are I do not think is a good one. We could pin a topic that links to all the various rules, but pinning the full set of rules I do not think is a good move. Perhaps we are actually in agreement with 3, I'm a bit unsure if that is what you also had in mind @ron-murhammer

**Comment by ron-murhammer** [comment]
@DanVanAtta Alright I'm good with README pages rather than wiki though would like to choose one and consolidate as we have some in each location currently. During the 1.9 release, I'd like to make sure we update release instructions and have it documented reasonably so that if the 2 of us disappear tomorrow others could take over.

I think we are mostly on the same page. My concern is I want to avoid having folks have to swap back and forth between the 3 locations. After you are a regular user (downloaded and play the game) and aren't either a developer or mapmaker then we really should be pushing people to warclub.  If it is a large portion of static content that is gonna live for a while then maybe putting it on github.io and linking to it makes sense (thinking having a single pinned post that includes links to the most important static github.io pages). Kind of treating github.io pages as almost a document repository for large portions of static content that we just link to from the forums as its much easier to edit/mange it there.

**Comment by williamdekryger** [comment]
One of the big issues we have right now is the sheer number of sites we are trying to run, which causes much confusion to our users (including me, as recently as a few months ago). Let's try to be sure that our final product uses a similar design and branding to give the user the sense not of going between sites, which is confusing, but of staying within the same site.

I think getting the domain name up is imperative for getting this effect. I am willing to try once more to point the domain name to the Github site if I am given the proper credentials. Then, I can also get up a subdomain, maybe forum.triplea-game.org for the forum. @DanVanAtta could we try this again?

**Comment by DanVanAtta** [comment]
Invite for domain has been resent to you @williamdekryger  Though, be aware, warclub is more than just a forum - but there is also the warclub ladder.  So it's not just a matter of migrating a forum.

**Comment by williamdekryger** [comment]
True. Even with the current warclub, though, a redesign may be in order to bring it in line with the website, or vice-versa.

**Comment by williamdekryger** [comment]
Alright, here's my 2 cents, after a discussion with @DanVanAtta. The warclub, for all its active community, has no TripleA logo in the header, outdated links on the homepage, and some very small text to read, especially within the forum. The design of the website is very simplistic, but there is little confusion as to what the user should do, and the design (in my opinion) contributes a lot to the TripleA brand. Therefore, I vote we restyle the warclub to match the website, or even choose a compromise design over switching the website to the warclub design.

I'd be willing to try to accomplish this myself, but I don't think it would be wise, as we are already looking for another forum solution in #1067. Let's wait until we have the new forum software in place, then I'll write some CSS to properly style it to match the website, maybe at the address of warclub.triplea-game.org. The lobby/ladder could potentially remain in place, if this is possible. This is the best use of all of our time, and a potentially preferable end result.

Those are my thoughts. If this is not feasible, let's discuss other options.

**Comment by DanVanAtta** [comment]
For follow up: https://github.com/triplea-game/triplea/issues/1067
