### ISSUE TITLE
Banned Players Unable to Download Maps

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#11014]
With map download (listing) requests going to the server now, and any request to the server checking if the given player is banned - if a player is banned then their request to download the map listing would fail.

Is this just deserts, or something that we should avoid?

**Comment by TheDog-GH** [comment]
Just because they have been banned from multi-player or the forums I think they should still be allowed to download maps, if that is easy to do.

**Comment by panther2** [comment]
@DanVanAtta Are you addressing something lobby-specific?

I mean everybody can still download and install a vanilla TripleA and then download any map without being registered anywhere? Isn't it?

In case things have changed here in general it would be really helpful to know about that - otherwise it will become difficult to give any end user support.

**Comment by Cernelius** [comment]
I think it is quite obvious people should never be banned from downloading maps... Moreover, people ma be wrongfully or mistakenly banned, and it is disputable whether or not a ban should have been given.

The only edge case I see is (as we had occurrences in the past) users who ask to be banned in order to save themselves from a TripleA addiction, even though this is not covered under TripleA rules.

---

However, I assume everyone (also permanently banned users) will always be able to get and play whatever maps they want from "github.com" by doing so manually with a browser.

So (as much obvious as this may be) I suggest to change the title to say that they are unable to download maps via TripleA only. Meaning editing the title to "Banned Players Unable to Download Maps via the TripleA Program".

---

I think this should be labelled as "problem", yet I think TripleA can be released without fixing this problem, but only as long as documentation is made available on the forum to explain how to download and install maps from GitHub if you are banned from TripleA.

**Comment by DanVanAtta** [comment]
@panther2  is the OP not quite clear? A big difference in 2.6 is that the map download listing is coming from the server and not just a static file somewhere.

**Comment by DanVanAtta** [comment]
I'm most interested in the question whether we care about this problem enough to fix it - or if we just consider banned players as persona non-grata, in which case, tough.

**Comment by TheDog-GH** [comment]
Im for tough, as long as we give the banned person a message of some sort with a url to be able to download the maps manually.

**Comment by panther2** [comment]
@DanVanAtta 
> @panther2 is the OP not quite clear? A big difference in 2.6 is that the map download listing is coming from the server and not just a static file somewhere.

I wouldn't have asked if it was clear to me.  Would you mind answering my questions? In the end it will be me who helps end-users troubleshoot problems with the new release on the forums. 

So a new user after installing a vanilla TripleA needs to be registered somewhere (and not banned, either) to be able to donwload and install maps?

**Comment by panther2** [comment]
> ?
> 
> Currently, there's no need to have an account to join the lobby. Did I miss something that now registration will be obligatory to join the lobby (and download maps)?

That is exactly my question. How can a "banned user" (banned from what?) be unable to download maps if there isn't a sort of account-verification behind it? That is why I asked if this issue is something lobby-specific.

**Comment by DanVanAtta** [comment]
> I mean everybody can still download and install a vanilla TripleA and then download any map without being registered anywhere?

Yes, anyone can still download and install vanilla TripleA and download maps without being registered anywhere.

> How can a "banned user" (banned from what?) be unable to download maps if there isn't a sort of account-verification behind it?

The ban criteria is a 'system-id' and 'ip' address, it does not matter if you are "registered" or not. Any request to the server contains these and we checked them regardless of which functionality from the server you are requesting. Any request the server receives, the first thing it checks is if you are banned. This is not only for just malicious lobby users, but is also helpful if someone is also attacking the server. The concept of registration is very much independent here. The fact though that we check all requests to the server automatically is a new implication for 2.6 where requests to get the map listing for download goes through the server now (and hence newly subjects users wanting a download listing to a 'ban' check)
