### ISSUE TITLE
Request to be a map admin like Roger

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#11017]
@DanVanAtta 
Please could I be made a map admin like Roger as I have 4 maps, soon 5 maps to upload to GitHub and its slow work.

Also I will be doing the map tags for 2.6 soon, so I will probably need similar access to the request above.

Thanks in advance.

**Comment by DanVanAtta** [comment]
The admins are more there to help maintain the existing maps rather than make it easier to add new maps. Be what it may, I don't object, and making it easier to add new maps is an unexpected (but worthy) objective too.

You should have an invite in your email @TheDog-GH 
There are some ways to make it easier to upload maps. You can 'initialize' a git repository in any folder on your folder system. Once you've done that, check in all the files and then you can push to the github repositories. Some googling will be needed, but do ask questions/points if you give it a try and get stuck.
