### ISSUE TITLE
Savegame File Creation broken with current Pre-release

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#11056]
### Reproduction Steps
Start a PBF game, do a test post, post a turn summary.
You will see that no file is created but a link to a "Null Page" instead.

### Attach a Save Game
See:
https://www.axisandallies.org/forums/post/1606174
https://www.axisandallies.org/forums/post/1606175

### Engine Version
2.6+14142

The problem occurs on the above mentioned forum (see links), that currently runs on NodeBB 1.19.1.
It works fine on forums.triplea-game.org that currently still runs on NodeBB 1.16.2.

It looks like the issue has already started at least back in March 22 with another 2.6-pre-release. 
See for example:
https://www.axisandallies.org/forums/post/1585098

Here @ron-murhammer posted savegames that lead to a "null" , for example https://www.axisandallies.org/forums/topic/20781/panther-s-triplea-pre-release-test-thread/null

It hasn't been noticed before as almost everybody uses the current "stable" for PBF working around all the related issues.

**Comment by panther2** [comment]
@ron-murhammer @RoiEXLab @djensen47 

Any ideas?

**Comment by RoiEXLab** [comment]
@panther2 I haven't been able to keep up with the latest development. But from the issue you describe it looks like the link it's generating for the file is just "null", thus the weird null page because the browser think it's a link instead of a wrong value.
This is what the current code looks like:
https://github.com/triplea-game/triplea/blob/0a52eb2a9fc6913a924313a619e611f3cc974ab5/game-app/game-core/src/main/java/games/strategy/engine/posted/game/pbf/NodeBbForumPoster.java#L155-L167

The only way the link can be "null" is when the request is successful (i. e. the savegame has been successfully uploaded, or the server at least pretends it was), but the server does not use the same format as before to report back the URL. It does not look like the folks at NodeBB changed the format or something (https://github.com/NodeBB/NodeBB/blob/5dbcfef91fcf2f0923f1e350827de5343e6fb6fa/src/controllers/uploads.js has not been changed since march and there doesn't seem a commit that changes anything in the direction).
I won't have the time to have an in-depth look at this problem for the next 3 weeks (unlucky timing, 2 weeks ago I would've had a couple of days to spare).

If this is an important issue to you @panther2 and you are able to acquire an API token for the forum (I forgot how it works, but the class https://github.com/triplea-game/triplea/blob/0a52eb2a9fc6913a924313a619e611f3cc974ab5/game-app/game-core/src/main/java/games/strategy/engine/posted/game/pbf/NodeBbTokenGenerator.java does it, Ctrl+ F for `forumUrl + `) and you know how to use `curl` or some other HTTP client you might be able to work out the differences between our forum and the a&a forum.
Once we know what the actual difference is we can either open an issue over at NodeBB to report a bug (if it's just missing) or fix it ourselves once we know it's just the spelling that changed or something.

Alternatively you might be able to try this branch I just hacked together:
https://github.com/triplea-game/triplea/tree/RoiEXLab-patch-1

If you clone it/check it out locally and run `.\gradlew run` in the console it should print the server response in the console when trying to upload the savegame. If you post the results here that would help too, at least I hope it does, haven't tested it obviously.

**Comment by panther2** [comment]
Thanks a lot, @RoiEXLab , for your explanation and ideas and even a first patch, codewise.

The issue is not only important for me but for the entire PBF-community, that has been sufferering from PBF/NoteBB incompatibilities for quite a long time now. Everbody hoped for a new release that would potentially solve the issue. But now we seem to have a new unresolved issue.

Unfortunately your ideas how I could deal with the issue are exceeding  my IT knowledge, so I don't know how to execute your first idea neither the alternative. 

However I will contact @djensen47 and point him to your post, I am sure he knows better how to deal with it.

Thank you again.

**Comment by RoiEXLab** [comment]
@panther2 I created #11092 which has a fix for this
