### ISSUE TITLE
Severely Slow Parsing of map XML (War of the Relics)

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1128]
"War of the Relics" is a massive XML file. 

```
    530 ./minimap/map/games/minimap.xml
     531 ./Project/MapMakingTools/map_making_tutorial/games/Test1.xml
:
:
   26525 ./greyhawk_wars/map/games/Greyhawk_Wars.xml
   28655 ./empire/map/games/Empire.xml
   33214 ./total_world_war/map/games/Total_World_War_Dec1941.xml
   40286 ./blue_vs_gray/map/games/blue_vs_gray.xml
> 88809 ./war_of_the_relics/map/games/war_of_the_relics.xml  <
```

When it is loaded, it takes a long time, about 30s, sometimes up to a minute. During this time there is no feedback the user, and the game appears frozen/crashed.

If war of the relics is the selected map, then the freeze will happen on start up. If the map is downloaded then there is a pause when opening the select game screen.

Since there is no way to tell what is causing the slow down, this is a particularly devious problem. 

At most simple removing the map from the DL list will buy some time while we best determine how to solve this issue. 

Looking at the performance, the time is spent doing iterations on the XML data, and just becomes inefficient with a lot of loops/iterations.

**Comment by DanVanAtta** [comment]
Now that   "disable war of the relics download pending parsing performance fix triplea-maps/Project#52" is merged, removing 'next release' label.

**Comment by Cernelius** [comment]
I think there is nothing wrong with this cool map and I don't see why it should be removed from DL list. I just suggest updating the DL description as to make very clear that this map is going to be very slow, as a clear warning to anyone about to download it.
Whatever can be done to highlight that the map is loading would be good.
I want also to make you notice that it is totally possible to make heavier maps than War of the Relics, that will take several minutes to load.
Also, I want to make you notice that War of the Relics takes 30 seconds to load, but if you load it from a savegame, it takes only about 2 seconds.
Myself I made such heavy maps that it took over 10 minutes to load them, yet if you loaded them from a savegame they took only a few seconds.
So, if you somehow manage to have the xml load be as fast as the savegame load, you have fully solved this problem for about all possible cases (because I can tell the savegame loads fast even in case of incredibly big xml).

Anyway, the fact that TripleA doesn't tell you if a map is loading or the game is frozen is a problem of the engine, not a problem of the map, so it should be solved in the engine, if anyone wants to solve it, not by removing the map from DL list for sure (if is not a fault of the mapmaker!).

**Comment by Cernelius** [comment]
I'm also very perplexed about this tendency to simply outright remove a map from DL list just because it takes 30 seconds to load, which is not anything that bad (think about the time you use to play a game!). If a map is cool, I would gladly wait 30 seconds or more to play it! But, yes, the user should be informed that the map is loading and he just has to wait.
Again, it is totally possible having maps that need more than 1 minute to load. I don't see why such maps should be forbidden; just the user should be informed that this is a very heavy and slow game, that will make TripleA slow to start when preselected, in the description where he downloads it.
This is a cool map that clearly had a lot of work put in it and I think you should not just remove it because it takes 30 second to load! Just clearly inform the users about the drawbacks and let them decide if they want to have it or not; this is the most open way to do it, let the people decide if they want to wait those 30 second or whatever or not.

**Comment by DanVanAtta** [comment]
The problem is not that the game takes 30 seconds to load, but the select game screen takes 30 seconds. IE, if:
- someone downloads all maps
- they then click "select game", the select game window takes 30-60 seconds to open.
- there is no way to know which map caused the delay, or even that it was a map. Likely they will be stuck deleting all maps and will then have to be careful about which ones to download.

The map can still be obtained from the repo's. There is a bar for allowing in-game download, and that is the game engine must not spiral out of control. This ticket is to track the need to improve  game engine parsing performance for that map.

**Comment by DanVanAtta** [comment]
"I think there is nothing wrong with this cool map and I don't see why it should be removed from DL list."

There is nothing worng with the map, the game engine does not handle it efficiently. Please experiment around with downloading the map, loading it, playing it, then restart the game and repeat once.  If you did not know that it was this map causing problems, you'd think the game engine was completely broken (which it is when it comes to this map). I'm not going to repeat myself, the removal from DL is to protect the use case stated above.

**Comment by DanVanAtta** [comment]
Summarizing, task in this ticket is to look at how we can update either the game engine or the map to parse efficiently. Alternatively put this map in a different download selection so that it is not picked up when doing a select all install.

**Comment by DanVanAtta** [comment]
This is being adequately tracked in #979, closing this issue in favor of that #979

**Comment by Cernelius** [comment]
> The problem is not that the game takes 30 seconds to load, but the select game screen takes 30 seconds. IE, if:
> 
> someone downloads all maps
> they then click "select game", the select game window takes 30-60 seconds to open.
> there is no way to know which map caused the delay, or even that it was a map. Likely they will be stuck deleting all maps and will then have to be careful about which ones to download.

No it is not. You must have "Parse Selected" enabled, which is your choice (I hope it is not default), and force you to parse War of the Relics each time you click "select game", which is your choice.
As long as "Enable/Disable Delayed Parsing of Game XML's" is set as "Parse Selected", there is close to no delay at all.
**"Parse Selected" must be, of course, the default setting, if it is not already** (definitively "Parse All" is an option that a normal user should never select, as it has no value for them; so, you should not even consider this possibility), and, as long as it is, this map causes no relevant problems at all: people will have to wait only if they want to select it specifically, and I'm pretty sure they will realise it is that map only being slow to load, and they can just decide to select something else and never select it again, if they can't stand waiting 30 seconds.

> Alternatively put this map in a different download selection so that it is not picked up when doing a select all install.

I agree, there should be a separate DL section for maps with known issues, as well as each issue being explained in the description, and War of the Relics should stay there. Outrightly remove it from DL list would be something very close to just remove it, as almost noone will get to know about it, I'm sure you realise this.
But again, if you take a look at the time required to load a savegame of War of the Relics, it is nothing; thus if it would be possible to have the xml loading as fast as the savegames, the issue would not exist.

I'm still very perplexed of this tendency to so easily remove a cool and innovative (definitively quality) game from DL list, especially since, as long as you have "Parse Selected" enabled, noone will notice any slow down related to this map, until they decide to specifically select it. So, I don't even see the problem, really, unless "Parse All" is the current default and, if it is, I definitively advise being not, obviously.

Side note, all Engine Preferences settings should spell out which is the default (there is no way you can know if the default is "Parse Selected" or "Parse All", looking at the current description, and I just guess it is "Parse Selected" as having "Parse All" as default would make no sense) and, of course, the default should be what fits for regular users (that don't want to test if all maps are valid each time they click on Select Game). Also a general button for resetting all Engine Preferences to their defaults would be cool.

Also, maybe a mail should be sent to the mapmaker, informing him his map has been removed from download list. Of course, this is just a plus, and I'm not saying you have to do it.
