### ISSUE TITLE
Pre-Release Problem Objectives Tab Disappears

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#11305]
### Reproduction Steps

1.Starting with 2.6+31d2c60 the objectives tab disappears when you turn on History
2.When you exit history objectives tab does not reappear
3.

### Engine Version

Engine Version:

### Is there anything else we should know?

https://github.com/triplea-game/triplea/releases/tag/2.6%2B31d2c60

Before
![Screenshot from 2022-12-23 12-52-01](https://user-images.githubusercontent.com/24382682/209395261-24121167-f707-4e18-8216-74450341b691.png)

After
![Screenshot from 2022-12-23 12-52-25](https://user-images.githubusercontent.com/24382682/209395138-fc580fec-488c-454c-a51b-d3d08bd20cf0.png)

**Comment by beelee1** [comment]
To clarify it works correctly with the one before https://github.com/triplea-game/triplea/releases/tag/2.6%2B2c9a940

**Comment by DanVanAtta** [comment]
Hmm. That is interesting it appears #10844 has an impact considering that is all build related and nothing logic related. But it does give a place in the history to look.

I'll assign this to myself for further investigation, but others should feel free to comment & jump in if they can.

**Comment by asvitkine** [comment]
I think the bisection is incorrect here, in part due to the problem that the naming scheme for prereleases caused ordering to not match.

So specifically, https://github.com/triplea-game/triplea/releases/tag/2.6%2B31d2c60 and https://github.com/triplea-game/triplea/releases/tag/2.6%2B2c9a940 are not adjacent.

We can actually see the commit before https://github.com/triplea-game/triplea/releases/tag/2.6%2B31d2c60 by clicking on 'parent' here:
https://github.com/triplea-game/triplea/commit/31d2c601fb67f77d8f13eb9b482e32c88461ae3c

So it goes:
https://github.com/triplea-game/triplea/commit/31d2c601fb67f77d8f13eb9b482e32c88461ae3c (2.6+31d2c60)
https://github.com/triplea-game/triplea/commit/10235e4acf639e8c895962143359319795f22b1d
https://github.com/triplea-game/triplea/commit/a856aebe2ad479cbce8c1633d8fc4f939b971d29
https://github.com/triplea-game/triplea/commit/cb08884343e4ab7ae46feb1580d7155d148e5683
https://github.com/triplea-game/triplea/commit/f2987c937e66d8cdd7ab5a02f20140ae20930463
https://github.com/triplea-game/triplea/commit/4522c907d9b7dcd3a94d297a17b63b8cd0f76a69
https://github.com/triplea-game/triplea/commit/4c711365f53b59d58ed346fcceb35f4897faf4aa
https://github.com/triplea-game/triplea/commit/2c9a9400c54afee5c6389de15767d7972730bffc
https://github.com/triplea-game/triplea/commit/139d8e8d248bc0cfc872823734f4aab3adf32faa (2.6+2c9a940)

**Comment by asvitkine** [comment]
https://github.com/triplea-game/triplea/commit/4522c907d9b7dcd3a94d297a17b63b8cd0f76a69 looks like it could be related.

**Comment by asvitkine** [comment]
Indeed it's that change and I see this issue. Preparing a fix.

**Comment by beelee1** [comment]
@asvitkine you've been busy :) well done :+1: This was the main thing preventing me from using the prerelease. I will update my posts at A&A.org to reflect this
