### ISSUE TITLE
Landing on a newly placed carrier with Combat Move before purchase

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1184]
If combat move is moved to before purchase, Triple A won't know that there might be a newly built carrier which would be a valid landing spot. If there are no other landing spots, Triple A won't allow the move. How would we move the combat move before purchase while still allowing this? Edit mode, or is there a better way?

**Comment by Cernelius** [comment]
I actually dislike that you can make combat moves possible only because you are building a new carrier, since it is so unrealistic. TripleA never got a really decently sensible set of rules for fighter and carrier placement, through the various rulesets. I actually think that this limit would be an improvement, if intended.
You can have 2 combat move phases, one before and one after the purchase; that solves this problem, but may confuse people.

**Comment by DanVanAtta** [comment]
IF you make a move that requires a carrier, force the purchase once the move is completed. IE: prompt user, if confirmed, then in the purchase screen, the PUs will already be subtracted for a carrier, and one will already appear as purchased.

**Comment by simon33-2** [comment]
That's probably a good option.

**Comment by Cernelius** [comment]
Probably better first creating a new phase having both move and purchase in the same (which is good also for a lot of other things), then have the validation dependent on having the carriers selected for purchase and forbidding de-purchasing them without first undoing the validated move (like now when you can't undo a move dependent on another one made beforehand), leaving the regular move and purchase phases alone, as still usable alternatives to this added move+purchase new phase.

**Comment by DanVanAtta** [comment]
@simon33-2 any remaining questions on this one?

**Comment by simon33-2** [comment]
I guess not.
