### ISSUE TITLE
Upgrading to 1.9 maps

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1190]
Need a doc page, for now gathering info for it.

Upgrade script (assumes no spaces in file names):

```
find . -name "*xml"  -type f 2> /dev/null | xargs sed -i 's/occupiedTerrOf/originalOwner/'
find . -name "*xml"  -type f 2> /dev/null | xargs sed -i 's/ictoryCity" value="false"/ictoryCity" value="0"/'
find . -name "*xml"  -type f 2> /dev/null | xargs sed -i 's/ictoryCity" value="true"/ictoryCity" value="1"/'
find . -name "*xml"  -type f 2> /dev/null | xargs sed -i 's/isTwoHit" value="false"/hitPoints" value="1"/'
find . -name "*xml"  -type f 2> /dev/null | xargs sed -i 's/isTwoHit" value="true"/hitPoints" value="2"/'
find . -name "*xml"  -type f 2> /dev/null | xargs sed -i '/option name="giveUnitControl" value="true/d'
find . -name "*xml"  -type f 2> /dev/null | xargs sed -i '/option name="giveUnitControl" value="true/d'
find . -name "*xml"  -type f 2> /dev/null | xargs sed -i '/option name="takeUnitControl" value="true/d'
find . -name "*xml"  -type f 2> /dev/null | xargs sed -i '/option name="takeUnitControl" value="false/d'
find . -name "*xml" -type f -or -name "*java" -type f 2> /dev/null | xargs sed -i 's/Units repair at end of round/Units Repair Hits End Turn/'
find . -name "*xml" -type f -or -name "*java" -type f 2> /dev/null | xargs sed -i 's/Units repair at beginning of round/Units Repair Hits Start Turn/'
find . -name "*xml" -type f -or -name "*java" -type f 2> /dev/null | xargs sed -i 's/isParatroop/isAirTransportable/'
find . -name "*xml" -type f -or -name "*java" -type f 2> /dev/null | xargs sed -i 's/isMechanized/isInfantry/'
find . -name "*xml" -type f -or -name "*java" -type f 2> /dev/null | xargs sed -i 's/conditionType" value="XOR/conditionType" value="1/'
find . -name "*xml"  -type f 2> /dev/null | xargs sed -i 's/option name="turns"/option name="rounds"/'
find . -name "*xml"  -type f 2> /dev/null | xargs sed -i 's/passible/passable/g'
find . -name "*xml"  -type f 2> /dev/null | xargs sed -i 's/OccupiedTerrOf/originalOwner/g'
```

**Comment by Cernelius** [comment]
Need a doc page for upgrading to 1.9 maps?

I think it should be advisable making a Wiki, explaining how to manually upgrade maps from 1.8.0.9 to 1.9 or downgrade them from 1.9 to 1.8.0.9, using nothing else but a basic text editor.

If this is the aim of this issue, I can see if I can do this, if told exactly where to; or I can write it down here, and then you paste wherever.

**Comment by DanVanAtta** [comment]
Thanks for the offer @Cernelius
I think the wiki is world-writable: https://github.com/triplea-game/triplea/wiki

This issue is mainly a convenient place to keep the script for the conversion. The above script does not handle spaces in file names regrettably.

I don't see the use case for 1.9 to 1.8.0.9,  :shrug:

The conversions can be deciphered from the abovee:
```
find . -name "*xml" -type f -or -name "*java" -type f 2> /dev/null | xargs sed -i 's/isMechanized/isInfantry/'
```
That says, loop over all files ending in "xml", and swap "isMechanized" with "isInfantry"

**Comment by Cernelius** [comment]
It is advisable to try to assure catching the code stuff only (not comments or notes, that should be specifically changed, not mass changed, except only old changelogs, than should normally never be changed), in the changes, especially since here the common user case is opening the xml etc. with notepad and simply mass change one with the other.

For example, instead of mass changing:
"Battleships repair at beginning of round":"Units Repair Hits Start Turn"

it is definitively better mass changing:
**property name="Battleships repair at beginning of round":property name="Units Repair Hits Start Turn"**

Generally, mass changes are better being about as much detailed as possible, as long as they are going to change what they should in all cases.

For example, if you just mass change "Battleships repair at beginning of round" to "Units Repair Hits Start Turn", then you will also change the mention of it in the Veqryn old changelog section, which should not happen.
(it should stay "Battleships repair at beginning of round" there, and, then, you should optionally add a new changelog section in which you either explain the new changes or just write down "Converted up to TripleA 1.9.".

So, this would be the way I will write the instructions to do the mass changes, which should be better being before the release, but has to be done after I'm done with the WAW update.

For testing, can you indicate me a minimum number of maps that have undergone all changes (the best would be 1 single map that has undergone all changes, but I guess there is not such a thing).

**Comment by DanVanAtta** [comment]
Wow. Good example of why having the change log bundled in with the XML file is not a good idea. We've really made a simple task difficult.

**Comment by DanVanAtta** [comment]
@Cernelius , if you would like to clean up the OP text to be more straight forward, that would be helpful. It should be pretty short and sweet though. There was a problem where all the upgrades were getting scattered across different issues/PRs, was getting hard to track.

Also, should be a mention to *not* use notepad. It introduces silent new characters all throughout the file when you use it. Sublime Text or just about any other reasonable text editor is a good alternative.

**Comment by Cernelius** [comment]
Looks like you didn't delete:

option name="giveUnitControl" value="false

anyway, chances are no maps have that.

I'll let you explain why notepad is bad, because only thing I understand is that it can't read the GitHub texts endlines. Probably it should be done in a different section, about generally editing xml, tho.
But I'm curious: **if I produce a text with notepad, and upload it in GitHub, will GitHub convert the endlines to the ones used in GitHub, or will it just remove them all, leaving everything on a single line?**
I do believe the consequences of factoring texts with NotePad for uploading in GitHub should be fully explained, because I surmise that is the most popular text editor.

**Comment by DanVanAtta** [comment]
> " because only thing I understand is that it can't read the GitHub texts endlines"

Not quite. Notepad auto-inserts hidden and unnecessary characters to every line ending without prompting you.

> if I produce a text with notepad, and upload it in GitHub, will GitHub convert the endlines to the ones used in GitHub, or will it just remove them all, leaving everything on a single line?

Notepad is the only thing that is converting file endings. There are though some github client configurations you can use to auto-insert and auto-remove windows line endings. Easiest thing is to avoid notepad where possible. End of the day it's not that big of a deal.

**Comment by Cernelius** [comment]
I intend to get around doing this very soon.

**Comment by Cernelius** [comment]
find . -name "*xml" -type f -or -name "*java" -type f 2> /dev/null | xargs sed -i 's/isAirTransportableers/isAirTransportable/'

I was not aware of this. Did it exist an option called "isAirTransportableers"? Should we have an info the like of:
isAirTransportableers->isAirTransportable

And, of course, the old version will be "Battleships repair", not "Units repair".

**Comment by DanVanAtta** [comment]
That is just a typo in the update script. It should not have found any instance of `isAirTransportableers`, and so should have no effect.

Note the syntax of:
`s/isAirTransportableers/isAirTransportable/'`

Means effectively : `substitute: "isAirTransportableers" with "isAirTransportable"`

**Comment by Cernelius** [comment]
Can you also verify that no unitAttachment of the repository xml currently have multiple occurrence of:

```
name="isInfantry"
name="isAirTransportable"
```

For example, you could have had, inside a single unitAttachment:

```
<option name="isInfantry" value="true"/>
<option name="isMechanized" value="false"/>
```

And now you might have:

```
<option name="isInfantry" value="true"/>
<option name="isInfantry" value="false"/>
```

In this case, it should be reduced to:

```
<option name="isInfantry" value="true"/>
```

Meaning possibly check that the changes of these long disabled options didn't cause duplications of the same options in single attachments.

---

I'm also undecided whether we should suggest regular makers to do this:

**name="isParatroop":name="isAirTransportable"
name="isMechanized":name="isInfantry"**

or this

**name="isParatroop":
name="isMechanized":**

Meaning changing these disabled options to the closest supported ones or just deleting them. I believe the second solution (deleting) is the correct one.
They are currently doing nothing, thus deleting them would be the most correct way to go, by default, preserving the current (absence of) functionalities.
I just suggested them to be changed to the closest supported option, for the maps in the TripleA repository, to somewhat preserve the underlying info in the likely very long time abandoned maps having them.
On the other hand, I believe that, in perspective of updating from 1.8.0.9 to 1.9.0.1 (not from some older version), it would be coherent the most to just suggesting deleting all already disabled options.
Thus, I'm oriented for suggesting deleting all the options of any "isParatroop" and "isMechanized", because changing them like we did would not be strictly an update from 1.8.0.9, but a factual change of functionalities.

**Comment by Cernelius** [comment]
Is it possible to create sub-pages? How do I do that?

I would like to create a:

**Upgrade/Downgrade Maps Information**

page, that drops down into two:

**Upgrade Maps from 1.8.0.9 to 1.9.0.1
Downgrade Maps from 1.9.0.1 to 1.8.0.9**

Aside from this, I've all about ready.

**Comment by Cernelius** [comment]
Meaning that, then, in the future, more sub-pages can be added, eventually, without having too many main pages in the wiki, but just the
**Upgrade/Downgrade Maps Information**

**Comment by DanVanAtta** [comment]
1.9.0.0.3199 is stable release. Version numbers are listed here: https://github.com/triplea-game/triplea/blob/master/docs/admin/version_numbers.md#future-version-numbers

We are falling behind on chopping off zero's, if were diligent this would be 1.9.3199, but at this point the focus is elsewhere and more in releasing.

**Comment by DanVanAtta** [comment]
Downgrade sounds like a bad idea and wasted effort. I hope we can clear out the 1.8.0.9 lobby, 1.9 is out.

**Comment by Cernelius** [comment]
Why calling it 1.9.0.0.3199 instead of 1.9.0.1? This has always been the tradition, and it is easier to refer to releases that way, instead of having a whole bunch of numbers.
Also, I guess Veqryn informed you about this, odd numbers are stable and even numbers are unstable, in the fourth digit, traditionally.

However, does this mean that drop down are not possible?

If so, do you think it is better calling it "**Upgrade Maps Information**" or "**Upgrade Maps Information 1.8.0.9-1.9.0.0.3199**"?

Meaning, should future upgrade information being added up to that same page, or a page being made for each upgrade?

I will make a separate page for the downgrade instructions, under the same criteria as the upgrade ones.

**Comment by Cernelius** [comment]
Ok, I'm reading the background post about version numbers; it's not very clear.

**Comment by Cernelius** [comment]
Well, just tell me exactly what the next release number will be, if not 1.9.0.0.3199.

**Comment by Cernelius** [comment]
Ok I see the tradition of odd and even is kept and from what I read I still actually understand that it will be called **1.9.0.1** as I said?

**Comment by Cernelius** [comment]
It seems to me there are some problems at:

https://github.com/triplea-game/triplea/blob/master/docs/admin/version_numbers.md#future-version-numbers

The description says:

> The TripleA Version number looks like “X.X.X.X”, such as “1.6.1.5” or “1.8.0.5”. The numbers are called, in order: major.minor.point.micro
> If we bump any number except for ‘micro’, then all savegames from the previous version will be incompatible with the new version. However, if we only bump the ‘micro’, then triplea will attempt to load savegames from any other version of triplea that has the same major.minor.point numbers.

But then the list says, instead:

> 1.9.1(.0) = next release still compatible with 1.9.0 save games
> 1.9.1(.build) = first development build after 1.9.1.0

While, according to the description, something called 1.9.1 should be not compatible with something called 1.9.0.
So depending if "chopping off" the zero is going to be made for this release or not, either the description or the list should be changed.
Also, people should not be required digging into the issue to try to understand (I guess the description is obsolete, while the list is correct but unclear).
Also, all occurrences of triplea I guess should be changed to TripleA.
Just simply tell me how the next release will be exactly officially called. Will "1.9.0.0.3199" be the actual name?

**Comment by Cernelius** [comment]
From the list alone (that should be the updated part of the info), what I tend to understand is that the next release will be called:

**1.9.1.0**

Even tho it would be not actually true that "_next release still compatible with 1.9.0 save games_", with reference to the earliest 1.9 ones.

while we are currently at this stage:

> 1.9.0(.build) = first development release after 1.9.0(.0)

?

**Comment by Cernelius** [comment]
Ah, nevermind... I see that you have officially released it:
http://tripleadev.1671093.n2.nabble.com/TripleaA-1-9-Release-tp7593849.html;cid=1476545077822-708

So it is called:

**1.9.0.0.3266**

**Comment by Cernelius** [comment]
Now the Wiki has two new pages, for upgrading and downgrading to and from 1.8.0.9 and 1.9.0.1.
As, you can see, I've made them quite highly detailed, yet in some case I've reduced the level of detail (like just changing from "="turns"", instead of from "option name="turns""), to have a high chance to target the code only (not comments or notes). The reason for this is like if you just change:
"turns":"rounds"
then this might change a "turns" in Notes etc., in which you were just talking about actual turns or whatever, and should not be subjected to autochanges; thus the suggested autochange is, instead:
="turns":="rounds"
which should target only the code we want to change (it is still possible that it will change custom codes like custom properties called exactly that way, but very unlikely).
In case the value or the count was changed, not just the name, I've listed all changed code starting after the name.
However, this implies that it is also needed to list like:
value="conditionType" count="XOR":value="conditionType" count="1"
value="conditionType" count="-reset-XOR":value="conditionType" count="-reset-1"
in case a game is changing that option with triggers (very rare) (in this case even just changing "="XOR"" would not be enough, since you may have the "-reset-" before).
Also for coherency, the same criteria has been followed in all cases, even tho many of them have names that are unlikely to be find outside the code.
For example, as said, I have simplified from this:
option name="turns":option name="rounds"
to this:
="turns":="rounds"
and, on the other hand, I've complexified from this:
passible:passable
to this:
="isImpassible":="isImpassable"
mainly for coherency, as said (but, in this case, for example, it would avoid that if someone has a word like "impassible" in notes, talking about something being actually impassible (very unlikely, I know), it won't get changed to "impassable").
Aside from advanced (and likely very rare) codes referring to already deprecated items, like having triggers changing the "victoryCity" values of territories during the game to or from "true" or "false", this should automatically cover all basic codes.
Like you could also have a trigger setting "isParatroop" true or false (totally useless). In such casese it will be up to the mapmaker to find such outdated triggers and delete them.
A special note has been made about the necessity of changing the property names, since those are not validated (so, if someone misses or fails to change them, the game will still play, albeit not correctly updated) (they must be not validated because you can have custom properties).

I've tested the above changes on "pact_of_steel_2.xml".

---

I don't know how to order the pages list; I suggest it being ordered this way:

**Home
Broken Maps
Upgrade Maps Information
Downgrade Maps Information
Feature Back Log**

---

Other than the items directly related to this issue, I've also specified the need of changing the sounds from "wav" to "mp3", and updating the related references accordingly.

---

If you recall there are any other changes, with the former being either unsopported or deprecated or whatever, I suggest all of them being listed toghether in these upgrade istructions.
Also, if you changed the name of some assets, that may need being told (for example, if you changed the name of some sounds in the main installation, this would break the sounds.properties code of maps directly calling them).

---

Side note, an autochange like:

find . -name "*xml"  -type f 2> /dev/null | xargs sed -i 's/option name="turns"/option name="rounds"/'

would miss changing a trigger modifying the "turns" value for a condition.
However, chances are that there are no such a things in any xml currently in the repository.
Such triggers are one of the best feature for mapmakers, greatly expanding mapmaking possibilities, yet rarely used, so a marginal matter to consider.

---

A thing not to include here, as not belonging to the engine, but related is that a lot of maps folders had their names changed; so, for example, people having mods of any of them must assure the value of property name="mapName" being equal to the new name of the basic folder.
For example:
="mapName" value="World War II v3":="mapName" value="world_war_ii_v3"
I'm not sure if and where that would be better for this to be noticed.

The typical user case is somebody having made a (likely external) mod of a map like "World War II v3", playing it in lobby, and ending up being unable to still play it, with the new release, even after properly updating, because he missed that the map name was changed over. It is likely that he will think that he the update was not correctly done, while, instead, it is simply the map he wants to play that now has a different name (so, this is a different matter than updating, and I believe should not be part of the updating info).

**Comment by Cernelius** [comment]
The new pages are here:

https://github.com/triplea-game/triplea/wiki/Upgrade-Maps-Information
https://github.com/triplea-game/triplea/wiki/Downgrade-Maps-Information

I believe now it is just needed to reorder the pages; I suggest this order:

**Home
Broken Maps
Upgrade Maps Information
Downgrade Maps Information
Feature Back Log**

And then this issue may be closed.

**Comment by Cernelius** [comment]
> 1.9.0.0.3199 is stable release.

Since it is "1.9.0.0.3266" at the link given inside:
http://tripleadev.1671093.n2.nabble.com/TripleaA-1-9-Release-td7593849.html;cid=1476549477776-919
I've called it so.
Change it to whatever is correct, in case.

**Comment by Cernelius** [comment]
I suggest running a search of all the GitHub xml to ascertain there are no such codes left anywhere:

`="Battleships repair at end of round"`
`="Battleships repair at beginning of round"`
`="Naval Bombard Casualties Return Fire Restricted"`

As explained here:
https://github.com/triplea-game/triplea/wiki/Upgrade-Maps-Information
The following xml codes, as being properties, are not validated (if you leave them, the game will play, but they will set nothing in the engine) (it is suggested you double check you don't have them anymore)

This would be to check there are no more cases like this:
https://github.com/triplea-game/triplea/issues/1306

After this, for me this issue can be closed.

**Comment by ron-murhammer** [comment]
@DanVanAtta Can you update your scripts to check for these:
="Battleships repair at end of round"
="Battleships repair at beginning of round"
="Naval Bombard Casualties Return Fire Restricted"

We found an instance in Big World that needed updated today and it would be good to make sure no other maps were missed.

**Comment by Cernelius** [comment]
In case it got lost, I want to point out again that I think a stickied Topic about the upgrades should have been made in Developer forum, upon releasing (the Wiki here is quite hidden).
