### ISSUE TITLE
TripleA-2.6+14530 Could not find step name - Error

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#12022]
TripleA-2.6+14530

Map 1941 Global Command Decision
https://drive.google.com/file/d/164EADrFgLICzAElsld3l5WewYarzHAzh/view?usp=sharing

Load
[G18-autosaveBeforeBattle.zip](https://github.com/triplea-game/triplea/files/12837877/G18-autosaveBeforeBattle.zip)
Play
Center on Battle in 091 A Sea Zone
![image](https://github.com/triplea-game/triplea/assets/71022517/5e09fd10-5127-47e1-9bea-ba40b1c1a9d7)
The button says Retreat to 091 A Sea Zone but the attacks are in 091 A, so cannot retreat, is this the reason for the error?

**Comment by asvitkine** [comment]
I don't think the retreat is related. If you retreat planes, they will "retreat" to the same territory where the combat happened. And you can move them out in non-combat after.

But I can take a look at the "Could not find step name" problem.

**Comment by asvitkine** [comment]
I think the issue here is that separate steps were created for fighters and bombers due to "inf-trained" being in the defenders list.
But when the combat actually runs, the engine doesn't consider "inf-trained" as "present" since they're just loaded on ships and not actually defending. So it generates a different list of steps.

So I think we need to fix the logic when creating the steps.
