### ISSUE TITLE
Unable to Play Big World Variations

### ISSUE THREAD

**Issue by RogerCooper** [triplea-game/triplea#1237]
When trying to run Nekhanet 1939 I get
triplea.engine.version.bin:1.9
Loading map: big_world_variations, from: C:\Users\Judy\triplea\downloadedMaps\big_world_variations-master.zip
Loading map: big_world_variations, from: C:\Users\Judy\triplea\downloadedMaps\big_world_variations-master.zip
java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.awt.EventQueue.invokeAndWait(Unknown Source)
	at javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
	at games.strategy.ui.SwingAction.invokeAndWait(SwingAction.java:63)
	at games.strategy.triplea.TripleA.startGame(TripleA.java:117)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:49)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$99(AbstractLauncher.java:43)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Error in resource loading. Unable to load expected resource: polygons.txt, the error is that either we did not find the correct path to load. Check the resource loader to make sure the map zip or dir was added. Failing that, the path in this error message should be available relative to the map folder, or relative to the root of the map zip

**Comment by RoiEXLab** [comment]
I believe this error is related to the Map itself, not to tripleA... I'd suggest creating an issue [here](https://github.com/triplea-maps/big_world_variations/issues/new)
@DanVanAtta Ideas on why this is happening?

**Comment by ron-murhammer** [comment]
@RogerCooper Does this map work on 1.8.0.9?

**Comment by DanVanAtta** [comment]
It would be quite the process gap if this did not work in 1.8.0.9.

Looks like this has more to do with the jenky way mods were coded up. I think removing "_variants" from the resource loading search path would be sufficient. I think what broke was before a magic naming convention was used to translate a variant map back to the original. 

Longer term, fixing the way mods are done would be a much better fix. Adding the XML and .properties files to the original maps seems like a good way to go. Saves all the confusion of map dependencies and the whole mod category (not to mention the hacky code that makes this work)

**Comment by DanVanAtta** [comment]
Hacking up the resource loading path further is not very fruitful. The 'variants' supporting code is really crufty stuff to begin with. It would be a lot simpler if mods were bundled with maps. There are not very many mods, I think that would be a good course of action until we can solve any of the original problems that motivated mods in a different  / better way.

**Comment by DanVanAtta** [comment]
Raising idea of dropping mod support altogether here: https://github.com/triplea-game/triplea/issues/1244, in favor of merging the mod maps in with the base maps so it woudl be just one download. It would make the game code much easier, and make the user documentation much nicer too since we wouldn't have ot endlessly explain what mods are and how to play them.

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah, my thoughts are actually go the other direction and make every map fully standalone. 1 map per download period (one game XML). Makes things much simpler and makes it more clear what you are downloading. The only major drawback of this duplication of files when downloading multiple maps based on the same core tiles.

**Comment by Cernelius** [comment]
@ron-murhammer Before going on with this conversation, can you confirm that you actually mean that, for example, you would create 5 "age_of_tribes" maps, one for each of these xml:

**Age_of_Tribes_Classical
Age_of_Tribes_Cold_War
Age_of_Tribes_Modern
Age_of_Tribes_Primeval
Age_of_Tribes_Renaissance**

Duplicating everything but the xml themselves in each one of the folders, obliging Frostion to update 5 different repositories every time he wants to make any skin-related changes?

As another example, would you want to split "world_war_ii_v3" into two different maps, one for the 41 and another one for the 42, plus making 1 stand alone map for each one of these xml:

**WW2v3-1941.xml
WW2v3-1942.xml
WW2v3-1941-3Teams.xml
WW2v3-1941-freetech.xml
WW2v3-1941CB4P.xml
WW2v3-1941FFA.xml
WW2v3-1941_ChinaMod.xml
WW2v3-1941_UKfactory.xml
WW2v3-1942CB4P.xml
WW2v3-1939-11N.xml
WW2v3-1940-11N.xml
WW2v3-1941-11N.xml
WW2v3-1942-11N.xml**

(yes, I believe they all deserve to be kept)

And do you also intend to multiply "world_war_ii_global" into 6 skin clones, one for each of these xml:

**ww2global40_2nd_edition.xml
ww2global40.xml
ww2global40_alpha3.xml
ww2global40_alpha3_veqryn_balanced.xml
ww2global40_balanced2_0.xml
ww2global40_veqryn_balanced.xml**

(yeah, keep them all; I've never seen anyone playing or even asking to play or even selecting any of the Veqryn's mods in lobby, but I surely believe they deserve to be kept, as well)

Also, do you have some plans for the mapskins, that you would need to multiply by the total number of mods currently available (for example, 3x2=6 NWO mapskins and 6x1=6 Global mapskins)? Or do you have plans for allowing a same mapskin referring to multiple original maps?

**To be absolutely sure, can you please confirm that this is indeed your current proposal?** Or are you thinking to just delete a lot of mods (I hope not)?

Just for info, this matters for me, as I intend to propose for upload 6 mods soon, currently info named:
270BC 40%
270BC 40% Rev
270BC Rev
Napoleonic Empires: 5 Alliance - 1794
WWIIv3 1941 Move-Buy-Move
WWIIv3 1941 Tech Advance

(270BC 40% is the successor of 270BC Tertiered I proposed for upload almost 1 year and a half ago and no uploaders wanted to add it to 270BC)

**Comment by Cernelius** [comment]
Since the matter is so important and complex and the release is so close, my suggestion would be that you either sane this bug or revert all the related changes that caused it, keeping the mods supported as they are now, and think about how to eventually change how mods and mapskins are handled thereafter, waiting at least some months for opinions, especially from experienced map / mod makers.

Myself, I think that the current way is about the best possible one, all considered (which is a lot to consider), and I would also suggest you to move all or most of the Global mods and old versions outside the original map, in a different "variants" mods' folder, not to oblige everyone to have them, if they want to have Global.

Also, wow, thanks RogerCooper noticed and you didn't release yet, or all mods would have been broken down in the next release...

**Comment by Cernelius** [comment]
Also, why is this not tagged as Regression or Bug? This looks like a major regression to me, and it is of course a bug. And I would definitively say it should be solved before any release, due to the general importance of mods.
And why is this tagged as "Close Pending Confirmation"? Confirmation of what? That nobody cares about mods at all?
Of course, up to the developers; if you don't want to support mods anymore, and no developers want to solve the bugs, noone can oblige you. I'm just saying I don't get it, and would rather suggest you revert all changes that caused this regression, in that case.

**Comment by DanVanAtta** [comment]
Problem is covered by https://github.com/triplea-game/triplea/issues/1246

@Cernelius it is expected you'll keep a respectful and productive tone. Stop wasting our time with such garbage like this "That nobody cares about mods at all?" Instead pitch in and please look for bugs or other problems as has been requested.

**Comment by DanVanAtta** [comment]
Conversation of reducing map dependencies is covered in:
https://github.com/triplea-game/triplea/issues/1247

**Comment by Cernelius** [comment]
> @Cernelius stop wasting our time with garbage like this "That nobody cares about mods at all?" Instead, pitch in and please look for bugs or other problems as has been requested. I don't think you have contributed one bit towards putting us any towards any kind of solution given your tone and lack of basic respect. Please address this behavior by instead asking clarifying questions, and limiting your suggestions to conversations where you've read the full background.

Rereading what I wrote I understand that it can be interpreted as a bad and sterile statement, and that it was not helpful, and I admit this is probably a correct interpretation.

But I rather ask you not telling me that what I say is garbage, even if maybe it is, since I've never been that disrespectful and even insulting towards you or anybody here at all.

What I understood (maybe wrongly) is that a decision was almost made to stop mod support and this issue was about being closed / dismissed as not a problem, since it was not tagged as bug or regression.

I'm sorry to maybe have expressed my misunderstandings in the wrong way, but I don't think I deserve to be answered like that, since I think I've tried to have a very constructive / insightful approach here, highlighting several limits of the proposed new system, and I was ready to provide more information (I already wrote down a bunch of text, and was waiting for cutting it down, in case redrum would have wanted to reformulate or clarify his proposal), after having received a confirmation and having a better view of the different issues / proposals, hopefully cutting them down in number.

I can see I could have asked why this issue was not tagged as bug and was being closed in a different way, but I never got personal and never accused anyone to do garbage and being damaging.

I could apologise for not having tried hard to express my dubious / misunderstandings / concerns in a better manner, but I think your reaction is unbelievable.

But I'll go ahead and apologise for not having suggested to remove the close pending confirmation tag, or why this was not tagged to be solved, in a better way, but I really feel you are being very rude and unfair to me here, and think you should apologise much more than me here.

Anyway, even if you refuse to do so, I guess I will try hard to overlook what you just said and keep being helpful on this matter and others, for the sake of the community, but you cannot expect me to not care to be just insulted like that, while I was doing nothing wrong (except maybe asking why this was not a bug and was being closed a bit too directly).

I'm not really expecting you apologise, but I just hope you will reread what has been written down and see that I wasn't being disrespectful to anyone and your answer is totally unbelievable.

The fact that I didn't propose solutions is because I wrote them down but I was waiting to have a more clear picture, to be able to cut down the quantity of things to write down.

But, yes, I see that the "That nobody cares about mods at all?" was excessive, and I apologise for that, but I think your reaction is way more so. I was just asking why this is not a bug and it was being closed, nothing more, that that wasn't personally attacking anybody.

**But the one who is showing here a "lack of basic respect" is you, @DanVanAtta ,** and I feel very sad in saying so, because I thought we were all going along well and being sort of friends lately, and helped each other in a number or things, or at least I thought so, so I assumed that I didn't need to check my every single word to see that it was absolutely perfect (I see that I expressed my concern in a wrong way, as I said). :-(

As I said, I apologise for not having tried hard to express my concerns in a better way, but I think you should apologise much more than me, and I guess you won't, at this point, so I've no clue how this can be solved. :-(

As I said, since I guess you probably are convinced to have acted totally correctly towards me and will refuse to apologise, I guess I will just try hard to overlook this incident and somewhat get over this like it never happened, but you cannot expect me to just simply accept **your** lack of basic respect. Anyway, on my side, I recognise to have expressed my concerns about this matter being closed too harshly and apologise to not have tried harder to reformulate them in a better manner, and I'm sorry if this felt disrespectful and wasteful to anyone (I apologise to @ron-murhammer too, if he thinks so too, since I was actually talking with him, relatively to his single xml proposal).

At the end, I imagine that you probably think to have been totally correct towards me here (while I definitively believe you have been not) and that I totally deserved to be answered like that, so I guess better we keep our own opinions strictly inside this one discussion only and try to go on, not taking anything personally.

My only proposal at this point is that you edit out your last post and I will edit out this one and my previous two ones, keeping this discussion clean. Your call.

**Comment by Cernelius** [comment]
Just to be clear, I admit to have expressed my concerns in a wrong way, and I'm sorry for that. But I believe there was not a lack of respect from my side, or at least it was surely not intended, while your answer is surely unbelievable, unacceptable and disrespectful, @DanVanAtta , and surely intended, and you can't expect me to just accept something like that.

I've never accused you to write garbage, I've never accused you to have a lack of basic respect, and I've never told you to inform yourself better or shut up, and I've never disrespected you or anybody during this discussion. You did.

I sometimes strongly disagree with you, but I wouldn't dream to disrespect you or @ron-murhammer , and I'm very sad to see the reverse does not apply. Anyway, I will just try to forget about this and get over it, even if you refuse to apologise and just confirm what you said.

Let's just agree to disagree and try to keep this crap strictly here and move on, hoping something like this won't happen again, since we are not going to agree on who was disrespectful with whom here, most likely.

Even if I think you have been very unfair to me, I do not expect you to come to believe the same, and I just want to give you my assurance that I won't take this personally and I will do what I can to go on and help the developers out, on this issue too, for what little I can, like this never happened.

Again, my suggestion is to just edit out your last post and my last four, to get rid of all the garbage, as you said.

**Comment by Cernelius** [comment]
> Also, why is this not tagged as Regression or Bug? This looks like a major regression to me, and it is of course a bug. And I would definitively say it should be solved before any release, due to the general importance of mods.
> And why is this tagged as "Close Pending Confirmation"? Confirmation of what? That nobody cares about mods at all?

And, yes, to be very clear, I see I should not have written down my concerns this way and **I'm very sorry for the above** and I admit it was much too blunt and likely just wrong, but surely not disrespectful, nor personal, nor insulting at all. My other points still stand, as well as my belief that it is you showing here a major "lack of basic respect", @DanVanAtta , or at least much more than me.

Again, I know you think otherwise, and I will see to do what I can not to take this matter personally, and getting over it like it never happened. I just hope something like this won't happen again. I will try to not make it happen from my side and I just hope we will be able to collaborate on projects in the future regardless, friendly if not possibly like friends (after something like this it just not possible if you believe to have addressed me anywhere decently or correctly, which I believe you did not).

**Comment by Cernelius** [comment]
And I want to say that I just feel very sorry about what happened here (I cannot believe it) and I just hope it will just stay here or better deleting all. **I'm ready to take my responsibility of having been the one who started it,** by not expressing in a good and cautious manner my concerns (that would have been very bad to just close this issue without correcting or reversing the bug), but I definitively believe I didn't deserve to be personally offended like that.

My suggestion actually was (and is):

> Since the matter is so important and complex and the release is so close, my suggestion would be that you either sane this bug or revert all the related changes that caused it, keeping the mods supported as they are now, and think about how to eventually change how mods and mapskins are handled thereafter, waiting at least some months for opinions, especially from experienced map / mod makers.

But if the developers want to solve this issue before the next release, I can understand that, and I might try to contribute opinions on the matter, even if after what happened here it won't be that easy for me anymore to return on this issue. Of course, at the end it is just up to the active developers (doing the work) to decide whatever they prefer.

**Comment by Cernelius** [comment]
And, yes, I admit I was very wrong at formulating my concerns this aggressive way, and I apologise about that:

> Also, why is this not tagged as Regression or Bug? This looks like a major regression to me, and it is of course a bug. And I would definitively say it should be solved before any release, due to the general importance of mods.
> And why is this tagged as "Close Pending Confirmation"? Confirmation of what? That nobody cares about mods at all?

It was wrong of me to request assurance about this matter not being just closed and not considered a bug, since you are the developers and it is only up to you to decide what to close and what is a regression or not. Others can just hope and give suggestions.

And I guess you agreed generally on the matter of not closing it, since you removed the tag. That was just what I was (badly) trying to say.

But I believe you have been much more wrong then me at going over on a totally different level and attacking me personally on multiple levels like this @DanVanAtta :

> @Cernelius stop wasting our time with garbage like this "That nobody cares about mods at all?" Instead, pitch in and please look for bugs or other problems as has been requested. I don't think you have contributed one bit towards putting us any towards any kind of solution given your tone and lack of basic respect. Please address this behavior by instead asking clarifying questions, and limiting your suggestions to conversations where you've read the full background.

I never commented your tone etc., nor I would have ever done that.

I will overlook this and try hard to go on like this never happened, even if you don't apologise or even confirm, but I'm surely not accepting nor excusing nor understanding it. I just hope you will do the same and we can both get over it sort of like it never happened; I don't see any other ways out.

Hopefully now on our discussions won't end all up like this...

I'm just very sad and can't still believe something like this actually happened. We were getting along and helping each other on so many matters. I hope this won't ruin everything definitively. Nothing else to be said. :-(

All the developers, no exceptions, have still my full appreciation for all the work they put into this project, for what it's worth. And I guessed you also appreciated some of my other imputs.

I just hope we can at least agree to just try hard go on like this never happened, not letting it ruin anything else. :-(

**Comment by Cernelius** [comment]
Again, since this is just bad, I suggest we simply delete it all. If you delete your previous answer, I will just delete all my comments except the first one. I think this would be the only sensible thing to do at this point. We can talk privately, of course, but I don't think there is anything worthwhile left to say.
Or, if you or @ron-murhammer can, I suggest you just delete everything from my second post onwards.
Can we please just delete all this crap, and get over it?
It sometimes happens to say things in a wrong way, and then the matter excalates out of any bonds; better just remove them, and hoping to be able to keep being respectful towards each other, if sometimes that fails for some reasons.

**Comment by Cernelius** [comment]
Practically, to try to explain, I was just upset and negative, to start with, about this proposal of deleting external mods, and wrote down a quite long analysis of the pros and cons of the current system, but wanted to have a better defined range of the current alternative proposals (possibly reducing them to only one, in case redrum was overlooking any consequences), before posting my considerations.

Ultimately my strongly negative views on this matter, and the confusion about where this was going (maybe just me being confused), and my (personal) belief that the developers were going in a way to make matters much worse than the current system (and just refusing to take into consideration this as a regression at all to solve before closing) badly surfaced up in my tone, and I apologise for that, but I was not being disrespectful towards anyone, or at least didn't mean to.

To do an extreme summing up about what I wanted to explain, I believe that having 1 single xml is a bad idea because would imply an enormous proliferation of original skins and be very unfriendly to players and mapmakers in cases like age_of_tribes and other reasons, while limiting mods to be only bundled inside the referring map only would be a very bad idea because it would oblige players to have their select game cluttered by a lot of games and, even worse, it is likely to make very difficult to have mods actually uploaded, especially if referring to high quality maps, while you should not either oblige the mapmaker to accept into his map mods he doesn't want to have nor oblige the modmaker to receive the blessing of the original mapmaker or anyone, to be able to make 1 mod at all (also because this would cause prolyferation too, as the modmakers will probably just make his mod into a stand alone map, cloning the skin, with no need). There are several other elements to consider, but this is as much concise as I can get it.

**A very important item, in my opinion, is that you should be still able to play mods with other players, with them having only the original map, without requiring having the mod itself installed. This is very important and would be very bad to lose such a possibility.** I don't even understand if any of the proposals would have implied losing this possibility; I surely hope not.

For example, now you can make a mod of New World Order in which armour costs 4 PUs and play that with anyone, as long as they just have the original new_world_order map. Whatever new system should really assure this being still possible, or it would be a very big blow to mods development and testing.

I'm up to detail my opinions in a better manner in the new thread, but I don't feel like doing it right now, due to how badly I have been offended here.

Me waiting to explain this and asking clarifying questions was just trying to limiting the field.

Ultimately, I think all ideas from the developers here are going in the wrong direction, and I would just ask (not demand) the developers to **please be cautious befoure closing this issue and making a decision and possibly keeping the system working exactly as it does now**, even reverting some of the other improvements made, in no other ways, unless there is a clear consensus on the changes, and everything has been fully taken into consideration (it is going to take some time).

But, while I expressed myself very badly, I don't think I was being offensive against anyone, and didn't deserve to be personally (yes) offended like that. I still can't believe it.

I strongly suggest we just delete all from my 2nd post onwards. If you agree with this, just delete your reply and I will delete all the rest. Nothing else to be said. If you don't want to delete, then let's try hard to have this remaing confined here only; hopefully this is my last comment on the matter, but I fear not, unless we just delete all.

I'm just very sad this ended like this. :-(

Sorry again, on my part.

**Comment by RogerCooper** [comment]
I suggest withdrawing the mod from the repository until the issue is resolved.

I have a large number of mods on my own site, many of which never made it to the TripleA repository. I generally tried to make mods stand alone, as I could never be sure what mods people had (except for the ones that came with the download).

I am dubious about the idea of the master map system. Any change in the master can break the mod.

**Comment by DanVanAtta** [comment]
@RogerCooper Downloaded map Mods are a pretty major functionality to have broken, needs to be resolved one way or another. If the problem were isolated to say one or two rarely played maps, it would be more tempting to just exclude them. #1247 discusses the future of how we will support downloaded map mods

@Cernelius It's a process to learn to disagree effectively and work together. I understand you were upset and I appreciate the apology. I'm sorry I was not more diplomatic on my behalf either. I've found sometimes it helps to back up a bit and focus on identifying the benefits the other party is suggesting. Generally that makes a good foundation for suggesting alternatives that would achieve the same or similar benefits. Not all ideas pitched are going to be complete or even necessarily good, so it's fair enough to point out problems. At the same time please remember that in this small community we all have good intentions.

**Comment by Cernelius** [comment]
I still strongly suggest we just delete all this crap. I leave it up to you; if you delete your offensive comment, I will delete all my comments here from the second one ("Since the matter"...) onwards. I think this is the only decent way to close this and hope it won't happen again.
