### ISSUE TITLE
Maps Project Repo Future

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1243]
Issue to discuss pros/cons of using the map repo. Question for this ticket is what usages do we want to get out of that repository?

Summarizing current uses:
- issue queue is a place to track items that impact all maps.
  Alternative: We could use the triplea-game issue queue instead and add a label to represent the same
- map admin operational scripts are stored there
  Alternative: now that we are more or less dropping travis map builds, there are not many scripts, we can house them with triplea-game
- map documentation has already been moved out of that repo to https://github.com/triplea-game/triplea/tree/master/docs
- triplea_maps.yaml file used to live there and is now moved to triplea-games (https://github.com/triplea-game/triplea/blob/master/triplea_maps.yaml)

**Comment by ron-murhammer** [comment]
@DanVanAtta My preference would be to just move everything over to game repo and delete it. Though I'm open if folks would rather consolidate the general map stuff there instead. I just want to avoid the half and half which we kind of currently have.

**Comment by DanVanAtta** [comment]
now that some time has passed, what are your thoughts on the maps Project repo @ron-murhammer ? @ssoloff , @simon33-2 , @RoiEXLab , do either of you have opinions on what to do with it? Should we consolidate it here, or keep that repo for map specific problems? Part of the idea there is that we could acquire new map admins that could watch that queue and not be worried about everything happening in triplea-game/triplea. Then again, we do have an updated forum now, so that adds some more options.

**Comment by simon33-2** [comment]
I'd be inclined to put the triplea_maps.yaml back in it and allow most users write access to the repo. At least that takes a PR out of the process of updating maps.

**Comment by simon33-2** [comment]
Otherwise it seems a reasonable place to track map bugs. Not too keen on them cluttering up this repo's issues list.

**Comment by RoiEXLab** [comment]
I agree, that map bugs should probably not clutter the triplea main repo, but this could be also solved by opening issues on the respective Repositories although I must admit I haven't looked at them for a very long time.

**Comment by ssoloff** [comment]
> I'd be inclined to put the triplea_maps.yaml back in it

^^ This.  With the new validation tasks added for `triplea_maps.yaml` recently, I'm concerned they:

* Slow the overall build down
* Could trigger a build failure for a less-than-stellar reason like GitHub was bouncing some servers at the time

It would be ideal if the `triplea_maps.yaml` validation tasks were **only** run if that file changed.  Moving it to the triplea-maps/Project repo would make that more likely.  And, if a build is going to fail intermittently due to issues outside of our control, it is, IMO, more preferable for the triplea-maps/Project build to fail than the triplea-game/triplea build.

If it's still desired to keep a local copy of `triplea_maps.yaml` with the engine installer, we could simply download the version of `triplea_maps.yaml` from the Project repo associated with the last successful build on `master` during the triplea-game/triplea build.  Whether that's via direct download from the repo or by using the releases feature is up for debate.

**Comment by DanVanAtta** [comment]
Picking this thread back up, seems like we may have some agreement to move `triplea_maps.yaml` to a new repo. We can move it to the `Project` repo, add more value to that one and would make sense if that were the repo to consolidate the map themed issues.

We have a couple other files that are downloaded by game clients, such as the lobby properties file. I've thought it has been a bit odd to have these files mixed with other configuration files, it can be confusing to know what is updated live and what is bundled with the game and installed. The question I have in this respect, would we like to maybe create a dedicated repo for serving live configuration, or are we okay splitting live config files between `Project` and `triplea-game` repos?
