### ISSUE TITLE
2.6 needs a Game version like 2.5 had

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#12432]
@asvitkine 
EDIT: Game Version ~~Map Version:~~ is missing on the Selected Map panel.

Screen of 2.5
![image](https://github.com/triplea-game/triplea/assets/71022517/a7811c8a-f94c-42e5-8fdc-5f617b581975)

.
Screen 2.6
![image](https://github.com/triplea-game/triplea/assets/71022517/e812e5d9-7227-4c54-8d35-2ae7ee5be3e1)

**Comment by Cernelius** [comment]
Actually, this was a change that @DanVanAtta made deliberately if I recall correctly.

I guess the labels "Problem" and "Regression" should be removed, but I'll let someone else do it.

By the way, it is wrong to say "Map Version": it should have been called "Game Version".

**Comment by DanVanAtta** [comment]
I vaguely recall the reasoning for removal. The gist is `Map Version` is not used for anything. If you're sophisticated enough to switch map versions & to know which version you are using, you don't really need the UI to tell you.

**Comment by TheDog-GH** [comment]
I have a novice computer user and I cannot ask him what version of the map/xml he has, so this would have been ideal.

My answer is to get them to remove and reinstall the map & hope they do it correctly.


Its a nice to have, so no biggie.

**Comment by beelee1** [comment]
@TheDog-GH yea as a workaround, I had to add a notification at game start saying which version it is, so players know they have the same one. 
You would have to have them open up the xml otherwise. Obviously not ideal for a lot of users.

**Comment by Blessedatbirth** [comment]
Someone is using my email ***@***.***
And a few other emails of mine
It could be tito jerry alvidrez keyonha and a few others esponza aka niki
oliver trying to make it look like im hacking them
Taking over my accounts porting my business numbers redirecting disabling
my websites changing my numbers on my websites
Gail m Bush
805-598-1587

**Comment by Cernelius** [comment]
> Considering that maps are bundled with scenarios, they are essentially 1:1.

If by 1:1 you are referring to the maps featuring a single game, this is simply not true in general whether or not these maps might be the majority (not sure). How about looking at the top 3 most popular maps in the lobby: they are World At War, Global and Revised.

What of these maps is a single-game (or single-scenario) map?

None.

The "world_at_war" map features 2 games, namely "World At War" and "WAW 1940".

The "world_war_ii_global" map features 8 (!!!) games, namely "World War II Global 1940 Canadian Mod with Combat Move First", "Ozteas 1941 Global Setup", "World War II Global 1940 Original", "World War II Global 1940 2nd Edition", "World War II Global 1940 2nd Edition with Combat Move First", "World War II Global 1940 Balanced Mod3", "World War II Global 1940 Balanced Mod3 with Combat Move First" and "World War II Global 1942 2nd Edition".

The "world_war_ii_revised" map features 2 games, namely "World War II Revised LHTR" and "World War II Revised".

By the way, I think that the "world_war_ii_revised" map should actually feature 7 games in total because 5 more are inside the "world_war_ii_revised_variations" map (which is just a skin clone of the "world_war_ii_revised" map as far as I know) and should rather be bundled inside the former (If two maps are the same map, they should be the same map to avoid needless and potentially harmful duplication.).

However, I tend to agree that what is currently called a "game" may be called a "scenario" if preferred (though I prefer the term game but that may be just due to the fact that I'm into TripleA since a long time and that has been the name for me: the folder where the XML are located is called "games", not "scenarios", for example).

---

However, I see your point that every "game" which I play of the same "game" is a game in itself, so (for example), if I play 10 games of the "270BC Wars" game, I can see those as 10 different games of the same game, which does sound self-contradictory. I think that here there is indeed the same term used for two different things, which is not great, but this is really a language problem (Also if I play 100 games of "chess", I can say that I've played 100 games of the same game and everyone would understand what I'm talking about.), and I think that it is really not a big deal: those 10 played games are further split into as many game-saves as taken in the course of each of the games, and we are not operating on game-saves (we just look at them).

Notice, moreover, that the splitting of a same game into multiple games does not only happen for the former (which is merely the common starting point of each of the latter) as it also happens whenever I decide to reload. For example, if I play a game until achieving victory on round 10 and thereafter I decide to reload and re-play from round 5, I now have two different games of the same game which share all game-saves until round 5 but have different game-saves thereafter. On this regard, the reloading point at round 5 is conceptually the same thing as the original game, as that can be regarded as a game-save taken after having played nothing of the game, thus justifying this apparent contradiction of calling two different things with the same name on the basis that they can be actually seen as being the same thing!

I would agree about opening in forum a poll on whether or not to rename the "games" as "scenarios", but I would vote to keep calling them "games".

However, if "games" would be changed to "scenarios" in the UI, then you would be left with the fact that "scenarios" are called "games" in several non-UI places (like the "games" folder or in the "map.yml"), which is not a big deal in general but would mean that every new developer or power-user will have to be told that "scenario" and "game" mean the same thing (beside of course the fact that you would need to go through all the extant map-making documentation and update it to the new nomenclature).

**Comment by Cernelius** [comment]
By the way (off-topic but related), why having "Game Round" showing under "Game Name" also when you load a new game? I think that should show only if you load a game-save.
