### ISSUE TITLE
Map Dependencies

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1247]
Continuing discussion from: https://github.com/triplea-game/triplea/issues/1237

Dan: Raising idea of dropping mod support altogether here: #1244, in favor of merging the mod maps in with the base maps so it woudl be just one download. It would make the game code much easier, and make the user documentation much nicer too since we wouldn't have ot endlessly explain what mods are and how to play them.

Ron: @DanVanAtta Yeah, my thoughts are actually go the other direction and make every map fully standalone. 1 map per download period (one game XML). Makes things much simpler and makes it more clear what you are downloading. The only major drawback of this duplication of files when downloading multiple maps based on the same core tiles.

Edit: To clarify, mods wouldn't really exist as everything is standalone and no map zips are dependent.

**Comment by DanVanAtta** [comment]
I like the low dependencies between map XMLs. We would need to determine a way to reduce overhead though. It's an expensive investment in the graphics for a map, so it makes sense they would be re-used. How to do so with minimal dependency is an interesting question.

**Comment by ron-murhammer** [comment]
Yeah, I'll clarify that my view was probably more extreme than is actually realistic. That being said I want to avoid packaging 20 different game XMLs together when most of them are rarely played and not of the same quality/balance. Here would be the points of the system I'd prefer:
- No dependencies across map zips (all zips are standalone so no variants zips depending on others like today)
- Can have multiple game XMLs in a zip but should all be around the same level of quality/popularity and preferably owned by the same map maker
- The variants zips today should just get a copy of the map assets and be managed separately in most cases (I don't want the core WW2v3 to come with 20 different game XMLs as its confusing and messy especially for newer users)

Examples:
- Age of Tribes - good example where 5 game XMLs should be packaged together
- WW2v3 and its variants - should not all be packaged together, should have 2 more or map zips with just the core WW2v3 in the main zip then any others in other standalone zips with a separate copy of the assets

**Comment by ron-murhammer** [comment]
One other thing is you should probably clarify all the terms we are using as 'mod' has a number of different meaning as many people would call WaW40 a mod of WaW even though they are packaged together.

**Comment by Cernelius** [comment]
> Yeah, I'll clarify that my view was probably more extreme than is actually realistic.

I agree; and it is good to discard the least realistic options before proceeding discussing them, if possible.

> That being said I want to avoid packaging 20 different game XMLs together when most of them are rarely played and not of the same quality/balance.

I agree, and I would not discard any of them either, as long as they are decent. Mods are the starting window to mapmaking, and it should be relatively easy to have a mod accepted, as long as it is not unacceptable.
Side note, on this line, I would suggest the map admins to move all or most of the mods and old versions of Global outside the main folder.

> One other thing is you should probably clarify all the terms we are using as 'mod' has a number of different meaning as many people would call WaW40 a mod of WaW even though they are packaged together.

WAW40 is indeed a mod of WAW, it doesn’t matter where it is and it doesn't stop being a mod if you move it somewhere else. It will also work if you put it inside the games folder of age_of_tribes, as only what is the value of property name="mapName" matters, not the xml position.

@ron-murhammer This new last proposal of yours is, as I see it, clearly the preferable one amongst all the ones advanced so far, and it is good that we have reached a better / more workable alternative solution for comparison with the current (pre-regression) system, but I still believe the current system is preferable, for several reason, main one being that I don't like the concept of duplicating skins when they are exactly the same (unless you make an automated utility for checking it, it will be also difficult to ascertain if two skins are exactly the same, or some marginal changes have been made, when you want to make any changes to a map skin, and should change the same way all the ex mods, now clones), plus it is also going to multiply the work, both in making and in testing (you have to make some skin corrections to WWIIv3, like the ones recently applied to Global, and you need to multiply them by the number of clones, that could have been collections mods, plus the fact that you have to search if a map has such clones or not).

I agree that the alternative of 1 xml per map folder is too extreme, for the reasons explained.

The solution of forcing mods to requiring always being inside the referring map folder or just dropping them from / not accepting in download list is in my opinion even worse, for the reasons explained and others. Mostly because it will either bloat the Select a Game folder of users or make very hard for mods to be accepted for download list, if they must be inside their maps' folders. As long as maps owned are concerned, I surely believe the owner should not be forced to accept mods he doesn't want to have nor the modmaker should be forced to obtain the consent of the map's owner to make 1 mod at all (also, this would ingenerate proliferation too, as the only solution would be cloning the skin, where you could have just made a mod's folder, instead).

**The most important item, as far as mods are concerned, that I encourage you to keep, is the ability to play (new) mods when other people have only the referring map, not the mod itself (for example, if I have only the Age_of_Tribes_Primeval.xml or even no xml at all inside my age_of_tribes folder, I should be still able to play the Age_of_Tribes_Classical.xml started by somebody else). This is important, as you currently may make and play mods of existent maps (like even just changing armour from cost 5 to 4) with people having these maps, without requiring other people downloading your new package. Any solution removing this possibility should be better discarded, as very damaging to playtesting and customisation.**
This way, somebody making a mod can play it with anybody having the original map, by having it inside the map's folder, before proposing it in GitHub, either iside the original map's folder or in another variants folder.

Anyway, even if the proposal to have 2 stand alone maps, one for the original and one for the variants, is not too bad (in my opinion), **I believe the current system of not requiring an xml being inside the folder it is referring to is much preferable, and I suggest you solve this bug or even consider reverting the changes that caused this regression.**

If this issue gets corrected, it should be better to be so for all these cases:
- A mod in a master folder referring to a master folder
- A mod in a not master folder referring to a master folder
- A mod in a master folder referring to a not master folder
- A mod in a not master folder referring to a not master folder

But if a modmaker can keep the mod inside the master folder (and be able to play it with anyone having said folder, even if not the mod itself) while in the process of playtesting it, before proposing it for download list, I guess that supporting only this case might suffice:
- A mod in a master folder referring to a master folder

Am I correct that both simple folders and master folders are intended to be supported?

I think this is pretty much everything I have to say on this matter. I believe the current system is the best, and I suggest it being kept / debugged.

**Comment by Cernelius** [comment]
The current behaviour, as per 1.9.0.0.3183 is:

- **A mod in a master folder referring to a master folder: Doesn't work,** crashing on start up, giving the following error:

> Caused by: java.lang.IllegalStateException: Error in resource loading. Unable to load expected resource: polygons.txt, the error is that either we did not find the correct path to load. Check the resource loader to make sure the map zip or dir was added. Failing that, the path in this error message should be available relative to the map folder, or relative to the root of the map zip 

It then leaves the broken java process running hidden on your computer.

- **A mod in a not master folder referring to a master folder: Practically works, but it is bugged,** since it tells you don't have the map and asks you to download the master version of the map (that you already have), after you have started the game (you can just click "No" and keep playing).

- **A mod in a master folder referring to a not master folder: Doesn't work,** crashing on start up, giving the following error:

> Caused by: java.lang.IllegalStateException: Error in resource loading. Unable to load expected resource: polygons.txt, the error is that either we did not find the correct path to load. Check the resource loader to make sure the map zip or dir was added. Failing that, the path in this error message should be available relative to the map folder, or relative to the root of the map zip 

It then leaves the broken java process running hidden on your computer.

- **A mod in a not master folder referring to a not master folder: Works perfectly.**

I want to underline that it never mattered where any working xml was at all, as long as it was inside whatever "games" folder.
What is the referring map folder was given only and exclusively by the value of:
property name="mapName"
(that should be exactly the same as the name of the map folder you intend to have as original skin)
And not at all by the xml current place.
I believe this is still the best way to go (**referring only to what is written inside the xml, not to where the xml is**).

So, the ones that appear to be bugged are only the mods downloaded as master folder.
Mods inside regular (not-master) folders works, no matter if the referring map is a master or a regular folder, but if the referring map is a master folder, you will be told that you don't have the map and needs to download it (after you have successfully started the game; so you can click "No" and keep playing).

**Comment by Cernelius** [comment]
Anyway, while I think that **keeping (debugging / reverting) the current system would be the best,** I believe that the latest @ron-murhammer proposal is decently workable (but I don't like the skin duplication), as long as it allows you to paste a mod inside a map's folder and playing it with whoever has that same map's folder, which is very important for developing new mods or testing variants of a same map that you may plan in the future to substitute to the current one.

Still, being able to keep the mods in a separate folder and still referring to the maps folder everyone else has (as it currently works) is the most practical way.

Maybe the best solution is really reverting all related changes and just going back to the old system, giving up with supporting the master folders, but I don't fully understand most of the reasons behind this change, beside not needing updating the yaml at each new release (I just got that it makes uploading and updating maps much easier, which is surely good).

I think this is pretty much everything I can possibly say on the matter. I hope the developers will be able to solve this bug and keeping both the current old system of having external mods without having to have a new full stand-alone (duplicative) installation and the recent improvements, whatever they actually are.

**Comment by Cernelius** [comment]
To say it in a single line, the current system (we had for a long time) is the best because (1) it avoids duplication of exactly same skins and (2) it allows people to select a limited number of such skin related games (with all the many benefits related to point 1 and 2).

Thus, the best is making the old mod system working with the new master system. If this is not feasible, then it should be considered reverting all changes causing this regression. If this is deemed not advisable, then redrum's proposal (of normally two clones skin, one for regular and one for the variants) is the only decently workable alternative.

I want also to underline that the new engine, automatically sending you downloading the map you need (in case you downloaded the stand-alone mods but not the related map), fully cut down any remaining confusion on the user’s side; thus the old system is even better under the new engine, if it actually works.

As I said, the coolest thing of mods is that you can play them with anyone having the referring map, with no need for them to have your game. This is also quite important if you want good quality mods when they are firstly proposed for download list or for playtesting a new version of your map you are considering updating, but don’t want yet.

**Comment by DanVanAtta** [comment]
Bit short on term here, but to respond a bit and add some considerations.

Definitions:
- when I refer to mod, I will tend to mean a 'stand-alone' downloaded folder that contains XML files. NOt really talking about the 'extra' XMLs that can exist in a map bundle. 

- The code for mapping a mod to its source map is a bit crufty. It not only depends upon the mapName in XML, but also the folder name housing the mod. For example, notice the behavior of the mods changes when it is launched from a 'master zip' folder, or other format. IF it were only the mapName XML value that only mattered, then it really would not matter where the map mod XML is located. Because of this complication, making it work will be taking a crufty system and making it more complicated.

- The duplication problem is a real problem. To some extent we choose what to duplicate. For many XMLs, we are duplicating territory names, and other data. So while we save on the skin, we do not save on other duplication.

I think I am leaning towards making the mods to be be full blown maps via copy/pasting their assets to the mods folder:
- it allows us to simplify the code, the support for map mods is actually not very clean
- I think I see two main cases. 1. A map mod is created by the person that originally owns the map. They will put their mod in with their map. 2. A map mod is created by someone else. IN this case I think it is actually okay for there to be duplication. It's then *not* the case that someone is duplicating Age of Tribes assets 'n' times if they own all the maps. For example, if I someone else wanted to create an Age of Tribes mod, I would create a repo called "age_of_tribes_lafayette_variants". In this case the responsibility is on me to update my mod to keep in step with any changes from the original map. In this respect, the maintenance seems reasonable since it is up to the person that 'forked' the map to create a mod. Then finally, we get a benefit of independence. In this case the owner of Age of Tribes can update their map as much as they wish without worrying about breaking variants (which they will have no good way to know about)

**Comment by ron-murhammer** [comment]
@DanVanAtta I think we are on the same page. I think the only thing we haven't thought through all the way is skins. They appear to still function alright as separate downloads even after the master changes. The code is pretty rough but here is the check it performs to find any skin zips:
```
mapSkin.startsWith(mapName) &&
        mapSkin.toLowerCase().contains("skin") &&
        mapSkin.contains("-") &&
        !mapSkin.endsWith("properties");
```

Maybe its better to just leave skins alone for now. Essentially the only thing we need to do then is copy all assets from original games into each variant mod so they are standalone. I believe as long as the variant standalone zips still meet the above criteria then the skins should work for both.

**Comment by DanVanAtta** [comment]
Yes, I think so @ron-murhammer . I had to patch skins so that they worked with 'master zips'. Likely they can be left alone at this point. The problem there was that there was was special code to look for 'skin' in the name of the map folder, and then based on that it would search for the original map folder based on the skin folder name. I updated it to be a bit more flexible and to also search for an original 'master' map folder or zip.

So for stand-alone mods, we are only talking about 4 of them, and potentially 5 if we migrate the global mods to be stand-alone. I think that is then a good starting point for future work to reduce the duplication and maintenance burden of maps.

**Comment by Cernelius** [comment]
Related questions:

If you have an xml in a simple folder, can you play it with somebody having the master folder of the same, and vice versa? I believe this should better be possible (I'm not talking about mods' packages, but like one having a releases download and the other one a master one).

Can you confirm it will be still possible to play game with xml the other side hasn't, as long as they are inside the same folder (for example, if the other side removes all the xml inside his age_of_tribes, can I still play a game of that with him, if I start it (normal case is that you make a mod and add it inside the map's folder, together with the other xml; can you play it with anyone having the regular installation?)?).

**Comment by panther2** [comment]
Help me understand this, please.

For example we recently integrated the "Balanced Mod" into 
https://github.com/triplea-maps/world_war_ii_global

Before this there have been six game xml inside the game-folder:

a) Those reflecting the development of the official ruleset:
ww2global40.xml
ww2global40_alpha3.xml
ww2global40_2nd_edition.xml
ww2global42_2nd_edition.xml

b) Some files created by Veqryn:
ww2global40_veqryn_balanced.xml.txt
ww2global40_alpha3_veqryn_balanced.xml.txt

c) And now there is additionally:
ww2global40_balanced2_0.xml

Those under a) would not be considered to be "mods", I suppose.

Those under b) might be considered as "mods" - I don't know...

And the c)-one would then be treated as a "mod" as it additionally introduced new units - so at least this one would be a stand-alone game again, although it made sense to include it? 
What would be the benefit of separating this one again?

There is a big similarity between all of them. The main difference is a different setup and some different national objectives.

Thank you...

**Comment by Cernelius** [comment]
At the end what to have inside the main map and what to have inside the clone map is highly subjective; theorically you could add the player folders needed for supporting the 11N series, and have all these games inside WWIIv3:

**WW2v3-1941.xml
WW2v3-1942.xml
WW2v3-1941-3Teams.xml
WW2v3-1941-freetech.xml
WW2v3-1941CB4P.xml
WW2v3-1941FFA.xml
WW2v3-1941_ChinaMod.xml
WW2v3-1941_UKfactory.xml
WW2v3-1942CB4P.xml
WW2v3-1939-11N.xml
WW2v3-1940-11N.xml
WW2v3-1941-11N.xml
WW2v3-1942-11N.xml**

which is about the same concept as having, for Global:

**ww2global40.xml
ww2global40_alpha3.xml
ww2global40_2nd_edition.xml
ww2global42_2nd_edition.xml
ww2global40_veqryn_balanced.xml.txt
ww2global40_alpha3_veqryn_balanced.xml.txt
ww2global40_balanced2_0.xml**

or having for NWO:

**new_world_order.xml
new_world_order_smalls
NWO_5_Nation
NWO_Eastern_Front**

etc. etc.

If there is a map owner, the matter is very simple: it stays inside what the owner wants to. Period.

Frostion decides if he wants to have whatever inside age_of_tribes.

Redrum decides if he wants to have the ice's WAW40 mod inside world_at_war and will decide if he wants to have a WAW mod of somebody else, if somebody else asks for adding WAW41 or WAW42 or whatever.

etc.

For unowned maps, it is just up to the general admins, that are the two main developers, all the same.

In my mind, from an user's standpoint, the best system would be:

The original map comes bundled with only the most recent versions of the games or with whatever the owner wants to have; for example (in my mind), Global would have only:

ww2global40_2nd_edition.xml
ww2global42_2nd_edition.xml

Then you have 1 external (close to weightless) stand-alone mod's folder for each single one of the mods and old versions, referring to the main folder, so everyone can freely cherry pick (and remove) his own list of mods, he wanna have in the select windows, amongst both the mods and the old versions (like if somebody wants to have the regularkid Balanced mod, he doesn't have to get the Veqryns too).

So, basically, like now, but with 1 folder per each mod, instead of 1 "variants" folder for all the mods.

But this is just in my mind, since external mods are going to not be supported anymore (both the main developers agree to remove them, apparently), so just wanted to say what would be my vision, considering the new cool "Remove" button we have, that seems perfectly tailored for such a task of having 100% customizable game list, without the extreme proliferation that a 1 xml per map would imply (not realistic a solution, as we agreed).

Also, being able to keep mods externally, instead of having to put it inside the referring folder, is very handy for modmakers, overtime, because you can see all the mods you have, instead of having to recall or make a list of what xml you added where.

This thing of downloading the master folder has some serious drawbacks and it is quite confusing. Would be much better if there would be a way to simplify uploading / updating of maps likewise, but downloading then in the regular format, instead of in the master one (with the many subfolders), but I surmise this is just not possible.

Sill interested in answers to the two questions I previously made (and maybe others might be too).

**Comment by Cernelius** [comment]
> What would be the benefit of separating this one again?

The only benefit is not obliging everyone wanting to have Global or v3 or whatever to have all the mods of it in download list, and how much this is a good or pointless thing is purely subjective (which is fine if the map has an active owner). Also, nobody knows how many other mods of Global will be made in the future, and I seem to understand this issue is also about setting the standards.

**Comment by Cernelius** [comment]
@panther2 I guess we would need Veqryn or Sean Bridges to tell what is the official definition of "mod", but, from my understanding of past discussions, technically all those are, directly or indirectly, mods of ww2global40.xml.

And, no, you don't need to add stuff to the folder for something to be a mod; rather this is the exception. An example is that you can see in new_world_order you have "Cavalry" units, that are useless for the main game (added for mod support), but it's not like a mod having "Cavalry" is more of a mod than the others; rather sort of the contrary, as mods are normally supposed needing nothing else but the original skin (modifying the original skin with something not needed for the original game is surely more the exception than the rule, as far as modding is concerned).

**Comment by panther2** [comment]
Thank you, @Cernelius , and I agree - it is about setting the standards.

**Comment by FrostionAAA** [comment]
Tried to read this long thread. I don’t know if I got everything, but here is my input. It would be nice if (like I seem to see DanVanAtta mentioning) we say someone who made a mod XML of for example Age of Tribes had his own cloned set of files of the original. Then the mod could also alter files, like altered unit player colors, pictures, sounds and whatever. And the original Age of Tribes could also alter these things without changing the mod. Essentially a new standalone map. I hope this is what is agreed upon?

**Comment by DanVanAtta** [comment]
In effect. Turns out there a number of nwo variants which similarly have a copy/paste of the entire map: https://github.com/triplea-maps?utf8=%E2%9C%93&query=new_world_ord, it looks to be a pretty dominant methodology.

Regardless, things are simpler and we restore functionality to the map. The lack of hidden dependency between map folder is a really good thing.

I've almost wrapped up getting those changes up for PR. The map variants are already playable now and have been updated.

**Comment by Cernelius** [comment]
Wait a moment everyone: there is a very major thing I assume we all overlooked (or at least I did and noone made me notice it).

This was, to start with, not a bug or a regression in the code at all (so, for example, my suggestion of reverting the engine changes that caused this regression made no sense at all), but merely a bug in the map itself.

Nothing in the way mods are currently handled appears to have broken with the recent changes, and everything seems to be still functional.

I assumed, like anyone else, maybe, that this was a code problem related to the recent addition of master folders support. Instead, the problem is only that some changes were made inside the external mod's xml.

For example, in the case of:

NekahNets_1939_3.xml

the problem was only that in the xml there was:

property name="mapName" value="big_world_variations"

and, instead, there should have been:

property name="mapName" value="big_world"

I see all mapName were mass changed back then when all maps were firstly imported in GitHub; so I guess it was made when all map's names were changed to be all lowercase etc..

I imagine that noone ever played a mod with the prerelease, at least since the new "downloadedMap" folder was introduced, then.

Thus this has exactly nothing to do at all with the recent "master" changes. It was so since a long time; just noone noticed.

Changing it (back) to "big_world" makes the game work with no problems (as it always did).

So, since the code appears not to be broken, and since I believe that external mods are a cool feature, my suggestion is to not remove this feature.

Regarding the actual issues, my suggestion now is simply to change (back) the values of:

property name="mapName"

of all external mods to be the name of the referring maps, not of the folders they are into.

However, if the current developers prefer not having any external mods at all, nothing stops them from making all current external mods into stand alone maps (it could have been done at any point in the past, as well, and the only reason it has never been is just @veqryn 's preference not cloning skins, which I agree with (just to make an example, the original mapmaker of "NWO_Eastern_Front" initially made this as a stand alone map; Veqryn, seeing that the only reason for it to be not a NWO mod was the absence of the "Cavalry" units, added these units in the NWO package, and asked for this to be converted into a mod, adding it together with the other NWO external mods)).

In any case, going in the direction of making all external mods stand alone is not actually needed to solve the current bugs, apparently, that can be solved by just changing (back) all the "mapName" values to be those of the actual referring maps (I don't know when they got all changed to be the ones of the folders containing the mods).

I want to highlight that the system of having working external mods appears to be still functional (the problem was only that the "mapName" had been wrongly changed), so I surely advice to keep it as it is (meaning an xml referring to a map for loading its original skin only based on what it is in "mapName", as it works and it always worked, with no regard to the current physical position of the xml, beside being in a place allowing for it to be read at all).

(my previous tests are all invalid, due to the fact that I didn't notice that the "mapName" was not the correct one)

---

As far as the mentioned ww2global40_balanced2_0.xml

my suggestion is (unsurprisingly) to make it into an external mod (in either a "wwii_global_variants" folder or in a folder of its own).

This would be better than having it back as a stand-alone map, for 4 main reasons:

- Anyone having "world_war_ii_global" installed can play it, with no need to download any separate installation for the mod (this makes significantly easier for people to get interested in the mod, as far as live play in the online lobby is concerned, and much reduces the risk of crashing because someone misunderstood and don't actually have the map).

- People can download it in virtually an instant.

- You don't need to apply all skin changes for "world_war_ii_global" to all other clones, as well (like the recent changes made by redrum to remove a wrong connection)

- You don't risk to overlook changes and being in doubt whether two maps are really skin clones or not (maybe they are, or maybe they have some marginal changes you are overlooking; the external mods system removes any such doubts)

All the above reasons apply to pretty much whatever external mods and, albeit I can't speak for Veqryn, I assume are the main reasons why we have (or should I say had) external mods at all, which I believe are the best (and still fully working!) way of handling mods, for the reasons I mentioned:

1 - It allows limiting the number of games available via "Select Map" with the original installation (which may be a must, if the map owner doesn't want to have them), without the need of cloning an exactly same skin into multiples.

2 - It allows playing any mods with anyone having the original map, without the need of having it bundled in the original installation (this was more of an advantage for preinstalled maps, but it is still a major advantage; for example, you can play the "Balanced" mod with all the "Global" community, with no need of bundling it).

Side note, I see that both Veqryn's mod are currently disabled, since they are not xml, but normal txt. This raise the problem of what to disable or not to disable, to keep the "Select Map" list short, and the best answer to this are the external mods (so that anyone can have his own mods, no matter how many or how simple they are (sometimes you may want to make a mod just to add a few units here and there, like in substitution of bidding), and nobody is obliged to have them if he wants the original map).

As said, I just tested (with the correct mapName, this time) and verified that external mods fully work, both to and from master and not master folders, in all the following cases:

- A mod in a master folder referring to a master folder
- A mod in a not master folder referring to a master folder
- A mod in a master folder referring to a not master folder
- A mod in a not master folder referring to a not master folder

So, what I'm saying is that, since it actually works, I suggest the support for external mods (currently working) not being dropped (or maybe this has never been an item at all?), even in the case the developers decide to convert all currently available external mods into stand alone maps (I surely suggest not to, either). In this case, modmakers should be informed that they can only ask their mods being bundled in the original maps (like in the case of WAW40, for example), for any future such mods additions requests (if the external mods window gets closed, as a practice).

Sorry for having added a lot of misunderstandings myself here; I just didn't verify that the "mapName" was the correct one, since it has been such a long time that I just (wrongly) assumed the problem could not have been possibly there (this is why I assumed it was an engine issue due to the recent "master" related changes, while it has nothing to do with those at all).

So, practically, turns out that this is not an egine problem at all (as I wrongly assumed), so the ways to solve it are either:

1A- Change all mapName to be the correct ones, and leave everything else as it is.
1B- Change all mapName to be the correct ones, and move all external mods inside the referring maps.
2- Paste the necessary assets inside the external mods' folders.

As said, I surely suggest 1A, but looks like the developers have already chosen 2; I'm just fully rewriting my point of view in case anybody else overlooked the fact that everything can be just solved by changing all the mapName values to be the correct and intended ones; it is such a long time all these mods have been added, and just nobody noticed they never worked! I just assumed the Nekanet etc. mods were all working, all this time, while they were not, since the GitHub maps repository was originally made.

**Comment by Cernelius** [comment]
> The code for mapping a mod to its source map is a bit crufty. It not only depends upon the mapName in XML, but also the folder name housing the mod. For example, notice the behavior of the mods changes when it is launched from a 'master zip' folder, or other format. IF it were only the mapName XML value that only mattered, then it really would not matter where the map mod XML is located. Because of this complication, making it work will be taking a crufty system and making it more complicated.

My previous tests were wrong and not representative. I tried again (with the correct mapName etc.) and it seems that everything works fine, like it always did, as long as the mapName is exactly the name of the referring folder (for the original skin), no matter where the (mod) xml is located (master or not), nor whether it is referring to a simple or a master folder. So, yes, as far as I know, only the mapName in the XML matters, as I believe it always did. Forget my wrong previous tests (got confused about what the issue was).

Now it seems to me that there is nothing at all that needs to be made nor reverted in the engine.

So, **this was just an xml only bug and existed since all those xml were originally added in the GitHub repository, and can be just solved by changing the mapName values in all the external mods, to be the names of the original maps** (like they have always been in SourceForge, before the migration to GitHub), not the names of the folders they are in.

**Comment by Cernelius** [comment]
So, I want to quote what I believe would be the best system, from a user's standpoint, since it is actually totally possible (just needs to be sure the mapName values are correct) (forget about the rest I said in that post):

> In my mind, from an user's standpoint, the best system would be:
> 
> The original map comes bundled with only the most recent versions of the games or with whatever the owner wants to have; for example (in my mind), Global would have only:
> 
> ww2global40_2nd_edition.xml
> ww2global42_2nd_edition.xml
> 
> Then you have 1 external (close to weightless) stand-alone mod's folder for each single one of the mods and old versions, referring to the main folder, so everyone can freely cherry pick (and remove) his own list of mods, he wanna have in the select windows, amongst both the mods and the old versions (like if somebody wants to have the regularkid Balanced mod, he doesn't have to get the Veqryns too).
> 
> So, basically, like now, but with 1 folder per each mod, instead of 1 "variants" folder for all the mods.

**Comment by Cernelius** [comment]
I just wanted to say that now that I realise that everything works fine in the engine and that the issue was just that the xml mapName values were wrong I see really no reasons for dropping mod support altogether (not sure if that means just making all mods stand-alone and not accepting external mods anymore in the repository or even changing the engine as obliging any xml to be inside the games folder of the map its referring to?).

**Comment by DanVanAtta** [comment]
Okay, that is good news. There are still advantages to requiring mods to require their own assets. 

## Suggestion
Require map variants to have their own assets

## Against-argument:
- 1. assets bundled in map variants will require more disk space, slower download
- 2. can no longer publish a stand alone, light weight mod that is just an XML
- 3. duplication, fixing an image problem has to be done multiple times with no guarantee we'll find all of the duplicates


### Rebuttal
- 1. Not that big of a problem with faster downloads from github, and smaller download size with mp3 encodings instead of wav
- 2. light weight mods are not very intuitive and add significant complication, meanwhile there is not much benefit to end-users, mostly to behind the scenes map making items.
 3. Duplication of images is a problem. Let's say we need to update an image everywhere, it becomes a more signficant challenge. But, we already have much of the problem today since variants are not consistently done, we have a lot of full map copy/pastes out there. Variants does not seem to have really solved this problem.

## Pro-Argument
- 1. Simpler map download experience, no mod tab. No need to describe what a 'mod' is to those downloading maps, no need to go over the details of you have to have the original map, etc..
- 2. Simpler game engine config, one less map category to have and deal with
- 3. No hidden dependencies can be added to a map you are developing. Let's say someone produces a successful map and there are new variants added. You then updated the map significantly, everything works, but now suddenly at release the variants are now suddenly broken.
- 4. Long term far simpler map loading. The map resource loading today does a lot of magic, it looks at the map name, it looks at the folder, it looks to see if you are loading form a zip, from something that has the word "skin" in it, or something that has a dash in the name... And that is more or less the first half of identifying possible map locations to match. Moving away from a system where map assets are loading relatively magically based on search paths is going to be simpler for us in the long run.
- 5. Simplified map maker instructions. Simply tell people that they can either copy/paste an XML in place, or copy/paste the whole map folder.


## The image duplication problem

I think long term this is better solved by splitting map graphics from the map XMLs. This would create 'map gfx packs'. These resource bundles would be handled behind the scenes. So instead of including map assets directly in a map folder, you would refer to them by name. We could do the same for unit images as well.

There are some details to work out, but overall this would eliminate most of the duplication of image files. I think this is roughly the best long term goal to work towards.

## Summary

With view to solving the image duplication problem long term, we gain a number of simplifications by removing stand alone variant support without losing that much benefit. Happy to get more input, but it seems that we would be better taking this half step back to simplify things, allowing us to take a couple good steps forward in the future.

**Comment by DanVanAtta** [comment]
With https://github.com/triplea-game/triplea/pull/1256 merged this is pretty much now done. There remains support technically for map mods in their existing form, but there is no longer a special map download category for them. The 5 mods we had have been updated to have copies of their necessary asset files.

**Comment by Cernelius** [comment]
6, actually. You missed ww2v3_variants.

Another major thing is that, for a modmaker, it is much better having his mod bundled inside the original map, instead of having it in an experimental folder that needs a separate installation to work. This raises the issue that it becomes very arbitrary to decide what to bundle and what not. For example, the Global Balanced mod has been bundled; what about if I make another mod of Global (or another map) and ask it to be bundled too (because it would be **so much** better for the visibility and popularity of my mod); how can one decide what deserves bundling and what doesn't. For example, the NWO Smalls or the BW Nekhanet are more played than WAW40 or UW Revised.

Even if everything is stand alone, a separate section for highlighting maps supposed to be skin clones of others would be valuable. Also, you have moved everything to Experimental, while at least some of those clones are surely quality (for example, BW Nekhanet is reputed being of at least the same quality as the original BW, and NWO Small is surely at least good quality and surely well playtested, developed and definitively not experimental by any possible meaning of the word); a separate section would solve the issue of rating variants, especially in case a same folder has multiple ones.

I still believe 1 mod per folder referring to the original map would have been the best and least arbitrary solution, but I've nothing else to say than what I already did.

Good thing they at least still work in a separate folder; it makes it easier for modmakers and also mapmakers testing out possible variants, plus general experiments, for various reasons.

**Comment by Cernelius** [comment]
What I meant is that removing the main "Mods" category is correct, if everything is stand alone, but I suggest having a "Variants" category, after "Experimental" (instead of a "Mods" one beside "Skins").

**Comment by Cernelius** [comment]
Actually, 4 (out of 9) external mods' folders are still broken; refer to:
https://github.com/triplea-game/triplea/issues/1271
