### ISSUE TITLE
New Maps are Unable to be Played in the Lobby with 2.6

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#12517]
This is project related. New Maps such as "1941 Global Command Decision" and ""UHD World War II Global" are currently unable to be played in the lobby. This is demoralizing to map makers not to have there work available to those that would otherwise never hear of it.

A&A .org recently helped with financial issues for triplea. They mostly PBF but will occasionally go to the lobby for big battles for a live setting. UHD Global 40 is gaining popularity there and they should be able to play on lobby if desired.

All new maps should be playable in the lobby. In the rare case a map is deemed inappropriate, it can be removed by mods alerting the necessary triplea power.

This will help grow and keep triplea engaging for old and new users alike.

**Comment by TheDog-GH** [comment]
I agree.

**Comment by Cernelius** [comment]
Wow! How is it possible that new maps cannot be played? This should certainly be a release blocker.

**Comment by DanVanAtta** [comment]
@beelee1  is this a problem because the bots do not have those new maps installed?
Could you please be far more specific & ultra-precise to the problem you are describing? (There are lots of problems in TripleA, I could easily latch onto one, spend 8 hours on it, to then realize it's not the thing you were talking about. I get maybe about 8 hours of dev time for TripleA in a month -that would be a loss of a month. It's important to convey EXACTLY what you are talking about, please be very specific)

**Comment by Cernelius** [comment]
Right. I also don't understand how it is that new maps cannot be played in the lobby. I've not made a new map myself since some time.

Maybe @TheDog-GH can clarify if he knows better?

**Comment by Cernelius** [comment]
@beelee1 Let's say that I make a completely new map from nothing and would like the community to be able to play it like whatever other map which is already available. What does it make that impossible?

**Comment by TheDog-GH** [comment]
I cannot clarify as never played in the Lobby.

But at a guess these two maps dont work
"1941 Global Command Decision" and "UHD World War II Global" are both new maps posted on GitHub Nov 2023

Both have been available for a month or so for download within 2.6 is all I can add.

Best wait for @beelee1 to answer.

**Comment by DanVanAtta** [comment]
Could you clarify what you mean by "don't work"?  Is it impossible to select them? Is there an error when they are loaded? Is there an error shortly after game play has started?

**Comment by beelee1** [comment]
Yea, so download "1941 Global Command Decision" or "UHD World War II Global" in 2.6. Then go to lobby and take control of a bot. 
Hit Select game. Both games don't showup as an option to select when the "Change game to" prompt shows up

**Comment by Cernelius** [comment]
Ah, so you mean that the automated hosts have not been updated as to have those maps, but the maps themselves are playable with no problems in normal hosts? Is this a bots-only issue?

Is there somewhere any documentation about how automated hosts are updated? For example, if I make a new map, how much time should I be expected to wait on average before seeing it in automated hosts, and am I supposed to make a request somewhere to that effect or just to wait? Is it automated or is there a list of volunteers who operate the bots to such effect?

I've never cared myself about such issues because I just host and virtually never use bots, but I think it would be good having such matters documented somewhere as I can see it may be frustrating for other map-makers having to wait indefinitely in the hope to see their maps in the bots.

**Comment by beelee1** [comment]
@Cernelius yea that seems to be the problem the more I find out about bots. I've never hosted privately, so idk if the maps would be available then.

Anyway, UHD been out for a year now, so I would have thought it'd be playable by now

**Comment by DanVanAtta** [comment]
> My time is also important :)

@beelee1, indeed. I did not intend to imply otherwise. Avoiding Q&A and defining "does not work" the first time saves everyone effort. That's all I was getting at.

-----------------

There is a script to update bots. It needs to be fixed up a bit to be back in a working state. I can give you some screenshots of how to run it @beelee1 . Because you have write-access, it would be a click of a few buttons for you to run whenever needed.

**Comment by beelee1** [comment]
@DanVanAtta  no worries all good :)

Yes , if you show me how I will do. I also think the Dog and Roger should be able todo it.

I'm in the 4th qtr of life and will probably only be around for 2-3 years.

Be good to have ave a backup regardless :)

**Comment by TheDog-GH** [comment]
@DanVanAtta 
Yes add me to the 'bot starter' admins

**Comment by Cernelius** [comment]
I think this should be taken off the "2.6 Release" project.

**Comment by DanVanAtta** [comment]
@Cernelius I agree, considering this is a problem for any game version.

Others/all, the 'update map' script no longer works   : |
I'm working on getting it up and running, it's a significantly heavier lift to do that than I imagined.

**Comment by beelee1** [comment]
@DanVanAtta 

Would you give us a update on the status please

**Comment by DanVanAtta** [comment]
Still working on it..
The efforts are here: https://github.com/triplea-game/infrastructure

I have so far the baseline install of the servers fixed.
I need to still build a CI/CD pipeline so that the infrastructure runs whenever we update that codebase.
Once that is done, access to all of the servers would be restored (most of the bot servers right now are a complete PITA to access, and secondly any scripting against them would not work for the same reason).

After that, there is some work to restore the bot/lobby installation & configuration steps. Following that, the  script to update maps would be next.

**Comment by TheDog-GH** [comment]
Gentle nudge.

**Comment by DanVanAtta** [comment]
I was able to run the update-maps script on the bot servers. They have updated maps now, except they each need a restart to pick up the new maps. All but 'bot201, bot202 and bot404' have been restarted. Most bots now have updated maps.

Things are still being repaired & rudimentary at this point. Next priority is getting a 2.6 lobby up, the right per-version routing config enabled, 2.6 bots going.. and then making updating bot maps a bit more routine/easier.

**Comment by DanVanAtta** [comment]
Marking as resolved now.
Lobby bots get a refresh daily now & pick up the changes on restart, which is now whenever a game ends.
