### ISSUE TITLE
Broken Air battles with 2.6

### ISSUE THREAD

**Issue by WCSumpton** [triplea-game/triplea#12542]
This problem only accurses when one area is attack with air battles set to happen prior to land battles.
In 2.5 the battles happen as they should, air battle must be completed prior to the land battle.
In 2.6.14727 (latest pre-release at this time), the land battle automatically happens, and the air battle can be selected to happen after the land battle.  

The following save was created in 2.5 and can be loaded into 2.6 to demonstrate the problem.

[2024-4-27-Pact-of-Steel-2.zip](https://github.com/triplea-game/triplea/files/15140419/2024-4-27-Pact-of-Steel-2.zip)

Cheers...

**Comment by Cernelius** [comment]
@WCSumpton Where is the game-save? To me, it looks like you've uploaded the map.

---

While at it, how about merging the air and land battles happening in the same territory? Meaning, instead of having to select first the air battle and thereafter the land battle, just being able to select the combined air/land battle and the program of course making the air battle first (just the same as if you select the land battle immediately after having finished the air battle in the same territory). The same for air battles and sea battles happening in the same zone.

I mean integrating the air battle as part of the land or sea battle in the same zone instead of having it as an actual air battle unless there is no other battle in the territory.

Opinions?

**Comment by WCSumpton** [comment]
Thank you @Cernelius, I have corrected the post with the correct file. I also think your suggestion is valid.

Cheers...
