### ISSUE TITLE
unable to load game

### ISSUE THREAD

**Issue by kevenwall** [triplea-game/triplea#12555]
I am running 2.5.22294 java version 11.0.6 and I can't open a save game from a friend...it says 

"This save was made by a newer version of TripleA. To load this save, download the latest version of TripleA: https://triplea-game.org/download/  If this problem happens frequently and is something you cannot fix, please report it to TripleA"

I believe he is running the same version, and it looks like I'm running the most recent version based on what I see online. 

I can't seem to be able to attach the savegame file to this thread.

**Comment by TheDog-GH** [comment]
You need to find out and be sure what version your friend is using.

If its a pre-releases they are here
https://github.com/triplea-game/triplea/releases

**Comment by kevenwall** [comment]
It is the same version. He sent me an image of his load screen...

**Comment by beelee1** [comment]
Hi @kevenwall 

To attack, oops, attach lol, saves, you need to put them in a zip and then upload.

Dog is correct that you need to download latest pre release. You are probably on 2.5 Anyway, DL prerelease and try it. 

Also, when you DL the pre, put it in a different folder, I just add the pre number to the end of the existing one. That way, you can have both, although you can now access the 2.5 lobby with the pre as well

**Comment by beelee1** [comment]
@kevenwall 

Were you able to get this to work ?

**Comment by DanVanAtta** [comment]
There might not be a lot to do. 

2.6 is better when it comes to this situation as it does actually try to load a save game and then fails only if the game really can't load the game.   OTOH, 2.5 just looks at the game version in the save file and then just gives up if the version is greater than the current game engine version (which is really lame).

I suspect quite strongly that the save game is actually a 2.6. I have not found a clean way to downgrade saves. I think the only thing to do would be to play out the save in 2.6.

We're working to get 2.6 fully launched, but it might still be another week or three. I would recommend to do a side-by-side install of 2.6 (install 2.6 in a different folder from 2.5), and then play out the game in 2.6. Your friend will also need to do a similar side by side install.   OR, you can wait for the full release of 2.6, at which point we'll try to get everyone to upgrade and then there won't really be anymore issues since 2.6 works with 2.5, but not the other way around.
