### ISSUE TITLE
Official upgrade instructions for 1.9 / Keeping 'old jars'?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1263]
It's quite difficult to get the upgrade instructions short and simple: http://www.triplea-game.org/upgrade_notes/

It would be a bit easier to simply say that 1.8 games should be finished with the 1.8 game engine. Should we do that?

**Comment by panther2** [comment]
As long as 1.8.0.9 will be available for download, this would be acceptable I think.
But in this case there is no need to keep the old jars 1705 and 1809 with the new release, IMHO.

**Comment by DanVanAtta** [comment]
'Old' 1.8 downloads now available here: http://www.triplea-game.org/old_downloads/
There is a link to the 'old downloads' page now on the downloads page - http://www.triplea-game.org/download/

I also simplified the upgrade notes to essentially say to use 1.8.. Now it finally seems simple enough to follow (maybe with some luck) - http://www.triplea-game.org/upgrade_notes/

I agree that there is no real need for the old jars. Would make for a smaller download and simpler code to support them. Before we did not have support for the installer to install new versions side by side, now we do. The previous map upgrade instructions and attempt to have only 1.9 was not looking promising. 

@ron-murhammer What do you think, is there still a strong case to have the 'old jar' functionality considering that old and new game engines can be downloaded side by side?

**Comment by panther2** [comment]
Another argument to leave the old jars **out of 1.9** is:
In fact you get the old jars when you download the 1.8.0.9 version.

**Comment by prastle** [comment]
just tell tell them the old save don't work.  Keep the old lobby alive for a month as veq used to.

Jmho

**Comment by DanVanAtta** [comment]
By default we're keeping the old-jars functionality for 1.9 (requires effort to actually remove it, and we're effectively at a point where 1.9 should be out there). Going forward, since we're going to make each release available (eg: 1.8, 1.9, etc..), and additionally now that they can all be installed side by side, it seems there is agreement we no longer need the 'old jar' functionality at all going forward.

**Comment by DanVanAtta** [comment]
@ron-murhammer , would you mind weighing in on this one, do you agree that we can remove the old jar functionality?

**Comment by ron-murhammer** [comment]
@DanVanAtta I'd be interested in the community's thoughts on this one. The main benefit of having the old jars is so you can load old saved games and don't have to go download an old version. I've used it a decent amount but not sure how often others do.

**Comment by DanVanAtta** [comment]
One complication is that 1.9 will need a maps migration for old jars to work. It's a complicated process to describe as it involves taking any maps from the 1.8 game install folder and placing them in the maps folder. The problem is that 1.8 expects those maps to be present in the triplea/maps, but for the 1.9 game engine there is no such folder. 

Personally I've never used the feature. My personal experience over the last 2 releases is that most do not know about this feature and will launch an old version to play old version'ed games.

IMO the best path forward is to keep the feature for now, even though most 1.8 maps will not work with it (and of the pre-bundled ones). This simplifies the upgrade instructions, I don't think most people will really want to, or will be able to successfully move maps around. It's far easier to have folks to simply keep the 1.8 installation as is and to play out games like that.

The only use-case that remains is for playing very old save games, for example from the 'game-of-the-month' thread. Even still in that case, having those games no longer work, or requiring a DL of 1.8 I think is reasonable. The real roadblock is that map compatibility is going to stop those games from being played, and there is no mechanism to roll back to old map versions. Since we are not supporting old map versions, it does seem like we are unable to adequately support playing really old save games on new engines.

Does that alter your opinion at all @ron-murhammer ?  I am indeed curious what others think as well, in case there is something being overlooked.

**Comment by Cernelius** [comment]
It does seem like you are unable to adequately support playing old save games on this new engine, with reference to the old preinstalled maps.

Unless you have some integrated solutions, or you are also going to somewhat bundle all the old preloaded maps for them only, which I'm surely not suggesting to, my thoughts are that you should not support any old releases for this 1.9.0.1 release, since the main referring TripleA games were bundled in the old installations, thus it would be not anymore possible to load all those maps, as @DanVanAtta  pointed out.
Certes, moving maps around (meaning adding in the user maps folder the old preinstalled ones) would be much more confusing than just telling regular users to use their old 1.8.0.9 installation.
Moreover, the WWII series and 270BC were both preloaded and disposable in download list, and this would be a mess, since, for example, people that want to load their "WWII Revised" games, and didn't install the map, as it was also bundled in the main installation, will need to either move it around, as well, or go downloading the map from the old SourceForge repository, if you are not paring it down, and this is going to be very confusing for most users, also because some may already have such old maps in their "Users" folder and some other ones not.

I would definitively not keep a feature most maps, and especially the preinstalled ones, won't work with.

With this said, I believe that almost all users are not going to go use and even less go download an old version to play old savegames and whatever, and removing the "old-jars" functionality is going to be equal to removing the possibility of finishing old savegames for most people (or at least in what I think would be their perception). This is particularly true for live multi, and especially FFA, old savegames, in which you would need each human player logging in with the correct old engine (I doubt even only 1 multi / FFA live savegame will be ever reloaded after the new release). I believe most live players won't launch an old version to play old versioned games, but will just give up with playing any of them.

Without something like the "old jar" I don't think I would ever even try to reload old savegames for live multi / FFA.

Meaning that, for the future, I advise you to keep the old-jars functionality, or something like that, for any releases in which you don't make such extensive changes to suggest otherwise.

Even better than having old jars, in my mind, is to have releases installed side by side, and the new one being able to automatically switch to any specifically supported old one, as long as it is in the same path as the former (side by side, no matter where), much like now it would start the ones inside its "old" folder (no clue if such a thing would be feasible). If such a thing would be feasible, then you could fully support 1.8 games for this release too, comprising those of preinstalled maps.

Also, as prastle sort of pointed out, assuming you won't be able to join the new lobby with the old releases, for how long do you intend to keep the old lobby open for people to play their old games? And how many bots there will be in it? Mind you that keeping the old lobby alive with some bots in it may induce people to keep playing new games there, instead of moving over to the new release (as long as a good number of bots are kept in it, I can quite see the old lobby being used much more by people not updating than by people needing to actually continue their old savegames, they started before the last release).

Anyway, I think everything here is quite marginal, so whatever the developers prefer or is easiest should be about fine; kind of whatever... As a related off-topic note, I would surely **not** make savegames 10% heavier or anything, for supporting something marginal like integrated backwards compatibility.

Myself, I care little about this matter, and wasn't actually thinking to reply in here, but I guess you should open a Topic in forum (probably best the axisandallies.org one), to have some user's opinions. Also, you should set apart live and PBEM users' opinions. I tend to think this is mostly relevant for people that "have" to continue saved games, like for ladders and tournaments. Also there are some people that, even outside tournaments, are quite hardcore in keeping their streaks of games, and absolutely want to finish each one of them (making the other side go download / use an old release may be a burden for them).

Likely, something like the "old jar" is more useful for live players than PBEM ones, and almost needed for live multi / FFA players, but not a big deal anyhow.

**Comment by Cernelius** [comment]
To sum it up, as it is, unless something different gets worked out, I surely suggest not having any "old jar" for this 1.9.0.1 release (mainly because of the removal of the preinstalled maps), and, of course, not any other 1.9 releases, as well (unless something different gets worked out); but if future 1.10 etc. releases would allow the "old jar" to fully work, like in the past, Tutorial aside, it would be good to have them, but really not a big deal, anyways.

**Comment by Cernelius** [comment]
To make a clear example, I surely believe it is better if old savegames don't work with 1.9.0.1 both for NWO and WAW, rather than they seem to work for both, but they actually do only for WAW, while people will crash on start-up with NWO; that would be a mess, and only power-users will get around moving the NWO map in the Users folder.
Yet, I don't think that most people will go using the old engine, if the old jars feature is removed; I believe they will just assume that old savegames are not anymore playable, get maybe a bit upset about it, and forget about them, I'm pretty sure. And, of course, almost noone will read the upgrade instructions. Of course, this is just my perception, but I've little doubts.

**Comment by DanVanAtta** [comment]
I don't know if it makes sense to start including 'old jar' capability in future releases, but not this one. The bulk of the problems we are seeing are due to map versions, that problem is seemingly only going to be getting worse, particularly now that it's easier to contribute to maps, and to update them.

A top priority has been to update the game to use a non-native save game format. Once JavaFx migration is done (which seems like it is already about halfway done) I think that will be the next big dev initiative. If we can get that in place, there will be no need for old-jars at all, we'll effectively be able to have the game work with any other version. Then we'll only need to worry about map compatibility.

The map compatibility problem is quite significant, particularly since we do not allow downloads of old maps. I think we should do a couple of things there:
- save maps with a version number and store the last 3-5 versions
- allow on-demand downloads of arbitrary versions, so in case you do not have the right version it will download
- add an XML version in the map files. This way we can update the game parsing code to read new map XML configurations, while still being able to read the old (and not have to update every map)

So I think between saves being cross-version playable, and stronger map versions, we'll be in a much better situation and will not even require major releases anymore. We'll be able to push updates much more often, and players will not have to do the mass cross-lobby migration, nor worry about not being able to play saves. With the above as described, you'll almost always be able to play any map version, and old save games will launch in new game engines and then can be saved with the latest engine.

**Comment by simon33-2** [comment]
@DanVanAtta 

My suggestion would be for the 1.9 installer to look for the 1.8 engine and maps and create the needed links for it to work OOB. That gets the best of all possible worlds as I see it. When we go to 1.9.1 you could use the same logic. Link to the 1.9.0 jar. I guess the limitation would be if it can't be found, should there be prompt to ask the user for it? Another option would be to have a button in the Engine Preferences dialog to do the same.

**Comment by DanVanAtta** [comment]
Closing for now. The question posed originally has more or less been settled. @simon33-2 not a bad suggestion. My preference is to simplify and remove the old jar logic and do backwards compatibility in other ways. Let's consider that further as we move to the next major release.
