### ISSUE TITLE
TripleA engine

### ISSUE THREAD

**Issue by EduardoPantalones** [triplea-game/triplea#12666]
Hi, was just enjoying the TripleA engine with friends, and got to wondering if it's still be actively developed? Just curious..  Possibly the best game engine I've ever seen. Kudos. (Battlestar Galactica map/scenario please lol)

Regards,
Ed
(The donate button is broke btw)

**Comment by DanVanAtta** [comment]
Where are you seeing the broken donate button?

**Comment by Cernelius** [comment]
Maybe he got TripleA from one of those alternative hosting sites which have been forgotten since ages past. We had a discussion about those which went nowhere (my suggestion being to remove them all or as many of them as possible).

My question would be which "engine version" of TripleA he is using.

**Comment by Cernelius** [comment]
@EduardoPantalones

Did you get TripleA from one of these links?
https://user-images.githubusercontent.com/13902879/92022103-0df22000-ed5b-11ea-93a7-5534a9125881.png

**Comment by EduardoPantalones** [comment]
Or he went to the webpage and clicked on the Donate button on the bottom left 😊 It takes you to the paypal error at bottom.  This not you guys? I’m recently retired from an IT career, and just recently found your engine, fantastic work.  Still under development?

***@***.***

***@***.***

**Comment by EduardoPantalones** [comment]
Got it from a discord chat room, and playing it with several people there. See snip for version

***@***.***

**Comment by EduardoPantalones** [comment]
Bottom left of webpage, maybe not your webpage?

***@***.***

**Comment by DanVanAtta** [comment]
**Regarding old engine versions [which IIIRC some had a donate button, which is likely busted]**

@Cernelius old versions of the game engine had a donate button, right? Do I remember that correctly? I love that you're a time traveling guru of TripleA to remember things like that   : )

Looking at the old-download link list you posted - I'm really impressed there is a working apt repository for TripleA. It comes with a 1.9 instead of a 1.7, which had this prompt:
![image](https://github.com/triplea-game/triplea/assets/12397753/8fe7b8ed-6ba2-4b9a-ab1b-139e60b18df2)

There are some aging mechanisms for keeping that "your tripleA is out of date" prompt working. Having the old download links is a strong reason to keep those mechanisms around and working.

Though, how to comprehensively fix that list of download links is a pretty involved effort. In the meantime keeping the update prompts working seems to be something of a mitigation. 

-------------

**Regarding TripleA development...**


TripleA development ebbs and flows, completely volunteer based: [how to contribute](https://github.com/triplea-game/triplea/blob/master/docs/contribute.md). The project is 20+ years old now. Usually there has been at least one person working on it at any given time. I think to give the project true justice, it could use 5x more developers. There's lots of aging things from that legacy and between transitions of different people.


---------


**Regarding the donate link...**

@EduardoPantalones Thanks, I found where you're talking about   :smile: 

The footer really could use some more love...

**Comment by DanVanAtta** [comment]
I took a stab at updating the footer: https://github.com/triplea-game/triplea-game.github.io/pull/397

Notably, donate link is removed. 

@EduardoPantalones  - thanks for raising this issue!

FWIW: The "pulse" of the community is arguably in the forums: https://forums.triplea-game.org/

TripleA is short on just about everything, certainly looking for a variety of volunteer effort! Nonetheless - the donate button in the forums works :grin:

**Comment by Cernelius** [comment]
> @Cernelius old versions of the game engine had a donate button, right?

Yes.
