### ISSUE TITLE
World War II Global download doesn't get fixed version 0.27

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1266]
I'm confused. Where is this updated now that the Project repo has been deprecated? I just deleted and downloaded the G40 map and it doesn't have the corrected objective.properties file (.xml file could have changed too). This causes the objective panel to go missing.

**Comment by panther2** [comment]
Strange, Both files - as well the ww2global40_balanced2_0.xml as the objectives.properties- of the 0.27 version are identical to those you get with the ingame downloader. Just checked wit "HashMyFiles".

**Comment by simon33-2** [comment]
Looks like I've solved it - the problem was that the ww2global file had -master appended to it's name and an old file was lying around and got picked up in preference. Won't this happen to other users. So I was looking in the wrong place when I checked the objectives.properties.

I would close this but I feel this will happen to a lot of people.

**Comment by panther2** [comment]
I would recommend to close this - as the map update/download process works just fine.
Mixing up downloaded files happens "everybody, anywhere and anytime".

Just to answer your question concerning the update process:

When you use the ingame downloader, taking Global as example, you get your file from: https://github.com/triplea-maps/world_war_ii_global/archive/master.zip

This is exactly the same zip-file that you get when you use the "Clone or **Download**"-button in the map repository, as the "Download ZIP" function links to the same url:
https://github.com/triplea-maps/world_war_ii_global/archive/master.zip

When downloading from either way, the map name is added to 'master.zip', resulting in the file
'world_war_ii_global-master.zip'.

Every time the map-repository is updated causing a new release (from 0.24 to 0.27 for example), the resulting release will be the new basis for the above mentioned master.zip

Version control for the ingame downloader takes place in the triplea_maps.yaml, that has been moved to https://github.com/triplea-game/triplea/blob/master/triplea_maps.yaml

Here you find in

- line 339:   url: https://github.com/triplea-maps/world_war_ii_global/archive/master.zip     and in
- line 357:   version: 1

To realise the update in TripleA it will be enough to increase the version number, so that the ingame downloader will notice it.

So you never have to update the download-url in the yaml when updating. Edit the map in the map repository - and the rest is automated (except the versioning in triplea_maps.yaml).
