### ISSUE TITLE
mapCategory for variants in triplea_maps.yaml?

### ISSUE THREAD

**Issue by williamdekryger** [triplea-game/triplea#1268]
Recent changes to triplea-maps.yaml (https://github.com/triplea-game/triplea/commit/0c95b5b3800c66a5e6138490504a3a7203efed5b) have removed the mapCategory "MAP_MOD" from the maps in the listing. However, the mods were not reassigned with any new value. I was wondering if we could give them a mapCategory, so that the website can classify them appropriately. I was going to suggest "variation" or something, but I wanted to get input here before I proceed.

Here is the broken "Mods and Skins" page on the website (not linked to the public side): http://www.triplea-game.org/maps-list/mods/

With any change in format on the YAML file, I will reciprocate on the website.

**Comment by Cernelius** [comment]
4 of the maps related to this issue are not working; refer to:
https://github.com/triplea-game/triplea/issues/1271
https://github.com/triplea-game/triplea/issues/1272

**Comment by Cernelius** [comment]
I actually already advanced this same suggestion here (giving some explanations about why it would be advisable having such a section):
https://github.com/triplea-game/triplea/issues/1247

Main question is: do you want that listing only the skin clones (having exactly the same assets, thus potentially workable as mods of the originals) or also modified versions on a skin level too, and, if so, do you have any ideas about where to draw a distinction?

Also, once decided, what about renaming all those maps with the same convention (for example, all with the shortened original name (like "bw" instead of "big_world") followed by "_variants" (instead of "_variations" or whatnot) (an extreme case, is that currently we have a repository called "nwo_variants" and another one called "new_world_order_variants"))?

Example 1: **270bc** with respect to **total_ancient_war** with respect to **rome_total_war** (taw is a vastly modified version of 270BC, while rtw is a modestly modified version of taw, both are not mods, but rtw is very close being a mod of taw).

Example 2: **world_war_ii_v3** with respect to **ww2v3_variants** (currently a broken collection of external mods; likely to be converted into a pure skin clone, as per similar cases).

Example 3: **world_at_war** with respect to **world_at_war_pbem** or **world_at_war_variants** (world_at_war_pbem is a (currently broken) collection of external mods, while world_at_war_variants is a stand alone map and not a skin clone of others).

Example 4: **new_world_order** and **nwo_variants** and **new_world_order_variants** and **new_world_order_lebowski_edition** and **new_world_order1915lebowski** (only nwo_variants is a skin clone, instead new_world_order_variants is not, nor are the others, but they are all pretty close being mods).

Example 5: **domination** and **domination_1914_no_mans_land** and **domination_1914_blood_and_steel** (BAS is quite close to NML, skin wise, and could have been made as a mod of it, by adding the required assets in the original).

And several others...

My suggestion is to categorise in the "Variants" section only either the ones that would work as mods of the original or, more strictly, only the ones being exactly skin clones of previously made maps. Extending them to also comprising more or less marginally modified versions of originals would open quite the pandora jar, as a matter of deciding what's what and making sense.

On the other hand, while it was previously very easy to know what was a mod's folder and what a stand alone map, now it would, instead, need verifying that all the skin elements are exactly the same, amongst the mods, and keeping doing that at each update, not to miss that maybe someone broke the potential skin compatibility, by making skin changes to one or the other, and not in exactly the same way (example: "Global" gets a bug correction for the skin but the variants are not updated the same way), needing a consequential reclassification of the "variant" outside of the "Variants" section in download list, for coherency, if the decision would be actually listing the skin clones only, there, as I tend to suggest.

**Comment by DanVanAtta** [comment]
@williamdekryger treat the mods as if they were maps. The concept of a "variant" is being dropped. In terms of upkeep, it is up to whoever owns the variant pack to ensure it gets updates from the source map. Previously it was the responsibility of the original map owner to make sure it did not break any of the variants, now it is up to the variants to make sure they stay in check.

**Comment by DanVanAtta** [comment]
I would personally simplify the maps page and drops skins completely, leaving only maps.

**Comment by Cernelius** [comment]
How about having a category for the promiscuous folders only. Meaning folders meant to be freely ownable by anyone wanting to have a mod in them.

In this case, such a category would have all those like **ww2v3_variants**, but not those like **smalls_1939**.

This would make some sense, because you can't seriously rate such promiscuous folders, having mods made by different makers, and more to come in the future. For example, you could argue that the **NekahNets_1939_3.xml** inside **big_world_variations** deserves to stay in High Quality (or at the very least surely in Good Quality), while you may not think the same for all mods being in that folder or added in the future.

Never played myself, but I can tell you NekahNets is hold in high esteem but some of the best lobby players. I think all mods inside big_world_variations are at least good quality, but I'm not sure (only played Smalls_1939.xml, once, years ago).

**Comment by williamdekryger** [comment]
@DanVanAtta @Cernelius I'm not really in favor or against any of these viewpoints. For now, here is what I will do

- Remove the "Map Mods" section from the maps page
- Rename the "Mods and Skins" page to "Skins"
- Leave Mods on the listing of "All"

This will fix the problem without having to use a deprecated feature of the maps listing, or change it in any way. Please let me know if you have any corrections/suggestions.

**Comment by Cernelius** [comment]
Premitting that I'm not the official source of the correct usage of the term "Mod", from what I understood in all these years, they are not anymore "Mods" now, in the sense I believe you mean. "Mods" are xml that refer to the same map of another xml they are modified versions of (and can be inside or outside that map's folder; doesn't matter).
Now the ex "Mods" are just normal "Maps" being skin clones of other ones.
So, there are still mods, but, aside from the remaining broken items not yet updated to be stand-alone (as per directions), all the mods now are supposed to be only inside the same map as the original, never external.

It's not like that if you take ice's WAW40 and move it outside, then it starts being a mod because you copy-pasted it or if you took small's new_world_order_smalls and moved it inside then it stops being a mod.

For example, I could add the ice's WAW40 mod inside new_world_order, instead of world_at_war, and it would still be a mod of world_at_war, not of new_world_order, that you get when downloading new_world_order, but need to have world_at_war to play it.

My last suggestion was a **proposal for a separate category for the Maps supposed to freely have inside (self referring) xml made by anyone.**
This is also to cut down confusion since, if I want to add an xml inside ww2v3_variants, I should be allowed to have it, as long as it is decent enough to have it at all, while more thought should be arguably (but this is highly subjective) put if anyone wants to add a mod inside a not promiscuous map (for example, if I want to put a mod directly inside world_war_ii_v3 or world_war_ii_global).

So, what I'm saying, is that to avoid confusion, I suggest stopping calling those "Mods" (because they aren't anymore), and calling them "Skin Clones", or something like that. Aside from the still broken items, the only Mods left are like the ice's "WAW40" or the regularkid's ww2global40_balanced2_0, etc..

What I mean is that, like, the xml inside ww2v3_variants are indeed mods of ww2v3_variants, but they are not anymore mods of world_war_ii_v3, even tho the skin of ww2v3_variants is currently a perfect clone of the one of world_war_ii_v3. And now it is hard to consider them mods at all, since you don't have a starting xml they are mod of anymore (so, you have a bunch of xml inside ww2v3_variants, but can't really tell what is the mod of what).

**Comment by Cernelius** [comment]
I meant, that assuming that world_war_ii_v3 too gets modified having the the assets inside, like already done for most of the other external collections of mods.

**Comment by DanVanAtta** [comment]
Sorry to be skimming the conversation only. For terminology, calling stand-alone repo's as "variants", and calling the 'extra XMLs' that can come bundled with maps as "mods" will perhaps keep things a bit more sane. Mod is a bit of a catch-all phrase otherwise, and we do have the concept of a map variant already.

@williamdekryger I recommend instead of "Skins" to specify explicitly as "Map Skins". Otherwise,  anything further needed in this issue?
