### ISSUE TITLE
2.6 Three changes of a territory left a factory unable to produce

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#12726]
Saved game, for 1941 Global Command Decision v170, available as a download 
[I11.tsvg](/assets/uploads/files/1721173544740-i11.tsvg)

Supporting text
https://forums.triplea-game.org/topic/3326/1941-global-command-decision-official-thread/708

and a much better explanation from @WCSumpton
https://forums.triplea-game.org/topic/3326/1941-global-command-decision-official-thread/709

and original; post
https://forums.triplea-game.org/topic/3326/1941-global-command-decision-official-thread/702

**Comment by WCSumpton** [comment]
As discussed in the post, what happened here is by rule since option "Abandoned Territories May Be Taken Over Immediately" is false.
Germany invaded Russian owned Baku-Azerbaijan during Round 7. After 7 rounds of combat there was no winner, and Germany did not retreat. Ownership of Industry-Med and Oil-Fields still belong to Russia, but the territory is considered stalemated and no owner.
Russia counterattacked during it Round 7 and failed, losing 9 Lend-Lease-Depot, which were destroyed, and ownership of the damaged Industry-Med and 2 Oil-Fields were given to Germany. This happened during Russia's turn, so, Germany cannot take ownership of territory Baku-Azerbaijan, so the territory remains stalemate with no owner.
On Italy's Round 7 combat movement it entered Baku-Azerbaijan and assumed ownership at the end of it turn, but Italy and Germany are allies so Italy cannot take ownership of the Industry-Med or Oil-Fields.

This is by rule as setup by the map in question, thus this issue should be closed.

Cheers...
