### ISSUE TITLE
Actions and Operations window seize increase request

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#1277]
The “Actions and Operations” window seems to have a default “max seize of a newly opened window” (or whatever we can call it), and this seems to be around **440 pixels in height**. This makes room for 7 lines, but if there are like 8+ Action and operations options, then scrollbars appear and players will have to scroll down – Like some of the below screenshots illustrate.

I know it is neither practical nor realistic to have the window just open up as high as it needs to be to show ALL lines, but **would it be possible to increase the size of this default max seize to be like 660 pixels instead?**

660 pixels seem to be the default seize of the “Download Maps” window. If it is OK to have this seize of window here, it could also work for the Actions and operations window, right? It would give room to display 2 or 3 lines more without the need of scrollbars appearing and players scrolling.

(And yes, I know it is possible to manually ajust the window seize when needed, but it would be nice to have to do this less frequently)

1 Line:
![1](https://cloud.githubusercontent.com/assets/15268177/19054716/ea3e8088-89c0-11e6-8d48-4a1597631735.png)

2 Lines:
![2](https://cloud.githubusercontent.com/assets/15268177/19054724/f01b5d6e-89c0-11e6-9cf7-06da096d572c.png)

4 Lines:
![4](https://cloud.githubusercontent.com/assets/15268177/19054729/f8659908-89c0-11e6-882a-b01e1111ba09.png)

7 Lines:
![7](https://cloud.githubusercontent.com/assets/15268177/19054731/fdf53b58-89c0-11e6-9651-efba514de4cd.png)

8 Lines:
![8](https://cloud.githubusercontent.com/assets/15268177/19054742/0a7c6a04-89c1-11e6-9cda-c1f325c03c0a.png)

25 Lines!!!!:
![25](https://cloud.githubusercontent.com/assets/15268177/19054744/0ecd9128-89c1-11e6-99bf-f8406caeec5a.png)

**Comment by ron-murhammer** [comment]
@FrostionAAA - It appears that the currently popup provides the description section with 2/3 of the screen height and the choices section with 1/3 of the screen height:

```
      final int availHeight = screenResolution.height - 96;
      final int availWidth = screenResolution.width - 30;
      final int availHeightOverview = (int) ((float) availHeight * 2 / 3);
      final int availHeightChoice = (int) ((float) availHeight / 3);
```

I have no idea why that is but my guess is there are some maps with long descriptions for this popup?

**Comment by FrostionAAA** [comment]
OK, so it is not a fixed pixel seize thing but a ratio thing.

Would it be possible to either enlarge this ratio to be like 3/4 of the screen in height? Or maybe even better just open up as high as it needs to be (like the "end of turn report" window seems to do)?

An argument I would like to make to justify this change is that it would (besides hopefully making the Iron War windows look better) also support the windows in Greyhawk Wars. Nearly all the “Actions and Operations” of this map’s players have 7 lines. And with the most used resolution, 1366x768 (according to https://www.w3counter.com/globalstats.php ) the windows on this map also has problems. They just don’t open op large enough. It looks stupid and it’s a shame as there is actually room for them to open op more correctly.

Let me show you some screenshots taken at 1366x768. Some of them is of the "Actions and Operations" of Greyhawk Wars:
NB: No more text follows after the pictures ;-)
![1366](https://cloud.githubusercontent.com/assets/15268177/19094066/8062d0aa-8a8e-11e6-95b4-f027a665a978.png)

![1366-2](https://cloud.githubusercontent.com/assets/15268177/19094069/8728214c-8a8e-11e6-81dc-317f4dd4c6fe.png)

![1366-3](https://cloud.githubusercontent.com/assets/15268177/19094076/8b103510-8a8e-11e6-8b7c-28ded93b1c6c.png)

![1366-4](https://cloud.githubusercontent.com/assets/15268177/19094079/94234372-8a8e-11e6-800f-2c001254facd.png)

![1366-5](https://cloud.githubusercontent.com/assets/15268177/19094084/9bacb894-8a8e-11e6-8e5f-d762afb3f101.png)

![1366-6](https://cloud.githubusercontent.com/assets/15268177/19094088/a14c3e50-8a8e-11e6-8865-cc6a0da649ba.png)

**Comment by ron-murhammer** [comment]
@FrostionAAA So the easy change here is to swap the ratios and have 1/3 for the overview and 2/3 for the choices. My only concern is are there maps that need a large area for the overview portion?

Otherwise this change would result in the Greyhawk Wars example looking like this:
![capture](https://cloud.githubusercontent.com/assets/1427689/19097071/5c1d6560-8a67-11e6-83e8-21e6f51b9a59.PNG)

**Comment by Cernelius** [comment]
What is the overview portion in Actions and Operations???
You mean that you can customise the "You have the following Actions and Operations at your disposal:"??
Are you sure you are not confusing it with the Politics screen?

![mead_political_actions](https://cloud.githubusercontent.com/assets/19562310/19111523/500b1ae4-8b00-11e6-837a-d6d52b6c0216.png)

**Comment by Cernelius** [comment]
Btw, if you would be able to customise the section in which you currently have "You have the following Actions and Operations at your disposal:" with some spiffy image or somesuch, or even only changing that line with something better for the map, that would be really cool, but I think it is not possible.

In my mind, it would be ideal if you can customise the "Actions and Operations" overview and whatever more or less like this:
![ck1-11](https://cloud.githubusercontent.com/assets/19562310/19112133/8d0d9d6a-8b03-11e6-8c79-93d5b9b6bfff.jpg)

**Comment by FrostionAAA** [comment]
@ron-murhammer
Your Greyhawk Wars example looks good and looks like t would fit the size of other large windows. I assume that if a player's resolution is lower than 1366, then there will just be scrollbars like with other windows?

@all. My understanding of the mentioned 1/3 and 2/3 ratio was, that it was exactly what we could see in play in my very first screenshot in this thread. It looks like a 1/3 and 2/3 ratio, even though there is only one Action / Operation choice. But maybe I misunderstood.

**Comment by ron-murhammer** [comment]
@Cernelius - Thanks for the input as I realized the UserActionPanel was created from the PoliticsPanel. The same code was kept from that which is why the height was set that way. I didn't even realize the UserActionPanel overview always said the same thing "You have the following Actions and Operations at your disposal:".

@FrostionAAA - I updated the UserActionPanel to use as much of the screen height for the choices as possible: https://github.com/triplea-game/triplea/pull/1280. Please test on various maps to ensure it works properly.

**Comment by Cernelius** [comment]
If there would be a way for the overview portion to be customizable like the notifications (so, basically, like a notification with choices), that would be nice. Otherwise, I suggest just removing it (not showing the "You have the following Actions and Operations at your disposal:" at all), having only the buttons part, since, anyway, you have already the "Actions and Operations" title. Also, I would surely change the title from "Actions and Operations" to just "Actions"; what's the point of calling that thing "Operations"?
Overall, I think the UserAction is quite bad looking, currently, especially for a game.

Myself, I tend to think ideal would be using only 1/2 of the screen height (definitively 1/3 was too few), not more, but you can set it at whatever value Frostion and Panguitch like it the better, since they are the only ones using it (or planning to use it) to any major extent.

Also, when the vertical scroll bar is needed, this should not cause a pointless horizontal one appearing too, just because the vertical one reduced the useful wideness of a few pixels.

**Comment by FrostionAAA** [comment]
@ron-murhammer 
Besides the fact that the “download maps” window pops up behind the main game startup window, it all seems OK (but...)

I tested out the new “Actions and Operation” window size on these maps: Iron War, Pact of Steel 2 and Greyhawk Wars. I think it looks great. It seems like the window opens up as high as it need to, and maybe at a max of like 98 or 99 % of what the resolution allows. I could see that the 25 options window of Scarlet Brotherhood in Greyhawk Wars opened up to almost the size of what the resolution allowed, but not 100%. Maybe this is just a windows/OS “frame” or windows size determined thing, but it looked OK on my Win 10.

Only the 25 options window of Scarlet Brotherhood in Greyhawk Wars had a minor problem: The longest line has a punctuation mark hidden and this made an unnecessary vertical scrollbar.
![gw1](https://cloud.githubusercontent.com/assets/15268177/19153090/4d99d3c4-8bd5-11e6-9116-6af21780574e.png)

![gw1b](https://cloud.githubusercontent.com/assets/15268177/19153113/740366b0-8bd5-11e6-8dcf-2e1a7fd5c2ba.png)

This problem might be related to this: The End of turn report of a Dragon War map player (with extreme and unrealistically many possessions of resource generating units) can also generate an unnecessary vertical scrollbar as it also hides a tiny part of a text line. In this case the “L” in the word metal:

Note: This End of turn window, unlike the Actions and operations window, cannot be adjusted in height / width. There should just be an up/down scroll bar. But there is also an irritating horizontal scrollbar because the “L” in “Metal” on one of the lines is hidden for some reason.
![dw1](https://cloud.githubusercontent.com/assets/15268177/19153171/9f5be666-8bd5-11e6-96ee-d5f3a36dbe7e.png)

To complicate things even more, this might also be related to something that has bothered me for a pretty long time, on both my old Win7 and now my Win10 PC, and on all versions of TripleA. My purchase windows in ALL maps always has two sets of scrollbars. Every single time I have to do a purchase (on any map) I always use some seconds to adjust the window size minimum 1 pixel more in hight – and the scroll bars both disappear. It looks like this:
![gw3](https://cloud.githubusercontent.com/assets/15268177/19153232/ecb2e9a0-8bd5-11e6-8fa7-89c88ad90875.png)

![gw4](https://cloud.githubusercontent.com/assets/15268177/19153253/06fba7c0-8bd6-11e6-84af-c570f1c3d4c7.png)

**Comment by Cernelius** [comment]
I think the User Actions would be better not spanning the whole screen height, but only 1/2 or at most 2/3 of it, but if Frostion and Panguitch likes it better otherwise it's fine.

On the other hand, I believe the "Political Actions" one is about fine as it is and was.

**Comment by ron-murhammer** [comment]
@FrostionAAA @Cernelius - I decided to remove the static overview section and made some adjustments to fix the width issues when vertical scroll bars appear: #1284. Please test the changes.

@FrostionAAA - Lots of other good points. I'd prefer to open separate issues for each different popup/screen so we can discuss and track testing them.

**Comment by ron-murhammer** [comment]
@FrostionAAA I went ahead and put fixes in for the end of turn report and production window scroll bars as well: #1285 and #1286. Please test these as well as I don't have the same issue on my computer.

**Comment by FrostionAAA** [comment]
I trested it out. Whatever you did, it fixed the problem with two of the issues I listed.

Actions and Operations windows now do not hide the very last of the longest sentence.

Also, the very long (and not likely to happen in a game) end of turn report generated in Dragon Wars does not hide the very last of the longest sentence.

I also looked at the maps and windows concerning Political Actions. This also seems OK.

The changes did not change/fix the issue I have with the purchase window always opening up 1 pixel short in height. So this still happens.

![unavngivet2](https://cloud.githubusercontent.com/assets/15268177/19180866/6aa3d6d8-8c69-11e6-9402-c706f35ff71a.png)

![unavngivet](https://cloud.githubusercontent.com/assets/15268177/19180877/75962550-8c69-11e6-80ca-7a5eb79c9c26.png)

![unavngivet3](https://cloud.githubusercontent.com/assets/15268177/19180889/8ac0f6ee-8c69-11e6-9598-ab2171a8f1ba.png)

![unavngivet4](https://cloud.githubusercontent.com/assets/15268177/19180902/9d82f4c6-8c69-11e6-8e62-6d786e905f2a.png)

![unavngivet5](https://cloud.githubusercontent.com/assets/15268177/19180912/a852f4e6-8c69-11e6-88f9-3adefcb943d8.png)

![unavngivet6](https://cloud.githubusercontent.com/assets/15268177/19181208/befd0f68-8c6b-11e6-9d2a-ceadf02e5535.png)

![unavngivet7](https://cloud.githubusercontent.com/assets/15268177/19181218/cfbb0350-8c6b-11e6-890c-9f4f815069b1.png)

**Comment by Cernelius** [comment]
Doesn't anybody else feel that calling it "Actions and Operations" is not making sense in a strategic game?
I was thinking calling it just "Actions", since with user actions you can do everything you can do with political actions and more (the only drawback is that you don't have the politics overview), thus making "Political Actions" into a subset of user actions.
If not just "Actions", what about "Special Actions"?
Even better might be a customisable "XXX Actions". Frostion would probably call it "Economical Aid Actions".
Any ideas of a better name than "Actions and Operations"? Or do you think it is fine?
Opinions?

@FrostionAAA The vertical scroll bar in purchase has a different cause; I suggest you open a new issue for that.

**Comment by Cernelius** [comment]
But nothing relevant, "Actions and Operations" is decent and if everyone else (mostly Frostion and Panguitch) thinks it looks fine enough, then all good.

**Comment by FrostionAAA** [comment]
I have not given the names of the different "actions" much thought. But, the Actions and Operations is clearly able to trigger a lot of different things, so an "economics" name would maybe not cover all what creative players might set up in different maps. It is a shame that it is only PUs that can be used as payment for the triggers (a payment that the engine can actually  withdraw immediately and that the engine can be sure the to be able to remove). It could be great if the payment could be of any resource type(s). For the political name, what about something with "Diplomatic"? Overall, I think the name are OK right now.

**Comment by ron-murhammer** [comment]
@FrostionAAA - I tried adjusting the height/width slightly for the production popup: #1289. Please test and let me know if that resolves the scroll bars appearing.

**Comment by FrostionAAA** [comment]
@ron-murhammer - I have tested it. We are on the right track but it needs a bit more adjusting.
I opened up a purchase window in TripleA version 3249 and took a screenshot, and did the same in the newest 3258, and then I compared the two.

It looks like the window now opens up a tiny bit larger, both in height and width. (Since a player in my position can make the window look normal by only manually adjusting the height (removing both scroll bars), I would have thought that you would change only height, but maybe you need to do both?)

In the comparison it looks like the window still needs a tiny bit more of the same, as the change you made is just not enough.

Here is an animated gif of before and after (bigger window is after):
![3249-3258](https://cloud.githubusercontent.com/assets/15268177/19211579/07a541fc-8d40-11e6-92c2-d41080f5a237.gif)

**Comment by FrostionAAA** [comment]
@Cernel
Did you once mention on the forum that you or someone else had a similar problem to my described problem, but still different? Something like experiences with the windowe width being too narrow? (I just remember that we discussed this briefly)

**Comment by Cernelius** [comment]
Ok, since you want to discuss this issue in a topic named "Actions and Operations window seize increase request" (maybe change the topic name to be more generic), plus the fact that the so many images already are making it annoying to open:

Yes this is an annoying old problem several people have pointed out and discussed in the development forum over the ages, but noone ever addressed, as far as I know.

To talk about it yet again, this is a problem between TripleA and the text-and-other-elements zoom of Windows. From what I see, you probably have it at 150%; just reduce it to 100% and you'll see everything will be fine.

However, 100% looks bad, because it is way too tiny, and I cannot believe any Windows user can be wanting to have it like that, unless being on 32" monitors or more (but I would still have it at 125% on a 32").

So, this is an issue that I bet many Windows users have, and it has been beaten around the bush several times over the years in the developer forum and other places, but hopefully this might be the last time.

If you use some horrible and very basic themes, like "High Contrast White" (my eyes bleed!), however, you should see that it works fine (but I can't see how anyone would want to have such a theme, aside from playing TripleA). On the other hand, the problems is still present in other basic themes, like "Windows Classic" or "Windows 7 Basic", that anyway I guess almost noone uses.

However, there is a way around it. If you like set it on "High Contrast White" (ahhh my eyes!), then start the game, then change it to whatever other theme, you can keep playing the game without having this issue, and still having your whatever theme otside the game.

I don't know what part of the theme, that is not present in "High Contrast White" but it is present in most others, gives this problem when coupled up with the text-etc. zoom of Windows over 100%.

I'm on Windows 7 (didn't upgrade to 10).

What @ron-murhammer  is now doing is basically a hack, to overincrease the Produce pop-up to accommodate this issue, when it presents itself (which should not); going this way is better than nothing, I would say, but I want to point out that only increasing the height is needed, not the width at all: the horizontal scroll bar is there just because the vertical one takes out space. So, if we go for solving it this way, I suggest @ron-murhammer to set the width back at the previous value and increase the height only a lot more than he already did.

**Comment by ron-murhammer** [comment]
@FrostionAAA @Cernelius I was able to reproduce it by setting windows font size to 150%. Then I tested a few different settings and realized that removing the sizing calls all together appears to allow the window to adjust itself to the various font size settings: #1290. Please test on as many different OS's and font sizes as you can.

**Comment by FrostionAAA** [comment]
I have tested the newest version 1.9.0.0.3263. And it seems to do the trick. I tested with 100% and 125% font size and also with some of the various individual text size options of Windows 10 found in this menu:
Settings and go to System > Display > Advanced display settings > Advanced sizing of text and other items.

Now the purchase windows opens up just as large as it needs to be. Any manual shrinking of the window results in the immediate appearance of scrollbars. Nice :)
