### ISSUE TITLE
Allow multi-hit, capturable infrastructure (trenches)

### ISSUE THREAD

**Issue by jdimeo** [triplea-game/triplea#1335]
(if this issue is redundant with the PR, feel free to close/delete)

I'm in the middle of modding/overhauling Great War with my friend and we want to introduce trenches. At first, we took the Middle Earth approach of having cheap infrastructure with low defense, but then we found ourselves building single trenches here and there as a kind of "mine field" to slow down offensives which doesn't make sense- trenches need defenders to have any value. So instead, we thought trenches should be:
- Capturable - if no defenders are present, the other side can capture the trenches for their defense (happened a lot in WWI)
- Infrastructure - can't move once placed
- No defensive power - once again, useless by themselves, but good for absorbing hits to "protect" the units present that can fire back
- Two hit - they can be "repaired" if damaged but left alone for a turn - incentives attackers to hit heavily fortified territories hard to ensure capture or risk not making any progress, just like the "meat grinders" in WWI. 

The engine almost supports this but needs a few changes. I don't believe this will affect any existing maps/games because it requires a very particular and unusual combination of unit attachments to have any affect. Basically it involves overriding some of the matching for infrastructure (that they aren't "attackable") if multi hit is also present.

I read about the needing a map to use/justify each code change, and we're not quite ready to deploy our Great War mod yet, but we plan to in the next couple months. I just wanted to start the discussion on this engine change so it could be in the next release.

**Comment by Cernelius** [comment]
(not a developer, but I think it is not redundand, but you should link the PR)

Firstly, I want to remember that infrastructures are currently kept in battle, albeit unable to take hits, if they have combat abilities, like an attack / defense value or any supports. Meaning that you can have (and it is indended and supported) infrastructures that take part in battle as bystanders (it is used at least in Rome Total War and Greayhawk Wars).

Secondly, there is still a bug (relevant for Feudal Japan, Greyhawk Wars, and maybe other maps) where infrastructures with no combat abilities are removed from combat and made unable to retreat (like the Horses of Feudal Japan). That still needs to be corrected.

Uhm, interesting case, and ones that has been already proposed. I'm actually making a map in which there are infrastructures that fire AA shots against other infrastructures, the target having multiple hitpoints.
Practically, there is a "Castle" defensive infrastructure that has AA shots against a bunch of units comprising "Engines". The "Engines" unit is a 2 hitpoints infrastructure that just absorbs hits from the "Castle", that would otherwise kill normal units, and it is otherwise useless (it is basically a shield unit for those AA shots only) (I don't like the usual settings in which you have the siege engines that work like modern artillery, but wanted them being totally useless if no Castle in the attacked territory).
If this
https://github.com/triplea-game/triplea/pull/1336/files
gets made, it would be not anymore possible having multiple hitpoints infrastructures siding in battle normal units, but being only possible targets of AA shots.
And I'm not sure if this might be an issue for currently existing maps having infrastructures taking part in combat (probably not, I guess).
What about, instead of deciding if to have an infrastructure taking hits based on it having 2 or more hitpoints, making, instead, a specific option for defining if an infrastructure can or cannot take normal hits?
I believe this would be also better for clarity (you don't have to know that multiple hitpoints infrastructure behave one way and single hitpoints ones behave another) and it would allow you to also have capturable and hittable units having 1 hitpoint only, not obliging you to restrict this concept to multiple hitpoint ones only (which I don't see why it should be restricted to 2+ hitpoints only).
For example, then you could make the Fortress of Napoleonic Empires capturable, despite that they take hits and have only 1 hitpoint, not being obliged to give them 2 or more hitpoints in order to have that behaviour.
This would have a more extensive use, as I can se many cases in which you may want to be able to capture units that you "kill" in combat but you want them to be 1 hitpoint only (for example, Napoleonic ships or artillery (likely to be also coupled with a downgrade upon capture, which is already possible)).
Another thing, is that it may be cool having like not-capturable units that cannot be normally hit. For example, you may want to have "air" units that are not capturable, but cannot be normally hit, but can take shots only from AA. This would be interesting in a WW1 map, so you could avoid that your fighters can be used as fodder in naval battles between battleships, which really doesn't make sense, in WW1.
So, I would much rather suggest having a boolean option like:

`<option name="isNotAttackable" value="true"/>`

When this option is not set, it defaults to false normally, but default to true if the unit is an infrastructure (making everything behave exactly like now).

If set to false for an infrastructure, it does exactly what you want to (but you can have it also for 1 hitpoints capturables, not only 2+ hitpoints (practically, **I suggest checking if that specific option is false, instead of checking if the infrastructure has 2+ hitpoints**)).

If set to true for an not-infrastructure, it makes the infrastructure not normally hittable (of course, it would be likely up to the mapmaker to setup AA shots for hitting such units, to avoid having indestructible and uncapturable units going around).

Would this be a feasible alternative?

(in general, I suggest making such things by adding stuff that doesn't change any current behaviour, because, with so many maps, you can hardly be sure you are not changing / bugging some crazy stuff somewhere, and I really don't see why capturable and hittable units must have 2+ hitpoints, and can't be 1 hitpoint too)

**Comment by Cernelius** [comment]
Or, to restrict it to your needs only, it may be just

`<option name="isAttackableInfrastructure" value="true"/>`

that it is an allowed option only for units also having:

`<option name="isInfrastructure" value="true"/>`

(meaning that if the first is true and the second is false the game won't be validated)

And:

if "isAttackableInfrastructure" is false, everything works as now;

if "isAttackableInfrastructure" is true, the infrastructure works as you want to (but you can have it also for 1 hitpoints capturables, not only 2+ hitpoints (**practically, I suggest checking if that specific option is true, instead of checking if the infrastructure has 2+ hitpoints**))

**Comment by Cernelius** [comment]
I think such an option would gain a lot of popularity amongst mapmakers of complex maps, especially coupled with the already existing:
`whenCapturedChangesInto`
This may be a very cool feature addition.

**Comment by Cernelius** [comment]
But, I'm not sure if I understand correctly. Are those units supposed to be normally capturable (during combat move) if left totally alone but not capturable at all (during combat) if there is an not infrastructure unit avoiding their capture during non combat move, or are they capturable after having killed them?

I mean like I get that the enemy will capture 4 trenches if left totally ungarrisoned, but if there is 1 infantry and 4 trenches defending will no trenches at all be captured or will those 4 trenches (you killed during combat) be captured upon winning? If the trenches are always captured if left totally alone but never captured otherwise, I don't think this would make much sense, and I'd rather suggest you going for having the trenches as infrastructures giving support, instead of taking hits, and always capturable, both if left alone or if conquered in battle (look at the Forts of Rome Total War).

**Comment by Cernelius** [comment]
I meant, I don't want to be negative, it is still an interesting option. Just saying that I tend to think it would make more sense (and being more realistic) if you also capture those trenches after having "killed" them, not only if they are totally undefended. Was just asking because I'm not sure if I understood correctly, as I initially though this was the matter of making infrastructures hittable and capturable, but maybe the matter is merely limited only to making them capturable during combat move only, if totally undefended, and being just like normal combat units (never captured) if defended?

My main problem would be that I actually want to have 2 hitpoints infrastructures (hittable only by AA) in a map of mine (I've played it, and it works), but I've not finished it, and I don't know if there are any maps with multiple hitpoints infrastructures, currently (I might, for example, think about two "infrastructure" hero units, that can AA-fight each other, while supporting other units or whatever).

**Comment by Cernelius** [comment]
If I previously understood wrongly, and the matter is just having units that are captured if left alone, but are totally (not capturable) normal combat units if sided by at least 1 normal combat unit, then I rather suggest having an option for non-infrastructure units that, when true, make them capturable upon entering or before battle, when in a territory there are only such hostile units or infrastructures.

Or, in my mind, it could even be a property related behaviour if in a territory there are only units with 0 att/def that they are instantly captured/destroyed, instead of, like, obliging you to keep rolling till killing all of them.

Sorry for the many posts, I'm now thinking that in my previous ones I assumed you wanted units that you kill and then you capture after having killed them and taken the territory, but now I guess this is not what you want? I guess I just understood it this way, because it is how it would make the most sense for trenches to behave, in my mind (that you capture the trenches both if they are defended and if they are undefended, but not "for free" if they are defended).

**Comment by ron-murhammer** [comment]
@Cernelius Can you briefly summarize your thoughts on this? 

@jdimeo So you essentially want any infra units that have more than 1 hit point to be allowed to be in battles and take casualties (in your case a 0A/0D/2HP infra unit)? But infra units that only have 1 hit point can't take casualties? Wouldn't it be better to have trenches be infra unit that have 0A/0D but provide say +1D support to 3 units?

**Comment by Cernelius** [comment]
I will delete my old posts and make a new one once the matter is clearer to me.

Initially I thought that he wanted to have capturable infrastructures being able to take hits, then being captured (probably because in my mind it made the only sense that trenches are captured, both if undefended and after having killed their defenders), but now I think instead maybe the matter is just having them as capturable infrastructures if left totally alone and just as normal units otherwise? Also I wonder what will it happen if a combat starts with hittable infrastructure + normal units and at any point of it only hittable infrastructures are left?

I tend to think that if the matter is just having them captured if totally left alone, it would be better to just have a property for making stacks of not-infrastructure att/def 0/0 units being immediately captured/destroyer (since, anyway, it would make sense that if you attack 1 ballista with 1 velites, the ballista dies immediately, not requiring you to roll at 1 against 0 till you get a hit).

Anyway, having a behaviour with 1 hitpoint and another one with 2 hitpoints sounds weird to me; so, whatever it is, I suggest doing it with a specific option, or anyway in a different manner than checking for 2+ hitpoints.

**Comment by jdimeo** [comment]
Thanks for the great feedback! I agree that I was uneasy about having different behavior based on number of hit points is not ideal.  I like a new `<option name="isAttackableInfrastructure" value="true"/>` option, but I was trying to avoid another subtle/special case option if I could help it (there are so many already).

@ron-murhammer Yes. I want infra that, if other units are present, can be taken casualty even if 0D, but if no other units are present, are capturable upon entering. Your idea is really good and gets us mostly there. There's a subtle difference in combat dynamics though- with what I'm envisioning it makes the defenders "harder to hit", vs "stronger". Say you attack 3 trenches (2 hit 0 def) and 1 inf (2 def) with 6 inf (low luck). It would take you at a minimum of 7 rounds of combat to capture the territory even if you got a hit every time, which gives the lone defender 7 rolls at 2 or less to defend.  Instead of the scenario you proposed where 6 inf vs 1 inf would be over very quickly, even if the inf's strength was boosted due to trenches. But, if the defender abandons that front, the trenches can't fight on their own and are therefore capturable. Finally, if trenches are 2 hit- say the defending inf scores 3 hits in a row and the attacker decides it's not worth it. Even if they got 3 hits on the trenches (1 on each), they'll repair next round and the attacker will have sacrificed 3 inf for nothing (very realistic to WWI).

In any case, my PR as it is is almost certainly not the right way forward.

**Comment by jdimeo** [comment]
@Cernelius " but maybe the matter is merely limited only to making them capturable during combat move only, if totally undefended, and being just like normal combat units (never captured) if defended?"
Exactly.

**Comment by Cernelius** [comment]
Gameplay wise, unless you have very costly fodder or very few income, wouldn't this (abandoning 2 hitpoints and att/def 0/0 trenches) be a very rare occurrence?

I mean, it is very common to leave 1 cheap unit to trade territories; with a trench that is 0/0 and 2 hitpoints, I can very rarely see people not leaving at least 1 "infantry" there, since that infantry would become a 3 hitpoints unit with 1 trench, and more with more trenches.

I'm thinking that if those trenches get also captured, this is actually going to almost never happen, because anybody will almost never let that happen.

On the other hand, something like that would be somewhat needed, gameplay wise, otherwise when it actually happens that you decide to abandon a stack of trenches, then your opponent might decide to attack them with an attack=1 unit, and you would need to keep rolling and rolling till all trenches are gone, which would be ridiculously tiresome. This is something I already considered, that is a substantial general gameplay problem against having defence 0 units with hitpoints.

I have to think more about that, but I definitively think this should not be done depending if the unit is 1 hitpoint or 2 hitpoints, but should be set independently from that (so that it will be possible both if you want to have 2 hitpoint trenches or 1 hitpoint trenches or whatever), and possibly also solving the general problem of speeding up the inevitable kill of defence 0 stacks.

**Comment by Cernelius** [comment]
Side note, making the defender _"harder to hit" vs "stronger"_ is also possible by giving defending trenches the ability to give negative defence support to enemy (attacking) units (for example, 1 trench reduces from 2 to 1 the attack value of 1 infantry, and maybe the infantries are all att/def 2/3 base), which is what Civil War does, but I get there are other items you want to achieve, so this would not be a good enough solution for you.

**Comment by jdimeo** [comment]
"Gameplay wise, unless you have very costly fodder or very few income, wouldn't this (abandoning 2 hitpoints and att/def 0/0 trenches) be a very rare occurrence?"

Exactly- once you've built up trenches, you're highly motivated to keep at least one unit in every territory and maintain the "front". You would be surprised though, sometimes in testing my friend or I would pull out the last infantry to defend a neighboring territory, for example if it had a factory and you needed every last unit to swing the odds in your favor.

**Comment by Cernelius** [comment]
Ok, so, now that we have clarified most, I delete my previous unreplied Posts and reexplain the matter.

Infrastructures having hitpoints is currently not useless; as infrastructures can be target of AA gun and can partake in air battles (don't know if it is intended or just a by-product, but it works). For example, you can have air units that are infrastructures, but they will be hit by AA attacks and may take part in air battles.

I'm not aware of it being used in maps currently in the repository (but it may be it is).

For example, in your map, currently, you could have the "trenches" as capturable infrastructures giving support, plus having the "artillery" units having an additional AA offensive attack against "trenches", meaning that the "trenches" will participate to the battle as by-standers, giving support to other units, but not taking normal hits, while only the "artillery" will be able to destroy the "trenches" in a special strike before either combat round 1, or all combat rounds or a limited amounts of combat rounds since the first (this is settable too).
This way, for example, if you want to capture the trenches, you can decide to send in attack the "infantry" only, not the "artillery", and, then, after winning the battle, you would be able to capture all defended "trenches" without harming them. Or you can have "light_artillery" not damaging the "trenches" and "heavy_artillery" destroying them, or whatever.

I'm not aware this possibility (infrastructures with hitpoints hit by AA attacks) is used in any maps (even tho it is possible that there are maps around or under development using it and I don't know; I'm thinking about the map that "m3tan" was (is?) making, in particular), nor I know if this was intended at all; however I'm using it in a map of mine I've not yet finished (I can give more detail, if anyone is interested), and anyway I think it is an interesting possibility, albeit quite hidden, so I ask for it not being removed.

**Thus I suggest, instead of relating this to the hitpoints an infrastructure has (it definitively makes no sense in my mind that 1 hitpoint works one way and 2+ hitpoints work another one) or even forcing all infrastructures, not taking part in combat, to have 0 hitpoints (thus I assume removing the possibility of hitting them with AA attacks), I suggest doing what you want with a specific option:**

`<option name="isAttackableInfrastructure" value="true"/>`

that it is an allowed option only for units also having:

`<option name="isInfrastructure" value="true"/>`

(meaning that if the first is true and the second is false the game won't be validated)

Or, as I said, if you want to make a more involved map as a matter of representativity, you can have "trenches" as normal infrastructures giving defensive support (like attack malus to enemy units (which would also allow you setting bigger malus for "cavalry" than "infantry")), while giving "artillery" an offensive AA attack ability against "trenches", that already works. You can also give "trenches" 2 hitpoints each, and have "light_artillery" taking out 1 hitpoint upon AA-hitting, and "heavy_artillery" instant-killing upon AA-hitting (you need to set "damageableAA" true to not kill instantly).

Since "infrastructures" can take part in battle as by-standers (hitting themselves or giving support, without being hit (for example, Rome Total War does both)), I believe they should be still hittable by AA shots as well (thus, having hitpoints), and, in a map I'm making, I actually use double hitpoints infrastructures that can be AA hit by other infrastructures.

Beside your own case, this would also solve the issue of having defense=0 hittable units, that should rather be all destroyed if left alone, instead of having to keep rolling and rolling till inevitably killing all of them, and this could be done by making them attackable infrastructures that are destroyed upon capture (once having the "isAttackableInfrastructure" option; rest is already there).

**Comment by jdimeo** [comment]
I'm having a hard time following your logic because what I was suggesting doesn't have anything to do with AA or air units (at least not directly). Where does that piece come in? thanks for thinking about this with me!

**Comment by Cernelius** [comment]
Many options in TripleA have not very well descriptive names, in many cases because they were expanded. For example "isAA" doesn't mean that "it-is-an-anti-air-gun", but it means that it is something that can make attacks (which means defensive special shots, not offensive; otherwise they are called "offensiveAttack") against some specific units, the default only being all air units (but you can set to whatever).

Maybe you understood AA as I was talking about "anti air", which I wasn't specifically. AA attacks is how they are called ("isAA" etc.), but it doesn't mean it is an anti-air gun (I though this was clear enough, since I was talking about AA attacks against trenches). Default is to all air units, but you can set to whatever. Also, AA attacks doesn't mean that they are attacks, and they normally are not "attack" attacks; the default is actually for defence; the AA attacks that are actually for the "attack" are called offensive attacks, while the normal AA attacks are defence only, not attack.

Infrastructures can be hit by AA guns, thus them having hitpoints is not pointless.

As I said, currently, for example, you can have "trenches" that are always infrastructures that cannot be normally hit, and, then, having "artillery" that makes offensive AA attacks (which doesn't mean anti-air) against the "trenches", beside whatever normal attack or defence, they may or may not make.
I know that this works fine, but I don't know if is actually a wanted behaviour; anyway I have 2 hitpoints infrastructures attackable by AA attacks (doesn't necessarily mean against air units) in a map of mine, thus I'd like the ability of an infrastructure to have hitpoints and be AA attacked to be kept as is.

This is why I'm suggesting obtaining what you want via an added:

`<option name="isAttackableInfrastructure" value="true"/>`

and leaving all the rest as it is.

Regarding units able to make AA Attacks (not necessarily meaning shooting at air units), for example these are only some of the options:

```
                         <option name="isAAforCombatOnly" value="true"/>
                         <option name="maxRoundsAA" value="1"/>
                         <option name="damageableAA" value="true"/>
                         <option name="typeAA" value="aaa"/>
                         <option name="targetsAA" value="bbb"/>
                         <option name="maxAAattacks" value="2"/>
                         <option name="attackAA" value="3"/>
                         <option name="mayOverStackAA" value="false"/>
```
The "targetsAA" allow you to freely set the targets for that AA capable unit. Only if you don't set it, then the default is to all air units (comprising infrastructures, if you have flying infrastructures).

The "targetsAA" can be also infrastructures involved in combat as by-standers (and eventually able to attack themselves or give/receive support; look at the Fort of Rome Total War).

As I said, "attackAA" means that they don't attack, but defend only; if you want them attacking, you need "offensiveAttackAA", instead (they can be both set).

Regarding the 1 more option thing, it is up to the developers, but I personally surely believe that 1 more clearly explicative option is much better than a somewhat hidden behaviour. And, anyway, as I see it, beside your need, that option would be quite useful in general to make possible to autokill stacks of power 0 units, instead of having to roll and roll till they are gone, for example for other games having purely hit-absorbing units like No Man's Land (you would just need to have them attackable infrastructures that are destroyed upon capture).

I'm not really arguing against what you want or trying to make things more difficult; sadly the AA thing is ramified and difficult to explain. I'm just suggesting doing it with an _"isAttackableInfrastructure"_ option that kicks your infrastructures into the combat when it is set true, which seems the most safe and understandable way to have this behaviour (in place of looking if the unit is 1 or 2+ hitpoints or whatever else of the currently existing options, that are already meant to do other stuff). And for the AA thing, I was just pointing out that, for infrastructures, having hitpoint is not currently necessarily useless (if there are AA set to target them, which is what I have in a map of mine). Infrastructure just means that can't take normal hits and it is captured/destroyed if alone, but it can still take part in the battle attacking and defending or giving and receiving support, and eventually be also hit by other units with AA abilities (for example, you can have a transport "aircraft" being an infrastructure, or a land transport infrastructure, as well; look at the Horse of Feudal Japan).

**Comment by Cernelius** [comment]
I didn't mean to make what you want harder, and didn't know that adding 1 more option is very hard.

What about using the existent:

`isCombatTransport`

That when set "true" for an infrastructure would do what you want (having the infrastructure taking hits). The option may be renamed as "isCombatUnit"? I think this option is used only in a few maps. This way this option would have the double function of making your transports fight and making your infrastructures take hits, which are somewhat similar matters.

**Comment by Cernelius** [comment]
> But yes, `<option name="isAttackableInfrastructure" value="true"/>` is a good idea as long as we don't mind adding yet another subtle option to the game file.

Up to the developers if they are sick of options, but I don't think the matter is too marginal here, and may well deserve a specific option; I can see a general application for all immobile hit-taking units with defence 0, and not only those.

I think I may actually use that option myself for a mod of Napoleonic Empires, making the "Tower" defence 0 and cost 2 (1 hitpoint).

For example, I always thought that "Lord of the Rings: Middle Earth" would have been better with "fortifications" at defence 0 and cost 1, instead of the current defence 1 and cost 1.5 (by 2 for 3 PUs) (at least because I really hate being obliged to buy 2; it makes no sense), but I would not do it, because, then, it can happen that a territory has like 6 fortifications, but then it is left alone and the enemy sends 1 orcs to kill all of them, and you would need to keep rolling and rolling till you score 6 hits at 1/6 each roll! As I said, this option would solve that problem, by making the fortification an attackable infrastructure destroyed upon capture.
Defence 0 hit-absorbing units is not such a strange concept; for example, "Domination 1914 No Man's Land" has exactly the same "trench" units as you want to have (I guess you copied it?). I don't know how the guys playing that manage it, when they maybe attack undefended stacks of trenches with 1 guy (I guess very rare); I suppose they edit them out and edit all the rest, instead of keep rolling for tens of times.

I'd just not trade it for the current ability of AA-hitting infrastructures having whatever hitpoints (that I'm also using in a map of mine (to represent medieval siege engines vs castles) I intend to propose for download list).

**Comment by jdimeo** [comment]
Here's what I have now:
```
<attachment name="unitAttachment" attachTo="trenches" javaClass="games.strategy.triplea.attachments.UnitAttachment" type="unitType">
	<option name="movement" value="0" count=""/>
	<option name="attack" value="0" count=""/>
	<option name="defense" value="0" count=""/>
	<option name="isConstruction" value="true" count=""/>
	<option name="isInfrastructure" value="true" count=""/>
	<option name="constructionType" value="trenches" count=""/>
	<option name="constructionsPerTerrPerTypePerTurn" value="2" count=""/>
	<option name="maxConstructionsPerTypePerTerr" value="10" count=""/>
</attachment>
<attachment name="supportAttachmentTrenches" attachTo="trenches" javaClass="games.strategy.triplea.attachments.UnitSupportAttachment" type="unitType">
	<option name="unitType" value="infantry:fieldArtillery:cossack:mechInfantry"/>
	<option name="faction" value="allied"/>
	<option name="side" value="defence"/>
	<option name="dice" value="strength"/>
	<option name="bonus" value="1"/>
	<option name="number" value="2"/>
	<option name="bonusType" value="artillery"/>	
	<option name="players" value="Russians:Germans:British:French:Austrians:Ottomans:Italians:Americans:Bolsheviks"/>
	<option name="impArtTech" value="false"/>
</attachment>
```
Pros:
- The trench is useless by itself, but provides a boost of 2 defense to defending units
- It can be captured if left undefended
Cons:
- It's always captured and never destroyed- a huge stack of trenches instantly switches sides and provides a lot of defense to the new occupant, which doesn't reflect the damage that would've happened during the battle
- It can't be taken as a hit and absorb hits, thus it doesn't "prolong" the battle, it simply means the attacker will lose more

So yes, I think we do need some property that indicates it's capturable AND attackable. Unless something like that does exist and I'm not aware of it.

**Comment by DanVanAtta** [comment]
@jdimeo @Cernelius Seems like the conversation has come to a resting point. Please feel free to re-open if there is more to add to this topic, will close in the meantime.

**Comment by jdimeo** [comment]
I still need this for my map- waiting for a dev to weigh in on the best way forward. In the current engine, I either have to have the trenches not be capturable (which leads to battles that takes tons and tons of rounds while a single infantry whittles away at a stack of 10 2-hit trenches) or I have to give the trench a non-zero defense to have it participate in battles (instead of just being a bystander like a factory). I would love a setting that gives me both (0 defense + 2 hp but capturable if no other units present).

**Comment by DanVanAtta** [comment]
Thanks for the quick response, I will re-open to indicate this is a fresh/ongoing issue.

**Comment by Cernelius** [comment]
> I would love a setting that gives me both (0 defense + 2 hp but capturable if no other units present).

Considering that these units would be primarily normal combat units, and the behaviour of being, instead, captured if alone is the factual exception, I suggest adding a special property called:

"**isCombatInfrastructure**" (boolean)

this property would:
Set "isInfrastructure" true.
Allow this unit being taken as casualty, if any other units that are not "isInfrastructure" are still present

When this is true, what happens is:
If all units of one side are all "isInfrastructure" (comprising also "isCombatInfrastructure"), combat ends immediately (or doesn't even start) and they are all captured.
If not all units of one side are all "isInfrastructure" (or "isCombatInfrastructure"), you can take as casualties not-"isInfrastructure" units plus any "isCombatInfrastructure" ones, but not any other "isInfrastructure" ones.

Code wise, what you are going to do is just testing for presence of not-"isInfrastructure" ("isCombatInfrastructure" are "isInfrastructure" too) when you have to see if the combat goes on but, then, add up also the "isCombatInfrastructure" to the casualty list you can / must select.

p.s.: You already don't need to kill defenselles units. For example, in v5, if 1 infantry attacks 3 AA-guns that are alone they are all destroyed; the infantry is not going to keep rolling dice at 1 till scoring 3 hits (in averagely 18 combat rounds). If that is not working for your defenseless unit, you should see what it is impeding it and consider if an engine behaviour change may be advisable.
p.p.s.: Theorically, you could already obtain this with all a serie of triggers testing a lot of stuff, but that would be a massive amount of triggers.
p.p.p.s.: Going hacky all the way, you can already mostly obtain your wanted behaviour by triggering in and out "isInfrastructure" for the unit respectively at start and end of CombatMove. You can consider this as an intermediate step while you wait for coding it properly in the engine.
p.p.p.p.s.: Not up to me to decide what is what, but this seems a "feature request" discussion to me (just saying, since we are discussing)...

**Comment by ron-murhammer** [comment]
@Cernelius @jdimeo This is definitely more of a feature request and I think a number of folks probably have thoughts on adding something like this. I'd recommend creating a thread in the forum here that can be used to discuss how folks think the feature should work: https://forums.triplea-game.org/category/42/feature-requests-ideas
