### ISSUE TITLE
Moderator "Report Infraction" feature

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1341]
Eventually instead of moderators having to decide if/when/how to ban/boot someone, we will instead keep track of an 'infraction' count, and standard actions will happen at certain levels. 

For example, 1 infraction -> warning message. 2 -> mute for 5 minutes. 3 ->  boot for 10 minutes, 4 -> boot with 1 hour, etc..

Please assume for this conversation that we can uniquely identify users. Let's solve/discuss that problem in a different conversation. For now I would like to discuss the idea of taking automated actions based on an 'infraction tally'. Only moderators would be able to add to the 'infraction tally'. 

To roll out the feature we would just add it as an additional right click menu option, and see how it goes from there.

**Comment by yamamot0** [comment]
An improvement would be 
1) a automatical mod-action report with action and reason (!) of action 
- assuming we can "uniquely identify users", which we cant at the moment:
2) a log with date, actions and reasons against a player, which you can read from the lobby

an Infraction tally need to adress the problem that each kind of violation need another kind of response.
Some violations gets 5 warnings, others only one. The reason is crucial, not just the fact of a violation.
