### ISSUE TITLE
Map Bug Tracking

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#1344]
So I think we need to decide how we want to track bugs in maps. In theory, we have the issues under each map but this tends to make it so they are never looked at again. My initial thought is for all maps that have no current owner and are in high quality that the bugs should stay here. Anything else gets pushed to the appropriate map repo. An example of this is #1331 which I think should stay here as otherwise it might never get fixed.

**Comment by Cernelius** [comment]
Yeah, I also feel that is very dispersive. If I see a bug in a map, opening an issue in that repository really feels like nobody will see it ever, or close so.
I really don't like seeing purely map bugs being labeled here as Bug either, which should be better reserved to engine bugs only.
It is bad either ways; and the Issue section is still there in the single repositories, which means duplication and confusion about where to have the Issues.

Myself, I think the bugs of a map should stay in the repository of that map only, but is there a good way to know and, most importantly, don't miss all maps bugs? If a map like "Big World" or "WWII Global" is broken, that has an importance similar to a major engine bug, and would be bad not noticing it for a long time.

Visibility, beside the fact that it may matter for multiple maps, is the reason why I didn't post this inside the "big_world" repository, but I really dislike to see this being labelled as a "Bug" here in the Engine repository, as that should be for the Engine bugs, that is not:
https://github.com/triplea-game/triplea/issues/1332

Besides, even under the excuse that it might matter for other maps, I should rather have posted it in:
https://github.com/triplea-maps/Project
(also, can you stick that repository to be always at the start of the list?)

Moreover, most people won't really know if a bug is engine or map (and even mapmakers may get confused), thus, either a place where to post all bugs, no matter what, or people moving them around (if it is possible at all to move an issue from here to a map repository?) would be still needed.

There is no way a normal user that see something in "Global" not working will be able to know if he has to open an issue in that map repository or here, really... Rather let normal users report them in forum, then open an issue only after somebody knows what the problem actually is.

**Comment by Cernelius** [comment]
Mostly, I really don't like seeing the "Bug Backlog" label here:
https://github.com/triplea-game/triplea/issues/1332

As when I click on "Bug Backlog" here I would imagine to see everything and only that is not working fine in the engine (there is no engine bug at all related to that issue).

**Comment by ron-murhammer** [comment]
Maybe keep them here but use a different label for map issues?

**Comment by Cernelius** [comment]
Well, there is the other side of the coin that you may have a plethora of map bugs of experimental maps nobody cares about that may remain there forever but should not be closed either, and they should be better to stay in the maps repositories, to be seen just by anyone interested of eventually taking over the map.

**Comment by ron-murhammer** [comment]
Yep. That's why we'd just keep bugs for high quality maps with no active owner here. Everything else would go to the map repos.

**Comment by Cernelius** [comment]
If possible, I'd rather disable the ability to open Issues in all repositories, and concentrate them all in:
https://github.com/triplea-maps/Project
Then you could just add labels like "High Quality" and "Map Bug Backlog" etc..

Or if some people want to keep an eye on the repos and update a page in the Wiki here with the issues of High Quality maps, that might work too.

I get the point of not missing popular maps being broken and not being flooded by maps bugs, but this sounds really patchy.

**Comment by Cernelius** [comment]
In my mind the best would be having 1 issue tracker for the engine and 1 issue tracker for the maps in the repository.

For the issue tracker for maps, then you could add the "bugs" etc. and "high quality" etc. labels.

I think having all maps' issues tracked somewhere in:
https://github.com/triplea-maps/
makes the only sense, but it is bad having them dispersed into the single repositories, so that you have to check them all to see what issues are open (practically, the current system is fine if you just want to know all issues about a map, but it is very bad if you want to know what maps have issues).

This is why I suggest disabling the opening of issues in the repositories (if possible), and concentrating them all in 1 single repository; probably this one (which should be better always being pinned top list):

https://github.com/triplea-maps/Project

Otherwise, you give more visibility to High Quality, but bury the rest even more.

I'm not sure if that repository is much checked by the developers; for example, it seems that panguitch is having problems updating his map since a while, and opened an Issue 11 days ago:
https://github.com/triplea-maps/Project/issues/64

I've no clue about the matter, but if a smart guy like panguitch can't figure out something and even seems totally stuck, that's a bit worrying... Hopefully some developer will find some time to teach him (and maybe update the instructions, if this is the matter), but I'm wondering if the Project currently suffers a visibility problem too.

**Comment by Cernelius** [comment]
As a side note, since you made the case of Great War, at least in lobby there are several mods (currently in Experimental) that, even if not popular, are definitively much more played / popular than that map (which looks being very rarely played). It is good to have categories, but they have never been that defining.

For example, in lobby _Big World : NekahNet's 1939_ alone is seldom played, but I believe it is still like 10 times more played than the seemingly very niche _Great War_, and that's just one of the mods in that folder, currently in experimental (like all ex external mods).

**Comment by DanVanAtta** [comment]
> "I'm not sure if that repository is much checked by the developers; for example, it seems that panguitch is having problems updating his map since a while, and opened an Issue 11 days ago:
triplea-maps/Project#64"


I've been tracking updates, but it's been a bit pressing/difficult to respond. It has been a really busy last 2 or 3 weeks for me, will continue to be for another week. So it's more developer availability at fault rather than failing to see the communication.

>  This is why I suggest disabling the opening of issues in the repositories (if possible), and concentrating them all in 1 single repository; probably this one (which should be better always being pinned top list): https://github.com/triplea-maps/Project

I think I like this idea. I agree with a lot of the comments so far that many queues is good way to lose issues, but also keeping them all grouped with the game engine issues is not necessarily wise either. Keeping the 2 queues minimizes the locations, pretty logical grouping. We will still have map issues in the game engine queue, but IMO we can train folks to avoid that.

It also simplifies the code a bit for the map feedback, we can probably remove the give map feedback button in the download screen and keep only the option in the in-game drop down menus.  (simplifying code is good, and we can do this since before it was programmed to open up the right map issue queue when submitting map feedback).

**Comment by ron-murhammer** [comment]
Alright, let's go with that then for now. We'll use https://github.com/triplea-maps/Project for all map specific issues.

**Comment by Cernelius** [comment]
Any ideas about a good way to make clear that maps issues should be posted inside
https://github.com/triplea-maps/Project/issues
and not in the maps repositories or here or somewhere else?

For sure, it would be needed to change:

_Project Tracking - Issues global to all maps_

to something different, making clear this would be not anymore just for shared issues (which I guess would be a very rare occurrence), but for specific maps' issues, that, until now, have been posted in the repositories.

Also, is it possible to move the Issues already posted in the repositories to project?

It is possible and it has been decided to fully disable Issues in the repositories, correct?

**Comment by Cernelius** [comment]
Posted here even tho the issue is closed cause that are just clarifications / confirmations; didn't want to open a new one for them.

**Comment by DanVanAtta** [comment]
yeah, we should keep track of some follow on tasks.
The code needs updating to reflect this. 
We also need to do some documentation updates in the README and over in the map project repo too (which claims to be deprecated).

**Comment by panther2** [comment]
In the context of this discussion:
- Who actually is the "owner" of a map?
- Who actually is responsible for the map repos?

**Comment by ron-murhammer** [comment]
Owner is essentially who created the map or if they have been inactive for a long time then whoever has taken ownership and made updates.

The developers are responsible for the map repos as a whole but owners are responsible for their individual repos.

**Comment by ron-murhammer** [comment]
@DanVanAtta I think we need to make a decision on this on either:
1. Keep map issues in this repo (triplea-game) and tag them as such
2. Keep map issues in https://github.com/triplea-maps/Project

After we decide on the preference there, then we just need to update documentation/code to meet that.

**Comment by ron-murhammer** [comment]
So based on number of issues opened, I think its better to just keep the issues in this repo. As we end up not using the other repo much and end up not checking it.
