### ISSUE TITLE
ts_users db change not taking effect in 1.9 lobby

### ISSUE THREAD

**Issue by americanknight** [triplea-game/triplea#1352]
At the request of prastle, I updated the 1.9 user db using the following SQL commands and they take effect in the 1.8 lobby but not the 1.9.

I made the following changes and it looks like they take effect on the old 1.8 lobby but not the new one.
Logged into lobby server as tripleA account. 

sql update ta_users set admin=1 where username='AmericanKnight'

When I run this command to see admins,
sql select * from ta_users where admin=1

 user DB is updated but  does not take effect in 1.9 lobby, rather it does in the 1.8 lobby. Any suggestions?

Respectfully,
AmericanKnight

**Comment by DanVanAtta** [comment]
Which DB file did you use?
Also, how did you connect to it? I'm very curious about this for personal edification.

**Comment by americanknight** [comment]
I have since learned much more about what is causing this. Was editing ta_users which as it turns out was using the 1.8 lobby files.

 

The 1.8 lobby was hosted in a screen which also included a SQL tool as part of the app screen. The way I edited was using the SQL tool loaded with that lobby app screen. Hence this explains why it wasn’t loading in the 1.9 lobby.

 

Working now of seeing if we can configure the 1.9 lobby to load in a script similar to the one that was used for the old 1.8 lobby so it will load the sql tool and be able to be managed in screens by the mods with triplea account user access.

 

AmericanKnight (Joey)

**Comment by ron-murhammer** [comment]
@americanknight @DanVanAtta Just to add the rest of our conversation here:

I believe you are correct regarding needing to launch to 1.9 lobby in a screen. I think Dan was messing around with lobby/bot scripts and didn't launch it in a screen so we don't have any way to edit the database through the SQL admin tools. Feel free to take a stab at relaunching the 1.9 lobby in a screen and the best time to do it is late at night when few people are in the lobby. I'll hopefully we around some this weekend.

Oh and in case you haven't seen these are the best instructions regarding lobby/bots/database that I know of: http://www.tripleawarclub.org/modules/newbb/viewtopic.php?topic_id=1479

I think they should still be mostly relevant for 1.9.

**Comment by DanVanAtta** [comment]
Latest, todo:
- when launching a derby_db request, say `select * from ta_users`, the UI freezes and never completes the DB round trip.
- we need to investigate / find out why this is happening and fix. 

We have a migration ticket, so we would like to get on a new DB. If we fail to find a fix a plan B would be to migrate to a new DB: #1041

**Comment by prastle** [comment]
So Im sorry to be BLUNT
  
But AK did ask to reload reboot 

needs Sudo to do so to see if triplea user pass doesnt have permissions.

This was  to see if new changes have taken affect.

 Originally you wanted us each to have our own sudo access.

What has happened with this plan?  Or has sudo been lost?

Either way as stated elsewhere it seems we need more ram to host more bots.   We also need a paypal 

link that works.  So we can all as community donate.  It seems silly to me to have all these multiple 

rooms of discussion.  With multiple websites.  Just My Humble Opinion

Pras

**Comment by DanVanAtta** [comment]
Blunt is okay, as long as you are clear.


> "But AK did ask to reload reboot"

What does reload reboot mean? If that means to reboot the system, that will not to fix the Derby DB problem here.

> needs Sudo to do so to see if triplea user pass doesnt have permissions.

triplea does not have sudo, and the plan is not to give it sudo. Only perhaps 3 people will have full sudo access, but a small number more will have server access.

> Originally you wanted us each to have our own sudo access.

No, just your individual login so we are no longer using a shared and insecure account. 

> What has happened with this plan? Or has sudo been lost?

I got really busy at work and was not able to follow up adequately. The keys that were provided to me were not valid SSH keys for some reason. At some point soon the task will get picked back up.

> Either way as stated elsewhere it seems we need more ram to host more bots.

Indeed, linode has a free upgrade waiting for us, will be an hour downtime. Need to schedule it and make it happen.

>  We also need a paypal link that works. So we can all as community donate. 

Indeed, the linode cost is now coming from my bank account. I'll hope to get this set up over the next two weeks, there are a number of priorities in the project, and only a few people updating code.

>  It seems silly to me to have all these multiple rooms of discussion. With multiple websites. 

To some extent I agree. You're likely not aware of the source forge bug tracker. Github issues is a replacement for that, and is also serving additional purposes. So at least we don't have to check the source forge bug and feature request queues anymore in addition to all of the other items.

Gitter to re-iterate is for quick and possibly unfocused messages. It is for light weight conversation where quick messages can be passed, or ideas refined to build into a formal ticket (issue). 

I do not get new notifications for warclub, the UI is not good for seeing new issues there, the forum threads cannot be closed so you have to dig out what actually needs action, etc.. Hence you do see me checking github issues frequently because I get emails. Meanwhile warclub is not easy to log into using linux, and suffers from the above. That last point is a longer topic, if you'd like to discuss more, which I would encourage, please do open a new (and dedicated issue). Part of the trick is that we keep items very actionable, and avoid these 20 page threads where you have to sit down for 2 hours to understand what the problem and what needs to be done. We simply do not have that much time available for the developers, our time is severely limited.

**Comment by prastle** [comment]
Thank you for the clarifications.  I believe that American Knight felt that with higher level access than triplea user his changes would take affect.  Perhaps you could contact him directly and he can explain better than I.

**Comment by DanVanAtta** [comment]
The stuck thread is:
```
"Headless console eval print loop" #20 prio=5 os_prio=0 tid=0x00007f9a0047d800 nid=0x643f runnable [0x00007f99e1bf3000]
   java.lang.Thread.State: RUNNABLE
        at java.io.FileInputStream.readBytes(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:255)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        - locked <0x00000000f0434b98> (a java.io.BufferedInputStream)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        - locked <0x00000000f03c9508> (a java.io.InputStreamReader)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        - locked <0x00000000f03c9508> (a java.io.InputStreamReader)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at games.strategy.engine.lobby.server.headless.HeadlessLobbyConsole.printEvalLoop(HeadlessLobbyConsole.java:69)
        at games.strategy.engine.lobby.server.headless.HeadlessLobbyConsole.lambda$start$263(HeadlessLobbyConsole.java:59)
        at games.strategy.engine.lobby.server.headless.HeadlessLobbyConsole$$Lambda$11/1470344997.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Cernelius** [comment]
For the WarClub bots, I tend to think best may be 10 bots (not more) at -Xmx384m each. This is what I would try out.

**Comment by DanVanAtta** [comment]
We're crashing when reading database for input. The code here has not changed for some time. This indicates we have a problem outside of the application code. Potential sources of a problem:
- system configuration or permissions
- java derby jar + java8

**Comment by prastle** [comment]
Apparently it still works fine in 1.89
 What changed?

**Comment by DanVanAtta** [comment]
To be clear, in terms of code, nothing. This leaves library versions, and system configuration.

**Comment by prastle** [comment]
We also have another problem. Could you read this thread of the last few posts in bunker?  Thanks.

http://www.tripleawarclub.org/modules/newbb/viewtopic.php?post_id=17573

**Comment by DanVanAtta** [comment]
prastle, please use gitter to 'whisper' bunker links. This issue has the topic of the ta_users DB. Please be aware that we are using many smaller github issue tickets to talk about specific focused topics. Hence gitter is to fill the gap for items that are so small you do not want to create a ticket for them. My point is to please keep the discussion on topic.

**Comment by DanVanAtta** [comment]
Closing, we have no plan to fix this. DB migration project was spun up in part because we the Derby DB is so borked.
