### ISSUE TITLE
Website bugs

### ISSUE THREAD

**Issue by JayArghArgh** [triplea-game/triplea#1357]
Hi there, I'm looking for website bugs (RetroPy). Hook me up and I'll make them disappear.
I need; brief description of problem, link, screenshot if it helps, any other info you think might help especially if the problem is a subtle one ie:
- What exactly isn't working
- What exactly should x be doing
- Where exactly (if anywhere) should the broken link be going (or it gets deleted :+1: 

Once I have access I'll start getting into it.
JRR

**Comment by Cernelius** [comment]
There are many topics on this matter, some of them secreted in the admin only part of the WarClub forum.

I believe the main three open references on the matter are:

For the general issues:
http://www.tripleawarclub.org/modules/newbb/viewtopic.php?topic_id=2323

For the issues impacting on using the WarClub as a developer forum:
http://www.tripleawarclub.org/modules/newbb/viewtopic.php?topic_id=2317

And the outdated but still stickyed:
http://www.tripleawarclub.org/modules/newbb/viewtopic.php?topic_id=1531

Anyway, if they accept your collaboration, I believe a leader should take a backup of the entire WarClub forum and, then, give you access to it.
The current owner of the server (thus of the WarClub too), as far as I know, is @DanVanAtta (as far as the WarClub only is concerned, this has been communicated in the secreted Bunker only); the previous one was @Deltium ; the one beforehand, and the original creator of the WarClub is Bung (which is currently either totally inactive or in the background for emergencies).

If you ask me, I believe the main issue is that the PBF is broken, as that used to be the major part of the WarClub activity (I removed them from showing up in homepage, back then, since they made very hard to show up anything else in the currently broken as well Recent Replied Topics block) and also considering that, apparently, the integrated "Play By Forum" of the latest release still has the "TripleaWarClub.org" (side note, it should be changed to "TripleAWarClub.org") as one of the two referring forums, inducing people to unsuccessfully try to play there; for example:
http://www.tripleawarclub.org/modules/newbb/viewtopic.php?topic_id=2507

I believe this was the latest PBF game successfully uploaded in the WarClub (back in February):
http://www.tripleawarclub.org/modules/newbb/viewtopic.php?post_id=15651

**Comment by Cernelius** [comment]
On the other hand, since the PBF activity of the WarClub has been built up over the years and by now certainly almost totally lost, that might be not nearly as important as it was the day after it broke down.

Also, beside what doesn't work anymore, I believe the WarClub can't be a good developer forum if you can't upload PNG images (that was never possible), or generally have at least what the current Developer forum in SourceForge offers (my opinion). The best would be having an upload pictures at the levels here in GitHub (the imaged shown shrunk, to reduce the time needed to load the page, and you can click on it to view it full).

**Comment by DanVanAtta** [comment]
Match result reporting in the ladder was reported as broken here: http://www.tripleawarclub.org/modules/newbb/viewtopic.php?post_id=17464

If PBF is broken, that would be another important item to fix

**Comment by Deltium** [comment]
Agreed.  Those are very important to fix.   Many players play PBF + PBEM and the loss of this functionality (coupled with the reporting feature for ELO / rankings) has effectively rendered the warclub website meaningless. These are urgent fixes!

**Comment by yamamot0** [comment]
After fixing the broken links, I think the ladder fix should be Item number 1
A lot of people are asking how to report games.

**Comment by Deltium** [comment]
Agreed 100%

**Comment by Cernelius** [comment]
Yeah; considering that PBF broke down almost 1 year ago, while the ladder broke down recently, despite the fact that the PBF players used to be many more than the Ladder players, lately, probably Ladder is the item number 2 (after updating the download TripleA links), as we already lost the PBF community anyway (while the Ladder folks are still around waiting for it).

**Comment by ron-murhammer** [comment]
Yeah, PBF has mostly moved to A&A.org now.

**Comment by JayArghArgh** [comment]
no problems. I'm away with work at the moment, back home in Saturday / Sunday for 5 weeks. So will attack it then. Thanks for all your guidance above.

**Comment by Deltium** [comment]
Thanks for your efforts.  I know that I'd donate a couple hundred bucks to you if you could fix most of these issues, and I suspect Prastle may throw in some cash too.  Please take this as a small gesture of our thanks for your time and effort.

**Comment by JayArghArgh** [comment]
Hey there @Deltium thanks for the kind offer but strictly volunteering to help. Just getting my energy back from my extended work trip now; and starting to look into it.

**Comment by Deltium** [comment]
Welcome back.  Happy to chat by email (5683deltium@gmail.com) if you want to exchange ideas on the website.  Cheers.

**Comment by prastle** [comment]
Added  as lobby/forum mod and webmaster for warclub  
Thanks for the help.

GLHF

**Comment by DanVanAtta** [comment]
Shall we use the warclub repo for bug tracking related to the website?
https://github.com/triplea-game/tripleawarclub.org/issues

(note about the above repo, we still need a deployment mechanism, so updates are not live, but at least the code is publicly visible and can be checked in. To be deployable, we have to figure out how to preserve the DB password files (the DB passwords in repo are starred out))
