### ISSUE TITLE
Request for resources displayed in Actions and Operations

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#1361]
Would it not be possible, and a good idea, to have a player's available resources be displayed in the bottom of the Actions and Operations window, just like the purchase window? I know that this window’s buttons does not in theory always require the player to spend resources, but since the actions and operations can require spending resource and also may result in triggers giving resources, then I think it would be fitting to have the available resources displayed.

Whether a player must do Actions and Operations before or after a purchase step, it can be very irritating that the current available resources are not displayed.

![unavngivet2](https://cloud.githubusercontent.com/assets/15268177/21026421/bc7f47e0-bd8c-11e6-8bc8-8b1486a3fda0.png)

![unavngivet](https://cloud.githubusercontent.com/assets/15268177/21026424/c2aa94f8-bd8c-11e6-8621-171e97285672.png)

**Comment by ron-murhammer** [comment]
@FrostionAAA Yeah that could probably be done fairly easily. Probably would be even better to only show it if any of the options require resources.

**Comment by Cernelius** [comment]
Correct, I definitely believe it should be only shown if any of the options require resources. It would be weird if it shows you the PUs for an action that has nothing to do with purchasing anything.

As a related matter, if the others agree, I believe you should not have the actions you can't pay for (currently, if you don't have the needed PUs, it will tell that you don't, after you click on it).

For example, there, if Japan has 19 or less PUs, the last action should not be present at all, in my opinion.

**Comment by ron-murhammer** [comment]
@Cernelius I'd disagree slightly on that. I think all options should be displayed but the ones you don't have enough resources for should be grayed out and unclickable. The reason being that the player should know all the options that are available even if they can't currently take them.

**Comment by Cernelius** [comment]
That way may be better for noobs that don't want to read the rules, but for fully knowledgeable experienced players not seeing what you can't do I'm sure is always the best.

Well, all actions, both political and user, that don't meet their conditions are not displayed, currently, and I surely believe this is good (like, would be just a mess if you get all the political actions you have in the game); the PUs thing is actually the only 1 exception in which you have an action (user or political) that you can't do displayed, but I'm not strong on this one minor thing one way or the other.

I definitely don't want to see that I can ally with somebody in Napo FFA while I'm at war with him (currently, you don't, and this is good). Having all the possible political actions ever displayed, even greyed out, would be a big mess (you don't have to see them, in this case; so all good here).

It can stay as it is, anyhow. It is just the only 1 exception. I don't really care.

The best way to have that customisable would be by being able to check for resources with conditions, so that mapmakers can assure it, if they want to (meaning that you can check if the player A has X or more of resource Y, with a condition option, to validate triggers or actions).

I recall that time ago I wanted to make powers able to donate anyone as much money as they want (because, why not?); so I made 300 actions from 1 PUs to 300 PUs to the other 15 players in the game, for total 4500 actions. Worked fine, but, then I trashed it and did it with boxes (purchase then place money units in the other one's), instead; not sure what I prefer, at the end, because 1 button per PUs per player is still worse than managing it via placement.

**Comment by ssoloff** [comment]
@FrostionAAA, @ron-murhammer: these features are now on `master`.  When you have a chance, would you mind validating and closing this issue if the implementation is acceptable?  Thanks.

**Comment by FrostionAAA** [comment]
I have not tested it out. If I download the very latest build of TripleA, then the feature is in? I will try to do this. This will be a great feature.

**Comment by ssoloff** [comment]
@FrostionAAA Yes, please use the latest build.  While this feature was merged a few weeks ago, the release builds were not really usable until recently due to #1547, which was fixed in [1.9.0.0.3856](https://github.com/triplea-game/triplea/releases/tag/1.9.0.0.3856).  So any build after that one should be ok to test with.

**Comment by FrostionAAA** [comment]
I have tested it out. To me it seems to work fine. I just want to point out an aesthetic issue. As you can see in the below screenshots there seems to be a lack of space between the frame of the Actions and Operations window and the start of the “You have XX PUs, …” text. Is it possible to do something about this? Maybe add some margin?

![unavngivet](https://cloud.githubusercontent.com/assets/15268177/23911610/a248803e-08dd-11e7-8ab4-ea931b15c3f9.png)

The same thing goes for the text to the right of the “buttons”. I have made text arrows in my maps to make this less of an issue. Right now, the text displayed next to the buttons (found in the maps actionstext.properties) does not allow a spacebar “space” before the text, so I compensated with the arrows. It would especially be an issue if the text starts with a capital I/i. It would be great if something could be done here also.

I don’t know if this is useful, but there seems to be enough space in the purchase window. Maybe some code used here to configure the behavior of the window can be used in the Actions and Operations?
I would like to say that this is only screenshots of how this is displayed on my specific PC, Windows 10 and my settings. Maybe it looks different on other systems.

![unavngivet2](https://cloud.githubusercontent.com/assets/15268177/23911641/b7c4321e-08dd-11e7-9df8-e2915375a2da.png)

**Comment by ssoloff** [comment]
Thanks for testing, @FrostionAAA!

I agree with your observation about the lack of margins throughout this dialog and your recommendation for improving it.  (And, yes, it does occur on non-Windows platforms, as well.)

If you don't mind, could you create a new issue for improving the layout of this dialog?  I think your previous comment (including the screenshots) describes the problem perfectly and can just be copy-pasted into the new issue as-is.

**Comment by FrostionAAA** [comment]
Will do! 👍
