### ISSUE TITLE
issues with bots / Lobby - Player names not always removed on exit

### ISSUE THREAD

**Issue by Deltium** [triplea-game/triplea#1372]
this may be a known issue, but when people leave a bot, it seems that in some cases there name still remains.   I saw this in Bot4 and botRamb0.    Also noticed that when people leave the lobby, their name still appears sometimes, even though they are not there.

**Comment by ron-murhammer** [comment]
@Deltium I've noticed this as well. Do you know if this was the case with 1.8 as well?

**Comment by Deltium** [comment]
No, I have just seen it happening with the 1.9 version.

**Comment by prastle** [comment]
in the past we often had to remove ghosts from bots.
link here
http://www.tripleawarclub.org/modules/newbb/viewtopic.php?topic_id=2284

Lately tho we have a lot of people just parking while playing other games.  I am usure if this is just abuse?  Or more ghosts.

http://www.tripleawarclub.org/modules/newbb/viewtopic.php?post_id=17531

**Comment by gamergray** [comment]
Not sure of the best place for this, but it seems very similar to what this thread is describing.

Since the migration to the 1.9 lobby, almost every time I host, the host become a ghost upon exit.  It will often show me still in the host, even though I have left.  Even leaving the lobby completely does not eliminate the host.
There is a ghost out there right now with my name on it.
This did not seem to happen with the initial migration, but later with one of the 1.9.xx updates.

Don't know what else to add, there is not an error message in the java console that I am aware of.
Also, you guys are doing a wonderful service.
