### ISSUE TITLE
Map Loading Indicator

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1469]
Picking up from #979, the game gives no feedback when a map XML is loading. War of Relics is a pathological XML, but it is a good example of this behavior since the map takes about 30s to load. The game appears frozen during this time. The UI should be providing feedback to the user to indicate it is loading the map XML.

Proposals
- progress bar / window
- status message label

The status label update has a very low performance cost. This could be as simple as renaming a button after it is clicked and we are now loading a map.  The progress bar/window I've found in previous performance analysis was quite expensive on its own. Therefore we would not want to show it unless a map was likely going to take a long while (and most maps do not, they are typically under 2 or 3 seconds). This then gets into some complexity.. Meanwhile updating a status somewhere is pretty simple, and accomplishes the feedback goal.

**Comment by ron-murhammer** [comment]
I'm open to either and would probably take some testing to see which works best. Either is probably better than nothing. 

If we go the progress bar/window/icon route it would probably be good to create a standard TripleA component to do that. I've wanted to add one to the AI's turns for a while.

**Comment by Cernelius** [comment]
Both are good, and I don't think there is a big need to have a progress bar here, as I can say maps taking more than 1 minute to load have much bigger slowdowns when played in lobby or with the AI (except Easy), thus I doubt mapmakers will want to go too much in that direction anyway, as now, but sure it is neat and a progress bar always looks more pro than a label, even if not particularly needed (I much like the progress bar addition when downloading maps).

Related to this, I don't know if this issue is actually a partial regression (?) for everyone or just for some, but in the old 1.8.0.9, when I started it and on other cases, there was indeed a message label that the game was loading, meaning this one:
![triplea_starting_label](https://cloud.githubusercontent.com/assets/19562310/22093879/7e620f5e-de09-11e6-8e21-2f081afbbcff.png)
And now I don't see it anymore.
For example, if you start up TripleA with a map that takes some time to load (the most extreme example at the moment is War of the Relics, but theorically longer times are possible), now it looks like nothing started, until it finishes loading and it appears, while in the 1.8.0.9 I would have seen the label above.

Also, a strange thing is that it seems you load the map you have selected every time you join someone else private host, from the lobby. For example, if you have War of the Relics selected, you will have to wait like 30 s to join someone else host, even if this host is a different map, and you are not going to play War of the Relics at all.

Regarding Hard AI, I suggested and suggest the "AI Pause Duration" delay overlapping with the delay for calculation so that, for example, if you have 250 ms delay and the calculations take 373 ms, the delay is just 373 ms, not 623 ms. The status bar for the AI should appear after the AI Pause Duration delay has expired, and being already in progress; so, for example, in the above case, it would appear after 250 ms but with the bar starting already 67% completed, for the calculations done while waiting for the "AI Pause Duration" delay to expire, anyway (and, of course, when the "AI Pause Duration" lasts longer than the calculations, you don't see any bar). This is particularly relevant for calculations between different combat rounds of a same battle. Side note, I don't know how it is currently working, as it is a long time I haven't tested it.

**Comment by DanVanAtta** [comment]
> Also, a strange thing is that it seems you load the map you have selected every time you join someone else private host, from the lobby. For example, if you have War of the Relics selected, you will have to wait like 30 s to join someone else host, even if this host is a different map, and you are not going to play War of the Relics at all.

Not 100% unexpected. The game is loading the map panel selection frame, it then loads the 'default game' (eg: war of relics), then it does the code to update to the remote game. Not very efficient..

> here was indeed a message label that the game was loading

It was intentionally removed. It turned out that you could almost spend just as long waiting for the progress bar to load as you would the map itself.

Really seems like we need to find a way to put a progress indicator somewhere without slowing down the map loading thread and UI rendering.

**Comment by ron-murhammer** [comment]
@DanVanAtta Maybe finding something light weight. Also initializing it and hiding til its used might make it react faster.
