### ISSUE TITLE
The future of Anonymous Logins?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1488]
Should we continue supporting anonymous logins?

Anonymous login problem:
- makes trolling easier

Anonymous login pro:
+ it's a relief to be able to download and just login. No extra confirm email, and nobody particularly wants to give up their email.

What to do with anonymous login, keep it? Can it be saved?

One suggestion:
- For anon logins, append a hashed ID of a players mac address to the end of their users name when in lobby. For example "LaFayette (55262)"

**Comment by simon33-2** [comment]
So if banned they could still work around it by just changing their login by one character? 

If we are going down this route, the whole mac address needs to be recorded imo.

**Comment by ron-murhammer** [comment]
@simon33-2 We can already ban by mac address.

@DanVanAtta I'm fine either way (not a lobby player so not much of an opinion). I'd recommend trying to get a consensus from the active lobby mods.

**Comment by Cernelius** [comment]
> I'm fine either way (not a lobby player so not much of an opinion). I'd recommend trying to get a consensus from the active lobby mods.

I suggest admin related things being discussed in the admin only forum first, and in other places thereafter.

@DanVanAtta , I understand this is a strange request, in the main development site, but I much suggest you edit out any tracking references from your post here. Up to the leaders, of course, but I definitely think it is advisable not talking openly about how stuff works, or this is just helping people knowing how to evade. I mean better not explicitly talking about what kind of ID is used for stuff and the like.

If I'm allowed to be blunt: **don't go around telling people how they are banned.**

Of course, I realise that, being open source, everyone can know everything by definition, but the matter is to keep such things as much secret as possible. I think all the developers that may be involved in this item can talk about this in the admin only forum, with no issues; so not much advantage at keeping such discussions open to all anyways (I mean the specific info about tracking / banning).

I surely suggest any discussions related to the matters relevant for the admin only forum being kept inside the admin only forum, and moved to GitHub only when not anymore at a Discussion state.

Besides, it would be anyway wise to involve the mods in the matter, thus I eco @ron-murhammer about a notice about this in admin forum, anyway.

For the Anonymous login, it is important to break the first barrier; I suggest keeping it, but adding a 1 hour delay for joining anonymously, and a notice about this delay, a time out, and the info that registering removes it.

Moreover, I suggest anonymous users being unable to pick any names, but having just "anonymous" assigned, and just joining as "anonymous (1)", "anonymous (2)", etc..

Definitely against showing up any ID etc., as this would be just info for trolls. Please, at the lead developers, read this (yes, all the 11 pages) as an example, if any of you haven't, already:
http://www.tripleawarclub.org/modules/newbb/viewtopic.php?topic_id=2135

I think the anonymous login is an importand, yet minor item; the main item is banned people being as much as possible unable to get around the ban, for which is needed:
- A very good banning system.
- A high level of secrecy about how the banning system works.

The only real issue of anonymous login is people taking the name of other users, impersonificating them, but I'm not much concerned about that, because if people loging anonymously, this means that they are fine about that (and they could have had registered, to avoid others using their usernames).
For example:
http://www.tripleawarclub.org/modules/newbb/viewtopic.php?post_id=17431

**Comment by Cernelius** [comment]
@ron-murhammer , you lead developers are free to discuss wherever and however you think is best for the development or whatever, of course, but, based on some past history, I suggest you as well to edit your post to remove the info about how users are banned. Telling people what kind of address is used has proved to be the first step for evading.
Again, please read, for an example:
http://www.tripleawarclub.org/modules/newbb/viewtopic.php?topic_id=2135

**Comment by Cernelius** [comment]
I'm not saying that not talking about stuff is the solution (besides, ban related things can be fully discussed in the admin only forum), and if you don't want to take my advice, fair enough; your call.

**Comment by yamamot0** [comment]
I would like to contribute to this, but this discussion need to be in an admin forum.

We can discuss why we ban in open, but not how we ban. You only need to google if you know, and you will be back online in 2 min. A mod told for over a year ago a banned user how we track users, and we still have to deal with the consequences: http://www.tripleawarclub.org/modules/newbb/viewtopic.php?topic_id=2135 - we cant ban him anymore and he can do whatever he wants.
Was we learned was very clear: Never tell the users how we ban them

**Comment by yamamot0** [comment]
On the matter: Anonymous login has more negative effects then positive.
positive: a new(!) player is faster online
But if you want to play triplea as a regular user, you only need to sign in onces. So I think you can spend some minutes for that 
negative: The list is so so long: 
Normal Trolling, 
nametrolling, 
trolling mod after nameban player
Quitting a game were a risky round 1 went wrong and coming back right away with a new nick to ask for new game
easier to quit games allover
highjacking other unsers names for fun, trashtalk or to hurt them
No player easy tracking for players and mod.
You dont know who you are playing against, and players tell you who they are, wenn they wi,n and just leave the game, wenn they are losing  
The list goes on - we had it all.

**Comment by Cernelius** [comment]
While theorically yamamot0 is of course right that registering is not a big deal, the very big spread between TripleA users and lobby users (despite online live play, as being the closest to the absolute best live play on board, being sponsored as the best way to play at startup) makes me think that anonymous should be supported.
Being able to briefly join to take a look may make a difference for a likely great number of users undecided if to play online or just with AI, as most people are just content to play with AI, before experiencing that playing with other people is 100 times better.
Just look at the enormous difference between downloads and how many (few) people are in the lobby.
I believe having a 1 hour delay to join anonymously (as I suggested) would cover most issues.

The matter is not the time needed to register; the matter is that TripleA is just one amongst many games, and people don't like to register to a million different things, unless they are quite sure about it, already.

Plus there is the ongoing problem that @ron-murhammer keeps making the AI better, and this lowers the incentive to play online. :-)

**Comment by RoiEXLab** [comment]
While I'd be fine with anonymous logins, I'd rather not prefer to have them...
IMO anonymous logins make the database handling just more difficult, we would need to seperate between anonymous users and registered users, and handle them different - work that could be avoided...

**Comment by DanVanAtta** [comment]
Few comments about process:
- we should favor any discussion with a clear end-goal being on github issues. That way we can close it down when it is done. Operational stuff can/should be on an admin forum.
- this is an open source project, if someone is likely to dig this thread up, they are perhaps just as likely to dig up the game code. It would not take that much to just guess IP or mac ban and simply go from there.
- game code being public, we want new people to jump in. It is much better to avoid, this is a 'secret' project of one or two people, then once in, boom, you can now view the hundreds of pages of info we dumped into a secret warclub forum. That is pretty useless for development, makes it harder for new developers to join, and makes it harder to know what has been considered, decided, and why.
- if we talk about how to get good security, perhaps someone will suggest a plan. Seriously though, it takes as much effort to find this issue as it would be to go in the code and search for 'ban' and start seeing how it is done.

To the points raised:
- I agree with Cernel on the 'one more login'. I did not register for tripleA until I had to, and now I'm not very happy about it since I have to type in a password every time. Allowing for a remembered login would help.
- Download counts in SVN I think are inflated by a lot. Likely robots or something. That many downloads, we should see a lot more traffic, and we do not. The traffic to the new github download site was not nearly the size, yet in theory to get the latest game that is where you have to go, and we've updated most of the game links at this point. 
- The one hour to register is an interesting idea. I think people would work around that as well, and it gets back to the identifying users problem. IE: if we can detect someone has been online for an hour, we can detect if they are a unique anonymous user as well. In which case it does not matter if they register or not really.
- The ID suggestion I don't think has been understood. Would it really give more info to trolls @yamamot0 ? I was thinking it would do the opposite. When you see "Bob" and "Jack" both have the same IDs, you know they are anonymous and second likely the same person.The ID would be a hash of the mac addreses, so mac addresses would not be exposed directly.

Registration doesn't solve a number of problems as well, we should consider that. If you've ever had the misfortune to play a Kabam game, multiple accounts are an advantage. It's common there to manage a dozen or two dozen accounts, each needing a unique email address. So for name spoofing, it's easy to register an account with a slightly different name or what not.

I'm left thinking the ID tagging is best we can do to help avoid these problems. With the following rules:
- all anon users are tagged. Admins can then have liberty to show less tolerance to anon users, and boot them on smaller infractions.
- registered users with duplicate mac show their tag. This is to show that a registered user is the same and is logged in twice

With respect to ban system:
- IP logging seems just broken to me. I recommend we drop it.
- Mac address seems to be the most annoying thing to get around, IMO still worth having this.

Otherwise I think the only thing we can do to avoid multiple nicks and abuse is to increase the investment users will have in an account. IMO stat tracking would go some way. It would probably be the case pretty quickly that a brand new account will be seen as sketchy, and allows players to do more of their own due diligence.

**Comment by DanVanAtta** [comment]
ps: I don't think there is any plan to do DB tracking of anon users. There are some technical issues introduced if we do. For the moment that is not in the docket. So things like forcing registration after X times is not terribly desired. Has some other interesting question/implications, like what to do if that user is in a game? Overall the coding effort for the gain does not seem worth it. It's an interesting idea nonetheless, I appreciate it being shared.

**Comment by Cernelius** [comment]
> The one hour to register is an interesting idea. I think people would work around that as well, and it gets back to the identifying users problem. IE: if we can detect someone has been online for an hour, we can detect if they are a unique anonymous user as well. In which case it does not matter if they register or not really.

No. I didn't say give them a free hour, then oblige them to register. What I suggested is this:

> For the Anonymous login, it is important to break the first barrier; I suggest keeping it, but adding a 1 hour delay for joining anonymously, and a notice about this delay, a time out, and the info that registering removes it.

Meaning that, when you want to join the lobby, you have to wait 1 hour for that to happen, if you want to do it anonymously, then you can stay in lobby for as long as you want or are allowed to. Of course, it is needed a notice about it, or people will just think they can't join the lobby. If you log off or get booted, you will have to wait 1 hour again for logging in again, as well as every time.
This would assure that people don't have to register to anything to join the lobby (people don't like to register), and the delay will both incentive them to do it and help the mods about the nick spamming.

> this is an open source project, if someone is likely to dig this thread up, they are perhaps just as likely to dig up the game code.

Well, no. Reading open discussions and delving into the game code are so much on different levels I'm not sure why I'm pointing it out to a developer. I already said myself that, obviously, being an open source project, everything can be known, but it seems obvious to me that only a very small minority of people are likely to dig up the game code to know how the ban system works. Thus, as I said, if you don't tell people how they are banned (like you are doing now, and it seems you want to keep doing in this Issue and I guess elsewhere), most will have a much harder time figuring it out, or will give up.
And, no, not sure why I have to point it out, but, of course, reading an open discussion whatever on TripleA is not on the same level as digging into the code, to have the same info. For example, I'm reading this discussion, but I'm not digging into the code, and I don't really even know what that means, to start with.

> Seriously though, it takes as much effort to find this issue as it would be to go in the code and search for 'ban' and start seeing how it is done.

Well, no; just no. Unless we assume that all TripleA users are developers, this is just a no with no arguing.

> The ID suggestion I don't think has been understood. Would it really give more info to trolls @yamamot0 ? I was thinking it would do the opposite. When you see "Bob" and "Jack" both have the same IDs, you know they are anonymous and second likely the same person.The ID would be a hash of the mac addreses, so mac addresses would not be exposed directly.

It seems obvious to me that if you can see exactly when your multiple nicks are spotted or not, then you can figure out and be assured if the way you are using to get around detection is working or not. If you really want to do that (better not), my suggestion is limiting it showing up the aliases to all, right of the names, in main lobby list (currently it is only for moderators).

> With respect to ban system:
> 
> - IP logging seems just broken to me. I recommend we drop it.
> - Mac address seems to be the most annoying thing to get around, IMO still worth having this.

While the IP is easy to change, it gives the info about the location of the person, and it is at least something to work with. Why do you want to drop items for moderators, just because they are of little use, unless proposing something else to replace them? Wouldn't this make a bad situation just worse? What is the aim, beside, I guess, simplifying the code? I don't think that if something is of little use (besides, how much of use it is can be guessed only by reading the Bunker history), then it makes sense to remove it, with no substitute (?). Isn't something of little use still better than nothing?
Fair enough, if you want to publicly give full info about how the ban system work, and don't want to edit out what has been said so far, and move the discussion into the admin only forum, you are the leaders, let's keep doing that.

> Otherwise I think the only thing we can do to avoid multiple nicks and abuse is to increase the investment users will have in an account. IMO stat tracking would go some way. It would probably be the case pretty quickly that a brand new account will be seen as sketchy, and allows players to do more of their own due diligence.

Of course, to have an opinion on this point at all, it is needed to know exactly what "increase the investment users will have in an account" means in practice, but I just suggest to be cautious about the directions to realise this, not to go in the direction of desertify the lobby, reducing the inflow of new people, in the effort of piling up barricades for trolls.

---

Since you want to publicly discuss with full info how exactly we ban, let's take this opportunity to ask a couple of questions:

1) Did all member developers involved in this discussion fully read what me and @yamamot0 linked at:
http://www.tripleawarclub.org/modules/newbb/viewtopic.php?topic_id=2135
Do you have a solution for that, especially now that it is preferred to go in the direction of letting everybody know exactly how the ban system work (if they read the development discussions), without the need of digging into the code to know it? How about all people that get banned do what at that topic?

2) Is there a way to have a better ban system than TripleA currently has? Are there other more solid ways to ban a terminal with no coming back, beside IP and Mac only?

3) Can we keep this discussion focused on just the item of having or not Anonymous login, and open other ones for other items; it is already hard to talk about that without all the confusion of talking about the ban system.
The ban item was added by @simon33-2 , while the initial post is not talking about banning at all, just about having or not having not-registered users (they all get banned the same, so banning doesn't have to be discussed here).

4) Is my suggestion of keeping Anonymous login, but oblige people to wait 1 hour each time they want to login Anonymously, viable and acceptable as a third way between having or not having them? I really think the big item is that people don't want to register to something, until they believe they want to; so the "tryout" function of Anonymous logins is of marked importance.

5) I would prefer whatever discussion about banning being postponed till at least the database actually works. Currently, if a mod right click and mistakenly permaban a user, that user has no legit ways to be unbanned, and this is the situation since more than 1 year, with many people complaining about illegitimate (never reported) long bans, and there is no info in Bunker if they received any answer or not (so, I'm guessing, they never did).

6) @RoiEXLab , since you are one of the many (seemingly random) people banned for no good reasons; when you got banned, what did you do to unban yourself? Just curious. I would prefer you let the mods know inside the admin only forum, but whatever.

---

I suggest "Member" of this site automatically having access to the admin only forum, right when they become "Member", if not already so. In the WarClub, you can yous the "Senior Staff" group, if they don't want to moderate or be webmasters.

**Comment by Cernelius** [comment]
Simple example: I'm in lobby now.

Me or anyone ctrl + paste the link to this one Issue in the lobby chat room (maybe to tell a mod to take a look).

Ta-Da! Everybody knows how banning exactly works, and can talk about it and pass the knowledge.

I don't think it is on the same level as everyone delving into the (of course, open source) code, to know it. It's not a matter of everything being perfect or not; it is a matter of dealing with what little makes sense.

We can as well give full info about what exactly is banned in the rules section of the forum, at this point, and pointing the users to that each time an action is taken; that would be fair and not discriminatory the most. Or something is supposed to be secreted or it is supposed no to be; I don't get the grey area of "let's talk it openly and trust nobody reads but the developers only, that would know it anyway".

As I said, I hope the developers don't take my objections as anything personal. I do recognise that the developers are the leaders, and if the new ones want to change any directions or just don't want to suffer the problems that secrecty gives to development, it is just up to them. Sorry for repeating the same things, I just wanted to make my view unmistakably clear; now I'm done.

**Comment by DanVanAtta** [comment]
> Did all member developers involved in this discussion fully read what me and @yamamot0 linked at:
http://www.tripleawarclub.org/modules/newbb/viewtopic.php?topic_id=2135

No, most dev's are not admins. We want to attract new developers, deciding items in secret is not helpful.

> Is there a way to have a better ban system than TripleA currently has? Are there other more solid ways to ban a terminal with no coming back, beside IP and Mac only?

That is a bit at question, we probably should discuss in a new issue as later requested.

> Can we keep this discussion focused on just the item of having or not Anonymous login,

I agree, this thread is really getting off-topic too easily.

> Is my suggestion of keeping Anonymous login, but oblige people to wait 1 hour each time they want to login Anonymously

I think this defeats the purpose of anonymous login. From a code perspective this could be hard to enforce. I don't think this is viable.

> I would prefer whatever discussion about banning being postponed till at least the database actually works. 

I don't think the existing DB will ever be brought back up. Been there, did not figure it out. Not wasting hours of time when that could be spent re-writing the DB, which is something we really want to do anyways to support ladder/game challenge features. 


> if a mod right click and mistakenly permaban a user, that user has no legit ways to be unbanned, and this is the situation since more than 1 year, 

Accidental clicks is bad.. IP address bans is where a lot of the false positives. AT this point I don't think IP banning has *any* value. It's just broken.

Re: security. If someone searches in this forum, I'm already impressed. A determined enough attacker will find a way. Now, telling trolls directly how to get around the ban, is a bit of another thing. To another point, if you rely on obfuscation for your security, you actually do not have it. A person should be able to read and understand all source code, and if they still can't get around a ban, then we actually have an effective system. By keeping the discussion open, we are allowing all dev's, and potential dev's, to participate and revisit this same conversation.


-------------
Re attaching aliases. I don't think that will work because of the tracking requirements. Instead of showing IDs, or aliases, we could disallow duplicate mac address logins. 

The ID item I think is still viable. It may give a clue to how we identify, but it is not terribly direct. Meanwhile it gives some incentive to not have an anonymous login.  If someone is determined enough, they will get around it.

I think this gets to a requirement that whatever system we come up with, it can't be a moderator only thing to enforce, needs to be a system level or public accountable.


> but I just suggest to be cautious about the directions to realise this, not to go in the direction of desertify the lobby, reducing the inflow of new people, in the effort of piling up barricades for trolls.

I think this is misconstruing what I've said. I'm not really talking about barriers to trolls, other perhaps making them work a bit more to change their IP and/or Mac. More I"m stating that we create additional value and investment in existing accounts. This way switching to a brand new one has some trade-off cost to it.

**Comment by DanVanAtta** [comment]
> "let's talk it openly and trust nobody reads but the developers only, that would know it anyway".

What we wish to keep secret is already compromised. Yes, don't go advertising that, but for all intensive purposes, the horse is out of the barn. Our ban system is pretty broken, and with the DB in bad shape, it's more broken then normal.

It does get to IT security though. People who are really exploiting things will go to the code, and perhaps they'll be smart enough to not let us know they are trolling.

**Comment by DanVanAtta** [comment]
We should get back on track:
- anonymous logins are good feature, nobody likes to register, and nobody likes remembering typing passwords all the time.
- anonymous logins allow abuse to occur more easily. Some problems though:
 - our ban system needs improvement
 - requiring registration with email only increases the cost of a new account slightly. The answer to stop anonymous login abuse is *not* to force email registration.

Ultimately I'm thinking:
- the anonymous login is a good feature, we'll keep it unless we can come up with a very good ban system that would not work with anonymous login
- we can improve our ban capability, and should do so.
- we can improve detection of duplicate logins, should help for trolling
- add features that make it more valuable to have an account open for some time.

This conversation naturally gets to security/abuse because that is what we are trying to prevent, it is the biggest reason to not allow anonymous logins.

**Comment by Cernelius** [comment]
> > Did all member developers involved in this discussion fully read what me and @yamamot0 linked at:
> > http://www.tripleawarclub.org/modules/newbb/viewtopic.php?topic_id=2135
> 
> No, most dev's are not admins. We want to attract new developers, deciding items in secret is not helpful.

I meant all the developers being "Member" (as opposed to "Contributor"), which, in turn, I think they should all be at least Senior Staff, in WarClub (thus Bunker access).

Ok. Another idea may be that anonymous users are freely able to join the lobby but unable to join the bots (only host or join private games). The matter would be keeping the anonymous function, but giving some serious reasons for getting aroung registering. Since the bots are supposed to be moderated, that would make also some sense.

**Comment by DanVanAtta** [comment]
That's a pretty interesting idea. 

Do you think it would be more effective than keeping track of player stats? Should we do both?

IMO tracking player stats would be discouragement since it would be obvious which accounts are brand new.

**Comment by Cernelius** [comment]
I surely don't like the idea of tracking player stats, but this is almost only a matter of merely personal preferences, so I didn't even comment on it. In general, I'm just not a fan of badges, ranking and somesuch. But I guess whatever is admin only, instead, the more the info the better.
I'm fine with removing IP bans; I mostly meant keep IP tracking, also for alias.

**Comment by prastle** [comment]
Tracking player stats would make them want to register.   IP bans are very ineffective but IP tracking helps with alias.  Personally I dislike the anonymous login but if it is decided to be kept then we should have a notation that is visible to all players that this person basically couldn't  be bothered to register thus probably isn't a serious player.  As far as our security goes yup its broken.  Hopefully the new captcha and email required to register and login will help.  I would like to point out that since players stats would be visible to all users they could easily discover that oh this guy joined a week ago and has played 1 game.  This would encourage people to be a little more serious about their reputations i would hope.  I also think that if you havenet registered their should be things you are not privileged enough to be allowed to do.  Examples would be posting you are read only,  I really like Cernels Bots ideas above.  Im sure other things could be thought of as well like perhaps no sound ? no slap ability? etc.

**Comment by prastle** [comment]
BTW this doesnt mean that players stat tracking needs to be a massive thing.  That's done in the the tourneys and ladder.  All registered users should be tracked somehow tho imho.  Perhaps just join date and games played?  Either way I do believe anonymous users should be visible to all in lobby.  To what extent not sure.  I also believe multiple knicks at same time in lobby should be stopped somehow!

**Comment by prastle** [comment]
Some lobby comments from tonight since any could have read

majorQ10 has joined
Ugly_The_Noob has joined
(20:07:45) hippytrip:  bot05
(20:08:10) Lafalot:  shmitty from gto?
(20:08:21) Ugly_The_Noob:  i was on gto
(20:08:28) Lafalot:  cool
(20:08:43) hippytrip:  I don't think shmitty is
(20:08:46) Lafalot:  poor gto - we knew it well and it died a lousy death :(
(20:08:48) hippytrip:  he isnt
(20:08:57) Ugly_The_Noob:  i was in the lobby at the end
(20:09:02) Ugly_The_Noob:  rob game me a life time ban
(20:09:05) Ugly_The_Noob:  but i snuck back in
(20:09:13) hippytrip:  lol
(20:09:17) Ugly_The_Noob:  i bought a prepaid debitcard with cash
(20:09:24) Ugly_The_Noob:  and used it and a vpn to buy coins
(20:09:28) Lafalot:  hehe
(20:09:28) Ugly_The_Noob:  no ip to trace
(20:09:33) Ugly_The_Noob:  and no CC to trace
(20:09:40) Ugly_The_Noob:  cause first i vpned and bought coin
(20:09:50) Ugly_The_Noob:  and he say my name on the cc record, and refunded and banned me
(20:10:15) Ugly_The_Noob:  i was in a game of vegas at the end
(20:10:19) Ugly_The_Noob:  the last game of vegas
(20:10:36) Ugly_The_Noob:  rip vegas and aquire
(20:10:47) Ugly_The_Noob:  this site is better for axis and allies style game though
(20:10:57) Ugly_The_Noob:  and its free
CaffeineJunkie has joined

**Comment by prastle** [comment]
Iwould also like to add that i posted in warclub hoping that all would discuss this in new bunker
which can easily be fixed, for now, to allow any to talk there that should be apart of this discussion.  So I have to agree with many above about WHY ? are we discussing this here?

**Comment by prastle** [comment]
So after examining permissions in the new site we have many options available.
Disable name change avail.   disable email change avail.  password expiry days avail.
chat can be restricted avail.  topic search can be restricted,  email notification can be restricted 
 avatars  etc.... etc....

If we create a new group labeled guest all solved.

ALSO all should look at Google Analyticals as RoiEx pointed out wow!

THUS Guests  can be easily limited!  

We can also offer rewards for registering.   Thus if a registered user is separate on the database from a guest with same login they get a lot more options.   

The real ? is can we use the new! rejoined! database from a new War-Club/Forum to separate the registered users from the guests in the lobby?   The other option would be to have  to login to warclub before joining the lobby game?  

Ideas?

**Comment by wirkey** [comment]
there are ups and downs for both.
I would prefer an unanonymous login, though i have an idea:
what about both? You can login anonymously but in that case your username doesn't show in the lobby and you can't write anything (they might write something only visible by mods and might be seen by mods). If they enter a game they can participate like now. Might be a hell of a coding, but i guess it benefits all.

**Comment by DanVanAtta** [comment]
I think consensus is to keep anon logins.

We can open up more and more features to registered only users, such as stats, game challenges, ladder, maybe even cloud/hosted saving. With some luck that will be incentive to create accounts. Meanwhile we will do what we can to enhance de-duping based on network identifiers.

**Comment by prastle** [comment]
Actually from what i have read many said they dislike anon logins but believe what ya wish.  It complete makes a ranking system impossible and forces all players to wonder is this new guy for real?

**Comment by DanVanAtta** [comment]
There are problems related to anon login, but they are not solved by forcing email registration either. We do not seem to gain anything by removing anon login. Independently we do want to do a better job of dupe login detection, regardless of anon login or not. We also seem to want to do something to give indication of 'account age'. EG: stats of games played, registration date, etc..
