### ISSUE TITLE
Help, can't connect in lobby or via network

### ISSUE THREAD

**Issue by Ted1970** [triplea-game/triplea#1491]
Apologies if this is the wrong place. I'm new to this; just discovered TripleA (amazing) and am trying to play it computer-to-computer with my young son. But we can't connect via network (LAN) or online. Network: one computer hosting, other computer tries to join, but just goes back to the main menu screen, which is then frozen. Online: one computer hosts, other tries to join; a box on the screen seems to flash very quickly (too quick to read), then main menu and frozen. We've disabled firewall, forwarded ports, updated Java (and tried adding the "Prefs" folder), and downloaded the latest version of the game. Both computers run Windows 10 64-bit.  Can anyone help?

**Comment by DanVanAtta** [comment]
Is there anything in the error console? You can show that screen from the options/preferences off of the main startup screen. Typically the error console auto-pops up, but in this case maybe not.

Can you connect to yourself? You should be able to host a local game, and then connect from the same machine?

Next thing to check, can you establish a telnet connection to the host machine? IE: if host machine is on port 3303, can the guest do a`telnet <IP> 3303` and get a connection?

**Comment by Ted1970** [comment]
Thanks for the quick reply! The program freezes after I try to connect, so nothing comes up in the error console.

I just tried for the first time to connect to myself by hosting local, then opening a second copy of TripleA and joining. The connection worked.

I'm not sure I'd have a clue how to do the telnet connection.

**Comment by DanVanAtta** [comment]
On windows, in start menu, type `cmd`, then you just type `telnet <ip> 3303` where <ip> is the IP address of the other machine and 3303 is the port you specified.

For the connection freeze, we likely need something called a thread dump. http://stackoverflow.com/questions/2124672/java-stack-dump-on-windows

The error console has a 'enumerate threads' button that should actually produce the same. Does not look to be working, so that is something for us to perhaps get fixed. Could make the above much easier.

**Comment by DanVanAtta** [comment]
Feel free to re-open for additional help.
