### ISSUE TITLE
try with autocloseable should only have one closeable

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1507]
Java has trouble with java7 auto-close blocks that create multiple closeable objects. Instead of:

```
try(Closeable c1 = ...; Closeable c2 = ...;) {
```
Do this:
```
try(Closeable c1 = ...) {
  try(Closeable c2 = ...) {
```

Below is a grep that regex matches when we have a try-with-autoclose block that contains a ';' on the same line. By convention we avoid unnecessary syntax, so if there is one statement, then the ';' is extra syntax and can be removed. Otherwise it means we have two statements in the one try block.
 
```
~/work/triplea$ grep -A1 -r "^\s*try *(.*;.*"
src/games/strategy/triplea/ui/TripleAFrame.java:    try (FileOutputStream fos = new FileOutputStream(filename); ObjectOutputStream oos = new ObjectOutputStream(fos);) {
src/games/strategy/triplea/ui/TripleAFrame.java-      oos.writeObject(m_data);
--
src/games/strategy/triplea/ui/menubar/ExportMenu.java:      try (final FileWriter writer = new FileWriter(chooser.getSelectedFile());) {
src/games/strategy/triplea/ui/menubar/ExportMenu.java-        writer.write(xmlFile);
--
src/games/strategy/triplea/ai/proAI/logging/ProLogSettings.java:    try (final ByteArrayOutputStream pool = new ByteArrayOutputStream(10000);
src/games/strategy/triplea/ai/proAI/logging/ProLogSettings.java-        ObjectOutputStream outputStream = new ObjectOutputStream(pool);) {
--
src/games/strategy/engine/framework/ui/NewGameChooserModel.java:    try (ZipFile zipFile = new ZipFile(map);
src/games/strategy/engine/framework/ui/NewGameChooserModel.java-        final URLClassLoader loader = new URLClassLoader(new URL[] {map.toURI().toURL()})) {
--
src/games/strategy/engine/framework/ProcessRunnerUtil.java:        try (Scanner scanner = new Scanner(s);) {
src/games/strategy/engine/framework/ProcessRunnerUtil.java-          while (scanner.hasNextLine()) {
--
src/games/strategy/engine/framework/startup/ui/PBEMSetupPanel.java:      try (FileInputStream fin = new FileInputStream(m_file);
src/games/strategy/engine/framework/startup/ui/PBEMSetupPanel.java-          ObjectInput oin = new ObjectInputStream(fin);) {
--
src/games/strategy/engine/framework/startup/ui/PBEMSetupPanel.java:      try (FileOutputStream fout = new FileOutputStream(m_file, false);
src/games/strategy/engine/framework/startup/ui/PBEMSetupPanel.java-          ObjectOutputStream out = new ObjectOutputStream(fout);) {
--
src/games/strategy/engine/framework/startup/mc/ServerModel.java:      try (ByteArrayInputStream input = new ByteArrayInputStream(bytes);
src/games/strategy/engine/framework/startup/mc/ServerModel.java-          InputStream oinput = new BufferedInputStream(input);) {
--
src/games/strategy/engine/data/properties/GameProperties.java:    try (ByteArrayOutputStream bos = new ByteArrayOutputStream(5000);
src/games/strategy/engine/data/properties/GameProperties.java-        ObjectOutputStream outStream = new ObjectOutputStream(bos);
--
src/games/strategy/engine/data/properties/GameProperties.java:    try (ByteArrayInputStream byteStream = new ByteArrayInputStream(byteArray);
src/games/strategy/engine/data/properties/GameProperties.java-        InputStream inputStream = new BufferedInputStream(byteStream);
--
src/games/strategy/engine/random/PropertiesDiceRoller.java:    try (CloseableHttpClient httpClient = HttpClients.createDefault();) {
src/games/strategy/engine/random/PropertiesDiceRoller.java-      HttpPost httpPost = new HttpPost(m_props.getProperty("path"));
--
src/games/strategy/engine/random/PropertiesDiceRoller.java:      try (CloseableHttpResponse response = httpClient.execute(hostConfig, httpPost);) {
src/games/strategy/engine/random/PropertiesDiceRoller.java-        HttpEntity entity = response.getEntity();
--
src/games/strategy/util/PointFileReaderWriter.java:    try (InputStreamReader inputStreamReader = new InputStreamReader(stream);
src/games/strategy/util/PointFileReaderWriter.java-        LineNumberReader reader = new LineNumberReader(inputStreamReader)) {
--
src/games/strategy/util/PointFileReaderWriter.java:    try (InputStreamReader inputStreamReader = new InputStreamReader(stream);
src/games/strategy/util/PointFileReaderWriter.java-        LineNumberReader reader = new LineNumberReader(inputStreamReader)) {
--
src/games/strategy/util/PointFileReaderWriter.java:    try (InputStreamReader inputStreamReader = new InputStreamReader(stream);
src/games/strategy/util/PointFileReaderWriter.java-        LineNumberReader reader = new LineNumberReader(inputStreamReader)) {
--
src/games/strategy/util/PointFileReaderWriter.java:    try (InputStreamReader inputStreamReader = new InputStreamReader(stream);
src/games/strategy/util/PointFileReaderWriter.java-        LineNumberReader reader = new LineNumberReader(inputStreamReader)) {
```

**Comment by RoiEXLab** [comment]
What do you mean with "Trouble"?

**Comment by DanVanAtta** [comment]
trouble => incorrect behavior, no guarantee that the multiple closeables will get closed.

**Comment by ron-murhammer** [comment]
@DanVanAtta Interested in this. Do you have a reference regarding the issues? Or reproducer?

**Comment by ssoloff** [comment]
Sorry to keep this question going, but I'm interested in learning more about this problem, as I use multiple resources in a single try-with-resources statement regularly.  @DanVanAtta, could you please provide a reference to the problem you're talking about?

I am aware of the problem when merging two resources that require management into a single try-with-resources managed variable.  For example:

```java
static void printToFile(File file, String text) {
    try (BufferedWriter bw = new BufferedWriter(new FileWriter(file))) {
        bw.write(text);
    } catch (IOException ex) {
        ex.printStackTrace();
    }
}
```

If the `BufferedWriter` constructor throws, the `FileWriter` will not be closed (this is, admittedly, an unrealistic scenario).  However, I always thought that splitting this into two managed variables within a single try-with-resources statement was acceptable:

```java
static void printToFile(File file, String text) {
    try (FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw)) {
        bw.write(text);
    } catch (IOException ex) {
        ex.printStackTrace();
    }
}
```

Because the JVM guarantees that if, for example, the `BufferedWriter` constructor throws, the constructed `FileWriter` will still be closed.

Just for kicks, I created a [test file](https://github.com/triplea-game/triplea/files/743775/Test.java.txt) that has one method that uses two resources in one try-with-resources statement with multiple variables and a semantically-identical method that uses two resources in two nested try-with-resources statements.  I then extracted the [bytecode](https://github.com/triplea-game/triplea/files/743779/Test-multiple.javap.txt)
for the method with one try-with-resources statement and compared it to the [bytecode](https://github.com/triplea-game/triplea/files/743780/Test-nested.javap.txt)
for the method with two try-with-resources statements.  As you can see, other than the signature, the bytecode is identical.  Am I wrong to infer that if both styles of try-with-resources generate the same bytecode, they would both have the same issue with cleaning up multiple managed variables?

The previous bytecode was generated using OpenJDK 1.8.0_121-b14.  The fact that Java 7 was specifically called out at the top of this issue compelled me to re-run the same test with Oracle JDK 1.7.0_80-b15.  However, the results ended up being the same.

**Comment by DanVanAtta** [comment]
When we upgraded to java7 try catch blocks in the code base this came up: https://github.com/triplea-game/triplea/pull/140

@ssoloff  good point to distinguish between:
```
  try (BufferedWriter bw = new BufferedWriter(new FileWriter(file))) {
```
and:
```
    try (FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw)) {
```

The first case causes problems. Pretty reasonable, the inner new FileWrite is evaluated inline, java7 try block never gets a chance to see it.

The regex given does not correctly identify the problem. Need a new one if we want to find more cases of the above.

**Comment by ssoloff** [comment]
Thanks for the reference, @DanVanAtta.  I read through the comments in that issue, but I couldn't find any discussion related to the problem raised at the top of this issue.  I did see several comments related to the problem we just ping-ponged (i.e. use `try (FileWriter fw = new FileWriter(file); BufferedWriter bw = new BufferedWriter(fw)) {` instead of `try (BufferedWriter bw = new BufferedWriter(new FileWriter(file))) {`) under the reference "don't use decorator pattern," but nothing about preferring one `AutoCloseable` per statement.

There were a lot of collapsed comments in that PR, so I suspect I may have just missed the relevant one.  Could you please provide a link directly to the appropriate comment(s)?

**Comment by DanVanAtta** [comment]
I should have elaborated more when stating:

> The regex given does not correctly identify the problem. Need a new one if we want to find more cases of the above.


The 'problem' stated at the top of the ticket is not actually a problem. It is a problem if multiple closeables are defined in one statement, but as multiple it is okay as has been discussed.  

The only task remaining is to find stuff like:
```
try (BufferedWriter bw = new BufferedWriter(new FileWriter(file))) {
```
Doing a quick grep, I found nothing. Seems like we're okay at this point. #140 had the right issue pointed out and seems to have been fixed.
