### ISSUE TITLE
Outdated maps on clients not being update

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1522]
When does Triple A check if the version of the triplea_maps.yaml file has been moved on? Do you have to go into the downloadMaps window? It seems that there are some people out there with some outdated versions of global 1940.

**Comment by DanVanAtta** [comment]
It checks on a periodic basis, I think once a month. Otherwise need to go to the download window.

**Comment by ssoloff** [comment]
@simon33-2 @DanVanAtta Might want to consider re-opening this issue...

While working #1602, I had to modify the code in `MapDownloadController#populateOutOfDateMapsListing()` (as of 1.9.0.0.3932):

```java
  private static Collection<String> populateOutOfDateMapsListing(
      final Collection<DownloadFileDescription> gamesDownloadFileDescriptions) {

    final Collection<String> listingToBeAddedTo = new ArrayList<>();

    for (final DownloadFileDescription d : gamesDownloadFileDescriptions) {
      if (d != null) {
        File installed = new File(ClientFileSystemHelper.getUserMapsFolder(), d.getMapName() + ".zip");
        if (!installed.exists()) {
          installed = new File(GameSelectorModel.DEFAULT_MAP_DIRECTORY, d.getMapName() + ".zip");
        }
        if (installed.exists()) {
          if (d.getVersion() != null && d.getVersion().isGreaterThan(DownloadMapsWindow.getVersion(installed), true)) {
            listingToBeAddedTo.add(d.getMapName());
          }
        }
      }
    }
    return listingToBeAddedTo;
  }
```

During testing, I observed that the files assigned to `installed` are using the wrong name.  For example, for the tutorial map, the file name is `Tutorial.zip` rather than `tutorial-master.zip`.  As this file does not exist (in either of the two directories used in the above code), the update check is never performed.

The code in `MapDownloadController#populateOutOfDateMapsListing()` doesn't appear to have changed since it was introduced in 736f3fc.  I don't know when the maps were first available on GitHub, but from the history of `ResourceLoader#getPaths()`, it looks like the `<normalizedGameName>-master.zip` file name format was introduced in 372f336 (2016-09-01).  Could this feature really have been broken for almost six months before someone reported it on the forums?

Anyway, if this indeed requires a fix, it seems like the logic for generating map name candidates needs to be in a single location.  Any recommendations for the best package/class to host this?

**Comment by ssoloff** [comment]
@simon33-2 @DanVanAtta Bumping the [previous comment](https://github.com/triplea-game/triplea/issues/1522#issuecomment-290892285)...

**Comment by ssoloff** [comment]
@simon33-2 When you have a chance, can you please verify that this issue is fixed in build 4319 or later, and then close it?

**Comment by simon33-2** [comment]
Well it worked last time I tested it, I'm sure it still does.
