### ISSUE TITLE
this happens when I hit the play online button on my girlfriends windows 8 comp

### ISSUE THREAD

**Issue by guerrillaj** [triplea-game/triplea#1530]
https://gist.github.com/guerrillaj/03d427a598d1e5f0a86cee566d491ca0#file-online-play-issue

**Comment by RoiEXLab** [comment]
1. Please post long Stacktraces like this one in a [gist](https://gist.github.com) in order to keep issues clean...
2. There are a couple of possibilities which could be causing this issue:
* Open your command prompt (WindowsKey + R) and enter `setx _JAVA_OPTIONS -Djava.net.preferIPv4Stack=true`
* Try temporarily disabling anti-virus programs, or other programs controlling your connection ("RelevantKnowledge" seems to cause problems if installed)

**Comment by guerrillaj** [comment]
first part worked. thanks

**Comment by RoiEXLab** [comment]
No problem, fell free to close this issue then.
