### ISSUE TITLE
Any interest in creating a web-based version of TripleA?

### ISSUE THREAD

**Issue by jonearley** [triplea-game/triplea#1613]
Has this already been discussed? If yes, are those discussions available somewhere I could read up on?

**Comment by jonearley** [comment]
https://github.com/triplea-game/triplea/issues/284

A related discussions I started in 2015. Checking back in about any new interest.

**Comment by RoiEXLab** [comment]
I'm currently working on a UI-Rewrite...
TripleA will be based on javafx in the (not near) future.
This means the triplea-code is going to be more modular which could potentially enable us to implement an android version. 
But still. Porting triplea to another platform would be an incredible large task...

**Comment by RoiEXLab** [comment]
In short: Since nobody is being paid and we all work on this project in our freetime nobody is probably going to work on this in the near future.

**Comment by ssoloff** [comment]
(Note that I'm speaking for myself here and not on behalf of the TripleA org.)

One of the primary reasons I got involved with TripleA a few months ago was for this very reason.  I wanted to see what it would take to build a web client (and I'm embarrassed to say that I never came across #284).  I figured the best way to do so was to just dive in and start fixing bugs and adding features.  That experience has made me realize that there are a lot of infrastructure issues that would have to be addressed first, and #284 describes them pretty well.

I think @RoiEXLab's pending JavaFX client (#1588) will go a long way (hopefully all the way!) to making a clean separation between the client and non-client portions of the code.  Ideally, I'd like it if we could split the current monolithic app into distinct client and server processes, possibly even in separate repos.  That would make adding alternative clients in the future that much easier.

As also has been pointed out numerous times, the coupling between the domain model and the persistence layer is another big issue.  I plan on prototyping a possible solution to that problem soon.  Solving that issue is a first step to moving away from the RMI-like network API TripleA currently uses.  A more platform-agnostic network API would obviously make non-JVM-based clients easier to write.

IMO, there seems to be a lot of up-front work required before entertaining the idea of new clients.  Putting additional effort into fixing these larger infrastructure issues is probably the best way forward, and I'm sure that any help that is offered on those tasks would be welcome.

**Comment by RoiEXLab** [comment]
@ssoloff Couldn't have explained this better!

**Comment by simon33-2** [comment]
I'm not aware of a JVM for either iOS or Android so doesn't this then require a complete rewrite in some other language? Then you've UI issues on whether a drag means to scroll or move units. I think the screen on even the largest phone is going to be too small to be fun to play.

So I think there are large obstacles and small and debatable gains from this idea.

**Comment by RoiEXLab** [comment]
@simon33-2 This is correct, but Android uses Java as it's default language

**Comment by ron-murhammer** [comment]
I think there is a lot of interest in doing this but a lot of work still needs done as @ssoloff lays out fairly well. I would also be interested on whether a web-based interface could handle the image sizes for some of the larger maps as well. But it would be great to eventually get to something like http://www.freeciv.org/

**Comment by RoiEXLab** [comment]
Interesting: Found [this](https://github.com/jashkenas/coffeescript/wiki/list-of-languages-that-compile-to-js#javajvm)

**Comment by RoiEXLab** [comment]
Also worth mentioning that TripleA is a fairly old project, which comes with lots of legacy issues...

**Comment by simon33-2** [comment]
@RoiEXLab  Does that mean a JVM isn't required for Android?

**Comment by RoiEXLab** [comment]
This means, we can reuse all the backend triplea code for Android... We'd need to create a GUI though.
Since Android 5 or 6, java source code is copiled ahead of time during installation (that's why it takes so long). This means the JVM is basically built into the android ecosystem (it's no seperate application)

**Comment by RoiEXLab** [comment]
@ssoloff I'd like to hear your opinion on #1505 
I had a suggestion about the RMI successor, which would make fixing network releated bugs so much easier...

**Comment by nateous** [comment]
I've been wanting to write my own web based version for years but haven't found the time. 

Perhaps writing an api so that front ends can use it would be worth while?

I'm a c# developer.

**Comment by simon33-2** [comment]
It still raises the question about why playing Triple-A on a screen smaller than 13 inches would be fun. It's small enough on a laptop.

**Comment by nateous** [comment]
The interface could change to accommodate smaller screens. I don't think it would be impossible.

**Comment by RoiEXLab** [comment]
The current problem with the code is that "backend" and "frontend" are tied together, we'd need to refactor the code in order to have some sort of modular frontend...

**Comment by nateous** [comment]
Which is why I would start a total rewrite. :)

**Comment by simon33-2** [comment]
> The interface could change to accommodate smaller screens. I don't think it would be impossible.

I can't conceive such a change. What do you suggest?

**Comment by nateous** [comment]
For instance, when choosing to attack you could select a territory to attack first, then a list of units in range could show up to choose from. Along with helpful buttons to select which units you want to use or all or all from just one territory. 

That's just off the top of my head, but you can conceive of any number of ways to accomplish the tasks without having to have a huge map.

**Comment by nateous** [comment]
But again, starting with an api first would them allow multiple UIs to be created.

**Comment by simon33-2** [comment]
Doesn't sound fun to play. There is a need to be able to see at a glance the strength of a territory.

**Comment by nateous** [comment]
Sounds like I need to quit talking about it and make it happen, if not only to allow my friends to play! Haha

**Comment by DanVanAtta** [comment]
Closing for now. Please re-open or a new issue to continue the conversation

**Comment by nateous** [comment]
That's fine. If I rewrite it, it would be in c#. So I will start a new repo.
