### ISSUE TITLE
Can the travis build compile triplea_maps.yaml versions?

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1633]
Had this idea that you could put into the travis build automatic generation of the version numbers. Use the Github API to extract the version from all the maps. The only problem I foresee with this is that the build would need to push the parsed file to somewhere to host it. Surely that's a solvable problem. You could also get rid of the different version numbers in the triplea_maps.yaml and the maps themselves.

**Comment by RoiEXLab** [comment]
Somewhat related to #1444
But this seems like a good idea to me, although I'd like to use the method of #1444 which would get rid of the file entirely.

**Comment by simon33-2** [comment]
I think the method outlined in #1444 (looked for that issue but couldn't find it) sounds cool but would be enough overhead to make it impractical to do for every Triple-A startup.

I thought of this after noticing the game_engine.properties edit in the .travis.yml and thinking of this issue.

**Comment by DanVanAtta** [comment]
This topic may be out of date since we moved to downloading the tip of 'master' for any map, and not specific versions.  @simon33-2 , could you confirm?

**Comment by simon33-2** [comment]
Not really because the version number in the .yaml file is still used to work out if we need to move it on. The problem is that the version in that is necessarily arbitrary because the version in the .xml can't be used - there are many .xml files to one repo and also the companion files can be changed without changing the .xml.

Either way, it isn't the end of the world.

**Comment by RoiEXLab** [comment]
Just mentioning: The "topics" API is now in an open beta stage, so we could potentially revisit this topic again, just one request needed to categorize all of the maps.

I agree with @simon33-2 that this is probably the best idea. @DanVanAtta we still can download specific revisions of the maps, a feature we should use once we change this build step.
Every commit has a SHA-1 hash, and a corresponding zip file to download, so if we integrate this into travis, we can retrieve the latest commit, and therefore map the latestcommit with the current version number, so maps will continue to be compatible to versions of triplea even if the user is not updating!
This will require a couple of requests, 1 or 2 per map, but in my opinion it would be worth it.

Thoughts?

**Comment by DanVanAtta** [comment]
Tracking SHA-1 versions could get very painful. Remember we want the map making process to be self service, needs to be as easy as possible for map makers. We had a travis build so that release numbers could be used, but that overhead was not great for admins and actually made it harder for people to host in github. They tended to throw their hands up seeing their was a piece only we could do. The current hope is folks would set up a repo and then we fork them into the triplea-maps org to adopt the maps.

**Comment by RoiEXLab** [comment]
@DanVanAtta With an "automatic compilation" map makers don't need to worry about that, the link is generated automatically every time a travis build runs. If we merge not frequently enough for this, we could also use travis "cronjobs" which make travis run every hour/day/week/month automatically without any push

**Comment by DanVanAtta** [comment]
The update cadence would be wrong, no way to push a new map immediately, and cron builds would generate 99% no-change builds.

Maybe having two files yaml config files would be the way to go, the first one being a 'driver' file for the second that is auto-generated. The seed file would look like the yaml file of today, though it would be missing the download URL. When the version is updated on that file, on travis build, we would check that file vs the generated file, any maps with a newer version we would fetch the latest SHA-1 and update it in the latest generated map listing file.

This way map makers could actually request map updates at explicit intervals instead of having the latest always be 'the latest'. It's also nice that the update number is more functional, not just a notification flag, but actually controls when the map version changes.

**Comment by DanVanAtta** [comment]
Re: engine versions and map XMLs

I strongly believe we need to add a "XML" version to our XML specs. This way the engine could read for example "version 2.0" and load perhaps a completely different set of parsing rules, but if that if that version is missing then we default the legacy XML parsing.
