### ISSUE TITLE
Checkstyle: Two consecutive capital letters?

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1659]
What is the approved naming method for variables like playerID - playerId?

Also variables to do with SAX parsing, should they be Sax?

Seems strange to me, that's why I'm asking.

**Comment by ssoloff** [comment]
Good question.  This (AbbreviationAsWordInName) is one of the Checkstyle rules I haven't been fixing because a) there seems to be a long history in the project of using capitalized abbreviations in type/member names, and b) I haven't seen any of the committers flag such names in PRs as they have some other naming conventions (e.g. `m_` prefixes).  I was waiting until all the straightforward violations were fixed before posing a question asking if the committers want to adopt this convention or to simply disable and/or modify this rule.  However, this seems as good a time as any.

In summary, the Google style guide allows only two consecutive capitalized letters in type/member names, and the name must not end with a capital letter.  See [this summary](http://checkstyle.sourceforge.net/reports/google-java-style-20170228.html#s5.3-camel-case) for examples.

If the committers determine that strict Google style in this respect is too aggressive, there are some alternatives that can be employed rather than simply disabling the rule.  One possibility is to whitelist the allowed capitalized abbreviations using the `allowedAbbreviations` attribute.  For example, if we wanted to allow `PlayerID`, then `ID` could be added to the allowed abbreviations list.

**Comment by simon33-2** [comment]
There's a whitelist? Let's use that if no better idea comes up.

**Comment by RoiEXLab** [comment]
SHA should also be added to this whitelist...

**Comment by DanVanAtta** [comment]
Late to the party here - good question indeed to bring up.
I think there is enough of a mix, and has been enough change that we can decide which way we want to go on this. The previous rules were not too much beyond the variable prefixing, which we have since dropped.

Are there votes to go with all caps for acronyms? Votes for lower case for acronyms after first letter? I personally find 'HttpConnection" to be easier than "HTTPConnectoin" (Particularly on the 'PC' word boundary), but once determine either way is fine, and we can update the checkstyle rule as agreed.

I think that then leaves it to more or a less a straight vote, unless there is perhaps another proposal on how to proceed .

**Comment by simon33-2** [comment]
I'd have playerID rather than playerId.

**Comment by ssoloff** [comment]
I prefer option (2) simply because I don't want to have to remember what the exceptions (i.e. the whitelist) to the general rule are. :smiley:

**Comment by RoiEXLab** [comment]
I'd prefer the exceptions, but I'd go with option 1

**Comment by ron-murhammer** [comment]
So based on #1730 looks like at least @DanVanAtta has chosen option 2. My vote is for option 2 and we should document the decision somewhere. Unfortunately I think the majority of the code uses option 1 so it'll take some time to change.
