### ISSUE TITLE
Galatic War - some bugs 

### ISSUE THREAD

**Issue by Falkon98** [triplea-game/triplea#1662]
Just some errors I noticed, will comment more once fully play tested for the FFA Star Wars Galactic Wars:

FFA - Assassin Droid does NOT give the -3 to one unit, also it's description is wrong in the "i" on the map and in the game notes and unit buy

FFA - Combat-Speeder-Group and other faction units give +1 to 2 units, this needs to be noted in unit help, the "i" on the game map and unit buy

FFA - The fortifications, only allows 1 on any territory, needs to be noted in game notes and the "i" on the game map and unit buy.  No reason to not do 5 or more.

FFA - Jedi - the +1 in def/att is not noted in the "i" on the game map or in the notes and unit buy.

Thanks, Falkon

**Comment by ron-murhammer** [comment]
@FrostionAAA FYI. Probably should move this to the appropriate map repo.

**Comment by FrostionAAA** [comment]
I will look at this soon. @Ron-murhammer Do you mean that this should move to the triplea-maps/Project issues? I don't know how to do this.

**Comment by ron-murhammer** [comment]
@FrostionAAA Yeah, I was thinking of re-creating the issue in 1 of these 2 locations:
https://github.com/triplea-maps/Project/issues
https://github.com/triplea-maps/star_wars_galactic_war

**Comment by FrostionAAA** [comment]
@Falkon98 
Thank you for reporting the issues. I don’t think many people find and report Star Wars map issues, so I am glad someone does. I have tried to fix the above issues on all the Star Wars Galactic War and Tatooine War maps. Please report back if you find any more errors. If you want to download the new versions, then uninstall the old versions and download the maps again. New version is called v1.4.2.

• Assassin-Droid and the Saboteur units are now fixed. Some text has also been added to notes.
• Combat-Speeder-Group unit seems to work as it should, no fix here. I think the Jedi might have given you a false impression of who gave who an extra +1.
• The Jedi have been fixed to not give 11 times +1 in some cases, but only 10 times +1 always.
• Fortifications are self repairing each round. That is why I would like to keep them down to only one placement per territory. The one placement policy is now in the notes.

@ron-murhammer
I seldom look at these issue posts, so I actually only saw this because you @ me. I can see that there is some other map issues posted here also, so to me it is fine if they are just posted here.

**Comment by FrostionAAA** [comment]
If there are no follow ups here, I would consider this issue to be closed :-)
