### ISSUE TITLE
Changes which introduce incompatibilities

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1735]
I think we need a place to collect changes which cause incompatibilities to 1.9.0.

That means either a fork or a branch. Not sure if it is possible to create PRs into a branch so it might need to be a fork.

**Comment by ron-murhammer** [comment]
@simon33-2 I believe you can make PRs into a branch in the main repo here.

@simon33-2 @DanVanAtta Let's sort out the autosave incompatibility issues before merging any more PRs. Then we can determine if there are any other changes we want to make before we do a compatible release (1.9.0.1).

**Comment by DanVanAtta** [comment]
Following up from: https://github.com/triplea-game/triplea/pull/1672, I don't think there are any current incompatibility problems. At the same time we need to make this a non-problem, and/or anyone able to check for incompatibility problems easily.

Moving past that, are a couple of times:
- what do we want to include before we move to 1.9.1?
- what updates do we want to try and get in for 1.9.1 that require a version update?
- how do we coordinate the work to 1.9.1?

From my point of view:
- I think we should get the user DB migration going before 1.9.1. That would need a few weeks to before it is ready, then it'll need time to migrate users after being deployed (at which point going to 1.9.1 is okay)
- What to include in 1.9.1 is a pretty meaty topic. I think we should include serialization proxy so we can eliminate save game compatibility issues. Part of that work it would be natural to do variable renaming since those have to be updated/touched anyways. A global variable rename would be good to include. There may be some map items that are not compatible that we may want to consider.
- How to do the transition? 
No need for a fork, we can create a 1.9.1 branch and do PRs into that. There is some overhead there though and some potential problems. We may want to consider the branch approach a bit more. Another option is to pick a point when master moves to 1.9.1 and we simply then allow and start accumulating non-backwards compatible changes. The branch approach can become difficult if it starts to contain a lot of changes different master, and secondly it adds overhead. I can see a short-term benefit for a 1.9.1 branch, but long term it could become very troublesome (testing scope can increase as well, a number of new factors can start to come into play). 

Perhaps going forward let's first consider what we want in  1.9.0 and 1.9.1. Then it may be a bit easier to discuss the details of the branching strategy, we'll know a bit more what we'll need to support and have a better idea of potential pitfalls of either approach.

**Comment by ssoloff** [comment]
> I don't think there are any current incompatibility problems

IIRC, #1583 broke serialization, but it looks like @simon33-2 included changes in #1734 to fix that.  In light of the recent comments in #1672, the auto-save-2 stuff would simply have to be removed from #1734 to leave it as a pure #1583 fix.

**Comment by simon33-2** [comment]
I reckon just put #1734 into 1.9.0 but exclude it from 1.9.1. That way we keep the refactoring in #1583 in the code line.

Regarding the list of things we would want in it:
- Rocket final fix (currently open PR doesn't quite fix it all)
- Sub submerge limitations fixes, particularly that submerge is queried and only afterwards checked to see if it is mandatory
- Checkstyle upgrades including variable naming so we don't have 5k warnings, which is ridiculous.

None of that is really a very good reason to ask users to upgrade though. If #1645 could be fixed that would be one of the last remaining niggling annoyances in the system.

The suggestion of serialisation proxy would still mean that 1.9.1 could neither create or use 1.9.0 save games, right? Would it mean that we wouldn't have the same problems looking forward? If so, probably should be 2.0.

**Comment by ssoloff** [comment]
> what do we want to include before we move to 1.9.1?

Might want to consider merging #1695 before the next release.  I don't know how important the out-of-date map check is to users and map makers, but `triplea_maps.yaml` seems to receive version bumps pretty regularly (1-10 times a month?).

**Comment by ron-murhammer** [comment]
Moving conversation to #1768
