### ISSUE TITLE
Change TripleA versioning

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#1739]
I'm a huge fan of semantic versioning and I believe triplea should go for it as well.
Because of travis we need to keep the build numbers though!
I'd like to have `major.minor.patch.build` e.g. `1.9.0.4313` instead of `1.9.0.0.4313`.
Every time we'd like to evaluate the versions we'd just cut off the build number.
Read more about semantic versioning [here](http://semver.org/#summary).

**Comment by ron-murhammer** [comment]
Agree. We really don't have any good reason to have the extra number.

**Comment by simon33-2** [comment]
Although it isn't conforming because semantic numbering updates only the first number for incompatible changes.

**Comment by RoiEXLab** [comment]
But how often are we creating incompatible changes?
Once we have a system allowing to change code without breaking savegames this should happen pretty rarely

**Comment by simon33-2** [comment]
We don't have that system yet.

**Comment by DanVanAtta** [comment]
@RoiEXLab   Lost in the weeds of the documentation, there is some background on this topic, see notably:  https://github.com/triplea-game/triplea-game.github.io/blob/master/dev_docs/dev/version_numbers.md#future-version-numbers

We intended to chomp a version number when we moved to 1.9, but that was lost in the tangle. The overall goal was set to get to a single release number plus build number. 

I think the approach could be revisited. We outlined in the docs a way to get there incrementally as we solved compatibility problems in:
- network (java RMI)
- save game loading (serialization)
- map XML loading (xml format,  the reflection that used to happen is with some luck removed completely)


Instead maybe it makes sense to jump to the final version number format/scheme. In that case the only decision I think is do we stick with the single number + build number plan, or go with: `major.minor.patch.build`.


First some requirements I can think of here:
- users should have a way to see exact version, and be able to report it to us. That version should map to an exact git commit.
- in case we can't make a set of backwards compatible changes, we do need a way to bump at least one version number (can't just be a build number).  This is mostly for messaging and coordination to users. If we run multiple lobbies for example, it could be easier to say one version is `1.X` and the other is `2.Y`. In contrast we could message:  lobby 1 is for version `X < 5000`, and lobby 2 is for versions `X > 5000`. With that example in mind, it's not impossible that we could get away with just the build number, but I think we would want to weight the options here in more detail.

With that context:

### Question 1 - do we change version number incrementally by dropping digits over time, or go whole sale and move directly to a final plan?

For version number, since there is pain on each upgrade, I think going whole sale is better option.

### Question 2 - do we use 4 version numbers, or 2?

`major.minor.patch.build` vs `major.build`


When answering this question, I think some relevant context is the expectation of how often we will do non-backwards compatible changes and also how often we will release. My hope/goal is that we will remove the usual suspect for compatibility problems and then rarely (once every few years maybe) have to do a major version number change. The other side, how often we will release, my hope/goal here is that we will be able to release after nearly every PR. Our deployment automation is just about there, we need some more work on our testing infrastructure to really get there more easily. Today, I would expect whenever we merge a PR and have tested for compatibility, that we would mark the latest build as the latest stable/release build.

So, my answer to this question is go with two numbers. User facing it is easier than having 'minor' and 'patch' thrown into the mix. I could be convinced otherwise, but I don't quite see the value in the overhead of the `minor.patch` numbers, to either developers or game players. So if we would like a 4 number versioning set up, I think the key would be to clearly map and define what the minor and patch numbers would be, and how we would use that information.

**Comment by simon33-2** [comment]
2 numbers makes sense but 4 might be easier to implement.

Users can already see the build number. No problem to solve.

**Comment by ron-murhammer** [comment]
I think I'd prefer sticking with 3-4 version numbers. I see benefits from at least 3 numbers:
**First** - major, compatibility number, only if this number is the same will save games and lobby work
**Second** - minor/patch release number, doesn't affect compatibility but we can increment it to drive folks to a new release as otherwise they never upgrade (if we eventually have an update process prompt from TripleA then this wouldn't be needed)
**Third** - build number which specifies exactly what commit

So essentially, major.minor.build. If its easier then we can keep one additional number out front which is never really changed to make it: 1.major.minor.build

**Comment by simon33-2** [comment]
I think getting rid of the 3 point incompatible versioning is a bridge too far at present. Sure, the fourth number achieves nothing really but there's no need to change the way the first 3 digits work.

**Comment by DanVanAtta** [comment]
I'm okay with the 3 number system, agree about the bridge too far.

I submitted a PR to update the version numbering docs: https://github.com/triplea-game/triplea-game.github.io/pull/208 (I've also been going through and trying to trim our docs some, some other PRs there too to shorten things up).

I think we're pretty decided on a  3 number system. Next steps as far as I know would be to update the game engine, and take care of serialization when reading old save games, and any logic the game engine has built into it to handle version number.

**Comment by simon33-2** [comment]
So what is the decision, I'm not sure I understand. 

Next incompatible release will be 2.0.build?

**Comment by simon33-2** [comment]
I think going to 1.9.build will confuse the compatibility check for existing installations out there.

**Comment by DanVanAtta** [comment]
`2.0.build` sounds right. Likely we'd have to do that jump as an incompatible change for the reason you mentioned @simon33-2

**Comment by ron-murhammer** [comment]
So for this next compatible release, I think we leaving versioning as is and go to 1.9.0.1.build.

For the next incompatible release, we do either 1.10.0.build or 2.0.build depending on if we want 3 or 4 numbers and how easy it is to adjust the engine to handle it.

**Comment by DanVanAtta** [comment]
I had a different expectation than going to 1.9.0.1. 

I expected the last compatible release to be pinned at whatever number we leave off at, eg: 1.9.0.0.x
Instead we update the version number directly to `2.0.build` (that option instead of `1.10.0.build` since leading number would be the major  (compatibility)  version number). I'm not very clear otherwise on why we would go to `1.9.0.1.build` instead of `2.0.build`

**Comment by simon33-2** [comment]
Don't see the need for change for the next compatible release.

**Comment by simon33-2** [comment]
Why not 2.build?

**Comment by RoiEXLab** [comment]
@DanVanAtta @ron-murhammer @ssoloff I messed around with the Version class in order to "enable" TripleA to recognize the new version format e.g. `MAJOR.minor.build`.
Currently there are a couple problems with this. How would TripleA know which build it is?
We need gradle to somehow generate a file telling triplea which build number to use. (MAJOR.minor should be set manually)
If this file is not existing, we just display `MAJOR.minor.experimental` or something similar.
What's kind of annoying is that the Version class is being serialized with every savegame. This means we can't remove or modify existing fields.
Idea is to modify the code so every "4/5 part version number is valued less than" version numbers  using the "new" format.
Thoughts?

**Comment by simon33-2** [comment]
Can I suggest the next compatible release should be 1.9.0.build as suggested in the OP.

Incompatible we could go the whole hog to 2.build although the major number can increase quite quickly with that. That raises the question: so what? Although the same question can be asked about why there is a need for change from the status quo.

**Comment by RoiEXLab** [comment]
@simon33-2 I agree, I think this is a good idea 👍

**Comment by DanVanAtta** [comment]
Summarizing latest state - seems like there is agreement to lop off a build number at the next incompatible release.

**Comment by simon33-2** [comment]
By now, all of the bots should have #2394 so I think the last version number can be lopped off right now - although I think that latest_version.properties may need to be left as is.

No need to wait for an incompatible version.
