### ISSUE TITLE
Derby DB migration - Integration testing without Derby

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1758]
FYI I'm looking to introduce new integration tests to test the new database that replaces Derby DB. I'm planning for the DB set up to be 'offline' from gradle. The following looks like a good model for the gradle part that will actually run the integration tests: https://selimober.com/gradle_unit_integration/

Goal for this issue, and points of discussion: I'd like to sound out my plan a bit, double check my thinking, and see if there are any suggestions. 

### Existing context:
- We have Derby DB. It's unit test configuration is very close to the prod configuration, so there is overlap between a unit test and integration test for it (see: https://github.com/triplea-game/triplea/blob/master/src/test/java/games/strategy/engine/lobby/server/userDB/DbUserControllerTest.java)
- Pertinent to the dev workflow when working on the lobby, when firing up a lobby  instance, there is some additional configuration compared to the unit tests (there are gaps in the existing configuration)

### Problem to solve
- After moving away from Derby DB, what does the new dev work flow look like when working on lobby?
- What does a new integration test look like after moving away from Derby DB?

### Proposal:
- unit tests will not run DB integration tests, and will not use a live DB  (no impact to dev's working on the game engine for example)
- gradle will have a new 'integTest' task added that will run integration tests that will hit an assumed to be running DB, that step will be added as part of the build and run on Travis. The setup there will be similar to what we run in prod

### Why not use HSQL DB, an in-memory DB fired up by unit tests? That would be very similar to Derby DB?

- Still has drift between integ config and prod config, it is an incomplete solution (grant it, HSQL does a good job of keeping the drift relatively small)
- MySql infrastructure testing problem left unsolved. 

The proposal I would have is that we set up our DB in Travis exactly how we would it up in prod. Then we run gradle integ tests, and those tests will then verify how we set up DB schema, increasing test coverage. Meanwhile normal unit tests have no reliance on a live DB, and can be run as normal.

### Why not use docker?

Still punts on a few problem, it's another layer, and requires some additional infrastructure compared to not having it.  If we had a deeper stack, or more complicated setup than install a pretty standard DB, then there would be stronger reason for it. Until then IMHO it adds more complexity than it removes, and does not even solve everything. For example, instead of documenting how to install DB, we'd have to document how to create a docker image, how to install DB to that, create some infrastructure to create a docker image, upload it somewhere, and then document how to install docker locally for development.  

When the install to image part is relatively simple, the overhead of the docker VM is not very beneficial. worse yet it can be challenging sometimes when setting up VMs from scratch and deploying schemas to have fast test iterations.

### Moving Schema setup control out of code

Today we have custom code that checks for tables and creates them if not present. It's simple, and has worked pretty well. There appears to be a number of advantages to removing this from code entirely:
- we are setting up DB before integration tests anyways, running schema as part of that is pretty natural and will extend the test coverage of integrate tests.
- there are some inherit limitations when code is in control of DB schema, and it can make some upgrades more difficult than they need to be. The simpler, finer grain control of doing DB upgrades offline before application upgrade can really help, at the very least the code is simplified since it does not have to worry about schema.

happy to discuss further and answer questions, thanks in advance for the consideration/feedback.

**Comment by ssoloff** [comment]
👍 for introducing explicit integration tests.  I've been burned in the past using HSQLDB in unit tests that produced false positives.  I learned the hard way that it's much more robust to stub the data access layer during unit testing and instead use integration tests to verify that "last mile."

Beyond database testing, I think adding an integration test configuration will be beneficial in other ways, as well.  It opens the door to other types of integration tests which we currently lack.  I'm not suggesting we start writing lots of integration tests (test pyramid and such) but covering the most important use cases would go a long way to building confidence in further automating the release process.  Even a few simple automated smoke tests for basic play would be a Good Thing.

One suggestion...  Now that Travis supports [build stages](https://blog.travis-ci.com/2017-05-11-introducing-build-stages), it might make sense to run the `integTest` task as a separate stage in order to keep the compile and unit test feedback snappy.  I can easily see running integration tests breaking the "10-minute build" rule.

**Comment by DanVanAtta** [comment]
Thanks for the feedback. This has been moving along pretty nicely. Closing for now.
