### ISSUE TITLE
Windows 64bit-installer is missing

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#1790]
starting from 4468:

![tra](https://cloud.githubusercontent.com/assets/20812775/26711015/e3b71ae4-475d-11e7-955e-d1b3ec2f0e9b.PNG)

Please add it back. Thank you.

**Comment by panther2** [comment]
@ssoloff 
What happened?

**Comment by ssoloff** [comment]
Thanks for the heads up, @panther2!

Build 4468 actually failed while uploading the build artifacts to GitHub with a Bad Gateway error.  I restarted the build when I noticed the error, and it appeared to have completed successfully.  However, I just checked the [build log](https://travis-ci.org/triplea-game/triplea/builds/238529526) and saw these lines:

```
Deploying application
[secure]-1.9.0.0.4468-all.jar already exists, skipping.
TripleA_1.9.0.0.4468_windows-64bit.exe already exists, skipping.
```

While it looks like `triplea-1.9.0.0.4468-all.jar` made it through on the restarted build, for some reason, `TripleA_1.9.0.0.4468_windows-64bit.exe` did not.

I suspect it was a transient problem due to the restarted build.  Let's wait for the next build before taking any action.

**Comment by ssoloff** [comment]
Just for reference, builds [4443](https://travis-ci.org/triplea-game/triplea/builds/237768873) and [4459](https://travis-ci.org/triplea-game/triplea/builds/238164106) failed with the same Bad Gateway error, and both of them have no GitHub releases.

@panther2 Presumably, if I wouldn't have restarted build 4468, there would be no GitHub release with missing files for you to waste your time with.  Sorry about that. 😄

**Comment by panther2** [comment]
Never mind, I am glad it's only a temporary issue, @ssoloff :smile:

**Comment by ssoloff** [comment]
Build 4475 just completed successfully, and the corresponding GitHub release contains all build artifacts.

**Comment by panther2** [comment]
Downloading... thanks!
