### ISSUE TITLE
Working with checkstyle more easily

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1795]
1. I'd like to pitch the idea of creating a gradle task that would output the delta of checkstyle violations of current version compared to the count checked in to tripleA. A negative number would mean a reduction (maybe useful to print the total here too so we can update more easily), zero would be a passing build., greater than zero means new violations.

Question: Do we have it configured today so that reductions are automatically update in the config, or do we need to reduce the violation count by hand?

Otherwise I'd like to discuss any other thoughts/ideas about working with checkstyle more easily. I've got the Intellij plugin going and after having configured the import ordering, it's pretty okay :+1:   I do not yet though have a great way of knowing if I'm increasing/decreasing the total violation count.

**Comment by ssoloff** [comment]
> Question: Do we have it configured today so that reductions are automatically update in the config, or do we need to reduce the violation count by hand?

Yes!  We have a Travis script that will automatically update the thresholds if they decrease.  This has been a part of the build process for about two months now.  But, unfortunately, it has been broken since the beginning of May as documented in #1700.  Getting that fixed ASAP would help a lot with the Checkstyle thresholds getting out-of-sync on each PR merge.  (If my theory is correct, the fix is simply to regenerate the token associated with the `GITHUB_PERSONAL_ACCESS_TOKEN_FOR_TRAVIS` Travis environment variable, which shouldn't take more than a few minutes.)

> I do not yet though have a great way of knowing if I'm increasing/decreasing the total violation count.

Per above, you should only need to worry about increases.  Does the Checkstyle plugin for IntelliJ not highlight Checkstyle violations as you type?  When I see a violation highlighted as I'm typing new code, I'll stop to fix it if it was just a derp or something that requires about two seconds of thought.  Otherwise, I add a `FIXME` comment and come back to it before I make my next commit to avoid breaking my train of thought at the moment.

> I'd like to pitch the idea of creating a gradle task that would output the delta of checkstyle violations of current version compared to the count checked in to tripleA.

I looked at something like this when I first enabled Checkstyle in the build back in March.  It's complicated by the fact that existing violations may change lines due to insertions/removals.  So it may not be possible to accurately isolate them from the Checkstyle report alone.  You may have to analyze source, as well, which posits a bang for your buck question.

The simplest solution I could come up with that provides the best value is to diff the violations per file and show the line number candidates which **may** contain the new violations.  Your brain can usually then spot them quickly in the IDE with the appropriate Checkstyle plugin enabled.  Obviously, it's tough if you have a file with more than 30 or so violations, but I think those are becoming rarer as we've been fixing violations at a fairly regular pace.

Note that this would still require you to generate a baseline set of reports to diff against, so it's not a simple one-command solution.  I envisioned the workflow as the following:

1. Before starting a PR, run `check` on `master` (or on your freshly-created feature branch) and save the resulting Checkstyle XML reports someplace.
1. Code/test cycle.
1. If, after running `check` on your feature branch, the build fails due to an increase in violations, then run the `diffCheckstyle` (or whatever) task, passing the path to the folder where you saved the reports from step (1).  If you're doing this step regularly (ideally before each commit or at least before pushing to your remote), the resulting output should be relatively succinct.

If you ever rebase/merge `master` back to your feature branch, you'd need to regenerate the baseline reports in step (1).

Note that this doesn't really require a separate Gradle task to do the diff.  I've followed this process a few times simply using GNU `diff`.

However, as discussed above, I think the most efficient way to avoid adding new violations in the first place is by fixing the new violations as soon as the IDE plugin highlights them.
