### ISSUE TITLE
Middle Earth Map Stops working

### ISSUE THREAD

**Issue by Arkslayer** [triplea-game/triplea#1821]
Just downloaded this game for mac, and was really enjoying the Middle Earth Scenario when it froze on an enemy attack roll and wouldn't go on from there.  It's happened both with the Rhun invading South Dale and Mordor invading  Eastern Osgiliath, and I would love a work around/fix.

Edit: Looks like I'm having that problem with all maps actually.

**Comment by DanVanAtta** [comment]
Thanks for reporting. Do you have an autosave of the game by any chance? If so, could you post the file here? (first zip up the tripleaA tsvg save game  file, then you should be able to upload it here)

**Comment by RoiEXLab** [comment]
We need some more details to help you with this problem.
Which exact version are you using? I'm assuming you downloaded triplea from the [official download page](http://triplea-game.org/download/).
I barely ever touched a mac, so correct me if I'm wrong about something. By freezing you mean that no error pane is showing up, correct? It just stops working, eventually being closed by the os (on Windows the "xyz.exe stopped working" dialog would show up).
If so, please provide the exact steps until your game froze. If possible create and upload a savegame just before this happens so we can further investigate this problem.
I'm concerned that this could be a Mac-only problem, which would make it really hard for us to resolve it, since AFAIK nobody here owns a mac.

**Comment by RoiEXLab** [comment]
Oh @DanVanAtta, didn't notice you already sent a message ^^

**Comment by ron-murhammer** [comment]
@Arkslayer Can you provide some additional information as described above? Otherwise it is difficult for us to help diagnose the problem.
