### ISSUE TITLE
Drop the non-recent Map Creators?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1860]
Any reason not to drop all but the latest map creator? The latest, beta is AFAIK the latest, based on the C++ version. The map creators we would drop would be the ones linked in the map download list (under tools), and the 'main' map creator that is not marked as beta in the engine settings.

**Comment by panther2** [comment]
Please see #1722 

I think we still need both parts (Map Creator (part 1) + Map Creator Beta (part 2)) that are included in the Engine (Preferences).

![cb47a37e-3b42-11e7-8ccc-cd200d512590](https://user-images.githubusercontent.com/20812775/27005752-57a8713c-4e25-11e7-8319-78c3588ca0f6.PNG)

**Comment by ron-murhammer** [comment]
@DanVanAtta I think @ssoloff was evaluating all the map creators to determine the best path forward and if any of the older ones are still utilized or have value. But I think we do want to consolidate to one map creator tool if possible and then focus on improving that one.

**Comment by ssoloff** [comment]
To clarify, I was originally evaluating the need to be able to run the two standalone map creators from within TripleA in conjunction with the two in-game map creator tools (#1722).  If you read through that issue, what I think we've learned is

* There doesn't seem to be much use of the standalone map creators among the map maker community.
* As @panther2 pointed out above and in #1722, the features of the two in-game map creators do not overlap 100%.

My [last comment](https://github.com/triplea-game/triplea/issues/1722#issuecomment-305949161) in #1722 was a suggestion to go ahead and remove TripleA Map Creator (version 1 of the two standalone tools) from `triplea_maps.yaml`.  However, I defer to the map makers on the in-game tools and don't think we can completely remove the non-beta version until they are satisfied that the beta version has 100% feature parity.

**Comment by Cernelius** [comment]
I've never used any map creators beside what you get by clicking "Run the Map Creator" (which should be renamed "Run Map Making Utilities" as it is not a map creator, meaning single utility for creating a map from start to finish, with it).
I've never clicked before on this "[Beta] Run the Map Creator" but I see that what it does is asking you to "Load Game XML File"?
Anyways, of course, keep something like the current "Run the Map Creator", in which you can do the stuff one item at times separately. Not sure if you mean that there is something else somewhere around that does that too, or better.
What is supposed to be the substitute, if I like want to go re-run the placement of a map or redo the reliefTiles, etc., without having to select an XML File, like the "[Beta] Run the Map Creator" is asking me?

I've just tried the "[Beta] Run the Map Creator" there for the first time now (and I've never tried any of the mapcreators not part of the engine) and, from what I see, it looks like it is just like the other one, but all bundled up, to make your map from start to finish?
My judgment is limited by the fact that I've never actually used it, and just opened it now for the first time, but you surely want to have a way to jump directly to do the specific stuff, rather than having a single program for doing all in sequence.
I'm skimming the stuff of this "Beta" right now, and it looks to me that I surely don't like it. Like I'm in "Unit Placements" section and only thing I can do is clicking on the "Auto-Fill" button? I don't know if that button does anything, but I don't see anything happening when I click on it (does it do all and auto-overwrite without asking, or am I not seeing another button to do that?), also nothing happens when I click on the other button "Available Choices".
Maybe I'm missing something, but only looking at the "Unit Placements" I can't even understand if that works and how at all, and it looks like much more limited than the normal utilities, not even allowing you to manually pick the placements (am I overlooking?), and all the various modes??
For what little I'm looking at right now (sorry, never used this "Beta"), my suggestion is definitely to keep the "Run the Map Creator", and maybe rather delete the "Beta" one, instead, or cut it down handling the XML things only, renaming it accordingly. I've never used (nor I would want to use) any map creators for creating any XML, besides the utilities for like the connections etc., that I then paste manually into the xml.
Also having one utility for each thing is surely more practical than all in one, unless, maybe, you are doing a very simple map.

So, my partially informed suggestion is:

- Keep everything working and available just exactly like it is now (talking mostly out of ignorance of the "Beta" stuff here; I've looked at it now for the first time).

- Rename "Run the Map Creator" to "Run the Map Making Utilities"

- Keep "[Beta] Run the Map Creator" or rename it "Run the Map Creator", if you think it is over the beta stage.

Did anyone here made a full map using this "[Beta] Run the Map Creator"?

Sorry, but I'm mostly confused about this proposal, due to my limited knowledge, since I've simply never used anything else at all but what it is suggested here to be deleted / substituted (the utilities behind the current non beta "Run the Map Creator" button). What @veqryn thinks?

I think here we would need like three or four known experienced mapmakers who did at least a complex map each fully using all utilities of both one and the other, and can all agree and confirm the Beta makes the other one totally redundant (looking at it just now, I would say surely not, unless I'm overlooking a lot).

Anyways, whatever thing that gets removed from the main TripleA installation should be still available to get and use, I believe.

**Comment by Cernelius** [comment]
> There doesn't seem to be much use of the standalone map creators among the map maker community.

If you mean the various utilities that you get by clicking on "Engine Preferences/Run the Map Creator" (not the beta), I've actually never used anything else but that (besides, of course, a text editor (usually, notepad) and an image editor (usually, GIMP)).
So, I don't know how much I amount in the map maker community, but the regular "map creator" amounts to 100% of the use for me so far.

> As @panther2 pointed out above and in #1722, the features of the two in-game map creators do not overlap 100%.

As I said, I've never looked at the beta one before today, but either I'm overlooking a lot or that beta map creator is dramatically less useful than the not Beta one, on multiple levels.

> My last comment in #1722 was a suggestion to go ahead and remove TripleA Map Creator (version 1 of the two standalone tools) from triplea_maps.yaml.

So, practically, correct me if I'm wrong, you mean that this issue is partially a misunderstanding, and the matter that started it was not to remove the stuff in "Engine Preferences/Run the Map Creator" but what in "Download Maps/Tools/TripleA Map Creator", instead? Correct.
If so (?), I suggest closing this issue and restarting a new one, so to try to minimise misunderstandings.

If that is the only proposal, at the end (?), sorry but I don't believe I've ever used the "TripleA Map Creator" that I see in Download Maps/Tools, if you mean the one "By Wisconsin, SGB, and ComradeKev". I vaguely remember I might have downloaded it and briefly looked into it a long time ago, but I'm not sure.

Sorry, but I'm just not sure where the proposal of dropping the utilities inside "Engine Preferences/Run the Map Creator" exactly originates. If the matter is instead dropping either one or the other of the map creators inside Engine Preferences, to avoid duplication, as they are partially doing the same things, and focusing on one only, for what I see I almost surely suggest to **go ahead dropping the "Beta" one** (but I'm not a good reference here, since I've never used it), and focusing on the old one (not "Beta") only, as it seems clearly better, more extensive and more practical (surely much better having separate utilities than all in one, especially if they are also better). Maybe you can cut the "Beta" one down to an XML creator only, removing all the not XML stuff in it, and incorporate it as an utility in the other one.

**Comment by Cernelius** [comment]
For what I see (sorry, limited by not having ever used or even clicked on the "Beta" one before today, just evaluating it now for the first time), I'm guessing you can go for:

1. Rename "Run the Map Creator" to "**Run the Map Making Utilities**" and keeping that as the main collection of tools for advanced mapmaking, and especially reworking maps.

2. Rename "[Beta] Run the Map Creator" to "**Run the Basic Map Creator (Tutorial)**", and keep that as a simple introductory utility for making a simple / small maps from start to finish, as a sort of mapmaking tutorial (maybe with a tooltip telling to use this only to make a very simple / fast map in one go).

It looks surely confusing having 2 things named the same way, except one with a "Beta" tag beforehand, and I don't believe it makes sense, here (one might think that the "Beta" one is just the new version of the other one, which it isn't).

I cannot say anything about the one in Download Maps, since I'm not sure if I've ever even downloaded it.

**Comment by Cernelius** [comment]
> But I think we do want to consolidate to one map creator tool if possible and then focus on improving that one.

So to sum it up, my suggestion is to consolidate to the older not-Beta "Run the Map Creator" one only, as I can assure that already allows you to do whatever you need, and very well, except only lacking a full XML creator (that I personally would not want to have, as just taking like PoS2 and modifying it as you need works the best).
But my insight is limited by the fact that I've never used anything else but the not-Beta "Run the Map Creator" utilities, and I looked at the "Beta" one only now (because of this issue). Also, I'm not even sure if that is for making a map from zero, since it asks you to "Load Game XML File" and doesn't start at all if you don't have one already???

**Comment by ssoloff** [comment]
@Cernelius It looks like you figured out what the different map creators are in your previous comment, but let me enumerate them just to avoid any confusion for future readers of this thread:

ID | Name | Author | Description| Notes
-- | -- | -- | -- | --
1 | TripleA Map Creator version 1 | Wisconsin et al. | Standalone tool written in C# available from [Google Code](https://code.google.com/archive/p/tmapc/). | Screenshots available [here](https://github.com/triplea-game/triplea/issues/1722#issuecomment-302582242).<br><br>You can also download the tool in-game via **Download Maps > Tools > TripleA Map Creator**, but you must unzip and run it outside of TripleA.
2 | TripleA Map Creator version 2 | Wisconsin et al. | Standalone tool written in Java available from [Google Code](https://code.google.com/archive/p/tripleamapcreator/). | Screenshots available [here](https://github.com/triplea-game/triplea/issues/1722#issuecomment-302582242).
3 | Map Creator | TripleA team | In-game tool available from **Engine Preferences > Run the Map Creator**. |
4 | XML Map Creator | TripleA team | In-game tool available from **Engine Preferences > [Beta] Run the Map Creator**. |

**Comment by veqryn** [comment]
IMO: Ditch the ones made by Wisconsin and instead focus on the recent ones

**Comment by Cernelius** [comment]
Ok, right.

That is helpful.

Sorry, but, as I said, I've never used or even looked at anything but only the not-Beta utilities in the "Run the Map Creator" (that I understood this issue was discussing if to remove).

Thanks.

What I can say is that:

- I've never used 1, 2 or 4 for doing anything.

- Since I never needed any more or better tools than what 3 offers, I've looked at 4 only today, after reading this issue, and it seems dramatically inferior to 3 for the not xml stuff, but nothing works for me, and it seems just totally broken (I'm trying it by loading "world_at_war", since it refuses to start if you doesn't give an xml to load).

- Are you saying that the 4 is for making the XML of the map only (and nothing else) or are you saying that it is for making all the map comprising the XML (thus XML plus original skin)? Sorry, but I'm trying it out now and it seems just totally broken to me; nothing appears to work, so I can't even figure out what is supposed to do.

I think I misunderstood the thing like "Unit Placements" of this beta thing as it was doing the actual place.txt, while I see now that must be for making the XML unitInitialize, instead, right (doesn't work for me)? Actually, I don't believe it works for me, or at least I can't figure out. I click on all the stuff and nothing seems to happen in any case. Also I can't understand how is that a "XML Creator" if it asks you to have an XML and doesn't start if you don't have already one??? Is that just an "XML Modificator"?

---

So, @ssoloff 
Since this is this issue:

> Any reason not to drop all but the latest map creator? The latest, beta is AFAIK the latest, based on the C++ version. The map creators we would drop would be the ones linked in the map download list (under tools), and the 'main' map creator that is not marked as beta in the engine settings.

Can you re-elaborate this matter from your own point of view, in detail, so that it might be clearer to me too?

**Comment by Cernelius** [comment]
> IMO: Ditch the ones made by Wisconsin and instead focus on the recent ones

If you ditch everything else but the (number 3 in list) in-game tool available from _Engine Preferences > Run the Map Creator_ (not the "Beta" one), nothing changes for me, as I've never used anything else but that.

**Comment by ssoloff** [comment]
@Cernelius 

> Are you saying that the 4 is for making the XML of the map only (and nothing else) or are you saying that it is for making all the map comprising the XML (thus XML plus original skin)?

Sorry, I've never done much with the map creation tools other than fix bugs.  Without spending some time looking at the code, I couldn't begin to tell you what (4)'s purpose is. :smile:

> Can you re-elaborate this matter from your own point of view, in detail, so that it might be clearer to me too?

I was just chiming in that we should no longer support (1) and (2), and specifically remove (1) from the Download Maps list.  As I said previously, I think the map makers should decide the fate of (3) and (4).  My _feeling_ from reading other posts is that (3) is still used frequently, and (4) _may_ offer some additional features that map makers _might_ find useful if they knew about them (please don't ask me to explain that as it will involve a lot of hand waving :smile:).

**Comment by Cernelius** [comment]
Ok thanks. So basically now we have to wait either for someone that ever used 4 to make a full map or that I manage to actually use / understand it (I probably won't, since it seems just broken, and I don't need it, and I'm already getting annoyed trying to figure it out).

@ssoloff , since it is just not appearing to do anything for me, it would be still good if you can maybe confirm that 4 is for making the XML only, and nothing else, as it looks like, but I can't be sure. If you call it "Run the Map Creator" one would imagine that thing is able to make a full map from zero, not just the xml only, or maybe just modifying it (as it seems it doesn't start at all if you don't give an xml already). Once that is confirmed, the name should really be changed to something like "Run the XML Modifier".

So, to sum it up (sorry for the many posts; I'm just confused):

If the proposal is dropping 1, 2 and 3 in list, and keeping 4 only, I rather suggest dropping 1, 2 and 4 in list, and keeping 3 only, or at least surely not dropping 3. I cannot judge over 4, since I've never used it before, and, now that I'm trying it, either I can't figure or it is just totally broken, and I'm not even sure if that is for XML only, or maybe XML plus map.properties only?

If the matter comes from partial misunderstandings in other issues etc., my suggestion, at this point, would be restarting a new issue based on the tab posted by @ssoloff , possibly exactly clarifying what each of those is specifically meant to do, if not the whole map (all skin plus all xml).

Sorry, I've never even used 1 and 2 (or don't remember) and don't really feel like trying them out right now, especially after the current experience with 4... Hopefully someone else that uses / used them might give some info. Just dropping a @FrostionAAA here, in case.

Only thing I can say, especially after briefly looking at 4 (the Beta) for the the first time: **don't drop number 3: In-game tool available from Engine Preferences > Run the Map Creator.** (should really be renamed to "Run the Map Making Utilities", tho)

**Comment by Cernelius** [comment]
This is what I see if I run the "Beta" Map Creator with world_at_war (it doesn't work if I don't give it an XML already), and nothing appears to work but maybe partially. If the condition is the same for other users, I suggest renaming it to "Alfa":

![20170612_beta_map_creator](https://user-images.githubusercontent.com/19562310/27018207-c87230ec-4f2e-11e7-813d-d043f022cb9e.png)


Sorry, I've never tried this Beta before today.

**Comment by FrostionAAA** [comment]
@All
I have used 1, 2 and 3 many times. Never used the Beta one. I also have Iron War Europe in the making, and for this map I only have the graphics ready, so I need to build up the rest. I could give the Beta map creator a try and write down my experiences and critic as I progress through the map making process.

I think I already share some of Cernels impressions concerning the Beta map creator. The non beta tools are filling most of my needs and I have pressed the button of the Beta map creator before, but gotten confused by the load XML thing. Maybe a bit scared about this beta creator tools messing up any XML file I had already, so I just closed the creator again.

Maybe within a week or two I can start testing the Beta map creator (when creating the Iron War Europe) and post what I experience.

**Comment by panther2** [comment]
@ALL
This is how No. 4 works:

Loading an XML-file already completed:

![b1](https://user-images.githubusercontent.com/20812775/27022989-e09a32d8-4f50-11e7-8fa0-446de92e2d4a.PNG)

Loading an empty XML-file:

![b2](https://user-images.githubusercontent.com/20812775/27022998-ed8f02fc-4f50-11e7-9977-7d9e36a67c95.PNG)

Note, that "empty" means an XML-file containing at least this code:

![b3](https://user-images.githubusercontent.com/20812775/27023023-035df430-4f51-11e7-8296-47f19785e84f.PNG)

I am not sure if No. 4 works perfectly and covers everything but it appears to be a very helpful tool to either modify existing XML-files or create a new one "from scratch" for people without deeper knowledge of greating/modifying game.xml files using ediors.

**Comment by Cernelius** [comment]
So, @panther2 , can you confirm that the so-called "Beta Map Creator" is about absolutely nothing else but the XML? Thus it can / should be renamed "**XML Creator / Modifier**"?

Also, it is so strange that it requires you to prepare a minimal XML to start with, instead of getting around doing it itself. Anyways, this doesn't strictly make it even an XML creator, but a modifier.

I've never tried anything that changes XML, as I prefer just rewriting it myself with notepad, starting from POS2 or else.

**Comment by panther2** [comment]
@Cernelius 

> can you confirm that the so-called "Beta Map Creator" is about absolutely nothing else but the XML? Thus it can / should be renamed "XML Creator / Modifier"?

Indeed. Just look at the (screenshot) window title above: There it says **TripleA Map XML Creator**

> Also, it is so strange that it requires you to prepare a minimal XML to start with, instead of getting around doing it itself. Anyways, this doesn't strictly make it even an XML creator, but a modifier.

Maybe this is one of the reasons why it is called "Beta".

**Comment by Cernelius** [comment]
That is really not that clear, since it may either mean "Map Creator comprising XML" or "XML Creator for Maps". I would actually guess the first, since I go there by clicking on a button called "[Beta] Run the Map Creator", and this is clearly what @DanVanAtta understood too (or he would have never suggested what at this Issue, in particular not dropping the not-beta map creator, since we have clarified that the beta one is about doing the XML only).

So, before anything else, I strongly suggest to push the following names changes:

"Run the Map Creator"->"**Run the Main Map Making Utilities**"
"[Beta] Run the Map Creator"->"**[Beta] Run the XML Creator**"
"TripleA Map XML Creator"->"**TripleA XML Creator**"

This should cut down starting confusions for future discussions like this one, as it seems it will be still a long way to go. I can only say that I surely believe that stand-alone utilities, for each different thing, like in the current not-beta "Map Creator" are better suited to advanced mapmaking than a single map creator, doing all from start to finish.

**Comment by panther2** [comment]
After that I would vote for keeping (and - if possibe - further improving) the built in "(Main) Map Making Utilities" and the "XML Creator".

**Comment by FrostionAAA** [comment]
I have not had time to test/use the Beta map creator, but I still plan too, at some point. Hope someone else is also up for the testing and evaluation.
(Map making tools and programs should not be under-prioritized :-D )

**Comment by FrostionAAA** [comment]
OK, I have tested number 4, the (Beta) Map Creator. I have made this report over my first impressions and what I experienced along the way:
[BetaMapCreatorTesting.docx](https://github.com/triplea-game/triplea/files/1099902/BetaMapCreatorTesting.docx)

My final thoughts are (not included in report), that if number 4 (Beta XML creator) is to be made into a Map Creator that could be a leading all-in-one tool for map making, there is surly a long way to go. Not impossible, as I can easily imaging this number 4 working better and integrating some of the smaller tools of number 3 (Non-beta tools) map creator.

But IMHO the very best thing that could happen from a map creator’s point of view is a revitalization of Wisconsins TripleA Map Creator version 2. This is/was a very user friendly and simple to use tool with a lot of features. It is totally outdated, but I really hope some developers are able to bring it up to date. From my untrained eyes point of view, this map creator would require much less new development compared to merging the features of 3 and 4.

If this wish is totally unrealistic for some reason, merging 3 and 4 would still be a very welcome project =)

**Comment by Cernelius** [comment]
In my opinion only, this matter can actually have low priority, as the current (non beta) mapmaking tools are very good and with them only, plus manual editing of xml, starting from like pos2, you can pretty much do whatever you want very well, already (like, you can do a map like Total World War, that way, aside from the graphic skills). The delays of doing the xml stuff manually are like nothing, compared to what it takes to make a map.

On top of that, I actually use the  in-game Edit and, then, "Export game.xml File", to populate the xml.
For example, you load up the game, edit all the units as you want, export the xml and copy-paste the unitinitialize into your actual xml. That works very fine, and it is already about as good as I can imagine (I would not want an automated utility to mess with my main xml anyways!).

But, while I believe currently everthing is already handled very well as it is, if I have to look at the matter from the point of a perfectionist or to be friendly to new mapmarkers, I would think that the best would be having a single utility supporting at the same time:
1) Making a map from nothing from start to finish, maybe even integrating a basic graphic program for drawing the stuff, like the baseTiles.
2) Being able to freely pick the single utilities, to use them, without the need of loading or having or making a whole map, nor of loading the whole map creator (this would apply also for making specific parts of the xml, like the territory definitions, to be manually copy-pasted, without having to load or create or directly modify the entire xml).

Something like having a map making tool that you can open and use it to make a map or select a specific part to, for example, produce your "place.txt" only, without having to load the whole map, or ever having a finished map at all, to do it.

Basically, number 2 is already supported by the non-beta map creator, and I don't think that number 1 is important (but I guess it would be neat and would cut down some learning time for new mapmakers).

I still suggest the renamings:
"Run the Map Creator"->"**Run the Main Map Making Utilities**"
"[Beta] Run the Map Creator"->"**[Alfa] Run the XML Creator**"
"TripleA Map XML Creator"->"**TripleA XML Creator**"

(note that the not-beta map creator is also about the XML; for example, you use it to create the connections and territory definitions, that you, then, paste inside your XML (which works fine and I personally prefer over something that directly modifies your XML))

I'm not sure if it should be "Alfa" or "Beta", especially since I superficially tested it. @FrostionAAA would you say "Alfa" or "Beta", based on your testing; I'm guessing "Alfa", reading it.

https://en.wikipedia.org/wiki/Software_release_life_cycle
> Beta phase generally begins when the software is feature complete but likely to contain a number of known or unknown bugs.

**Comment by FrostionAAA** [comment]
I would say that the “Beta map creator” is not a very usable program. An “Alfa”-stage name would be more fitting. I am just about to make Iron War Europe, and I can’t see myself using the "Beta" map creator at all.

Maybe the most realistic and doable project, in regards to creating a good tool for easier and more user friendly map making, is a merging of the already working tools of the non-beta map creator and the interface and its step-by-step procedure of the beta map creator (XML-creator/editor). I agree with Cernel that that any work related to placing units, setting relations etc. is easiest done ingame via edit mode. Maybe the in game edit and XML export features could somehow be expanded to also include territory production, territory effects etc. and be altered to actually also be a part of the map making tools/process? Maybe these features could be integrated as map-making tools that could open up a map via the engine and let the map maker edit and save xml?

In the report I posted, I have expressed my ideas about clickable website or forum links in any future map making tools, links that could guide and instruct mapmakers on how to handle the map making process. A good thing about such links and detailed instructions that compliment the tools, would be that they could be constantly worked by and improved by users and not really need to involve the devs who probably want to use their time working on the actual programming.

@Cernel do agree with some of these ideas and views? Maybe we should make a “template” of what we envision in regards to a new and better “Map Making Tool”, like a description og this tool's steps, menus, functionalities etc. Hopefully this could be a tool that replaced the current tools, but also was an evolved version of the (beta) XML creator that made use of the fine and already functioning non-beta tools? Maybe we could make a Google doc for this work or work on it at the forum?

**Comment by Cernelius** [comment]
As I said, in my opinion, the tools are already very good as they are.
Also, I believe the documentation allows understanding all that it is needed fairly well, especially the "Map and Map Skin Making Overview".
On the actual mapmakers (the two "Wisconsin et al."), I can say nothing, as I've never used them, or don't recall.
If anyone wants to develop a more integrated way of mapmaking, I guess that can be good (I don't see it as a priority, as I said), even tho I can't see myself doing a map from start to finish with a single "map creator" tool, nor I would feel confortable with any tool that load and resave my map as a whole.
My main concern was to not do what proposed at the start of this issue and in particular (one way or the other), if a true reliable actual map creator will ever exist, always leaving available single-step tools, like the ones you currently have in the not-beta "Run the Map Creator" (not really a map creator, but a collection of map making tools).
I was just mostly worried about any changes, as I find the current tools and info satisfactory as they are, tho my suggestion would be adding all main ones back inside the main installation (in a "doc" folder, like in 1.8.0.9) but I don't think this is that needed, either, as I see you can reach them quite easily clicking on "Help" and, then, on "Map Maker and Developer Documentation".
However, I see that if I click on "Map Making" here:
http://www.triplea-game.org/dev_docs/maps/
It sends me to a broken link:
http://www.triplea-game.org/dev_docs/maps/map_making/
Anyways, I believe that reading the docs listed as "Older (legacy) Documentation" allow to understand and use the available tools very well.

**Comment by DanVanAtta** [comment]
I think we reached some consensus on this, and some very good work here researching the map creators.

We removed the new 'beta' map creator and so are now down to just the one. We are clearly going to be keeping that. I believe that resolves this thread.

**Comment by Venryx** [comment]
Hey there! I'm the one who made the two very old map creators, and just wanted to add some info that might be helpful.

1) The non-beta map tools from the TripleA menu are, as you determined, helpful shortcuts to the packaged individual tools. Definitely keep this as it's easier to access than the old command-prompt approach. (something like "java -jar triplea.jar --classpath games.triplea.tools.placement-tool")

2) The "beta" map creator appears to (have been) a cut down version of the v2 Java map creator I created. Some things were changed, but the messages and UI choices I definitely made (some of them ill-conceived, such as the "auto fill" button, which is too much of a black box and so non-useful).

As mentioned:
> Also, it is so strange that it requires you to prepare a minimal XML to start with, instead of getting around doing it itself. Anyways, this doesn't strictly make it even an XML creator, but a modifier.

Yeah, I agree that is kind of strange. In my original program, it had a main menu where you can choose to either create a new map, or edit an existing one. Apparently, the person who merged it into the TripleA project has it auto-start into "load map" mode instead of giving the options.

As for the removal of the beta XML creator, I'm not sure that's the best idea. It definitely has some bugs, and so should have warnings (eg. labeled alpha) and fail-safes (eg. auto-saving to backups like in the main game), but I do think long-term it is helpful for new map builders to have a UI approach they can start with, as it helps to ensure they don't get snagged up on syntax errors or not knowing all the different components and options available/required. This is one of the strengths of user-interfaces over plain text: it keeps you from making certain mistakes, and can show you the various options you have available at each stage.

At the very least, I think there should be a panel added describing the various phases of map development -- perhaps a link to the TripleA wiki on map creation could be a start.

If I had more time, I would love to come back and fix the map creation tools up to where they are actually helpful and do not constrain the creation process; but I have some other projects that are higher priority right now, so can only chime in with some thoughts.

> I agree with Cernel that that any work related to placing units, setting relations etc. is easiest done ingame via edit mode. Maybe the in game edit and XML export features could somehow be expanded to also include territory production, territory effects etc. and be altered to actually also be a part of the map making tools/process? Maybe these features could be integrated as map-making tools that could open up a map via the engine and let the map maker edit and save xml?

That would be ideal, if the tools could harness the display and control abilities already present in the main game. The main problem there is that there are a number of components which the main game just has no code to handle at the moment (for example, the territory connections and gameplay sequence), and it would take some thought to integrate those additional components in nicely, without bloating the main code-paths with systems only used during map creation.

Definitely possible, but it's actually somewhat more work than just creating a new (basic) editor from scratch, because you have to work within the existing infrastructure. (and the TripleA code-base overuses interfaces and constrainment of data access, in my opinion) Some people don't mind this development constraint, but to me it's somewhat suffocating -- which is one of the main reasons I didn't take this route in the first place. The end result would probably be nicer/more future-proof, though. (since it piggy-backs off the main engine code in the areas where it can)

So anyway, whether the XML creator/editor is brought back, we add new tools to allow edit-mode changing of a wider range of XML content, or we simply add a panel/button linking to a Wiki page guide (with mention of a buggy-on-some-computers UI option perhaps), I think any of those three options are better than leaving players hanging a bit as they are now.

**Comment by panther2** [comment]
Just a +1 for adding back the (improved) XML-creator one day.

As I said above:

> ... but it appears to be a very helpful tool to either modify existing XML-files or create a new one "from scratch" for people without deeper knowledge of creating/modifying game.xml files using editors.
