### ISSUE TITLE
Right Click Not Working Deselecting Units in Current Master

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#1888]
If you click on a unit then right click to deselect it then it instead moves the unit just like left click.

@RoiEXLab I'm guessing this has to do with PR #1883. Can you please take a look.

**Comment by Cernelius** [comment]
Ah, on this regard, there are two limits of this feature of right clicking to deselect also in stable:
1) When you are over another unit, right click to deselect doesn't work.
2) When you are not on a territory (none), right click to deselect doesn't work.

This is especially annoying (but nothing major) on maps like WAW, in which you may happen to have the pointer in the "none" borders in between of the territories or over some of the many units, and, if so, right click won't deselect the units.
You can easily test it in WAW by selecting an infantry in Berlin and moving the cursor so to highlight another unit in Berlin or moving it over any "none" spots, like the Berlin territory borders (the empty part of the map like in between of Berlin and Brandenburg, or any of the fake sea zones (mainly the lakes)), and, in both cases, nothing happens, when you right click. This practically means that in a situation like Berlin WAW the right click to deselect works only in the minor portion of that territory in which you are not over units.

This applies (and it is problematic the most, as most users I believe won't realise the matter) also to units that can't be highlighted, normally the ones unable to move (for example, in WAW, select the infantry in Berlin and move the cursor over the factory in Berlin: you won't be able to deselect it, by right clicking), making this feature particularly annoying to use on maps having invisible units (usually, invisible factories, like in Dominations and others), where you can just happen to spam the right click button and not understanding why it is not working.

On top of the above, I suggest to allow for using the right click to deselect also in case of minimal movements; for example, if I only move of a couple of pixels while I'm right clicking, this likely means that I didn't want to move the board of 2 pixels, but just happened to move my mouse a bit while right clicking, and I believe would be nicer if it still deselects. Thus I suggest (instead of the current not-deselecting upon right click if you move of any while having the button pressed) to disallow deselection by right click only if you move the mouse of 4 pixels or more between the pressure and the release of the right click button (instead of current 1 pixel or more).

**Comment by RoiEXLab** [comment]
@ron-murhammer Your assumption was correct, although I still don't get why this even got introduced (See the PR diff)
#1891 has a fix!

**Comment by ssoloff** [comment]
@RoiEXLab I tested your fix, and it works.  Just curious, though...  Did `SwingUtilities#isRightMouseButton()` not work for you?  When I add the following to `MouseDetails#isRightButton()`:

```java
final boolean swingValue = SwingUtilities.isRightMouseButton(m_mouseEvent);
final boolean ourValue = (m_mouseEvent.getModifiersEx() & InputEvent.BUTTON3_DOWN_MASK) != 0;
final boolean prValue =  (m_mouseEvent.getModifiersEx() & InputEvent.META_DOWN_MASK) == InputEvent.META_DOWN_MASK;
System.out.println("ourValue = " + ourValue + ", prValue = " + prValue + ", swingValue = " + swingValue);
```

and click the right mouse button, I see the following trace:

```
ourValue = false, prValue = true, swingValue = true
```

The OpenJDK 8 implementation of `SwingUtilities#isRightMouseButton()` is:

```java
public static boolean isRightMouseButton(MouseEvent anEvent) {
    return ((anEvent.getModifiersEx() & InputEvent.BUTTON3_DOWN_MASK) != 0 ||
            anEvent.getButton() == MouseEvent.BUTTON3);
}
```

Is this not reliable for some reason?

**Comment by RoiEXLab** [comment]
@ssoloff It works perfectly! I opened #1894 to change this!
