### ISSUE TITLE
Logger.info opens Console

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#1950]
In some parts of the code `Logger.info` is being called to log a specific event in the console, like [here](https://github.com/triplea-game/triplea/blob/297f180c800fd80faf0620f3aad9a4c10012d9bf/src/main/java/games/strategy/engine/chat/ChatController.java#L109).
But although it's logging level is "INFO" and not ERROR or WARNING, the console is still being opened, as if an error is being thrown.
How should we "fix" this problem? Change the logger?

**Comment by ssoloff** [comment]
When I look at my Eclipse console, that message is colored red, which means it came from `stderr`.  (My understanding is that the TripleA console is displayed whenever something is written to `stderr` but not `stdout`.)

So, for some reason, this particular `Logger` instance is sending its output to `stderr` instead of `stdout`.  We probably need to hunt around and see if we can find some code that is playing around with the configuration of this logger or one of its ancestors.

**Comment by ssoloff** [comment]
My bad...  I was under the impression all other `Logger`s sent their output to `stdout` and this one `Logger` was the exception.  But it looks like the default `ConsoleHandler` that the loggers inherit from the root `Logger` sends everything to `stderr` by default.

What is the requirement here?  Should `Logger` output always go to `stdout`?  Or should levels above a certain threshold go to `stderr` and those lower go to `stdout`?

Depending on the above, there are a few possibilities:

* Configure a custom `ConsoleHandler` that simply sends all output to `stdout`.
* Write a custom `Handler` that sends some output to `stderr` and the rest to `stdout`.
* Don't mess with the `Handler` but change the configuration so that INFO logs are turned off by default.  That way only ERROR and WARNING logs will cause the TripleA console to pop up.  Devs can turn on finer log levels if they want with the understanding those will cause the TripleA console to pop up because the logs are being sent to `stderr`.

**Comment by RoiEXLab** [comment]
@ssoloff I figured this as well, IMO only error (and more severe levels) levels should be printed on stderr

**Comment by ron-murhammer** [comment]
@RoiEXLab @sbridges While in theory I agree "INFO" probably shouldn't open the console, there are definitely messages being logged at the level "INFO" that are essentially errors. Logging in general needs an overhaul across the code base and have clear standards on how it should be used.

**Comment by ssoloff** [comment]
@RoiEXLab If you're satisfied with the solution in #2289, I believe this issue can be closed.

**Comment by RoiEXLab** [comment]
I am.

**Comment by DanVanAtta** [comment]
2 cents, it looks like the intent was for logging to be done via 'system.out' and 'system.err', and no formal logging framework was used. The intent then appears that info messages go to 'system.out' which are appended to the console, but it does not open the console if it is closed. 'system.err' on the other hand was to open the console (note the title is "An error occurred").

The log util objects I think were later added, but it's not very consistent. I added `ClientLogger` to try and wrap any logging done from the Client app. The intent was to at least consolidate the logging handling to the one location. The other confusion is that we have server code which does use java.util.log, and since some of it is shared it can be a bit odd to think of the different contexts for shared code paths.
