### ISSUE TITLE
AI vs AI automated testing

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2140]
What I'm thinking is something like this, we set up an AI vs AI client/server match via command line and have it play 5 rounds on a various set of maps. 

I'm wondering if others would brainstorm and potentially help with this idea. A first question I have, should we send results like error counts to a dashboard, something like an html table stored on github.io, or should we fail the build if we see errors?

**Comment by ssoloff** [comment]
Sounds like a great idea.

> A first question I have, should we send results like error counts to a dashboard, something like an html table stored on github.io, or should we fail the build if we see errors?

I like the idea of running these tests automatically on Travis but not necessarily with the main build simply because it will increase the build time tremendously.  We should investigate using Travis build stages or a separate build so these types of tests can run out-of-band from the main build.  Then just piggyback on the existing Travis failure notifications to let us know when there's a problem.

> I'm wondering if others would brainstorm and potentially help with this idea.

How about starting with the simplest thing that provides value?  I'm thinking along the lines of a script devs could run locally for now that automates the AI vs AI tests.  That script could become the starting point for whatever we decide to automate on Travis in the future.

The script would accept two arguments: the versions of the client and server to test (which may be the same).  I tried working through this manually to see what is currently possible.  I came up with the following actions I believe the script would have to run.  Please correct any misunderstanding I have of how these aspects of TripleA work.

* Download and install TripleA.
    * Download `server` zip archive for _server_ version and unpack to appropriate location.  This is referred to as "bot" below.
    * Download installer for _server_ version and install to appropriate location.  This is referred to as "client-S" below.
    * Download installer for _client_ version and install to appropriate location.  This is referred to as "client-C" below.
* For each map to test (previously downloaded to the default TripleA maps folder):
    * Start bot and wait for it to be ready to accept connections.
        * _This looks like it's possible by scanning the bot log, but something cleaner might be better._
    * Start client-S, have it connect to bot, select all even players, and configure those players as AI.
        * _Might have to add new properties to do this headlessly.  Maybe even a new `HeadlessClient` entry point?_
        * _It doesn't seem possible to configure a network client to use AI players.  Is there a secret to doing this?_
    * Start client-C, have it connect to bot, select all odd players, and configure those players as AI.
        * _Same issues as for client-S._
        * Bot will automatically start game once all players have been configured.
    * Wait for client-S and client-C to play through N rounds and shut down.
        * Forcibly terminate processes if timeout exceeded (in the future, we can introduce some kind of heartbeat that indicates the AI is still playing and isn't hung due to an error).
        * _Might need a property to automatically and gracefully shut down an AI node after N rounds._
    * Shut down bot.
        * _Looks like sending TERM will gracefully shut down the headless server._
    * Scan bot, client-S, and client-C stdout/stderr looking for error/severe messages and stack traces.
        * Store test pass/fail result for later use.
        * Save stdout/stderr in a different location if the test failed.
        * Possibly save autosaves in a different location if the test failed in order to help debug any failures.
* Exit script with non-zero code if any test failed.

The only question I have is will the use of a bot hide certain types of compatibility problems?  I haven't really worked with bots much.  I'm assuming they are really just relays for RMI messages, and that client-S above runs through the same code paths as if it had hosted a network game itself and client-C connected to it directly?

**Comment by DanVanAtta** [comment]
Bots being a headless server seem best to me as a starting point. What we may be missing is a 'headless' client.

We might be able to skip install by relying on the 'old jar' mechanism and using command line args to select the version to run.  For consideration is if we would want to design two different tests. One, to check different versions, and gear that specifcially to look for compatibility between versions. Putting that test in travis only with a single flag to enable/disable it I think would be good. When we break compatibility, we would be able to turn off or verify that the test is failing. Second, a same version client vs a same version client with a bot, the idea here being to focus on other game regressions. I can see reason though to focus on the cross version check since we get overlap with the same version test, though I wonder how we handle when we start working on a non-backwards compatible version.

**Comment by DanVanAtta** [comment]
Closing for now, an interesting discussion. This likely could be a good Project for TripleA, though I think we may be best tackling this later as part of bot / server rework. In the meantime not sure if it's valuable tracking this without an active project..
