### ISSUE TITLE
Save Game Backwards Compatibility Broken

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#2206]
If you load a save game before this change #2137.

Then you get this exception:
java.lang.NoClassDefFoundError: games/strategy/triplea/oddsCalculator/ta/BattleResults (wrong name: games/strategy/triplea/oddscalculator/ta/BattleResults)

Do to the rename of the package oddsCalculator -> oddscalculator.

**Comment by ssoloff** [comment]
@ron-murhammer When I create a [save game](https://github.com/triplea-game/triplea/files/1220018/issue-2206-save-game.zip) in 3635 to reproduce this issue, I'm seeing `java.io.StreamCorruptedException: unexpected end of block data` instead of `NoClassDefFoundError` when loading from `master`.  There's no question the root cause is due to the package rename, as I verified reverting the package name allows me to load the above save successfully.

However, I'm curious why I don't get a `NoClassDefFoundError`, which seems to be the more reasonable exception to expect.  Do you mind attaching your save game so I can try to determine what causes the difference in behavior?

**Comment by ron-murhammer** [comment]
Save game: 
[triplea_40005_Tha6.zip](https://github.com/triplea-game/triplea/files/1220117/triplea_40005_Tha6.zip)

**Comment by simon33-2** [comment]
I'm confused. Why don't we just change the name back? Isn't the old name correct under the naming convention anyway. I must have missed something.

JavaFX seems to have broken the build for me. Been a while since I've contributed.

**Comment by ssoloff** [comment]
@ron-murhammer Weird, I get the same `StreamCorruptedException` when I attempt to load your save game.  We're either running TripleA at different revs or using different versions of JDK 8 (I'm still on update 131).  Oh well. ¯\\\_(ツ)\_/¯

**Comment by ssoloff** [comment]
@simon33-2 

> Isn't the old name correct under the naming convention anyway.

The Checkstyle PackageName rule wants package names all lower case with no underscores, so, technically, `oddsCalculator` does violate our naming conventions.

> JavaFX seems to have broken the build for me

The same thing happened to me because I was using OpenJDK, which does not include JavaFX.  I had all sorts of issues trying to get OpenJFX working on my Linux distro, so I just punted and switched to Oracle JDK.  I don't know if that's the problem you're having, but it's easily checked.

**Comment by simon33-2** [comment]
There's a log of packages which would violate that lowercase rule. Not sure why we would add such a requirement. The application wasn't written to it.

Either way, such a change requires a major (incompatible) release. The compatible release is taking too long for my money.
