### ISSUE TITLE
6157 - WaW - sub in combat can still move, but unable to move it

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2224]
Sub starts in sz36 (off of Liberia), it can move to attack either the transport or cruiser further north. If you move the sub first to sz34 to attack the transport, you can no longer move the sub to sz31, which is a valid move.

Note, this move is allowed:
![move_allowed](https://user-images.githubusercontent.com/12397753/29331804-976d42d2-81b2-11e7-84f7-e2e62b1fd3a4.png)

But after moving sub once, it is no longer allowed even though still legal:
![not_allowed](https://user-images.githubusercontent.com/12397753/29331877-d3bdcbd0-81b2-11e7-803f-78ee7106d4d6.png)

Save game at this location:  [sub_move.zip](https://github.com/triplea-game/triplea/files/1226087/sub_move.zip)

**Comment by panther2** [comment]
Just for my understanding, as I don't know the map: On this special map special rules apply that allow the sub to as well engage the transport as move on and engage the cruiser, too? So there is a sort of "combat while moving"?

**Comment by DanVanAtta** [comment]
On WaW - my understanding is sub movement is only blocked by destroyers. If the transport were a destroyer, then the move to attack the cruiser would always be illegal. In the above, it should not matter if yo move first to attack transport, the move to attack the cruiser is legal if the sub is in either sz36 or sz31, it should always be able to move to along that same path to attack the cruiser.

**Comment by panther2** [comment]
I cannot comment on WaW. But in newer A&A-games the sub may choose to either ignore the transport and move on to engage the cruiser or to engage the transport. In case the sub chooses to engage the transport movement is done in the SZ containing the transport because combat results. No way the sub can attack both ships during one move. But maybe it's different in WaW, that's why I asked.

**Comment by DanVanAtta** [comment]
> sub may choose to either ignore the transport and move on to engage the cruiser or to engage the transport

yes, if the sub moves once it would attack the transport (it will be given a dialog to confirm whether an attack is desired), or it can move again to attack the cruiser, and again will be given a final confirmation dialog before combat phase begins. Most maps have these same sub rules, should work similar.

> No way the sub can attack both ships during one move.

That should not be implied, or at least I did not intend to imply it. If yo move the sub one SZ, then you attack one boat, if you move it another then you are ignoring the transport and attacking the other boat. 

------------------------------

Let me see if I can summarize the problem a bit better:
- the sub at the start of the turn can move to attack the cruisier
- if the sub moves to the transport, it still has 1 movement, the move to the cruiser should still be valid

**Comment by panther2** [comment]
Now I have understood the issue. It was your sentence 

> If you move the sub first to sz34 to attack the transport, you can no longer move the sub to sz31, which is a valid move.

that irritated me, because "to attack the transport" implied, well, an attack.

You are perfectly right: If the sub enters the transport's seazone it should be able to move on to the cruiser's seazone (ignoring the transport).

**Comment by Cernelius** [comment]
I really wonder if this should be a bug or usability. If this is a bug, then we have a bunch of similar "bugs", in that you can do a thing a way but not another (in this case, you can do what you want, just have to do it in one move except than in two moves). I'd say this is "usability", but not up to me.

I would say it may be actually good that the engine forces you to make the move in 1 step only, not 2, as this is what the true move is, and keeps history cleaner (won't look like you have moved to attack that transport, at some point).

Also, if the path of the submarine is blocked by a canal, but you have another path, then, because of this "limit" or "bug" or whatever, you are obliged to use Ctrl to do the move at all, because the engine doesn't search for alternative routes when the first one is blocked by a canal (most people don't know about Ctrl the path, so they just edit the sub, in this case).
So, this issue may be something that makes you unable to do the move without setting the path with Ctrl, in case of any canal blocking the default autoselected path amongst multiple possible ones.

**Comment by DanVanAtta** [comment]
> I would say it may be actually good that the engine forces you to make the move in 1 step only, not 2, as this is what the true move is, and keeps history cleaner (won't look like you have moved to attack that transport, at some point).

You have a point, though it seems like a superficial benefit. If someone were moving large armies, shift clicking is a convenient way to do that, some units would not move that could otherwise move.

> Also, if the path of the submarine is blocked by a canal, but you have another path, then, because of this "limit" or "bug" or whatever,

This seems like a very different problem. The above is triggered not by the path being obstructed, but by the unit in combat. The logic for deciding when to move based on combat condition is complex and very conditional, it's very easy for such a condition to not be considered correctly. 

> So, this issue may be something that makes you unable to do the move without setting the path with Ctrl, in case of any canal blocking the default autoselected path amongst multiple possible ones.

Ctrl does not play a role in this problem.

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah, this has to do with how move validation rules are written currently. As @Cernelius mentioned there are a lot of small issues if you try to make multiple moves. I think this is a pretty rarely hit limitation and my guess is playing around with this movement validation logic would be fairly painful.

**Comment by Cernelius** [comment]
Maybe I've not been very clear, so I will explain better what I was saying.
In this case, Ctrl is pointless.

However, you can have a similar case in which:
You can go from A to D passing either trough B or C (all sea zones).
The default path is (for no particular reasons) A-B-D.
There is a canal, blocking A-B or B-D moves (doesn't matter one or the other).
There is a blocker in C that, as per this issue, you can go over in 1 move, but not in 2 moves.

In the above situation, you cannot go A-B-D, because of the canal, but you can go A-C-D. Still, the autoselect path obliges you to go via A-B-D, telling you that you can't, because of the canal. However, because of the blocker in C, you can't move in C then in D, but the only way to do the move is by Ctrl the A-C-D path in one move.

This was simply an example that shows you a case in which the limit at this issue (not being able to make the move in two steps) has the effect to make the move possible at all only by using "Ctrl".

**Comment by DanVanAtta** [comment]
Perhaps of some interest, it seems this case is almost the opposite. To attack the cruiser in the above, it must be done as one move. My impression is you describe a case where the auto route is bad, but you can still make the move by selecting the correct way points. In this case, the route A-B-C is valid, but if you make the A-B move first then suddenly B-C is no longer allowed. Seems like the move logic is missing this consideration.

**Comment by Cernelius** [comment]
No. The moves are A-B-D or A-C-D. There is no A-B-C.
Wait a second, I'll picture it in WAW.

**Comment by Cernelius** [comment]
No picture.

There is actually a simpler example: having the A-C option blocked by a canal and the A-B-C option "blocked" by a unit.

Example:
You have a submarine in 52 Sea Zone.
Enemy has units in 55 Sea Zone.
Enemy has 1 transport in 51 Sea zone.
Izmir is Neutral.
You want to attack 55 Sea Zone.
You can't go 52 to 55 because of the Rhodes canal.
You can go 52 - 51 - 55, but, since you can't do it in two steps, the only way to do it is using Ctrl.
Thus people that don't know about Ctrl to set the path won't be able to do the move (they will try to do it in 2 moves, moving in 51 first, but without being able to).
This can be tested in WAW right away, by adding 1 Germans submarine in 52 and 1 Allies transport in 51.

**Comment by Cernelius** [comment]
This was just to say that, with canals, you can have situations in which this limit of not being able to do this same kind of move split in two is not merely trivial, but means that you can't do it but by using Ctrl to set the path (which most people I believe are not aware of).

**Comment by Cernelius** [comment]
I still believe that doing it in 1 move, not splitting it in 2, is the correct way to do this move. So I've really no problems if the engine doesn't allow you to split it. Maybe the engine should do the same in all cases of multiple movement on the same phase. Just saying.

**Comment by DanVanAtta** [comment]
While maybe "clean", it's not obvious, and the move is valid.

**Comment by DanVanAtta** [comment]
>  Maybe the engine should do the same in all cases of multiple movement on the same phase.

While being "pure" about the moves is nice, the game needs to be fast and easy to play. Explaining to players why they can't make valid moves, because they moved the unit once, and did not know the final destination when they started, is frustrating. TripleA needs to be much faster to play than it is today.

**Comment by Heppisorus** [comment]
This affects more unit interacts as well.  The same thing happens in TWW when you stop a sub in the same SZ as a destroyer (which cannot block the subs movement)... you have to undo the move and redo it moving to the final destination (through the SZ with the destroyer) without stopping.  Minor annoyance... but I agree with Dan's assessment.
