### ISSUE TITLE
6157 - combat button text is truncated, could use some hover text

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2228]
Notice that the full territory name is not displayed. We could use some hovertext to show the full name in case it would ever be important:

![no_hover_text](https://user-images.githubusercontent.com/12397753/29332528-309f5e0c-81b5-11e7-94a2-f642e1c32cf3.png)

**Comment by Cernelius** [comment]
Really, just get rid of the "Battle in " at start. Simple fix, and nobody can think we are talking about something else but battles. That done, I don't think a mapmaker will ever get so crazy with the names that anything else is needed.
The only item would be the "air battles", but those should really be integrated with the related battle; so that is something to rethink anyways.

**Comment by DanVanAtta** [comment]
Territory name only is a good suggestion. If truncation happens we should look to adding a hover text. The window sizing is not very strict, this can be shrunk to be smaller. It's a rule that there will always be a name that is +1 longer than the max you expect.

**Comment by ron-murhammer** [comment]
@Cernelius @DanVanAtta I don't think removing "battle in " would be a simple solution here. The reason is there are different types of battles such as normal land/sea battles, air battles, air raids, and bombing raids. You can also have more than 1 type in the same territory.

**Comment by Cernelius** [comment]
@ron-murhammer As I said, land/sea battle is not a problem at all, because you would see if it is on land or on sea and, anyway, the "Battle in " adds nothing there. For the air battles and the strategic bombing raids, the first ones, as I said, should really be integrated with the related battle, as the first step of it (so that is something to rethink anyways) and, the second ones, should just all happen before any normal battles.
So, none of the above you mentioned should be an issue, if they would be handled correctly or sensibly; then the "Battle in " at start would be surely redundant and uninformative, thus cuttable.

**Comment by ron-murhammer** [comment]
@Cernelius So fair points though I think what you describe would be a much larger effort to change. I think this issue is more around how can we make some small usability improvements and the best way to do that.

**Comment by Cernelius** [comment]
@ron-murhammer For the bombing raids and possible connected air battles, I just tested and I see that they are already correctly now all made before any normal battles to select; so that is not an issue, already.

**Comment by Cernelius** [comment]
@ron-murhammer The above leaves the air battles before the normal battles as the only one remaining issue.
I'm not aware if there are any rules for such air battles (?) or if it is a custom addition of TripleA (maybe @veqryn can tell here, since it was him adding this feature) but, unless there are rules against it, I would strongly advice the air battles being part of the same battle they are beforehand. Meaning not having an air battle in the X territory and a normal battle in the same too, as two distinct buttons, but having the air battle just as the first phase of the whole battle (thus never more than 1 button per land territory).

**Comment by Cernelius** [comment]
Alternatively, it would also make sense having all air battles before any land or sea normal battles. This would create two consecutive lists, thus not presenting the naming problem either.

**Comment by simon33-2** [comment]
All air battles are already automatically fought! 

Amphibious assaults are not presently noted differently from overland or naval battles.

Removing "Battle in" has no impact on maps I'm aware of; perhaps there are other maps though.
