### ISSUE TITLE
6157 - no 'unmute' option

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2231]
On a multiplayer staging screen, there is no 'unmute' option, you can mute someone, but you can then never unmute them.

![network](https://user-images.githubusercontent.com/12397753/29333631-57e65fca-81b9-11e7-8661-98f3449eff2e.png)

![muted](https://user-images.githubusercontent.com/12397753/29333743-ca244dae-81b9-11e7-8fa3-526c1c342cc9.png)

--------------

Instead of adding an 'unmute', maybe we should remove 'mute' and replace it with a 'kick' option?

**Comment by ssoloff** [comment]
It looks like this will require the addition of a few new "unmute" methods to `IServerMessenger`.  The only thing that I'm not sure about is if `IServerMessenger` methods can be invoked remotely because, if they are, adding new methods will introduce a compatibility issue with old releases, as we've discovered in two other recent PRs.  My cursory research seems to indicate that `IServerMessenger` methods are _not_ invoked remotely (at least not directly, but they are invoked in response to other remote method calls). [**EDIT:** After a second look, I realized `IServerMessenger` was recently modified to use `Instant` instead of `Date`, and we didn't have to revert those changes.  So that probably confirms that it is immune to RMI compatibility issues.]

However, there's a slightly different implementation that would not require any new methods, and thus would be immune to potential compatibility issues.  When muting, we currently pass `null` for the duration, which means the muted user will never be scheduled for unmuting.  I believe it would be trivial to prompt the host user for a duration (as is done in the lobby) after they select the user to mute.  Then we can pass this duration instead of `null` so that the muted user will eventually be unmuted.

Does that sound like a reasonable alternative?  Or should we just pursue an explicit unmute command (noting that this would only apply for a P2P game; adding it to the lobby _would_ require breaking RMI changes).

**Comment by RoiEXLab** [comment]
@DanVanAtta If we remove a "mute xyz in chat" option, we should provide a "disable" or hide chat option though, which simply does not display the chat at all, and doesn't allow the user himself to write messages until he re-enables the chat again.

**Comment by DanVanAtta** [comment]
Closing, unlikely we will get to this. If we redo how server/client networking is done, then as part of that having a complete mute/unmute would be ideal. This I think will be a known problem until then.
