### ISSUE TITLE
Fix accidental Space bar confirmation (problem while typing, eg: chatting)

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2293]
Background: https://forums.triplea-game.org/topic/293/remove-space-bar-for-casualties-confirmation

Task:
- look at any place where an action can be confirmed with a single press of space bar (politics is an example). Check if:
  - if it makes sense to assign a new hotkey for confirmation and space bar can be excluded
  - if a second confirmation prompt would be appropriate
  - if the confirmation can be made  async
  - if an 'undo' can easily be added so that there is no such penalty for an accidental confirmation.
- look at any place where an action can be confirmed with two space bar pressed (eg: combat casualties). Check if the UX can be improved.

Requirements:
- keep combat fast, players need to be able to confirm casualties with keyboard shortcuts quickly. 
- make it very difficult if not impossible to unintentionally confirm actions (even while chatting), and/or make the cost of such accidents zero by allowing 'undo' for example

**Comment by Cernelius** [comment]
Just as a side note, for actions (political and user) accept there is the workaround of having 2 or more action accept for the same player. That way, you get asked the same thing twice (or more), and accept it only by accepting it all the times, thus basically working as a confirmation upon accepting (not upon refusing). However, this is a hack, because the multiple is supported for political actions requiring the consent of multiple players, not for asking the same one again and again.

```
<option name="actionAccept" value="France:France"/>
```

**Comment by DanVanAtta** [comment]
This issue is getting stale, closing, with some regret seems this will continue to be a known problem for some time .

**Comment by DanVanAtta** [comment]
Second thought, adding ice-box label, this can/should be worked on, but we do need to take it out of the active queue (after not being worked on for a year, pretty clear this is not active).
