### ISSUE TITLE
Dragon War

### ISSUE THREAD

**Issue by gavmelv** [triplea-game/triplea#2301]
### Any additional information that may help:
Zombie Plague slows down (Rnd 5,6) then stops (Rnd 7).
I have saved games available as tsvg, but zipping is an issue at the mo.
DW R05 5Und 1.tsvg
DW R06 5Und 1.tsvg
why is the Z Plague not able to move 3, only 1
DW R07 5Und 1.tsvg
not at all
Zombie at Misty Slopes et al cannot move either

Email me/let me know if you want these games

**Comment by gavmelv** [comment]
loving the game/map

**Comment by ron-murhammer** [comment]
@FrostionAAA Can you take a look at this?

@gavmelv Uploading the save game here (you need to first zip it then upload it) would be helpful.

**Comment by FrostionAAA** [comment]
I have just played a 10 round game. Used 1.9.0.0.3635 and downloaded Dragon War. Also ran an AI vs AI game and observed. I cannot see any errors and the console is also empty of errors.

The Zombie plaque acts like it is coded:
•	It can fly into an empty enemy territory during combat move, and not capture it, as it is an air unit.
•	It can also end its round there, again without capturing the territory.
•	At the end of the Undead turn it spawns a “Zombie” land unit.
•	This Zombie also does not capture the territory in that same round as there has been no combat move into the territory.
•	At the next undead turn the spawned Zombie cannot move, again as there has been any capturing of the territory. But it will capture the territory automatically in the combat round, since it is enemy lands, cannot move and therefore forced to use its combat move phase to attack the land.

I can see how this unit behavior could cause confusion, even though there is nothing wrong.
I can see that the long capture time can be avoided by having “Abandoned Territories May Be Taken Over Immediately” set to true in the XML. I have not seen any side effects yet of having it set to true, so I think it will be set to true in the next Dragon War release, when the new TripleA engine is live. (The release supporting hidden players)

How to use the Zombie Plague: I would try to have it flying in friendly territories and ending turns in friendly territories, then the Zombies can move at next combat move phase. Also I would avoid leaving it exposed and vulnerable to enemy attacks. If it is wiped out: No more free units every turn from the Zombie Plague. I can see that the AI seems to be pretty protective of it and sometimes moves it to the capital and makes it spawn units there, but sometimes the AI also brings it into battle, something I would avoid.

The territory “Misty Slopes” does have all its connections. So there is nothing wrong with it.

**Comment by gavmelv** [comment]
Yes, FrostionAAA, I agree that's how things should go with the ZP and on many occasions it has done.
But not with this one.
I'm having trouble with zip on this new laptop with Windows10. If you're in the US and see that wee fella Gates, then give him a slap from me. I'll email you the files directly.

It might be an idea to put that info in the Game Notes.

**Comment by FrostionAAA** [comment]
@gavmelv
Sorry for holding this issue open this long, I totally forgot about it. Your save games are of Dragon War v1.2.2 and I could not load them. The Dragon War map is v1.2.3 now and I yet again tried a few games to round 10-11 as the Undead player. I can’t spot any strange behavior from the Zombie Plague. Its seems to work as it should.

If you don’t have this problem anymore or you have not seen it since the map version update or TripleA engine update, this issue should be closed. If you remember how you get these units to become buggy, then please recreate an instance and post it again as a save.

**Comment by gavmelv** [comment]
No worries, mate. I'll give the new version a spin sometime soon and get
back to you one way or another.
Strange that my down/up-loaded games didnt show up the error.

Keep up the good work
Gav
