### ISSUE TITLE
Warclub / Xoops Read-only

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2318]
Seems like it is the right time to turn warclub forum to read only and put links to post in the new forum. Correct me if I'm wrong, the sourceforge forum is already read-only.

Can anyone pick up this task and see it through, perhaps @prastle ?

**Comment by prastle** [comment]
The war club has a link to the new forum in the news.  New members have been blocked already.  I will look into what needs to be changed to block posting by all except webmasters.

**Comment by prastle** [comment]
It appears to require resetting the default permissions template for all the different user groups.  A bit of a time consuming thing.  Probably unnecessary if we are going to image move it.  Since new users are the only ones that were posting generally in the past few months and they have been blocked.
