### ISSUE TITLE
SVN forum read-only

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2319]
Can this be done? If so, can someone take this task up? (I'm assuming there is no objection to this being done at the moment, please chime in if you think we should wait on this task or maybe not do it at all)

**Comment by ssoloff** [comment]
By "SVN forum," do you mean the Subversion repository on SourceForge?

**Comment by ron-murhammer** [comment]
@DanVanAtta Assuming you mean this forum: http://triplea.sourceforge.net/mywiki/Forum

I've now made it read-only for everyone except admins. The one other thing that should be done is updating the old SF home page to point to the new forum and remove war club link: http://triplea.sourceforge.net/mywiki/TripleA

**Comment by Cernelius** [comment]
I suggest allowing posting in it forever in old threads, and also keeping allowing new users registration, but disable new ones, if possible. This should also solve the spam problem, as I see they always open new topics, not post in any existent ones.

For example, there are a lot of maps topics, you may want to give some opinion about, but not opening a new whole thread about it (and very few of those will be reopened in any new forum); example:
http://tripleadev.1671093.n2.nabble.com/Empires-Napoleonic-Wars-tp4696030p7595744.html

**Comment by Cernelius** [comment]
That is assuming the old forum is not being imported in new, as you said.

**Comment by ron-murhammer** [comment]
@Cernelius I'd rather users create a thread in the new forum and just reference the old one. I'd really prefer not to have any more posts in the old forum.

**Comment by Cernelius** [comment]
@ron-murhammer I'm not sure how this can be. Are you sure that you want to allow anyone to open the official/main thread of any maps?

Of course, I don't believe that there is a way to verify anything, so I could as well register in the new forum as "Sieg" (while not being him) and open the new official main thread of "New World Order", but I guess false impersonification should happen very rarely, and anyway I'm not worried about it (this was just a side note).

On the other hand, I can't see what you say really happening, unless I guess you well document that this behaviour is expected. For example, in the moment in which I want to talk about "Great War", maybe saying that I dislike some stuff in the map (and in the old forum I would have made a reply in the thread), am I supposed/encouraged to open the new official main thread of that map, for anyone to use from then on, referencing to the old one? I can hardly see anyone else but the mapmaker, or any new owners, doing that, unless if, I guess, you intend to clearly document this procedure in the new forum for all (that anyone can open the new main thread of any maps, that is then supposed to be used by anyone, preferably, instead of opening more and more of the same)?

Mainly, even if this would be the process and it would be well documented, I can hardly see it actually happening, because I don't think that users will dare to go ahead opening the new main thread for a map, just because they want to comment about it. In the above case, I would feel very reticent at going ahead opening the new main thread of "Napoleonic Empires", to be used from now on, because I want to say something (maybe minor) in it.

Or maybe you, instead, intend that the procedure would be to open a new thread just to talk about what you wanted to talk only, not reopening a new general thread for the map/game. Well, in this case, as I said, I tend to think that having the comments about a same game/map all in a single thread is much better than keeping opening different threads about the same map each time somebody wants to say something about the game/map (of course, nobody stopped anyone doing this anyway, but normally users used to reply in the main thread, if present).

Anyways, I realise this is probably mostly a moot point, as I don't believe the old forum would get used much, for this or anything else, especially by users not yet registered in there.

**Comment by Cernelius** [comment]
The coolest thing, and I don't even know if this is a feasible feature request, would be that a topic in forum is automatedly created for each map, in the moment in which the map exists in download list, with a static incipit, like what you see here:
http://www.triplea-game.org/map/270bc/
and an additional section thereafter, that it is fully directly editable only by the admins of the related repository (or refer to something that it is, additionally to the download list comment reference).
That way, you could have 1 forum thread for each map, comprising all existent ones, which will probably remain just there for casual comments; but you would be able to assign it if anybody would happen to take over the related maps.
It should also be possible to have multiple admins assigned. For example, @ron-murhammer would share WAW with **ice** (two games in a map).
Maybe even keeping the official threads not in forum, but in a static page like the one I linked, except with an additional section below, able to be modified (in particular, adding other images) by somebody having restricted access to it, and with the ability for anyone to comment further underneath it, but I think it would be better as part of the forum.
Again, no clue if something like this would be feasible.

**Comment by prastle** [comment]
Actually @Cernelius  that is completely possible in the forum.  We just add a group that have permissions for that section only (other than admin). Or we add 20 sub groups 1 for each map if ya want it really isolated as the assigned owner and admin only have true permissions in that section.  Good Idea! up to them.

**Comment by RoiEXLab** [comment]
@prastle Thought about that too.
I think it's worth mentioning it would be way too much work to automate creating threads, if you can add them manually.

**Comment by prastle** [comment]
@RoiEXLab dont think we need to automate.  The owner(s) of that map is sub admin(s) of their own thread.  BTW I am referring to the future.  Past threads would have to be imported and ownership taken over.

**Comment by Cernelius** [comment]
I was actually talking mainly of past threads, and only incidentally of future ones. I think for any future threads just simply opening a forum topic, like it was done in the old developer forum and I see it is being done now (for example, @ron-murhammer did it for WAW), works well enough, and may be just the best way.

The main problem is that if you just close the old forum, people has no anymore a way of talking in a specific map thread, while opening a new thread each time you want to comment on something about the same map would be silly and dispersive, and I doubt that it is workable that random people reopen a new main referring thread, and almost noone of those threads is going to be reopened by their original makers (beside the fact that I don't believe you have any ways to know who is who anymore, since everyone has to register anew).

So, I think that, for the time being, you should keep the old developer forum open for registering and posting, and just disable new threads (since you moved to a new forum for that), if that is possible (would be no problem for spam, I believe, as it always opens new threads only).

Anyways, up to the admins of the old developer forum to do what they prefer, of course.

**Comment by Cernelius** [comment]
To be clear, I don't think it would be good if the mapmaker has to ask admittance to anyone for making his own map thread, as that would increase overhead on both sides (especially work for the admins and waiting time for the mapmakers) and be an unnecessary confusing element overtime (with people missing the step and creating a normal thread, instead). As I see it, either it is automated (created in the moment in which a new map is added in the repository) or better sticking to simply letting people opening a normal thread, but this is not solving the problem of all those old maps threads that you are now making inaccessible for posting.

If the automated way is not feasible, I think better just letting the old developer forum open for registering and posting and disable only new threads.

**Comment by Cernelius** [comment]
> I think it's worth mentioning it would be way too much work to automate creating threads

Ok, nevermind then. I was just wondering, since you made this (neat) thing in the static website:

http://www.triplea-game.org/maps-list/maps/

**Comment by DanVanAtta** [comment]
> The main problem is that if you just close the old forum, people has no anymore a way of talking in a specific map thread,

> opening a new thread each time you want to comment on something about the same map would be silly and dispersive, 

I don't necessarily agree it is dispersive. For most maps there will likely be one thread, but there is no hard and fast rule about this. It is pretty simple: open a new thread if you need one. If you are picking up from an old thread, use the same title, link the old thread, and just pick up from there. The old forum is still not yet read-only, now is a good time to finish any threads. Really though we don't want anyone looking at the old forum any longer, all eyes on new forum, time to march ahead, it's been almost a year now.


---------------

@Cernelius long threads are fine if the contents of a thread can be "forgotten" as time goes on (eg: 50 pages, but you never have to read any but the last 2). This works for example if you have a single person building a map and responding to commentary. This does not work very well when you have teams working on something. Also for dev's, contributors, and admins, long threads are a bit of a nightmare since there is so much overhead to even understand what a task involves let alone even start on it.

On the other hand, there is a tradition of using forum threads to discuss maps. I would be careful to consider the limitations of that, avoid task tracking as much as possible in forum threads since that is just not the right tool.

> So, I think that, for the time being, you should keep the old developer forum open for registering and posting, and just disable new threads

Problem here, nobody should even be reading the old forum actively, we want all eyes on the new forum.

----------------------

### Re: map ownership and map thread hijacking

Official map ownership is whomever has write access to the map repository.  Having a map thread does not necessarily make someone an owner of a map. If it does become a problem, we can delete threads.

---------------------

## Automated conversation thread

Somewhat ironically @Cernelius this is easiest by using github issues. Each map, since it is hosted on github, will have a github issue queue and we will know the link to it. So we could add a link to view the open threads and another to create a new one. 

I think we do want a forum based approach though for the map conversations, notably just from precedent. There is a loose end to add in more meta information for the map listing, as part of this we could allow an optional "official forum post" link. So when you update the maps yaml file, there will be a new field you can update there to add the link. We could then put that link on the map page in: http://www.triplea-game.org/maps-list/maps/, and also in the game engine itself as well when playing a map (recall we previously had a 'leave map feedback' menu option that did open a new github issue for the current map)
