### ISSUE TITLE
New (?) lobby login failure (stable only)

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#2398]
### My Operating System:
Windows 7.64

### TripleA version:
Stable (3635)

### Map:
irrelevant

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Lobby login fails (stable only)

### Do you have the exact error text? Please copy/paste if so
![tra](https://user-images.githubusercontent.com/20812775/30753925-13bfcb4e-9fc1-11e7-9728-b8ceb00e037e.PNG)

### Instead of this error, what should have happened?
I expected to be able to log in using stable, too (using my new account created about two weeks ago).

### Any additional information that may help:
**I am able to log in using the latest pre-release(s) (6727).**

As indicated here 
https://github.com/triplea-game/triplea/issues/2347#issuecomment-328291627
I had been able to log in using 3635 about two weeks ago, too.

I am not raising this issue asking to resolve something concerning the old stable.
Maybe there have been changes in the meantime, so this is the expected behaviour. 

I am just pointing it out because there still seem to be issues for users.
Also see https://forums.triplea-game.org/topic/329/installing-and-running-pre-release

**Comment by ssoloff** [comment]
@panther2 In the current production lobby database, there is a single column that is used to store your hashed password.  However, the current client uses one algorithm to calculate the hashed password (MD5Crypt) while the pre-release client uses a different algorithm (bcrypt).  Because there's only a single column, only one or the other type of hashed password can be stored at a time.

Therefore, once you login with a pre-release client, the bcrypted password is stored in this column.  When you go back to login with the current client, the MD5Crypted password sent by the client does not match the bcrypted password stored in the database, and you get the error message you observed above.

@RoiEXLab has submitted PR #2358 so that both the MD5Crypted and bcrypted passwords can be stored simultaneously.  That should then allow you to login with both clients.

Note that if you _really_ need to login with the current client, there is a hack to restore your MD5Crypted password in the database:

1. Login to the lobby with the latest client.
1. Go to **Account** > **Update Account...**.
1. Enter your _current_ password in both password fields and click **OK**.

If this code hasn't yet been changed, updating your account will overwrite the bcrypted password with the MD5Crypted password.  After that, you should be able to login with the current client.

@RoiEXLab please confirm if the above is correct.

**Comment by ssoloff** [comment]
> As indicated here
#2347 (comment)
I had been able to log in to 3635, too.

For completeness....  This worked temporarily due to an error on our part.  We deployed the new lobby code without updating the database schema to match what it expected.  This prevented the new lobby from writing the bcrypted password, so it _always_ wrote the MD5Crypted password.  Because the pre-release client can login with either the MD5Crypted password or the bcrypted password, you were able to login without issue using both the current and pre-release clients.

In response to #2347, the database schema was updated.  After that point, logging in with a pre-release client would allow the lobby to write the bcrypted password, thus preventing future logins from the current client.

**Comment by panther2** [comment]
Understood! Thanks a lot for the comprehensive background information, @ssoloff .
So my feeling that my latest experience has been "expected behaviour" due to interim development has not been wrong. 

I'm sticking to latest pre-releases anyway and only access 3635/stable for testing purposes here and there. But your explanation will help me understand possile issues other players experience better.

**Comment by prastle** [comment]
TY  @ssoloff  but the simple answer is if @hepps wants to use pre release he needs account deleted and needsto login with a pre correct?

**Comment by ssoloff** [comment]
@prastle I looked at @Heppisorus's [thread](https://forums.triplea-game.org/topic/329/installing-and-running-pre-release) on the forum.  As @panther2 pointed out, that error message indicates the client cannot even connect to the lobby; not that authentication failed.  So it is probably unrelated to the old vs. new hashed password issue discussed above.

I think @panther2's theory about Windows Firewall blocking the connection because TripleA was installed to a different (non-protected) directory is a good place to start.

**Comment by prastle** [comment]
Just to clarify
I cannot login with stable after login with new pre

**Comment by prastle** [comment]
all other pre releases work have um 20?

**Comment by prastle** [comment]
but not stable

**Comment by panther2** [comment]
@prastle This is most likely due to the same situation I created this issue for.

**Comment by prastle** [comment]
he only way I was able to login again with a pre was by deleting my own account....

**Comment by ssoloff** [comment]
@prastle 

> Just to clarify
I cannot login with stable after login with new pre

 Yes.  Unless @RoiEXLab overrides me on this, that is the expected behavior at this time.

**Comment by prastle** [comment]
ok so can someone tell hepps since he doesnt believe me

**Comment by prastle** [comment]
and by delete to be CLEAR
deleted from database
and recreated

**Comment by ssoloff** [comment]
@prastle 

> he only way I was able to login again with a pre was by deleting my own account....

Did you mean "with ~a pre~ current"?

**Comment by prastle** [comment]
YES

**Comment by prastle** [comment]
Created account with stable
couldnt use pre
Created account with pre
cant use stable

**Comment by prastle** [comment]
Is that clear?

**Comment by prastle** [comment]
Just to also clarify Why am I deleting myself to test?

**Comment by prastle** [comment]
atm using .6714
i appologize for the issues
just explaining as best i can @panther2  did as well

**Comment by ssoloff** [comment]
@prastle 

> Is that clear?

I think so.  If you're saying you can't login with a pre-release using an account created with 3635, that's a problem.  Let me try to reproduce that.

> Just to also clarify Why am I deleting myself to test?

Because we broke compatibility. :smile:  To be fair, I don't think the concept of the test group had been established at the time those changes were merged into the pre-release.  So no one was thinking there would be a large number of users going back and forth between stable and the pre-release.  I know we discussed that going back to stable after logging in with the pre-release would not be possible, and those of us involved with that PR seemed ok with it at the time.  It seems we dropped the ball, but #2358 is attempting to correct that.

**Comment by prastle** [comment]
No what im saying is i cant login with an acount created with pre release back to stable
thus hepps recreated his new account in stble and cant use a prerelease.

**Comment by prastle** [comment]
SO
as i asked in other spots
Is the simple answer delete his account and he logs in with a pre?

**Comment by ssoloff** [comment]
@prastle 

> No what im saying is i cant login with an acount created with pre release back to stable

Ah, ok.  I was confused by the first two lines of your previous statement:

> Created account with stable
couldnt use pre

I interpreted that to mean you could not use the pre-release after creating an account with stable.

<hr>

> Is the simple answer delete his account and he logs in with a pre?

If hepps is getting a "Connection Refused" error, I don't believe deleting and recreating his account will have any effect.  That error implies his client is not even making a network connection to the lobby, which is a prerequisite to logging in.  As @panther2 said in the forum, it sounds like it could be a firewall blocking his new installation.

One other thing you can check in the pre-release is the lobby host/port configuration:

1. Click **Engine Preferences** from the main menu.
1. Go to the **Testing** tab.
1. Verify that the **Lobby Host Override** and **Lobby Port Override** fields are blank.

If those fields are not blank, click **Reset To Default**, then **Save**, and then **Close**.  Finally, try to reconnect.

**Comment by prastle** [comment]
ty we can try that
 
but i can safely say

anyone on stable join that time period cant go vice versa

**Comment by prastle** [comment]
doesnt really matter its truly up to him

**Comment by prastle** [comment]
and yes he created with stable thus cant use pre

**Comment by RoiEXLab** [comment]
@ssoloff Everything you said is correct.
The "hack"/workaround you spoke of: It's true, thr code hasn't changed, because the code to update the current password is invoked seperate from the whole login and registering code.
The latest commit to the branch of my PR "fixes" this behaviour by sending a "not-md5crypted hash" along with it, but it doesn't improve security, as this md5 hash is not send encrypted in any way, e.g. it essentially replaces the password which is bad. Now the SHA-512 hashed password is sent, but this is basically the same problem. 
I need to look into the code to see if I'm able to make account updating use the RSAAuthenticator without breaking compatibility. 
Otherwise we are forced to continue sending the password unencrypted over the Web until we work on a breaking release.
