### ISSUE TITLE
Question: Github import of maps

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#24]
Maps is still in sourceforge? Atari map has a bug where "Factory.png" is used instead of "factory.png". A person only see this problem on a case sensitive file system. Seeing that reminded me maps are not in git. @veqryn , will you be moving maps into git? Second thing I wanted to ask, can we check in the map files in an expanded format (not compressed in zip)? Allows for easier modification,  building  would be simply zipping stuff up.

**Comment by veqryn** [comment]
I can.  But I never really treated them as 'code'.  The only reason it was under svn was so that I would receive updates when someone else adds or changes a map.

One question would be: Right now, that svn repo is like 2 gb or something.  If we broke everything out of zip files and had it sitting raw in git, I could imagine it being 4 gb.  It git and github ok with that?

Another would be: we would need some 1 line command that turns all the maps into zip files that look exactly the way they do right now.

And the last question would be, would the person who manages this repo (currently @ron-murhammer) be ok with unzipping maps people give him and committing their contents, in addition to all the other steps he already takes when updating a map?

**Comment by DanVanAtta** [comment]
The XML files would be good to be under source control. Given map editors might not be comfortable with it, that makes this a longer discussion.

github AFAIK only allows 1gig for opensource free repo's.

For zipping the file, we could create an ANT or Gradle thing that will do that, or maybe a shell script, it can be done one way or another. Problem is where to host the assets. 


I think I have my questioned answered. This can be closed IMO, I'm in favor of letting the maps be and their process be alone for some time.
