### ISSUE TITLE
Lobby Monitoring?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#241]
Relating to the crash that happened in #234, it was a few hours before the lobby was restored in that example. Is there anything set up to monitor the lobby?  

If nothing is in place, any thoughts about setting up a monitoring node?

**Comment by veqryn** [comment]
I am fine if someone wants to set up some simple free monitoring of some kind.

I believe an email got sent out to everyone with access to our server instance, that a restart would be done.
Unfortunately I did not see the email.
Since then I've added redrum to the list of people with access to the server (in linode), so he would see it as well.

**Comment by DanVanAtta** [comment]
Biggest problem for this is having a server where we can run the monitoring. Anyone have any ideas/thoughts/suggestions there?
