### ISSUE TITLE
The Donation link needs to be updated.

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#2480]
When playing in a game the donation link under the web tab still lists the old paypal link  We need to update this.  Running   .7051

**Comment by ssoloff** [comment]
@prastle If you can provide the exact URL, I can update this.  It's not clear to me just by looking at the Donate link on the Forum what the correct PayPal URL should be.

There's also a link on the [Sponsors](http://www.triplea-game.org/sponsors/) page, but that appears to be an older PayPal link that went directly to Chris.  That should probably be updated, as well.

@RoiEXLab I noticed that there is no link to the Sponsors page from any other page on the website.  Is this intentional, or did we accidentally drop the link at some point?

**Comment by prastle** [comment]
@ssoloff   TY  

This should work I think.
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=GKZL7598EDZLN

Yes the sponsors link should probably be updated to the last years sponsors.  

https://forums.triplea-game.org/post/2160

**Comment by RoiEXLab** [comment]
@ssoloff I'd assume it has been dropped at some point probably not intentional, searching through the git history may make some things clear...

**Comment by ssoloff** [comment]
@RoiEXLab Weird...  It doesn't appear that the Sponsors page has _ever_ been linked from within the website, even when it was first introduced in triplea-game/triplea-game.github.io@b9e3448.

Do you have any suggestions from which page it should be linked?

**Comment by RoiEXLab** [comment]
@ssoloff Maybe somewhere in the footer section?

**Comment by prastle** [comment]
I can safely say I have never seen it till you showed me.

**Comment by prastle** [comment]
Either way the people who have donated or sponsors should be the most recent with perhaps past history.  jmho

Perhaps just eliminate it altogether and just use the donations link in new forum?  Just a thought.

**Comment by ssoloff** [comment]
@RoiEXLab Sounds good to me.  How about right under **About > License**?

> Perhaps just eliminate it altogether and just use the donations link in new forum? 

@prastle I was just going to ask you that since you said you had never seen the Sponsors page before. :smile:

@ron-murhammer Do you have an opinion on keeping the Sponsors page on the website?  It's never been linked, so for all intents and purposes, no one has probably ever viewed it since it was first introduced two years ago.

Another alternative is to drop the Sponsors page and add a Donate link in the footer.

**Comment by prastle** [comment]
Well we always had a donate link in footer or header forget which?  It went to Veq then.  Ron removed that awhile ago.  I think just and same link to donations page in new forum in header or footer.

**Comment by ron-murhammer** [comment]
No strong opinion on it. I actually didn't realize it existed either :)

**Comment by ron-murhammer** [comment]
Closing as this should be fixed now.

**Comment by prastle** [comment]
TY
