### ISSUE TITLE
axisandallies.org has trouble supporting PBF

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#250]
Background info at #37

The quantity of save games getting attached the forum and their size causes operational problems for the axis and allies.org people.  They would like this fixed in some way such that it's not a big maintenance burden to manage disk allocation for the megabytes of game files that accumulate.

**Comment by ron-murhammer** [comment]
So I think the only way to really fix this is to create manual save game binary creation instead of using java serialization. Probably a pretty big change. All save games I've seen are <1MB and usually around 1/10 of that. I'd be interested to see statistics on how many save games and total size that A&A has to determine the importance of changing this.

**Comment by DanVanAtta** [comment]
The task here is not well defined. It's not the right place to track us getting to a custom save file. WaW games I'm emailing are regularly 1MB, the PBEM game I have going would have consumed about 60MB if all posted to a forum. The problem is perhaps that the save does not scale well, that it can easily blow up in size.
