### ISSUE TITLE
Bots Seem to very slow to load.

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#2555]
I am not sure if this is an issue.  Lately the bots seem very slow to restart if they have been shut down.  I don't ever recall it taking this long to restart four bots.  I often shut down the DE server bots unless it is needed and all the bots in the lobby are full.  It makes the lobby very crouded with 20 bots running and half of them empty was my theory.  I just timed it right now (lobby is full and busy so they were needed back up)  and it took 11 minutes for them to restart.  I am just mentioning.

**Comment by DanVanAtta** [comment]
Bot load time is dominated by map parsing. @prastle check if War of the Relics was installed, that map takes longer to load then all other maps combined and then some. Deleting the file is best way to go, no way to preserve that map in the game and avoid the really slow load delay (if that is what is actually at issue)

**Comment by prastle** [comment]
Ok ty I will look. @DanVanAtta

**Comment by RoiEXLab** [comment]
We did in the past, but the current "update" script redownloads all maps, so we need to delete it every time after an update.

**Comment by DanVanAtta** [comment]
Opening, action item: omit downloading War of Relics when download 'all' maps so we don't accidently re-introduce the map.

**Comment by RoiEXLab** [comment]
I submitted a bunch of PRs that should speedup bot loading on the bot servers.
War of The Relics probably no longer impacts the general loading that heavily.
So since the update script seems to be bot related, I think opening a dedicated issue at the lobby repository would be a good idea.
If the engine should implement an auto-updater for bots, then I'd like you to open a dedicated issue for this topic as well, simply to make clear what we are aiming for exactly.

**Comment by prastle** [comment]
Np Close it for now. @RoiEXLab
