### ISSUE TITLE
Low Luck workaround for always active AA's

### ISSUE THREAD

**Issue by airwalker1** [triplea-game/triplea#2627]
### Any additional information that may help:

There is an opportunity to exploit to low luck behavior when passing through active AA territory by sending one air unit at a time. While this could lead to an increased chance of hits, it provides the opportunity to have 0 hits as well when sending what should be a guaranteed loss of unit/units. Perhaps moving the AA hit engine to the combat phase when active to sum all units would be appropriate. The same would obviously have to go for non-combat returning units of active AA territory.

**Comment by ron-murhammer** [comment]
@airwalker1 So the problem is that A&A rules dictate that the AA fly over dice must be resolved immediately as each air unit moves. So moving those rolls to the end of combat move would not align with the rules as the player then would not have information til all their moves are done on whether air units were shot down.

IMO, this is an acceptable side effect of LL which most closely aligns the the regular dice rolls. I'd suggest opening a thread on the forum to get more community feedback to see what others think. I'm going to close this for now but we can re-open if we end up with a lot of community support for changing this.
