### ISSUE TITLE
Battle simulator startup delay is too slow for large GameData games

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2643]
I've had the experience of playing WaW to round 20+, the game save size is 5MB and it generally took 5~10 seconds before the battle calculator was usable. This delay made the calculator essentially broken, could not be used during a live game for more than one or two calc's without adding minutes to a game turn.

Repro Problem:
- get a large game data (I'll see if i can attach a save game, appreciate it if anyone can attach one they create)
- open calculator, you'll see it filled in all details but the button is not enabled to calc
- eventually the button is available, this is the problem. The client has the local gameData client, there does not seem to be a good need for this delay (and even if there is, the delay makes the calculator broken to use).

**Comment by Cernelius** [comment]
I surely believe this copying of data should be made only the first time, upon opening the battlecalculator, and, then, stored. The same for the AI (how long does the AI store the data currently? Only for the same phase?).
This may also benefit games like Feudal Japan, when you have to wait some for the AI moves of many AI players, one after the other.
This way, opening and closing the battlecalculator would be not different from keeping it open.
Each time something fires off, that may change anything related (a trigger or a new tech), then data gets cleaned (like a tech may give +1 att to Fighter), plus maybe a refresh button on the battlecalculator.
This is really a hard issue only for getting data from territories, as otherwise you can just pust the battlecalculator aside, instead of keeping opening and closing it.
World At War wise, you should copy the data only the first time you open the battlecalculator, store it, and clean it when the triggers changing the production frontiers (adding units) fire off.

**Comment by ron-murhammer** [comment]
Without a bunch of changes that won't work. As the battle calc needs the current game data otherwise calc would be incorrect. An example would be tech or triggers that impact unit values.

**Comment by Cernelius** [comment]
>Each time something fires off, that may change anything related (a trigger or a new tech), then data gets cleaned

What I was saying is that you have these data stored, thus closing the BC is like you put it on standby or hide it.
As soon as any trigger fires or any new tech is gained, then this data get cleaned (no matter if maybe the trigger or the tech didn't actually impact on the BC stuff).
Then, the next time you open the battlecalculator, after the clean up, data get stored again, like the first time you opened it.
This means that in WAW that would happen only up to 2 times total, as long as you get to round 4, and in maps with no tech and no triggers you would just have the delay the first time, nevermore.

**Comment by Cernelius** [comment]
To make it even simpler, you can have the data stored only for the same phase, and clean it each time a phase ends (this is absolutely safe). This at least means that if you have to do a bunch of Ctrl+B on the same phase, you will get the data load only on the first one. Doesn't the AI already do something like this?

**Comment by ron-murhammer** [comment]
@Cernelius Correct that is what the AI does. I sets the game data once per phase since it shouldn't change in relation to calculations within a phase. In theory, we could do that with the player battle calc as well say the first time they open in each phase.

**Comment by Cernelius** [comment]
That would be a relatively major step. I would say that would cover like 80% of what this issue is for, as pretty much the matter is not having the delay again and again when you keep Ctrl+B on different territories and keep otherwise opening and closing the battlecalculator.
Also it would be good to standardise what the humans and the AI get all the same.
If further steps would be taken, like clear on triggers/tech/actions, instead of end phase, or even only when something influences what is relevant for the BC (I'd suggest against this, as this sounds like something with big legacy issues, when stuff gets changes), that would be better being all the same for human and AI as well.

Side note, maybe rename it as "Battle Simulator". It doesn't actually "calculate".

**Comment by Cernelius** [comment]
By the way. Isn't this a feature request?

**Comment by DanVanAtta** [comment]
> @DanVanAtta It doesn't really have anything to do with lobby vs local games

I mention this as there is a requirements difference. Local game, yeah its' not good. For a lobby game, turns are ideally short, ballpark 5~15 minutes. Suddenly needing 2, 3, or 4 minutes for calc is very impactful, makes the game slow and hard to play. My biggest criticism, issue with TripleA where I think we lose the most is how slow it is play a mulitplayer game (that's my personal 2 cents, most of my efforts I intend to basically come back towards this goal).

**Comment by DanVanAtta** [comment]
> By the way. Isn't this a feature request?

No, as the battle calc is not usable when turn time is a factor and you are playing late game on a big map. It's a bug due to how the feature is coded. Such gameData files are 5MB, the battle calc does not need anywhere near that much information to operate. The fact it gets a full read of full history and everything else is basically a hack to not wire in the right data properly. The result is that the code does not scale correctly, the battle calculator should not be slower in round 20 compared to round 1.

**Comment by DanVanAtta** [comment]
> Ctrl+B on different territories 

This is the primary use case I had in mind as entering in by hand army info for large groups is not very practical (think end of game WaW where there are upwards of 6 or 7 stacks that can have 150+ units).  Entering in large armies is not practical any other way, even to just get counts. There are open feature requests so that ctrl+b can go to an open battle window so you can basically click two territories and have a calc of the armies fighting rather than updating the values by hand from one window to the other.

**Comment by DanVanAtta** [comment]
> In theory, we could do that with the player battle calc as well say the first time they open in each phase.

Considering it's major surgery to rewire data, this could be a good option. I do suspect though if we can find which required data is needed, it's super fast to do the in-memory transfer of such relatively small data, that would be a long term solution and avoid the cost of state tracking.

**Comment by asvitkine** [comment]
I haven't looked at the code for the battle calculator, but I'm curious why it has to do a slow copying operation at all? Doesn't your local client already have all the information available - since it draws this info on the map.

**Comment by ron-murhammer** [comment]
@asvitkine It has the information but needs to make a copy as the battle calculator actually create battles and changes the copy of the data it has. So if you just used the actual game data then you be changing the actual game.

**Comment by Cernelius** [comment]
On this matter, and talking for experience, the battlecalculator will be slow loading also if you have a very big xml, for having tons of stuff like conditions and triggers, even if nothing of those matters at all for what the battlecalculator needs to know.

**Comment by ron-murhammer** [comment]
@Cernelius Correct, as it copies the entire game data minus the history (I recently removed the history copying based on a user uploading a 150+ turn game which made the copying really painful).

**Comment by Cernelius** [comment]
Cool. I would appreciate, and I could test it right away in a map I'm making that is not currently available (I intend to be), if you could also remove copying all the conditions and objectives and triggers and user actions and political actions. For that game, I tested now with 1.9.0.0.10535 it takes more than 20 seconds to load the data (until I can click on "Calculate Odds"). I would be happy if it would be faster (also I guess it keeps a bunch of RAM used for all that data), but it's playable (I hope).
