### ISSUE TITLE
Purchase Screen Buggy

### ISSUE THREAD

**Issue by General-Dru-Zod** [triplea-game/triplea#2660]
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

Two separate bugs regarding purchase screen.

1) No longer lists the maximum amount of allowable units for placement at bottom of purchase window.

2) Shows incorrect selections if I do the following:

a) 1st edit yourself 200 pu for Russia.
b) Try to buy 10 paradrop and maximum 40 infantry.
c) 40infantry ,10 paradrop  selected for purchase, click done. 
d) Get prompted that I am buying 50units and only 15units can be placed, and asks yes or no to continue with purchase. Click No.
e) Click change button to adjust infantry to 4 and click done. It incorrectly lists 40 infantry, 10 paradrop for purchase in the Action window. I actually have 4 infantry, 10 paradrop selected.
f) Click done anyways, and history lists correct amounts purchased and placed. 

### Instead of this error, what should have happened?

1) Should list at bottom of the purchase window, the maximum amount of units available for placement this turn.

2) Should display correct amount of infantry in Action window after I reselected correct amounts.

### Any additional information that may help:

[BW2_BOP_Purchase.Phase.Buggy.1.0_v7601 and v 7658.zip](https://github.com/triplea-game/triplea/files/1512004/BW2_BOP_Purchase.Phase.Buggy.1.0_v7601.and.v.7658.zip)

**Comment by ron-murhammer** [comment]
@General-Dru-Zod Responses:

1. I believe this is only available for maps with certain rule sets. The reason is when certain rules are active around infrastructure and units requiring other units for placement, the calculation is not straightforward.

2. I was able to reproduce that. If you then hover over the Actions panel then it does actually update to show the proper units. This appears to be an issue with the Actions panel not refreshing for some reason if you said 'no' to the prompt and then changed your purchased units.

**Comment by General-Dru-Zod** [comment]
1. Hmm, understood.

2. I am able to reproduce the glitch as long as the change (reselected number) does not go into the 10th place, so 9 and under. Looks like it has the 1th place and 10th place mixed up for refresh. 

I don't see mine refresh to accurate number with mouse pointer hover. However, if I click another tab and back to action its refreshed.

**Comment by simon33-2** [comment]
I'm sure I've seen this in Global too. Was never sure how to reproduce it.
