### ISSUE TITLE
Build script update request - working integration-test for dev with In-memory DB 

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2679]
This is on my wish-list, but also I think our build is lacking in this respect:
- today you have to install a postgres DB and get it up and running locally for the integration tests to work. Happily on travis this is easy configuration, and in prod we did this (https://github.com/triplea-game/lobby/blob/master/setup_lobby#L49), but in dev it's a small pain and you have to manually install a postgres.

Requested:
- add a parameter to the gradle build script, "QA" - that we would use with the travis build. This would instruct the build to use the local postgres instance (as it does today)
- when the "QA" parameter is missing, do a 'dev' build. For dev builds, before we execute 'integration-test' an in-memory DB should be launched and allow the tests to pass.

Note, when all is said and done, using `gradlew`, and having java installed, I don't think you would need anything else to have a fully working local build (yay!)

**Comment by ssoloff** [comment]
I thought we discussed previously not using a different in-memory database because then it's not really testing the "integration" with Postgres?

My typical dev cycle is to run `./gradlew check -x integTest` before pushing unless I'm directly modifying something covered by an integration test (e.g. lobby database stuff).  I let Travis verify the integration tests are passing before creating a PR.  If the issue is that `./gradlew check` should Just Work for a new developer, maybe we could exclude `integTest` from `check`, so that the Travis build command becomes `./gradlew check integTest` and the `check` task only runs unit tests?

FWIW, the lobby DB Docker container we have [here](https://github.com/triplea-game/triplea/tree/master/.docker) pretty much automates the creation and initialization of the lobby DB.  That takes most of the effort out of setting up an environment capable of running the integration tests.  Maybe we could somehow integrate that with the Gradle build?  For example, having Gradle automatically start/stop the Docker container as part of the `integTest` task.  That would also help with resetting the DB state between runs since the tests themselves don't clean up the data they create.

**Comment by RoiEXLab** [comment]
@ssoloff I want to point out it might be better if we'd use docker images in production for the lobby as well, so we could make updating easier (Although I must admit it has gotten pretty easy now that Derby is gone)

**Comment by ssoloff** [comment]
@RoiEXLab No objection from me.  In fact, I was going to suggest we use the new Node dice server as the guinea pig for using Docker in production.  That would give us a relatively straightforward platform on which to learn how to manage things the "Docker Way" without affecting an existing production service.  Then we have the option of migrating the existing services slowly over time.

**Comment by RoiEXLab** [comment]
@ssoloff Feel free to setup docker configs etc. on the repo, I believe I'm currently requiring a private key file (passed as a CLI param), and a postgres database, with a predefined scheme (see the [db-handler.js](https://github.com/triplea-game/dice-server-js/blob/master/src/db-handler.js) file for any information)
Just push the changes, no need for PRs there until we have a fully functional piece of software
When everything is working I'm going to create a documentation for everything related to HTTP requests and usage.

**Comment by DanVanAtta** [comment]
Before we add Docker in production, I'd like to clarify it's value. Docker for me is nice because you don't have to worry about env differences and you get a base OS. The fundamental problem is that you then don't have to set up your OS env. Although I think that pushes the problem to being able to set up a docker image. If we introduce docker, I'd like to be sure we have an easy way to update the docker image. Overall things need to be easier, Docker is another moving component after-all, needs to be well worth it.

**Comment by DanVanAtta** [comment]
@ssoloff good point on agreement, we feel short though for making the local dev setup easy, it needs to be scripted, one-touch. Having manual setup instructions to set up a DB is "hackery". Fundamentally I think the problem is that we don't have automation for local or production deployment of DB infastructure, (docker only kinda solves that but not fully).
