### ISSUE TITLE
Civil War - Map Bugs

### ISSUE THREAD

**Issue by dboyarsk** [triplea-game/triplea#2723]
### Do you have the exact error text? Please copy/paste if so 
java.lang.IllegalStateException: Wrong number of sea zones for canal (exactly 2 sea zones may have the same canalName):[Mechanicsville Station]
	at games.strategy.triplea.attachments.CanalAttachment.getAllCanalSeaZones(CanalAttachment.java:45)

**Comment by ssoloff** [comment]
@dboyarsk If you have fixes for the map, you can submit a pull request at the repo for the Civil War map (https://github.com/triplea-maps/civil_war).  Feel free to ask for help if you run into any issues submitting your changes.

>  I have unzipped the zip, edited the xml to fix these issues, but when I rezip and try to start the game, I get immediate failures

TripleA supports unzipped maps, which are much easier to edit and test, but it's not as simple as just unzipping the _*-master.zip_ file in your _downloadedMaps_ folder.  If you have a Git client, you can clone the map repo into your _downloadedMaps_ folder and everything should Just Work.  (Note that you should delete the map from the Download Maps window before you do this so you don't get confused between selecting the same-named map from the unzipped folder and the zip file.)  Then you can just edit the files in the cloned folder, as needed, without having to re-zip anything.

**Comment by dboyarsk** [comment]
Thanks for the response. 

I have now successfully fixed the Stalingrad xml file by following the procedure you describe above.  Unfortunately, the Civil War game, when unzipped, has a different folder structure.  After unzipping it, it tells you, 'Map missing civil_war, could not join game.  This game has two scenarios, 'A House Divided' and 'Eastern Campaign'. 
I have tried moving some of the folders around, but still couldn't get past this error.  I can try some other things, but I was wondering if you already know what to do to fix this... 

Thanks,
Don

**Comment by ssoloff** [comment]
@dboyarsk This process worked for me:

1. Download _civil_war-master.zip_ from [GitHub](https://github.com/triplea-maps/civil_war/archive/master.zip).
1. Open the zip file in Explorer and copy the _civil_war-master_ folder that's inside.  (Honestly, it's been such a long time since I used XP, that I don't even remember if you can open zip files from Explorer. 😞)
1. Paste the copied folder into _C:\Documents and Settings\dboyarsk\triplea\downloadedMaps_, where you should replace _dboyarsk_ with your Windows user name.  (If you changed the user maps folder setting within TripleA, you'll need to paste the copied folder into your custom location instead.)
1. Rename the copied folder from _civil_war-master_ to _civil_war_ (i.e. remove the _-master_ suffix).
1. Start TripleA.
1. Click **Select Map**.
1. Select one of the two Civil War maps and click **OK**.
1. Click **Start Local Game** and then click **Play**.

At this point, the Civil War game I selected started successfully.

You should now be able to edit the files under the _C:\Documents and Settings\dboyarsk\triplea\downloadedMaps\civil_war\map_ folder and restart the game to see the changes without having to zip it back up.

**Comment by DanVanAtta** [comment]
bit of a side note, would  be super ideal @ssoloff  if we could remove the need for step "#4: Rename the copied folder from civil_war-master to civil_war (i.e. remove the -master suffix)."

**Comment by ssoloff** [comment]
@DanVanAtta Agreed, but the _truly_ ideal way for a map maker to download and edit a map should be to clone the Git repo. :smile: The time spent learning how to do basic tasks (clone, commit, and push) in a Git GUI client would more than make up for all the nuances of _not_ using Git.

**Comment by dboyarsk** [comment]
Steven,

After renaming the folder to civil_war I was able to run the game.

I think that I have fixed the bugs in the Eastern Campaigns xml file and have also fixed the errors in the Stalingrad xml file.  I will try to get those fixes posted this weekend. I will also try to fix the larger Civil War xml file in the near future.

Thanks for the help!

Don

**Comment by dboyarsk** [comment]
All,
I ran the main Civil War scenario this weekend and it doesn't have any of the issues that the Eastern Campaigns scenario has.  When I get a chance, I'll upload the fixed Eastern Campaign xml file to TripleA.
