### ISSUE TITLE
Air attack problem

### ISSUE THREAD

**Issue by gamer016** [triplea-game/triplea#2814]
### My Operating System:
Apple OS

### Engine version:
1.9.0.0.3307

### Map name and version:
World War II Global 1940 balanced mod 3 with combat move first

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
When another country uses an air attack against my forces, I am prompted to scramble my fighters.  THe prompt flashes on the screen and I can not click on it.

### Do you have the exact error text? Please copy/paste if so:
No

### Instead of this error, what should have happened?
I should be able to click that I want to scamble my aircraft.

**Comment by panther2** [comment]
I remember people noticing this issue some time ago with (now) outdated versions of TripleA.

Issue https://github.com/triplea-game/triplea/issues/1269 seems to indicate that this has been fixed with version 1.9.0.0.3379.

Please install the latest stable version (1.9.0.0.7621) from http://triplea-game.org/download/ and try again.

Please report back. Thank you.

**Comment by ron-murhammer** [comment]
@gamer016 As panther mentions, please try updating to the latest version 1.9.0.0.7621 and see if that resolves the issue. If not then please attach a save game to reproduce the issue.
