### ISSUE TITLE
change log management

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#287]
to manage the change log let's create a branch in the triplea repo called "change_log". On that branch we'll only modify just the change log file. Also rather than doing PRs to update the change log branch, we'll avoid long running changes and do short and sweet pull rebase updates frequently and push any changes immediately (generally after a PR merge). Then when we do a release, to update the change log file we'll do a single merge of the change_log branch into master.

@veqryn , @ron-murhammer , sound good?

**Comment by veqryn** [comment]
Not sure i understand this sentence: `Also rather than doing PRs to update the change log branch, we'll avoid long running changes and do short and sweet pull rebase updates frequently and push any changes immediately (generally after a PR merge)`

I think this is a good idea, and I'd be fine with people just committing directly to that branch (no need for pr's), since it would only be the changelog file.  (Obviously, please try to follow the existing style and granularity.)

**Comment by DanVanAtta** [comment]
@veqryn , to clarify, I was describing the work flow for this branch.

- check out the branch
- do a `git pull --rebase`
- make some changes (~5-10 minutes)
- push those changes

So let's say one is working on an update or feature. One would submit a PR, then after it has been merged to master, somebody would update the change_log branch as well.

**Comment by DanVanAtta** [comment]
Sounds like we have agreement on this branch, I'll go ahead and create it. Please chime in if there are any questions

**Comment by ron-murhammer** [comment]
I'm fine with this.
