### ISSUE TITLE
Use @Nonnull annotation

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#2885]
Follow-up from [this discussion](https://github.com/triplea-game/triplea/pull/2874#discussion_r162793083).

**We currently annotate nullable types with `@Nullable`.  The question is should we annotate non-nullable types with `@Nonnull`?**

The primary argument for using `@Nonnull` is that it allows static analysis tools to provide better results around the usage of `null`.  The primary argument against using `@Nonnull` is that it will effectively require an annotation on every field, method parameter/type, and local variable.

Nullable types should be a rare exception in our codebase, such that `@Nonnull` should be the default.  However, we have so much legacy code that this will obviously not hold true in many cases.

Eclipse supports the concept of "non-null by default."  This can be enforced with a third annotation that is used to indicate that, within a scope (package, class, method), all unannotated types are effectively `@Nonnull`.  I don't know if IntelliJ supports a similar feature, but it would be worth researching because the use of a non-null-by-default annotation would provide the same static analysis benefit with less verbosity in the code.

If IntelliJ doesn't support the third annotation, another possibility is to just configure tools to assume unannotated types are `@Nonnull`, which will probably generate several hundred new warnings.  Then we would add `@Nullable` where needed over time.

**Comment by ron-murhammer** [comment]
I'd probably vote for non-null is the default. That keeps the code cleaner and hopefully at some point its 95% of the code base.

**Comment by DanVanAtta** [comment]
>  the concept of "non-null by default."

This is jsr-305: https://github.com/amaembo/jsr-305/blob/master/ri/src/main/java/javax/annotation/ParametersAreNonnullByDefault.java

Both IntelliJ + Eclipse support it:
- https://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_null_annotations.htm
- https://www.jetbrains.com/help/idea/nullable-and-notnull-annotations.html

In eclipse case looks like there may be some config to turn it on:
> Available annotations
The Eclipse Java compiler can be configured to use three distinct annotation types for its enhanced null analysis (which is disabled by default):


The annotation is for non-null parameters, does not cover fields or return types. For that we can create custom annotations: https://stackoverflow.com/questions/11776302/how-to-indicate-that-member-fields-are-nonnull-by-default

We'd then need to drop in a `package-info.java` file to every package, that file would look like:
```
@ParametersAreNonnullByDefault
@ReturnTypesAreNonNullByDefault
@FieldsAreNonNullByDefault
package games.strategy.util;

import javax.annotation.ParametersAreNonnullByDefault;

import games.strategy.FieldsAreNonNullByDefault;
import games.strategy.ReturnTypesAreNonNullByDefault;
```

There are a lot of nulls in our code base:
```
:~/work/triplea$ find . -name "*java" -type f 2> /dev/null | xargs grep "null" | wc -l
5322
```

We will need to weigh level of effort here vs focusing on removing code, for example I'd much rather see WeakAI removed before we haggle over nullity analysis in that section of the code.

For us to really benefit from non-null parameters/return types and fields, we'll need to annotate what can be null. This can be done automatically in IDE (should not be done by hand).

Though, if we turn on non-null via package-info.java, in this one example we see a warning on two fields:
![warnings](https://user-images.githubusercontent.com/12397753/35257663-81904aba-ffaf-11e7-9b13-89c02cd6a5fa.png)

If we remove the defaults and infer nullity, we see:
![screenshot from 2018-01-22 20-03-14](https://user-images.githubusercontent.com/12397753/35257677-95e1eb86-ffaf-11e7-8ca7-174e5f6d7b53.png)

So in this case the defaults are almost completely wrong. It's okay for any of the fields to be null, and the method returns null as well (and presumably that is handled by any callers). With the default turned on, callers will not be marked correctly as any IDE trusting the annotations will assume a non-null return value (incorrect). This is where the real problem is, most of the time the IDE will be wrong to think there is a non-null return value and we'll have lots of warnings that it is violated. From the first part we'll lose benefit of nullity analysis, we'll use APIs that we think are maybe non-null but do have nullable return types. Secondly, we'll have a lot of work to fix up many APIs so they do not return null or to mark them as nullable.

-----------------

Summing up, I would see four or five tasks that would need to be done here:
- create custom annotation class for not nullable fields and return types
- add gradle plugin to geneate package-info file, modify it to add not null field and return type annotations
- use IDE to auto-generate @Nullable annotations 
- correct the many cases where @Nullable annotations were not generated for methods that can return null either by refactoring or adding a @Nullable annotation
- last make, make sure there are no hidden issues, that we corrected all cases and our uage of reflection or serialization does not mess things up too much  ("what do you mean that was null? it was annotated as non-null! Oh.. the annotation was wrong - we serialize that and so it can be null")

From my position I'm a bit neutral on this, leaning negative. I'd rather see us work to remove legacy code first. If someone was inclined to take this up, we'd just need to be sure we don't just give a false sense of security and that the annotation defaults are made accurate.

**Comment by DanVanAtta** [comment]
I left out the link to the Gradle plugin that generates package-info.java files, here it is: http://stancalau.ro/java_package-info_generator_gradle/

**Comment by DanVanAtta** [comment]
Perhaps doing this incrementally is a viable approach? That would mean hand-dropping the `package-info.java` files and fixing warnings/nullity handling at same time. Once we hit a critical mass we can eventually automate the generation of the `package-info.java` file with the aforementioned gradle plugin.

**Comment by ssoloff** [comment]
> The annotation is for non-null parameters, does not cover fields or return types. For that we can create custom annotations

Note that Eclipse already publishes a jar containing the annotation `@NonNullByDefault`, which can be applied to packages, classes, and methods.

And the one drawback of the JSR 305 annotations is that they were created before Java 8 type annotations were introduced.  So, for example, you can write something like this using the Eclipse annotations but not using the JSR 305 annotations:

```java
final Map<String, @Nullable Object> map = new HashMap<>();
```

> In eclipse case looks like there may be some config to turn it on:

Yes, but for the "non-null by default" case, it only supports one primary annotation.  I don't think it can be configured to recognize the distinction between `@ParametersAreNonnullByDefault`, `@ReturnTypesAreNonNullByDefault`, and `@FieldsAreNonNullByDefault`.  Here's the annotation-based null analysis configuration dialog:

![eclipse-null-analysis](https://user-images.githubusercontent.com/4826349/35691201-d862ac00-0745-11e8-8083-e8d78445be1f.png)

> Perhaps doing this incrementally is a viable approach?

Agreed.  For a codebase this large, it's probably the only reasonable approach.

**Comment by DanVanAtta** [comment]
I may need to fire up my eclipse copy, @ssoloff the jsr 305 annotations cannot be selected in the dialog? Also to confirm, once enabled the nullity warnings show up as a compiler errors, or does the analysis need to be triggered manually?

**Comment by DanVanAtta** [comment]
> I don't think it can be configured to recognize the distinction between @ParametersAreNonnullByDefault, @ReturnTypesAreNonNullByDefault, and @FieldsAreNonNullByDefault

Note that two of those are custom, I would be really surprised if they did not work with eclipse. I'll potentially be able to investigate further tonight.

**Comment by ssoloff** [comment]
@DanVanAtta

> the jsr 305 annotations cannot be selected in the dialog?

Yes, the JSR 305 annotations can be selected in Eclipse with the following caveats:

* JSR 305 `@Nullable` and `@Nonnull` cannot be used as type annotations (whereas Eclipse `@Nullable` and `@NonNull` can).  This is simply because the JSR 305 annotations were written before the `ElementType#TYPE_PARAMETER` and `ElementType#TYPE_USE` values were added as supported annotation targets in Java 8.
* JSR 305 `@ParametersAreNonnullByDefault` can be selected as the "NonNullByDefault" annotation, but Eclipse will interpret it to mean more than just parameters are non-null by default (see below).

> Also to confirm, once enabled the nullity warnings show up as a compiler errors, or does the analysis need to be triggered manually?

Annotation-based null analysis in Eclipse needs to be turned on explicitly.  Whether the violations are reported as errors or warnings (or ignored) is configurable:

![eclipse-null-configuration](https://user-images.githubusercontent.com/4826349/35691916-d1f4f98e-0747-11e8-8bbf-9acde0079c7e.png)

> Note that two of those are custom, I would be really surprised if they did not work with eclipse.

Eclipse can use custom annotations (that's the purpose of the first dialog I captured above).  What I was trying to convey above is that Eclipse can only support a single NonNullByDefault annotation, and that annotation

> sets 'non-null' as default for all elements in a package, type, or method

**Comment by DanVanAtta** [comment]
@ssoloff sorry for late response, picking this issue back up. Is there any configuration that works in both of the major IDEs? Can we use both eclipse and JSR annotations? Does eclipse support annotations for non-null return at all in the end?

**Comment by DanVanAtta** [comment]
@ssoloff is there a problem with using this file:

> We'd then need to drop in a package-info.java file to every package, that file would look like:

```
@ParametersAreNonnullByDefault
@ReturnTypesAreNonNullByDefault
@FieldsAreNonNullByDefault
package games.strategy.util;

import javax.annotation.ParametersAreNonnullByDefault;

import games.strategy.FieldsAreNonNullByDefault;
import games.strategy.ReturnTypesAreNonNullByDefault;
```

> You could use @Nullable and @Nonnull from JSR 305, and @NonNullByDefault from Eclipse

This option: "use @Nullable and @Nonnull from JSR 30"

This is not an IDE war... at same time locking ourselves into eclipse specific configuration makes it one, not acceptable. Intellij supports a good chunk of eclipse, so we can have things that are "eclipse" specific, but we verified that we get universal support.

From a technical point of view, my questions are:
1. Does eclipse support the file described above? If there is no problem we can move forward
2. If not, is there a compatibility mode supported in intellij for the eclipse specific configurations.

**Comment by DanVanAtta** [comment]
Non-technical, implementation roll out.

The project has a long running assumption that everything is nullable. I don't think it's necessarily appropriate to start marking things as nullable until we start actually changing that assumption. Specifically, if we start seeing @Nullable cherry-pick through the code, it does throw surrounding code in question (is it nullable by default, or not?). Unless the surrounding code is updated to be consistent, we're not necessarily doing ourselves a favor.

Said in another way, a bit more directly: for better or worse because of project legacy parameters are nullable by default (along with everything else). What would the plan be to change that? How do we avoid the cherry-picked fixes? What can we do to get to a point where if you start seeing @nullable annotations, you'll get valuable information as opposed to questions about consistency?

I think the answer is probably pretty simple, I'll propse this:
1. we fix any technical problems, find something that works for all major java IDE's
2. drop in package-info.java file by hand one at a time and fix each package each time we do so.

When we move around packages, which we want to do, we may need to drop some package-info.java if the moved code no longer guarantees the annotations. That much of a transition state I think is okay as that woudl be a step to smaller packages where we can more easily drop in the non-null by default package marker.

**Comment by DanVanAtta** [comment]
@ssoloff you seem to be leading the charge on non-null by default. Would you mind checking the `package-info.java` file and let me know if you see any problems with using it? Would changes, if any, would you suggest to the proposed plan?

**Comment by ssoloff** [comment]
@DanVanAtta 

> `@ParametersAreNonnullByDefault`
> `@ReturnTypesAreNonNullByDefault`
> `@FieldsAreNonNullByDefault`
> `package games.strategy.util;`

As I mentioned above, Eclipse only supports a single "non-null-by-default" annotation.  You can use whatever annotation you want, but Eclipse will always apply it to multiple targets within the scope you attach it to.  Eclipse does not support different non-null-by-default annotations for parameters, return values, fields, etc.

I probably haven't explained this very well.  The Eclipse documentation on this feature may be more helpful:

* [Using null annotations](http://help.eclipse.org/oxygen/topic/org.eclipse.jdt.doc.user/tasks/task-using_null_annotations.htm?cp=1_3_9_0)
* [Using null type annotations](http://help.eclipse.org/oxygen/topic/org.eclipse.jdt.doc.user/tasks/task-using_null_type_annotations.htm?cp=1_3_9_1)
* [Using external null annotations](http://help.eclipse.org/oxygen/topic/org.eclipse.jdt.doc.user/tasks/task-using_external_null_annotations.htm?cp=1_3_9_2)

> The project has a long running assumption that everything is nullable.

I'm not sure I'd describe it that way.  I'd probably say the project's default nullability assumption is "figure it out."  By that I mean you usually have to look at the code to see if a parameter or return type can be `null`.  (Sometimes you get lucky, and the Javadocs tell you.)

If the default assumption is that everything is nullable, I would expect code like this:

```java
final PlayerID player = getData().getSequence().getStep().getPlayerId();
// do something with player
```

to instead be written like this:

```java
final GameData data = getData();
if (data != null) {
  final GameSequence sequence = data.getSequence();
  if (sequence != null) {
    final GameStep step = seqeuence.getStep();
    if (step != null) {
      final PlayerID player = step.getPlayerId();
      if (player != null) {
        // do something with player
      }
    }
  }
}
```

But it's usually not. :smile:

> drop in package-info.java file by hand one at a time and fix each package each time we do so

Trying to do one package at a time may be too much to bite off at one time, especially for packages like `attachments` and `delegates`.  Again, the nice thing about Eclipse's `@NonNullByDefault` is that it can be applied at multiple scopes: packages, types, and methods.  So, for example, you could attack one class at a time, and once all classes within a package are properly annotated, remove the `@NonNullByDefault` from each class and add one to the package.

**Comment by DanVanAtta** [comment]
> I'm not sure I'd describe it that way. I'd probably say the project's default nullability assumption is "figure it out." 

Hmm, it is a nuance between return types and parameters. Parameters are pretty frequently nullable, I suspect a good bit more so than parameters. I'd agree it is essentially, 'figure it out' 

> Again, the nice thing about Eclipse's @NonNullByDefault is that it can be applied at multiple scopes: packages, types, and methods.

Is that not also true for the JSR annotations?

> Trying to do one package at a time may be too much to bite off at one time

for large packages, I don't think we are precluded from tackling one class at a time. At same time, we probably should not have such large packages so some of this can be easier after package breakup.

**Comment by DanVanAtta** [comment]
> As I mentioned above, Eclipse only supports a single "non-null-by-default" annotation. You can use whatever annotation you want, but Eclipse will always apply it to multiple targets within the scope you attach it to. Eclipse does not support different non-null-by-default annotations for parameters, return values, fields, etc.

So, does it matter at all if we are using the JSR annotation or eclipse specific? 


> I probably haven't explained this very well. The Eclipse documentation on this feature may be more helpful:
Using null annotations
Using null type annotations
Using external null annotations

Appreciate the link, except for type annotations, the JSR annotations support the checks.

**Comment by ssoloff** [comment]
> > Again, the nice thing about Eclipse's @nonnullbydefault is that it can be applied at multiple scopes: packages, types, and methods.
>
> Is that not also true for the JSR annotations?

Technically, yes, because the JSR annotations do not specify a `@Target` annotation, and so they can be applied anywhere (except type parameters).  However, the Eclipse null analyzer will reject the `@Nonnull` and `@Nullable` annotations everywhere except on a `TYPE_USE` target.  For example, trying to apply `@Nonnull` to a class will not work:

![null-analysis](https://user-images.githubusercontent.com/4826349/36441792-a9051fd2-1641-11e8-9f6b-13e06dced586.png)

---

We seem to be going in circles here a bit.  Would it just be easier to adopt explicit usage of `@Nonnull` and `@Nullable` and not assume a default for now?  When we figure out how to get an appropriate non-null-by-default annotation working in the future, we can retrofit it in and remove the `@Nonnull` annotations.

**Comment by DanVanAtta** [comment]
@ssoloff yeah, sorry for the circles. I'm having trouble understanding what eclipse will understand. I probably should fire up my copy and investigate this in more detail. My current impression is that eclipse does not support the JSR annotations like we would want to, that that package-info.java file will not apply correctly. Is that truly the case? 

If so then we should see if intellij has compatibility for the eclipse specific annotations.

Ultimately we need to agree on two things:
1. how to do this technically. Less agreement here and more understanding what works
2. plan to roll out. I think we are mostly on the same page, but it's important I think at same time to be sure this is not left as a half-done project for years to come.
