### ISSUE TITLE
Remove map feedback feature?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2912]
- it's been broken for some time. Was reported recently: https://github.com/triplea-game/triplea/issues/2896
- feature is low value, not used very often
- feature is misguided even, idea at one time was that map owners would 'watch' a few repo's and each would be self contained. It has not quite worked out that way. For file hosting map repos has worked out okay, but for issue tracking it does not.
- partially broken, some maps have issue queue disabled

----------------

This may be a one-sided debate. It's a really good question though how the overall map feedback process should work. It's pretty clear such a button on the download page is not it : )

**Comment by prastle** [comment]
lol sorry yes kill it

**Comment by ssoloff** [comment]
> some maps have issue queue disabled

Was this just an oversight?  Should such repos have their issue trackers re-enabled?

If all map repos aren't going to have an issue tracker, then I agree this feature should probably be removed.  Or just have it point to the main issue tracker, but that seems kind of redundant since we already have such a feature on the help menu.

**Comment by ron-murhammer** [comment]
Yeah, probably best to just remove it. Even if we had a better way to track/address map feedback, I don't think the download window is really the place for it. As you can't really give feedback before playing a map...
