### ISSUE TITLE
Save Game Compatibility Project

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2913]
Problem: save game with engine version Y, upgrade to next version and sometimes can no longer load the old save.

This issue: discuss, track, coordinate solving this problem

Benefits to solving:
- the only reason remaining for someone to not upgrade their engine is save game compatibility.
- we could do automatic game engine updates
- simpler, players never need to load old games to get things to work, can always just play latest game engine
- dev life happier, we can change more without busting compatibility (or at worst case add some logic to forward convert old saves)

**Comment by DanVanAtta** [comment]
Serialization proxy was a bust, I'm thinking to serialize to a text format such as yaml. Parsers of future engines would be able to parse old versions quite readily and could handle upgrade logic. 

I've trouble to think of too many more other feasible options. With YAML the goal would basically be to convert the game data component objects to be serializable to YAML using something snakeYaml (currently a dependency available to us), or gson.

**Comment by RoiEXLab** [comment]
An Idea: We could let classes implement Externalizable and write the streams using JSON or YAML (which is a superset of JSON since 1.2) manually.
This way only renaming the complete class would break compatibility.
If we don't want that either we need to come up with a savegame system on our own. Something like have every class have a static nested class Implement a custom interface "Saveable" that defines a toJSON/toYAML and fromJSON/fromYAML method which constructs the class based on the data. Figuring out what YAML belongs to what class needs to be captured in a simple map and a property in the YAML.

**Comment by ssoloff** [comment]
Just pointing out that the data format is not the barrier to save game compatibility.  It's the complexity of recreating a domain model object graph from a save game.  A discussion of text vs. binary, YAML vs. JSON, etc. is warm and fuzzy, but it's not going to solve the root cause. :smile:

We need to focus on cleaning up the relationships between the various objects (specifically, circular references).  That, in and of itself, is going to break save game compatibility.  Unfortunately, those problems only became obvious to me as I was actually trying to read a save game and create the corresponding objects.  I'm not sure they would be easy to identify simply by looking at code.

BTW, @RoiEXLab's suggestion to use `Externalizable` instead of `Serializable` might be a good short-term compromise.  It would still support the circular references in the domain model, but, at the same time, allow us to version the format.  That would enable us to make decisions in `readExternal()` such as deciding to read the object's format from the previous version or the current version, etc.  As @RoiEXLab pointed out, `Externalizable` still has the drawback that we're tied to the class names, but if we're breaking compatibility, we can at least move/rename them once to address any current issues we identify.

**Comment by RoiEXLab** [comment]
@ssoloff Well a potential benefit from using JSON or YAML as serialization format would be that we could apply transformations to it before actually deserializing it

**Comment by ssoloff** [comment]
@RoiEXLab That's true; there's plenty of secondary benefits to using such formats.  Sorry if I came across as dismissing the importance of having that discussion.

However, as I said above, deserialization itself _is_ the core problem.  We're going to run into the same issues creating associations between objects during deserialization using the current domain model, regardless of format.
