### ISSUE TITLE
all_platform.zip not very popular on releases, looks like can be dropped from build

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2917]
Release artifact DL counts are available with:
`curl https://api.github.com/repos/triplea-game/triplea/releases/latest | egrep "name|download"`

Windows installer has been downloaded close to 1000 times : )
The all_platforms and jar file have been downloaded in single digits.

There is little demand for the all_platforms.zip, it seems we would benefit to remove the generation of the file. There would be a couple of benefits:
- build script is easier to maintain and modify
- fewer choices on releases page, this is a good thing, makes it easier to find the right choice 

```

     "download_count": 4,
      "browser_download_url": "https://github.com/triplea-game/triplea/releases/download/1.9.0.0.8304/triplea-1.9.0.0.8304-all.jar"
      "name": "triplea-1.9.0.0.8304-all_platforms.zip",
      "download_count": 13,
100 24039        "browser_download_url": "https://github.com/triplea-game/triplea/releases/download/1.9.0.0.8304/triplea-1.9.0.0.8304-all_platforms.zip"
100 24039    0         "name": "triplea-1.9.0.0.8304-server.zip",
  0  53389      "download_count": 2,
      0 --:-      "browser_download_url": "https://github.com/triplea-game/triplea/releases/download/1.9.0.0.8304/triplea-1.9.0.0.8304-server.zip"
-:-- --:--      "name": "TripleA_1.9.0.0.8304_macos.dmg",
:-- --:--:-- 53420
      "download_count": 215,
      "browser_download_url": "https://github.com/triplea-game/triplea/releases/download/1.9.0.0.8304/TripleA_1.9.0.0.8304_macos.dmg"
      "name": "TripleA_1.9.0.0.8304_unix.sh",
      "download_count": 90,
      "browser_download_url": "https://github.com/triplea-game/triplea/releases/download/1.9.0.0.8304/TripleA_1.9.0.0.8304_unix.sh"
      "name": "TripleA_1.9.0.0.8304_windows-32bit.exe",
      "download_count": 201,
      "browser_download_url": "https://github.com/triplea-game/triplea/releases/download/1.9.0.0.8304/TripleA_1.9.0.0.8304_windows-32bit.exe"
      "name": "TripleA_1.9.0.0.8304_windows-64bit.exe",
      "download_count": 965,
      "browser_download_url": "https://github.com/triplea-game/triplea/releases/download/1.9.0.0.8304/TripleA_1.9.0.0.8
```

**Comment by ssoloff** [comment]
I'm all for removing the standalone jar file.

However, I find the portable build very useful for reproducing issues in different releases.  I can easily download, unzip, run a build, and uninstall fairly quickly without having to go through the installer.  I don't typically use the portable build for stable releases, but rather for pre-release testing.  For example, on three different occasions in Q4 of last year, I had to bisect to track down a regression, and it would have been a pain to be required to use the installer, when I can instead run a a four-line bash script to automate installation/uninstallation of multiple versions.  (I find using the IDE to run code during a bisect to be annoying because there may be Gradle buildscript changes that have to be resynced [that's not an automatic thing in Eclipse], which may take 30-40 seconds vs. a ~13 second download. :smile:)

I suppose I could use install4j's unattended installation mode, but I'm always concerned about undesirable registry-like changes install4j may make to my system (e.g. there was an issue raised a few months ago about install4j creating a slew of new registry keys that don't get removed upon uninstallation; I believe this ended up being a known install4j bug).

There's 11 lines in the Gradle script used to generate the portable build, so I'm not sure that removing that will simplify the 350-line script much.  In order to help users find the right file to download, we could consider renaming some files to make their purpose clearer.  For example, renaming _-all_platforms.zip_ to _-portable.zip_ and _-server.zip_ to _-headless.zip_.

**Comment by DanVanAtta** [comment]
> I'm all for removing the standalone jar file.

Sweet, let's make it so. 

Given a use-case for portable, I can agree to keep that  around.
