### ISSUE TITLE
Mute anonymous lobby users

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#2923]
Proposed as part of a larger feature request about [anonymous lobby users](https://forums.triplea-game.org/post/6260).

In a nutshell, anonymous users should not be able to chat in the lobby.  A quick prototype shows that this appears to be possible with a purely server-side change that does not break compatibility with older clients.  Implementation details to be discussed in this issue or in an associated PR.

**Comment by RoiEXLab** [comment]
Just noting, that IMO the server should keep track of anonymous users in memory (no Database, just a Set of users) and just check when a user tries to post if this user is anonymous, and reply with an appropriate message.
If that's possible without breaking compatibility.
Ideally we'd store a set of user objects with details of all users to have a consistent scheme to check user data in general, but that's a much bigger task.

**Comment by DanVanAtta** [comment]
How is this going to help exactly? Is this theater or actually effective at reducing trolling? I played one game where I created 72 email accounts, it was common in that game - our trolls would do exactly the same. Why is registration any deterrent?

I'll note I played as an anonymous user for about 8 years before switching to a registered account, and that was *only* because I was made mod. It is getting feasible for us to require accounts with the 'remember password' feature :+1: , but at the same time let's do something because it is effective and not because it is feel good. I'm most concerned that a poor UX for new players can increase what is already a potentially high abandonment rate (download counts far exceed player activity, this has suggested high abandonment rates and/or just a lots of bot downloads). 

Since it's trivial to create a new email account, I'd like to see burden of proof be that this will not actually cause new users to abandon, or good reason why would be an effective trolling deterrent. I suspect it would be just as effective to mark the anonymous accounts in chat, or not allow those players to pick a user name maybe.

Accounts are a sensitive topic to some as TripleA used to require 3, maybe 4 of them. I'll quote one of our players posting in forum just last week: "first off, it's too hard to file bug reports, I don' wanna have to make a whole github account just to file bug reports, so i'm posting here. I hate the proliferation of account needs for everything."

Given that this is someone that *plays* the game, what kind of reaction would we get from someone who was like-minded but only just trying the game? Getting new players to not abandon is more important than a really questionable tool against trolls. I am all for reducing trolling, I could be convinced otherwise, but I don't see a case how this is effective though.

**Comment by DanVanAtta** [comment]
> Just noting, that IMO the server should keep track of anonymous users in memory (no Database, just a Set of users) and just check when a user tries to post if this user is anonymous, and reply with an appropriate message.

I've been thinking of anonymous user tracking *in* DB. In part this would encourage, challenge, and verify that mac is a good way to track players. If player identities shift too much then we'll know we actually have deeper problems, like "mac" for user bans, and we'll need to solve them. Otherwise we'll profit by not being reliant on email addresses for user identification. (we'll still tie email address to users, but it'll be a many to one or one to one between email and mac)

**Comment by prastle** [comment]
I am curious if we have any way of knowing how many Anon users use the Anon service?

**Comment by prastle** [comment]
I personally don't think its worth closing since unless i am mistaken (10 new names a day on a busy day in two hrs) anon is being abused.  Just my two cents but up to you.

**Comment by ssoloff** [comment]
@DanVanAtta I'm ok with closing it for now.  I opened it based on mod requests, and I'm pretty sure they know they have a problem with anonymous users abusing chat.  However, I'm all for backing up feelings with facts, and now that we are prepared to capture this information, we should be able to do so relatively quickly.  (I'm going to open a new issue soon to discuss upgrading the lobby to get these new features into production.)
