### ISSUE TITLE
AI pause only between movement and not combats

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#298]
From: http://tripleadev.1671093.n2.nabble.com/Slow-Computer-Reaction-Times-tp7590362p7590365.html

"I would just suggest not having the AI Pause Duration between battle rounds, but only between movements"

**Comment by ron-murhammer** [comment]
@DanVanAtta - So that's easy to remove. Here is the line: https://github.com/triplea-game/triplea/blob/master/src/games/strategy/triplea/ai/AbstractAI.java#L395

If you remove that pause that means that battles essentially happen instantly though unless the AI needs to consider a close retreat. Personally I'd rather them just happen instantly but not sure everyone would agree.

**Comment by DanVanAtta** [comment]
Sourceforge post to get some community feedback on the topic of no pause between battles, or do a fraction of the "ai pause duration": http://tripleadev.1671093.n2.nabble.com/Default-quot-AI-Pause-Duration-quot-td7590442.html

My vote is as well no pause between battles, or maybe have the pause be 20% the value of the AI pause duration, so it would be very brief at leas.

**Comment by ron-murhammer** [comment]
@DanVanAtta - Didn't get much feedback to change this. I think we can close this as we have plenty other issues to address.
