### ISSUE TITLE
Continuous Integration Process

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3]
I'd like us to agree on a continuous integration process and to document it on the github wiki.

Definition: continuous integration means the work of multiple developers is integrated together on a short iteration cycle. Meaning, merge conflicts that come up are small and not so frequent.

Proposal: simply use master branch for integration. Pull requests will add new code, "git pull --rebase" to pull down remote code and integrate it locally.

**Comment by ron-murhammer** [comment]
Yep. Everyone should fork the repo and submit pull requests for Veqyrn and I to review for now.

**Comment by ron-murhammer** [comment]
I'll add one more important point which is please make small commits that are properly commented. Its much easier to review small commits that make it obvious what they are doing rather than huge commits that make lots of changes. It also allows us to accept changes at a finer grain rather than having to reject a large commit because of an issue with a small part of it. 

This is especially important since there are only 2 of us reviewing pull requests right now and Veqryn has been pretty busy recently.

**Comment by DanVanAtta** [comment]
@ron-murhammer I want to avoid confusion and be clear about one point. The extra branches are not necessarily the forks of the repo. The master branch of the triplea repo should always move forward and be accepting new updates. This is our integration branch. It allows developers to integrate with each other. IE: I push to master and pull to it, you do the same, in this way we integrate with each other. 
The alternative is that we both work on our own forks, then eventually we both merge into master, this represents a large one-off merge, this is not continuous integration.

So to be clear:
- triplea master is continous integration branch, all pull requests go to it
- triplea master periodically has a branch cut for stabilization of release

Preferences and consensus for a pull request need to be achieved, I suggest a new issue for that, or a wiki page with things you would like to see.

**Comment by DanVanAtta** [comment]
Closing, at some point maybe later today I'll try to document this on the wiki. The integration+release process I think should be documented somewhere, probably there.
