### ISSUE TITLE
Why has the UI buttons changed?

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#3039]
I noticed that the latest pre-release suddenly has a new version of the standard substanceGraphite UI. Buttons are now suddenly outlined with white. To me this seems to disrupt my eyes ability to focus on the text. It’s simply harder to quickly recognize the letters and read the text.

Look at picture. **Left is old stable release** / **right is new pre-release**.

Also, as you can see, the new version of the substanceGraphite UI messes up the tabs. Notice that one cannot disticuish the tabs from each other, abnd the new version has an unwanted spacing all around the window. Very noticeable just left of the “AI” tab.

![oldnew](https://user-images.githubusercontent.com/15268177/36392644-90fdb74a-15ac-11e8-9728-2d8134bbcd4e.png)

**Comment by ssoloff** [comment]
Just FYI, the change in Substance appearance has been present for almost two months: https://github.com/triplea-game/triplea/pull/2717#issuecomment-353749348.  (BTW, I don't like the button borders either, but have found SubstanceTwilight to be a good compromise.)

> the new version has an unwanted spacing all around the window

We can't blame that one on the Substance change. :smile:  That was a purposeful update made in #2952 to improve the overall layout of the Settings window.  Some L&Fs actually draw a border around the tab content, so that having a standard margin around the tab container is helpful.  For example:

![settings-metal](https://user-images.githubusercontent.com/4826349/36393143-574ad936-157c-11e8-968a-4a1fa53b574e.png)

**Comment by prastle** [comment]
Ya @FrostionAAA  I was going to say substance graphite should be default its what i use  👍

**Comment by FrostionAAA** [comment]
@prastle I think substance graphite is the default, at least it seems so when I press "Reset to default"
@ssoloff I don’t know what to say, besides that TripleA could use a new UI. I hope that this is still on the table :-)

**Comment by prastle** [comment]
@FrostionAAA  they have been working on it.  I do agree it's a little off now.

**Comment by prastle** [comment]
But the new engine settings etc are awesome! :)

**Comment by ssoloff** [comment]
@FrostionAAA I believe both @DanVanAtta and @RoiEXLab are working on two separate efforts to improve the UI.

**Comment by RoiEXLab** [comment]
@FrostionAAA 
@Heppisorus and myself are working on a long term UI overhaul, I didn't do too much the last couple of weeks, but I try to continue with this project soon.
You might want to read https://forums.triplea-game.org/topic/464/taking-your-suggestions-for-a-new-ui/145 if you're interested in more details.

**Comment by ssoloff** [comment]
@FrostionAAA So reverting to the old SubstanceGraphite L&F is probably off the table because that library is no longer supported (which was the impetus for upgrading to the latest version in the first place).

With respect to the Settings window, are there any actionable layout changes you'd like us to consider?  Otherwise, I'd suggest we close this issue.
