### ISSUE TITLE
Cloud file storage for save games

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#306]
Feature:  be able to save the game to a "cloud"

Allows a person to save a game on one computer and pick up more easily on a second.  See #284 for some background discussion.

**Comment by djensen47** [comment]
I'm in the process of migrating Axis & Allies .org forums from SMF to NodeBB. After I migrate, TripleA cease to work with the forums. :disappointed: 

As part of this process, I would like to create an API endpoint for uploading save games. Then, when TripleA is integrated w/the new forums, all that will be needed is to post a link to the file instead of attaching the file itself. 

Before we get into the weeds on how to do this, any thoughts?

**Comment by DanVanAtta** [comment]
I was thinking about trying to use github in some manner to accomplish the same. Would it be possible to allow github credentials to be used in that API @djensen47? I'll also be hanging out on gitter a bit tonight @djensen47 to chat more.

**Comment by djensen47** [comment]
I don't think Github would be advisable (until they start rolling out their cloud storage services if/when that happens).

So what I'm offering is essentially a file sharing end point specifically for TripleA.

If you want to allow people to _bring their own_ file sharing, then we should integrate with the following:

- Dropbox
- Google Drive
- Microsoft OneDrive

iCloud is only for Mac so I would advise against that.

**Comment by ron-murhammer** [comment]
@djensen47 So after the forum migration PBF won't work with A&A.org at all? That is a pretty serious issue I think as a large portion of the A&A.org community uses PBF. I actually don't think cloud is the best solution since keeping all final saves for PBF games would be preferred. I think having a way to mark PBF game threads complete that removes all attachments but the final ones would be better.

**Comment by djensen47** [comment]
Yeah, I decided to poll the community and it seems they like having the
save games available to download for posterity.

One idea would be to "replace" existing game files with new ones. I'm not
sure that would work without allowing just anyone to replace existing
files. We could allow permissions for certain users to change files but
that seems overly complicated.

I'm open to other ideas. I'll also brainstorm ideas in the Plugin
Developers forum at community.nodebb.org

**Comment by DanVanAtta** [comment]
We need some concrete ideas on how to implement this. Will re-open if anyone has good suggestions.

**Comment by djensen47** [comment]
It looks like the community has spoken and they want the files on the forums. I'd like to figure out some way to make this work better than in the past. Maybe replace existing files or something like that.

**Comment by DanVanAtta** [comment]
I'm not very familiar with the PBF API. Is it something that the forum can control, or do we need to change the code to get it to keep only the last file? I'd opt for keeping the last 3 in case there is upload corruption.

**Comment by djensen47** [comment]
I'll have to look into it. It'll be be the NodeBB API which is not very well documented.

**Comment by DanVanAtta** [comment]
Closing, not terribly actionable.. Please re-open if there is more to discuss.

**Comment by djensen47** [comment]
Agreed. My new strategy is to just use block storage or S3 to store the uploaded files. The cost isn't terrible,
