### ISSUE TITLE
Remove LinkedIntegerMap

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#3122]
Based on comments in #3118 

So I'd be interested in thoughts on performance impact of LinkedHashMap vs HashMap. If you query the usage of LinkedIntegerMap and IntegerMap in the code base, there are only 24 references to LinkedIntegerMap while there are 957 references to IntegerMap. I have a pretty strong feeling that a good portion of the IntegerMap ones should be using an ordered key set (essentially anything that is reading from the XML or used for UI display as we don't want inconsistent ordering in those cases). My preference would be to consider just removing LinkedIntegerMap when we do an incompatible release. I think that is probably the easiest way forward unless we feel the performance considerations are that impactful.

If there are performance concerns, the alternative would be going through the all the usages to see when we should use unordered vs ordered.

**Comment by DanVanAtta** [comment]
My first thoughts are that we're unlikely to see any data structures large enough where it's a concern. It should be nano-second time to go through in-memory values, a few versus a dozen nanos is likely not going to dominate. I would suggest we first go with what is simplest unless we have some performance numbers to tell us otherwise.
