### ISSUE TITLE
Github +  Forum Discussions

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3170]
There is a long held desire to consolidate communication and involve the community.  Any thoughts on how to cleanly split the two if we start moving development discussion to forums? My thinking is we'll use Github issues as more of a pure task and bug tracker.

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah, that I think would be best. I've already moved most of my discussions to the forum so that its easier to get feedback and interaction with the community. I think github issues are good as a bug tracker, tasks, and technical discussions. But anything that is a feature or enhancement fits better on the forum IMO.

**Comment by DanVanAtta** [comment]
I'm noticing the duplicate convo's, I think I'm just a bit late to get behind the swing of things : )

**Comment by DanVanAtta** [comment]
I created a 'Game Engine' topic in forums: https://forums.triplea-game.org/category/48/game-engine

Start of a migration : )

**Comment by ssoloff** [comment]
So, I'm confused.

@DanVanAtta stated: 

> if we start moving development discussion to forums

@ron-murhammer stated:

> I think github issues are good as ... technical discussions.

Is the gist of this issue to agree on moving technical discussions to the forum, as well?  I thought we discussed this a few months ago, and we all agreed to keep technical discussions on GitHub. :confused: 

Regardless, I don't have any objection to moving technical discussions to the forum if that's what the team thinks is best.  However, I feel like I need to schedule a memory loss test with my GP given all the resurrected discussions lately. :smile:

**Comment by DanVanAtta** [comment]
>  However, I feel like I need to schedule a memory loss test with my GP given all the resurrected discussions lately. smile

Heh, probably should be me going in for memory loss, some items I truly did not remember. But... sorry, my personal style is to revisit items frequently in small iterations. When things are not working well I do like to bring them up fresh for discussion.

-----------

Part of it might be context miss too. In some respect this project is still new to github in some ways. In other ways we hit a maturity spike.

**Comment by DanVanAtta** [comment]
It probably makes sense that topics that relate to github only would be on github. Admin tasks are likely to remain as well. I think in some ways maybe our usage will not change that much except 'discussion' will move to forums.

**Comment by RoiEXLab** [comment]
I'm feeling mixed on this, but I'd go with whatever you choose 🤷‍♂️

**Comment by beelee1** [comment]
You should probably keep the technical stuff here. Could provide a link at the forum for those that want to follow. 

You might get (even well intentioned ) comments that will distract from what you want to do.

Imo : )

**Comment by Cernelius** [comment]
I believe it is a good thing to move all discussions, also about the game engine, to the forum, as this would help breaking the tendency of creating two separated communities, with the developers on one side and the rest on the other (and, for example, the developers would just not even notice the feature requests or what is going on in the forum).

Otherwise the risk is that you have GitHub, where the developers read stuff, and a forum ghetto where no developers read anything going on, even if it might be of interest to them. For some reasons this brings memories.

The main drawback about this is that you drown the gaming community with a bunch of techtalk most don't want or care to see, and I think that's why we used to have a game forum and a developer forum, additionally to the SourceForge bug/feature tracker, but, anyways, most talking is already about tech stuff.

On this line, I think it would make even more sense to move all the bug reports that are map (not engine) bugs only, meaning closing these topics and reopening them in a "Maps Bugs" section in the forum:

https://github.com/triplea-game/triplea/issues/3160
https://github.com/triplea-game/triplea/issues/1331

It really makes no sense that map-only bugs are tracked in the place that is mainly about the engine, and anyways the developer forum is the right place to track such thing, as it was done in the past.

Of course, this is up to you, because, then, once ascertained that a bug opened here is not engine related, you would have to close the issue and tell to reopen it in the developer forum (that is how it worked in past, as well).

Ideally, all bugs related to a map should be reported in the main thread of that map, but, with the move from the old forum, most maps don't have referring threads anymore. On this regard, maybe you should decide if map bugs should be reported in the main map thread or in stand alone threads, and stick such instructions in the same place where, instead, you would tell to report engine bugs in here.

Of course, most users may not be able to discriminate between engine and map bugs, so this would imply telling them to post in forum (this would make bug reporting easier for everyone, as well), if they are not sure, then opening an issue in here once it is determined the bug reported is engine, not map, dependant (so, this may be a bit of a work more moving the bugs from forum to here, but this can also be made by other community members, not necessarily engine developers).

**Comment by DanVanAtta** [comment]
@Cernelius good feedback. We still want Github for task tracking as you can close and assign issues. 

----------------

First, I've noticed we are good about tackling new items as they come in, that is perfect and we should continue to do that (good work!).

I've noticed we have a steady state long tail to the github issue queue of open items. We're hovering around 90'ish, and the bottom 60 are generally hanging out ignored. That setup is effectively a forums, temporal ordering with bottom of list always open and ignored. How can we fix this? How can we get the github issue queue to be just one page?

**Comment by DanVanAtta** [comment]
My answer is offload discussions to forums, they belong there anyways for community consolidation and feedback : )

Second part I would suggest we mark anything older than 6 months as archived and close from the list. Maybe even one month. Basically we set an SLA for fixing non-critical problems, and try to avoid archiving. If something gets that old, it slipped, it's okay, and we admit some small defeat and archive+close it.

**Comment by prastle** [comment]
@DanVanAtta Did you mean 6 months old and archived on the forum and closed or here?

**Comment by DanVanAtta** [comment]
here, essentially bugs that old would fall off the active queue.

**Comment by DanVanAtta** [comment]
The 'game engine' category on forum was not a success. The one useful topic of was moved to 'feature requests and ideas'.

I think this means that we keep msot development conversation on github; but discuss updates to the game play and features on forums 'feature requests and ideas' https://forums.triplea-game.org/category/42/feature-requests-ideas

**Comment by prastle** [comment]
@DanVanAtta  Oki Doki.  Did you notice the new Bug Topic does that work for you?

**Comment by ron-murhammer** [comment]
@DanVanAtta Agree. I don't think having 'developer'/'engine' conversations on the forum is helpful. I think keeping technical conversations in github issues is easier. I think the key is focusing on the end user population for github being developers (anything technical in nature) and the forum being focused on the community (anything less technical in nature).

**Comment by Cernelius** [comment]
As long as the developers always discuss in forum (rather than in GitHub) whatever things changing default behaviours or available options for the users / makers. Otherwise, it is not really fun following all tech stuff in GitHub in search of something that might.

For example, I believe the decision of removing the ability to set the ram in game (via Engine Preferences) should have been discussed / reported in forum (less important now that you have increased to 2 GB, but just talking in general).

Kind of strange, then, having two discussions going on at the same time in GitHub and in forum, like when the matter was to enforce some NCM limits, and other cases, but your choice.

**Comment by Cernelius** [comment]
In my opinion, and I believe this was about the old way (even tho a lot was actually done with no discussions at all, when the developer was only 1), discussions where always kept in forum and, once something was agreed that it was going to be done, a ticket was opened about doing it, specifically (so, a single discussion could have resulted in a bunch of tickets).
I cannot recall a single sourceforge ticket that resembled anything like a general discussion, and that seemed logical enough to me.
But I see strongly technical discussions feel a bit awkward in forum, when nobody but the developers can really understand what's even being said. And in the moment there is a single forum, instead of a gaming forum and a developer forum, like in the past, the akwardness increases.
But I still think all discussions should stay in forum, as otherwise you have to decide if this or that discussion should go in forum each time, and you end up with two discussions going on at the same time, both in GitHub and in forum, which is really not helpful.
For example:
@panther said in [No unit \- except air units \- should be allowed to move during both CM and NCM during the same turn](https://forums.triplea-game.org/topic/301/no-unit-except-air-units-should-be-allowed-to-move-during-both-cm-and-ncm-during-the-same-turn/13?page=1):
> I hope you understand that I am not going to duplicate my Github-statements again. Please read through the respective issue(s) created there if interested.

That thing was made in "Help & Questions". Probably it would fit better as "TripleA Development" or "Feature Discussions".

Also, having feature requests in forum and not discussions is really strange, as, obviously, discussions are more of a forum thing that feature requests. In the past, you would have discussed in forum, and, then, made a relatively concise feature request ticket.

**Comment by Cernelius** [comment]
To be clear, when in the past we had a gaming forum and a developer forum, it seemed obvious development discussions were for the forum (that was the name of the forum itself!).
Now that there is a single forum, I'm not so sure, as drowning users with techtalk they don't care to see is a drawback, but the new forum is already mostly about mapmaking talking, I guess most users are not following, either.
But as a person interested in mapmaking I can only make guesses about what not-mapmaker users (the vast majority) prefers, also since we don't get so many of those using the forum to talk about the game, like, instead, it happens in https://www.axisandallies.org/.
The more the techtalk in the forum, the more users not interested in it are likely to stay away from the forum, not seeing topics they are interested in following, I tend to think (but it's just a guess).

**Comment by Cernelius** [comment]
This is an example of a topic that would fit better in a "TripleA Development Discussions" section, rather than in Announcements, and it seems reasonable to keep in forum, rather than in a tracker:

https://forums.triplea-game.org/topic/464/taking-your-suggestions-for-a-new-ui

I think that one should have been moved in the new development / discussions section.
I'm not sure why initially there was a preference for discussing in forum, and then, all of a sudden, "the 'game engine' category on forum was not a success", before it practically started, why? Only reason I see is to limit the amount of techtalk in forum, to keep it more gaming focused (since now the developer and the games forum are one), but in the moment we have loads of mapmaking etc. anyways, I don't think the regular users really feel a difference, between some discussing the skin of a map and some discussing how the program should look.
