### ISSUE TITLE
amphibous attack doesn't work corectly 

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#3225]
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

Not really. Can post a save

### Any additional information that may help

hmm.... don't no how to do save game. did it at the triplea site. Git is hard to understand

**Comment by beelee1** [comment]
```fuck it`

**Comment by ssoloff** [comment]
@beelee1 On GitHub, you need to zip your save game first.  On Linux, you can try using your window manager's file browser and right-click the save game file.  In most cases, there will be a command on the context menu named **Compress...** or something like that.  Alternatively, you can open a terminal and use the `zip` command:

```
$ zip my_save_game_to_post.zip <path/to/save_game.tsvg>
```

where you need to replace `<path/to/save_game.tsvg>` with the path to the save game you want to post.  The `my_save_game_to_post.zip` file will be created in the current directory, and that's what you want to attach.

Then you can attach it to this issue either by dragging & dropping it in the comment box, or by clicking the link at the bottom of the comment box that says **selecting them**, navigating to the folder containing the file, and selecting it.

**Comment by beelee1** [comment]
TY

**Comment by panther2** [comment]
I have loaded the provided savegame.
TripleA then downloaded a map called "global_40_house_rules", using a "Global 40 House Rules with Canada"-XML.

I have found the issue in Japan 11. During Combat Move two Japanses units are unloaded to US-owned Wake. For any reason during Combat Phase this does neither initiate a battle in Wake, nor does Japan take Wake.

What should happen is a "battle" during Japanese combat phase indicating

```
Battle in Wake Island
Japanese take Wake Island from Americans
Recording Battle Statistics
```

All of this does not happen.

I veryfied with the "original" Global 40 map, that the procedure works correctly there.

That makes me think that this issue is most likely a map issue related to that special house rule map.

**Comment by beelee1** [comment]
Thanks for looking at it panther. Not sure why it does that. The unit will take infrastructure on land ok but maybe it being an Attack 0 unit makes it act differently on sea for some reason ? Idk. I actually have another Attack 0 unit. I'll try and replicate with that.

**Comment by beelee1** [comment]
yea idk why it did it. Same game, same move and it worked correctly the next rd. Oh well, it will remain unknown : )
