### ISSUE TITLE
Aircraft movement during “Move air units to carriers”

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#3305]
### Engine version
1.9.0.0.9708

### Issue
It seems that when I place a carrier, and the “Move existing fighters to new carriers” is true, then I am able to move more carrierCost out to sea than the placed carrier unit has carrierCapacity (Like in the pictures where I move 6 carrierCost to a 3 carrierCapacity carrier). This results in a warning after all placement is done. Here I can then redo the placements.

![unavngivet](https://user-images.githubusercontent.com/15268177/37733994-2926c4e4-2d4a-11e8-85ce-063c848365b3.png)
![unavngivet2](https://user-images.githubusercontent.com/15268177/37734003-2c793938-2d4a-11e8-89a1-0c7cb2c31cb9.png)

1.	Could this be changed so that it was only possible to move a carrierCost number that was able to land? Or at least use the system that is used during “Produce fighters on carriers”, meaning that a warning pops up immediately after placing too many fighters, not after all placement is done?
2.	It seems that the “Move existing fighters to new carriers” only allow fighters to move from a SINGLE territory with a factory unit. Could this change to all adjacent territories, or all adjacent territories with factories? (If factory presence is a must to move, why is it a must?)

**Comment by ron-murhammer** [comment]
@FrostionAAA Yeah, this is a known limitation. I personally don't plan to enhance this as I think “Move existing fighters to new carriers” is really an outdated property.

**Comment by DanVanAtta** [comment]
@ron-murhammer is there a different property replacing "Move existing fighters to new carriers”? If so, will does the replacement fix this or make it easier to fix?

**Comment by Cernelius** [comment]
>It seems that the “Move existing fighters to new carriers” only allow fighters to move from a SINGLE territory with a factory unit. Could this change to all adjacent territories, or all adjacent territories with factories? (If factory presence is a must to move, why is it a must?)

I'm unclear what you mean/want here. By rules, air units (regardless of ownership) redeploy to carriers only from the territory that placed the carrier. So, if you mean that territory A produces the carrier and you redeploy fighters from territory A and B on that new carrier, that would be illegal: you can only redeploy from A. If a same sea zone is adjacent to 2 territories with factories, you should be able to decide whence the carrier is being placed, then you can redeploy fighters only from there, for that carrier on that phase.

Or you mean something else?

**Comment by Cernelius** [comment]
Personally I don't have a good opinion of any ways fighter-carrier placement is handled in the various rulesets, but I don't want to digress with opinions that I doubt would be of interest.

Pasting this from the lobby (anyone could have read it):
>(21.59.44) ekkolodd:  I have a rule question
(22.00.36) DanD:  I'll try to answer it
Alexar4 has left
(22.00.55) ekkolodd:  talking to mod
Winter_Warrior13 has left
(22.01.16) DanD:  I used to be a mod
(22.01.32) DanD:  but then I married
(22.01.54) DanD:  can't be both
darquan has left
(22.03.21) ekkolodd:  mkey, I was wondering about carrier rules in nwo: is it possible to build carrier in one area and place air from another area on the carrier? I can't find any rule that says that you can.
(22.03.58) ekkolodd:  but some player tried this against me and ragequit when I told him I was unsure about his move
(22.04.11) Dany:  did system allowed it?
(22.04.18) Dany:  or he had to edit the move?
(22.04.36) ekkolodd:  the system did allow it
(22.04.41) ekkolodd:  but I think its a bug
riverrat has joined
MSM has joined
Leatherneckinlv has joined
(22.05.32) DanD:  As long as the planes have a carrier to land on why does it matter where it came from?
(22.05.40) ekkolodd:  yeah
(22.05.45) Cernel:  hey ekkolodd, mods are not actually supposed to be any kind of official rule reference
(22.05.52) ekkolodd:  because the air did not have movevemnt to land where he build the carrier
(22.06.05) ekkolodd:  I was asking epinikon, he knows the game
(22.06.13) Cernel:  but to answer your question, for that NWO follow Revised rules; no exception regarding that aspect
(22.07.05) DanD:  do you mean restriction?
jesperbp has left
(22.07.21) Cernel:  that means only air from the territory that it is placing the carrier can move to the carrier
(22.07.34) ekkolodd:  yeah, that was also what I have read
(22.07.49) Cernel:  what the engine does doesn't matter
(22.08.24) ekkolodd:  yeah, just got a bit unsure if I had missed something when the engine allowed it
(22.08.25) Cernel:  epinikion probably has sound off; since he says he's watching pay-per-view
Alexar4 has joined
(22.09.09) Cernel:  uhm, what did the engine allow? to move a fighter from another therritory than the one that placed the carrier? I don't think so
(22.09.28) ekkolodd:  well, it was 2 factories that he could build units
Alexar4 has left
(22.09.54) Cernel:  right, the engine doesn't allow you to choose which one; so you need to edit that as you intend to
(22.10.11) Dany:  or you fill up one factory with inf
Alexar4 has joined
(22.10.17) Dany:  and then place the carrier
(22.10.24) Cernel:  but I'm fairly sure that the territory whence the fighter redeployed was the one autoselected for placing the carrier
(22.10.26) Dany:  and undo the inf placement iff you want something else
Winter_Warrior13 has joined
(22.10.48) ekkolodd:  y

**Comment by FrostionAAA** [comment]
@Cernel If the A&A rules originally states that “Move existing fighters to new carriers” is only possible from the same territory that also produced the carrier, or if any engine changes connected to players choosing factory when placing units is to be handled elsewhere, then the part 2 of my original issue/suggestion should just be ignored.

But I still think part 1 could be addressed, about the pretty late occurring notification about to many placed aircraft.
