### ISSUE TITLE
Bots are very flaky / not stable / crashing, requiring daily maintenance

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3413]
Tracking ticket to document what we discover with bots. 
@RoiEXLab @ssoloff @ron-murhammer please dig in as you can...

@prastle is reporting that bots are crashing pretty frequently, hourly basis, application restarts are needed daily and if not more frequently.

**Comment by prastle** [comment]
No complaints lately.  I believe they are fixed @DanVanAtta  @RoiEXLab .  Thanks

**Comment by prastle** [comment]
401 bot dropped out today.  Remote shutdown with toolbox got it to restart by the chron job.   Admin login to bot is still not working correctly. @RoiEXLab

**Comment by RoiEXLab** [comment]
@prastle it's working for me without any problems.
Does it still ask for a password, or is there a problem with the login process itself? 
PM me on the forum or Gitter to avoid cluttering this issue.

**Comment by prastle** [comment]
Perhaps we should clarify that the bots are 01-04 all bot servers and not 402 as an example in the document it bot says bot number.  since ls and up arrow no longer work no one has any idea.  They just use the bot number in the lobby.  Also since it is just me resetting them now that I know of.  I can only say I reset two today.  Ty for clarifying @RoiEXLab  in your pm.

**Comment by RoiEXLab** [comment]
@prastle Great to hear everything is working for you 👍

**Comment by prastle** [comment]
Sad to hear no one else and docs are wrong.  But yes it can be rewritten.
