### ISSUE TITLE
Bot / Lobby should be able to survive a system restart

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3414]
This is a task tracking ticket, we need to have the bot/lobby servers to be able to survive a system restart and boot back up cleanly without by-hand intervention.

**Comment by RoiEXLab** [comment]
Problem 1: https://github.com/triplea-game/infrastructure/issues/42


Problem 2: network configuration issue, similar to the lobby issue a while back, the ipv4 network interface didn't start due to an invalid line in the startup script.
Hard to track down the root cause, might be related to uninstalling or updating sendmail? Details in #3409

**Comment by DanVanAtta** [comment]
Cool, sounds like we're close to having this resolved. We should confirm that this is the fixed by doing a test restart and verifying things come up well.

**Comment by DanVanAtta** [comment]
@RoiEXLab any idea if we have this fixed?

**Comment by RoiEXLab** [comment]
I'm pretty sure the lobby does automatically start itself on boot.
I also think that the bots start themselves when restarting, but 1. there might be memory issues when all bots start at once and 2. if they lose connection when the lobby Restarts, they take way to long before trying to reconnect IIRC

**Comment by DanVanAtta** [comment]
Closing for now to avoid overloading the backlog.
