### ISSUE TITLE
10509 Graphics

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#3518]
### My Operating System
linux

### Map name
global 40 house rules

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
graphics are bad

### Do you have the exact error text? Please copy/paste if so
here are screenshots of 509 and then 506
![screenshot from 2018-07-07 01-58-33](https://user-images.githubusercontent.com/24382682/42408367-2d15ab2e-8191-11e8-90c7-578fb925f63a.png)

![screenshot from 2018-07-07 02-47-54](https://user-images.githubusercontent.com/24382682/42408371-3a35c186-8191-11e8-81f0-bf4a80d405f2.png)

**Comment by Cernelius** [comment]
What zoom?

**Comment by beelee1** [comment]
@Cernelius the map zoom. If I remember right that's what it'd look like if you zoomed out too far. It was a few years ago

**Comment by Heppisorus** [comment]
I have been testing on the new pre release since last night.  Unfortunately there are some real side effects to these changes...
 As far as to what @beelee1 has said, the quality of the graphics deteriorates significantly once you zoom out from 100%.  
This new version also experiences greater tile flicker when the screen moves around or while transitioning between game phases.  
There also seems to be more pronounced delays when transitioning between game phases.
The last thing I noticed is that the space bar function during combat will cease to work sporadically during battle.  It is as though the game unselects the combat window and you have to click on the battle window to be able to continue using the spacebar to progress.

Going to keep testing for a little longer to see if I have any other observations for you.

**Comment by ron-murhammer** [comment]
@beelee1 Yeah, I'm seeing the same thing and posted TWW at 80% zoom at the bottom of the original PR: https://github.com/triplea-game/triplea/pull/3482

**Comment by RoiEXLab** [comment]
#3519 Has a fix
