### ISSUE TITLE
Production Monitoring Strategy

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3531]
Two questions for the group to decide:

1. How are we going to identify production errors?
2. Who will be responsible for this, how often?

The ideal outcome for me is for us to create issues (tickets) to track these problems. Without that visibility I don't think we'll get them fixed.

**Comment by ron-murhammer** [comment]
Good questions. Honestly, I don't have much grasp on any of the new infrastructure scripts or what the process is to report issues or fix them. There are some issues in this queue and some here: https://github.com/triplea-game/infrastructure/issues. As well as discussions on gitter. And of course PMs and lobby discussions.

Personally, I don't have a strong opinion on the lobby/bots and don't particularly want to be very involved in maintaining them. I did it for a while with the old scripts but not really that interested in server admin and automation. I'm glad to help at least report issues though and if we have a clear process to do that then I think that would help as at least mods then know where to report the problems so they have the proper visibility. Also for common issues, trying to empower mods to be able to handle them is best as otherwise they are powerless to fix things.

**Comment by prastle** [comment]
The simple answer is allow the admin docs to work so all can use them.  Sadly they do not.  Prior to infra structure we had a few admin/mods that could stop restart etc.  now they have all abandoned it due to changes again just as they were learning.  Not much can be said after that since I am still dealing with changes and I was the one teaching them.

**Comment by DanVanAtta** [comment]
Thanks for the responses. I would like for us to focus on application problem identification and tracking.

The obvious choice for tracking would be github issue tickets.

For problem identification, beyond user reports and grafana server metrics, we have two sources to know about errors:
- Application and system logs are aggregated to papertrail (retention is ballpark a 1wk): https://papertrailapp.com/groups/8707471/events?q=error
- Red activity messages in the server gitter room are alarms raised by infrastructure: https://gitter.im/triplea-game/server


We need some volunteers, ideally a team(s), to watch these two sources and cut github issues so Dev can address the errors. Which team(s) can that be? ( if not 'dev'?)

Another question, can/should non-technical teams (eg: mods) help check logs and create error reports?

**Comment by DanVanAtta** [comment]
Closing, not actionable, conversation has grown stale.

The lack of production monitoring does remain something of a liability, and we have not war-gamed out disaster scenarios which does represent some project risk. At the same time we've been running like this for years and we've taken a number of steps to automate setup configuration which reduces our time to restoration to be pretty acceptable in case of disaster... There are still valid items to follow up on, but nothing specific noted here to close this ticket, so will resolve and leave it to future new issues to follow up on specific action items.
