### ISSUE TITLE
How many bots to run?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3553]
How many bots game instances should we be running to meet reasonable peak demand and not have to add 'emergency' bots?

**Comment by DanVanAtta** [comment]
If we had more bots, would we have had more than the 18?

**Comment by prastle** [comment]
Twenty four in past had many empty.  and clutter during the week.  Ideally 6 bot servers running 4 bots each with one that could be shut down during the week should be fine.

**Comment by prastle** [comment]
I should also add that the community has also been steadily growing.  So this could change and increase in a few months.

**Comment by DanVanAtta** [comment]
We've a min ram requirement that is around 115MB. AFAIK that is mostly bursty and when maps are loaded, but it also seems the servers get hit with large games running (we need to investigate this performance better). So I'm not 100% sure why/if going from 4 bots to 3 bots was actually helpful. We had 5 running on many servers and did not get cleaned up, I'm not sure if we actually jumped from 5->3..

So we have 3 running per server. Hit 24 we'd need 8 bot servers.
It's sounding like the 21~24 ballpark is about right.

**Comment by prastle** [comment]
We have had very few issues since switching to three bots.  Yes I agree the problem isn't solved.  I one hundred percent agree it is a memory buildup over time.  A simple solution is to save and reload after a few rounds.  It also seems to occur when there are many obsewrvers of a long game in progress that they lock and crash.

**Comment by prastle** [comment]
Well I would love to see the mem leak fixed and stick with 6 @ 4 but that's your department :)

**Comment by DanVanAtta** [comment]
Getting off topic: When servers lock and crash, see if you can leave them in that state and have me or another dev look at it. If we can get a thread dump, we'll potentially be able to fix the problem.

**Comment by DanVanAtta** [comment]
As far as 21 vs 24 bot instances,  if the extra bots are the difference between a game being played or not, and if we can get just one extra weekend game in each month, it's pretty easily worth it.  The difference between playing or not, critical, worth the money IMO.

**Comment by ron-murhammer** [comment]
Well this was a significant memory issue that is resolved now in the pre-release: https://github.com/triplea-game/triplea/pull/3370. That is the only memory leak I found when looking over a few of the heap dumps a few months back but it could have been masking others. Until a new stable is cut with that included, it'll probably be hard to say what the bot RAM requirements should be. I'm glad to review thread/heap dumps to further optimize it.

I tend to agree we need around 20-25 bots. From an ideal standpoint, I'd say 3 servers with 7-10 bots is where I'd like to get to.

**Comment by prastle** [comment]
Server does not lock the bot locks and crashes and boots them without a save

**Comment by prastle** [comment]
That would be great if we could get to 3 bot servers! 👍

**Comment by DanVanAtta** [comment]
@prastle let's aggregate info about bot crashes/lock-ups to: https://github.com/triplea-game/triplea/issues/3554; that is something we shoudl get to the bottom of. Indeed it is the application, if we can see it in a frozen state, we can pull off some diagnostic information that will let us know why it is frozen.

**Comment by DanVanAtta** [comment]
On-topic, 8 bot servers total will deliver 24 instances.

That is $40/yr. I think that is called biting the bullet until we can get some bot scaling problems fixed.

**Comment by prastle** [comment]
Then we need a command added
Remove from lobby and can't rejoin till restarted ;)

**Comment by prastle** [comment]
atm we have 500? I forget left in linode and 725 in paypal

**Comment by veqryn** [comment]
May I suggest that we use larger linode instances, and then run a lot more bots on them?
That would allow each individual bot to burst quite high on memory and cpu, while the average usage from all bots total would still stay quite low.

Perhaps instead of 8 servers ($5/month each) with 3 bots each @ $480/year (1gb ram, 1 core),
you could do 3 servers ($10/month each) with 8-12 bots each @ $360/year (2gb ram, 1 core),
or 2 servers ($20/month each) with 12-20 bots each @ $480/year (4gb ram, 2 core).

If spinning up new bots, or even new linodes, was part of an easily run script, you could cut the number of bots by half during the week or during slow timezones, and double the number of bots during weekends in hot-timezones.

Another option might be to dynamically spin up the bots as needed. You'd probably want to use docker swarm or something for this, so call it a pipe dream for now....

**Comment by DanVanAtta** [comment]
Couple updates:
- We have 3 new bot servers up, we're at 8 running now with 24 instances.
- While on that task, I also updated/overhauled the how to add a server instructions: https://github.com/triplea-game/infrastructure/pull/89, now includes step-by-step screenshots

@veqryn you could be on to something : )
I'm not sure if linode plans were always so linear, at the time it looked like $5 instances were the best ratio of RAM to cost. Regardless, with twice as many cores, very importantly we still have same number of cores per bot, *but* bots instead have access to multiple cores.

I'm thinking it may be a good idea to swap 2 of the new servers for 1 larger one that is double size running 6 instances. See if there is a noticeable benefit. If so then re-organize into more instances on larger servers.

Overall bots should not be consuming so much resources for just server hosting, I do think the real fixes are to offload processing from bot nodes and make them basically little more than network relays. On the other hand a clean and working auto-scaling configuration would be very valuable.

**Comment by DanVanAtta** [comment]
Keep lobby isolated is a good move. It's pretty fast to spin up bots on a new server, so we can get results pretty fast that way.

Medium term, moving the lobby off of current marti so we only have dice on that server, and loading it up with bots could be a good thing : ) 

Then we'll be in no rush to migrate dice server.

**Comment by prastle** [comment]
@DanVanAtta Great we need to make sure it loads the maps this time.

**Comment by DanVanAtta** [comment]
@prastle reboots in the future could help, I think the problem was that the servers booted before the maps had finished downloading.

The 'big' server is up and running, NJ_70_XL. I wound up having to tune it down to fewer bots with more memory on them for the bots to launch and be stable. Next time I'll experiment with a server connected to the test lobby... In the meantime we'll get some experience with how a larger server performs.

**Comment by prastle** [comment]
all good its a work in progress now we have data from looking at one not many

**Comment by prastle** [comment]
@DanVanAtta  side not but 709 is missing and we have a 710 looks kinda weird...

**Comment by prastle** [comment]
K it's up  now.  I will add another 100 from paypal to keep us safe with Linode.  So @ all 16 months to figure it out :) with no donations ... use that test lobby and test :)  Great JOB GUYS!

**Comment by veqryn** [comment]
@DanVanAtta So I saw the max memory size in your infrastructure script is actually pretty small, meaning there is little chance of bursting high in memory (ie: some big maps might need 500mb to load, then drop to 250mb to play, before dropping back to 50mb when idle).
This reminded me of how the hotspot jvm is normally quite greedy about memory, and tends not to play well with other processes.
I did a little googling, and it does seem that with the right settings the JVM will actually give memory back to the OS (for use by other processes) when it is not using it:
https://stackoverflow.com/questions/30458195/does-gc-release-back-memory-to-os

It would be ideal if we had something like the following, with the 2 gb server you just spun up and 14 bots:
Minimum memory per bot: 96mb
Max memory per bot: 512mb
Have each bot's jvm settings release unused memory back to the OS.
Have each bot switch to "no map" loaded whenever noone is in the bot's room (in order to fully release all its memory when noone is using it).

**Comment by prastle** [comment]
Just watched it occur in the new mega server @veqryn  in another thread I commented earlier.  I like it you two are on the same page @DanVanAtta   great stuff!

**Comment by prastle** [comment]
@veqryn  you made it happen years ago with the war club and running marti on same server....
simple point is a general ? to the lobby and a few mods today they have had zero issues with new config.
Can we just run 2 mega servers with some backup bots on the others for emergencies?

**Comment by prastle** [comment]
0 probs with new setup reportedthus I recomend we kill the mini servers @DanVanAtta 200 I booted from the lobby. feel free to play
