### ISSUE TITLE
"Players" tab shows technologies even for maps which don't have that enabled

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#3574]
"Players" tab shows technologies even for maps which don't have that enabled.

It's weird to see "Heavy Bombers" in Feudal Japan, for example.

**Comment by Cernelius** [comment]
Not having that tab is a feature already supported, by having the reference in the xml, but leaving it empty. Feudal Japan (as well as several other games) could be updated accordingly (and could have been since many years).

**Comment by Cernelius** [comment]
For an example, you can look at World At War.

**Comment by Cernelius** [comment]
This has been the discussed way in the past, and this is the way @veqryn decided to go. I hardly remember anything, but I suppose you can search in the old developer forum, if you find any explanations.
Anyway, I believe this fully covers (I tested it), as you can also not have that tab for players actually having techs (which is the case of Feudal Japan, since most players are mechanized).
But, yeah, almost no mapmakers follow or even know about this practice, for not having the technology tab, so you have tons of games with no tech that display all the AA Radar etc. pointless stuff. Personally, I'm not too concerned.

**Comment by ron-murhammer** [comment]
@asvitkine This could definitely be improved and at least inferred to some extent. If a tech can't be researched by anyone then no reason to show it. If there are no techs at all in the map then no reason to show the table at all. But as @Cernelius mentions sometimes players are all given a hard coded tech like Mechanized Infantry so couldn't really hide that automatically.

**Comment by Cernelius** [comment]
In cases like Feudal Japan, I would hide the technology tab, as the fact that everyone is Mechanized doesn't need to be displayed (you get the relevant info in the tooltips and how the horse work is better to be explained in notes), and that can be already done (hidden). I never bothered doing it myself.

**Comment by veqryn** [comment]
The option to disable technology I believe only disabled the ability to pay to research it.  It can still be acquired by players using triggers or whatever.
The map should just be updated to remove all technologies (instead of getting world war 2 techs as a default setting).
