### ISSUE TITLE
Internet connectivity problems reported "update-ca-certificates -f "

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3607]
https://forums.triplea-game.org/topic/922/java-error/10

- Our software needs to handle the problem automatically, or alternatively detect the problem and give users clear instructions on what to do.

@RoiEXLab last worked on this:

> I dug a little bit deeper into this and this seems to be a java installation related issue.
Try running update-ca-certificates -f in the terminal and see if that helps.

**Comment by RoiEXLab** [comment]
I don't think we should be responsible for handling this problem. It's very much related to the JRE installation itself.
Agree on having a clearer message though.
Telling the users to visit the forum when they believe they should be able to connect is a good thing

**Comment by RoiEXLab** [comment]
@DanVanAtta I don't think we can cleanly detect it either.
The only thing we could do is to check if theres a `java.security.InvalidAlgorithmParameterException` somewhere in the caused by chain.
We can't check the exception message either because if the java installation has a different language that might affect the message.

**Comment by DanVanAtta** [comment]
"cleanly" maybe was badly defined, I was wondering about false positive rates for misidentification.  Checking for a specific 'caused by' to be in the stack trace is not necessarily ideal but still reasonable IMO.

We should consider as well if maybe we are going about this wrong. Maybe a page with 'common' problems would be better. That could have example traces that a user could line up, and at the bottom of the page we could have a "Did not find your problem? report it here..."

I think I like the digging into a stack trace idea better still though, I'd like the game to be as pro-active as it can about identifying problems and telling users what is going on and what they can do to fix it.

**Comment by RoiEXLab** [comment]
@DanVanAtta Following the linked thread further it seems like this is a ubuntu related issue, which will be fixed in the future, so not our task.
However, I agree that we need to do something about the system check thingy.
We should be able to detect if a user just forgot to enable WiFi, or there's something wrong with the configuration instead and provide exception details at request.
Just had this a couple of weeks back with my laptop, I wasn't online, and every time I started triplea I got this super annoying message in my face.

**Comment by DanVanAtta** [comment]
I agree not our task to solve the problem, but overall we should be detecting and presenting error cases to the user in a reasonable manner. If we can detect a known problem then directing a user how to fix it would be excellent. That could really be as simple as giving them a FAQ link where we can describe "if you see this in the error stack trace, then it means to do XYZ and if that does not help then contact us." We really don't want to leave users without direction of what to do.

**Comment by DanVanAtta** [comment]
Closing, does not seem like this will get fixed/improved. If we see more error reports then perhaps it will motivate us to fix the UX.
