### ISSUE TITLE
Lobby Compat Possibly Broken

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3648]
Using latest 'master' as of fcfb5ce67545f442a82d612d93c9af6314601b02; I'm seeing an error message for `null` 'version' when logging in to the prerelease lobby. This is usually due to a network/game compatibility problem.

![lobby_compat](https://user-images.githubusercontent.com/12397753/43373368-19370e20-935e-11e8-9134-b481239ddc32.png)

**Comment by ssoloff** [comment]
Anonymous logins seem to be working for me:

![staging-lobby](https://user-images.githubusercontent.com/4826349/43374026-920b9ce0-937b-11e8-8b23-c72e7a59a5ba.png)

I didn't have an account on the (new) staging lobby, so I just created one and was able to login with that registered account, as well:

![staging-lobby-registered](https://user-images.githubusercontent.com/4826349/43374152-373ed934-937c-11e8-849e-dc40f7f3534d.png)

(Running from dev environment at fcfb5ce67.)

**Comment by ssoloff** [comment]
I can reproduce the error message if I change my Engine Preferences so that my lobby override points to a host/port corresponding to a running network game host.  That is, trying to get a `LobbyLogin` to communicate with a `ClientLoginValidator`.

Might want to verify your lobby override points to `lobby-staging.triplea-game.org:7000`.

**Comment by DanVanAtta** [comment]
Thanks, that was the issue. Forgot the oddball 7000 port was the right one.
