### ISSUE TITLE
Moderator Toolbox freezes when checking "ghosted" games 

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3729]
Find a game that is locked up, listed in lobby but cannot be joined, try to view the game info as moderator and the app locks up.

**Comment by prastle** [comment]
As I suggested in the forum thread.  A simple solution might be to post an error message similar to the one received if trying to join the locked up game as an observer.   When using the toolbox to view the host info  Example "Can not connect for host info!"  Or whatever...  Just a thought.

**Comment by DanVanAtta** [comment]
Indeed, but first is to make sure the game does not freeze.

**Comment by Cernelius** [comment]
The best solution would be, of course, that games that cannot be joined are never kept connected to the lobby.

**Comment by Cernelius** [comment]
Have really no clue on the tech aspect, but would it be possible, like the mods right clicking, that, instead, the lobby every minute check if a game connected to itself is reachable, and, if not, it autoboots it (so that ghosts never stay there for more than 1 minute).

Sorry for the off topic, if so.

**Comment by DanVanAtta** [comment]
Since we're re-writing the toolbox, focus will be on the new version of this tool.
