### ISSUE TITLE
AI - Refactor BattleUtils to Allow Separate Battle Calcs for Fast and Hard AIs

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#381]
Can't run both Fast and Hard AIs in the same game since they share a static battle calc.

**Comment by DanVanAtta** [comment]
Adding 'bug' label.  @ron-murhammer ,"urgent" I've informally been using as "release blocker". It might make sense to rename the label to that perhaps. 

For this issue, if you consider fixing this a requirement before we do the next release, then the urgent label seems appropriate. Otherwise I think we could label the "fastAI" as a beta feature and stick with the 'bug' only label. Up to you @ron-murhammer  on which direction to take there (the ball remains in your court).

**Comment by ron-murhammer** [comment]
Yeah, I've been treating it the same way. I do plan to tackle that before the next release.

**Comment by ron-murhammer** [comment]
This is addressed in #392. Will close this once that is merged.

**Comment by DanVanAtta** [comment]
Out of curiosity, have you given it a try mixing the two AI's up in a game? No need to respond, just a question for you ;)

**Comment by ron-murhammer** [comment]
Yeah, I did and seemed to work fine now. Fast AI even wins on some maps where the AI just plays one side much better than the other!
