### ISSUE TITLE
Bid Phase Bugs

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#391]
There are at least 2 bugs with bid phase.
1. Unit place restrictions shouldn't be applied (example is 270BC you can only place a bid in city territories which is incorrect).
2. You can place unlimited units in a territory where the official rule is "1 unit per territory or seazone where the nation has a minimum of 1 unit already". Though there are some maps such as Feudal Japan and Domination 1901 that don't follow this and allow unlimited.

**Comment by DanVanAtta** [comment]
SZ bid placement I don't think has well agreed upon rules. Some say:
- any empty SZ next to a territory that you control
- any empty SZ next to a factory that you control
- any SZ where you have an existing fleet
- any SZ 

Seems like for this one, per-map we'll need a "bid-policy" field that can tell the engine which of those are correct.

**Comment by Cernelius** [comment]
I believe this issue should be split into two different issues:

**1**. Is a **bug** (medium or high priority, in my opinion).

**2**. Is a **feature request** (it is not a bug at all) (low priority, in my opinion).

In my opinion, 1 should be addressed with some priority, as it makes proper bidding impossible in several maps (main example is that in 270BC you can't use bid for RomanAlliance, that I'm quite sure it needs from 5 to 10 bid, at default options). Of course, people edit into the units, instead of using the bidding phases, but it gets confusing and problematic, especially for multys.

I disagree with the need of addressing 2, and anyway (if you really want to at all) it should be low priority and the current bid behaviour kept anyway (thus, optional).

And, of course, there are no official rules for bidding (there are ladder rules, but this doesn't make them official; for example, in v3 ladder it is forbidden to bid a Bomber, but this doesn't mean that you have to enforce this ladder rule in the engine).

**So, first of all, I definitively advice splitting this issue into two different ones, for 1 and 2, and 1 needs to be debugged while 2 needs to be debated** (for example, how to deal with sea zones with ownership or in case of minors?).

p.s.: The one described by @ron-murhammer it is not even the actual ladder rule, since you don't need having any units in land territories, only in sea zones, and you can't put bid units in land territories you don't own, no matter if there are units of yours in them, but this is not the point.

http://www.tripleawarclub.org/modules/comp/rules.php?lid=6

> The current stable version, as of the above date, of TripleA is v1.2.5.4.
> For 1941 with regular luck (Dice), the Allies bid is set to 8 IPCs.
> For 1941 with LowLuck (LL), the Allies bid is set to 13 IPCs(*)
> For 1942 with regular luck (Dice), the Allies bid is set to 9 IPCs.
> For 1942 with LowLuck (LL), the Allies bid is set to 9 IPCs
> (*) No bomber purchases are allowed for this game and bid combination
> These IPCs may be spent on units to be placed on the board prior to game start. The IPC may be split the allies in any way. The first restriction is that no more than one unit may be placed per territory. Naval units must go into a sea zone with existing Naval units of the same nation. Placement of naval units in empty sea zones or placement of, for example, British units with American units (and vice versa) is not allowed. Similiarly, ground/air units must be placed in the territories controlled by the same nation. However, ground units may be placed in territories that have no existing ground/air units.

**Comment by DanVanAtta** [comment]
#1403 will allow placement, but it does not impose a bid restriction of 1. I think it is probably better to allow the move and force players to enforce the 1 bid placement limit, rather than not allow the placement at all and force edit mode.
