### ISSUE TITLE
PaperTrail is full / Reduce Logging to PaperTrail

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3948]
We're no longer getting papertrail logs, over limit, we're almost flying blind. You *can* ssh to every single server to see logs, but that is not terribly practical.

Jumping to the next plan is the shortest term fix we can have, though IIRC the next price tier is a $10 or $15 more per month.

Long term, reducing log volume would help.

**Comment by DanVanAtta** [comment]
Looks like we were at $160/yr, next plan is about $300/yr   :money_with_wings:

**Comment by RoiEXLab** [comment]
@DanVanAtta I'm also under the impression that the logs got more over time.
This could be of course caused by an increasing amount of bots, but it could also mean that there may be more exceptions?
Or there are just too many irrelevant things being logged.
The last time I looked I saw a lot of boilerplate logs caused by the automated updates every x minutes (apt everything is up-to-date etc. and more).
Reducing those logs could help a lot already.
If that's not enough we might want to analyse what log level the logs are being sent at. If there are for example toi many INFORMATION logs, but almost no errors or warnings, we could consider not sending anything under warning anymore.

**Comment by DanVanAtta** [comment]
![default](https://user-images.githubusercontent.com/12397753/44950237-841fbd00-adf7-11e8-8360-15d1502dfdb0.png)

This looks to tell the story I suppose. Either: A) the logging from prerelease was simply excessive, or B) the full disk caused lots of errors to be logged, which then cascaded to a problem where we ran out of log space.

**Comment by prastle** [comment]
Np adding funds... one request tho.. when we were chatting with @veqryn  you came up with a great list of all costs in another thread.  Can you please add a post here https://forums.triplea-game.org/topic/782/donation-drive-for-2019/58 @DanVanAtta  of the overall general cost so that all users understand?  Thanks

**Comment by ron-murhammer** [comment]
@DanVanAtta I believe like 80-90% of the logs were the staging lobby so that is probably the issue.

**Comment by DanVanAtta** [comment]
@prastle https://github.com/triplea-game/triplea/issues/3537#issuecomment-405384063

I think in this issue we should track that we want to do log cleanup. The suggestion to reduce to only warning or error logging being sent to papertrail I think is a good one. The activity feed in gitter is good for us to know that the update jobs are running, we get a report of the bot counts and the version being run with that.

The task here then would be to prune down logs that are sent to papertrail. I think there would be two aspects to that:
- infrastructure updating logging #3962
- application logging #3963

Otherwise we are just waiting a few days now for the logging cycle to roll over and we'll start with a fresh 1GB limit. With the new tasks created, this task is no longer actionable (closing)
