### ISSUE TITLE
Error Prone: Resolve remaining ImmutableEnumChecker rule violations

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#3972]
Three enums remain that currently trigger a violation of the Error Prone ImmutableEnumChecker rule:

* `ClientSetting`
* `ClientSettingSwingUiBinding`
* `ClientSettingJavaFxUiBinding`

You can read the Error Prone docs [here](http://errorprone.info/bugpattern/ImmutableEnumChecker), but, in a nutshell, this rule states that it is a violation of the Principle of Least Surprise if an enum is mutable.  The above enums contain true mutable state (e.g. non-final fields and mutable collections that are modified at runtime).  (`ClientSettingJavaFxUiBinding` is not quite there, but since it is effectively a clone of `ClientSettingSwingUiBinding`, I suspect it will eventually have the same mutable state.)

We've already suppressed a few occurrences of this rule violation for mutable enums that employ the Enum Singleton pattern described in _Effective Java_ simply because it's a well-accepted pattern.

I see three ways forward to resolve the remaining violations (feel free to add any others I did not consider):

1. Affirm the rule should be followed for non-singleton enums and convert the above enums to final classes with private constructors and one static final field per instance.
1. Affirm the rule should be followed by default, but for the above cases permit an exception, and suppress the rule violation on a case-by-case basis, similar to what was done for singletons.
1. Reject the rule completely, disable it in the build via `-Xep:ImmutableEnumChecker:OFF`, and remove the existing `@SuppressWarnings("ImmutableEnumChecker")` annotations.

Thoughts?

**Comment by RoiEXLab** [comment]
@ssoloff I believe the only reason those enums use suppliers is because otherwise substance/JavaFX would complain that the UI elements are not being created on the UI Thread when the class is loaded.
I don't know if when the class is first referenced from the UI Thread if the class loader runs from the same thread.

**Comment by ssoloff** [comment]
@RoiEXLab I should have stated this in the description, but it wasn't the `Supplier` fields that prompted this issue.  Those could be addressed per the Error Prone recommendation to convert them to `abstract` methods on the enum itself.  That alternative design would still preserve the threading behavior you referenced above.

The true mutable state is in the `ClientSettingSwingUiBinding#selectionComponent` and `ClientSetting#onSaveActions` fields.

**Comment by ssoloff** [comment]
Actually, we might be able to get rid of `ClientSettingSwingUiBinding#selectionComponent`.  It looks like this was some sort of optimization to only build the UI component once per setting.  However, note the following:

1. `buildSelectionComponent()` is only called from `SettingsWindow`.
1. `SettingsWindow` only calls `buildSelectionComponent()` once per setting.
1. `dispose()` is only called from `SettingsWindow`.

Therefore, the way things work currently, the UI components are created once every time the `SettingsWindow` is opened.  So it seems like caching the UI component is not really necessary and is just a premature optimization.  @RoiEXLab, is that why you didn't add this functionality to `ClientSettingJavaFxUiBinding`?

I'll prototype removing it to see if I run into any issues.

**Comment by RoiEXLab** [comment]
@ssoloff 
> The true mutable state is in the `ClientSettingSwingUiBinding#selectionComponent` and `ClientSetting#onSaveActions` fields.

Makes sense.
> So it seems like caching the UI component is not really necessary and is just a premature optimization.  @RoiEXLab, is that why you didn't add this functionality to `ClientSettingJavaFxUiBinding`?

Had to look up the code to see what you were reffering to exactly, and I recall why exactly it was done this way.
See, when we change a client setting indirectly (like pressing reset/resetToDefault (or save while an invalid value is selected)), the UI component should be changed as well of course.
That's why the value is being "cached", so we actually change the same ui component, and not a newly created one which has no effect on the existing one.
That's why I did it this way. Changing everything into final fields would be fine for me. I'd prefer this solution over suppressing the warning.
I'm open for any fundamental design changes of the binding though, although I think, unless it would be a clear improvement from a usability perspective, it's probably not worth it.

**Comment by ssoloff** [comment]
@RoiEXLab Ah, now I see what you're doing in `ClientSettingJavaFxUiBinding`.  The cache is still there, but you've hidden it behind `Suppliers#memoize()`.  That's probably a better approach (although it still doesn't solve the overall mutability of the enum instances).  I'll probably submit a PR to do that in `ClientSettingSwingUiBinding` just to keep things consistent (and get rid of one more Error Prone warning).

I understand what you're talking about with keeping the UI component updated.  I think there might be another way to do that without requiring the cache in the `*UiBinding` enum.  However, as you said, it may not be an improvement from an API usability perspective.

**Comment by ssoloff** [comment]
All remaining ImmutableEnumChecker violations have been resolved.
