### ISSUE TITLE
Bot Player Ordering on Setup Screen Incorrect

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#4065]
![image](https://user-images.githubusercontent.com/1427689/45795185-eda92380-bc5f-11e8-8dc4-6fad701f84dd.png)

Local game:
![image](https://user-images.githubusercontent.com/1427689/45795195-01548a00-bc60-11e8-8e84-657ff0f5fba3.png)

**Comment by ron-murhammer** [comment]
I think this PR is the issue as it copies the map but doesn't appear to ensure the ordering: https://github.com/triplea-game/triplea/pull/3615/files#diff-f72e8d0ae698abae1bbc70eb2ca08b68R86

**Comment by ssoloff** [comment]
:+1: Yeah, that looks like a good candidate.  It's tough to figure out the exact build where this bug was introduced because there were about 100 builds between 10663 and 10792 that throw an NPE during bot startup, so that one can't connect to test the player order.  Regardless, a 10663 bot does not exhibit this problem, while a 10792 bot does.

**Comment by ssoloff** [comment]
@Cernelius Thanks for noting.  I can confirm that a client connecting to a private host would also see the wrong player order, so this issue isn't isolated to just bots.  I verified that the private host scenario is also fixed in build 12102.

**Comment by Cernelius** [comment]
What do you mean by referencing 1.9.0.0.12102? This is tagged as Release Blocker, so: is it fixed for the current release, namely 1.9.0.0.11996? Should I tell users to install the latest release or that prerelease version you mentioned?

Example in lobby, as of today:

> epinikion has joined
> (19.28.04) AdamF:  @epi
> robhun has left
> (19.30.13) epinikion:  hi adam
> (19.30.29) AdamF:  Hey
> (19.30.49) AdamF:  Was there a new release of the software engine?
> (19.31.22) epinikion:  since when?
> (19.31.51) epinikion:  1.9.0.0.0687
> (19.32.09) epinikion:  recently the bots were addapted i think
> (19.35.02) AdamF:  ah
> peirce has joined
> (19.35.48) AdamF:  becaise now in revised, the powers are listed differently
> (19.36.00) epinikion:  yeah
> (19.36.22) AdamF:  used to be in trun order...now its G, UK, USA, USSR, J
> (19.36.42) AdamF:  not a big deal, but counter intuitive.
> (19.36.57) epinikion:  i dont know the reasons
> (19.37.06) AdamF:  I'm sure there are programming reasons for it,
> (19.37.17) epinikion:  probably
> (19.37.41) Dany:  hey epi
> (19.37.46) epinikion:  hi dany
> (19.37.50) AdamF:  Just wanted to be sure there wasn't a bug or issue for me (which I always have :)  )
> (19.37.58) AdamF:  TY
> (19.38.00) epinikion:  ok adam
> (19.38.03) epinikion:  welcome
> (19.38.19) epinikion:  dany
> (19.38.23) Dany:  yes!
> (19.38.25) epinikion:  i have like 90 min
> (19.38.29) Dany:  good!
> (19.38.29) epinikion:  in 8 min
> Olcayto has joined
> (19.38.35) Dany:  alright:)
> Olcayto has left
> kay has joined
> (19.39.48) Dany:  301 when ready!
> (19.39.59) TheKhan:  hi in game
> (19.40.11) kay:  kk
> Babbe01 has joined
> Nineteen has joined
> (19.43.47) Nineteen:  hey, anyone know how do you repair in Camp David?
> Master_Blaster has joined
> (19.45.57) Cernel:  You just slapped AdamF
> (19.46.10) Cernel:  Hey AdamF, the stable release has been recently updated to version 1.9.0.0.11996.
> (19.46.21) Cernel:  However, I understand this issue was still present in that one, so you may want to download the latest prerelease here:
> (19.46.30) Cernel:  https://github.com/triplea-game/triplea/releases/tag/1.9.0.0.12102
> Cow has joined
> (19.46.55) Cernel:  If you do it, please test and let me know if that appears to fix the issue for you.
> (19.46.58) AdamF:  Thank cernel, will games work with one player on new release and other player(s) on older version?
> TAZZ has left
> (19.47.17) AdamF:  last update that was huge issue
> (19.47.18) Cernel:  If they don't, that would be a bug too.
> (19.47.30) Cernel:  They do for me, so I guess you should be safe.
> Gabreski has joined
> Master_Blaster has left
> (19.47.53) Cernel:  I'm on Windows.
> (19.47.58) AdamF:  same
> Master_Blaster has joined
> (19.48.29) Cernel:  So, your call if you want to take the risk to install the unstable I linked. If you do, please test it and let me know if it fixes the issue.
> (19.48.56) AdamF:  maybe i wait for stable, thanks cern
> (19.49.00) AdamF:  Hello MB
> (19.49.04) Cernel:  What I linked is not the new release, it's the latest prerelease.
> (19.49.19) Master_Blaster:  9687 isnt the lastest version ? hi g uys
> (19.49.27) Cernel:  No, it is not.
> (19.49.30) AdamF:  its latest STABLE
> atok123 has joined
> (19.49.38) epinikion:  hey cernel, butr bots are updated the version 1.9.0.0.0687?
> (19.49.38) Master_Blaster:  yes
> (19.49.44) Cernel:  The latest stable has been recentry updated to 1.9.0.0.11996.
> (19.49.55) Master_Blaster:  pre version...always a danger...
> (19.50.06) epinikion:  then headline of lobby should be frehed up
> (19.50.13) AdamF:  ^^ Yes
> (19.50.16) epinikion:  *freshed
> (19.50.46) AdamF:  That cant be "fake news"
> (19.50.50) AdamF:  :)
> (19.50.55) Cernel:  Hey epinikion, I don't know anything more about bots than what is written in bunker. What is written here in lobby, however, is certainly obsolete, as that version is not anymore the latest release.
> (19.51.00) Master_Blaster:  lest stay at the good working version adam    and start a game
> (19.51.18) AdamF:  k, 402 for you ass whooping!
> (19.51.30) Cernel:  Comon MB you are a power user.
> (19.51.33) Master_Blaster:  warning !!
> (19.51.40) Master_Blaster:  yes
> (19.51.47) Cernel:  You should be on lateste prerelease 5 minutes after it's out.

**Comment by ssoloff** [comment]
@Cernelius I was simply noting that the bug is fixed in 12102.  11996 bots will most definitely continue to exhibit the problem.

Traditionally, the **Release Blocker** label means we won't promote a new stable release until it is fixed.  Since this issue was created _after_ 11996 was promoted, it just means we can't promote any subsequent pre-releases to stable until it's resolved.

For this particular issue, I'm not sure if promoting a new stable is necessary.  For the majority of users, it will be sufficient to simply upgrade the bots to 12102 or later.  However, as all the recent QA testing was focused on 11996, there probably should be another round on 12102 to ensure there's no other regressions lurking in those 100+ builds since 11996.  That will be a @ron-murhammer or @DanVanAtta decision when to promote.

> Should I tell users to install the latest release or that prerelease version you mentioned?

Just to be clear, this bug affects the server (e.g. a bot), not the client.  Therefore, even if a player upgraded their client to the latest pre-release, they would still see the problem.  In fact, even if they downgraded to 9687, they would still see the problem.  We have to upgrade the bots to properly fix the issue for the typical player in the lobby.  (Players who host their own bots in the lobby or just run private peer-to-peer games would also need to upgrade.)
