### ISSUE TITLE
Lambda foreach Discussion

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#408]
Lambda ForEach's

For this issue, let's look at examples of replacing foreach loops with lambda and discuss what we like and do not like. The goal will be to come up with general guidelines of where we expect to see J8 lambda's helping, and where we think they might actually might hurt.

### A
```
for (final Territory t : allTerritories) {
  final List<Unit> moveableUnits = t.getUnits().getMatches(moveableUnitOwnedByMe);
  if (!moveableUnits.isEmpty()) {
    highlight.put(t, moveableUnits);
  }
}
```

```
allTerritories.forEach(t -> {
  final List<Unit> moveableUnits = t.getUnits().getMatches(moveableUnitOwnedByMe);
  if (!moveableUnits.isEmpty()) {
    highlight.put(t, moveableUnits);
  }
}
```
(from #396)

### B

```
List<Integer> list = Arrays.asList(1, 2, 3);
for (Integer i : list) {
    System.out.println(i);
}
```

```
List<Integer> list = Arrays.asList(1, 2, 3);
list.forEach(System.out::println);
```
(From http://blog.jooq.org/2015/12/08/3-reasons-why-you-shouldnt-replace-your-for-loops-by-stream-foreach/)

### C

```
List<Integer> list = Arrays.asList(1, 2, 3);
for (Integer i : list) {
    System.out.println(i);
}
```
```
List<Integer> list = Arrays.asList(1, 2, 3);
list.forEach(i->System.out.println(i));
```

Related links/reading/references::
-  http://blog.jooq.org/2015/12/08/3-reasons-why-you-shouldnt-replace-your-for-loops-by-stream-foreach/
- http://stackoverflow.com/questions/16635398/java-8-iterable-foreach-vs-foreach-loop
- https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html
- https://docs.oracle.com/javase/8/docs/api/java/util/function/Consumer.html
- https://docs.oracle.com/javase/tutorial/collections/streams/

**Comment by DanVanAtta** [comment]
For A:
IMO the two are very similar, really effectively the same here. I do really like that `Territory`  type is removed. But, we do not have other places where equivalent locations use the lambda version. 

I've come to agree with you @ron-murhammer on this one. Namely it does seem  easier to not  mix the lambda versions in, unless it really helps. I think I see where the concern is then about the large scale to convert everything - since if they are equivalent and one is 'better' for us, then we would want to achieve that level of uniform code.

For B:
The lambda version is not pretty.. I agree with the article on this one. My bias is perhaps that I don't fully understand the "::" operator yet. It seems odd where it is located, between `System.out` and the method `println`.  I also wonder how you could modify what is passed in to the System.out.println(), like for example if you wanted to do: `System.out.println("value of: " + i)`

For C:
I think the lambda version makes a light weight foreach loop, even lighter.  It reads pretty cleanly to me as well.  When the foreach loop body is really simple like this, the lambda version seems preferable to me.

**Comment by ron-murhammer** [comment]
For A:
Agree. They are similar but definitely prefer the traditional foreach. Just more common and easier to read/maintain for most developers.

For B:
Yeah, I'm not a fan of "::" operator. Just seems awkward and makes it seems like some 'magic' is happening.

For C:
This is probably the toughest one as the single line lambda is pretty lightweight and clean looking. This one I think really boils down to preference and how comfortable people are with the most basic use of foreach() and lambdas. I think I still prefer the traditional foreach even though its a little more verbose just because I've read thousands of lines like it before but only in the 10-100s of lambdas so doesn't come quite as naturally. Another point here is when these 2 lines are one after another the context of the list is right there so makes not having the additional type declaration beneficial. If say you had a 10-20 line gap between the 2 lines then I would almost definitely favor the traditional foreach so I can see what type of variable I'm looping over (though in this case it really doesn't matter the type much since we are just printing it but might if we were doing something different in the one line expression).

**Comment by DanVanAtta** [comment]
I think the 10-20 line gap point is quite interesting. With a foreach, to know the type for the loop variable one looks at the foreach statement. For lambda's it is at the declaration of the Iterable.


Since we have both large foreach loops, and large gaps between the foreach and  declaration of the foreach Iterable, lambdas are probably going to make it much harder to know the type of the loop variables for us.

Essentially, I believe the trick is then knowing the type of "i", or "t", by looking one or two lines away, whether that is at:
```for (Integer i : list) {```
 or at:
```
List<Integer> list = Arrays.asList(1, 2, 3);
```

**Comment by DanVanAtta** [comment]
So I would suggest that a guideline for a lambda foreach is that it is okay, as long as:
- the declaration of the Iterable is one or two lines couple lines away, this it's clear what type we're looping on. 
- the expressions in the lambda needs to be really simple. No additional nesting.

Given the first requirement there, IMO it'll probably be rare where it makes sense for us to retrofit old code with the lambda foreach. You've certainly changed my mind on the matter @ron-murhammer , before this conversation I would have said to go with A. I agree now that knowing the loop variable type is a primary consideration.
