### ISSUE TITLE
Combat result numbers not shown in history

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#4082]
### Engine version

1.9.11996

### My Operating System
Ubuntu 18.04

### Map name
World War II Global 1940 Balanced Mod3

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
View history

### Do you have the exact error text? Please copy/paste if so
![screenshot from 2018-09-22 14-22-22](https://user-images.githubusercontent.com/20733860/45913292-09384800-be73-11e8-8762-ae3a944a223a.png)

Note how the numbers of the units are not shown, with ellipsis (...) shown instead  

### Instead of this error, what should have happened?
Numbers should be shown.

### Any additional information that may help
Pretty unusable as is.

**Comment by ssoloff** [comment]
Strange.  I can't reproduce that truncation on Fedora:

![issue-4082-fedora](https://user-images.githubusercontent.com/4826349/45913514-f33e6f00-be01-11e8-8469-4e34847f2a42.png)

Or on Windows:

![issue-4082-windows](https://user-images.githubusercontent.com/4826349/45913521-ff2a3100-be01-11e8-9fbb-5e7366cf2d51.png)

@simon33-2 Could you please attach a save game so we can see if it's something specific to the save or your windowing system?

**Comment by simon33-2** [comment]
Also affects the territory view, placements and everything else next to an image in that window.

Hmm, just tried an old version and it also applies. Looks like it is a problem with the windowing system. What a bummer! Any suggestions?

**Comment by ssoloff** [comment]
@simon33-2 Not with TripleA, but I used to see this issue (text overflowing its boundaries) a lot on Windows when a user increased their display DPI from the default in order to make text appear larger (in the day, it was typically from `96` to `120` dpi).  It typically occurred when an application used a lot of hard-coded dimensions for things (like TripleA does) instead of querying the OS to map logical pixels to display pixels.

So that may be something you can investigate under the assumption that you possibly changed it from the default.  I really have no idea where that setting might be on Ubuntu, but [this SO question](https://askubuntu.com/questions/197828/how-to-find-and-change-the-screen-dpi) may help.

**Comment by simon33-2** [comment]
Ok, I've actually found a fix. Turns out that it's because I upgraded my OS and on this computer I use a slightly different window manager to another Ubuntu computer which I'd already upgraded. So I assumed it was to do with the Triple-A rather than the window manager.

The libfreetype6 upgrade to 2.9.1 was the problem btw.
