### ISSUE TITLE
Flaky integration test

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#4083]
Just noticed that there was an integration test failing on the master build (only Java 8).
```
org.triplea.http.client.WireMockSystemTest > sendErrorReportSuccessCase(WireMockServer, String) FAILED
    java.lang.AssertionError at WireMockSystemTest.java:77
```
[I preserved the original log for future reference](https://github.com/triplea-game/triplea/files/2407690/raw.failed.log.txt)

@DanVanAtta Any idea when this race condition could happen?

**Comment by DanVanAtta** [comment]
@RoiEXLab hard to say much about the error with just an assertion error. Shouldn't this have failed the build? I'd like to see more examples and we'll need to add more logging around this. If we are not failing the build then the test is not worthwhile to begin with (could fail for real and we'll keep ignoring it, maybe that is a legitimate failure and the race condition is when it happens to pass by chance rather than fail by chance).

**Comment by RoiEXLab** [comment]
@DanVanAtta It failed the master build, that's why I kept the raw log.
I restarted the build afterwards, because it's the master branch.
Maybe this failure isn't even our fault and we discovered a race condition bug in the library, but I just wanted to note this happened.
I'd suggest keeping this issue opened for another week and close it if we don't see this failure during that time.

**Comment by ssoloff** [comment]
I believe I've seen two Travis builds fail in the past week, as well, due to the same test (well, not positive it was the _exact_ same test, but it was one involving WireMock).

It might be useful to, at least temporarily, bump the verbosity of JUnit logging so we can capture the test output when the failure happens on Travis.

**Comment by ssoloff** [comment]
Here's a stack trace from a recently-failing integration test on Travis:

```
> Task :http-client:integTest FAILED
org.triplea.http.client.WireMockSystemTest > sendErrorReportSuccessCase(WireMockServer, String) FAILED
    java.lang.AssertionError: 
    Expected: is <false>
         but: was <true>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at org.triplea.http.client.WireMockSystemTest.sendErrorReportSuccessCase(WireMockSystemTest.java:77)
```

It doesn't really add much, but there it is.

**Comment by DanVanAtta** [comment]
Options:
- file bug with wiremock and live with this in the meantime
- remove the http client testing that uses wiremock
- find a different server stub framework

As we add more http clients, this presumably would become a worse problem.

**Comment by DanVanAtta** [comment]
Please note any additional options that are available, I think that is more or less the list of choices we have.

**Comment by ssoloff** [comment]
To get further diagnostics, it might be helpful to display exactly what exception is contained in the response.  To include that in the test report, you could change the assertion to:

```java
assertThat(response.getThrown(), is(Optional.empty()));
```

**Comment by RoiEXLab** [comment]
Haven't seen the race condition in a while.
If anyone has objections, feel free to reopen
