### ISSUE TITLE
Process Question - Just close issues? Or Close pending Confirmation?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4138]
Getting into the gory details here :grinning: 

My question is, when it comes to issue/task handling, which kind of process would we prefer to have?

A) Close when work is complete and re-open if there is more to do
B) Mark as 'pending confirmation' and allow author to confirm this and close issue

If we decide A:
- we would delete the 'pending confirmation' label and close any such issues.

If we decide B:
- this is more or less status quo, no changes to labeling

With either decision we would also as an outcome of this issue have some updated documentation to note our policy.

**Comment by ron-murhammer** [comment]
No strong preference. I think I used to do B more often and now tend towards A.

**Comment by RoiEXLab** [comment]
I agree with @ssoloff

**Comment by DanVanAtta** [comment]
Thanks for feedback. (A) seems reasonable enough. I deleted the 'close pending confirmation' label. We can create a new one if we have the "verifying fix" use-case

**Comment by Cernelius** [comment]
I suggest having a "Fixed" label. That would be better telling than this label (you could label the issue as fixed and close it after a while or immediately; whatever you prefer) and would also have the use to clarify what of the closed issues have been closed for this reason. A problem would be that you would still have all the past issues not following this method; so probably better having all kind of labels, so that every new issue would get one of them before being closed, if not getting the "Fixed" one. Basically, like @veqryn used to do in the old tracker, where he would have written down fixed, not fixed, won't fix or invalid (guess you'd add the ice-box one).

**Comment by DanVanAtta** [comment]
> I suggest having a "Fixed" label. That would be better telling than this label

It seems in essence closed means this - no further tasks remaining. Looking at closed issues is not a thing that should be done unless wanting to reference previous discussions. 'ice-box' is the exception which means there are outstanding things that could be worked on in the closed issue. 

A further problem is it does not allow everyone to add the label. We could very easily have one person create an issue, another submit a PR that would close that issue. Since the PR author and issue author both do not have write, they can't jump in to add the label, it'd be an extra step for the project maintainers.

> old tracker, where he would have written down fixed, not fixed, won't fix or invalid (guess you'd add the ice-box one).

ice-box is more the "won't fix" (and because we simply haven't/can't get to the issue and it became really old). invalid is simply closed if invalid.
