### ISSUE TITLE
Resources panel includes income for capital-less nations who can't collect income

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#4224]
### Engine version

1.9.0.0.11599

### My Operating System
Ubuntu 16.04

### Map name
World War II Global 1940 Balanced Mod3

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
View resources panel. The income shows as though the capital is held e.g. 0 (+10) for France should show 0 (+0)  when Paris is not held.

### Instead of this error, what should have happened?
Show 0 income for nations without a capital.

### Any additional information that may help
It is perhaps arguable that this is a bug. However, in my view it is silly that this value contributes towards the faction's (i.e. Axis or Allies) income.

**Comment by ron-murhammer** [comment]
@simon33-2 This also leads to the question of should the players tab show the production amount for a nation that can't collect income? As I believe it currently does.

**Comment by simon33-2** [comment]
I guess that's true but it does show you how much money is up for grabs from a defeated nation and I don't find that total useful. Perhaps it is annoying if you're playing a map which has no national objectives but then you've got the total on the resources tab if we fix that.

While I'm thinking about that, on the Global maps, why is there a column for an "oil" resource which doesn't exist on those maps. Is it a map error?

**Comment by simon33-2** [comment]
One other point, in this map China has no capital and can always collect income. Presumably other maps also have that property but at least you can test it all in one map.

**Comment by ron-murhammer** [comment]
@simon33-2 Guessing that's a map error. Columns should be based on what resources are defined in the map XML.

**Comment by Cernelius** [comment]
It is usually a bit annoying having to think about subtracting the production of the players that cannot collect income, when pondering the statistics (for example, in 270BC, when GreekCityStates loses Sparta, but has a bunch of territories, that are likely to stay there unproductive for the rest of the game). However, strictly speaking, that is still production, even if it can't be used.

Also keep in mind that the production is relevant also in case of Economic Victory (no capitals required, in this case). So, removing that from the total would, instead, give problems in the moment you have to keep an eye on that victory condition being reached (would be very annoying to have to sum up each time). If the production would not be so recorded, then games having Economic Victory should have an additional column telling the relevant production value, much the same way has you have a VC column for the games with Victory Cities based victory conditions.

Moreover, you can have a game like World War II v3 1941 (as well as 1942), where you have the Production value for Chinese, that is not owning its capital (the capital being Mongolia, but this is just a hack, as Mongolia shouldn't be the capital of anything), and that is about as pointless as seeing production for players not having capitals, as the production doesn't matter at all, but you receive 1 infantry for every 2 territories you possess. So, if you would not see the production for a player that doesn't have the required number of capitals (usually 1, but it can be 0 to whatever natural), and I'm not saying it should nor it shouldn't, then probably you should not see it for Chinese, either (that I guess it would be already so, because of the Mongolia capital hack (my best guess is that hack is there otherwise Easy AI would crash)).

On the other hand, I want also to remember that the production is not telling your expected income in case you have national objectives (that are sometimes even used to take income away from you all the time; see Napoleonic Empires).

I see that the current behaviour is that the "Players" tab gives the true "Production", no matter if usable or not, while the "Resources" tab for Chinese gives your actual expected income for that player, that is always 0 (tho, one might argue it should give you the total TUV of the units that you are expected to receive). I'm thinking that this may be actually the best way, as it also avoids the two entries being purely redundant with one another, so it would maybe be better than the players without capitals still have the production in the "Players" tab, but an expected "(0)" income in "Resources" (it currently doesn't work this way, but the production is accounted in both, at least in "270BC 40%"). In such a case, an item would be, then, how to make that clear to any users (that they are supposed to go look in "Resources", to know the usable production).

**Comment by simon33-2** [comment]
I think what I suggested works and is pretty intuitive for most players except for the v3 example but even in that case getting a 3IPC unit for every 2 production is only a small error when there are only a few territories. Not sure what way fractions go in that map.

**Comment by Cernelius** [comment]
@simon33-2 Is what you suggested to have players not owning the required number of capitals needed to collect income to have it set at 0 in the "Resources" tab, but still showing fully in the "Players" tab, regardless? Guessing so, since at the first post only the "Resources" tab is mentioned, not the "Production" value in "Players".

Regarding China, or anything that gives some units for some number of territories, I said "you receive 1 infantry for every 2 territories you possess", and it would be "you receive 1 infantry for every number of territories you possess". If you don't fully possess the required number, you don't get the stuff.

**Comment by Cernelius** [comment]
>getting a 3IPC unit for every 2 production

I said: "the production doesn't matter at all, but you receive 1 infantry for every 2 territories you possess."

**Comment by simon33-2** [comment]
Perhaps China can get Kiangsu and Manchuria but the point is that the error in most cases is quite small.

Yes, what I suggest is that the players panel is unchanged. Of course, if a player without a capital gets plunder, you'd only set the income part of the display to zero but show the correct number of PUs in the resources.

**Comment by simon33-2** [comment]
Oh no I didn't know that. So then there is already some ghost income in the form of extra Chinese infantry. Not sure that's the best system. Should the income be 3IPC per 2 territories held?

The Global system for China involves them collecting income like any other power and getting to spend it at the start of their next turn but no factories or capitals are needed.

**Comment by DanVanAtta** [comment]
@simon33-2 ; @Cernelius , what is the desired outcome for this issue ticket? Can it be briefly summarized? Is this still an important item to work on?

**Comment by Cernelius** [comment]
@DanVanAtta Sorry for not answering sooner, I think I just considered to have been clear enough, and probably missed to read this reply.

My recommendations are:
- Leaving the Player tab exactly as it is (showing the production total also for nations that don't have the required number of capitals and also for nations that don't use production values), as that is showing the production raw, usable or not (and it is necessary to look at raw ownership stats when you have an Economic Victory condition, that just accounts the production, no matter if usable in any ways).
- Fix/Change the Resources tab as showing, for example, "**0 (-)**" instead of "**0 (+10)**", when the player doesn't have the required number of capitals (usually 1) to collect that resource (so the "**0 (+0)**" case would remain only in the case the player can collect resources, but has nothing to collect (this would mainly be the case of players that don't need capitals to collect, like Russians in WAW, but it is not forbidden having capitals in value 0 territories, in theory)) (practically "**(+0)**" means you can collect but have nothing, while "**(-)**" means you are unable to collect).
- Only in case of players that don't use resources at all, for example Chinese in v3 (that receives units directly based on territory number), have the Resources tab displaying as "**0 (-)**" (assuming the player as 0 saved, as it normally always should), instead of the current "**0 (+0)**" (they would still show the sum of the production values of territories they own in the Player tab, though). Alternatively (I'm not sure if this would be advisable or not; at the moment I'm thinking not), this case may give the TUV of the units that you are expected to receive, but only if the unit has any TUV assigned, in a production frontier or anything (for example, if Chinese holds 4 territories, thus would receive 2 infantries, the Resources tab might list the player as "**0 (+6)**").
- As an additional item that needs to be fixed (I consider this an actual bug), the income from National Objectives is already accounted in the Resources tab, which I agree it is a good thing, but that has the issue that it is still accounted in the case the player cannot collect it, for failing the general capital requirement, if the capital is not directly specified as a (redundant) requirement by the objective code in the xml. So, this should be fixed too, in that national objectives should not be accounted in the resources flux (the part between parentheses) in the Resources tab if you cannot actually collect them (for missing the general capital requirement or whatever). For a test example, you can see that, in v3 1941, Russians is given, in the Resources tab, the +5 from Archangel free of allies also if the "Russia" capital is enemy owned (just edit it to an Axis player), while this should not be the case, as Russians will not collect that +5 (or any other national objectives) if it doesn't have its capital (you could fix this in the game itself by assigning the "Russia" territory as an additional condition to "Archangel", in the specific national objective itself, and do the same for all national objectives not having the respective player capital as specific requirement, but that would be purely redundant coding).

**Comment by simon33-2** [comment]
I endorse Cernel's post. Felt the need to post that even though liking the post should be enough. In particular:
- Players tab remain unchanged
- Resources tab has two modes. 
  - Normal game mode should exclude the income from powers who require capitals to collect income but the capital is not held.
  - History mode only shows the objective bonus in the parenthesis - in this mode I love the idea of (-) but could still live with (+0)
- In v3, I've never played this map but I like the idea of "0 (-)"
- I totally agree that the value in the parenthesis being counted for the alliance total in the resources tab being an actual bug.

**Comment by ron-murhammer** [comment]
@Cernelius @simon33-2 So essentially this boils down to have the resources tab consider whether the player meets capital ownership requirements when displaying income for territories and objectives.

**Comment by Cernelius** [comment]
I believe this should be all, as per my suggestions:

Test if the player meets all these requirements:
`"player"` is `optional="false"`
`retainCapitalProduceNumber` (default=1) is greater than the number of `"capital"` territories the player has assigned and currently owns.
or this requirement:
`"step"` `delegate="endTurn"` is absent for the player

then the resource flux in the Resources tab is given as "(-)" (this should cover also the problem of Objectives income being accounted also for players having not enough capitals to collect it).

Theorically, one may argue you should also multiply the resources flux for as many `delegate="endTurn"` that player has in `gamePlay` (normally every player has only 1), unless that flux is meant to tell how much you are going to get in any of that phase, not how much you are going to get in a whole round (though, in this case, one may argue the value should be given also for those that are missing the phase, that is having 0 of them, if that is not telling the number of such phases at all). I'm not sure about it, but I tend to think not, but, on the other hand, if you give nothing when the player has no `"endTurn"`, I guess it would be consistent, for example, giving double when it has two.

Also keeping in mind that a player may have `"endTurn"` delegates in only some of the rounds.

**Comment by Cernelius** [comment]
I'm actually not sure how it should work if the player would have `"endTurn"` delegates in only some of the rounds.

**Comment by DanVanAtta** [comment]
Moving feature request to forums: https://forums.triplea-game.org/topic/1699/resources-panel-includes-income-for-capital-less-nations-who-can-t-collect-income

Per (newly documented) feature request tracking policy: https://github.com/triplea-game/triplea/wiki/Bug-Report-And-Feature-Request-Tracking
