### ISSUE TITLE
territoryEffectAttachment – /+ movement effect?

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#4226]
### Engine version
1.9.0.0

As of now erritoryEffects seems limited to: combatOffenseEffect, combatDefenseEffect, noBlitz and unitsNotAllowed

I think, as movement is a very basic unit stat, it would be fitting to also have something like “movementEffect” that could slow or speed up units, like in swamps, mountains, reef filled waters, paved roads, flat plains etc.

I actually don’t understand why this was not an engine feature from the get-go. Movement seems to be such a basic stat in TripleA. It is wired that the engine supports unit att/def boosts/nerfs, but movement boosts/nerfs has to be handled via invisible units or other workarounds :-(

**Comment by ron-murhammer** [comment]
@FrostionAAA - The biggest reason for that is that having varied movement costs for territories makes route finding significantly more complex. It also opens up questions like if I have 1 movement left and a territory takes 2 movement then can I move there? (as well as a few similar questions)

The other thing is whether movement cost should just be part of the core territory attachment or even be enabled my unit attachments rather than territory effects (or all of them). As you can imagine being able to build road/rail/path/etc units not just static territory effects.

**Comment by FrostionAAA** [comment]
Well, in Civilization when a unit has 1 Move left and you move it, it can move into a "requires 1 move" territory but not into "requires 2 move" territory.

But my thoughts was that in TripleA, the territory affected the unit after it has arrived and therefore the unit was first affected when standing in the territory, like when it has just moved into it or when the unit started its turn in there.

**Comment by ron-murhammer** [comment]
@FrostionAAA Well actually only Civ6 I believe handles it that way. All previous Civ versions allow you to move to any cost territory if you have >0 movement left (I could move into say a 3 cost mountain territory even if I have only .1 move left). I've seen games do it either way and not sure which is really the best option.

Though either way I think would be ok. The biggest challenge is still route finding as once you have territories that cost varying amounts of movement route finding is much less straightforward.

**Comment by Cernelius** [comment]
Instead of territories or units, wouldn't be better this being related to the connections? Meaning, for each connection, you can set how much movement points it costs, default being 1.

This could be, then, expanded as to be also able to set a combat modifier for units that moved through a connection to enter combat, similarly to the isMarine option, that is related to unloading, instead.

Typical example, borders with a major river.

For stuff like highways and such, that would be certainly better as units, instead, expanding the current functionality of giving movement as to require all movement being made on territories having such unit, to get the bonus, rather than just the starting one.

**Comment by ron-murhammer** [comment]
I'm going to close this feature request in favor the the forum post as I think the discussion fits better there: https://forums.triplea-game.org/topic/1183/terrain-effects-for-movement
