### ISSUE TITLE
isInfrastructure units can't retreat

### ISSUE THREAD

**Issue by panguitch** [triplea-game/triplea#442]
Units with isInfrastructure=true can't retreat from battle. Instead they are destroyed.

For example, AA guns that can move during combat and join in an attack. If the rest of the army retreats, they get left behind and destroyed.

Unless they also have a regular attack value, or a support attachment, in addition to their AA function. Then the engine keeps them in the battle and allows them to retreat with the rest of the army.

Cernel explains here: http://tripleadev.1671093.n2.nabble.com/Help-me-get-my-AA-to-retreat-tp7591174p7591181.html

**Comment by ron-murhammer** [comment]
@panguitch - If you have a save game to reproduce this issue that would be helpful.

**Comment by panguitch** [comment]
Cernal recommended I create a save game example using feudal japan. Honestly, I've never played feudal japan and I don't know that it's particularly popular, and I can't think which other maps have infrastructure units that can move in combat, so I'm just going to give you a save game using Greyhawk Wars 1.0.

[http://tripleadev.1671093.n2.nabble.com/file/n7591174/bomancantretreat.tsvg](http://tripleadev.1671093.n2.nabble.com/file/n7591174/bomancantretreat.tsvg)

Here you can see the bowman fires at the dragon, but isn't really considered part of the battle. So when the army retreats, only regular units are included. Bowman is left behind and destroyed, perhaps because it has an "is destroyed if captured" property.

The hero/leader unit is isFactory, which means it is also isInfrastructure. But it retreats just fine, probably, as Cernel says, because it's a support unit and included in the battle.

**Comment by DanVanAtta** [comment]
Feudal japan recreates easily with horses. The horses are not part of the battle, and so when the retreat happens they are left behind. The end battle logic kicks in and sees they are capturable in enemy territory, and they are then captured.

**Comment by ron-murhammer** [comment]
@veqryn Any thoughts on this bug? The issue appears to be that infra units that don't have combat stats get removed from battles: https://github.com/triplea-game/triplea/blob/master/src/main/java/games/strategy/triplea/delegate/MustFightBattle.java#L2340

Is it necessary to remove them or is it just so they don't clutter the battle window?

Trying to determine whether it would be best to just not remove them from the battle in the first place or if they need added back into the potential retreat units.

**Comment by veqryn** [comment]
Could the map just add the field to prevent them from being moved during combat-move?  That way they wouldn't be in the attack in the first place?
I'd find it very funny to have your naval base get moved with the retreat...
Also, how does the `doNotIncludeAA` parameter work in that match?  (sorry, i don't have my ide setup right now with the project)

**Comment by panguitch** [comment]
The problem is if you want to let some kind of AA unit be offensive and join an attacking force. It works, firing at air units before the battle, but unlike other units, it doesn't have the ability to retreat.

**Comment by ron-murhammer** [comment]
@veqryn As @panguitch mentions, they are meant to be moved during combat move. Essentially think of revised but players allowed to attack with AA guns not just defend. I think the issue mostly boils down to the meaning of isInfrastructure. It seems to be used for anything that doesn't have hit points not just factories/naval bases/etc. `doNotIncludeAA` isn't relevant here as its set to false.

**Comment by veqryn** [comment]
I seem to remember other maps solving this somehow, and having offensive AA.
Anyway, solve however you see fit.

**Comment by ron-murhammer** [comment]
@veqryn Yeah, what folks have done is add a 'do nothing' support attachment that provides 0 support value. The method keeps all units (even isInfra ones) that have any support attachment so this is kind of a hack to allow attacking infra to be included and therefore retreat.

**Comment by Cernelius** [comment]
I think it would be cool to have an option for isInfrastructure only that allows to choose if the infrastructure can retreat or, upon retreat, it remains in the attacked territory and gets lost.

Also, there is the problem that an air + infrastructure you send in attack gets captured when you retreat, while I surely believe it should just hover on the attacked territory, like all other air units, after a retreat. Especially if we decide that land + infrastructure can successfully retreat, the way any land retreats, **then I think it would be obvious to fix air + infrastructure to successfully retreat, the way any air retreats.**

 Also, I believe that if you lose a battle, in attack, losing all your not-infrastructure units, the air + infrastructure units should just hover on the territory, instead of being captured, like it happens to the not-air infrastructures, because, you know, the air infrastructures are flying over the territory, so I don't see why they should be captured, when attacking.

I think it would be cool having aeroplanes that are infrastructures. Simple example is a transport air unit, conceptually similar to the transport horses of Feudal Japan, but flying, but the issue that it gets captured when you retreat is a big problem. Myself, I would actually make all air units into infrastructures, if they would work in a sensible manner (not captured when you retreat nor when you lose the battle anyways, by losing all not-infrastructure units in attack).
