### ISSUE TITLE
Blurry Image with installer

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#4442]
Noticing this for a while now, but I wanted to resurrect #746 again.
Basically the installer somehow doesn't work really well with a zoom setting that isn't 100% on windows:
Installer 100% Zoom:
![100% Zoom Installer](https://user-images.githubusercontent.com/8350879/50162620-184a5d00-02df-11e9-880b-20b4194e9e50.png)
Installer 125% Zoom:
![125% Zoom Installer](https://user-images.githubusercontent.com/8350879/50162681-37e18580-02df-11e9-9b67-aa8dd62ad496.png)
Running from source 125% Zoom:
![125% Zoom Source](https://user-images.githubusercontent.com/8350879/50162739-5778ae00-02df-11e9-8662-f891187ff04e.png)

Haven't tried out java 9 or something that's supposed to fix a couple of HiDPI issues (or a more recent TripleA version with a newer version of Install4j)
But this is definitely something we should report if its still present in more recent versions.
Thoughts?

**Comment by Cernelius** [comment]
I said this about 2 years ago. Anyway, it has always been so since I started using the installer. Haven't tested it in some time, but if you, instead, use the "all platforms", there is not this behaviour (at least last time I did).

The other thing that I reported is that Windows zoom zooms the custom cursor too, making it pixelated and very bad looking. Moreover, it zooms the image but not the hotspot, so you can see, for example in Pact of Steel, that the target will be off.

The other issue was that the purchase etc. Windows were sized incorrectly, providing scroll bars as default, but that has been corrected by @ron-murhammer some time ago.

The above are the reasons why, in the past, I suggested to keep the all platforms available (and with the "exe" inside!) for any users to download, like it was during veq-old times.

I've no idea how windows users, with the commonly used zoom, can guess anything else but TripleA being a seriously bad looking blurred game, and that's it, after they install it (it looks really bad to me; try it at 150% zoom...).

**Comment by DanVanAtta** [comment]
Does this problem happen when you install with zoom turned on, or does this happen whenever the game is launched and zoom is turned on?

This is an odd one as in theory there is little different between the installer and stand-alone jar. 

@Cernelius do you remember if this was a problem on the 1.7 series and before?

**Comment by Cernelius** [comment]
This never happened to me before 1.9, as long as I remember, but I suppose this was due to the fact that I always used the all platforms zip, instead of any installers, and I recall this problem happened using the installer but not using the all platforms, early in 1.9. Practically, what I remember happened was that the all platforms had TripleA working pixel by pixel, thus looking good, while the installer used to expand TripleA by the specified Windows zoom, thus looking blurred.

I've not tested this issue again in more than 1 year, as it is a long time I just keep the general windows zoom at 100%, also since that causes issues with the custom cursors too.

**Comment by DanVanAtta** [comment]
@Cernelius which (exact) version of java do you have installed?

**Comment by DanVanAtta** [comment]
I'm thinking we might have a JDK problem, there are not many differences between the all-platforms version compared to installer. Something like this could be the issue: https://bugs.openjdk.java.net/browse/JDK-8156149  "Blurry rendering on Windows 7 at 125% screen setting"

**Comment by RoiEXLab** [comment]
@DanVanAtta I recall having this issue too in the past on my laptop.
My best guess at the moment is that it's caused by the windows zoom setting (125% on my laptop). Not sure if this changed in java 11 though, there were some minor improvements to swing I noticed (sideway scrolling now fires a normal mousewheel event with shift down mask it seems)

**Comment by RoiEXLab** [comment]
Nevermind, you googled faster than I could type

**Comment by DanVanAtta** [comment]
@Cernelius or @RoiEXLab can you confirm if this is still a problem?

**Comment by RoiEXLab** [comment]
@DanVanAtta If @Cernelius doesn't check until Friday I'll have enought time to check myself.

From the linked JDK issue it seems this problem was fixed in JDK 9

**Comment by RoiEXLab** [comment]
Also I didn't realize I opened this issue in the first place, but it makes sense now that I knew what the underlying problem was ^^

**Comment by Cernelius** [comment]
I could test, but, then, it would be still up to @RoiEXLab, so I guess it makes more sense for me to wait, and eventually double check what he checked, in case it gets fixed.

**Comment by DanVanAtta** [comment]
@Cernelius that does not quite make sense; if you're going to double check anyways, why not go ahead? :grin: 

There's nothing special in terms of this verification, anyone that had the original problem can verify if it's gone with the latest prerelease. We fixed nothing, the latest prerelease has a more recent version of java compared to 1.9

**Comment by RoiEXLab** [comment]
Yup, I can 100% confirm this is still an issue

**Comment by Cernelius** [comment]
I meant, if this gets fixed, I'll see if it's fixed for me too. Maybe consider the custom cursors too, they get zoomed as much, and in a very raw way. It would be good both the map and the custom cursor (meaning the skin in general) are not affected.

**Comment by RoiEXLab** [comment]
Well the problem is not really on us.
Something is wrong with install4j that causes this, because if I run the game from source code directly, I don't have any problems whatsoever.
I mean workaround is to go to your windows settings and set thr zoom level of your display to 100% when playing.

@DanVanAtta Might be worth upgrading install4j to see if that fixes the issue

**Comment by Cernelius** [comment]
Or still providing an all platform (zipped without installer) version, with the exe and all included, for easy of use, and advising Windows users to preferably use that over the Windows installer.

Not like this is the first time I'm suggesting keeping the all platform available, by the way. Not sure if one of the various release options here is like the old all platform, but that's definitely not for the common user.

**Comment by DanVanAtta** [comment]
@RoiEXLab see if you can launch the game with the same JRE bundled with install4j. The key difference is that, once you have the files deployed on system, the fact it was deployed with install4j should be immaterial.

> advising Windows users to preferably use that over the Windows installer.

No. Otherwise what's the point of an installer at all? Why even create or have it at all?

Warning users if they have a zoom over 100% would be useful though, but better we just fix this problem.

**Comment by RoiEXLab** [comment]
Launching triplea using cli directly (with just the bundled JRE) works completely fine.
Only when using the exe, the image is blurry.

The exe is also responsible for the splash screen, so that might have something to do with it

**Comment by DanVanAtta** [comment]
Okay, thanks for checking. If the problem is in the EXE, we should then confirm if latest install4j has the same issue and try a variety of the JDK options to rule them all out or find one that has no issues.

**Comment by Cernelius** [comment]
>Only when using the exe, the image is blurry.

What do you mean? You mean that if we would have an all-platform zipped with an exe inside it would still have the same problem? Did you create such a non-installed-but-with-exe package and test it?

**Comment by Cernelius** [comment]
Cause I remember than when the all platform was still available it worked fine also by just pasting the exe into it (after having unzipped it), to run it. Only the installed version had this problem, but, again, years since then.

**Comment by Cernelius** [comment]
>Warning users if they have a zoom over 100% would be useful though, but better we just fix this problem.

By now, it is years that Windows users (I assume all of them using a non 100% zoom) have this problem. I reported it a long time ago, for a time keeping using the all platform, then, myself, just switched the zoom to 100%. It's by now more than 2 years that I keep Windows at 100% zoom.

I'm actually surprised nobody complained. I assume that people that have this issue can do nothing else but assume that TripleA just looks bad like that normally; so not much to say.

Also, please, don't forget about custom cursors, that are affected by this too.

Side note, there were also resize issues with Windows zoom for the game's windows, like the purchase screen, but @redrum fixed those. Not sure if that may be of any help for fixing this matter too.

**Comment by DanVanAtta** [comment]
For context, are we talking text zoom, or zoom of everything? Can someone detail where the setting is exactly, to be sure we are all looking at the same thing.

**Comment by RoiEXLab** [comment]
Windows isn't overly specific on this. It says "Text, Apps and other elements"
![Screenshot](https://user-images.githubusercontent.com/8350879/65416024-3b1e1a80-ddf7-11e9-8f89-3b952298e713.png)

**Comment by RoiEXLab** [comment]
@Cernelius 
> What do you mean?

Exactly what I was saying. If I use the exe generated by install4j, the image is blurry, if I don't use it it's clear.

**Comment by Cernelius** [comment]
> @Cernelius
> 
> > What do you mean?
> 
> Exactly what I was saying. If I use the exe generated by install4j, the image is blurry, if I don't use it it's clear.

How about if you paste the TripleA package without installing it (like in the old all platform), then add an exe file to run it, still without using any installers?

From what you said, it sounded like the problem was running it through an exe, while I remember there was no problem back then we had a zipped all-platform package with the exe included.

**Comment by Cernelius** [comment]
@DanVanAtta I believe the general Windows zoom is supposed to zoom everything. If it does it with absolute consistence, I cannot say, since I'm not using it in years (actually stopped using it because of this issue here).

**Comment by ssoloff** [comment]
> The above are the reasons why, in the past, I suggested to keep the all platforms available (and with the "exe" inside!) for any users to download, like it was during veq-old times.

@Cernelius Note that the "all platforms zip" is still available, but it was renamed to **triplea-game-headed-\<version\>.zip** a year or so ago.  After downloading it, unzip it, open a command prompt in the folder to which you unzipped it, and then run `java -jar bin\triplea-game-headed-<version>.jar` to start TripleA, replacing `<version>` appropriately (or just use <kbd>Tab</kbd> completion after typing the `bin\`).

**Comment by DanVanAtta** [comment]
@Cernelius  / @RoiEXLab would either of you mind checking the latest? The installer software has been updated to a new major version and the bundled JRE is now more recent too.

**Comment by RoiEXLab** [comment]
Thanks for the reminder, will check later this evening.
Will also review the PRs then

**Comment by RoiEXLab** [comment]
Good news, looks like they fixed this issue 👍
