### ISSUE TITLE
Middle Earth Battle for Arda Incorrect file for the Bots

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#4476]
The bots do not have the updated current 2.0.7 listed in the game downloader.  Thus they keep asking players to download the map.  Is this just a minor update for Infra?  I thought they were automatically updating now?  @RoiEXLab @ron-murhammer @ssoloff

**Comment by ssoloff** [comment]
I just looked at all four bot Linodes, and they each have version 2.0.7 of battle_for_arda installed from 2018-10-08T20:08:50Z, which is the most recent update reported by the GitHub API.

For example, from bot65_tokyo_jp:

```
admin@bot65_tokyo_jp:/home/triplea/maps$ more battle_for_arda
"updated_at": "2018-10-08T20:08:50Z",
admin@bot65_tokyo_jp:/home/triplea/maps$ unzip -p battle_for_arda-master.zip battle_for_arda-master/map/games/Battle_For_Arda.xml | head
<?xml version="1.0"?>
<!DOCTYPE game SYSTEM "game.dtd"[]>
<game>
  <info name="Middle Earth - Battle for Arda" version="2.0.7" />
  <loader javaClass="games.strategy.triplea.TripleA" />
  <triplea minimumVersion="1.9" />
  <diceSides value="12" />
  <map>
    <!-- Territory Definitions -->
    <territory name="West Methedras" />
```

So, it appears the infrastructure _update_maps.sh_ script is working correctly.  Not sure what the problem may be.  Tagging @DanVanAtta just in case.

**Comment by prastle** [comment]
The bot when you load it says 2.0.4
Thanks for looking @ssoloff

**Comment by ssoloff** [comment]
It looks like the problem is there are two "Battle for Arda" maps installed on the bots:

1. battle_for_arda (version 2.0.7)
1. the_battle_for_arda (version 2.0.4)

the_battle_for_arda was last updated on 2018-08-28.  It looks like the repo got renamed sometime between August and October.  Because the_battle_for_arda proceeds battle_for_arda lexicographically, I suspect the last one wins, and that's why you're seeing 2.0.4 in the bots.

Manually deleting _/home/triplea/maps/the_battle_for_arda*_ on all bots may resolve the issue.  I don't think infrastructure yet handles maps previously downloaded that no longer appear on GitHub.  That may be a new requirement we have to handle. /cc: @DanVanAtta

**Comment by prastle** [comment]
Thanks.  Did you manually delete them?  Will the bots auto pickup a missing map?

**Comment by ssoloff** [comment]
@prastle I did not manually delete them.  The bots probably have to be restarted to pick up the correct map after the old map is deleted.

**Comment by prastle** [comment]
Ok I can restart them all as they empty if you don't mind deleting the files.

**Comment by ssoloff** [comment]
Sure, I can delete them, but it'll have to wait for a few hours.

Note that there will be a window between the time the maps are deleted and the bots are restarted where there is a possibility of a user receiving an error if they happen to select Battle for Arda during that time (because the map file will be missing).

**Comment by RoiEXLab** [comment]
Off-Topic, but gitter email notifications come with way too much delay:
@ssoloff Regarding the forum problem, it's time for the plan B you proposed

**Comment by ssoloff** [comment]
@RoiEXLab Okay.  So, if you reset the `root` password via Linode , you should be able to login as `root` via Lish and restore the permissions on your home directory, right?

**Comment by RoiEXLab** [comment]
Yeah I hope so. I just wanted to have on on board, so that I can give you the permissions as well while I'm at it. Let's continue this discussion on gitter

**Comment by prastle** [comment]
Yes I have done it before
It will work @ssoloff @RoiEXLab

**Comment by ssoloff** [comment]
@prastle `the_battle_for_arda` has been removed from all four bot servers.  (It wasn't present on `PreRelease`, so no need to do anything there.)  I'll reply in Gitter regarding restart commands.
