### ISSUE TITLE
Map Downloads: download content size not working

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4482]
## Java
1.8.0_181-b13

## Version
1.10.dev @ bcd589d3266b7de3fd5a3f38d4e1dfe23b0fc5e8

## Problem
- http head request to download length for map files appears to never be returning data.

## Impact
- we do not display map download size in maps window
- map download progress bar will _not_ show percentages but instead just a spinner

## Repro
Repro:
- launch headed game
- open download maps
- select any of the map titles in the 'available' list

Notice:
- size of map download does not appear next to the map title

![screenshot from 2019-01-02 15-06-13](https://user-images.githubusercontent.com/12397753/50618063-55991800-0ea5-11e9-95f6-eea64573daaa.png)

Repro (2)
- launch headed game
- open download maps
- uninstall Total World War (if installed)
- select Total World War (reason: it's a very large download)
- start download

Notice:
- notice the progress bar never switches to percentage, stays a spinner indicating we never get the total download length

**Comment by ssoloff** [comment]
I remember looking into this back in 2017.  I forget the details, but it came down to GitHub simply not sending the `Content-Length` header for dynamically-generated archives (which the maps are).

IIRC, the experiments I performed at the time showed that GitHub would cache the zip archives it generated on-the-fly for some period of time.  So that the first time (in a long time) one requested a map (using either HEAD or GET), no `Content-Length` header was provided.  But on subsequent requests, the `Content-Length` header would be provided until the cached archive "expired."  It's possible that, as of today, GitHub is no longer even caching the dynamically-generated zip archives, so that the `Content-Length` header will never be provided.

A bit off-topic, and I'm pretty sure this has been discussed before, but I was going to suggest that we consider moving map "releases" to GitHub releases.  That might solve the long-standing versioning problem we have.  Namely, that there's only one version of a map ever available from the in-game downloader.  However, I just tested sending a HEAD request for one of our client artifacts to see if it consistently returned a `Content-Length` header.  Apparently, those artifacts are hosted in Amazon S3, which seems to be configured to deny HEAD requests.  But, via GET, the `Content-Length` header is indeed consistently returned.

So, if we were to use a GitHub releases approach, we would not be able to provide a "preview" of the download size in the Download Maps window, but we would be able to provide an accurate download percentage upon initiating the GET.

**Comment by DanVanAtta** [comment]
Some history, when we migrated from SVN to github repos, the script that automatic the conversion of a 'zip' to a github repo included a travis build script. This was later removed in favor of having a download address that is static. In part this was done as there was little incremental development and tended to be large merges updating maps to new release versions.

Meanwhile the travis element introduced a few challenges:
- mass updates were slightly tricky
- managing all the updates, ensuring they all triggered and all releases build was tricky
- overhead for maintaining scripts that checked all maps were in configuration at latest version
- in mass, travis+github releases did not always work really well
- the changing URL and concept of 'latest' were all yet one more thing adding to the learning curve for map makers

I think maps likely should be restructured. I'd like to see XML files land in a single repo. Overall, I don't think we should solve the download length problem by changing how the maps are hosted.

Not having a reliable `Content-Length` seems a bit like a deal-breaker for using http head requests. The intent behind download-length is to give a sense that there *is* progress, for a long time TripleA just had a spinner bar only. We could do that by switching from a percentage indicator to how many KB have been downloaded. I think that'll simplify things up in the code as well.

There are some more options, like we could add file-sizes to the download description file, but overall I think we should favor going simple here.

**Comment by RoiEXLab** [comment]
@DanVanAtta What about having map makers create tags whenever they want to release a map update instead of having to update the main file?
This would work similar to an release, won't require and automated build, and the "source file" size might be pre-calculated (this is the thing we should check).
If the tag would also contain compatibility information, we could solve 2 problems at once, by having the client check the latest version that's compatible with itself.

**Comment by DanVanAtta** [comment]
@RoiEXLab given the current learning bar I'd be reluctant to complicate things any further. IMO how the maps are hosted should be changed in a more dramatic fashion, in the meantime I would not recommend we make such changes and focus instead on the better design changes, or getting map makers on the current system at all.
