### ISSUE TITLE
Selecting "No" in the "Leave Game" or "Exit Program" dialog box causes "Quit" menu item to not pop up "Exit Program" dialog box (nothing appears, game does not exit).

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea#4525]
### Engine version

1.9.0.0.13066

### My Operating System

OS X Mojave 10.14.2

### Map name

World War II v6 1941

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

Select "Quit" after starting a game, then click "No" when prompted in the "Exit Program" dialog. Or, select "Leave Game" and do the same thing when prompted. Subsequent selection of the "Quit" menu item yields no dialog box, and the program fails to exit. This appears to persist even after selecting "Leave Game" and closing a map. Only restarting the entire program fixes it.

### Do you have the exact error text? Please copy/paste if so

No error text.

### Instead of this error, what should have happened?

An "Exit Program" dialog box should pop up, allowing the program to be exited.

### Any additional information that may help

This also happens on a later 1.10 test build.

No save game attached, as this is easily reproduced and not specific to a particular map.

**Comment by panther2** [comment]
Is that OS-related? I cannot reproduce the issue on Windows.

**Comment by ssoloff** [comment]
@panther2 Yes, this is specific to macOS.

I hesitated earlier today to create a new **macOS** label for issues specific to Macs.  However, your two recent comments made my decision for me. :smile:  I'm not sure if the other devs will agree, but macOS-specific problems are kind of special for us at the moment because it's very hard for us to address them due to lack of resources.  Therefore, I felt calling them out loudly with a label is probably not a bad thing.
