### ISSUE TITLE
Duplicate "About" window able to be created when "Produce" window is active

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea#4526]
### Engine version

1.9.0.0.13066

### My Operating System

OS X Mojave 10.14.2

### Map name

World War II v6 1941

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

Start a Local Game with the Russians as an AI player, and the Germans as a Human player, immediately select "About" from the TripleA menu dropdown, and leave it open until the German player's turn starts and the "Produce" screen appears. Select "About" from the TripleA menu dropdown again, and a second window will be produced.

### Do you have the exact error text? Please copy/paste if so

N/A

### Instead of this error, what should have happened?

The existing, already open TripleA window should be brought to the forefront, or no new window should be opened (probably the latter).

### Any additional information that may help

![second about page](https://user-images.githubusercontent.com/4445057/50733657-22c17f00-1146-11e9-9829-68ad65217f0c.png)

**Comment by panther2** [comment]
@ssoloff Here I fail to reproduce the issue on Windows, too.

**Comment by ssoloff** [comment]
@panther2 Ditto on this being a macOS-specific problem.

**Comment by DanVanAtta** [comment]
The code behind the about window is Mac OS specific.

OS specific code has a high cost. I wonder if it is worthwhile having the about menu being OS specific, perhaps it's not worth the testing effort we are putting into here.

@tvleavitt, @RoiEXLab any thoughts if the about menu were to be made into a standard menu instead of being Mac specific? Presumably it would not be a good thing, but I'm wondering in terms of an ongoing ROI if it's really worth having, particularly if there are problems with it that nobody can really test and ergo not really fix.

**Comment by asvitkine** [comment]
I can't repro anymore with current release. Possibly because we're no longer implementing a custom about window (we just get a standard one that has the app icon and version number). Closing.
