### ISSUE TITLE
requiresUnits and consumesUnits Placement Enhancements

### ISSUE THREAD

**Issue by sneakingcoward** [triplea-game/triplea#461]
sneakingcoward

following enhancements should be also done:

correction of option name="requiresUnits" and option name="consumesUnits"

When using this 2 unit attachments, there are problems with unit placement.
For landunits production and placement territory are the same, but for ships not and also not for "place new fighters on old carriers".

a.) option name="requiresUnits"
Here only the PRODUCTION territory is checked.
In case of ships additional also the PLACEMENT territory should be checked.
Generally the production & placement territory should be checked in this order.

b.) option name="consumesUnits"
Here only the PLACEMENT territory is checked.
In case of ships additional also the PRODUCTION territory should be checked.
Generally the production & placement territory should be checked in this order.
Also valid for "place new fighters on old carriers".

**Comment by DanVanAtta** [comment]
@sneakingcoward  - is there a map that demonstrates this? Not finding any maps with this option. An XML snippet would be of help too.

**Comment by sneakingcoward** [comment]
hello,
map would be
https://sites.google.com/site/tripleamarshal/home/world_at_war_variants.zip
take the game: world at war variants - vXXX

it uses recruits which are land based.
ships or planes produced on carriers are sea placed when produced.
therefore  requires and consumesUnits doesnt work.

sneakingcoward

**Comment by sneakingcoward** [comment]
ships have this argument
<option name="requiresUnits" value="Shipyard"/>
<option name="consumesUnits" value="1:Recruit"/>
fighter planes have this
<option name="requiresUnits" value="Aircraft"/>
<option name="requiresUnits" value="Carrier"/>
<option name="requiresUnits" value="BigCarrier"/>
<option name="consumesUnits" value="1:Recruit"/>

**Comment by sneakingcoward** [comment]
is it still open or solved ???

**Comment by Cernelius** [comment]
If the developers are fine with other people commenting on the labels assigned, this is not a Bug, but a Feature Request. I also wish to underline that the only two modificative elements (other being expansive) is having the production checked before the placement for "consumesUnits", that would have, for example, your fighters on land consumed before your fighters on sea, when you are upgrading one on sea, and the ability of "requiresUnits" to work both on the production territory or in the placement sea zone, which seems weird (for example, a flying-factory air unit can act as factory only on land, while here required air units would allow land factories to probuce both if being in land and sea). Would be interesting to ear the arguments behind this, as I'm not sure of its opportunity.
Also, I believe you should make sure that you can consume a fighter on land to place an upgraded one on sea only in case you would be able to place such a fighter if not an upgrade (there are several properties setting this, in different cases), otherwise this would be modificative of the current behaviour too. For example, I think it would make sense that you are able to consume a Fighter on land to place an upgraded one on sea only in case you are also able to move such an existent Fighter during placement, which is property related.
I suggest to fully define all the dependencies with respect to the current significative properties and I also believe it would be needed a good argument to have the order of production then placement territory for the "consumesUnits", since now it works only (thus starting from) the placement territory.
Myself I tend to think that these are mostly good ideas, especially the ability to consume units on land (or a combination of land and sea) to place your ships on sea (main example being that you have your launched hull, but still needs both the hull and additional components from the land to proceed upgrading). The dubious part, I believe, is related to those units that can stay both on land and on sea, which means aeroplanes.

**Comment by Cernelius** [comment]
Yet, I think the limit of consuming units only in the sea zone may be considered a bug for air units that need land units to be consumed, but are otherwise supposed to be placeable on carriers (which would then become possible for the basic ones, but not for the upgraded ones, which makes no sense). Still more a limit of the engine that a true bug, in my mind, tho I'm not sure when something starts to be a bug, when we don't have a ruleset we are supposed to clone. Maybe an additional category of "Limits" in between of "Bugs" and "New Features" may be good for all the half-backed stuff not referring to some official ruleset to complete?

**Comment by Cernelius** [comment]
To be clear, I'm favourable to all these things being made the way sneakingcoward describes (tho I'm not sure if it is better to have production then placement for consume or the other way round, which would be closer to current), tho this can create some weird situations for aeroplanes, but quite surely an improvement over the current limits, pretty much. I've no plans myself on such things, right now, but especially being able to consume units on land to upgrade your ships sounds like a neat improvement.

**Comment by Cernelius** [comment]
> Also, I believe you should make sure that you can consume a fighter on land to place an upgraded one on sea only in case you would be able to place such a fighter if not an upgrade (there are several properties setting this, in different cases), otherwise this would be modificative of the current behaviour too.

I meant for example being able to move the existing fighter on a new carrier, if you can consume it to place an upgraded one on sea (otherwise you would be able to move existing fighters on carrier when upgrading them, but not otherwise).

**Comment by sneakingcoward** [comment]
a.) option name="requiresUnits"
Here only the PRODUCTION territory is checked.
b.) option name="consumesUnits"
Here only the PLACEMENT territory is checked.

with my map world_at_war_variants there are also all features used, available for aaa.
i use also recruits which are consumed by placed units.
this error is then only happening with ships, where production is not the same as placement territory.

its definitely a bug and can be solved quickly, for ships at first production and then placement territory is checked for both unit properties.

**Comment by Cernelius** [comment]
Well, I think it is not a bug because I believe the consumesUnits was meant to have a limited use like upgrading a Hull on sea to a Battleship (or anyway only upgrading units in the same territory or sea zone), and not meant to cover more cases; but, as I said, it would be surely good to expand it to be able to also consume units on land to place units on sea, tho there may be some issues related to aeroplanes (all good and purely expansive when all units involved are only land or sea ones).

**Comment by Cernelius** [comment]
Just to be clear, again, by saying that this is not a bug (of which I'm surely convinced), I did not meant in any ways to lower the importance of this proposal.
**I think being able to consume land units to place sea units (as well as air units on sea) would be a great improvement.**
Also, in view of what Hepps said in forum, about having a battleship started on land and, at some point, getting launched, this would support it in a good way, not by using a fighter with carrier cost 0, which is a hack and might be problematic (I've some concerns I didn't test).
The only one correction I suggest is the consumed unit being a land unit only (consuming air units working only if the air unit is where you are placing), to avoid the issues I mentioned. Then, it could be still somehow expanded to include air units. Just talking about the consumed units on land to place on sea; the upgrade itself, placed on the sea, may be either a sea or an air unit, of course (and can't be a land unit by definition).

Minor note, the title is reading "bug fixes". While I don't agree that it is a bug, I tend to agree that it is sort of a "fix", as if you consume a land unit to place a sea unit, that can only be from land. A remaining item to test would be to make sure that dependent units (like land units on transports) are never upgraded.

**Comment by sneakingcoward** [comment]
hello,

 

when recruits are used, then placing a ship (general sea unit) can consume a hull in the placement seazone or/and a recruit on the production landzone.

so for placement following order for consume and also for require: 1. looking at production landzone and 2. looking at placement seazone.

 

if bug or fix....it should be done.

the recruits model otherwise works fine, only this makes annoying.

 

sneakingcoward

 

Gesendet: Montag, 26. Juni 2017 um 08:06 Uhr
Von: Cernelius <notifications@github.com>
An: triplea-game/triplea <triplea@noreply.github.com>
Cc: sneakingcoward <wgbt@gmx.at>, "State change" <state_change@noreply.github.com>
Betreff: Re: [triplea-game/triplea] requiresUnits and consumesUnits placement bug fixes (#461)


Just to be clear, again, by saying that this is not a bug (of which I'm surely convinced), I did not meant in any ways to lower the importance of this proposal.
I think being able to consume land units to place sea units (as well as air units on sea) would be a great improvement.
Also, in view of what Hepps said in forum, about having a battleship started on land and, at some point, getting launched, this would support it in a good way, not by using a fighter with carrier cost 0, which is a hack and might be problematic (I've some concerns I didn't test).
The only one correction I suggest is the consumed unit being a land unit only (consuming air units working only if the air unit is where you are placing), to avoid the issues I mentioned. Then, it could be still somehow expanded to include air units. Just talking about the consumed units on land to place on sea; the upgrade itself, placed on the sea, may be either a sea or an air unit, of course (and can't be a land unit by definition).

Minor note, the title is reading "bug fixes". While I don't agree that it is a bug, I tend to agree that it is sort of a "fix", as if you consume a land unit to place a sea unit, that can only be from land. A remaining item to test would be to make sure that dependent units (like land units on transports) are never upgraded.
