### ISSUE TITLE
Update to map property "notes", convert to full blown gameNotes tag that then allows CDATA

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#467]
Rather than each map having:

```
    <property name="notes" value=" &lt;html&gt;&lt;body ...."/>
```

```
   <gameNotes>
           [!CDATA
                        <html><body> ....
            !]
  </gameNotes>
```

Key benefits:
- xmllint won't mess up the formatting
- CDATA will allow for HTML tags without the HTML escaping, much easier to read/edit

**Comment by ron-murhammer** [comment]
Agree with this.

**Comment by ssoloff** [comment]
(I'm new to the TripleA code and thought this issue would be a good place to get my feet wet.  Apologies in advance for any blatantly clueless statements. :smiley:)

It appears that `g.s.engine.data.GameParser#parseProperties()` already supports a `property` element with either a `value` attribute or a `value` child element.  When `value` is specified as a child element, the code correctly handles the case where the element content contains a CDATA section.  In fact, the `g.s.engine.data.export.GameDataExporter#printNotes()` method takes advantage of this and always outputs game notes using a CDATA section (and it appears it has done this since the [commit](https://github.com/triplea-game/triplea/blob/4f6d64287ecffa73f76412620d154e12a7da30de/src/games/strategy/engine/data/export/GameDataExporter.java#L235) in which it was introduced).

A quick scan of the maps repo shows that at least some of them (e.g. [here](https://github.com/triplea-maps/world_war_ii_classic/blob/master/map/games/classic.xml#L1388)) are using a CDATA section for the game notes.  While others (e.g. [here](https://github.com/triplea-maps/big_world/blob/master/map/games/Big_World_1942_v3rules.xml#L3779)) are using the attribute value.

**Given that property values can already be specified using a CDATA section, is it necessary to add a separate `gameNotes` element?**

If the answer to the previous question is "no," then would it be appropriate to simply ensure that any code that writes a game XML file uses a CDATA section for the value of the game notes property?  As I mentioned above, `GameDataExporter`already does this.  However, `tools.map.xml.creator.MapXmlHelper#appendPropertyList()` does not.  There may be others, but I could not locate any other code within this repo that might output the game notes.  (I'm assuming there may be other community map creation tools that I'm not familiar with, as well.)

**Comment by ron-murhammer** [comment]
@ssoloff Yeah, looks like the engine already handles wrapping the notes in CDATA. I think the issue is really that all maps that have game notes that use &lt; should be updated not to have them. I don't think we really need any code changes for this at this time.

**Comment by ssoloff** [comment]
Thanks for the confirmation, @ron-murhammer.

Just for completeness, the following change seems to be sufficient to get the (new?) XML Map Creator tool to output the game notes in a CDATA section:

```diff
diff --git a/src/tools/map/xml/creator/MapXmlHelper.java b/src/tools/map/xml/creator/MapXmlHelper.java
index 14fec58..c636c2e 100644
--- a/src/tools/map/xml/creator/MapXmlHelper.java
+++ b/src/tools/map/xml/creator/MapXmlHelper.java
@@ -966,7 +966,7 @@ public class MapXmlHelper {
       final Element property = doc.createElement(XML_NODE_NAME_PROPERTY);
       property.setAttribute(XML_ATTR_PROPERTY_NAME_NAME, XML_ATTR_VALUE_PROPERTY_NAME_NOTES);
       final Element propertyValue = doc.createElement(XML_NODE_NAME_VALUE);
-      propertyValue.setTextContent(getNotes());
+      propertyValue.appendChild(doc.createCDATASection(getNotes()));
       property.appendChild(propertyValue);
       propertyList.appendChild(property);
     }
```

**Comment by ron-murhammer** [comment]
@ssoloff I believe so but you'd need to test it. I'm not the well versed in the map creator tool code or functionality.

**Comment by ssoloff** [comment]
@ron-murhammer Yeah, sorry for not being clear about that in my previous comment. :smiley:  I did test it and verified the CDATA section was output with no trace of any character entity references.

**Comment by ron-murhammer** [comment]
@ssoloff Cool. Feel free to make a PR with the change then.

**Comment by DanVanAtta** [comment]
Looks like we can define game notes with this:
``` <property>
    <value>
           [!CDATA
                        <html><body> ....
            !]
  </value>
</property>```
Map maker updated, closing this out. We could create an issue to update map XMLs to simplify them. IMO perhaps better to wait in case we wish to migrate those notes somewhere else.
