### ISSUE TITLE
Network Serialization and Sockets (Java Socket + Https)

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4724]
I'm opening this issue to discuss some ideas about networking layer and to align the team on future changes.

I'm thinking our two biggest needs are:
- (A) encrypted/secure communication channel, ie: https
- (B) simpler/easier architecture so we can make changes and more easily build additional network-enabled functionality 

Websocket gives us (A), but that is only by virtue of running over 'http' with a 'nginx' reverse proxy, we get the same thing with an 'http' server. Perhaps we can simply use the http(s) server for a secure communication channel where needed, and otherwise stick to java sockets.

If we drop the desire to encrypt *all* network traffic, websocket no longer provides much benefit, and has a few critical costs:
- (1) operations and performance implications, notably getting a new server and network technology up and running, well, is likely going to be a bigger challenge then we realize. For performance, this [blog post](https://medium.com/kifi-engineering/websockets-vs-regular-sockets-b3b8e7ea0708) notes a large throughput difference between websocket and plain old sockets.
- (2) Parallel architecture, migration and rewrite effort. Typically parallel projects do not go well, having two different infrastructures will also make things complex if we go with current approach of building into new and slow migrating from old to new. With the latter approach, I don't think we'll ever fully get rid of the legacy network tech and would likely suffer from [lava flow](http://antipatterns.com/lavaflow.htm).  

 ### Key Ideas

(1) Perhaps we can just improve our current socket layer, and couple it with an https server to get secure communication as needed.

I like this idea because I think it's a very feasible direction and targets both of our needs (A) and (B). We already have an http server with an https nginx proxy in front of it, so we have the second half far on its way.

One of the biggest challenges of websocket when I tried to code it up, I found was really to be defining an application level communication protocol. While we could spend solid time building something nice, I think we'll find our design could easily break down when we try to migrate all java socket code to it, and secondly the migration of existing code to new could become exceedingly painful. I'm much more convinced if we can find a pattern to convert and improve the existing code rather than rewriting it in parallel.

As noted, we are far along with the https server, but I think we are actually in a good position to convert most of the reflective code to something that is application driven. Please note the `Serializable` payload in [MessageHeader](https://github.com/triplea-game/triplea/blob/master/game-core/src/main/java/games/strategy/net/MessageHeader.java#L12). I'm thinking if we change the `Serializable` to a `String`, we can instead encode an 'envelope' class as a JSON string. That 'envelope' class would have at least these two fields:

```
  private final String jsonString;
  private final String typeIdentifer;
```
From here, we can have a mapping of type identifier to actual types, and use JSON to decode to that type. This removes most reflection at the network layer, we'd have a java reflection dependency on `MessageHeader` only. Most network interactions could also then be traced much deeper in the code, to where we map a type identifier to a type, and that should make it much easier to build on new features. I'm also thinking we could introduce 'Version' at the next release to the JSON encoding and decoding to allow network types to handle version specific encodings. 

To sum up key benefits:
- remove most Java reflection used at the application network layer
- get better compile time guarantees and can trace code to a deeper layer
- more flexibility when handling version specific network traffic.
- we'll be able to refactor code in place
- avoids introducing a new, large architectural component, a whole new server for websockets.

Given the above, I think we may also want to discuss if the https server and java socket server should be on the same JVM or separate? Eventually we'll need to design how an https server would communicate to the socket server. 

Previously, I was thinking it would be via DB state, with 'https server' writing to DB and 'socket server' (lobby) reading it. We could also have the communication be in-memory, though in general I think lobby would do well to read more state from DB rather than keep in-memory. Perhaps that could be okay still with https and socket server.

**Comment by RoiEXLab** [comment]
Interesting questions.
I'm convinced that everything should be encrypted in 2019 ([see also](https://doesmysiteneedhttps.com/)) so using plain TCP is not an option for me. Also note that the article you linked is a bit dated, almost 6 years. Overhead shouldn't really be our problem. Also everything is moving towards Web technologies, so sticking to those isn't the worst thing to do.
As mentioned by you already using strings for network communication is probably the best thing to do. JSON can be checked for compatibility easily before actually trying to deserialize it so that should be a huge deal already.
Interesting idea about the technology swap proposal. This idea definitely has potential. While this is definitely not a good end solution because it ultimately just replaces tcp with wss and doesn't improve the code maintainability, we could realistically replace the code that remote objects (in IBridge IIRC) with our own RMI-like code that turns objects into json, sends them over a Websocket and reverses the whole process on the other end.
This would allow us to migrate everything to a cleaner way of doing network traffic step by step, ideally without breaking compatibility if we prepare the code correctly.
I conpiled a list of features that are being required for network communication in an older issue in case you're interested.
I'm not sure about the socket/https separation you proposed. The latter requires an HTTP endpoint anyways to establish the connection in the first place, so strictly separating them seems unintuitive and makes communication unnecessarily complicated.

**Comment by DanVanAtta** [comment]
I would tend to agree with [everything should be encrypted](https://doesmysiteneedhttps.com/), but TripleA is *not* a website. That is really important, think about our requirements carefully. Full encryption of everything is a goal, not a requirement. 

Second to consider, the marshaling process is AFAIK independent of transport. In other words, moving to websockets does not automatically convert  {byte array + java reflection} to  {String+JSON}, we'll still have to code that.

>  we could realistically replace the code that remote objects (in IBridge IIRC) with our own RMI-like code that turns objects into json, sends them over a Websocket and reverses the whole process on the other end.

I'm suggesting we should focus on this, leave websocket out of it for now, and where we *need* https, use it with the https server that is coming online. I thought our previous plan was to have both an https server and websocket (and that the HTTPs server was *not* temporary, but made more sense for classical server/client communication).

**Comment by RoiEXLab** [comment]
@DanVanAtta 
> I'm suggesting we should focus on this, leave websocket out of it for now, and where we need https, use it with the https server that is coming online. I thought our previous plan was to have both an https server and websocket (and that the HTTPs server was not temporary, but made more sense for classical server/client communication).

I think there's a disconnect at some point. I wasn't suggesting that plain HTTPS should only exist temporary. It clearly makes more sense than websocket on certain occasions and vice-versa.
The reason why I explicitly stated websocket in this use case is that I'm concerned that using HTTPS stops working well enough when we get to multiplayer games, where a lot of data needs to be sent to different hosts in multiple directions, where as when only the host has a websocket server (I'm guessing that's what's currently happening with TCP anyways), only a single bi-directional connection needs to be created for every player. Note that my focus is on ***bi-directional*** here. I'm convinced that hosting a web server just to receive events (which would also cause problems with port forwarding etc.) isn't the best thing to do.
I'll try to explain my idea differently: I was thinking about 1:1 replacing TCP with websocket for now to get the technology and necessary infrastructure in place (routes, certificates, port-, nginx configuration etc.).
This way we'd only need a single websocket for all connections to just work out of the box.
We could also base64 encode the bytes in order to send them as message.
After that everything that can be implemented step-by-step in a better way using HTTPS and a REST call for example is just modifying existing classes instead of having to establish a completely new class model.

Does this male sense?

**Comment by DanVanAtta** [comment]
I think I understand @RoiEXLab , thank you for talking this out!

So, from my perspective:
- websocket is a bi-direction encrypted layer sitting on top of an http server (and without the overhead of http once you go into the bi-direction socket mode).

I discount the web interaction benefit. I don't want to be harsh, but it's so far off to have even a simpler API, let alone a whole new web front-end, that I don't think the benefit is there. First things first. The real benefit I see is in having a simpler framework. For now we get the same from TCP sockets as we do websockets, so websockets is potentially just one more thing for right now.

I am wondering and have two questions:
1. If we go to websockets, would anyone hosting a game have to fire up a websocket server?
2. If we discount the web connectivity benefit, could we use https to set up encryptiong keys and then encrypt data that we send over socket?

**Comment by RoiEXLab** [comment]
@DanVanAtta 
> I am wondering and have two questions:
> 1. If we go to websockets, would anyone hosting a game have to fire up a websocket server?
> 2. If we discount the web connectivity benefit, could we use https to set up encryptiong keys and then encrypt data that we send over socket?

1. Yes, just like they have to accept a TCP connection in the current state of the engine. Something needs to host a server. Of course this doesn't apply to the clients connecting to the game. They just have to connect to this server.
2. Difficult to say. For direct connections that use a password, we could create a symmetric key based on the password, which we're already doing to encrypt a random string, so the password isn't visible on the web. This doesn't protect against MITM of course (the rest of the connection isn't encrypted and can still be intercepted), but it would be a way to generate a key to encrypt the traffic when the game is using a password. However in case there's no password in case of bots that's far more difficult to achieve. I mean we could try to implement a E2E encryption which popular messengers do, which would be really cool if someone knows well how that works, but it would be much easier to just send a public key via HTTPS to the lobby and trust it to hand it over to the other game. And then establish a symmetric key that is used to encrypt the following traffic. Of course if we're able to use TLS, we could just generate a self signed certificate on the server and send the relevant information via HTTPS over the lobby to the client for it being able to verify the issuer of the certificate.
Of course this requires both clients to be able to reach the lobby, but if this isn't the case we could as well just force the host to use a password, or the client to just ignore the self signed certificate error.

**Comment by DanVanAtta** [comment]
Re: (1), if we're using a spark or a dropwizard to fire up the underlying http listener, it seems overkill to ship this for a P2P game. 

> but it would be much easier to just send a public key via HTTPS to the lobby and trust it to hand it over to the other game. And then establish a symmetric key that is used to encrypt the following traffic.

This is very much along the lines of what I was thinking. Both clients would use a special HTTPS lobby endpoint to establish a shared secret.
