### ISSUE TITLE
tooltips.properties does not work on map

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#4844]
It is possible to create custom tooltips to replace the standard generated tooltip info.
This is very usefull if units actually do other stuff than what their raw data stats say, or if the mapmaker just wants to display unit info in another way than the standard.
I don’t know how many maps use this feature, but it is used in Age of Tribes and also in my work-in-progress World of War Heroes map.

AoT:
![Unavngivet4](https://user-images.githubusercontent.com/15268177/58415645-65491100-807f-11e9-877e-86ebe59221a7.png)
WoWH edit window:
![Unavngivet3](https://user-images.githubusercontent.com/15268177/58415664-72660000-807f-11e9-8588-3f92fa3a3907.png)
WoWH unit help window:
![Unavngivet](https://user-images.githubusercontent.com/15268177/58415691-8dd10b00-807f-11e9-93e7-22b366f4b7cf.png)
WoWH on the map ... custom toolpits do not work here :-(
![Unavngivet2](https://user-images.githubusercontent.com/15268177/58415744-bc4ee600-807f-11e9-83a1-6882963315b1.png)

The custom tool tips info seems to show/pop up in places like the Purchase screen and Edit Placement Screen. But they seem not to work on the map itself? Why is that? Is this just a flaw and nobody has ever noticed or asked about it? Is it deliberately?

I would like to ask for custom tooltips also to replace the automatically generated tooltips on the map, or I ask for some other solution that would allow custom tooltips to be used on the map also.

**Comment by Cernelius** [comment]
Yeah, this is something I wanted to report too.

I definitely believe this should be counted as a bug, and, when custom tooltips are present, they should show everywhere, instead of the pregenerated ones.

I can say it's certainly an issue when noobing the Battle for Arda map.

Off topic, I think it would be also good to have:

1) A setting for defining, preferably at a map level, how many seconds to wait before getting the tooltip.
2) A setting for defining, preferably at a map level, how many seconds the tooltip will linger.
3) A setting for showing the custom tooltip, instead of the pregenerated one, in all cases (default on custom).
4) For the mapmaker, the ability of calling any elements for the referenced unit attachment, in the custom tooltip (for example, instead of writing "3", or whatever, being able to call the number for the "Attack" value, or whatever, of that unit, that would give the current value, as modified by tech attachments) (so that tooltips may be tech-friendly, multi-games-per-map friendly, less prone to misinformation, self-maintainable upon modifying games).

**Comment by ron-murhammer** [comment]
@FrostionAAA Yeah, I think the custom tooltip was never extended to the on map units as almost no one used that tooltip until the recent enhancement for it to show when hovered over (used to be a hotkey). Agree that this would be a good feature to add now and make things more consistent.

**Comment by ron-murhammer** [comment]
@FrostionAAA PR to fix this: https://github.com/triplea-game/triplea/pull/4853

**Comment by ron-murhammer** [comment]
@FrostionAAA Please test with the latest pre-release. I'm gonna close this but let me know if it isn't fixed.

**Comment by FrostionAAA** [comment]
@ron-murhammer I have not had time to test this because of work. It will be a few days from now before I have time. But it is great if it can work. :-)
