### ISSUE TITLE
Version Numbering Problem and Maybe the Final Discussion!!!

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4875]
Now that we are two version numbers plus build number there is a problem:

Example: v1.10 and v1.11 are not expected to be compatible.

We are currently in a situation where we *want* users to do a compatible upgrade from version 1.9.x to a later version of 1.9. If we only have 1.10 and build number, we will *not* be able to indicate this with version number.

I think there are three options before us:

### (1) use build number when communicating to users, eg: 1.10+23525
Pretending the problem is with 1.10, and that we wanted to let users know they should upgrade, we'd tell them to "upgrade to the latest release: 1.10.23525"

### (2) Add in a build number, eg: 1.10.0+23525
Again, pretending we have this problem with 1.10.0, we'd ask users to "upgrade to version 1.10.1"

(note this very handy diagram that explains what each number represents: https://user-images.githubusercontent.com/12397753/51069660-64d83e00-15e8-11e9-8961-4c9c3d393308.png)

### (3) Use the first number for incompatible and second number is compatible, eg: 2.0+23525
Again pretending we had the problem with 1.10, we'd tell users they'd need to go to 1.11 and 1.11 would be compatible with 1.10. Version 2.0 would not be compatible with 1.x

## Second topic: use a plus side for splitting build number

I don't think this one is controversial, on the last topic of version numbers it was recommended to use a "+" to designate the build number, eg: `1.10+23525`

### My thoughts

- AFAIK it's not a best practice to use build number extensively nor for external communications. This makes me shy away from option 1
- I like option 3 as it makes good use of the first version number, I'm a bit skeptical we'll go to a version 2 or a version 3 ever, and I don't think it'll be really easy to create a definition of when the major version should be adjusted.
- I like option 2 as it is essentially semver

What are people's votes? Please indicate if you have strong feelings as well or if you're just voting. Let me know if the problem statement could use more clarification. Sorry to drag this topic up again, I hope we can hit resolution on it this time.

**Comment by RoiEXLab** [comment]
Difficult question: I'd actually prefer 2 or 3 with a slight tendency to 3

**Comment by ssoloff** [comment]
Vote: (3) (which seems more like semver to me)

**Comment by DanVanAtta** [comment]
I always thought semver had 4 numbers rather than 3. :man_shrugging: 
Appreciate the vote!

@simon33-2 I'd love to hear your feedback here if you get the chance. Given the work you've done on version numbering I'm thinking you might want to weigh in on this one.

**Comment by ron-murhammer** [comment]
I'd vote for option 3. And vote no to changing to using "+" for build number as I think it could be confusing for non-developers. But I'm fairly open on this topic if others feel strongly.

**Comment by RoiEXLab** [comment]
@ron-murhammer Well using + is a semver covention.
Also the build number isn't really a typical version number because it doesn't reset after incrementing the next number, so making it seperate is clearly pointing that out IMO

**Comment by ron-murhammer** [comment]
@RoiEXLab I know but as long as we plan to expose the build number to the end user and expect them to report it for bugs then I think its simpler to leave it as a "." instead of "+".

**Comment by DanVanAtta** [comment]
I think (3) has it. I'd opt to stick with the 'dot' simply because it is less code to change. I think at this point we just need to update the logic in `Version.java` for what it considers to be compatible or not.

With this updated definition the current version in prerelease would be a 2.0

**Comment by simon33-2** [comment]
> I think (3) has it. I'd opt to stick with the 'dot' simply because it is less code to change. I think at this point we just need to update the logic in `Version.java` for what it considers to be compatible or not.
> 
> With this updated definition the current version in prerelease would be a 2.0

Umm, but then why was 1.10 not called 2.\<something>? Never understood that decision. I was never aware 1.10 was made generally available?

Changing the delimiter to a '+' doesn't trouble me, but I don't see the point in having more than one number for compatible releases to remain at zero, as it did all through 1.9. It's just irritating.

**Comment by Cernelius** [comment]
Not my field, by I would definitely keep the old conventions, meaning the ones followed till 1.8.0.9, except that the fourth digit should rather be the build number here (instead of the custom of even or odd numbers for, respectively, unstable and stable).

I think it is inherently wrong and confusing changing versioning conventions in an ongoing project, and if there are strong reasons for doing so, then I would say it should be done only upon upgrading the first numeral (in this case, to 2.0), otherwise it doesn't make sense to me.

But I see you have already changed the conventions at least from 1.10, I suppose, and I don't know what the new ones are, so I don't really know. In general, I would say better not keeping changing them.

p.s.: Back in 1.8.0.9 there was a bug in which the fourth digit was not seen in the xml specifications; only the first three. Whatever the new convention is, it should be consistent with what mapmaker would need to define in the "triplea minimumVersion", to cover all possible cases (mainly referring when a new feature is added, and the game would crash with any previous versions). The bug was that, for example, if someone changed from 1.8.0.7 to 1.8.0.9, the mapmakers had no ability to set the minimum version at 1.8.0.9, as the program used to see only the 1.8.0. Now it should see whatever the relevant numbers are (2, 3 or 4, or whatever).

**Comment by Cernelius** [comment]
Also, in my mind, if you change the way versions are numbered, you should rather redefine them all, starting from the first one. In particular, TripleA by now had a lot of incompatible releases, and the version was still numbered at 1. So I think that if now the first numeral is upgraded in any case in which the new version is incompatible, then you should go back see how many incompatible releases were made since TripleA started existing, and setting the current first numeral at that number plus 1, rather than at 2. Otherwise why to have the next release as the number 2.0, when maybe TripleA already had a number of releases that were much more compatibility breaking, and were never numbered as 2.0 themselves?

This said, I'm not a developer, so I don't really know how stuff usually works, when people change numbering conventions for programs.

**Comment by DanVanAtta** [comment]
@simon33-2 , @Cernelius please check the problem statement in the (overview)[https://github.com/triplea-game/triplea/issues/4875#issue-453342635]. Any additional options or ideas to solve the problem are very welcome.

**Comment by Cernelius** [comment]
I was mostly saying why not keeping the way it was until 1.8.0.9, except substituting the 4th digit with the GitHub build number, if not having it as 5th.

I cannot remember where the documentation that explains that is, but definitely there has been very compatibility breaking releases that didn't cause the first digit to change. Number 2 seems the closest to how it worked in the past, from what I remember.

**Comment by Cernelius** [comment]
And, yes, of course, not using the build number for any communications. Build number changes only for progressive prereleasing, then at least upgrading the last non-build digit at every new stable release.

**Comment by DanVanAtta** [comment]
>  then at least upgrading the last non-build digit at every new stable release.

In this case, what is the use of the first 3 digits?

**Comment by DanVanAtta** [comment]
Second, back to the original problem, how do we signal to users that they *should* upgrade to a new release that *is* compatible?

**Comment by Cernelius** [comment]
Fourth=Build for prerelease. Third would be compatible, second incompatible, first something that never happened to TripleA so far. No idea what.

**Comment by DanVanAtta** [comment]
Same, no idea what the first is used for @Cernelius. Option (3) is essentially what you've described with the first first number lopped off.

**Comment by DanVanAtta** [comment]
One note, we'll always have an incrementing build number, we cannot zero it out for the standard releases.
It was actually intended originally for each build to become it's own 'stable', the concept of stable vs unstable is a somewhat legacy way to build code. It's geared for a pattern where everyone gets one code base, then they email one person all their updates, that one person then merges it altogether and you then have an unstable where you work out all the bugs to then have a stable. There a many problems with that pattern of development. We've shifted to a new paradigm where instead we favor many small changes and try to keep the code stable all the time. Any unstable changes are removed ASAP, since all changes are relatively small they are likely to be stable and since we only add one at a time, it's more clear usually which ones cause problems.

**Comment by DanVanAtta** [comment]
For context with the email paradigm, essentially one 'super-dev' gets patches from "N" developers all working from an out of date code base, it gets really messy and adds a lot of work for the one dev. A *lot* of that work is automated with git and github.

**Comment by Cernelius** [comment]
So, I'm not a developer or a member of this team, but I wanted to relaunch the versioning discussion with a suggestion.

Considering that there may be a huge difference in different kind of incompatibilities, I'm thinking that it would be advantageous to define more specifically what compatibility is being broken, on a scale of importance.

Something like:

first digit: map incompatible
second digit: network incompatible (chiefly lobby)
third digit: other incompatible (chiefly savegames)
fourth digit: compatible

Then a "+" sign followed by the build number. I really think this is a must in the moment in which this last digit is not reset to 0 when any previous ones are incremented. If a full stop sign, then I believe the build number should reset to 0 each time any other digits are changed.

In this case, the current prerelease should have been 1.10, instead of 2, if I'm understanding correctly map compatibility is not being broken (only savegames).

This would be still incoherent with the past, as TripleA was not forwarded to version 2 back when map compatibility was broken.

**Comment by DanVanAtta** [comment]
Documented in: https://github.com/triplea-game/triplea/wiki/Versioning
