### ISSUE TITLE
GPG key checksum failing on xenial

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4886]
Builds are failing with:
```
gpg: key 5B474E6A/5B474E6A: error sending to agent: Operation cancelled
gpg: Total number processed: 2
gpg:               imported: 1
gpg:       secret keys read: 2
The command "./.travis/setup_gpg" failed and exited with 2 during .
```

(1) This is perhaps a difference between xenial and the previous ubuntu distro that was configured on travis

(2) It looks like the magic env variable is not being picked up by this version of PGP

(3) Looking at setup_gpg, it skips if the right environment variable is not set. That means branch builds do not execute this step and hence we can be surprised after merge with failures.

(4) reproducing/troubleshooting this is a PITA and takes a lot of time with travis builds needing to be on master

-------------

Short-term disabling the checksum seems to at least let us move forward. 

For reference, artifact signing was discussed/introduced in: https://github.com/triplea-game/triplea/issues/2466

It looks like this might be the way to go to fix the problem: https://stackoverflow.com/questions/45188811/how-to-gpg-sign-a-file-that-is-built-by-travis-ci

I'm not sure how we fix the issue so that branch builds can test the key signing.

To another extent, I'm not sure if we *really* should be fixing this or not. 
- TripleA has a small user base, we are well under 10k users, this is not the worlds biggest application
- Adware injection is unlikely, TripleA was hosted on sourceforge for a long time, was not a problem then
- It's not clear there has been a single user to use the keys to verify what they download
- It won't be clear if you get a hacked version of TripleA even if you download one. Nothing tells you or directs you to check, if you get a bogus copy, you'll probably be none the wiser and nothing points you in the direction of checking.

Beyond disabling gpg in the short term, long term my 2 cents is it's great if its easy and works. Now that it's not, I don't see the ROI being favorable on this .

**Comment by RoiEXLab** [comment]
I don't have any strong opinion on this.
@ssoloff is probably the person to discuss this with as he was the one introducing it.

**Comment by ssoloff** [comment]
I came across something, quite by accident, and it reminded me of this issue.

The `error sending to agent: Operation cancelled` failure is due to the GnuPG client trying to run an interactive command while in a non-interactive shell (cf. [here](https://superuser.com/questions/1286801/gnupg-2-2-refuses-secret-key-import-error-sending-to-agent-operation-cancelle)).  Not sure why the client version on Xenial wants to run an interactive command (e.g. prompt for passphrase) when it shouldn't be necessary (the key in the environment variable is not passphrase protected).  According to [another user](https://askubuntu.com/questions/1069357/importing-gpg-key-in-ubuntubionic-docker-container) who experienced the same failure, they overcame it by running the client in batch mode, which suppresses interactive commands.

So, it might be as simple as adding `--batch` to the `gpg2 --import` command in _.travis/setup_gpg_.  Unfortunately, I have no way to test it, so all I can offer is hope and well wishes. :smile:

**Comment by DanVanAtta** [comment]
Watching the build after adding `--batch` flag, so far looks good and the `setup_gpg` step completed without issue:
```
$ ./.travis/setup_gpg
gpg: key 5B474E6A: public key "tripleabuilderbot <tripleabuilderbot@gmail.com>" imported
gpg: key 5B474E6A: secret key imported
gpg: Total number processed: 3
gpg:               imported: 1
gpg:       secret keys read: 3
gpg:   secret keys imported: 2
$ ./gradlew --parallel check jacocoTestReport
```
Will continue to monitor, good sign so far.

**Comment by DanVanAtta** [comment]
The artifact checksum scrip now fails after adding "--batch" to the setup gpg step:
`.travis/generate_artifact_checksums`

Failure is in this command:
```
  gpg2 --batch --no-tty --yes --armor --detach-sign \
      --passphrase-file <(echo "$GPG_PRIVATE_KEY_PASSPHRASE") \
      ./${engine}.txt
```

Build output is as follows:
```
./.travis/generate_artifact_checksums

Generating artifact checksums using 'md5sum'...
Generating artifact checksums using 'sha1sum'...
Generating artifact checksums using 'sha256sum'...

Signing artifact checksums for 'md5sum'...

gpg: signing failed: Operation cancelled
gpg: signing failed: Operation cancelled
```

**Comment by ssoloff** [comment]
According to [this SO answer](https://unix.stackexchange.com/a/448348), GnuPG 2.1 now requires `--pinentry-mode loopback` when specifying one of the passphrase command-line options (e.g. `--passphrase-file`).

**Comment by DanVanAtta** [comment]
Thanks @ssoloff , will give that a try with #4937 ; should be about 25 minutes to see if it works.

**Comment by DanVanAtta** [comment]
@ssoloff encountered an error: `gpg: setting pinentry mode 'loopback' failed: Not supported`

Per: https://www.fluidkeys.com/tweak-gpg-2.1.11/, adding a configuration line to see if loopback can be enabled. Trying it out in PR: https://github.com/triplea-game/triplea/pull/4938

**Comment by DanVanAtta** [comment]
Yay, successful build after latest update in #4938!

**Comment by DanVanAtta** [comment]
Checksums are showing up in the releases again.

**Comment by ssoloff** [comment]
@DanVanAtta :+1:

Strange that, with so many changes to default behaviors, the GnuPG team would see 2.1 as a compatible release to 2.0.  The numerous similar issues posted on multiple sites would indicate these changes broke a lot of existing scripts.  :man_shrugging:

BTW, it might be safer to write the `gpg-agent` configuration at the beginning of the _setup_gpg_ script.  Ideally, that script runs early in the build, so that if there's any other GPG operations that require the passphrase, they won't fail in a similar manner (or there won't be multiple GPG configuration commands spread throughout the build system).

**Comment by DanVanAtta** [comment]
Maybe we can/should combine setup_gpg with the checksum piece so it is one script? I'd lean to YAGNI w.r.t multiple GPG operations. My motivation was to try and keep as much locality for what is done and where it is needed. Perhaps could be argued both ways whether to setup early or where needed, I'd lean to leaving as-is now that we've a working config.
