### ISSUE TITLE
Two *.jar in <bin> directory

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#4891]
### Engine version
1.10.14895 (64bit Windows installer)

![triplea](https://user-images.githubusercontent.com/20812775/59251877-21334000-8c2b-11e9-9079-d5cff03bf967.PNG)

![TrA2](https://user-images.githubusercontent.com/20812775/59261639-26e65100-8c3e-11e9-81b6-66b535807929.PNG)

That contributes to the increased installer size.
Is the increased file size of a single *.jar caused by Java 11?

**Comment by RoiEXLab** [comment]
Good spot, this needs to be fixed.
The size increase might be because of 2 reasons at least partially caused by java 11:
1. JavaFX is no longer shipped as part of java 11, so we have to bundle it with your jar from this version forward.
2. Pack200 compression seems to no longer work with java 11 (saw a lot of warnings in the build), thus the increased jar size.

However I doubt that the fact that there are 2 jars as well as the 2 things I just mentioned will affect installer size by a lot, because the whole installer gets compressed before being uploaded anyways

**Comment by DanVanAtta** [comment]
Good spot, https://github.com/triplea-game/triplea/pull/4892 should fix this

**Comment by panther2** [comment]
@RoiEXLab Installer size is 14 MB less after all.

**Comment by RoiEXLab** [comment]
IKR, I wasn't expecting more than 5 MB difference.
