### ISSUE TITLE
Designing a Simpler Password Auth

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4962]
Our current system for authenticating password is quite complex. AFAIK the general best practice is client establishes a secure connection to server, hashes the password entered by user, sends that to server, server then checks to see if that hashed value exists in database. The decrypt step that our server side currently does is particularly worrisome and I think perhaps defeats a lot of the security that we are trying to add (unnecessary).

To get to a simpler setup, it seems the key is to have an encrypted communication channel. I can propose some options:
(1) use RMI over SSL and authenticate with RMI
(2) move lobby authentication to https server, on success the https server passes back a single-use token that is stored in DB. The single use token is then sent to the RMI server which then validates it and allows login.
(3) Ignore threat of network packet sniffers and send hashed password over an unencrypted channel

I'm curious if there are other good options to consider and any preferences between the two routes above. (1) has the advantage that overall there are fewer moving parts, but setting up RMI over SSL looks very painful. (2) is perhaps more straight forward but slightly more complex in terms of interactions between different systems.

**Comment by RoiEXLab** [comment]
> (1) use RMI over SSL and authenticate with RMI

Yeah I looked into that a long time ago and found out there's no standard solution to do that in the JVM. There appears to be a library to do help with that https://github.com/baswerc/niossl but it doesn't seem very well maintained and seems to have its own issues.
There seems to be a lot of example code out there that could be used to implement this though. NioSockets are tough to deal with.
The benefit of this approach would be that it would protect against MITM attacks and encrypt all traffic, which also prevents altering serialization data which could potentially be unsafe.

> (2) move lobby authentication to https server, on success the https server passes back a single-use token that is stored in DB. The single use token is then sent to the RMI server which then validates it and allows login.

While this keeps the password secure and protects the password itself against MITM, this token essentially becomes the password to grab using MITM, but this greatly reduces the "risk" for the user which is an improvement over the current process.

> (3) Ignore threat of network packet sniffers and send hashed password over an unencrypted channel

No chance. @ssoloff and I put a lot of work and effort into securing the passwords. Complexity shouldn't really be the main issue here.


That being said, I think (1) has the nice benefit that it encrypts all of the traffic like it ideally should. Of course this is a lot of work, but in the end the actual scope is fixed in size. (2) is a valid alternative IMO because the long term goal should be to move to HTTP-based communication anyways as that simplifies a lot of things that would otherwise be done manually.

**Comment by DanVanAtta** [comment]
We're still vulnerable to MITM, no? Anything the client sends could still be relayed to the server. With (2), the "access key" is single use. Thus, there's no difference in vulnerability.

Complexity is a barrier. The only hope is that we don't have to touch much of the login code in a significant way. The server AFAIK has always read and then decrypted password from DB; which is bad. The password should be just one way hashed. The passwords already hashed once in DB prevents a DB data leak from exposing passwords. Any decryption done by server can be done by any attacker that has access to the server or DB data; so it does not add extra security.

I'm working on a forgotten password feature, the encryption pieces are taking up all the effort. Once done, perhaps we won't have to touch login related code again for some time.

**Comment by DanVanAtta** [comment]
Both MITM and packet sniffing are unlikely; Not to say we should defend against either, but unlikely. MITM would require someone upstream of a computer to take control of DNS resolution so they could resolve it to their attack server. At that point, https or not, the MITM attack would be possible. Hence, I think we're vulnerable to that today as well (though it would be difficult and take a lot of effort, and probably more worthwhile to do a real attack against people with banking websites). Same for packet sniffing even.

With (1) or (2), it's possible to decrypt all passwords back to the singly encrypted form in database? I'm hoping in that case we could have the client do a bcrypt a single time and send that value for direct comparison to values in DB.

**Comment by DanVanAtta** [comment]
Actually, I"m incorrect on HTTPS defending against MITM, it does. On the other hand, the encryption/decryption we do, the source code is available and I'm not aware of a private key stored on server. Perhaps it's there and I don't know, but seems like a MITM attack server could use our own code to do any needed decryption.

**Comment by RoiEXLab** [comment]
Currently authenticating works as follows:
#### Encryption Layer
We use basic RSA encryption without any certificates (thus MITM is still possible), the keypair is generated by the server and kept in memory for the lifetime of the instance.
So whenever the clients wants to send a password, the server shares its public key with the client, so the client can use that to encrypt the password and send it to the server, which then decrypts it and processes it further.
A malicious server could intercept the connection and pretend to be the server and give the victim his own public key, so the client would encrypt the message using the attackers key, which would then allow the attacker to decrypt the password. Certificates allow the client to verify that the server they're talking to is actually the real server, which helps prevent MITM attacks.
#### Actual Authentication
In order to reduce the damage of a potential MITM (even if unlikely) the client prepends "TripleA" to the string and SHA-512 hashes it before sending. This way we prevent any attackers from collecting passwords our users might use for different, more important services like their bank account or paypal. Because SHA-512 alone might be brute-forced using a rainbow-table of some sort, we prepend "TripleA" before hashing to make sure the hash is more or less unique to TripleA and can't be found in common databases.
When the server receives the SHA-512 hash it does one of two things:
1. The account is about to be created: The SHA-512-hashed-password is BCrypted and stored in the DB
2. The account exists: The server looks up the existing bcrypted hash in the database and checks if using this specific salt (that is stored with the bcrypt hash) the same hash is created when hashing the SHA-512 hash. (Using `Bcrypt.verify(currentHash, sha512-candidate)` IIRC). The reason why the database can't compare the password directly is because this is exactly what the bcrypt salt tries to prevent. Using this approach even if an attacker would be able to get the entire database, they wouldn't be able to use a rainbow-table because they'd need one for every possible salt there is, which makes this practically impossible.

The best way to implement a password reset mechanism is really to send the user a single-use token (expiring after an hour or something), which then can be used to skip authentication once and allows to update the password using the existing code.

**Comment by DanVanAtta** [comment]
Thanks @RoiEXLab for recap; I got pretty far on a password reset and then spent a very long time (and still) trying to decrypt the single use token accurately.

**Comment by DanVanAtta** [comment]
Another thought @RoiEXLab; that is really good info and should not be lost/buried in an issue. It would be great to see a doc page be created with those design notes (perhaps preferred so the info is consolidated with other dev info),  or perhaps wiki.

**Comment by RoiEXLab** [comment]
@DanVanAtta Good point, I had to think about the details for a while myself, I implemented this such a long time ago with @ssoloff 
He might be able to extend this future article with information on password protected games, which to my knowledge generates a key based on the password and encrypts a nonce with it which is then decrypted on the other side. If this is successful, the password is correct.

**Comment by DanVanAtta** [comment]
I think we can rule out (1)
- damn complicated
- do we really need it?

(2) provides the benefit that MITM should be impossible when doing initial password authentication and any non-encrypted password information is all single-use (which can still use the public key encryption)

I think (2) is an option, but perhaps we should first focus on simplifying the current code first. It's not clear we can drop a lot of it even if we go with (2), we probably still do not want to send single-use-tokens in the full clear if we can help it. In terms of complexity, we have issues where notably for example `LobbyLoginValidator` severely violates SRP. It can be seen pretty well in the test code.

**Comment by RoiEXLab** [comment]
@DanVanAtta Created a wiki page: https://github.com/triplea-game/triplea/wiki/Lobby-Authentication-Logic

I'd appreciate if you could do some proof reading on it. As you all know english is not my native language, so there might be some smaller errors in it.
