### ISSUE TITLE
Where to track technical debt?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5135]
**Topic and Overview**
We've closed a lot of issues that track technical debt over time, it's also a bit of priority inversion when we fix yesterdays problems that we are tracking rather than fixing the technical debt that is getting in the way of todays problems.

At the same time a fix list can also set a future direction where we want to go and give new contributors tasks that can be readily worked on.

On the other side, there is so much technical debt, we could go crazy tracking it and we'd not gain any value in simply tracking it all and would incur overhead to curate and maintain the debt list.

If we feel we should track technical debt, should we do so in issues, in wiki, or in code? I think I'd vote for wiki if so. At the same time, I wonder if we are gaining that much by tracking such issues. If we decide to not track technical debt, would we delay merge because a PR does not leave us debt free?

**Desired Outcome**
Answer questions:
- should we track technical debt?
- what kind of debt should we track if so?
- where to track debt?

**Comment by ron-murhammer** [comment]
Uh. Not an easy answer for this. I'd tend to vote that we only track major technical debt issues that have significant impact on future development and anything that someone is planning to tackle in the short term and would like to discuss. Probably easiest to just use github issues for it. Anything else I don't think is worth tracking and we should rather ensure we have standards for PRs and future development that slowly improve the code base over time.

**Comment by RoiEXLab** [comment]
I think it really depends on the kind of goal we want to achieve, I think my reflection issue is a good example:
If the goal is to just create a list of places in the code that might not be safe to refactor, then a wiki entry is probably the best thing to go for, because no one is going to search for an issue in this case.
However if this list is supposed to be a checklist of places which should ideally get replaced with compile-time checked code, then an issue (or project item or something, whatever github offers) is more suited IMO.
Also we need to keep in mind that deciding what should be the goal isn't always a trivial thing to do, so in the end I believe the best thing is to open an issue with all the information, and move the relevant information to the wiki or something if the general consensus thinks it's the right thing to do.
I don't think there's a general answer though

**Comment by DanVanAtta** [comment]
I think we are generally agreed:

- (1) do not track technical debt in issues, nor wiki. I think the reasoning is that we more have tons of it. A lot of TripleA was written for Java 1.3, 'nio' was a new JDK feature when the networking code was written. There's lots of legacy, it's okay, but there's lots of things to improve and much more modern practices we could employ.

- (2) do open issues to discuss technical debt if we think there should be something done about it and we have something of a plan. The network code ticket @RoiEXLab raised I think was perfect. Fixing reflection is a very tangible goal, I've felt that one of our project priorities should be fixing areas of compatibility and making compatibility less error prone. I think it would help project velocity. In such cases an output artifact of a page going onto wiki I think is great. Essentially it's a documentation page to note an initiative, help us stay on the same page and essentially provides design notes. I'd like to see the wiki be used more to capture design notes. I think it's been pretty successful so far as a centralized documentation location.
