### ISSUE TITLE
Designing: Http Lobby

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5182]
I want to open this issue to begin discussing before any PRs land some of the major/interesting design choices for an http lobby.

### HTTP Lobby Motivation
I was then thinking about the moderator TODO's, the problems with lobby ghosting, the issues of internal reflection used as part of that network layer, the compatibility problems we still see, and the lack of isolation we have between games and interaction with lobby; it seemed like a lot of these legacy technologies are overkill compared to the effort of an http lobby.

### Concerns
 As far as I can see we have two main concerns:
- (1) latency of updates. With socket communications we have two-way communication so updates from game to client can happen in essentially real time.
- (2) server load. I think this is actually a moot point as our http server should be able to handle load on the 10k TPS range, but it's something to think about nonetheless. The overhead I suspect would actually be lighter than the custom java socket implementation, but I have not measured it to know for sure.

### Simulating Bi-directional messaging with HTTP
There are two main features I think for http lobby to be able to simulate the bi-directional communication:
(1) keep alive message: I'm thinking there should be an endpoint where all connections will 'ping' once or twice a second to indicate an active connection is available. 
(2) status request message: I'm thinking for an endpoint that clients will ping 2-4 times per second to get a list:
  - game states
  - chat history since time X
  - player list

### Authentication
Another item of consideration is authentication. The custom socket implementation placed unauthenticated connection in a "quarantine" where the protocol either authenticated the connection and placed it in a known 'node->connection' map, or the connection was closed. For http lobby, I was thinking for API keys, we already have the concept for moderator keys, it dovetails very nicely there and would remove the entire need for moderator API keys. In essence, on login a client gets an API key, on subsequent requests those keys are sent to the server.

**Comment by RoiEXLab** [comment]
> it seemed like a lot of these legacy technologies are overkill compared to the effort of an http lobby.

Agreed, if we reduce lobby to just the core functionality a HTTP lobby seems reasonable. It really is just a hub that supports chat functionality.

> (1) keep alive message: I'm thinking there should be an endpoint where all connections will 'ping' once or twice a second to indicate an active connection is available.

See, this is where websockets provide a real benefit over raw HTTP: Like half a year ago I implemented a system using spring+ websocket where users would open an editor page they would see if another user already has this page opened, and prevent the second user from editing anything if that were the case. If I had used HTTP exclusively, I would have had to constantly ping the backend server for every open tab, for every user. In this small scale this would've worked no problem, but it really is unecessary overhead, because websocket endpoints usually send EndOfStream packets once they want to close the connection, which makes updating lists near instantly as well. (Obviously there's a timeout in case one client crashes or something)
I don't know if this is the best solution or even a good one, but I'd suggest using websockets for broadcasting life information exclusively. This way, the headless host would update its GameState via HTTP, but all connected clients would recieve this update instantly and be able to update their UI.
Same for chat messages. Best of both worlds?

> chat history since time X

When using HTTP we have to keep the chat history for a short while, not sure if this is the best idea. When using websockets we wouldn't have to store anything, and could just broadcast any messages when they arrive, which makes things simpler IMO.

> In essence, on login a client gets an API key, on subsequent requests those keys are sent to the server.

Exactly what I was thinking, makes debugging stuff using `curl` or something straightforward, and avoids keeping something like a password in memory for the lifetime of the connection. Might be worth to consider using an open standard like OAuth2 for this. [Dropwizard seems to support this](https://www.dropwizard.io/1.0.0/docs/manual/auth.html), so this would make it easier to not make any security mistakes there and would also reduce the amount of code we'd have to write overall.


Funny side-note:
I was reading your issue while you were still editing it, I thought is was funny when all the lines I was reading suddenly were re-arranged multiple times 😄

**Comment by DanVanAtta** [comment]
***websockets***

I think websockets is perhaps overkill for lobby. It's really not that much different than socket programming. We would need to define a custom message protocol, which is part of the original problem of the existing socket implementation. IMO at that point we really may as well refactor and keep using the existing java socket code.

In terms of liveliness requirements, I can see your example @RoiEXLab needing websockets. It seems delays needed to be under 100ms (threshold for actions to seem nearly instantious). 

For us, lobby, a delay of 200ms to maybe 500ms or more is extremely tolerable for game state. I'd even think game state changes could be delayed by up to 1s, 2s maybe even up to 5s even.  I'm most concerned about chat. I suspect a delay there of 200ms should still be fine though. IMO lobby just does not have a requirement for such immediate updates to really need raw socket communication.

*** chat history ***
How would sockets handle the case when a network becomes unavailable for a short time? Would messages just be dropped? Would there not be a retry queue of any kind?

Agree that just blasting messages back over relay is easier than in-memory structure. I think we really want to have chat go into DB. Beyond that, seems like a good benefit for new joiners to get a small history of the existing chat. I can cite some examples where it would have been really helpful to know what was said in the last minute. Just very notable, notice those 'advertising' games will copy/paste their advertisement message for anyone new joining. Defining game parameters should be baked into the game, meanwhile some chat history would help.

> Exactly what I was thinking, makes debugging stuff using curl or something straightforward, and avoids keeping something like a password in memory for the lifetime of the connection. 

Hate to say, chances are good some portions of the network message will be stored as String somewhere, which is immutable and stored in permgen, the lifetime of the running server. At the same time, if the live-memory of the server is compromised, it's a very significant security breach already.

Defense in depth is a real principle, so not to elide this concern, the thing to do is to hash the password on the client side. Least this way the server is never dealing with raw plain-text passwords.

***OAuth***

I do want to keep it simple. I was working on a request filter to move the auth logic out of the handler code. Authorizer seems maybe a better fit. Our need for 'roles' is pretty limited though. One of the two should be used for sure. The bigger point though is that authenticated requests will be done with tokens.

**Comment by RoiEXLab** [comment]
> We would need to define a custom message protocol, which is part of the original problem of the existing socket implementation. IMO at that point we really may as well refactor and keep using the existing java socket code.

I don't think this would be a problem, we could easily create a different Websocket for every functionality which would keep everything separated, but I don't have any problem trying out raw HTTP to see if that works. I'm just saying that there's probably a good reason why servers use websockets if possible: GitHub uses them for real-time updates of the site, Gitter for chat, NodeBB for low overhead information retrieval

**Comment by DanVanAtta** [comment]
Indeed, if you want socket communication over HTTP, websocket is your answer. Java socket and websockets are basically the same thing. The underlying transport is slightly different, but in the end you have a socket and define your own protocol for communication. Having taken a quick stab at websockets once for lobby, it just really struck me as overkill.

I think TripleA can easily get away with just HTTP for lobby:
- we do not have 100k thousand concurrent users
- chat is the only thing that is really latency sensitive. To that extent, websocket would be nice, but it has a cost of custom protocol. Having a mixed design for communication compounds to that cost, when polling should work just fine.

**Comment by DanVanAtta** [comment]
I guess of some note, websites like HTTP as any existing devices, mobile, can communicate with those sites using HTML + Javascript. We've a thick client, we don't get benefit of using HTTP; hence we may as well just stick with java sockets if we really need socket communication.

**Comment by RoiEXLab** [comment]
Good point. Using Websockets over normal sockets has the benefit that we don't have to worry too much about auth, because it uses a HTTP request as a handshake, which uses the same auth mechanism as all the other requests.
Also in our case we'd need a refactor anyways to be able to encrypt everything, but that's only a small bonus in our case, not a general advantage.

But then again maybe all my concerns really don't apply for our case, so no problem to give it a shot

**Comment by DanVanAtta** [comment]
@RoiEXLab having thought about it more, I don't think I ever necessarily disagreed for websocket to be a good fit, but hard to judge it's cost and if it's worth it. It may still be, I'll continue to consider it. It still has some benefits to investigate:
- having one server is a big benefit
- a rewrite to split the network interaction of lobby compared to headless games seems like a really good move.
- refactoring the existing socket code is potentially really messy, in part because it is so heavily shared
