### ISSUE TITLE
Global 1940 - overbuy should provide a refund

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5195]
**Describe the bug**
In Global 1940 a refund for an unintentional overbuy should be given, the overbuys are carried over to the next turn(s) instead.

Reported in: https://github.com/triplea-game/triplea/issues/3767#issuecomment-412295846

**To Reproduce**
- play global 1940
- purchase more units than can be placed (TODO: attach a save with this set up)
- end turn
- notice that the overbuy carries over to the next placement phase

**Expected behavior**
- Overbuy units should be refunded and removed from the purchased units list

**Comment by Cernelius** [comment]
The refund is to be actually provided only for unintentional overbuy. It is thus propedeutic to this feature to define what makes an overbuy unintentional. Also, there are no rules to define what happens in case of intentional overbuy, so I would argue that the outcome would be that you lose the game, if the overbuy is somehow proved intentional. Thus also a feature making you lose the game if you do an intentional overbuy would have to be provided, as well.

**Comment by panther2** [comment]
Correct, @Cernelius 
We have discussed the vagueness of that "unintentional overbuy" in other related Github issues as far as I remember. When I find some time I will reference them.

**Comment by panther2** [comment]
cc: @DanVanAtta

**Comment by panther2** [comment]
The headline of this issue should be corrected, IMHO.

**Comment by Cernelius** [comment]
I actually suggest closing this issue in favour of
https://github.com/triplea-game/triplea/issues/5194
since all rulesets after v4 just behave exactly as v4, on this matter.

**Comment by DanVanAtta** [comment]
Isn't this a bug with the map XML?

Is there an active maintainer for the global map XML that can take care of this?

Resolving, we've a number of map bugs, we can track this in the Global repo is desired.

**Comment by panther2** [comment]
I will answer in #5194
