### ISSUE TITLE
History hotkey in Mac conflicts/un-usable

### ISSUE THREAD

**Issue by NickClark** [triplea-game/triplea#5254]
**Describe the bug**
On most platforms you can easily switch between history and current game using hotkeys. On mac, there is no hotkey to switch to history.

**To Reproduce**
Hit Ctrl-H while in game, observe nothing happens.
Hit Cmd-H while in game, observe app becomes hidden.

**Expected behavior**
Hiting a specified hotkey show allow switching mode. Bonus points: A single key that toggles between the modes.

**OS (please put an X in the appropriate box):**
[] Windows
[x] Mac
[] Linux

**Comment by DanVanAtta** [comment]
> Bonus points: A single key that toggles between the modes.

It turns out that is difficult :disappointed: 
I gave that a try and flipping between the modes regularly lead to various state errors. When entering history mode, there is a full game data copy that is done, it can't keep up when flipping back and forth and synchronization gets thrown off.

--------

It looks like 'ctrl+y' is an open option, thinking to set this hotkey for mac-os only to 'ctrl+y'

**Comment by DanVanAtta** [comment]
Hotkey remapped to 'ctrl-y' in: https://github.com/triplea-game/triplea/pull/6255

Please comment/re-open if that does not fix this.
