### ISSUE TITLE
Headless Host Moderator Tools Broken

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5275]
**Describe the bug**
Getting "remote not found exception" for moderator right click controls

**To Reproduce**
1. Launch a lobby
2. Launch a headless bot
3. Connect to lobby with a moderator account
4. Right click headless bot, select "get host info"
5. Notice: RemoteNotFoundException

**Comment by DanVanAtta** [comment]
Added some debugging and it looks like the problem is 'port' number

```
Caused by: games.strategy.engine.message.RemoteNotFoundException: Not found:games.strategy.engine.lobby.server.RemoteHostUtils:Bot01-testbot_lobby_watcher port:4000 ip:127.0.0.1, endpoints available: [games.strategy.engine.lobby.server.RemoteHostUtils:Admin port:3304 ip:2601:601:f00:ed0:0:0:0:1%enp0s10, games.strategy.engine.chat.IStatusChannel.STATUS, games.strategy.engine.chat.IStatusController.STATUS_CONTROLLER, _ChatRmt_LOBBY_CHAT, games.strategy.engine.lobby.server.ModeratorController:Global, games.strategy.engine.lobby.server.IGameController.GAME_CONTROLLER_REMOTE, games.strategy.engine.lobby.server.RemoteHostUtils:Bot01-testbot_lobby_watcher port:59660 ip:127.0.0.1, games.strategy.engine.lobby.server.RemoteHostUtils:Bot01-testbot_lobby_watcher port:59758 ip:127.0.0.1, games.strategy.engine.lobby.server.IGameBroadcaster.CHANNEL, games.strategy.engine.lobby.server.RemoteHostUtils:Bot01-testbot_lobby_watcher port:60050 ip:127.0.0.1, _ChatCtrl_LOBBY_CHAT, games.strategy.engine.lobby.server.RemoteHostUtils:Bot01-testbot_lobby_watcher port:59712 ip:127.0.0.1, games.strategy.engine.lobby.server.USER_MANAGER]
```

I looked at `GameDescription` and updates to it which I think helped pinpoint the breaking update.

c6d39ba58c3f62f6a71a9f7e68a4242a0e48e5f2  << broken
93d1a346feff6ac4c0878803b3e585fc3cb2026b << working (previous commit)


Looking to the where problem seems to be, `node` value in `messengers` seems to be getting the wrong port. It is assigned in QuarantineConversation, but that code has not been updated in some time. @RoiEXLab please have a look if you would, I'm hoping you might be able to spot the issue. This update: https://github.com/triplea-game/triplea/pull/5279 should help highlight the differing port and may help.

**Comment by DanVanAtta** [comment]
@RoiEXLab have you had a chance to look into this? Do you have any conjectures what might have broken the headless moderator tools since in this commit: https://github.com/triplea-game/triplea/commit/c6d39ba58c3f62f6a71a9f7e68a4242a0e48e5f2

**Comment by RoiEXLab** [comment]
I'll try to have a look over the weekend

**Comment by RoiEXLab** [comment]
@DanVanAtta I have some good news and some bad news:

#### The good news
I think I found the reason why #4747 broke the mod tools: It basically is indirectly cause by this change: https://github.com/triplea-game/triplea/commit/c6d39ba58c3f62f6a71a9f7e68a4242a0e48e5f2#diff-eb3063a12e22a83e4029e7fa26cecf7cL283-R270
Of course just changing this line didn't cause the bug, but the implications that came with it did. Note that there's a lot of speculation from my side, but I think my theory is plausible at this point.
So back to the change: So basically starting with this PR, there's no longer an extra port variable passed with a `GameDescription`, it exclusively relies on the port that `INode` supplies, because I thought that is was completely unnecessary passing both, since the client only really used the "extra" port in order to connect to a headless host, so merging this "extra" port into the node seemed like the logical thing to do, and for this part I was completely right.

#### The bad news
However apparently it seems that all the "RemoteMethod" logic relied on the port that already existed in the existing `INode` to identify the correct remote object, which makes sense because the server where this identification is done couldn't possibly know the "local port" of a headless host, so it uses the public "outgoing" TCP port that it can determine, using the NIO APIs, to identify the correct remote to call. Because we replace this outgoing port with the public connect port [here](https://github.com/triplea-game/triplea/commit/c6d39ba58c3f62f6a71a9f7e68a4242a0e48e5f2#diff-6efb69481cfe7bde9221005330a8338fL105-L109), the client no longer can call the correct remote (because of the port mismatch), and therefore everything fails.
In order to prove my point I wrote some extra code that passed the outgoing TCP port along with the public IP:
```diff
diff --git a/game-core/src/main/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcher.java b/game-core/src/main/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcher.java
index 346b3c41e..3525910d3 100644
--- a/game-core/src/main/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcher.java
+++ b/game-core/src/main/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcher.java
@@ -99,8 +99,7 @@ public class InGameLobbyWatcher {
         new Node(
             serverMessenger.getLocalNode().getName(),
             SystemPropertyReader.customHost().orElseGet(gameHostingResponse::getPublicVisibleIp),
-            SystemPropertyReader.customPort()
-                .orElseGet(() -> serverMessenger.getLocalNode().getPort()));
+            SystemPropertyReader.customPort().orElseGet(gameHostingResponse::getPublicVisiblePort));
 
     gameDescription =
         GameDescription.builder()
diff --git a/http-clients/src/main/java/org/triplea/http/client/lobby/game/hosting/GameHostingResponse.java b/http-clients/src/main/java/org/triplea/http/client/lobby/game/hosting/GameHostingResponse.java
index 6df80722d..319ca9c19 100644
--- a/http-clients/src/main/java/org/triplea/http/client/lobby/game/hosting/GameHostingResponse.java
+++ b/http-clients/src/main/java/org/triplea/http/client/lobby/game/hosting/GameHostingResponse.java
@@ -16,6 +16,9 @@ public class GameHostingResponse {
   /** Server responds with IP address that it sees. */
   private final String publicVisibleIp;
 
+  /** Server responds with port that it sees. */
+  private final int publicVisiblePort;
+
   /**
    * Server grants the host an API key for future connections. Game hosts do not necessarily go
    * through the lobby login process and need an API key.
diff --git a/http-server/src/main/java/org/triplea/server/lobby/game/hosting/GameHostingController.java b/http-server/src/main/java/org/triplea/server/lobby/game/hosting/GameHostingController.java
index 1b20c26f3..4d6c6a271 100644
--- a/http-server/src/main/java/org/triplea/server/lobby/game/hosting/GameHostingController.java
+++ b/http-server/src/main/java/org/triplea/server/lobby/game/hosting/GameHostingController.java
@@ -39,6 +39,7 @@ public class GameHostingController extends HttpController {
       return GameHostingResponse.builder()
           .apiKey(apiKeySupplier.apply(InetAddress.getByName(request.getRemoteAddr())).getValue())
           .publicVisibleIp(request.getRemoteAddr())
+          .publicVisiblePort(request.getRemotePort())
           .build();
     } catch (final UnknownHostException e) {
       throw new IllegalArgumentException(
```
I got the same Exception, just with a different port value.

#### The ugly news (the ones that are even worse)
Obviously this change would break the normal join process, which requires the public port, not the outgoing one the headless host uses to communicate with the lobby/HTTP-lobby, but after this change nothing worked, the reason was pretty obvious, but I don't know when a second bug was introduced:
Remember your error message?
```
Caused by: games.strategy.engine.message.RemoteNotFoundException: Not found:games.strategy.engine.lobby.server.RemoteHostUtils:Bot01-testbot_lobby_watcher port:4000 ip:127.0.0.1, endpoints available: [games.strategy.engine.lobby.server.RemoteHostUtils:Admin port:3304 ip:2601:601:f00:ed0:0:0:0:1%enp0s10, games.strategy.engine.chat.IStatusChannel.STATUS, games.strategy.engine.chat.IStatusController.STATUS_CONTROLLER, _ChatRmt_LOBBY_CHAT, games.strategy.engine.lobby.server.ModeratorController:Global, games.strategy.engine.lobby.server.IGameController.GAME_CONTROLLER_REMOTE, games.strategy.engine.lobby.server.RemoteHostUtils:Bot01-testbot_lobby_watcher port:59660 ip:127.0.0.1, games.strategy.engine.lobby.server.RemoteHostUtils:Bot01-testbot_lobby_watcher port:59758 ip:127.0.0.1, games.strategy.engine.lobby.server.IGameBroadcaster.CHANNEL, games.strategy.engine.lobby.server.RemoteHostUtils:Bot01-testbot_lobby_watcher port:60050 ip:127.0.0.1, _ChatCtrl_LOBBY_CHAT, games.strategy.engine.lobby.server.RemoteHostUtils:Bot01-testbot_lobby_watcher port:59712 ip:127.0.0.1, games.strategy.engine.lobby.server.USER_MANAGER]
```
The "endpoints available" part clearly lists a `RemoteHostUtils` part, it is not there on my machine, and I suppose it isn't either on yours when using master.
And I don't have the slightest clue why. It looks like at some point a bug was introduced that causes some remotes to no longer register at all, which is a second bug that breaks this feature. 😞 

#### Elegant solutions
Honestly I don't think it's worth our - or in reality _your_ - time, to try to find out why the remote is no longer registered, except of course if you remember having dealt with this kind of stuff before.
IMO the easier approach would be to add another controller to the HTTP server and just wire some unique ID that every connected game has to an existing bot control mechanism, that presumably still works from lobby to bot that only needs to be changed to work with HTTP instead of plain old RMI-like stuff. This way all of the legacy code for this can be removed as well.
I must admit thought that I really don't know much about either the complexity of HTTP implementations for bots, nor the complexity to deal with the obscure parts of triplea netcode.

**Comment by DanVanAtta** [comment]
Thanks for taking the look and I'm happy you made some headway even if not all good news.

For the remote, I've been wondering a bit if it is 'remote' vs 'channel' issue. It was not obvious, but I finally realized that "remotes" are 1:1 communication over socket. A 'channel' is still RMI but the endpoints exist on all clients. Instead of invoking a single endpoint via RMI on server, the server has a "remote" registered and messages to that remote are forwarded to all clients. I've been wondering if perhaps there is just a mix-up of the two.

I've been thinking about this situation and I think any fix might not carry-over when Java NIO lobby is removed. Thinking about alternative solutions and functionality we need:
- moderator boot player from bot
- moderator ban player from bot

I think maybe what we can do is tie the bot boot/ban to lobby boot/ban. To explain, if a moderator boots/bans a player from lobby, that action is automatically applied to all bots. A deal-breaker for that is if someone is playing a game and is being abusive in lobby, and they are simply kicked as a first warning. It might not be intended to disconnect them from any ongoing games. So perhaps all that is necessary is to remove players from bots if they are *banned*.

@prastle, your feedback here would be valuable. I think we are suggesting:
- remove all current moderator controls relative to a bot. No remote stop, no boot player.
- replace all those controls with an automatic "boot" on ban capability, so that if a player is banned from lobby they are then automatically kicked from a bot.

We would be losing the 'chat' logs functionality, that would perhaps be important. On one hand in theory the chats in games are not to be moderated, on the other it's probably good reference. It's on my radar so that all lobby chat will land in database and then you could search for a players dialog from Toolbox 2.0. We could extend this to bots so that toolbox 2.0 also has a history of bot chat logs. 

@RoiEXLab , @prastle thoughts?

@RoiEXLab for implementation of this, bots would be given an optional "API-Key" command line arg. If present, the bot would communicate to http-server. We'd either do short polling or a websocket. For short polling, the bot would ask the "http-server", "are any of my current players banned?". For websocket, the ban message would be relayed to the bots. I think I might be leaning towards short-polling, but the implementation is getting ahead of ourselves. We need to be sure we design which functionalities will remain available to moderators and how.

**Comment by DanVanAtta** [comment]
I want to recap next steps.. We need to rewrite/redo moderator controls of bots. For this, we need first a list of the functionality that must be available. Do we still need all of "boot/ban/show logs?" Second, once we have the needed functionality identified, we can discuss implementation strategy.

**Comment by prastle** [comment]
Reading and yes Boot/Ban from lobby automatically affecting bots would be a great addition since atm we have to boot from lobby and then search all the bots using right click functions.  If the chat logs of bots is lost it would greatly affect mods ability to verify complaints.  Most issues start inside a bot and then sometimes reach the lobby.  We need to be able to see bot chat logs.  Also you are incorrect @DanVanAtta. --> "On one hand in theory the chats in games are not to be moderated, on the other it's probably good reference. "  Bots are moderated since they are owned by triplea just like the lobby.  Only Private hosts are not moderated.

**Comment by DanVanAtta** [comment]
@prastle  Should a boot from lobby also boot the player from any bots (potentially disconnecting any games they are currently playing)? I presume a ban should certainly disconnect the player from any current games.

**Comment by prastle** [comment]
@DanVanAtta  Yes a Ban should obviously auto disconnect them.  You have a good thought about the boot though.  Perhaps not.   This would allow them to save their game.  We would still need to be able search all bots through right click and also be able to boot directly from the bot as we can now.

**Comment by DanVanAtta** [comment]
> We would still need to be able search all bots through right click and also be able to boot directly from the bot as we can now.

I'm curious for more details on this and when this is needed. It sounds like we'd want to kick players from specific bots, when would we want to do that? Is it just as well for a kick from lobby to be a kick everywhere? Or said another way, for a kick from a bot server to be a kick from both bot and lobby?

Another question, is there much use in a kick? Disconnecting a player sends a message, but I wonder if it really is more than just a nuisance. One could think of a kick as a zero-minute, or as a one second ban. Would we simplify our lives, rules and enforcement if the minimum punishment were something like a 5 minute ban? That means you take a break from any bots and the lobby.

For further consideration, we could have lobby games that are privately hosted to wire into the lobby and also enforce any 5 minute bans. That would mean any 5 minute ban or longer would be applied across the board.

**Comment by prastle** [comment]
@DanVanAtta   A 5 minute ban would work instead of kick just fine.  With the current engine we have to physically remove them from the bot /bots they are in after banning them in the lobby.   We need to be able to search the bots for two reasons.  The primary one being that since a ban from the lobby or kick does not remove them from a bot we still need to be able to kick boot them once they have saved their game. (If we don't care about them saving their games this could probably be removed).  The second reason is that we have noticed peeps directly joining a host and bypassing their ban in the lobby.  Hopefully your new wiring will eliminate that ability.  I like your idea of applying it across the board.  It sounds like it would make life easier for you to code as well.

**Comment by DanVanAtta** [comment]
The issue as described is fixed. Booting/banning a player will also do the same for players in games.
