### ISSUE TITLE
Manipulation of Items in the Place Queue

### ISSUE THREAD

**Issue by theredbaronaaa** [triplea-game/triplea#533]
Original forum post:
http://tripleadev.1671093.n2.nabble.com/How-to-Remove-Items-from-the-Place-Queue-tp7591348.html

Units that have already been purchased but not yet placed cannot be manipulated in any way other than adding more. This is a feature request to allow removal of items using a similar trigger. Not urgent, but I wanted to get this into the issue tracking before it fell off the front page of the forum.

**Comment by DanVanAtta** [comment]
@williamdekryger , would you mind clarify the request? Perhaps give an example?

**Comment by williamdekryger** [comment]
Basically, through the "purchase" trigger attachment, units can be added to the place queue, so that when the player reaches the placement phase, they will be available to place onto the map. It is done in the XML like so:

```
<attatchment name="triggerAttachmentAmericansLLFill" attatchTo="Americans" javaClass="games.strategy.triplea.attatchments.TriggerAttachment" type="player">
        <option name="conditions" value="conditionAttachmentAmericansLLAvailable"/>
        <option name="purchase" value="infantry" count="5"/>
        <option name="players" value="Americans"/>
        <option name="when" value="before:americanPlace"/>
</attatchment>
```

The problem with the above trigger is that it will give 5 infantry every turn, and if they are not all placed, the next turn, there will be more in the queue. I want to know if we can code a way to remove those units without placing them, a trigger I could run after the placement phase, to clear the specific units, keeping the "Placed units live when not placed" property true. Somehow, I would like to be able to "unpurchase" the units via a trigger. As of right now, there is no way to manipulate these units.

**Comment by Cernelius** [comment]
Regarding your case, I tend to think that a condition able to see what it is in the Place Queue would be more appropriate than a trigger able to remove units from the same.

Then if, for example, you want to always have 5 infantryLL, you will need to make 5 triggers per player, one adding 5 infantryLL if you have 0, another adding 4 infantryLL if you have 1, etc..

**Comment by williamdekryger** [comment]
I agree this is a better move, and has way more use cases than my original suggestion 👍
