### ISSUE TITLE
Confirm Defensive Rolls Feedback

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#537]
So I think the new feature to have the casualty selection skip if there isn't anything to do instead of requiring space bar is good. The issue is that 1.5s is really slow for people who don't really want to watch it go by and much slower than just clicking the space bar.

Here is some user feedback:
"Sorry if this has been discussed and I missed it. But something I've noticed with battle in the prerelease: you no longer have to acknowledge or select things (e.g. casualties) when there is only one option to choose. 

Good. Fewer keystrokes. 

But the entire battle process seems to have slowed. Like the AI is thinking harder about casualty selection. But it seems more like a uniform delay has been built into each step. 

This makes it easier to pay attention to what's going on. But when I'm just testing/messing around, it takes a lot longer than in the production version where I can just pound on spacebar/enter and the battle zips by. 

Just wondering how much of this is conscious decision for user experience vs. AI changes."

Personally, I've turned the feature off due to how slow it is. I think we should consider making the pause adjustable or have the default be the old way. Otherwise I think we could end up getting lots of complaints when we release that casualty selection is slow.

**Comment by DanVanAtta** [comment]
This is good feedback. 

Some things we can do to address this:
- Lower default to around 0.5s
- A settings window is needed to aggregate the menu settings. This allows us to display them in a split pane type of view that could include an explanation for what each settings would do (imagine the map download dialog window but with check box options instead of map names, and explanations of the options on the right)
- for discovery, having a 'battle settings' button, or pull out options menu on the battle screen itself would be very useful. We could group the other 'focus on own casualty' and other battle related settings there (but we would still want that centralized settings window to include those same settings  so the settings could be updated without being in a battle)

For consideration, part of the goal is to avoid the worst case scenario of multi-minute delays. Particularly thinking about FFA or multiplayer games where a player may be new and not all that excited, or they are not very engaged, in which case it can be 5~10 minutes before there is the confirmation click. Other times when there is a long delay for someone to select the next battle, it can be easy to confuse that with the combat phase being over, and heading off for a few minutes is pretty typical while waiting for non-combat to be played. In which case there is another many-minute delay.

Thus having it as a default setting is to help avoid this worst case scenario.

For now having a setting not be in the menus is intentional. It's complex to say the value only takes effect when some other game option checkbox is also checked.

**Comment by DanVanAtta** [comment]
Cernel had the idea of allowing for a space bar click to 'manually' confirm. I think that's probably the best solution.

**Comment by ron-murhammer** [comment]
@DanVanAtta Yep, I like that idea. Essentially change the option to 'Auto Accept Defensive Casualties After Pause' or something. This allows you to always click past with space bar but solves the AFK problem by allowing auto passing after a short pause. Also makes this more acceptable as the default.
