### ISSUE TITLE
Travis build script should terminiate with error if installers are not created

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#5395]
See https://github.com/triplea-game/triplea/releases/tag/2.0.16345

**Comment by DanVanAtta** [comment]
Looks like a one-time problem where install4j was unable to download network resources, presumably the bundled JDK.

One issue of note is that the overall build did not fail, we should update this portion of the travis build script to not continue and to instead kill the travis build with an error code.
 
```
install4j: compilation failed. Reason: java.net.SocketTimeoutException: Read timed out
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':game-headed:platformInstallers'.
> Process 'command '/bin/sh'' finished with non-zero exit value 1

The command "./.travis/do_release" exited with 0.
```

I'll re-run this build and with luck this is a very temporary problem. If so, this is a good tracking ticket to fix the error reporting so that we can more pro-actively know about this going forward.

**Comment by panther2** [comment]
Allright, looks good now. Thanks!

**Comment by panther2** [comment]
@DanVanAtta 
It happened again with https://github.com/triplea-game/triplea/releases/tag/2.0.16450
No need to rebuild, as there are so many open PR.
Just to let you know.
