### ISSUE TITLE
installer auto-java bundle maybe not working

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#542]
From SF: http://tripleadev.1671093.n2.nabble.com/Next-release-1-8-0-11-testers-wanted-tp7590912p7591486.html

@gaborbernat , would you mind taking a look and give us your thoughts?

Installed prerelease on my netbook.  It tried to get the appropriate Java automatically, but this didn't work: 
```
ruin@ruin-tiger ~ $ ./triplea_unix_1.8.0.10.1026.sh 
No suitable Java Virtual Machine could be found on your system. 
Downloading JRE with wget ... 
--2016-03-03 09:41:20--  https://raw.githubusercontent.com/triplea-game/assets/master/install4j/macosx-amd64-1.8.0_66.tar.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 23.235.40.133 
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|23.235.40.133|:443... connected. 
HTTP request sent, awaiting response... 200 OK 
Length: 36572179 (35M) [application/octet-stream] 
Saving to: ‘jre.tar.gz’ 

100%[======================================>] 36,572,179   237KB/s   in 6m 19s 

2016-03-03 09:47:41 (94.3 KB/s) - ‘jre.tar.gz’ saved [36572179/36572179] 

Unpacking JRE ... 
Starting Installer ... 
./triplea_unix_1.8.0.10.1026.sh: 636: ./triplea_unix_1.8.0.10.1026.sh: /home/ruin/triplea_unix_1.8.0.10.1026.sh.14984.dir/jre/bin/java: not found
```

So I got it manually.  Still had to rename the revised files.

**Comment by gaborbernat** [comment]
sure will try to do in the days, sorry for the long hiatus was just relocating to London, new job and all that :+1:

**Comment by RoiEXLab** [comment]
I looked at the problem...
It seems, that the JRE is downloaded properly, but deleted just before launching tripleA.
I think it's supposed to be deleted _after_ exiting tripleA.
is the sh script generated by Install4j?

**Comment by DanVanAtta** [comment]
Interesting, which `sh` script in specific?

**Comment by RoiEXLab** [comment]
The unix sh script distributed in the releases section

**Comment by gaborbernat** [comment]
it should not delete it at all, it's a script generated by install4j from what I understand

**Comment by RoiEXLab** [comment]
I did a short Video showing what I mean...
Just ignore, that my OS is in german...
https://youtu.be/rqyxbmcirG8

**Comment by gaborbernat** [comment]
That's fine as the extraction removes the download, however it should pick up the extracted version. Will look into this shortly, I've just set up a virtual machine just for this as I am now on WIndows, with new notebook and all that.

**Comment by gaborbernat** [comment]
for lack of other bundle I went with mac bundle, it turns out this does not run on Linux, hence the error :) will need to create another bundle then.

**Comment by gaborbernat** [comment]
So I've reached out to the install4j developer team regarding this, here's their take on the story:

> It is still possible to create your own JRE bundles on Linux with Project->Create a JRE bundle and the bin/createbundle command line utility.
> 
> We have discontinued the official JREs bundles for Linux and Unix. They have created lots of problems for our customers (and consequently for us) since JRE binaries only work for a certain range of distributions. It is not within our abilities to map this parameter space. Also, 64-bit distributions with incomplete 32-bit libraries lead to failures of JRE bundles.
> 
> When there is a problem with a JRE bundle, we cannot provide any satisfactory solution. The only safe way is to install the JRE that comes with the distribution. Since Java is open source, it should be easy to install it through the distribution.
> 
> Of course it would be desirable if JRE bundles simply worked on Linux, but they don't. I'm sorry for the inconvenience.

Considering this I would argue that anyone who has a Linux installation has the expertise required to install Java on their system, most probably. Therefore I would drop bundling Java with the UNIX installer, and place a such notice on the download page (that is that having a Java 8 is required before installation). It seems doing any level of customization on it will be just a constant source of pain for us to maintain. What do you think @DanVanAtta  @ron-murhammer @veqryn ?

**Comment by DanVanAtta** [comment]
Interesting. There are also not that many linux users. I'm happy leaving off the bundled version for linux.

**Comment by RoiEXLab** [comment]
I have an idea, which could work eventually. Install4j offers a rpm/deb packaging service. If you could host a PPA on Launchpad or whatever / an equivalent on the redhat/fedora/opensuse side and add the openjdk as a required dependency. This would allow for automatic updating and solve the JRE implementation "issue"

**Comment by gaborbernat** [comment]
I would advise not to be part of the official ppa, if someone wants to do
it, he can especially using the silent installer option. Would not want to
use our time on supporting os specific issues .

**Comment by DanVanAtta** [comment]
I would tend to agree with @gaborbernat , interesting idea, but likely not worth it. We are not supporting very many users by doing so as well, linux users can install a JDK8 fairly easily. We'll update the website simply to give some instructions to linux users.

The goal is to have folks go through the github.io website to download, not from github releases.

**Comment by RoiEXLab** [comment]
> The goal is to have folks go through the github.io website to download, not from github releases.

Yeah you're right but what I'm saying is not ruling out the github.io page.
What I'm trying to say, is that using a .deb/.rpm package will be a good replacement for the unix installer.
The first possibillity would be to include all of the triplea files into the archive and just install it into a fixed location (like /opt/triplea or /home/triplea). Using the GUI version of Install4j I created a package installing triplea into /home/triplea requiring openjdk-8-jre to be installed - auto installing it when not available (if the openjdk is in the official packages). 
This way TripleA could

- Easily installed per command line
- Updated with apt-get/equivalents on redhat fedora opensuse systems (if the packages are hosted on a package server)
- Always use a up-to-date java without requiring the user installing it (in most cases)

could not
- have an adjustable installation directory
- have multiple installation options in general (there would be no installer anymore)

I think that the "could not's" wouldn't be a big deal - Linux users generally don't use installers. Everything in linux is installed as a package.
Another option involving the package would be more complicated. in this scenario the user would still download a sh file - which would download an empty deb/rpm whatever package "requiring" the openjdk - instantly removing it and after that launching the installer _without_ bundled JRE

Using this method wouldn't be a big advantage - more something like a workaround in order to check if there is a openjdk installed and installing one if not.

What do you think?

**Comment by DanVanAtta** [comment]
What's the problem that we solve? 
- Missing JDK8 for linux users
- Able to install/upgrade via sudo apt-get

The PPA is cool, but I don't think it's necessarily worth it. Not many linux users, most are able to get J8 or have it easily, and we don't do many releases yet. For the moment you also need to control a bit how to upgrade because of the versioning issues.

I would tend to think we can work on other items. For example, there are still gaps in the automated deployment to lobby bots, the script I wrote to do so needs debugging. We have plenty of game features to add in, and last, the CI pipeline we have goes pretty far. So my 2 cents are I think it's interesting, but not necessarily worth it.

**Comment by gaborbernat** [comment]
For now I think this is done.
