### ISSUE TITLE
Invalid map list override setting error

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#5485]
**Describe the bug**
https://forums.triplea-game.org/topic/1645/can-no-longer-download-any-maps

If the "map list override" setting is set to a non-existent location then you get a generic and pretty bad error that prevents downloading maps.

The issue appears to be related to `readLocalFile` method returning an empty list rather than null which causes it not to default back to the standard download list: https://github.com/triplea-game/triplea/blob/master/game-core/src/main/java/games/strategy/engine/ClientContext.java#L63

![image](https://user-images.githubusercontent.com/1427689/68982479-bfc06000-07cc-11ea-833a-f809cfb685db.png)

![image](https://user-images.githubusercontent.com/1427689/68982487-cd75e580-07cc-11ea-903e-b75532924d32.png)

**Comment by ron-murhammer** [comment]
@DanVanAtta Any insight here?

**Comment by DanVanAtta** [comment]
- Probably a case where using a custom exception type would give a better and more direct error message. 
- The console probably should info log that an override location is being used (IIRC, info log is ignored on console? That may be another thing to fix, eliminate info log noise and print the info log to console) 
- A confirmation when setting the override to a non-existent folder would be prudent
- A warning dialog instead of exception would be better, detect this scenario instead of just letting the game explode.

I don't have the bandwidth to work on any of these in the short/medium term. AFAIK the map override is not popular, it enables a work flow most are just not familiar with. It's possible to clone a map and work on it directly without mucking around with the actual map installs, or to create a parallel map zip and work on that without mangling real maps. It's an easier flow when doing such work as you don't have to remove/restore original map files when you want to go back to playing an unmodified map.

**Comment by DanVanAtta** [comment]
>  it enables a work flow most are just not familiar with

To expound, when working on maps, you don't have to do *any* file zipping now.

**Comment by DanVanAtta** [comment]
We may also want to take a look at the system check, it seems like those checks are just ignored/confusing vs actually telling people when they are in a state where parts of the game are not expected to work. If the internet connectivity check is checking the map download list, that is a bit broken.

**Comment by ron-murhammer** [comment]
Ok. This isn't high priority given its a rarely used property. I think the quick fix is just having the method return null so that it defaults to the non override map list instead of throwing an error.
