### ISSUE TITLE
Auto SpotlessApply (?)

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5487]
Builds failing because spotlessApply was not run are pretty common and a bit annoying to see that kind of failure. We could set up travis to auto-run it and commit and changes. If the 'merge conflict' is bad it's not too hard to force push over the auto-committed change, and usually it's rare for a branch to need modification once it's been pushed and is up for PR.

Thoughts?

**Comment by RoiEXLab** [comment]
Good idea.
Since spotless was introduced I really got into the habit of not caring about formatting at all, so I usually run the spotless task from intelliJ just before commiting (If I would use IntelliJ for commits as well, I could even configure that as a pre-commit hook, but I really prefer my other GUI solution right now), but there are times where I just forget this, so a clear win IMO

**Comment by DanVanAtta** [comment]
@RoiEXLab as you noted, we can't push back to a branch from a PR with any kind of secret token. That seems to torpedo this idea. We could have a bot do a follow-up PR to correct any issues, but that would get very messy.
