### ISSUE TITLE
ProMoveUtils and IMoveDelegate should be refactored to work on Move objects

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#5499]
ProMoveUtils and IMoveDelegate should be refactored to work on Move objects.

This issue is to capture the refactoring proposed as a follow up to:
https://github.com/triplea-game/triplea/pull/5416

Currently, three parallel lists are used by the Pro AI to keep track of moves. This is messy, instead it should be a list of Move objects. I plan to address this.

**Comment by ron-murhammer** [comment]
@asvitkine Looks like there are some bugs in the current functionality. I think it would be better to do some more testing before further refactoring.

**Comment by asvitkine** [comment]
Thanks for the heads up. Agree about fixing any issues with the current functionality before more refactoring. (Which is why I wanted to do the refactoring in separate PR. :)

**Comment by DanVanAtta** [comment]
To super nit on terminology, refactoring is a process where code that is already tested is simplified. Changing code without writing tests for it first is re-writing. Refactoring is 'safe' so long as the tests are good, TripleA is devious because most code can hardly be tested without first being re-written.

I mostly call this out so that our response is not to "be more safe, don't simplify, be surgical", but instead to increase test coverage which pays dividends in safety of changes and the potential simplicity that can ensue. IE: the response should not be "don't make changes", it should be more "write better/more tests".
