### ISSUE TITLE
Convention? Favor Collections.emptyList() over List.of()

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5524]
Favor:
```
Collection<String> empty = Collections.emptyList();
```
Instead of:

```
Collection<String> empty = List.of();
```

--------------

### Decision

Favor `List.of()`

**Comment by ron-murhammer** [comment]
No strong opinion either way from me.

**Comment by DanVanAtta** [comment]
Thanks!
Me and @asvitkine have weighed in, any thoughts on this @RoiEXLab & @ssoloff ?

**Comment by asvitkine** [comment]
One other point:

I didn't address your comparison to .isEmpty() vs. == 0 earlier, let me do so now. In my mind, I don't think it's the same.

Some of the reasons to prefer .isEmpty() aren't relevant here:
 1. When not using .isEmpty(), you have to then debate whether it should be ".size() == 0" or ".size() < 1" (and ".size() > 0" or ".size() != 0" for the inverse). Without a convention, all of those end up being used in a codebase. So isEmpty() eliminates that decision/inconsistency with the alternative. This doesn't apply for List.of() since there's only one way to do List.of() for an empty list.
 2. The ".size() == 0" check is more complex - it includes a method call, an operator and a value to compare against. Whereas isEmpty() is just a method call - so simpler at the callsite. Again, List.of() doesn't have any issue here - and can be argue to be simpler at the callsite since it's shorter than the alternatives.

So given those 2 points, I don't consider drawing the analogy List.of() to ".size() == 0" as fair - the latter has very clear reasons why you'd want to prefer isEmpty(), that don't apply to List.of().

**Comment by DanVanAtta** [comment]
Good points @asvitkine . I'm curious if you have any comment to:

- equivalence between `List.of()` and `List.of(new String[0])`. This is bothersome as seems we have an unused arg. Variatic args, my impression, are typically for 1 or more args, zero args case seems a bit unnatural.

- `List.of()` is same as `Arrays.asList()`, previously `emptyList()` was still preferred, why would the `List.of()` API change that? Why have a `emptyList()` api at all if there was `Arrays.asList()`

**Comment by DanVanAtta** [comment]
FWIW, some counts on how many we have of each:
```
dan@dan-desk:~/work/triplea$ find . -type f -name "*java" | xargs grep -E "List.of\\(\\)|Set.of\\(\\)|Map.of\\(\\)"  | wc -l
39
dan@dan-desk:~/work/triplea$ find . -type f -name "*java" | xargs grep -E "emptyList\\(\\)|emptySet\\(\\)|emptyMap\\(\\)" | wc -l
141
```

**Comment by DanVanAtta** [comment]
Another point that just came to mind, in tests it's common to static import, indeed very often having the static import `emptyList()`. Seeing: `of()` as a static import could be a bit odd and would conflict with the other `of()` methods.

**Comment by ssoloff** [comment]
I guess I'd prefer `List.of()` simply to have One Factory Method To Rule Them All, as opposed to choosing between `Collections#emptyList()`, `Collections#singletonList()`, and `List#of()` depending on whether I was creating a list of size 0, 1, or N.

* I think it's fairly clear that an empty list is being created with that syntax, but I may be biased because I'm used to seeing `listOf()` in Kotlin code as idiomatic syntax for creating an empty list.
* It's potentially one less import.  `List` is ubiquitous, while `Collections` is less so.

**Comment by DanVanAtta** [comment]
Any thoughts then to the static import inconsistency in test files @ssoloff ? Beyond any biases, I find that to be the biggest stickler. Or perhaps we just make an exception for tests that we do not static import `List.of()`

**Comment by ssoloff** [comment]
As `of()` seems to now be the prevalent name for factory methods across newer portions of the JDK, I would recommend _never_ statically importing it from any type in either production or test code.  In addition to the aliasing problem you noted, the terseness of the name itself might make it hard to understand what exactly is being created, especially when used as a method argument.

Take, for example, `foo(1, of("bar"), true)`.  Is the second argument a list of one string or some kind of conversion from a string to a domain type?  `foo(1, List.of("bar"), true)` or `foo(1, PlayerName.of("bar"), true)` clears that up without having to gather extra context.

**Comment by DanVanAtta** [comment]
That was in part my point, in prod code we tend to avoid static method imports, in test we favor them. Hence we'd want to make a call-out/exception to static import the `of` method.

**Comment by DanVanAtta** [comment]
This showdown should have more cat pictures:

![12517933-showndown-photo](https://user-images.githubusercontent.com/12397753/69136764-4779c900-0a70-11ea-805e-7ff1e6f58f6e.jpg)

**Comment by DanVanAtta** [comment]
Overall I think there are some good points here and @asvitkine and @ssoloff convinced me.

Particularly thinking of how many ways there are to create a List:
```
Arrays.asList
Collections.singletonList
Collections.unmodifiableList
Collections.emptyList
````

I found this blog on this topic: https://www.geeksforgeeks.org/collections-singletonlist-method-in-java-with-examples/

It has some good points in favor of `List.of`

> Collections::singletonList will happily create a List of null.

> The List::of method's ImmutableCollections.List12 type is the strongest in terms of immutability; 

> All but one of the List::of methods accept a fixed number of named arguments, from one argument (as shown above) all the way up to 10 arguments–all for the sake of avoiding the varargs array penalty.

> Both Collections::singletonList and List:of are great choices for creating single-element lists. If you're fortunate enough to be using a version of Java that supports both methods (9 and above), then I recommend going with List:of for its ease of use, readability, and better-documented immutability.

**Comment by DanVanAtta** [comment]
Mass update PR is up and wiki is updated: https://github.com/triplea-game/triplea/wiki/Code-Conventions
