### ISSUE TITLE
http_server code name

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5558]
"Marti" dice roller really works well for naming. We can talk about 'marti' and it's pretty well known. An old code name for the lobby was 'sanjuro', I don't think that necessarily stuck and we just called it the lobby.

The new lobby, 'http_server' is a bit of a poor name for what it is. Error-reporting functionality is on it, so it's not strictly the lobby anymore either as error-reporting supports single-player games.

Do we want to keep calling 'http_server' as 'http_server', or give it a fun name? If so, any suggestions?

**Comment by RoiEXLab** [comment]
> sanjuro

I still found some artifacts of this name on the lobby server in some configs that haven't been touched for ages.

Regarding `http_server`, I don't know if forcing a name would just work without writing it down somewhere.
I think the reason the name "lobby" stuck is because it's referenced everywhere, in the code, in error messages, in the forum.
Same with MARTI.

So if we do come up with a catchy name, we'd have to advertise it everywhere without any exceptions.

I don't have a good suggestion, but I think people will still continue calling it the lobby, because on the surface it does the same thing.

**Comment by DanVanAtta** [comment]
There are a few terms that reference the system component, "the engine" (game-headed), "lobby". MARTI AFAIK is made-up (I'm curious if MARTI is a name for something else and not made up, but I think it's made up). 'Sanjuro' did not stick for super long, it was an internal name, I vaguely recall there was a DNS entry for that name that provided a debug output.

For http-server, I think the codename would just be a prefix, so we'd call it "X http-server". I thought about this briefly and figure a WWII theme makes sense. My suggestions:
- "Spitfire http-server"
- "Spitfire server"
- "Mustang server"
 
"http_server" perhaps is already technically wrong as it's a websocket and HTTPS server, but also the HTTPS is due to NGINX proxy, so it's a HTTP and WS server. Perhaps could be good to then replace the "HTTP" part of the component name to our desired codename. I'm leaning a bit towards "spitfire server"

**Comment by RoiEXLab** [comment]
"Spitfire" sound like a really cool name for a server.
If we change DNS entries (or just add one) to `spitfire.triplea-game.org` and change loading screens and text in the engine to mention this name somehow ("Connecting to Spitfire on <dns entry>:<port>", "Create account on Spitfire", etc.).
I really think this could work as a codename.

About the Marti thing, IIRC it's written as M.A.R.T.I. on the server, implying to be an acronym of some sort. So it's probably something made up to match some fine tuned description of what it's doing. Not sure if that's actually true though.

**Comment by ssoloff** [comment]
> IIRC it's written as M.A.R.T.I. on the server, implying to be an acronym of some sort.

```html
<title>M.A.R.T.I. Server -- "more accurate rolls than irony"</title>
```

https://github.com/triplea-game/dice-server/blob/bb07730886f904c24328ad478fd3c6b7f7214f8d/src/MARTI.php#L9

"Irony" is apparently a reference to another email-based dice server: http://www.angelfire.com/art/avas/mailroll.html

**Comment by RoiEXLab** [comment]
Nice research @ssoloff 
I always wondered what this slogan actually meant.
Had a look at it and it explains a lot why the dice server is what it is today.
Also it's funny/horrible to see how terrible websites can end up looking if not maintained for an extended amount of time (I checked archive.org, it hasn't changed since at least 2013 when the first snapshot was made), also the counter of mails sent has overflown, so it shows a negative amount 😂

A thing we might want to consider re-implementing somewhere is signed emails, to verify they actually were sent by Marti.

Anyways, I'll try to migrate Marti to the new triplea-game.org today, let's see how it turns out. After that we can have a design discussion about a replacement.
