### ISSUE TITLE
Code Climate GateKeeping

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5634]
We're already getting some more experience with code-climate, the inline comments are pretty nice!

I'd like to propose the following guidelines for when code-climate issues are blocking and/or should be fixed:

1. new code should pass code climate. So for example if we create a helper function, do an 'extract-method' refactor, or are writing brand new code.

2. existing code that is more than 50% modified should be fixed. For example, if half of a class is re-written or updated, then the class should be fixed to be issue free. 'Rename variable' refactors would be an exemption. 'Move-method' refactors would also be an exception.

3. Do a best effort to fix code climate issues, we do want the issues fixed, we should try to get them fixed if the risk of the original update is not too high.

4. Respond to inline comments from code-climate when things are not going to be fixed. Either we can say, it's existing code that was not touched very much, we can state that the refactor we did causes an exemption.

Long term, I don't know if we will ever be able to hard-require code-climate to pass for merges. Touching legacy code can trigger issues to be detected, so it might be a while before we can reasonably do this. In the meantime, the above are hopefully strong enough guidelines where we will not just always ignore the analysis.

**Comment by RoiEXLab** [comment]
Seems reasonable 👍

**Comment by ron-murhammer** [comment]
I'm fine with that as well.

**Comment by DanVanAtta** [comment]
@ron-murhammer good consideration. For legacy code, I'd fully agree. I suspect most legacy code will take a long time before we get it even close. For example, we have methods/classes that are at the 500+ level for complexity.

I think then thresholds are more important for new code. I suspect it's probably better to have the 'real standard' we want for new code so we are directly at an end state. I'm thinking that will help with the "Drain the bathtub", that we prevent new code from introducing any new issues.

Thoughts?

**Comment by DanVanAtta** [comment]
Thinking about this, I would agree even for new code, we probably would want slightly more lenient thresholds so we can separate the clear violations from the "almost violations". As @ron-murhammer mentioned, reduce the noisiness.

**Comment by asvitkine** [comment]
One thing I noticed is that trying to address codeclimate findings makes PRs larger and thus harder to reivew (i.e. bigger diff unrelated to the change itself due to extra refactoring). I'm not sure this is a good thing.

For example, for https://github.com/triplea-game/triplea/pull/5723 - the base change is literally adding a block like:

    if (!transportsToLoad.isEmpty()) {
      final List<Unit> allUnits = addMustMoveWith(units);
      final Collection<Unit> loadedUnits =
          TransportUtils.mapTransports(route, allUnits, transportsToLoad).keySet();
      return validateMoveWithDependents(loadedUnits, transportsToLoad);
    }

But with the extra refactoring to satisfy code climate (i.e. extra helper methods, moving params to class members to reduce number of params, etc), the change is quite a bit longer, to the point that reviewers are confused about the logic that's just moving to a new function but not being changed.

Also all the extra back-and-forths on the PR increase the time before the PR is landed.

Should we perhaps consider a policy where a PR that's modifying existing code is allowed to make codeclimate unhappy and improvements would be done as a follow up?

**Comment by DanVanAtta** [comment]
Good points @asvitkine , how to structure such updates is a question. I wonder if structuring PRs commit-by-commit is reasonable. 

Item (2) in the OP was meant to help address such situations:

> existing code that is more than 50% modified should be fixed.

Really at issue is also that we have thousands of violations/smells and code climate is very unhappy with a lot of existing code. How do we make progress on these problems? It's particularly stinging that these problems are not necessarily of our own making.
