### ISSUE TITLE
Should we have a bot play some AI-only games to validate PRs?

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#5648]
Should we have a bot play some AI-only games to validate PRs?

For risky changes, reviewers often ask to test by playing an all-AI game, which can uncover bugs.

But this is something that's tedious to do and not always done.

A recent refactoring change I've made missed a problem that was later found via an all-AI game. Should we set up a bot that plays an all-AI game and validates that there are no errors?

I'm not sure how bots are set up, but if it's too much trouble to do something custom, perhaps it can be done as a JUnit test - where the test literally runs the full all-AI game to completion.

**Comment by DanVanAtta** [comment]
This would be a great verification. Soon in addition we'll want to add compatibility checks, that we can load a save game from the last version and a client of the previous version can host/join games of the latest version.

Compatibility aside, we have a smoke test module that fires up a headless bot. The thing that is missing is there is no capability to set 'AI' players in a headless game. I tried updating the connection logic so that a player can join with a bot player to play for them. Using this, when all spots were filled, the game did start up, with all AIs. Connecting and observing it, all the AI players never took any actions, they just advanced their turn without moving or doing anything.

Overall it should be feasible to set up this kind of test. The non-determinism could be a problem, but it'll be well worth the verification. If we are successful, setting this up on a couple of different maps would probably be a good move as well to add yet more coverage.

**Comment by RoiEXLab** [comment]
I mean IIRC we should be able plug in an arbitrary random source, so we could create a deterministic random source that is only used for testing.

**Comment by DanVanAtta** [comment]
@RoiEXLab the problem is there is no way for bots to join auto-hosted games. The headless server logic assigns player positions to nodes. If we can solve that, then this should be very do-able.

@asvitkine is this just an idea, or something you'd like to follow-up with?

**Comment by asvitkine** [comment]
@DanVanAtta it's mostly an idea that I was hoping someone more knowledgeable than me in this space could do. I still have a list of other things I'm hoping to improve in TripleA - and still TODOs to address from my earlier PRs.

**Comment by DanVanAtta** [comment]
Thanks @asvitkine 
I added these notes to the "areas of need" wiki: https://github.com/triplea-game/triplea/wiki/Areas-of-Need

```
* **Better/More Tests**
  - improve test coverage
  - additions to smoke test
    - launch a game with AI players, run through a number of rounds and verify no errors
    - download a map, verify it is installed
    - load a save game from the latest version, verify still compatible
    - verify a client of the last version can connect to a latest host, and vice versa 
```

**Comment by DanVanAtta** [comment]
One quick comment/thought that came to mind on this topic, this is great for finding general errors. For AI updates, we'd have to go a bit further. For example we'd need to set up a demo scenario and verify that the AI can win, does amphib assaults, scrambles etc.. It's important that the AI not only functions but behaves well.
