### ISSUE TITLE
BB won't repair

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#5659]
**Describe the bug**

**Engine Version or SHA**

**To Reproduce**

**Expected behavior**

**Screenshots**

**OS (please put an X in the appropriate box):**
[] Windows
[] Mac
[xon 13066

] Linux
/home/greg/Desktop/BB won't repair.tsvg
**Zipped Save Game**

**Additional context**

**Comment by beelee1** [comment]
how to fckn send a save game to git wtf
[BB-won't-repair.zip](https://github.com/triplea-game/triplea/files/3920495/BB-won.t-repair.zip)

**Comment by beelee1** [comment]
triplea probably can't fix this. Before start of CombatMove is how it's set up. Anyway just spent 3 hours trying to make this report so w/e

**Comment by DanVanAtta** [comment]
![Now you know](https://media.giphy.com/media/5eG28RENYdnMrrHuwq/giphy.gif)

@beelee1 thank you for sending the bug report :+1:

**Comment by panther2** [comment]
@beelee1 
By the rules in Global damaged capital ships repair during Purchase Units Phase. TripleA has this step at the beginning of the combat move phase.
As the repairs have always worked correctly in the current stable I did another test: I edited the damage during G1 NCM ... and the damage correctly was correctly (as by TripleA) removed at the very beginning of G2 combat move phase:

[BBrepairs.zip](https://github.com/triplea-game/triplea/files/3920977/BBrepairs.zip)


That leads to the conclusion that in your savegame the issue might be caused by the fact that you edited the damage during the production phase immediately before the repair step, which then for any reason is ignored.

**Comment by beelee1** [comment]
Sorry for the tantrum. i'm gonna make a video for myself so i remember how to do this. : )

@panther2 Yea I got a save game where it happens in normal game play. I think it has to do with the French capital being lost, making it go directly to combatMove phase, which doesn't allow time to repair.

/home/greg/triplea/savedGames/Oztea 1939 1.83 November 27 2019.tsvg

Go to French RD 5 turn

Idk that triplea can work around it as it would change when all ships repair. Anyway, it's a easy edit, just wanted to mention it as I hadn't noticed it before

**Comment by beelee1** [comment]
`/home/greg/triplea/savedGames/Oztea 1939 1.83 November 27 2019.tsvg
`

**Comment by panther2** [comment]
@beelee1 It is no bug that a damaged Battleshi is not repaired when your capital is in enemy's hands.
As long as your capital is lost you skip the Purchase Units and Repair Phase. No repair during that time!
