### ISSUE TITLE
PR label practice

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5662]
I haven't added PR labels everywhere, but it does seem like I am the only one using them. I'd like to drill down on their utility and see if we can come up with a plan where we all apply PR labels.

I see a few options:
1. Stop labeling PRs
2. We use existing PR labels as a team and spread the practice (what would this require?)
3. Narrow down which PR labels are useful and focus on benefits

Benefits of labels:
- know which PRs to include in release notes
- can visually identify if anything in the PR queue needs attention.

(I'd strongly argue that for maintainers, keeping the PR queue reviewed and PR authors unblocked is the highest priority of standard tasks for maintainers. Hence, it's important that we can efficiently ensure all PRs are waiting for author input and not maintainer feedback)

**Comment by RoiEXLab** [comment]
Hmm I think labels on issues are useful, because it makes clear what this issue is all about and what the author expects from participants.
"Discussion" -> Post your thoughts about a certain topic
"Bug" -> No discussion required, depending on author check if this is a valid report
"Production Problem" -> Something important
Etc.

For pull Request however I think labels are only useful if they provide information thaf would actually influence the way those PRs are handled.
For example if a PR contains AI changes, and we have a label for that @ron-murhammer might have a look at this particular one even if somebody else already started reviewing.
Or maybe if a PR had a label "follow-up ready" reviewers could prioritize this particular PR over others.

But if a label really only is a label that just provides some information that is nice to know, but not really important then I don't think labels provide much value there

**Comment by ron-murhammer** [comment]
I haven't had many PRs over the lasts few weeks. My general feel is similar to @RoiEXLab and we probably have a few too many PR labels. I think if we can keep the number of labels to 5 or less that have value then I think we can get people to consistently use them. Any more than that and it becomes a chore to think about which ones to use when.

**Comment by DanVanAtta** [comment]
IMO we should be careful of information silo's and practice peer review. That means you don't need the infrastructure, or AI guru to review any such changes. Anyone should be able to review anyone else's changes to anyplace in the code. If you feel like you don't have enough context, then you can '@mention' a person who you would want to bring in for review or to review a specific point. If we have only certain people review certain changes, then it's not really peer review anymore (and can easily become gatekeeping)

I'll re-iterate these benefits of labels:

> Benefits of labels:
>    know which PRs to include in release notes
>    can visually identify if anything in the PR queue needs attention.

With labels+assignees, we can know when the queue is fully worked/reviewed. We should probably change stalebot to close out PRs that are open without activity much sooner. Branches living for more than a few days is bad practice, branches running for weeks on end is quite bad. Part of that, means reviews, at least an initial one, needs to happen same-day or next day. If we have many PRs in queue, then it's just difficult to know which PR is next in-line to get some attention.

For release notes, it's a real bear to go through the PR queue and know which ones to include, and we're going to miss things if we go just by title alone. Hence the 'feature add/change/remove' so we know how to include them in the notes.

@ron-murhammer it turns out we "only" have 7 labels for PR, the 3 for feature changes that directly feed release notes, problem fix (which might also feed release notes) documentation, simplification, and configuration. 

The other PR labels are to mark when a PR in queue needs some work by the author to be merge-ready (which is not ideal, but sometimes after a review we see that something is not quite ready, or we are close on something and do not expect changes but want to get the review started or out of the way). EG: a PR ha been reviewed and is just undergoing final testing (PR: testing), or a PR has been reviewed but now needs merge conflicts to be fixed, or a PR has been reviewed but now needs updates and is a work in progress. 

I think the questions are really:
- how do we keep the PR review queue effectively at zero?
- how do we update the release notes in a sane way and not miss items?

**Comment by RoiEXLab** [comment]
I like the idea of using labels to create release notes, I think this would encourage me to use labels more often.

Regarding the PR queue:
Currently the ansible PR is mostly blocked because of the lack of testing, but in theory it could be merged. What I'm trying to say is that the reason PRs are open for over a week, isn't because of a slow review process, but rather a delay from the author that just haven't got the time to get back to it.

**Comment by DanVanAtta** [comment]
Wasn't meaning to pick on any specific PR. Long lived branches in general is a bad thing.

Sounds like we are probably agreed that labels are useful for release notes.

For knowing if a PR is 'in-progress', or more specifically does not need a review, perhaps we can use assignee's. If something is being worked on, then we assign to the author and reviewer, and they then just `@` mention each other when ready for review or when updates are needed. The other reviews can then skip over anything that is already assigned. 

Sound like a process? If so, we can remove the "PR: merge conflict", and "PR: work in progress" labels, all labels that indicate a waiting PR state and use assignments instead.
