### ISSUE TITLE
Email Credentials in 2.0.17997

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#5921]
I might have missed that - but where are the login-credentials, entered in the "Play by Forum/Email" section of the "Engine Preferences" saved? And are they saved in an encrypted way?

**Comment by RoiEXLab** [comment]
On windows, the passwords are stored in the registry, encrypted with a fixed key to avoid accidental leaks.
I'm not sure if you're able to set a master password for this.
However if you want "true security" you probably shouldn't store it there

**Comment by DanVanAtta** [comment]
Any thoughts on prompting users for email password and never storing it? If the passwords are recoverable in plain-text, then they are recoverable in plain-text no matter how we do it.

We may want the same for the forums password. The convenience trade-off is more favorable for forum password. For me at least, probably most people, email password being compromised is as bad as it gets and results in actual financial ruin.

Second consideration/question, we seemingly have a perfectly good email server running on warclub, why not always use that for email?

**Comment by panther2** [comment]
As long as all login details for forum and email including passwords are stored encrypted personally I can live with that, as I am using different logins/email-addresses/passwords for different purposes.

Generally I would welcome a solution being prompted for login details without storing them anywhere. Wasn't it like this in the past? I had to mark "remember me" to have those details saved, IIRC. 

Maybe this might be a solution:
In case there are no details entered in the "Engine Preferences" and the user chooses PBF/PBEM prompt him to enter the details when either testing to post or trying to post his turn. In a respective dialogue the user could be asked to "pemanently save" the details ("remember me") or to enter the details for a one-time puropse.

**Comment by DanVanAtta** [comment]
While the credentials we store are not plain-text, TripleA can recover their plain-text value, which means any attacker who finds the non-plain-text values could similarly use the same code as TripleA uses to recover the non-plain-text value. 

We could prompt for password once per game session and then 'remember' password and store it in memory. If we store the password in persistent manner, @RoiEXLab mentioned needing a master password which would be the way the encryption would be unlocked in a way that you could not just do so with the TripleA software. 

In sum, to keep it secure, it seems we either need to:
1. prompt for password and remember it in memory only if authorized by user
2. (or) require a master password to unlock an encrypted password that is persisted to the system

Any thoughts/other suggestions anyone?

**Comment by RoiEXLab** [comment]
We had a master password mechanism some time ago, but I don't remember what happened to it. Maybe @ssoloff does remember?

**Comment by ssoloff** [comment]
> We had a master password mechanism some time ago, but I don't remember what happened to it.

Any credential managed via `DefaultCredentialManager` is protected using an automatically-generated master password:

https://github.com/triplea-game/triplea/blob/36fd7319bde98a7ecdc57c46bfc2e0bee9452210/game-core/src/main/java/org/triplea/security/DefaultCredentialManager.java#L38-L42

The current implementation persists the master password to a location that is only readable by the user (the user preference store), so it is only susceptible to disclosure by a trojan running under the user's account (this is similar to how Firefox/Chrome manage passwords without a user-specified master password).

However, `DefaultCredentialManager` was designed in such a way that the master password can be injected, so it can come from a source other than the preference store.  As discussed in #1955, the idea was to eventually add support for prompting the user for the master password via the UI, if the user chose to not persist the master password to the preference store.

**Comment by DanVanAtta** [comment]
Thanks for the context @ssoloff 

Isn't the user preference store just stored in registry typical for most users? If so, getting a dump of the registry could then lead to cracking of the password. Perhaps one key difference in my mind is closed vs open source, it would be much easier to reverse engineer that knowing the full details of how the password is encrypted and stored. An analogy is that we're storing both the safe and key together in the same place.

If we query for a master password, would we be just as well to query for the actual password and not store the password? I'm thinking for sure we'd give an option to cache the value so that it would not need to be repeatedly prompted, but at least the value would not be persisted.

Thoughts?

**Comment by ron-murhammer** [comment]
@DanVanAtta @RoiEXLab Does this need addressed before releasing?

**Comment by DanVanAtta** [comment]
This conversation informs how to fix: https://github.com/triplea-game/triplea/issues/5856

**Comment by ron-murhammer** [comment]
@DanVanAtta Ok, does it make sense to consolidate the 2 issues then? Just trying to narrow down what issues need fixed for the next release.

**Comment by DanVanAtta** [comment]
Having email creds is a big deal. If anyone ever had those hacked (through TripleA as the attack vector), that would be entirely ruinous for them personally: https://www.wired.com/2012/08/apple-amazon-mat-honan-hacking/

Our options:
1. system as is, creds and decryption key stored on the same system. An attacker with access to registry could get both. Please correct me if wrong here, though " user's preference
 tree" is actually registry (last I checked TripleA, on windows, stored preference values there). 
2. introduce master password prompt, when logging in to TripleA, and after the system needs password for the first time, a 'master password' is prompted and kept in memory to unlock the users email password that is stored (encrypted) in preferences
3. prompt for password when it is needed, give a checkbox option to cache the value until TripleA is restarted (ie: password is encrypted, in memory, with a random master password)  

I think the choice tree is whether we want option (1) or not, if not, then the decision is between (2) or (3).

**Comment by DanVanAtta** [comment]
Crud, while thinking about this, an option 4 comes to mind pretty readily:
4. Give option to do (1 or 2), where password is remembered and stored on system, if not specified, then default back to (3). Getting the messaging about that would be kinda tricky as it is nuanced what trade-offs a person is making. 

Please chime in if there are more considerations or options to be made here too, would love to close this issue out soon with a plan of how to move forward.

**Comment by RoiEXLab** [comment]
@DanVanAtta The original idea was to allow for a master password to mimic the behavior of Firefox password store.
If you save your password in Firefox without setting a master password it will just generate some key and encrypt the passwords using that key which is just stored as a file on the system.
If you do set a master password however this key will no be derived from the password.
In the end you trade convenience for security and I think ideally the user was allowed to choose just like they can choose when using Firefox

**Comment by DanVanAtta** [comment]
Understood. Ya'lls attention to convenience and security is impressive. Though it seems like enabling the option for a master password and explaining the risk/trade-off is a current feature gap. Meanwhile, to use automatic email's at all, credentials must be entered and persisted.

Email credentials are as serious as they get as there is material financial reward to an attacker. For the most part TripleA is not a target as a successful attacker does not gain very much. This changes when there is potential to compromise an email address (which cant hen quickly provide access to all of your financial accounts).

We therefore have a decision to make, either:
A) Master password encryption
 - give user option to prompt for master password or to store it
 - add enough help options and dialogs to clearly explain the safety/security of these options. (For example, I personally do *not* let firefox remember my email password).
B) Prompt user for password
 - whenever needed we'll prompt the user for password
 - provide an optional 'remember' option that will remember the value for the running session
 - provide help options and dialogs to clearly explain the safety/security concerns for a 'remember' option

I don't think we can release 2.0 until we make and implement one of those two decisions above. If anyone is ever attacked/hacked, they should have at least have been informed of the risks.

If I'm the one implementing the above, I'm inclined to make an executive decision for (B):
  - reducing the attack value of TripleA is valuable. To get an email password with (B) you'd need a key-logger, or be able to do a heap dump at a specific point in time while TripleA were running. In either case that user is already fully compromised.
  - strikes me as a simpler route, I'm more confident to cache a `char[]` array with the infrastructure we have for a running process then to ensure there is adequate cryptography achieved for persisted values.

If anyone would like to take on this work, they are welcome to it, please chime in and let us coordinate efforts. I'm currently updating the PBEM UI to display all required fields in order to at least fix: "PBEM/PBF 'Play' button is never enabled #5856"

**Comment by DanVanAtta** [comment]
Went with a 'remember password' option (default off) available when you start a game. There is a help text stating there is a risk.
