### ISSUE TITLE
Java source compatibility level - 1.7?

### ISSUE THREAD

**Issue by gaborbernat** [triplea-game/triplea#6]
Can we up the source compatibility to 1.7? What do you guys think. Given that Java 7 is no longer supported one could even argue that even going to 1.8 is valid.

**Comment by DanVanAtta** [comment]
+1 
For 1.7

To make sure it's captured here, I think the long term answer is for us to log client JVM versions when people join the lobby. That data would answer this question.

**Comment by veqryn** [comment]
Lets get the data first.
Unless someone is going to refactor important parts of the engine to take advantage of 1.7 or 1.8, it might not be worth dropping 5% of our user base just to have a single line or two using 1.7 idioms.
FYI: if you are going to capture this, you should do it ASAP, because we plan to release soon (like in a couple weeks).

**Comment by DanVanAtta** [comment]
Some alternatives perhaps worth considering:
1. poll 20 people in the lobby on their java version. If any are less than 1.7 than we'll want to see data. If not, jump to 1.7, then in 2 years we'll see about getting some data to jump to 1.10 or something ;)

2. jump to 1.7 now, then get data, see about jumping to 1.8 if data supports it.

3. favor jumping to 1.7, but rack up a couple of reasons first

**Comment by veqryn** [comment]
i would personally like to jump to 1.7 or 1.8, but i would like more data then a quick survey

**Comment by veqryn** [comment]
I just remembered something, that will prevent us from moving beyond Java 1.6. Mac users are currently being asked to downgrade to Java 1.6 when they install Triple A as a Mac app. This is caused by our code using Apple Java instead of the new Oracle Java, and might also be caused by things in are build process. This is something we need to fix right away, & I have made 3 posts in our forum about it because this is the only thing I don't know how to fix.

**Comment by ron-murhammer** [comment]
Feel like we really need a mac expert. Seems to always be causing issues for us.

**Comment by gaborbernat** [comment]
this could be solved by porting the Mac installer to a more supported tool, see https://github.com/triplea-game/triplea/issues/31

**Comment by ron-murhammer** [comment]
Good idea. I think improving the Mac build process while we are implementing gradle would be very beneficial.

**Comment by veqryn** [comment]
uh,... i am pretty sure we also need to figure out what to do about the java code that directly references things that might only exist in apple's java

**Comment by gaborbernat** [comment]
of course :) 

for now I'll keep the Apple extension jar, but will look into what can be done. Not so many classes using it:

> bernat@g22 ~/stuff/triplea (installer)$ git grep com.apple
> src/games/strategy/common/ui/BasicGameMenuBar.java:import com.apple.eawt.Application;
> src/games/strategy/common/ui/BasicGameMenuBar.java:import com.apple.eawt.ApplicationAdapter;
> src/games/strategy/common/ui/BasicGameMenuBar.java:import com.apple.eawt.ApplicationEvent;
> src/games/strategy/common/ui/MacWrapper.java:import com.apple.eawt.Application;
> src/games/strategy/common/ui/MacWrapper.java:import com.apple.eawt.ApplicationAdapter;
> src/games/strategy/common/ui/MacWrapper.java:import com.apple.eawt.ApplicationEvent;
> src/games/strategy/engine/lobby/client/ui/MacLobbyWrapper.java:import com.apple.eawt.Application;
> src/games/strategy/engine/lobby/client/ui/MacLobbyWrapper.java:import com.apple.eawt.ApplicationAdapter;
> src/games/strategy/engine/lobby/client/ui/MacLobbyWrapper.java:import com.apple.eawt.ApplicationEvent;

**Comment by djensen47** [comment]
+1 for Java 1.8 

I'm sure Lambdas will come in handy and it's quite a nice language feature. I wish I had it for Android development. (retrolambda is not really an option for me)

**Comment by veqryn** [comment]
Ok, so Java 1.7 or 1.8, but only after Mac builds work perfectly on oracle java 1.7/8 on a mac (as both zip and dmg).
