### ISSUE TITLE
Save Game Should prefill a suggested save name

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6105]
**How can the problem be recreated?**
1. From a new game
- start a new game
- single player
- save game
- notice that the save text field for file name is free-form and probably blank

Expected: some sort of prefilled file name, perhaps date (YYYY-mm-dd + map name)

2. From a load game
- load game
- save it
- notice the save field dialog is blank

Expected: save game file name should be prefilled to be the name of the game that was loaded

**Comment by prastle** [comment]
:) Good Stuff

**Comment by DanVanAtta** [comment]
this will be fixed by: https://github.com/triplea-game/triplea/pull/6143

**Comment by beelee1** [comment]
so this still doesn't work quite as good as 13066. If you start a save, then make another save, it always shows the first save, instead of the new save. 

For example: I start with save game "test". I then save the game and name it "test 1". When I go to save again, it goes back to "test" instead of staying on "test 1".

On 19071
