### ISSUE TITLE
Joshua Bloch discusses Serialization - Serialization Proxy / Memento Pattern

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#614]
Joshua Bloch, the author of "Effective Java", discusses a way to handle some of the problems with serialization: 

https://youtu.be/V1vQf4qyMXg?t=56m12s (4~5 minutes to watch, the rest of the talk is very interesting as well)

It's very interesting. I think we could probably use it. 

Thoughts?

To be determined:
- What exactly would need to be done to break backwards compatibility if we used the serialization proxy pattern

**Comment by ron-murhammer** [comment]
Interesting, I'd be concerned that we might have object graphs with circularity. It seems kind of like using something like JAXB where really just is boiling objects down to its fields/state. I think in the long run we should definitely replace serialization not sure whether this is the best solution but definitely interesting. One note is I think getting rid of reflection is a higher priority than getting rid of the serialization.

Also, when possible please post articles instead of videos. Much easier to consume and I'm way more likely to actually look at them.

**Comment by DanVanAtta** [comment]
I'm surprised you did not mention how the pattern insulates you from incompatibility with serialization and reflection. If we adopt that pattern, we would no longer need to worry about it, the areas of concern would be well defined.

Getting it so we can modify code freely, without having to constantly worry about 'breaking compatibility' is a very important task. We have a lot of issues releasing as well because of these strict compatibility requirements that couple the code to the saved contents of our users hard disks. With the construct described, we would have a conversion layer, allowing backwards compatible changes.

@ron-murhammer , a note about priorities. Please up-vote stuff, not down vote it. A lack of context can cause for very problematic conversations to ensue, and avoids some subjectivity. With respect to articles, if there were a good article, then I would present it. A long article can be easily take 10 minutes. I would prefer something to read as well, but the source material is a talk, and it addresses our biggest problem.
