### ISSUE TITLE
SemVer - two dimensions of compatibility - save game vs network compatibility confusion?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6184]
I'm starting to wonder if we may have made a mistake in our current semver.

Notably there are two dimensions of compatibility that are really important, network and save game (not just one. Technically there are three with map compatibility, but that is generally less salient).

The scenario I'm thinking about is this, if we change network compatibility then we land at a `3.0` that is *compatible* with `2.0` save games. We could then have a `4.0` that is not save game compatible and suddenly 2.0 games can be played on 3.0, but 3.0 cannot be played 4.0. I think this could lead to players being confused and maybe not willing to upgrade to pick up network compatible changes.

I think we have 3 options to resolve this:
A) live with it
B) Add a build number for 'network compatible', ie:
```
{save-game-compat}.{network-compat}.{release-number}.{build-number}
```
C) Drop the 'release' number and use it for network compatibility, ie:
```
{save-game-compat}.{network-compat}.{build-number}
```

Please recall the release number is useful when we accumulate a lot of compatible changes or have an important update we want players to pick up. EG "hey, there is a big security fix in 2.3, please upgrade if you are still on 2.2"

**Comment by RoiEXLab** [comment]
Actually I think the current system is a good simplification.
My concern if we change it to something like `{save-game-compat}.{network-compat}.{build-number}` is that suddenly users think that `2.3` must be incompatible to `3.3` simply because they're used to this.

I also think that the version number is not the thing that needs changing. Ideally we have a "protocol" for savegames and the network that will stay the same for the near future, so the engine itself is able to check if it is compatible with this savegame/remote game.
For savegames we can also store the engine version the savegame was created with so we can tell users which version to ugrade to.
For networked games we can advise people to upgrade their client to the latest version/wait until the server owner upgraded to the latest version in case it is not compatible.

> "hey, there is a big security fix in 2.3, please upgrade if you are still on 2.2"

I also think there shouldn't be any particular reason to upgrade, users should be conditioned to always update if possible so they get the undetected security fixes as well.

**Comment by DanVanAtta** [comment]
@RoiEXLab we would decrement the network-compat back to zero and assume if save game compat is broken then network is too. Hence, `2.3` would not be compatible with `3.0`, `2.4` would not be network compatible with `2.3` but you could play save games from `.2.3` on `2.4`, but you could not play those save games on `3.0` (even if technically network comptable).

> I also think there shouldn't be any particular reason to upgrade, users should be conditioned to always update if possible so they get the undetected security fixes as well.

They are simply not well conditioned to this as much as we like. Getting people to upgrade more than a few times a year has historically been painful.

**Comment by tvleavitt** [comment]
Why not make the upgrade automatic on open and require them to
affirmatively reject it, and generate a warning that doing so risks
exposing them to security flaws, incompatibility with lobby / network games
/ future maps. Really, there's no reason to keep using older versions. Many
contemporary games don't even offer the option to not upgrade.

We can give an option to install to a new location if they need save game
compatiblity. Has a save game conversion tool be considered?

Thomas Leavitt

**Comment by DanVanAtta** [comment]
Historically there has been a "your version of TripleA" is out of date mechanism, but for the longest time there was a bug where if we triggered that messaging it caused a game freeze.. We're now finally at a point where enough users have that bug patched where we can trigger it.

I think in part the upgrade is not automatic as we just haven't invested in it.

Would automatic upgrades mitigate potentially confusion on compatibility?

An auto-update might actually bring map compatibility into play as we don't have a good way right now for maps to be playable on multiple versions, once they are 'upgraded' then they crash unless a user upgrades, and some maps will crash *if* a user upgrades. The coordination of version is certainly messy when it comes to maps, essentially our goal will be to avoid any non-backward compatible changes to maps for the forseeable future.

**Comment by tvleavitt** [comment]
My suggestion is to bite the bullet on the map compatibility issue... also,
you have a relatively small data set of maps, so it seems like you could
automate map compatibility testing, create bug reports for incompatible
maps and notify creators, then blacklist incompatible maps from loading,
etc. Check local versions of maps against available updates and
automatically download, etc. The list of compatible maps could be
downloaded on launch, etc.

Net effect, going forward, issue goes away because current version
incompatible maps can't be loaded or downloaded, and almost no one is
running old versions incompatible with current maps.

Maybe some pain at the start, but much less pain long term. Same thing with
network and lobby compatibility. How much consciousness do end users have
of what version of other games they're playing?

Only burden is save game compatibility, and that can be dealt with via a
combination of tools that either fix them or if that's unfeasible for some
really compelling reason, warning users to install upgrades to an alt
directory.

Thomas Leavitt

**Comment by DanVanAtta** [comment]
The plan is for maps to go into database for 3.0; that should help as we can restructure things a bit more. Otherwise map versions have issues:
- the current version is only for player notfications
- the actual version of a map is not specified in the map
- to know the "min" version of a map you have to parse its XML, which currently is prohibitive if we are to show a list of all available maps (we could do some pre-processing there, but it has not been built).
- there is no 'max' version, it's basically assumed by the design of the code that if you are above the min version of a map that it will continue to work. For example when we renamed values in the engine, all maps were no longer compatible even though the engine version was greater than the 'min' version. 
- The min version is not a map compatibility version specifically, and it is also in the XML, further compounding the need to parse maps.

FWIW, the suggestion to not list incompatible maps is ultimately the key and is perhaps why we have 2 major dimensions of compatibility rather than 3.

**Comment by DanVanAtta** [comment]
I don't think there is appetite to really revisit this; simpler semver is nice. Hopefully we can avoid player confusion when doing network only incompatible releases.
