### ISSUE TITLE
Using the moderator toolbox for info and bans.  Fails in multiple ways.

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#6204]
**How can the problem be recreated?**
    After testing today with Yama a  few more issues discovered with the toolbox.  Right click function to scan for info of players inside a hosted game or bot fails.  Right click on a user name  directly to ban a user works but from inside the toolbox it does not.  It does not ban nor remove the user from the lobby from inside the toolbox.   A moderator can be ignored! by a regular user!  This cannot occur!  More testing coming.

**Comment by DanVanAtta** [comment]
>  Right click function to scan for info of players inside a hosted game or bot fails. 

How do you get to the right click function exactly? I'm unsure what you are referring to @prastle . Kindly assume that bug reports are for people that do not know anything and walk us through step by step how to get to the problem you are seeing, it's the best way to be clear about the exact problem you are seeing.

> . Right click on a user name directly to ban a user works but from inside the toolbox it does not.

It works does not? :grin:  #yoda

The toolbox does not have right clicks, there is a button to do so from the access log:
![Screenshot from 2020-04-11 19-12-30](https://user-images.githubusercontent.com/12397753/79058897-6ef04e80-7c28-11ea-97b3-12b2b3ea1a66.png)


>  A moderator can be ignored! by a regular user! This cannot occur! More testing coming.

Yes, that's not an implemented feature for the moment. I've debated back and forth on this one:
- blocking a moderator is questionable, should we really restrict tools of a user. If a user ignores a moderator, then they just get banned without hearing the warnings. It is at their own risk.

@prastle please follow the question form a bit more closely, I'm unable to really find exactly what problem you are seeing. The moderator mute functionality is a different topic from toolbox forms.

>  It does not ban nor remove the user from the lobby from inside the toolbox

You're clicking the 'ban' button?? Do you have the user in lobby? Which version are you using?

Please cut new issues with more details @prastle

**Comment by prastle** [comment]
Sorry for the poor info as we discussed it was mainly a note to myself.

 Simple explanations coming.  

! join the new lobby as anon user using a banned bad word.  It allows you to join.

Ignore a moderator or admin only the slap function works.  They do not see the typed conversation.  A mod/admin should not be able to be ignored. 

Banning a logged in user from the toolbox directly fails to ban or remove them... Right clicking on user name in ? directly in the lobby still works when they are logged in.

Scanning a hosted game or a bot  using right click mod functions on the room/host in ? no LONGER WORKS!  example right click on a bot and select "get chat log of Headless Bot" all these functions are missing

**Comment by DanVanAtta** [comment]
Which versions are you testing @prastle ?

> ! join the new lobby as anon user using a banned bad word. It allows you to join.

I am unable to repro this: 
![Screenshot from 2020-04-12 10-32-22](https://user-images.githubusercontent.com/12397753/79075643-05fceb00-7ca9-11ea-8b2b-94addd1cb3bf.png)

To be clear, there is 'banned username' and 'bad word', I assume you truly mean 'bad word' which does a contains match against usernames both anon and registered.

> Ignore a moderator or admin only the slap function works. They do not see the typed conversation. A mod/admin should not be able to be ignored.

Indeed, that is something that was not built and is not expected to work. 
1) Let's challenge this requirement and reason why we really need/want it.
2) Ban messages are relayed to users automatically now, we do not strictly need for moderators to tell users they are being banned anymore
3) If someone wants to ignore a moderator, they do so at their own risk, no?

> Banning a logged in user from the toolbox directly fails to ban or remove them...

I see users getting kicked out of lobby, can you give exact steps and your version numbers and when you tested this and how. It would be surprising for this to not work as well as the code behind the two different kinds of ban mechanisms is unified. Are you reporting test results that were from a few days ago?

> Scanning a hosted game or a bot using right click mod functions on the room/host in ? no LONGER WORKS! example right click on a bot and select "get chat log of Headless Bot" all these functions are missing

I'm not sure exactly what you are expecting/seeing. If you are referring to the right click menu of hosted games, then yes there is no history and there is no scan to list players. It is working as intended there.

- getting history of bot chat is pretty involved, it's an element of feature parity I don't think we'll get for 2.0, perhaps 2.1
- getting the list of users in a bot should not be as needed (and is even more difficult then getting chat history). Bans will boot players from bots now.

>  all these functions are missing

While they were in 1.9, there were some major problems with rebuilding them as they were. The removal of the functions was intentional.


@prastle this is really 3 or 4 different bug reports, it's easier to talk about each one independently then to have to ask you 5 or 6 questions all at once. The fixes for each of these issues is going to be different as well, which makes this issue harder to close as we need to get many fixes in rather than a single fix that closes the issue. Please favor creating one issue per problem.

**Comment by DanVanAtta** [comment]
@prastle please chop this issue up into each of the independent problems, it'll be easier to deal with this as the 5 or 6 different bug reports. Also need version numbers, when this was tested, and as exact of repro steps as possible so we can be sure we're looking at the same problem (as is, none of these appear to be problems as they cannot be reproduced and/or are things working as intended).
