### ISSUE TITLE
booted from lobby 

### ISSUE THREAD

**Issue by SilverBullet1234** [triplea-game/triplea#6298]
**How can the problem be recreated?**
the lobby booted me twice today, maybe for inactivity? 

**When the problem is fixed, what should have happened instead?**

**Which Engine Version are you using?** 

**Screenshots** 

**Zipped Save Game**

**Comment by DanVanAtta** [comment]
Thanks for reporting. @SilverBullet1234 I think the 'boot' was during software deployments. If you have relatively accurate timestamps of when it happened, we could try to correlate it. Otherwise we change code potentially several times in any given day, on each update we install a new lobby with the latest code and players are disconnected when that happens.

**Comment by SilverBullet1234** [comment]
yes, prastle mentioned that also,  it was the only problem i had so far.

---------- Original Message ----------
