### ISSUE TITLE
Fullscreen MapPanel

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#639]
Normally a game has no "File", "View" or other dropdown menus on top of the screen when the game is launched...
I would like to make the MapPanel to a windowed fullscreen Frame and make all Game Relevant options into an Esc Menu.
All options not fitting into that menu will probably get moved to a place in the main menu...

**Comment by DanVanAtta** [comment]
Some mock-ups of what you are proposing would be good to see @RoiEXLab . There are some problems to be solved for sure. I do tend to think we have some bugs that could use squashing first. Alternatively i wonder if we can make the entire game UI better rather than having a different full-screen mode that you switch to. For example, making the right hand menu and chat area both re-sizeable, or have a collapse tab so they can be hidden. This way you could just hide everything, or the things you want, and get a full screen. We could assign a hot key to 'hide-all', and would get the same effect as a full-screen.

**Comment by DanVanAtta** [comment]
@RoiEXLab , could you clarify what you mean by an Esc menu?

**Comment by RoiEXLab** [comment]
I mean that we may have a menu showing up when hitting Esc instead of the Buttons on top

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/wiki/Feature-Back-Log/
