### ISSUE TITLE
Re-Introducing Codacy

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6567]
Researching how to get inline PR comments from sonarqube had me stumble back on codacy.

I re-enabled it for TripleA to do scanning: https://app.codacy.com/gh/triplea-game/triplea/dashboard

You should now see the check in PR status (perhaps with in-line comments :crossed_fingers: )

We previously discussed introducing and then removing Codacy in:
https://github.com/triplea-game/triplea/issues/1850
https://github.com/triplea-game/triplea/issues/2498

The reason for removal was notably due to a lack of analysis, we were mostly getting just checkstyle. It looks like codacy is now covering a pretty wide variety of checks.

![Screenshot from 2020-06-01 17-21-12](https://user-images.githubusercontent.com/12397753/83466559-503e5500-a42c-11ea-82a2-baf8a6d9db47.png)

**Comment by RoiEXLab** [comment]
👍

**Comment by trevan** [comment]
I noticed that Codacy doesn't seem to detect methods in the java classes.  See https://app.codacy.com/gh/triplea-game/triplea/file/45757689879/issues/source?bid=18410648&fileBranchId=18410648.  At the top, it has some details about the file and there is a section that "Number of Methods:" and it is 0.  I've checked other files and I've only seen 0.

Is there a setting that needs to be turned on so that it detects the number of methods?
