### ISSUE TITLE
JavaFX Status & Things to Do & Fix

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6732]
Creating an issue to discuss various issues/problems/things to do in the JavaFX headed-client. The intent is for anything that is identified here to be converted to a project card and/or just fixed.

**Comment by DanVanAtta** [comment]
Couple things off the bat:
- no scrollbars on map selection
- after selecting a map, you have to then click 'select' (seems like an extra click)
- no option to load a save game
- inconsistent terminology between 'cancel' and 'back' buttons
- inconsistent placement of 'back' button

**Comment by DanVanAtta** [comment]
- text truncation of map selection names
![Screenshot from 2020-06-21 17-35-19](https://user-images.githubusercontent.com/12397753/85238845-9c563700-b3e5-11ea-8134-b3a6230f0702.png)

**Comment by RoiEXLab** [comment]
Some context:

> no scrollbars on map selection

The scrollbar is actually just invisible, I wasn't able to put it where I wanted so I just made it that way (I believe it's all somewhere in the CSS)

> after selecting a map, you have to then click 'select' (seems like an extra click)

I was wondering how to implement a "Map Viewer", so you can read the map description. That's why a single click selects the map so you can click "preview" (idk how the button is actually called) to see the game notes.

> no option to load a save game

Yeah that one is missing, it should be on the same screen like map select IMO as alternative option as descibed in #5965

> inconsistent terminology between 'cancel' and 'back' buttons

I would agree that it is inconsistent regarding the big picture, but I think from a grammatical standpoint "Cancel" sometimes sounds more reasonable.

> inconsistent placement of 'back' button

This is an actual problem. When I first started to implement some screens using JavaFX my original Plan was to "nest" screens in each other so we could re-use the outer screen layout. Because only some screens need a "Back" button the individual screens implement it on their own though which is less than ideal. This is where this rather important issue comes from

> text truncation of map selection names

Wasn't happy with this either. I think if all maps had a "real icon" (not just one in the maps yml file) the names wouldn't be that Important, people could just look at the icon and would recognize them. In this stage however I realized that a lot of names are super long and sometimes 3 lines wouldn't be enough and 4 lines would be simply taking wayy to much space

**Comment by asvitkine** [comment]
I know a lot of effort has been spent on JavaFX already, but I do wonder if it's really the right tech stack for the game going forward.

In my mind, a good goal for a new UI re-write is to have the UI be done in a web-compatible way (e.g. where it can be viewed in a browser). Obviously, there are challenges there since we use Java which doesn't run directly (anymore) in browsers.

Still, we could go for a split where the backend logic is in Java (i.e. re-using the existing game logic) and the frontend is web UI. Then, we could package the whole thing as an Electron app, for example. (Or longer-term, find a way to have the Java logic code either be hosted on a server as a backend, or compiled to WASM and running in the browser.)

Of course, to do that, we'd need to decouple the game logic code from the UI code, but that's a good thing to do regardless.

I find that going with JavaFX is a bit backwards - it's using a framework that hasn't really gotten a lot of adoption and few people are familiar with (definitely fewer than Swing) and kind of locks us in into something that will become more legacy code.

OTOH, going with an approach where the frontend use standard web technologies would be more future proof and make the game more accessible, both to users (if we can get it hosted on a site) and developers (lots more people develop for the web platform than JavaFX). Also, if we define a clear API between frontend and game logic, it will allow for easier experimentation with new UIs by developers.

Anyway, my 2c. I realize a lot of work has been done on the JavaFX port already. And it's still useful to experiment with different UIs in the meantime, but I really think it's not the right future for a re-write of the UI.

**Comment by RoiEXLab** [comment]
@asvitkine Please have a look at #6756 it should clear up a couple of things.

> is to have the UI be done in a web-compatible way

We're sort of going into this direction already, TCP sockets are being migrated to use websockets and https, serialization will eventually get replaced by json or something. Eventually we'll get to a state where we _could_ in practice re-implement the client in a webbrowser if spending enough time on it.

> Still, we could go for a split where the backend logic is in Java [...] and the frontend is web UI.

The Problem with this approach is that it doesn't offer a smooth transition. With JavaFX we _could in theory_ replace components one by one until we get to a point where all components are replaced.

> we could package the whole thing as an Electron app

That's something to consider, but the problem with all electron apps out there is that they have to ship a browser engine with it so the download size will be at least 50MB, which is way larger than what we currently have. (To be fair though, starting with Java 11 JavaFX is no longer shipped with the JDK so we have a similar "problem" there as well.)

> (Or longer-term, find a way to have the Java logic code either be hosted on a server as a backend, or compiled to WASM and running in the browser.)

Having to host servers for individual games is something we want to avoid in the future for a simple reason: It doesn't scale well, we don't have the resources to create a running process for every game people want to play. The goal is to get to a state where users are basically opening their own servers on their local hardware and we're basically just routing the network traffics to its destination (maybe we want to implement a die rolling mechanism and other stuff to prevent cheating though).
WASM sounds intruiging and is probably the most feasible thing to achieve, but it doesn't solve the underlying problem that the code is a complete mess and needs to be fixed before being able to patch in some WASM compatible interfaces.

#### My thoughts

I tend to agree on a lot of things, @DanVanAtta sums most of them up here as well: #6756

I 100% agree that the most future-proof action would be to go for a complete rewrite of the TripleA front-end for the webbrowser (not electron), the native approach with HTML, CSS and JS.
I think the browser is an excellent place for casuals to pick up the basics and get familiar with the game, but it isn't resource-heavy enough to justify a local executable. Also I think it would fit in with the way the lobby works right now.
It would solve a lot of problems we have too: For performance we could rely on the magic of browser engines and WebGL to do the heavy lifting for us, password storage/storage of sensitive data could be delegated to the browser, clients are always using the latest version by definition so no update mechanism is required. Because we're already online we could also fetch maps directly from the server (which we would be forced to because of the limitations) which solves the problem of out-of-date maps and there's probably a lot of other things I missed that we would be forced to tackle by the limitations of the platform.
Also electron is always a good thing to have as a "backup", so we could still offer an executable if people demanded it which would also allow us to port TripleA to several platforms like smartphones for example.
There are some problems with that though:
1. I have worked with web technologies in the past so there wouldn't be much of a transition for me personally, but I think @DanVanAtta and @ron-murhammer haven't really have to work with them in the past, so they need to be on the same page there and be willing to adapt, to learn a new technology stack.
2. The front-end is huge, the navigation is one thing but the in-game rendering (you can probably tell) aspects, all of the drop down menus, popups etc. are a lot of code that is all tightly coupled together, so until we get to a point where we've written a new UI that has all the necessary features we have a lot of "parallel code" for a long time that needs maintaining.
3. There are a lot of hidden implications that need to be solved first. If you open a game in a webbrowser, you want to be able to enter your username, select a map and play. My favourite example for this is https://krunker.io (which is my go-to browser game when having to wait like 10 minutes for someone to come online). However we'd have to redesign how maps are loaded first. Even though the files are hosted on GitHub, the code only knows where to get the map zip and parse everything in it. This doesn't work as easily when you have to know the direct path to every resource and no directory traversal is possible. It's mandatory that custom maps need to work regardless (for map makers to develop and share with their friends) even if they don't ever make it into the official map pool, so we are probably ending up hosting the maps ourselves.
Other example: When we want to break savegame compatibility we can do so by incrementing the major version and calling it an incompatible update. When going for a browser-only game this would imply 2 things: 1. We'd have to provide a way to play legacy versions of the game somehow. 2. We'd have to provide a way to export savegames. We could store savegames in the local cache of the browser, but when clearing the browser cache they would suddenly all be gone, so export to file would be an important feature to be able to transition savegames between browsers.

#### Ending words
I think all approaches have their pros and cons, but as @DanVanAtta already mentioned the Code isn't in a good shape yet where we could discuss those kind of things, so we have some fundamental problems to solve first.

I hope this cleared up a lot of things for you. JavaFX isn't set in stone and the future is unclear.

**Comment by tvleavitt** [comment]
With regards to the issue of save games, if we go with a browser based UI,
then I suggest eliminating the concept of a local save file entirely. Store
everything on the server (cloud saves) in a structured format (like a
database), and then update that structure at the same time as the code...
no need to worry about save game compatibility, because the structure of
all saved games gets updated simultaneously with the code.

We could probably do the same thing with maps, have them translated to a
database structure that gets updated along with the code. No old maps, no
incompatibilities, no local copies except those cached.

Obviously, a huge state transition.

Thomas Leavitt

**Comment by asvitkine** [comment]
Thanks! I missed the cursed zip discussion.

Sounds like we all agree on the next steps of decoupling GUI and game logic.
