### ISSUE TITLE
Game Usability - larger text and map zoom

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#674]
Requested:
- Be able to zoom past 100%
- Increase text Size

http://tripleadev.1671093.n2.nabble.com/Map-Zooming-Windows-10-tp7592444.html

**Comment by RoiEXLab** [comment]
@DanVanAtta looked into it... It seems, that at least Point a is a litle bit more difficult to implement, than i thought...
Got this when zooming 300%:
![Zoom Issue](https://cloud.githubusercontent.com/assets/8350879/16279076/aba75118-38b9-11e6-80c6-4c6a8f3abf86.png)
Everything past 100% is offset etc...
The MapPanel doesn't like such zoom

**Comment by Cernelius** [comment]
Quoting myself:

> Zoom is not really an answer anyway. 
> 
> The games you play that allow you to zoom in, you are not really zooming, they are just set at a zoom lower than 100% default. 
> 
> A true zoom over 100% almost always look bad, anyway; so, no point. 

Also, I would say having a good zoom-out is prerequisite before even thinking about zooming-in, since if the zoom quality is already bad for the zoom-out, it is going to be very bad for the zoom-in.

So I would suggest to think about making the zoom quality better, before even thinking about expanding the zoom above 100%. I believe it is practically a prerequisite; zooming-in is no gain if the end result is going to be too blurred.

For example, this is the TripleA zoom at 25% on WaW 2.0.1 I just released:
![zoom25 _triplea](https://cloud.githubusercontent.com/assets/19562310/16354854/a360da00-3aa4-11e6-97e2-d63ec752aefc.png)

And this would be the same thing using the GIMP zoom at 25%:
![zoom25 _gimp](https://cloud.githubusercontent.com/assets/19562310/16354858/b7b3e128-3aa4-11e6-9608-32ad043c8454.png)

No clue if it would be possible to import the GIMP zoom in TripleA...

**Comment by DanVanAtta** [comment]
Probably this should be tackled as two different projects:
1. for all the text, like in the stats table, the menu headers, the dialogs, etc..
2. another for the map itself to go beyond 100%, which will likely be a lot of work in the rendering to get zoom in/out to look good.

Moving to the backlog: https://github.com/triplea-game/triplea/wiki/Feature-Back-Log
