### ISSUE TITLE
Cannot load saved game (from and in 1.9.0.0.13066)

### ISSUE THREAD

**Issue by CNodd** [triplea-game/triplea#6781]
Hello,

I downloaded Triple-A for the first time this past weekend. I started the tutorial and am well into it (Round 29) and was having a blast. 
![Capture](https://user-images.githubusercontent.com/67348507/85479018-321ecd00-b572-11ea-8454-d530505e2d19.PNG)

Today I loaded Triple-A and a splash screen told me that a new version (2.0.X) is available. I downloaded that version and selected the option to update the 1.9.X version I installed a few days ago. 

I attempted to load my 1.9.X save game files in the new 2.0.X version and received the error that this is from an older version of the game. No problem, I re-downloaded and re-installed 1.9.X in a new folder (to be able to load both 1.9.X and 2.0.X versions) and opened it. 

Once reinstalled, I opened the 1.9.X version, saw the splash screen notifying me of the new version again, and I clicked ok to get to the main Triple-A screen. I then clicked "Open Saved Game" and selected my latest save file as I have done many times in the past few days. However, unlike previous days, the gray "Play" button at the bottom of the screen never became clickable. 

It doesn't matter what save file I attempt to load - the gray "Play" button stays grayed out and unclickable. This also happens when attempting to load autosaves and any other file that I was able to successfully open previously.

Please help! I'd like to finish this tutorial before moving on to 2.0.X and having fun with that version.

I am running Windows 10 Home, 64-bit system.

Thank you!
Chris

**Comment by DanVanAtta** [comment]
I'm sorry to say I don't think we'll be able to get this fixed. Any fixes will be on the 2.0 version, 1.9 is no longer being updated.

**Comment by Cernelius** [comment]
@CNodd You need to click on "Start Local Game".

**Comment by CNodd** [comment]
Thank you, @DanVanAtta. I get that 1.9 is no longer being updated, but does it really make sense that releasing a new version makes old 1.9X games completely unloadable? I don't know how extensive this problem is, but I imagine there would be more than a few people that would like to continue their in-progress games.

@Cernelius thank you for the suggestion, but wouldn't that just start a new tutorial (not continue my in-progress one)?

**Comment by Cernelius** [comment]
> @Cernelius thank you for the suggestion, but wouldn't that just start a new tutorial (not continue my in-progress one)?

As with many things in TripleA, the name of the button just doesn't make sense. If you click on "Start Local Game", you don't start a game, and you don't even launch anything. That button just determines that you are going to use TripleA offline.

So, don't worry and click on the "Start Local Game" button: No game will start, by doing so.

**Comment by CNodd** [comment]
@Cernelius Awesome! Thank you! As @Cernelius stated, it's just the name of the button. 

My apologies all.

**Comment by DanVanAtta** [comment]
> does it really make sense that releasing a new version makes old 1.9X games completely unloadable?

The answer to this is actually far more involved than one would expect. It's a high priority for us to address the save-game compatibility problem.

In short, the save game is done using an old technology where the in-memory contents of the code are dumped into a file. *Any* changes to the code that generates cannot be changed or else the save game cannot be loaded. Of course, over time, the code that is dumped is very convenient and has been used virtually everywhere in the code base. The net result is that very innocent and small changes that one would not expect to cause any problem, do, and they break compatibility. It's extremely restrictive to development, we constantly have to worry about breaking compatibility, we have to constantly check for it (by hand, which takes a lot of time every time we change anything), and last, because we are restricted so much by what we can change there are many changes we cannot make, or we have to make those changes in very insane ways that tends to make other problems worse.

In short, save game compatibilty is a big problem for everyone. It's actually a HUGE problem for development, let alone being a MAJOR problem for players. Hopefully by 3.0 or 4.0 we'll have tamed this problem and can make it so we can both change code and keep save-game compatibility without so much overhead. As-is, save game compatibility probably doubles all development efforts while we maintain compatibility and locks out many types of changes completely (and some change we realize break compatibility which we would have then wasted our time on and need to undo completely).

As mentioned, this is a big problem and is due to using very naive and old technology for save games chosen about 15 years ago when there were many fewer alternatives and the save-game technology being used was not yet considered or realized to be as harmful as it has proven.
