### ISSUE TITLE
Compile time is pretty slow

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#6841]
### How can the problem be recreated?
Running:
```
time ./gradlew :game-headed:run
```

Takes 40s on my machine, even when changing a single file (e.g. ImageScrollModel.java).
This makes the developer experience pretty miserable while doing iteration.

Could we have a set up where we have a blazing fast incremental build config? i.e. only build files that changed, don't run extra analyzes on them like errorprone, etc.

Disabling errorprone shaves off 5s. It's not clear to me where the other slow down is coming from. From Googling, it seems gradle should already being doing caching/incremental builds. Is it just plugins that slow it down and cause incremental builds to not work?

I would expect if I change one class, only that class needs recompiling (and anything that depends on it, IF the API changed). reading various gradle blog posts suggests that's what gradle is supposed to do, but clearly it's not happening for us. For example, I see a bunch of compile warnings from unrelated classes when doing a build.

### If playing a prerelease, which version are you using?

Game Version:

### If playing a prerelease, does this happen on the latest release?

- [ ] yes
- [ ] no

**Comment by DanVanAtta** [comment]
I want to say gradle has a profile mode that lets you see where it is spending time during execution. That could potentially be of help. I wonder if have a task that is configured to not do incrementals.

@asvitkine is the build being done in parallel? That helps quite a bit. There should be a default config to enable that for this project, perhaps that is not on (or we turned it off since parallel test at one point had issues, I can't recall where we landed on that in the end).

I noticed myself that 'validateYaml' task is slow and has no incremental configuration configuration to it. I dont' like how that task is potentially flaky as well since we can hit rate limits. Perhaps when we have map config stored server side then we will not need to worry about it, but we may want to see about 'un-chaining' YAML validation from the compile & run sequence and adding it as a build step similar to the custom verifications (and add the command to the `verify` script).

**Comment by asvitkine** [comment]
Yeah I looked at that - it seems we have the right settings -

    ```options.incremental = true``` in build.gradle
     ```org.gradle.caching=true``` in gradle.properties
     ```org.gradle.parallel=true``` in gradle.properties

So it would seem like it should be fast. But I'm not seeing it.

Here's the --scan output that seems to indicate it is the compilation that's slow (and doesn't provide any breakdown of that as far as I can tell):
https://scans.gradle.com/s/zqmgbuwjtcipy/timeline?outcomeFilter=SUCCESS,FAILED&sort=longest

**Comment by asvitkine** [comment]
It does look like incremental building is just failing.

When I run with --info, I get:
```
Full recompilation is required because unable to get source-classes mapping relationship from last compilation.
```

**Comment by asvitkine** [comment]
However, the mapping files exist:

```
$ find . -name source-classes-mapping.txt
./http-clients/build/tmp/compileTestJava/source-classes-mapping.txt
./http-server/build/tmp/compileJava/source-classes-mapping.txt
./http-server/build/tmp/compileTestJava/source-classes-mapping.txt
./swing-lib/build/tmp/compileTestJava/source-classes-mapping.txt
./game-headed-javafx/build/tmp/compileJava/source-classes-mapping.txt
./domain-data/build/tmp/compileTestJava/source-classes-mapping.txt
./test-common/build/tmp/compileJava/source-classes-mapping.txt
./test-common/build/tmp/compileTestJava/source-classes-mapping.txt
./java-extras/build/tmp/compileTestJava/source-classes-mapping.txt
./smoke-testing/build/tmp/compileJava/source-classes-mapping.txt
./game-headless/build/tmp/compileJava/source-classes-mapping.txt
./game-headed/build/tmp/compileJava/source-classes-mapping.txt
./game-core/build/tmp/compileJava/source-classes-mapping.txt
./game-core/build/tmp/compileTestJava/source-classes-mapping.txt
```

Not sure how to figure out what's wrong. I think we might have to debug gradle?

https://github.com/gradle/gradle/blob/f71651cd8bf8300268d2759004a68863081958fd/subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java#L187

**Comment by asvitkine** [comment]
I filed https://github.com/gradle/gradle/issues/13601 w/ gradle project. Let's see what they say.

**Comment by DanVanAtta** [comment]
Any upstream fixes we'll pick up. Since we're just waiting, will close -> no further actionable items remain in this issue.
