### ISSUE TITLE
Alliance button not working correctly

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#6915]
### How can the problem be recreated? (1)
Choose map like Pact of Steel 2 --> Press “start local game” --> Change Italians to “Hard AI” and press “Alliance/Axis”.
**What happens:** Italians becomes Human again.
**What should happen:** All Axis should become Hard AI

### How can the problem be recreated? (2)
Choose map Warcraft: War Heroes --> Press “start local game” --> Change player Humans to “Humans” and press “Alliance/Axis” (This works) --> Try to set player Humans back to “Hard AI” and press “Alliance/Axis”.
**What happens:** Humans become Human again.
**What should happen:** All hordes should become Hard AI

**Comment by Cernelius** [comment]
Cannot you see the tooltip explanation? To me, the explanation and the behaviour are consistent.

I assume you missed this:
https://forums.triplea-game.org/topic/1971/how-to-fix-staging-screen-alliances-button-missing-feedback

**Comment by DanVanAtta** [comment]
Thanks for the good bug report @FrostionAAA 

@Cernelius is right to point you to the forum thread.

If you want to select sides quickly, the thing to do is to set all to Hard AI and then click the alliance button of the alliance you would like to play. Hopefully the behavior is more intuitive now, it's "click to play" rather than "click to set to current"
