### ISSUE TITLE
release 2 - ai Doesn't create factories on game of thrones map. and unlimited construction doesn't work on fire and ice map

### ISSUE THREAD

**Issue by stephenvjohns** [triplea-game/triplea#6996]
### If playing a prerelease, which version are you using?

Game Version:

### If playing a prerelease, does this happen on the latest release?

- [] yes
- [] no

**Comment by asvitkine** [comment]
Did the AI used to create factories in past versions (like 1.9) - i.e. did this regress in 2.0 - or is this more of a feature request to implement logic that never existed? Asking because this would determine the right course of action (i.e. either track down which change caused it to break, or implement something new entirely).

**Comment by stephenvjohns** [comment]
The ai creates factories in 1.9 for game of thrones (I went back to 1.9)
but not 2.0

I misunderstood what unlimited constructions meant. Fired Ice needs more
unit placements not constructions and I don't know where to discuss that.

Thank you

**Comment by Cernelius** [comment]
> The ai creates factories in 1.9 for game of thrones (I went back to 1.9) but not 2.0 I misunderstood what unlimited constructions meant. Fired Ice needs more unit placements not constructions and I don't know where to discuss that.

I would rather argue it needs to have less units being purchased or otherwise obtained, as currently the piling up of units is quite ridiculous (even more so if you could always place them all with ease), especially for a FFA. But, of course, this is a personal opinion, as I'm not a fan of massive stacks (which is common to many TripleA games). Anyway, here it is the thread for that (long abandoned) map:
https://forums.triplea-game.org/topic/950/game-of-thrones-a-song-of-ice-and-fire-official-thread

**Comment by CharlieAtlas** [comment]
If memory serves, this got fixed?

**Comment by DanVanAtta** [comment]
Yes, this should be fixed. AI should be building factories again :tada:
