### ISSUE TITLE
Priority Labels

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#7136]
I'm thinking we might benefit to have some priority labels to help us know which of the error reports we want to tackle when. I'm concerned that we may spend time bickering on priority or everything becomes the same priority. I think having pretty clear-cut definitions that are somewhat objective could help. There are a few heuristics we can apply to know if we got it right. For example, if something is P2, is that a something that we should fix before any other P2, or is it about equal to everything else that is P2?

If we go this route, I'd suggest to try 3 levels of Priority as follows:
P1 - fix now
P2 - fix sooner
P3 - fix later

I'm certainly wondering if we would want more granularity for P3 and perhaps have a P4 category. There is something nice though about keeping it simple.

So P1 should be breakages or game crashes that are frequent and easy to trigger.
P2 should be somewhat broken or severe problems that are somewhat frequent.
P3 is everything else, it should be pretty clear that we want to fix any/all P2s before we fix a P3. 

Any thoughts on giving this a try?

**Comment by tvleavitt** [comment]
@DanVanAtta 

1. The de-dup mechanism means that we currently don't have information on which bugs are "frequent and easy to trigger", other than possibly slightly different manifestations.

2. My observation is that you're a small team, and relatively independently acting beyond sharing feedback via code review. Letting people tackle whatever they feel they have the capacity to seems to be working reasonably well and resulting in relatively rapid iteration. Setting priorities implies some mechanism for authoritatively prioritizing resources which I don't see present, and creates a potential for less than worthwhile meta discussions about the severity of an issue, or the merits of doing one thing or another when the practical reality is that an issue will get addressed when someone with the skill has the impulse to take it on.

3. You're all highly motivated to address the worst problems; in that vein, I think a simple bi-level mechanism to flag an issue as meriting immediate attention in the opinion of the flagger would be most beneficial: i.e., for any one issue, it's either a priority and needs to be fixed ASAP and it would be nice if someone tackled it sooner rather than later, or it isn't, and people can take it on as they wish. My sense is that you'd have very little debate about whether something is one or the other, and this would help folks wade through the morass and easily determine what urgent outstanding issues need addressing.

4. In that same vein, there are a fair number of bug reports, as you've pointed out, that really shouldn't be bug reports due to legacy exception handling, and a label that excludes them from view (but also lets them be easily found by folks wanting to focus on reducing the number of these) would be beneficial.

**Comment by DanVanAtta** [comment]
Thanks for the feedback @tvleavitt , you're confirming some of my previous thinking on the topic.

We have an 'urgent' label to indicate the burning issues, that seems to fit in with your point (3) above.

(4) is a good suggestion. The only gray are is if we need to confirm something is a problem or not. For example, we may want a label of "TBD if can be fixed", and if not, then add a "Needs logging improvement" label.
