### ISSUE TITLE
Why are the autosaves unavailable in a bot?

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#7187]
### How can the problem be recreated?
When hosting or pbem etc the autosave folders get used.  When using a bot as a client only the bot saves the autosave.

### Do you have any ideas for an expected fix?
  I am unsure of the reason that it was removed from the client side.  Could someone refresh my memory?

### If playing a prerelease, does this happen on the latest release?

- [.] yes
- [] no

### Is there anything else we should know?
  I seem to recall an old discussion about this.  Perhaps with all the repairs recently this could be added to the client side?  It would certainly help all lobby players that do not save frequently.  Here are some additional links. (But this has really been a long problem with live play.)
https://forums.triplea-game.org/topic/2126/an-alert-to-save-pop-up
https://forums.triplea-game.org/topic/2125/should-autosave-be-disabled-when-playing-as-a-lobby-client

**Comment by DanVanAtta** [comment]
I don't know when, if ever client-side saves were done. Client side save downloads the game from the host. I don't think it's a great way to do it, but that's how it was coded up. Disabling that makes sense since the game download can be slow and blocks the whole game (it appears frozen for everyone) until that is done. For a large game file, it can be significant and frequent.
