### ISSUE TITLE
Showing wrong map in downloadwindow

### ISSUE THREAD

**Issue by ZjelcoP** [triplea-game/triplea#727]
Trying out latest prerelease i encountered a small bug. 
If known disregard this message.

Version:1.9.0.0.1732
1: I download a map.
2: When asked "do you want to download more", choose yes.
3: The downloaded map is **visually** removed from the  mapslist however when browsing it appears to still be there. This causes wrong maps to be displayed when selecting one.
4: If you exit downloads and re-enter the issue is rectified. When starting a new download the issue reappears if you stay in download-window.

**Comment by DanVanAtta** [comment]
Note on the label change : release blocker means we should not release because we are doing something bad to the game. In this case the updates to the download windows are all new features, so we are releasing a new bug which we should fix. A bug is a tracking item for a bug that is out there in the wild already.

**Comment by DanVanAtta** [comment]
See PR #788 for a description of the problem, should be fixed when #788 is merged.
