### ISSUE TITLE
Maps hosted elsewhere

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea#7275]
See #7273 

This is an example of a very, very old map, circa 2011 that a current user is attempting to play. One containing a very very old "bug" that has long been fixed, but keeps on popping upo.

We do not host this map, it is available from various repositories (search in Google for "triplea" map Iwo Jima), and it is unlikely to ever be updated, but will clearly continue to be found and generate errors.

https://sites.google.com/site/uboataaa/

This suggests that it might be worth somehow identifying officially "validated" TripleA maps, and others, and issuing warnings that others may not function correctly and may not be maintained or compatible with the latest versions of TripleA.

**Comment by DanVanAtta** [comment]
In essence we'd need to have the lobby be aware of which maps are officially hosted and to essentially only track bugs against them. Even then, the names are hardly all that identifying as you can just grab an old version of an officially hosted map and it would still generate errors. Really I think we need SHA1 checksums of maps to identify them; I think this is just a design limitation overall.

**Comment by trevan** [comment]
> In essence we'd need to have the lobby be aware of which maps are officially hosted and to essentially only track bugs against them. Even then, the names are hardly all that identifying as you can just grab an old version of an officially hosted map and it would still generate errors. Really I think we need SHA1 checksums of maps to identify them; I think this is just a design limitation overall.

But what if the user never goes to the lobby?  Local games, PBEM, and PBF would have this same situation, wouldn't they?

**Comment by beelee1** [comment]
I'm not sure how'd you want to relay the info but Roger Cooper has been updating all the maps on his site:

https://axisandallies.fandom.com/wiki/Special:Search?search=iwo+jima&fulltext=Search&scope=internal&ns0=1&ns14=1#

and is active at the triplea site if someone needed to request an update. I know that's probably not quite what is wanted for the triplea engine part but it should prove helpful to the guy trying to play iwo jima.

**Comment by DanVanAtta** [comment]
@trevan  lobby is currently the thing that handles bug reports from the game. Bug reports are sent from a (any) game to lobby, then to github via the github API. It is essentially a pass-through so that known github credentials can be used and avoids users from needing a github login.

@beelee1 the problem is that it's hard to know if a map truly has a problem, if that problem is the game engine or the map, and/or if the map is just in development. Most map errors are treated as hard-errors, which are eligible to upload as a bug report, but such errors perhaps are nothing that we can or should fix. The question is whether we can distinguish what should be a map generated hard-error vs a "oh yeah, you're working out the XML and your polygon file was incorrect". Currently we can't really tell the difference between that and "the game engine crashed for no good reason on valid XML"

**Comment by Cernelius** [comment]
I might be wrong, but I remember the "Battle of Iwo Jima" map being in the repository and the official download list. I've checked it is not currently in the repository (thus neither in download list). Any chance this map might have been inadvertedly removed from the repository at some point?

**Comment by Cernelius** [comment]
Original Thread:
http://tripleadev.1671093.n2.nabble.com/Battle-of-Iwo-Jima-0-3-BETA-td5371476.html

In this post it is affirmed that the map has been "added it to the downloads list" on Aug 14, 2010:
http://tripleadev.1671093.n2.nabble.com/Battle-of-Iwo-Jima-0-3-BETA-tp5371476p5422472.html

However, in this post it is requests updating the map on Jul 08, 2011:
http://tripleadev.1671093.n2.nabble.com/Battle-of-Iwo-Jima-0-3-BETA-tp5371476p6562439.html

So, maybe, the map was in the repository in 2010 but became outdated and got removed in 2011. Still, I vaguely remember that it was in the repository after 2011.

**Comment by DanVanAtta** [comment]
It might not have made it into the GH repositories. There was one or two that did not, that one may have had an issue with it.

The larger point is that we've no way, engine-wise, whether this is an official map, an official map that is modified locally, or simply an unofficial map (or a map that is *just* started). Essentially we need checksums of the map files and those to be recorded for the official maps and then compared against the ones that threw the error. It's a tall order for us right now. Most map parsing errors we probably should just not allow for a user report (we do scan all known maps on every build and ensure they can be parsed, presumably any map parse errors is a users doing).

**Comment by Cernelius** [comment]
Ideally, the reporting automation should check, for the game in question, that the `info name` and its `version` corresponds to something currently offered in download list.

Maybe this could be done changing the
https://github.com/triplea-game/triplea/blob/master/triplea_maps.yaml
to have the full list of games' names of the map and their versions, instead of the release number.

For example, instead of this:
```
- mapName: Big World
  mapCategory: BEST
  url: https://github.com/triplea-maps/big_world/archive/master.zip
  version: 3
  description: |
    <br>WWII style map, larger version of revised.
```
You would have this:
```
- mapName: Big World
  mapCategory: BEST
  url: https://github.com/triplea-maps/big_world/archive/master.zip
  games: |
  Big World : 1942/2.5
  Big World : 1942 v3 Rules/3.8
  description: |
    <br>WWII style map, larger version of revised.
```

This may also help clarifying the download process, as this way you would not have a confusing additional version number, that it is not really a version of anything, and the download prompt may even give the information about which games have been updated, instead of just which maps. Moreover, this would avoid having download prompts in case a map receives any changes at a skin level only (for example, you change some unit images but the game files are the same), going a long way to clarify and standardize the process regarding whether or not a map's change should cause an update prompt (currently this process is practically merely left to the preference of the mapmaker, that may or may not decide to upgrade the version number when making any changes to its map).

Of course, the best would be that an automated process gets every `info name` and its `version` directly from the map in the repository, using it for prompting any update, thus assuring immediacy and perfection in the process (I guess this is not possible).

**Comment by DanVanAtta** [comment]
I appreciate the suggestion though I don't think we can solve this one.

I see two problems:
1. There is no way to know if a given map and game are actually the ones downloaded currently. This is where a checksum would have to come into play. Essentially we create a fingerprint of the map XML and only then could we know if it was official. To show the example, I can easily download a map, unzip it, modify it, and it'll look like an official. 

2. What happens when a map is updated with assets only? Just capturing that in game version only would not do it. We also then run into the issue of "what does a 3.8 mean vs a 4.0?" Do we really want to teach everyone how to follow semver and then follow it. It's a slight scaling issue as well if you want everyone to download a new version and say you do update something across all games, then you need to needless update all of the game XML versions.

3. If  single game version changes, you still have to download the full map bundle. It's complicated to track that many version numbers.

Overall, I want to start hiding more and more the fact that maps and games are different and even decouple them.

**Comment by DanVanAtta** [comment]
Unless we are looking to fingerprint maps, I think the only thing we can do is to reasonably lower the error thresholds on map errors.
