### ISSUE TITLE
AI not purchasing factories

### ISSUE THREAD

**Issue by moramoramora** [triplea-game/triplea#7353]
I believe the new 2.1.20365 engine does not build new factories anymore, at least under certain maps. Looks like affected maps are: The Rising Sun (Map v. 1.9.3), 270BC (map v. 1.7.0) and WAW. Using the 1.9 engine the AI would build plenty of factories or cities. But now they don't.

**Comment by Cernelius** [comment]
Whether or not to buy a factory should depend mainly on 3 items, on basic maps:
- The cost of the factory.
- The production value of the territory where the factory is planned to be placed.
- The relative cost-efficiency of the planned best purchase accounting only available PUs with respect to the cost-efficiency of the best purchase under the current placement limits (this should take into account that the more a unit is away from the enemy the less is valuable, especially if it is a land unit you need to transport oversea (in big maps, you may want to buy factories even if you have enough placement abilities, in order to place your units closer to where you need them)).

For example, 270BC is a game in which you want to place more factories than in any basic (WW2) games, because, while the cost of the factory is the usual 15 PUs, 270BC has unusually very high income territories (so the cost of the factory per production point is about half that of most basic maps) and the cost-efficiency of the cheapest units is unusually very high (you have 1/1 cost 2 units, that are usually better than the common 1/2 cost 3 infantries, while the 2/2 cost 4 units are unable to give support, so they are much worse than the common 2/2 cost 4 artilleries). While in most basic games playing a game never buying any factories is something that sometimes you want to do, and it is never something particularly bad, in 270BC a game with no factory being bought from either side is insane (highly sub-optimal).

**Comment by moramoramora** [comment]
I never played 270BC. I just heard about the issue. But I play WAW a lot. I don't have a clue about what and how AI thinks. What I see is its different behavior under very similar circumstances on the same map. The only difference is engine. Under 1.9 in both WAW maps AI builds factories where they are needed (to my opinion quite smartly). Under 2.0, AI NEVER buys any factories. Therefore the game is broken.

**Comment by DanVanAtta** [comment]
This is fixed in the latest prerelease
