### ISSUE TITLE
Current Master Branch Has Errors

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#741]
The current code in master doesn't run due to ~50 errors related to:
- Cannot infer type arguments for ArrayList<>
- Errors with Matches

**Comment by ron-murhammer** [comment]
This appears to be only an eclipse bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=448028

Most likely any version before 4.5 will have errors. I'm going to try downloading the latest 4.5 and see if that resolves it.

**Comment by ron-murhammer** [comment]
Created #744 to resolve 1 remaining eclipse error after upgrading to the latest version. It appears eclipse doesn't like expressions in the inner create even if the only options end up with the same type.

**Comment by DanVanAtta** [comment]
Unrelated, but a note on labelling:
Bug -> please  reserve for bugs in the tripleA code. Gradle is the authoritative build, so that it is the compiler bar we have to hit. The latest Eclipse now matches gradle, so looks like that is going to be a hard requirement. If that were not the case though, then we would work to keep eclipse functional, which could be as far as rolling back. In this case though the IDE can be rolled forward. Regardless, let's put the bug blame where it belongs.

Release Blocker   -> makes the 'bug' label not necessary. Also, let's not use it for everything we consider to be important. Technically we could have released just fine without this being fixed

**Comment by ron-murhammer** [comment]
Yeah I thought this was a bigger problem when I originally opened it. Closing now.
