### ISSUE TITLE
Drop GPG Signing?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#7426]
Having trouble with GPG signing:
```
+.travis/stages/deploy/prerelease/push-to-github-releases/setup-gpg
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
The command "$DEPLOY_PRERELEASE_STAGE/push-to-github-releases/run || $REPORT_FAIL "build installers"" exited with 1.
```
Regrettably my first instinct with these problems is to wonder if we really need GPG key signing. This is a tricky one as it's great to have, but, do we really need it??

The purpose of GPG signing is essentially if TripleA is available at a mirror you can compute the GPG value and compare it against what is published to verify that the TripleA artifact you seeing is authentic. I think the problem here though is that nobody will or has ever even done that.

If we remove it, we gain few benefits, mostly just a simpler build:
- no GPG signing step
- no GPG signed values published to releases
- no need to have secret GPG values in Travis and in document control

I think the bottom line, is it really worth fixing and having GPG signing? Is there any evidence that it has been a life-saver or ever been really used beyond "making us feel good?" I'd hate to put it in those terms, but sometimes we do have to think about what is interesting technically vs what the project really needs (simpler builds, more of our time).

**Comment by RoiEXLab** [comment]
@ssoloff I think you introduced this in the first place. Any thoughts?

**Comment by DanVanAtta** [comment]
@RoiEXLab I'm sure removing something that we invested in is not the best. Be what it may, we must stay detached and unless you and I can point to some concrete benefits here, I believe that is evidence enough. Already mentioned in detail is the theoretical benefit, so we know why we want GPG signing. It is up to us to then decide if we'll support it. Are you willing to put in time to fix the GPG signing issues we are now seeing again? At the end of the day I believe there is just a mismatch between really nice to have (best practice almost) and must-have here.

**Comment by RoiEXLab** [comment]
@DanVanAtta I think GPG is not used by 99.9% of our users, but I wanted to give @ssoloff the opportunity to share some of his thoughts about this

**Comment by DanVanAtta** [comment]
I welcome the additional perspective. I'd say it's probably more 100% of
users. We do need to deal with the build being broken on the gpg step.

**Comment by ssoloff** [comment]
Sorry, I can't think of anything new since the last time this discussion came up a year ago (#4886).

Note that generation of the checksums themselves does not require GPG; GPG is only required to sign the checksums. So if GPG is the problematic part, but you think there is value in the checksums themselves, you could just drop the signing process. As long as the unsigned checksums are delivered over HTTPS from GitHub Releases, they should be just as safe for someone to verify they have a copy that has not been tampered with.

Also, you probably should remove the **Verifying Binaries** link from https://triplea-game.org/download/.
