### ISSUE TITLE
Installer Looks Bad/Unusable with 150% window zoom

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#746]
There is a preference to avoid the all-platforms.zip version because it avoids the installer for this reason.

**Comment by DanVanAtta** [comment]
@gaborbernat  - any thoughts about things we might be able to  do?
Screenshot hopefully coming.

**Comment by DanVanAtta** [comment]
Latest. install4j might have fixed this issue, Cernel reported the problem via lobby chat, might have been referring to the old makensis installer. Regardless, this is a QA item for us to make sure the installer looks reasonable at 150% window zoom.

**Comment by Cernelius** [comment]
Using the latest 1827 prerelease on Windows 7.
I don't know if it is 150% at all or what. But I see that if you change the theme, the "all_platforms" seems unaffected, board wise, while the "windows" installer may or may not zoom in and, consequently, it becomes blurred (zoomed-in images are always blurred).

All Platforms:
<img width="960" alt="all_platforms" src="https://cloud.githubusercontent.com/assets/19562310/15526630/974452a8-2233-11e6-9c47-c5d10bd6a8cf.png">

Windows installer:
<img width="960" alt="windows_installer" src="https://cloud.githubusercontent.com/assets/19562310/15526670/eeee6386-2233-11e6-80bc-34f9abe6e5bc.png">


Also, Norton suggests you to remove TripleA, with the installer, while there are no warnings with the all platforms. Other anti-virus may react differently to installers, and give problems.
In general, adding an installer is one (unnecessary) step further that may or may not give problems; thus, the "all platform" alternative, if not the main one, should be always easy to find, readily accessible and usable by regular users, just in case. In particular, you should add the TripleA.exe back in the folder (it was there, in older versions, but as triplea.exe, since recent times).
Thus I believe the "all_platforms" should keep being the TA recommended main referring version for download, as you can still see in the http://tripleawarclub.org/
"
_Get Started!
To play some great strategy games, follow these steps!
Download TripleA from SourceForge
We recommend the "all_platforms" zip file_
"
