### ISSUE TITLE
Automated checkstyle Run on PRs

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#747]
Goal: run a checkstyle report on PRs, if the checkstyle count goes up, the build is failed.

Feasible:
-  It's possible to run check style on every java class.
- We record a count in a file. A script reads that count, compares to the new count:
  - if the new count is greater, we return a non-zero exit and fail the build, otherwise continue
- On merge, compute the new count, and record it in the checkstyle file.

```
dan@dan-desk:~/work/triplea$ java -jar checkstyle-6.18-all.jar -c google_checks.xml  $(find . -name "*java" | head -1)Starting audit...
[WARN] /home/dan/work/triplea/./test/util/triplea/mapXmlCreator/MapXmlCreatorTestBase.java:1:9: Package name 'util.triplea.mapXmlCreator' must match pattern '^[a-z]+(\.[a-z][a-z0-9]*)*$'. [PackageName]
[WARN] /home/dan/work/triplea/./test/util/triplea/mapXmlCreator/MapXmlCreatorTestBase.java:7: Wrong lexicographical order for 'junit.framework.TestCase' import. Should be before 'org.junit.Before'. [CustomImportOrder]
Audit done.
```

**Comment by RoiEXLab** [comment]
@DanVanAtta better idea: https://docs.gradle.org/current/userguide/checkstyle_plugin.html

**Comment by DanVanAtta** [comment]
At core of a checkstyle or any other tool, we need automated reporting of how the code metrics were shifted during PR. This is pretty difficult, since you are actually really interested in the delta of the last code version with what is proposed. 

We could decide to work to drive the checkstyle warnings to zero, and then fail the build if it is not zero. If there is interest in picking that up, we can open a new issue or re-open this one. Closing for this issue now,  not currently actionable.

**Comment by ssoloff** [comment]
Apologies for resurrecting a closed issue, but since I was recently looking at Checkstyle in the context of TripleA, I thought I'd suggest an alternative improvement that may address @DanVanAtta's previous comment.

The Gradle **3.4 (!)** Checkstyle plugin supports the [`maxWarnings`](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.CheckstyleExtension.html#org.gradle.api.plugins.quality.CheckstyleExtension:maxWarnings) property.  A first step would be to set this value to the current warning count on `master` for both the `checkstyleMain` and `checkstyleTest` tasks such that any global increase in Checkstyle warnings would trigger a build failure.  It's not as fine-grained a solution as proposed in the issue description, but it's a start to prevent any more (i.e. overall quantity) Checkstyle warnings from being introduced.  If a PR specifically addresses fixing Checkstyle warnings, the maximum warning counts could be updated (reduced) manually as part of that PR.

The next step would be to automate the update as part of the Travis build.  I haven't prototyped anything, but I think it would be straightforward given that the build already supports pushing back to GitHub from Travis (e.g. the `push_tags` and `push_maps_yaml` scripts).  I envision a new Travis script that would run in the `after_script` or `after_success` phase and do the following:

* Parse the Checkstyle reports to determine the new warning counts (separate values for production and test code).
* Compare the new warning counts to the current values stored in `build.gradle` (or preferably `gradle.properties`).
* If either of the new values are less than the current values, update `build.gradle`, and commit/push back to GitHub.

My proposal would be to do this in three PRs:

1. Upgrade to Gradle 3.4.
1. Define `maxWarnings` for both `checkstyleMain` and `checkstyleTest` (assuming manual updates).
1. Implement automatic updates of `maxWarnings` on Travis.

@ron-murhammer, @DanVanAtta, @RoiEXLab  Any thoughts?  Is this worthwhile?

**Comment by RoiEXLab** [comment]
@ssoloff #1580 Updates the gradle wrapper to the latest version...

**Comment by ssoloff** [comment]
@RoiEXLab :+1:

**Comment by ssoloff** [comment]
Bumping...

@ron-murhammer @DanVanAtta Do either of you have an objection to proceeding with phases 2 and 3 of my proposal discussed [above](https://github.com/triplea-game/triplea/issues/747#issuecomment-287681168)?  I don't want to introduce something that will fail the Travis build on purpose if it's going to cause heartburn. 😃

**Comment by ron-murhammer** [comment]
@ssoloff I think its a good idea so go for it! Out of curiosity what is the current warnings count?

**Comment by ssoloff** [comment]
@ron-murhammer :+1:

Current Checkstyle violation count on `master` is 9,538 (down from about 30,000 a few weeks ago).  About 50% of the remaining violations are variable naming pattern violations, predominantly due to usage of the `m_` prefix for instance fields.  Unfortunately, many of those can't be fixed without breaking serialization and having to go through version bumps.

**Comment by ssoloff** [comment]
#1618 fails the build when the total number of Checkstyle violations increase.

#1634 automatically updates the Checkstyle violation thresholds after each build if they are larger than the current violation counts.
