### ISSUE TITLE
I'm ready to upload a new map - Balanced Mod Anniversary 41

### ISSUE THREAD

**Issue by JGreenLowe** [triplea-game/triplea#7563]
I've created a TripleA version of the 1941 WW2_v3 Balanced Mod that was playtested at [https://www.axisandallies.org/forums/topic/32453/balanced-mod-anniversary-41?page=1](https://www.axisandallies.org/forums/topic/32453/balanced-mod-anniversary-41?page=1). I'm ready to upload it, and I'm trying to follow the instructions on https://docs.google.com/document/d/17YAhxbDffBCc-U2qx2Fsnszuq_tINNPD0vbpe6OREYY/edit#.

Note that there are only two relevant files that need to be part of the upload: the map file, and the objectives.properties file. However, I will probably copy all of the base files for ww2_v3_1941 because I don't know any other way of making sure that people get those two files.

**Comment by JGreenLowe** [comment]
Here are the two files, in case that is helpful.
[WW2v3-1941balmod.txt](https://github.com/triplea-game/triplea/files/5180226/WW2v3-1941balmod.txt)
[objectives.txt](https://github.com/triplea-game/triplea/files/5180227/objectives.txt)

**Comment by JGreenLowe** [comment]
Also available at; https://github.com/JGreenLowe/1941balancedmod

**Comment by beelee1** [comment]
I couldn't open the instructions you are using but here are frostions 
https://docs.google.com/document/d/1FfF7N0srp9QG0_if5D-c1d1Aa1QTttdhxgm1GBh3pI4/edit
They explain everything in detail

**Comment by JGreenLowe** [comment]
Yes, that's the file I'm using, thank you! Anyway, I uploaded the entire map folder to the 1941balancedmod repo. Up to the admins here whether they want to use that map folder (which is 99% the same as WW2_v3_1941), or just find a clever way to provide the 2 new files in my mod.

**Comment by beelee1** [comment]
right on you just have to wait for your invitation and the transfer of ownership to go through. You'll also want to do a pull request not an issue when you're ready. Think that's automatic though

**Comment by Cernelius** [comment]
Are you aware of the existence of the "https://github.com/triplea-maps/ww2v3_variants" map?

The category for the variants has been eliminated (but all items within it retained in download list as maps) some years ago, but some maps used to have game-only modifications without themselves.

In the past, persons making game-only modifications of existent maps would collect them within a variant bundle for the map if not as additional games of the same.

I don't know what mapmakers making game-only modifications are supposed to do now (after eliminating the variants section). Maybe a developer can clarify. I only know that some modifications of "Global" made in the last years have been added to the map itself (not a fan of this myself).

**Comment by JGreenLowe** [comment]
Yup! My main reason for not wanting to bundle this mod with the other variants is that it this mod has a long and complicated list of new national objectives which really need to appear in the "Objectives" tab on the right-hand side of the screen. I've modified objectives.properties accordingly to make that happen, and objectives.properties appears to rely on the name of the game as specified at the top of the XML file. So I wouldn't know how to make this mod part of an XML file that offers multiple games while still displaying the unique objectives appropriately. I also don't want to do the work of converting all of the changes into triggered effects unless I actually need to.

We'll see what the admins say -- I'm looking forward to hearing from them and I will cooperate with them to get this published! My buddies really enjoyed it during playtesting, and I think other people will too; there was a fair amount of interest on the forums while we were designing it.

**Comment by panther2** [comment]
I would prefer separate repositories / downloads for variants of the core games, too. I, too, am not happy with more and more variants having been added to "Global" in the past. At least the "core" games v1, v2... up to v6 and including the 1940-series should contain OOB and official variants only. So user created variants should go to separate repos, IMHO.

**Comment by Cernelius** [comment]
> Yup! My main reason for not wanting to bundle this mod with the other variants is that it this mod has a long and complicated list of new national objectives which really need to appear in the "Objectives" tab on the right-hand side of the screen. I've modified objectives.properties accordingly to make that happen, and objectives.properties appears to rely on the name of the game as specified at the top of the XML file. So I wouldn't know how to make this mod part of an XML file that offers multiple games while still displaying the unique objectives appropriately.

As long as you don't have the same game ("info") name as one of the game names for the map (which you probably shouldn't anyways), you just need to add your code within the "objectives" file of the map to which you are adding your game.

For example here:
https://github.com/triplea-maps/ww2v3_variants/blob/master/map/objectives.properties

You can see that the objectives information for the "World_War_II_v3_1941", "World_War_II_v3_1942", "WWIIv3_1941_Move-Buy-Move" and "WWIIv3_1941_Tech_Advance" games are all supported (the first two are games that are not present in the map, thus all the code for them is completely useless, and present merely because, some years ago, the original map skin elemets of all skin-less variants have been duplicated into the variants themselves, turning them into maps).

**Comment by JGreenLowe** [comment]
>  you just need to add your code within the "objectives" file of the map to which you are adding your game.

Yes, thank you; I've already done that! As I indicated in my original post, objectives.properties is one of the two files I've actually edited from the original WW2_v3_1941 map, and my edited version includes all of the older objectives under different file names, as you suggested.

I am going to wait to hear from one of the admins and see what they need from me in order to make the game available to the public.

**Comment by DanVanAtta** [comment]
@JGreenLowe good to see new map variants being added. 
Thank you @beelee1 , @Cernelius , @panther2 for doing an initial triage.

@JGreenLowe for next steps, I think there are 5:
1. Please delete the non-new game files in: https://github.com/JGreenLowe/1941balancedmod/tree/master/map/games  (duplicate game-files across all repositories will clash with existing games and cause troubles for the bots)
2. Please cleanup (delete) anything that is not used in the repository as safely as you can. The smaller the zip, the better it will perform in the game engine
3. Please go to the settings of your repository and 'transfer ownership' to the organization `triplea-maps`. We'll then add you back as an admin to the map repository and you'll have full permissions over the transferred map
4. We'll need to do a quick review of the map, basically that there are no content violations
5. Last, please add an entry to: https://github.com/triplea-game/triplea/blob/master/triplea_maps.yaml and submit a PR for the addition. I'd recommend getting the text ready and submitting the PR only when we are on this last step so we can merge that PR shortly after you post it.

**Comment by JGreenLowe** [comment]
@DanVanAtta Thank you!

1) Done.
2) I'm not sure there's anything to delete here -- there are many duplicate files that are the same as the files used by the original ww2_v3_1941 game, but if any of those files are unused, I don't know which ones they are.
3) I tried doing this, and got a message saying "You don't have permission to add public repositories to triplea-maps." I changed my repository to be private, and got a similar message saying "You don't have permission to add private repositories to triplea-maps." Any suggestions?
4) Sounds fine -- I think the most offensive thing I've added is that one of the national objectives is titled "MacArthur was a Donkey." If that's a problem, we can just change the name to say something like "I Shall Return." If that's not a problem, then nothing else is likely to bother anyone.
5) Proposed text for the YAML is below. Note that the image file I have suggested would be exactly the same as the original ww2v3_1941, since they use the same map.

- mapName: World War II v3 1941 Balanced Mod
  mapCategory: GOOD
  url: https://github.com/triplea-maps/1941balancedmod/archive/master.zip
  version: 1
  img: https://raw.githubusercontent.com/triplea-maps/world_war_ii_v3/master/description/TripleA_ww2v3_1941_mini.png
  description: |
    <br>A new version of World War II v3 that uses a small, steady flow of cash instead of a large initial bid to balance the game for the Allies.
    <br>The new national objectives encourage players to compete in both the Atlantic and Pacific theaters, with front lines appearing in historically plausible regions like the Solomon Islands, Eastern Ukraine, and Norway.
    <br>China is preserved as a playable country with a modest setup change and an increased ability to collect reinforcements, including artillery from the Burma Road.
    <br>Otherwise, unit types, regions, etc. have all been preserved so that players can take advantage of their previous experience with the World War II v3 map.
    <br>Initial playtesting with human opponents suggests that the map is balanced without a bid -- but the TripleA community will be the ultimate judge. Try it and see what you think!

**Comment by DanVanAtta** [comment]
Hmm, the 'transfer' button does not work?

![Screenshot from 2020-09-08 23-56-04](https://user-images.githubusercontent.com/12397753/92565040-f1f4ef80-f22e-11ea-9c88-1a9304ab7b10.png)

Hmm, interesting if it would not work. If it continues to give you trouble we can do a work-around.

For (4), no that's not a problem : )  I don't expect any -  the content check is for egregious things.

**Comment by JGreenLowe** [comment]
![image](https://user-images.githubusercontent.com/32722792/92565352-5c0d9480-f22f-11ea-87f2-267b19b6ca1d.png)
![image](https://user-images.githubusercontent.com/32722792/92565415-747daf00-f22f-11ea-86f0-c07c3d0e8be6.png)
![image](https://user-images.githubusercontent.com/32722792/92565471-89f2d900-f22f-11ea-9962-f8d45c555f7a.png)

Yeah, that's the button! But it's not working for me; I'm not sure why not.
Glad to hear re: (4). :)

**Comment by Cernelius** [comment]
So, general guidelines for adding new game-only modifications of existent maps is not making or using "variants" like maps, in the sense of up to one such map per every original map, inside which to add all such modifications for the map, but, instead, making a new skin-cloned map every time one or more such games are being added? For example, in this case, instead of adding this new game inside the "games" folders of the "world_war_ii_v3" or the "ww2v3_variants" existent maps, I'm understanding that the suggestion is making yet another skin clone of a map (substantially a second "ww2v3_variants" map) for this game only modification?

I see only 4 ways of handling game-only modifications of existent maps:

1. The new game file is added inside the "games" folder of the original map (this is what I'm seeing happening in the last years, especially with reference to the "Global" "mods").
2. A skin-less variant folder, containing only a "games" folder and no skin elements is made, and the new game file is added inside this "games" folder, but coded to refer to the original map (this is the usual way game-only modifications were handled in the past).
3. A new folder is made that is the clone of the original map except having no files inside the "games" folder, and the new game file is added inside the "games" folder of this new map, coded to refer to this map. Any more such game files (no matter if from different unrelated persons) are added within this "games" folder (so, you have two skin-identical maps, one to collect all basic games and one to collect all modifications of them).
4. A new folder is made that is the clone of the original map except having no files inside the "games" folder, and the new game file is added inside the "games" folder of this new map, coded to refer to this map (this process is repeated every time one or more such games are made, giving a potentially infinite number of skin-identical maps, each of them offering one or more game-only modifications of the same original map).

I would suggest the developers choosing a process and documenting it (if not already made). Practically some documentation telling makers what they are expected to do if they have made a game-only modification of a map (like a new map in which everything but the game (XML) files is the same as an existent map) and want to make it available to others through TripleA (just a suggestion so possibly not to go through this learning process every time, but before opening the issue).

**Comment by panther2** [comment]
> 1. The new game file is added inside the "games" folder of the original map (this is what I'm seeing happening in the last years, especially with reference to the "Global" "mods").

The process behind those additions to "Global" has never been discussed. It has simply been done, creating facts. Having writing access allows for doing so without any discussion.

Thinking about Global: There are so many user created variants out there. If every variant would be included into the "main" repo, it will be harder to distinguish different games, you will have more games in your game list than you ever wanted. 
I am for example happy that "Path To Victory" has been published in a seperate repo while "Balanced Mod" unfortunately had been included into the main repo (both created by the same user by the way).

**Comment by DanVanAtta** [comment]
@Cernelius  @panther2 , interesting/valid points about general map management. To continue that conversation and keep this issue focused on the new map, I moved your last two comments to: https://github.com/triplea-game/triplea/issues/7589

**Comment by DanVanAtta** [comment]
@JGreenLowe I forked your map repository, that created: https://github.com/triplea-maps/1941balancedmod
You should have a pending invite for admin permissions to that repository. The repository in your personal account should no longer be needed.

Items: 1, 2, and 3 are done.

**Comment by JGreenLowe** [comment]
Excellent; thank you! I've accepted your invitation; that all seems in order. You saw I posted some proposed text for the YAML above. Does the text look good? If so, I can add it to the YAML.

**Comment by DanVanAtta** [comment]
Content looks good, item (4) is done.

You might be able to remove:  maps/flags/OldFlags

I made a very slight tweak to the content in your post above via edit (removed the leading 'The' on one of the sentences). Generally looks good. Feel free to post that for PR when ready.
