### ISSUE TITLE
Download Rulebook Issues 1.9.0.0.1950

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#768]
- When you click on 'Rule Book", on the main menu, it opens up two things:
1) Okay to open URL in a web browser? http://triplea.sourceforge.net/TripleA_RuleBook.pdf
2) Okay to open URL in a web browser? http://triplea.sourceforge.net/mywiki/Guides

- Why the very important TripleA_RuleBook.pdf is still on sourceforge, while it seems everything else is on github?

I believe this should be release blocker, unless you readd back the TripleA_RuleBook.pdf inside the main installation.
Also, I want to say that I'm uncomfortable with a game not having the rulebook inside the main installation; this feels wrong and should not normally be the case, but I guess it is barely acceptable if the rulebook is easy to get.
As now, the direct link to the RuleBook is hidden under the link to http://triplea.sourceforge.net/mywiki/Guides , which in turn has a direct link to the RuleBook.
I believe that the RuleBook should either:
1) Be in the main installation
2) Be in each single map you download
3) Have an easy to get exclusive direct link to download it in 1 step (not going somewhere with links to the RuleBook and other things)

Of course, almost noone reads it ever, but this is not the point.

**Comment by DanVanAtta** [comment]
Link is out of date, needs to be updated. Rule book has been moved: https://github.com/triplea-game/assets/tree/master/rulebooks

There was a discussion on removing it from the game distro. It turns out that the  button opens a link rather than the one bundled locally. It's not very useful to have the game manual be buried in the game folder with no other way to access it. At 20MB it was a significant size.  Also it is a bit *late* to have someone only able to access the rule book after the game was already installed. So we also need to get a link up on the website to point to the rule book, and place that link near the download game button. This way folks might be able to check out the rule book while waiting for the game install. (tracking the website task in: https://github.com/triplea-game/triplea-game.github.io/issues/45)

**Comment by DanVanAtta** [comment]
Tracking the task to update links here: https://github.com/triplea-game/triplea/issues/769

Tracking In this issue, we should fix the other problems reported. For example, the double confirmation window pop-up seems bad.

**Comment by DanVanAtta** [comment]
PR #801 should address this. Effectively took option 3:

>  "Have an easy to get exclusive direct link to download it in 1 step (not going somewhere with links to the RuleBook and other things)"

To do this, the 'help' page was split from the rule book button. That avoids the double pop-up. In addition made the help/rule book links always appear near each other consistently (and not just the help, AKA "Guides", link)
