### ISSUE TITLE
Serializing a change list - Changing the way save games are done

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#7710]
I'm opening this issue to:
- walk through potential technical changes for save game serialization
- think through any problems we might have to solve
- review the design of changing save game serialization
- check if there can be help with this effort

We've long had an idea kicking around to change from java serialization for save games to something that is text based. At some point in the last few months an idea has been formed that perhaps we could serialize (to JSON) the change list of a game data. Essentially this data structure:

```
@Builder
public class SaveGameModel {
  @Nonnull private final String gameName;
  @Nonnull private final String mapName;
  @Nonnull private final List<Change> changeList;
}
```

The idea is that the game data would be treated as three entities. 
1) an immutable core of 'map data' that is derived from loading the map.
2) a list of change objects
3) a final 'game data' that is the map data with all change objects applied.

This would allow us to compute a 'game data' object. In this manner, if we store enough information to know which map, we can load that, then given a list of changes we can re-compute the 'game data' (the game state).

Storing this set of changes is actually quite easy, in GameData we only need a few modifications:

```
  // add this variable
  private final transient List<Change> gameChanges = new ArrayList<>();

  // update 'performChange' to add the change object
  /** Executes a change and notifies listeners. */
  public void performChange(final Change change) {
    gameChanges.add(change);
```

Then in `GameDataWriter` we can change the output quite readily:
```
  public static void writeToFile(
      final GameData gameData,
      final DelegateExecutionManager delegateExecutionManager,
      final File file) {

    // this is new, we convert here to a save game model object
    final var saveGameModel = SaveGameModel.builder()
        .gameName(gameData.getGameName())
        .mapName(gameData.getProperties().get(Constants.MAP_NAME, null))
        .changeList(gameData.getGameChanges())
        .build();
    
    try {
      // instead of using an object writer here, instead we convert the game model to a JSON string and write that.
      Files.writeString(file.toPath(), gson.toJson(saveGameModel));
    } catch (final IOException e) {
      log.log(Level.SEVERE, "Failed to save game to file: " + file.getAbsolutePath(), e);
    }
  }
```

Then when loading, we'd read the save game model, we could then find the right map, we'd parse that to get an initial game state, then we'd run "addChange" of game data to apply all of the saved changes and we would then be back to the latest game state.

Doing this, we run into this error on save:

> SEVERE: jdk.internal.ref.PhantomCleanable<?> declares multiple JSON fields named next
java.lang.IllegalArgumentException: jdk.internal.ref.PhantomCleanable<?> declares multiple JSON fields named next

I think what is going on is we have a circular reference. An attachment is being stored as a change object, which then has a reference to a unit, which then references a game data and JSON then tries to serialize the whole game data as part of that one change.

So I believe then to implement this we'd likely only need to make sure that Change objects can be serialized to JSON. I think if we converted the objects in the Change objects to primitives, then they would serialize well. This in turn means that anything that uses a change would need to convert back from primitives. For example instead of getting a `GamePlayer` object, the change would have the player name and the code would have to lookup the `GamePlayer` by name.

Change objects are transmittted over network, this implies that we are potentially transmitting full game data objects over network (I'm skeptical this is the case, but if so, that is quite bad). Be what it may, transmitting change objects over network seems to likely to continue being the future of network communication and when we change network to be likely websocket based instead of custom java RMI, we'll want to be able to similarly convert Change objects into JSON to send JSON strings over network.

So, the big pull of this project would be to convert Change objects to store primitives, which seemingly would at least break network compatibility. Likely we'd need to drop references to game data and/or mark them as non-serializable which may or more not impact save game compatibility. For this to be a success we likely need to do a major release for this and ignore compatibility concerns.

From a development point of view this would of course be a game-changer  :grin: 
We'd be able to drop loads of references to 'gameData' throughout the code, we would not need a 'gameData' to instantiate multitudes of objects. Cloning of game data could potentially be done very quickly, which would make battle calc, network saves, and AI all run extremely quickly (AI performance is dominated by repeated serialization of game data in battle cald). We'd have full liberty to change java objects, change up variables, and in backward compatible ways so long as the same change objects can still be applied. 

With that said, I'm curious for any thoughts and if anyone would be willing to collaborate on this. I think the 2.3 release is pretty close, my suspicion is going to a 3.0 shortly after with this as the main focus would make sense.

**Comment by trevan** [comment]
During a battle, we'll need to store which battle step is currently being run and possibly which steps still need to be run.

**Comment by DanVanAtta** [comment]
Agree @trevan . I'm thinking we may want to expand to have more 'change' objects, almost like event objects. So there would be a change object that represents when a new battle phase is entered, and a "change" object to record which dice were rolled.

**Comment by trevan** [comment]
I think we could start moving changes to using primitives without breaking save compatibility.  Adding a new attribute is compatible.  So, if a change object is storing a `Unit`, we could add a new `String` member variable to store the unit id.  Then, in the `perform` and `invert`, we would check if the `String` member is not null.  If it isn't null, then we know it is a newer change object and use that member to lookup the `Unit`.

**Comment by trevan** [comment]
I wrote up a quick example of what I'm talking about and you can see it at https://github.com/triplea-game/triplea/pull/7844/files.  I haven't tested it so I'm not sure if it actually works, yet.

**Comment by trevan** [comment]
@DanVanAtta , what do you think of my proposal to start moving change objects to primitives incrementally while keeping save compatibility?  Are you ok with me creating PRs with these changes?

**Comment by DanVanAtta** [comment]
Can you provide a second example and maybe some more details and/or an overview of the proposal in more detail? I would like to understand a bit better what you are proposing.

**Comment by trevan** [comment]
@DanVanAtta , I created another example that you can see at https://github.com/trevan/triplea/commit/366941086bdce5cd8e07ad64f1ec0645e92e566a.

Basically, the idea is to migrate all of the change objects without breaking save compatibility.  This can be done on the 2.x branch.  Once that is all done, we can then start testing out serializing them with json and passing that back and forth.  This can be done behind the "beta" flag.  Once it is finalized, we'll have to break save compatibility but the majority of the work should already have been done.

We can migrate each change object because new members don't break save compatibility.  So, we'll add a new primitive member for each of the non-primitive members.  In the `perform` method, it will check if the non-primitive member is non-null and if so, it will use that.  Otherwise, it will use the primitive member to hydrate the non-primitive value.

**Comment by DanVanAtta** [comment]
Thanks for the example @trevan , I think we're in agreement/concensus on how the change objects would need to 'change'.

I'm wondering whether it makes sense to go ahead and cut an incompatible release and begin work and make the updates 'properly'.  If we go with a 3.x, then we could avoid having to note everywhere incompatible changes. Furthermore, we could make various incompatible changes to fix various aspects of the data model and object names. For example `ObjectPropertyChange` is very generic, too generic, and it also seems like it actually deals with modifying unit properties. It's also odd that it acts on a specific unit and not a unit type.

Another question, should all, or nearly all, change objects be represented in the history and displayed in the history. I think it makes sense that most would, if not all.

Another question, how do we handle ID generation and should some map data actually be converted to change objects? For example, the units that are part of an initial placement need identifiers, how do multiple game instances establish agreement on those IDs?

**Comment by trevan** [comment]
> Thanks for the example @trevan , I think we're in agreement/concensus on how the change objects would need to 'change'.
> 
> I'm wondering whether it makes sense to go ahead and cut an incompatible release and begin work and make the updates 'properly'. If we go with a 3.x, then we could avoid having to note everywhere incompatible changes. Furthermore, we could make various incompatible changes to fix various aspects of the data model and object names.

I think making these changes in 2.x would allow better testing of the changes.  I expect that we might need to add additional change objects since it looks like whole objects are copied between the instances.  Once we get to the point where we have to break compatibility, then we can cut 3.x.

I think the `@RemoveOnNextMajorRelease` will make it really easy to find all the places to update once we cut 3.x and I don't think it is that big of an issue to continue adding the tags.

>
>For example `ObjectPropertyChange` is very generic, too generic, and it also seems like it actually deals with modifying unit properties. It's also odd that it acts on a specific unit and not a unit type.

I don't think it is possible to modify a unit type.  I can see places to modify unit attachments (using `ChangeAttachmentChange`) and units (using `ObjectPropertyChange`) but not unit types.

> 
> Another question, should all, or nearly all, change objects be represented in the history and displayed in the history. I think it makes sense that most would, if not all.

I, currently, don't really understand the relationship between change objects and the history.  I would expect that at least the `CompositeChange` objects are represented in the history.

> 
> Another question, how do we handle ID generation and should some map data actually be converted to change objects? For example, the units that are part of an initial placement need identifiers, how do multiple game instances establish agreement on those IDs?

It appears that the server sets up the map and then sends over the `AddUnits` change object.  This change object contains a `Unit` object which is copied into the `GamData` on all of the clients.  After that, when a change object that contains a `Unit`, the `GameObjectInputStream` checks if the `Unit`'s uuid is already in the client`s `GameData`.  If it is, it uses the local instance.  If it isn't, it adds the remote instance.

For `GamePlayer`, `UnitType`, `Territory`, `ProductionRule`, `IAttachment`, and `ProductionFrontier`, the `GameObjectOutputStream` replaces those objects with the name of the item and then the `GameObjectInputStream` converts them back into the object using the local `GameData`.

For other objects, it appears it just uses the data that was sent across the wire.
