### ISSUE TITLE
Error when selecting game

### ISSUE THREAD

**Issue by RogerCooper** [triplea-game/triplea#7766]
### How can the problem be recreated?

Clicking Select Map
### If playing a prerelease, which version are you using?

Game Version:
2.3.21796
### If playing a prerelease, does this happen on the latest release?

Yes
- [] yes
- [] no

### Is there anything else we should know?
Sep 25, 2020 10:40:38 PM org.triplea.game.client.HeadedGameRunner lambda$initializeClientSettingAndLogging$0
SEVERE: Unexpected error reading XML file: ParseError at [row,col]:[1,1]
Message: Premature end of file.
org.triplea.generic.xml.reader.exceptions.XmlReadException: Unexpected error reading XML file: ParseError at [row,col]:[1,1]
Message: Premature end of file.

**Comment by RogerCooper** [comment]
Going back to 20868 resolved the issue.

**Comment by DanVanAtta** [comment]
@RogerCooper Thanks for reporting this. Feel free to click on the auto-reported link to keep the bug report in one place and add commentary to that issue - I assume this one is you: https://github.com/triplea-game/triplea/issues/7762

I think what is happening is an invalid XML was placed outside of the games folder rather than removed entirely, it is now being read and the error handling is sub-par and causing a crash. This update: https://github.com/triplea-game/triplea/pull/7769, will prevent the crash and should report the file. I do wonder what the next steps ought to be as you will still see a message every time you go to select maps. Perhaps the error message should just say that the file needs to be deleted.

**Comment by DanVanAtta** [comment]
@RogerCooper please give the very latest a try and let us know how things work. The error message should be more specific and not game-crashing now. I'm wondering if you have any thoughts on how we can further as you're going to see an error message whenever selecting a game.

Perhaps a "do not show again" would be a good way to go, or maybe we should just update the error message to tell a user to delete the file. Could you also @RogerCooper please let us know which file is causing this error? I'm curious if it's actually an invalid XML or if there is something deeper happening here.

**Comment by DanVanAtta** [comment]
Likely this was due to parsing a non-game XML file. 2.6 fixes this.
