### ISSUE TITLE
null: SimpleUnitPanel - missing unit icon (won't be displayed): Wraith_hitGhosts, UnitImageFactory.ImageKey(player=PlayerId name...

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea#7800]
## User Description
Set WarCraft map to all Hard Ai and left it running. **Note:** I had to manually submit this report, see "Other" section below.

## Map
warcraft_war_heroes

## Log Message
missing unit icon (won't be displayed): Wraith_hitGhosts, UnitImageFactory.ImageKey(player=PlayerId named:Ghosts, type=UnitType{name=Wraith}, damaged=true, disabled=false)

## TripleA Version
2.3.21865

## Java Version
11.0.6

## Operating System
Windows 10

## Memory
Heap utilization statistics [MB]
Used Memory: 734
Free memory: 1244
Total memory: 1979
Max memory: 1979

## Other

I had to manually create this report, because of the following error... apparently, there's some mismatch between what the server expects, and what is actually generated by this version of the program.

![2020-09-28 08_26_19-Report Upload Failed](https://user-images.githubusercontent.com/4445057/94452996-06a91100-0165-11eb-8df1-18bfe6d93da5.png)

**Comment by tvleavitt** [comment]
@DanVanAtta I don't know if this was recently induced or not, but we may not be getting all the Error Reports we should at this point.

**Comment by DanVanAtta** [comment]
Likely that is new for 2.3, thanks for reporting, we'll look into it

**Comment by tvleavitt** [comment]
With regard to the main report, it seems like this is going to be very difficult to track down manually for map-makers... this AI game has been running for 31 rounds and has only generated this one error. It seems like the only answer to this problem is some kind of parser the proactively identifies missing unit images for the map-maker prior to submission. A task which becomes more complicated if units can be captured and converted to other nationalities, and there are otherwise nationality specific units.

**Comment by FrostionAAA** [comment]
A new update to the Warcraft map is in the works, and two of the changes are:
•	Added a missing Wraith_hit.png image, preventing an error when wraiths are killed.
•	Added a missing Abomination_hit.png image, so this unit no longer turns invisible when wounded.

I haven’t figured out why a _hit version of an image is needed when a 1 HP unit dies and turns into another unit type. It makes no sense to me, but maybe there is an explanation? Either way the Warcraft map has a lot of _hit images at the moment to prevent these errors. But I guess I missed 1 image ;-)

This is the Wraith unit code:
```
        <attachment name="unitAttachment" attachTo="Wraith" javaClass="games.strategy.triplea.attachments.UnitAttachment" type="unitType">
            <option name="defense" value="1"/>
            <option name="whenHitPointsDamagedChangesInto" value="1:false:Loot-Level-4"/>
                <option name="attackAA" value="6"/>                     <!-- Targeted Power -->
                <option name="attackAAmaxDieSides" value="10"/>
                <option name="maxAAattacks" value="1"/>
                <option name="maxRoundsAA" value="1"/>
                <option name="isAAforCombatOnly" value="true"/>
                <option name="typeAA" value="Magic"/>                   <!-- Ranged Type -->
                <option name="targetsAA" value="$AllLandUnits$:$AllAirUnits$"/>
                <option name="damageableAA" value="true"/>
                <option name="mayOverStackAA" value="true"/>
        </attachment>
```

**Comment by FrostionAAA** [comment]
Issue is related to:
https://github.com/triplea-game/triplea/issues/7170

**Comment by tvleavitt** [comment]
It took a full day, and a lot of CPU cycles, but the hardAI simulation completed with an economic victory for I forget who (the Gnomes?) without generating any further errors. I'm glad the exercise was vaguely useful for the map creator; I may repeat it the next time I see one of these errors. :) I'm thinking about doing this with another map that pushes the limits of TripleA's engine.

**Comment by FrostionAAA** [comment]
@tvleavitt Thx for your work! When this map first saw the light of day, it was loaded with errors. Now it is playable, even though the AI has some major issues.

**Comment by trevan** [comment]
> I haven’t figured out why a _hit version of an image is needed when a 1 HP unit dies and turns into another unit type. It makes no sense to me, but maybe there is an explanation? Either way the Warcraft map has a lot of _hit images at the moment to prevent these errors. But I guess I missed 1 image ;-)

The reason is that a history item is created when a unit is hit and converted into another unit.  The unit that is hit is attached to the history item.  And when the history item is attempted to be rendered (which is done automatically when the AI is playing), it will see that the unit has been hit and so it renders the hit version.

I looked at this back when I was fixing a few of the other errors that I fixed for Warcraft and I couldn't figure out a way to fix this.  The real issue is that when the history item is created, it has the non hit unit but it stores a reference and not a copy of the unit.  So when the unit is then "hit" and converted, the history now has a hit unit instead of a non-hit unit.  I've noticed similar issues where units are captured and the history shows their captured status instead of their original status.

It is definitely a bug but I'm not sure how to actually fix it in the engine.

**Comment by frigoref** [comment]
@trevan: Is this still a problem to be solved?
If so, can you describe a fast way to reproduce the issue and state clearly

1. What is the observed (unwanted) behavior?
2. What is the expected behavior and it's difference to the observed one?
3. What is you current viewpoint/knowledge about the root cause?
