### ISSUE TITLE
Bring back the ability to target infrastructures with AA

### ISSUE THREAD

**Issue by trevan** [triplea-game/triplea#7833]
**Can you please bring back the ability to target infrastructures with AA?** That is a change that I guess happened accidentaly in a previous refactor like this one.

For example, an air unit getting shot in a territory with an aaGun, no matter if the air unit is an infrastructure.

_Originally posted by @Cernelius in https://github.com/triplea-game/triplea/pull/7823#issuecomment-703037942_

**Comment by trevan** [comment]
The save game can be found at https://github.com/triplea-game/triplea/pull/7823#issuecomment-703055893

**Comment by trevan** [comment]
@Cernelius I've moved out your infrastructure vs AA comment to this separate issue.

I tracked down to when this change happened.  The PR is https://github.com/triplea-game/triplea/pull/4833/ and over a year ago.  It looks like @ron-murhammer added a new line to the new `FireAa` class that removed infrastructure units from the attackable list.  I can't find any reason in that PR for the addition of the line and the old class didn't have any such line.

I can look into bringing it back but I worry that it is a much larger issue.  If you'll notice, the battle UI doesn't show the infrastructure units.  This is a different code path that is stripping them from the UI and that code path is much older.

Before trying to figure out how to get this to work again, I'd like to know why or when should infrastructure units be targetable?  I see comments in the code about filtering out factories, air bases, etc so there are definitely some infrastructure units that should not be targetable.  How do I determine which ones are targetable and which ones aren't?

**Comment by trevan** [comment]
Also, should non-AA also be able to target infrastructure units?

I'm looking through the code, and there is a `unitTypeCanBeInBattle` method.  This is used to determine what should be shown in the Battle UI as well as what is initially targetable.  Inside of this method, it strips out infrastructure units that don't match certain characteristics.  This is the type of infrastructure units that it doesn't strip out:

* Units on attack that have an "attack" value (either specificed in the unit attachment or given by a tech ability)
* Units on defense that have a "defense" value (same as above)
* Units with a UnitSupportAttachment
* Unit has isAaForCombatOnly and either it has no maxRoundsAa or it hasn't reached the maxRoundsAa

Looking at pos2, the air_transport units don't have an "attack", a UnitSupportAttachment, or isAaForCombatOnly.  So by marking them as infrastructure, they will not be targetable.

**Comment by trevan** [comment]
I'm looking through the code, and there is a `unitTypeCanBeInBattle` method.  This is used to determine what should be shown in the Battle UI as well as what is initially targetable.  Inside of this method, it strips out infrastructure units that don't match certain characteristics.  This is the type of infrastructure units that it doesn't strip out:

* Units on attack that have an "attack" value (either specificed in the unit attachment or given by a tech ability)
* Units on defense that have a "defense" value (same as above)
* Units with a UnitSupportAttachment
* Unit has isAaForCombatOnly and either it has no maxRoundsAa or it hasn't reached the maxRoundsAa

Looking at pos2, the air_transport units don't have an "attack", a UnitSupportAttachment, or isAaForCombatOnly.  So by marking them as infrastructure, they will not be targetable.

**Comment by Cernelius** [comment]
> I'm looking through the code, and there is a `unitTypeCanBeInBattle` method. This is used to determine what should be shown in the Battle UI as well as what is initially targetable. Inside of this method, it strips out infrastructure units that don't match certain characteristics. This is the type of infrastructure units that it doesn't strip out:
> 
> * Units on attack that have an "attack" value (either specificed in the unit attachment or given by a tech ability)
> * Units on defense that have a "defense" value (same as above)
> * Units with a UnitSupportAttachment
> * Unit has isAaForCombatOnly and either it has no maxRoundsAa or it hasn't reached the maxRoundsAa
> 
> Looking at pos2, the air_transport units don't have an "attack", a UnitSupportAttachment, or isAaForCombatOnly. So by marking them as infrastructure, they will not be targetable.

It doesn't seem that this is relevant to the matter at hand. I've tested the same case as the save-game I provided, but with the "air_transport" unit having "attack" value equal to 1. They are still not targeted by AA Fire.

---

As far as the basic games go, it doesn't matter whether how it works is how it works now or how it worked.

It is a fact that, in the basic games, "infrastructures" cannot be taken as casualties under any circumstances other than being cargo on lost transports.

However, as far as AA attacks go, I'd argue that this is due to the fact that, in the basic games, all "infrastructure" happen to be land units and all AA attacks happen to target only air units.

So, I think that the fact that "infrastructure" units are not targetable by "AA" units is due to settings of the "AA", not of the "infrastructure", units.

Meaning that I believe being an "infrastructure" should not confer invulnerability to "AA" attacks (both for battle and fly-over movements). For example, I think that "transport_planes" that are air transporting units into a territory with an enemy "aa_gun" should risk AA Fire whether or not they (the "transport_planes") are infrastructures. This is actually how it used to work (in TripleA 1.9 and as far back as I can recall), so I see no reasons for the a change that causes a behaviour unespected under the basic rules and remove options for mapmakers (if you don't want an infrastructure unit to be targeted by AA Fire, you can simply not have it in the list of targets, namely the "targetsAA" option (https://github.com/triplea-maps/the_pact_of_steel/blob/d0981adc8ccc72e37de71f330bf141b6235c886f/map/games/pact_of_steel_2.xml#L1946)).

Regarding the details, **I just suggest going back exactly to how it used to work before the mentioned change** (of 1 year ago or so).

---

>Also, should non-AA also be able to target infrastructure units?

Basically, no. The reason why infrastructure units cannot be targeted by normal fire is that they are definitively removed from combat (and returned to the embattled territory) immediately before such fire.

However, since TripleA actually allows infrastructure units to have regular attack or defence, or both, values (which, under the basic rules, would be useless, as the infrastructures would be never in battle any longer upon reaching those steps), as well as being present in the battle after the first combat round (for example, for making AA Fire on multiple round of combat), also allowing to target infrastructures can be a good additional feature. However, this (as well as the ability of infrastructures to make regular fire or be present in battle after the first round of combat) would be simply an additional TripleA feature, having no roots in the basic rules sets, as far as I know.

So, I suppose having regular fire able to target infrastructure units would be a feature request (to be made in forum).

**Comment by trevan** [comment]
> > I'm looking through the code, and there is a `unitTypeCanBeInBattle` method. This is used to determine what should be shown in the Battle UI as well as what is initially targetable. Inside of this method, it strips out infrastructure units that don't match certain characteristics. This is the type of infrastructure units that it doesn't strip out:
> > 
> > * Units on attack that have an "attack" value (either specificed in the unit attachment or given by a tech ability)
> > * Units on defense that have a "defense" value (same as above)
> > * Units with a UnitSupportAttachment
> > * Unit has isAaForCombatOnly and either it has no maxRoundsAa or it hasn't reached the maxRoundsAa
> > 
> > Looking at pos2, the air_transport units don't have an "attack", a UnitSupportAttachment, or isAaForCombatOnly. So by marking them as infrastructure, they will not be targetable.
> 
> It doesn't seem that this is relevant to the matter at hand. I've tested the same case as the save-game I provided, but with the "air_transport" unit having "attack" value equal to 1. They are still not targeted by AA Fire.

I replicated the scenario of an air_transport with "isInfrastructure" and "attack" in pos2.  Running the battle, it does make a difference.  The air transport now shows up in the list of units in the battle ui.  Without "attack", it doesn't show up.  That shows that there are two different filters happening here.  One before the battle ui is shown and then before the aa fire.  A unit with just "infrastructure" is removed from the battle and is not available for anything.  But by adding "attack", the unit makes it through the first filter and then is filtered from the AA targets.

> Regarding the details, **I just suggest going back exactly to how it used to work before the mentioned change** (of 1 year ago or so).

And I have no problem with trying to make it work like it worked before.  But I don't know how it worked before.  There is no definition of "how it worked before".  I can't just revert the code changes because I don't know what the changes are and I would assume that there have been other changes that are affected by this.

So, we have to define how it worked before and see how to implement that.  Looking at the code, I don't believe AA could attack all infrastructure.  I think there is certain conditions of infrastructure that it couldn't attack.  What are those conditions?  Are they what I described previously?  Or are they different?

**Comment by Cernelius** [comment]
In theory, regarding the basic games, there are 2 types of infrastructures: the "factory" and the "aaGun". The first is just never part of any kind of battles, while the second is not part of any battle after the opening fire is over (and also cannot make regular fire or any fire after the first round of combat, but TripleA allows it, which is a good additional feature).

The term "infrastructure" itself doesn't make sense, because it is fairly descriptive of a "factory", but an "aaGun" is certainly not an infrastructure.
https://dictionary.cambridge.org/dictionary/english/infrastructure

So, I suspect that the option was initially taylored for the "factory" unit, then expanded to serve the "aaGun" too. Or maybe just nobody came up with a well descriptive label for it.

Ideally, instead of having a single "infrastructure" boolean option, you would have two of them, one for the "factory" like infrastructures and another one for the "aaGun" like infrastructures.

Instead, TripleA has only 1 option and infers whether or not an "infrastructure" is a combat (aaGun like) or non-combat (factory like) infrastructure by a number of things (that you have listed).

However, since the AA Fire has a "targetsAA" option, my suggestion is for them to target whatever unit that they have in their target list (being an infrastructure, or not, being completely irrelevant in any case). I don't think there is any need to try to distinguish them, since mapmakers can just make sure not to list what should be not targeted. So, yeah, I'd let an AA Fire able unit able to target whatever it is listed in its targets. I believe this is actually how it used to work. As I said, both for battles and fly-overs.

**Comment by trevan** [comment]
> However, since the AA Fire has a "targetsAA" option, my suggestion is for them to target whatever unit that they have in their target list (being an infrastructure, or not, being completely irrelevant in any case). I don't think there is any need to try to distinguish them, since mapmakers can just make sure not to list what should be not targeted. So, yeah, I'd let an AA Fire able unit able to target whatever it is listed in its targets. I believe this is actually how it used to work. As I said, both for battles and fly-overs.

Can you do some tests in 1.9 and find out exactly what types of infrastructure units were available as targets for AA?  What fields made the unit "invisible" to AA?  Are there combination of fields?  That type of information would be extremely helpful in figuring out how to bring back the old functionality.

**Comment by Cernelius** [comment]
> > However, since the AA Fire has a "targetsAA" option, my suggestion is for them to target whatever unit that they have in their target list (being an infrastructure, or not, being completely irrelevant in any case). I don't think there is any need to try to distinguish them, since mapmakers can just make sure not to list what should be not targeted. So, yeah, I'd let an AA Fire able unit able to target whatever it is listed in its targets. I believe this is actually how it used to work. As I said, both for battles and fly-overs.
> 
> Can you do some tests in 1.9 and find out exactly what types of infrastructure units were available as targets for AA? What fields made the unit "invisible" to AA? Are there combination of fields? That type of information would be extremely helpful in figuring out how to bring back the old functionality.

I tested it extensively in the past and I'm almost sure it was all of them. I believe I could send a completely useless infrastructure unit and have it subjected to AA Fire, but I'll get a savegame.

**Comment by Cernelius** [comment]
>Running the battle, it does make a difference. The air transport now shows up in the list of units in the battle ui. Without "attack", it doesn't show up. That shows that there are two different filters happening here. One before the battle ui is shown and then before the aa fire. A unit with just "infrastructure" is removed from the battle and is not available for anything.

Actually, not true. If you test Feudal Japan, sending one or more "Horse" units to attack toghether with one or more other units, you will see that the "Horse" units are not removed from the battle in offence, since they can retrat (if they would be removed, they would be unable to retreat).

**Comment by trevan** [comment]
I just did a pos2 test where I made the aaGuns able to fire all rounds.  I modified the air_transport to just have infrastructure.  The aaGuns could only hit the air_transport the first round.  They couldn't hit the air_transport any more rounds even though they could hit other airplanes.

**Comment by trevan** [comment]
> > Running the battle, it does make a difference. The air transport now shows up in the list of units in the battle ui. Without "attack", it doesn't show up. That shows that there are two different filters happening here. One before the battle ui is shown and then before the aa fire. A unit with just "infrastructure" is removed from the battle and is not available for anything.
> 
> Actually, not true. If you test Feudal Japan, sending one or more "Horse" units to attack toghether with one or more other units, you will see that the "Horse" units are not removed from the battle in offence, since they can retrat (if they would be removed, they would be unable to retreat).

How is what I said not true?  I described what the battle ui was showing and what was attackable.  The "horse" units would be another point to understanding the behavior.  They don't change the behavior that I described.

**Comment by Cernelius** [comment]
> I just did a pos2 test where I made the aaGuns able to fire all rounds. I modified the air_transport to just have infrastructure. The aaGuns could only hit the air_transport the first round. They couldn't hit the air_transport any more rounds even though they could hit other airplanes.

Ok. That is consistent with the basic rules (infrastructure can never be in battle past combat round 1), but since TripleA allows them to fire for multiple rounds, then I would expand them also being possible AA targets for any round. However, this would be a feature request (as you tested, it is not how it worked and it is not a possibility in the basic rules sets).

So, yeah, the suggestion is bringing back the past behaviour, but, in my opinion, expanding it to allow for targeting also past round 1 would be better.

**Comment by trevan** [comment]
> > I just did a pos2 test where I made the aaGuns able to fire all rounds. I modified the air_transport to just have infrastructure. The aaGuns could only hit the air_transport the first round. They couldn't hit the air_transport any more rounds even though they could hit other airplanes.
> 
> Ok. That is consistent with the basic rules (infrastructure can never be in battle past combat round 1), but since TripleA allows them to fire for multiple rounds, then I would expand them also being possible AA targets for any round. However, this would be a feature request (as you tested, it is not how it worked and it is not a possibility in the basic rules sets).
> 
> So, yeah, the suggestion is bringing back the past behaviour, but, in my opinion, expanding it to allow for targeting also past round 1 would be better.

Ok, then I need to know what the past behavior was.  You said that that all infrastructure was allowed to be targeted by AA units.  I just showed that the past behavior doesn't actually allow that.  If you can list out exactly what allowed infrastructure to be targeted and what prevented it to be targeted, I can see about changing the functionality.  But you can't just say "bring back the past behavior" or "all infrastructure is targetable".  I need specific details.

**Comment by Cernelius** [comment]
> > > Running the battle, it does make a difference. The air transport now shows up in the list of units in the battle ui. Without "attack", it doesn't show up. That shows that there are two different filters happening here. One before the battle ui is shown and then before the aa fire. A unit with just "infrastructure" is removed from the battle and is not available for anything.
> > 
> > 
> > Actually, not true. If you test Feudal Japan, sending one or more "Horse" units to attack toghether with one or more other units, you will see that the "Horse" units are not removed from the battle in offence, since they can retrat (if they would be removed, they would be unable to retreat).
> 
> How is what I said not true? I described what the battle ui was showing and what was attackable. The "horse" units would be another point to understanding the behavior. They don't change the behavior that I described.

It is not true because you said "**a unit with just "infrastructure" is removed from the battle**". If a unit is removed from the battle, it would be unable to retreat. The "Horse" of Feudal Japan doesn't have what you listed. This is the unit attachment:
```
    <attachment name="unitAttachment" attachTo="Horse" javaClass="games.strategy.triplea.attachments.UnitAttachment" type="unitType">
      <option name="movement" value="2"/>
      <option name="isLandTransport" value="true"/>
      <option name="transportCost" value="3"/>
      <option name="isInfrastructure" value="true"/>
    </attachment>
```

**Comment by trevan** [comment]
> > > > Running the battle, it does make a difference. The air transport now shows up in the list of units in the battle ui. Without "attack", it doesn't show up. That shows that there are two different filters happening here. One before the battle ui is shown and then before the aa fire. A unit with just "infrastructure" is removed from the battle and is not available for anything.
> > > 
> > > 
> > > Actually, not true. If you test Feudal Japan, sending one or more "Horse" units to attack toghether with one or more other units, you will see that the "Horse" units are not removed from the battle in offence, since they can retrat (if they would be removed, they would be unable to retreat).
> > 
> > 
> > How is what I said not true? I described what the battle ui was showing and what was attackable. The "horse" units would be another point to understanding the behavior. They don't change the behavior that I described.
> 
> It is not true because you said "**a unit with just "infrastructure" is removed from the battle**". If a unit is removed from the battle, it would be unable to retreat. The "Horse" of Feudal Japan doesn't have what you listed. This is the unit attachment:
> 
> ```
>     <attachment name="unitAttachment" attachTo="Horse" javaClass="games.strategy.triplea.attachments.UnitAttachment" type="unitType">
>       <option name="movement" value="2"/>
>       <option name="isLandTransport" value="true"/>
>       <option name="transportCost" value="3"/>
>       <option name="isInfrastructure" value="true"/>
>     </attachment>
> ```

retreating is a completely different thing from firing at it.  I believe 1.9 retreats submerged subs as well.  I was talking about removing from the target list.  But it doesn't matter.  I just need you to give me specifics on what makes an infrastructure targetable and what prevents it from being targeted.

**Comment by Cernelius** [comment]
> > > I just did a pos2 test where I made the aaGuns able to fire all rounds. I modified the air_transport to just have infrastructure. The aaGuns could only hit the air_transport the first round. They couldn't hit the air_transport any more rounds even though they could hit other airplanes.
> > 
> > 
> > Ok. That is consistent with the basic rules (infrastructure can never be in battle past combat round 1), but since TripleA allows them to fire for multiple rounds, then I would expand them also being possible AA targets for any round. However, this would be a feature request (as you tested, it is not how it worked and it is not a possibility in the basic rules sets).
> > So, yeah, the suggestion is bringing back the past behaviour, but, in my opinion, expanding it to allow for targeting also past round 1 would be better.
> 
> Ok, then I need to know what the past behavior was. You said that that all infrastructure was allowed to be targeted by AA units. I just showed that the past behavior doesn't actually allow that. If you can list out exactly what allowed infrastructure to be targeted and what prevented it to be targeted, I can see about changing the functionality. But you can't just say "bring back the past behavior" or "all infrastructure is targetable". I need specific details.

I believe the past behaviour was that all units listed in the "targetsAA" option were targetable on the first round of combat, regardless being infrastructure or not. As you tested, infrastructures were never targetable after the first round of combat. I think it would be better having them targetable on whatever combat round the AA Fire can be on ("maxRoundsAA") (it shouldn't happen, according to basic rules, but it is consistent the most with the fact that TripleA allows infrastructures to fire for multiple rounds), but this is merely a personal preference.

>I just need you to give me specifics on what makes an infrastructure targetable and what prevents it from being targeted.

I already suggested you to make them all targetable. In theory, "aaGun" like ones would be and "factory" ones would not be, but, since TripleA has only one infrastructure option for both, it is not possible to distinguish them. It really doesn't matter, since you can fill the target list for the AA however you want. If you really want to, you can sort them out under the same criteria as the ones that define the `unitTypeCanBeInBattle`, but I think it's better just having them all possible targets.

**Comment by trevan** [comment]
You say you want the behavior that existed previously but then you say what you believe is the behavior or what you want the behavior to be.  So, do you want the original behavior or something else?  You haven't told me what the original behavior is.

**Comment by Cernelius** [comment]
> You say you want the behavior that existed previously but then you say what you believe is the behavior or what you want the behavior to be. So, do you want the original behavior or something else?

I've a hard time understanding what you are missing.

As not being a developer, I cannot know certainly what the past behaviour exactly was. I can only know what I test and experience.

What I know (but I may missing limitations I'm not aware of) is that, at least for the first round of combat, AA fire could target any unit regardless of them being infrastructure. This is what I believe should be the behaviour (the infrastructure option not excluding the unit from AA fire at least for the first round of combat).

Additionally, what I said:

>I think it would be better having them targetable on whatever combat round the AA Fire can be on ("maxRoundsAA") (it shouldn't happen, according to basic rules, but it is consistent the most with the fact that TripleA allows infrastructures to fire for multiple rounds), but this is merely a personal preference.

>In theory, "aaGun" like ones would be and "factory" ones would not be, but, since TripleA has only one infrastructure option for both, it is not possible to distinguish them. It really doesn't matter, since you can fill the target list for the AA however you want. If you really want to, you can sort them out under the same criteria as the ones that define the unitTypeCanBeInBattle, but I think it's better just having them all possible targets.

---

>You haven't told me what the original behavior is.

Did you read this?:

>I believe the past behaviour was that all units listed in the "targetsAA" option were targetable on the first round of combat, regardless being infrastructure or not. As you tested, infrastructures were never targetable after the first round of combat.

I'm not aware there were additional items to it (but maybe there were). If you can find them out, that's good, otherwise I think this is good enough, if correct. I don't recall knowing anything more about it, nor that anything more can be inferred from the basic rules set.

**Comment by trevan** [comment]
> > You say you want the behavior that existed previously but then you say what you believe is the behavior or what you want the behavior to be. So, do you want the original behavior or something else?
> 
> I've a hard time understanding what you are missing.
> 
> As not being a developer, I cannot know certainly what the past behaviour exactly was. I can only know what I test and experience.
> 
> I'm not aware there were additional items to it (but maybe there were). If you can find them out, that's good, otherwise I think this is good enough, if correct. I don't recall knowing anything more about it, nor that anything more can be inferred from the basic rules set.

That's what you need to do.  Test out various setups of infrastructure and aa units.  Try and figure out what are the rules around infrastructure targeting.  You don't have to be a developer to figure that out.  You said you wanted the original behavior.  So you need to figure out what the original behavior is, document it, and then put it here so that I can build towards that.

Or, if you really don't want the original behavior and are fine with differences, then I can look at targeting infrastructure units that match the `unitTypeCanBeInBattle` filter.

**Comment by Cernelius** [comment]
>You said you wanted the original behavior. So you need to figure out what the original behavior is, document it, and then put it here so that I can build towards that.

I simply assumed that you would be able to get that behaviour from the code, so that would be the easiest for you (or any developer). If this is not the case, I would rather just tell what I believe the behaviour should better be, regardless of what it was.

**Comment by trevan** [comment]
> > You said you wanted the original behavior. So you need to figure out what the original behavior is, document it, and then put it here so that I can build towards that.
> 
> I simply assumed that you would be able to get that behaviour from the code, so that would be the easiest for you (or any developer). If this is not the case, I would rather just tell what I believe the behaviour should better be, regardless of what it was.

It isn't.  I'm currently trying to figure out small piece of code in another part of the code base and even with the code open in front of me, I'm basically trying different inputs to see what the outputs are.  And with battles, the code is scattered across a lot of files and is very disconnected.

**Comment by Cernelius** [comment]
Anyway, I made additional tests and it seems I can confirm what I said. The 1.9.0.0.13066 behaviour was:
>All units listed in the "targetsAA" option were targetable on the first round of combat only (regardless of being infrastructures or not). Infrastructures were never targetable after the first round of combat.

Is this enough? Are we now finished with the part of (hopefully) fully documenting the past behaviour? I'm just asking to be sure now we can leave this part behind us.

**Comment by Cernelius** [comment]
The "targetsAA" value being the list of all air units in the game if not specified, of course.

**Comment by trevan** [comment]
> Anyway, I made additional tests and it seems I can confirm what I said. The 1.9.0.0.13066 behaviour was:
> 
> > All units listed in the "targetsAA" option were targetable on the first round of combat only (regardless of being infrastructures or not). Infrastructures were never targetable after the first round of combat.
> 
> Is this enough? Are we now finished with the part of (hopefully) fully documenting the past behaviour? I'm just asking to be sure now we can leave this part behind us.

I just did a test with an air_transport that is infrastructure and has attack of 1.  AA guns could target it after the first round.

I'm just trying to figure out what you want the behavior to be.

**Comment by Cernelius** [comment]
Ok, so, based on what you say and on further testing, it seems that the past behaviour actually was:

- All units listed in the "targetsAA" option were targetable on the first round of combat (regardless of being infrastructures or not and regardless of anything else).

- Infrastructures were targetable by AA Fire after the first round of combat only as long as they satisfied at least one of the conditions to be recognized as `unitTypeCanBeInBattle` (this was not required for the first round of combat, instead).

I think this should be **everything.** Do you concur?

**Comment by trevan** [comment]
> Ok, so, based on what you say and on further testing, it seems that the past behaviour actually was:
> 
>     * All units listed in the "targetsAA" option were targetable on the first round of combat (regardless of being infrastructures or not and regardless of anything else).
> 
>     * Infrastructures were targetable by AA Fire after the first round of combat only as long as they satisfied at least one of the conditions to be recognized as `unitTypeCanBeInBattle` (this was not required for the first round of combat, instead).
> 
> 
> I think this should be **everything.** Do you concur?

I can't think of anything else but, then, I haven't really been looking into it.

**Comment by Cernelius** [comment]
Ok, so I think it would be good to bring back the old behaviour. However, I think this would be the best behaviour I can think of (meaning that I would suggest this over bringing back the old behaviour):

- **All units listed in the "targetsAA" option are targetable on every round of combat equal or lower than "maxRoundsAA"** (no matter if they are infrastructures nor if they meet any `unitTypeCanBeInBattle` conditions: if the unit is listed in the "targetsAA", it is always eligible).

I assume this would require adding to `unitTypeCanBeInBattle` the (sufficient) condition of being listed in the "targetsAA" option of one or more opposite units having isAaForCombatOnly and not having reached the maxRoundsAa (or having it equal to infinite).

**Comment by trevan** [comment]
Sounds good.

**Comment by Cernelius** [comment]
Once this issue is sorted, I intend to see if I can do something to clarify the matter within "pos2" (I'll need a developer to review and possibly merge that).

**Comment by trevan** [comment]
I've created a PR to fix this.

**Comment by Cernelius** [comment]
@trevan Release note for regular users and map-makers? Maybe:

Removed from "infrastructure" units the ability to be immune to targeted (AA-like) fire and made infrastructure targetable also beyond the first round of combat (in accordance to the fact that TripleA allows infrastructures to remain in combat beyond the first round of it).

---

I don't know (I haven't tested) if infrastructure units have been still targetable by fly-over AA fire. In case, you may want to clarify here we are talking only about AA fire in battle, not AA fly-overs.
