### ISSUE TITLE
Units placed in the India territory not recognised. 

### ISSUE THREAD

**Issue by marky1918** [triplea-game/triplea#7990]
When playing the 'Triple A - World War II Global Balanced Mod 3 with Combat Move First' map against AI, after units are placed in the India territory (to existing factory as British player), they are unusable in future rounds. Territory appears empty when running cursor over.

**Comment by marky1918** [comment]
New UK Pacific (with Union flag graphic) units placed in the India territory at the end of the turn are not converting into regular UK units (with British roundel graphic). Results in all new units placed in the India territory being unusable un future rounds.

**Comment by beelee1** [comment]
@marky1918 what triplea version are you using ? I seem to remember something like this a while back but it got fixed.

**Comment by panther2** [comment]
@marky1918 Can you please provide a savegame where the issue occurs?

**Comment by marky1918** [comment]
Hi, many thanks for the help chaps. I’m at the combat move stage for the British (human player is set for all allied countries - including UK_Pacific_UK). The newly placed units in India have not updated to the British ‘RAF roundel’ graphic and are not being recognised.

I’m not the most tech savvy so apologies if the attached save game isn’t accessible. I’ve saved file locally on my Mac - please advise if there’s an alternate way of sharing the save game and I’ll do my best.

Marky1918.

**Comment by beelee1** [comment]
@marky1918 yea put your save in a zip file then attach it

**Comment by marky1918** [comment]
Hi, please the attached zip file

**Comment by beelee1** [comment]
@marky1918 yea I'm still not seeing it. Just in case you're unfamiliar with the process, If you can't auto compress to a zip or are having trouble getting one, open triplea and then open your "downloadedMaps" folder. Pick any zip, copy, empty and rename to the saved game. Then put the save in there.

Click on the bottom of where you're posting, Attach files ... etc... and you can navigate to where your zip is or shrink your screen and drag it into the post.

**Comment by marky1918** [comment]
[India_error_30.10.20_marky1918.tsvg.zip](https://github.com/triplea-game/triplea/files/5469431/India_error_30.10.20_marky1918.tsvg.zip)

**Comment by trevan** [comment]
@marky1918 , thanks for the save.  It is after the place turn which is when the logic to change ownership happens but it does show that the owner hasn't changed.  I noticed that the save was for 'Triple A - World War II Global Balanced Mod 3' and not 'Triple A - World War II Global Balanced Mod 3 with Combat Move First' so I ran that map all the way to UK_Pacific place turn and watched what happened.  I was able to duplicate what you are saying.  I also tried on 'World War II Global 1940 2nd Edition' and it had the same problem.  I think all of the 'World War II Global' maps are affected.

It looks like this is caused by the fact that the `giveUnitControl` option for `PlayerAttachment` is now being skipped in @DanVanAtta legacy map updater (#7631).  I think this is because in #1033, @Cernelius said to skip that option if it is a boolean value but it shouldn't be skipped if it isn't a boolean value.

**Comment by Cernelius** [comment]
> It looks like this is caused by the fact that the `giveUnitControl` option for `PlayerAttachment` is now being skipped in @DanVanAtta legacy map updater (#7631). I think this is because in #1033, @Cernelius said to skip that option if it is a boolean value but it shouldn't be skipped if it isn't a boolean value.

I wouldn't say that is because of what I said. Especially in the moment I believe I've been the only user against it (just my personal preference of not supporting deprecated items any mapmaker can easily update).
