### ISSUE TITLE
Notes Comments Bug 1.9.0.0.2042

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#822]
Notes may bug off for the commented out sections, in TripleA 1.9.0.0.2042.

You can see that in "World At War" 2.0, I've released here:
http://tripleadev.1671093.n2.nabble.com/WORLD-AT-WAR-tp5862407p7592327.html

If this is a conscious decision to not supporting comments inside the Notes section anymore, that's a bad idea, but at least you should communicate it to mapmakers.

**Comment by RoiEXLab** [comment]
Hmm thats weird... It's not intended at all...

**Comment by ron-murhammer** [comment]
@RoiEXLab We are renaming a vast majority of the territories in WaW 2.0 and the list of updates is here: https://docs.google.com/spreadsheets/d/155CXax8k9FXX4hDV5rU31F7haUtLEjwfQwdZRUwdUgs

**Comment by RoiEXLab** [comment]
So I looked into it, and it seems that this is only a problem with the In-game NotesPanel itself... When viewing the notes in the game Chooser Menu everything looks just like it's supposed to do.
I debugged it using Breakpoints and edited the "False" NotesPanel to contain the Same Text as the right one...
Same result.
It seems like the NotesPanel is not being configured right...
BTW, I noticed, that due to the way the GameChooserPanel gets his html appended with a StringBuilder, the result is very bad html (e.g. double html tags etc.) Maybe someone could fix this
[Output](https://gist.github.com/RoiEXLab/3ae1b7b7055548ce1cc20c058abc0384)

**Comment by RoiEXLab** [comment]
#827 has a fix

**Comment by RoiEXLab** [comment]
It's working for me...
In theory this should also work for others... 
Can anyone confirm?

**Comment by RoiEXLab** [comment]
@DanVanAtta @ron-murhammer @frigoref anyone?

**Comment by DanVanAtta** [comment]
Yup, looks fixed
