### ISSUE TITLE
RFC: Maps Upload Design

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#8223]
Relatively simple maps upload design diagram, creating an issue for discussion before adding to the design docs @ https://github.com/triplea-game/triplea/blob/master/docs/development/design/maps-server.md

![map-upload-design](https://user-images.githubusercontent.com/12397753/99899439-3c96dd00-2c5e-11eb-976d-9f194256cc15.png)

**Comment by RoiEXLab** [comment]
I'm a bit late to the party I guess, but the design sounds good in general, I have some questions though:
### The public ID
Will there only ever be a single version of a map stored, or will the servers keep track of revisions?
If the server kept out-of-date versions of the map this would mean that "outdated" client versions could still get their appropriate version of the map if the latest uses features that are not available yet. Obviously the underlying problem is more complicated than that, but I just want to know if this ID is just an auto-generated token (maybe a simple UUID, or just some random hex number) or if it's a user-chosen (or developer-chosen) identifier that gets updated with the latest map revision.

### Storage  with nginx
I'm a bit curious how you are planning this one. Using nginx for static assets is a good if not the best choice IMO but I'm not quite sure how you are planning to combine it with dropwizard.
I would assume that you plan to create a folder that contains all the assets on the file system and just let nginx serve those files for all request with a certain URL prefix (something like `GET /assets/<public-id>/map.zip` where `/assets` is the prefix), and act as a reverse proxy for all other HTTP requests for dropwizard which does the actual management of the files. Is this assumption correct?

### Redundancy and integrity
From my understanding the client (TripleA) does not need to know anything about storage servers, it just talks with the map server and follows its orders, right?
So in theory there can be multiple storage servers connected to a single map server.
The authentication method using a shared secret that is passed with a bearer token you suggested (or which I assume you suggested at least) sounds simple enough, but I wonder how feasible this system would be to deploy. If one system gets compromised we'd have to change this key on every system. An asymmetric system where only the single map server has the private key and we hand out the public keys to all storage servers could avoid this risk, even if it's slightly harder to implement.
It would also allow for "independent" storage hosts, if the map server stores hash sums to verify integrity after downloading. Not sure if this is desirable, but I wanted to mention it nevertheless.

I also wonder if we want redundancy for map downloads. It sounds overkill, but let's say we have a single map server and a single storage server with all maps and now we create a new storage server because the current one is barely able to keep up with traffic. From your description this new server would only receive maps whenever a new one is uploaded (which is then distributed to both storage servers), but should the map server automatically push all non-existent maps to the newly created storage server so both servers will end up equivalent? That would be pretty sweet for load balancing if you ask me. It would also keep the system running if one of the storage servers crashes for some reason.


### General auth
Some final thoughts that aren't directly related to the design: How did you plan upload authentication with the map server?
I assume it will either use forum login credentials or lobby credentials, but AFAIK we currently don't have a way to prove your identity outside of the spitfire server software. So what are your thoughts there?

**Comment by DanVanAtta** [comment]
I perhaps should have closed this issue, the forum post that discussed this got pretty far ahead and we will continue storing maps in github. The questions raised are interesting and FWIW can give some quick responses:

> The public ID

This is something I would still like to have. Essentially any map downloaded will come with a unique, stable, public ID. When we are looking for missing maps, instead of doing name matching, we only need to check if a map with a given public ID is installed. With a well known URI to download maps by public id, this allows for any map to be readily downloaded. If the XML data is incompatible, that is another issue (though, as a long running premise, we will never break backward compatibility for XMLs, only forward compatibility; meaning any XML tag that has ever been created, as has been long-running tradition (recall the old-version jars), we will forever support reading those tags). 

> Storage with nginx

What you have described is about right @RoiEXLab . Nginx can have a folder where resources are served, dropwizard only needs to write files to that location and then provide 302 links to the client to fetch resources from that location.

> Redundancy and integrity

Access to maps would be public, as it essentially is today. For communication between map and storage server, yes, there would be a single secret value (an API key) deployed to the map server and potentially to the storage servers to, and they would check that requests between the server have the right token. It would have been option to use a public & private key scheme as well.

Having redundancy of some sort for the map files would have been imperative. Either through hard disk backups, some sort of commit and push to a git repository, or simply multiple servers.

> General Auth

>  AFAIK we currently don't have a way to prove your identity outside of the spitfire server software

We have a login endpoint that returns an API-key. We'd only need to create another endpoint to accept an API-key and tell us whether it is valid or not. A user would then do the login against spitfire and then forward that API key to the maps server which would in turn check with spitfire if the key were valid.

**Comment by DanVanAtta** [comment]
With keeping maps in repositories, we will still have a maps server, though it will be responsible for tracking which repositories we have and will only replace the `triplea_maps.yaml` file. We will do this by adding a 'map.yml' file that has the same information as the `triplea_maps.yaml`, but is now distributed to each map repository. The maps server will periodically poll the github repositories for a `map.yml` file and when found would upsert into database. Then requests to download maps will be a DB query rather than a file fetch.
