### ISSUE TITLE
Changes to Engine Preferences Window

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#834]
![__preferences_dialog](https://cloud.githubusercontent.com/assets/12397753/15988042/dafce89a-2ff6-11e6-8697-3f98626845e9.png)

### Cleanup: Removal
- Enable/Disable Delayed Parsing
Full parsing can be obtained by default by simply selecting a map. Thus it's not a terribly useful tool to have.

- Set Default Casualty Selection Method
I don't think anyone knows about the "slow" method, nor why they would want it. Any improvements we do would be best focused on single code path, rather than splitting effort between two.

- Set Max Host Wait Time For Clients And Observers
I don't think it anyone changes these values, or really knows what they mean, myself included.. We should use some reasonable defaults.

- Set Max Memory Usage

Looking at the code that runs this, we check for XMX at launch, and then if it is 20% more than what we are currently running, only then do we relaunch the game. Given the very scary text about changing this value, it does not seem like it will ever be reasonably used in a useful way. 

![__set_max_memory](https://cloud.githubusercontent.com/assets/12397753/15988127/5b8b2f10-2ff9-11e6-978c-0654ee629fa6.png)

- Open User Maps and Savegames folder

Not very useful. Seems like  a legacy debug tool

- Open Intalled Program Folder

Again, seems like a legacy debug tool

- Open REadme / User Manual

We have a link to this on the main screen already. 

### Cleanup: Moving

- Show Console
Move to main screen

## Further changes

With the above cleanups, we are left with a good bit less code, and less extraneous settings. 
Today, each button opens a new dialog that is typically a yes/no/cancel for whether to apply one setting or another.  That presents a problem, we need to be able pack in a lot more settings.

Thus I suggest we switch to a tabbed panel layout. Then from there each tab would typically present a grid of selection options. Once we have the current ones migrated we will migrate the various options from the menu, to the one settings window.

This will then give us a framework for adding more user defined options, there are plenty of hard code values that should be given options (like key settings for example, scroll speed, etc..)

**Comment by DanVanAtta** [comment]
I would also like to put the Proxy options on the chopping block. Going through the code, I just noticed this:

>  "(This only effects Play-By-Forum games, dice servers, and map downloads.)""

**Comment by Cernelius** [comment]
I really hate where this is heading to and the easy assumptions of triviality made on many things that have been added overtime and have a big history behind them that should be known before making assumptions.
If you want to remove something, I suggest doing some research on what is behind each thing (you need to read or check fully all the Topics of the entire sourceforge forum, since the info and discussions are dispersed, and probably that would be not even enough, since Veqryn used to keep things private to some extent), instead of just guessing.
If you don't want to do this, you can take my word that all those things have some serious history behind them (some added to solve very serious and widespread issues) and are all useful, some of them very useful, and you should leave them alone.
In general, a behavioural approach I suggest is that if there is something you don't understand, but it is there because it has been developed by someone else in the past, you should assume it has some uses you are missing (otherwise, why would anyone have developed it?), instead of easily assuming it has no good uses, just because you don't see them immediately.

I believe the most useful feature of them all is the "Open User Maps and Savegames folder", but I personally love the most the "Set Max Host Wait Time For Clients And Observers", for several reasons.

The only thing I'm favourable is to remove the "Open REadme / User Manual", because it is on main screen.

I'm strongly against removing anything else listed, with the only exception of "Set Default Casualty Selection Method", that I would be just interested to actually know exactly what it does, because I don't believe it is explained anywhere, and I (and noone else but Redrum and Veqryn only, I guess) don't even know what it does, so I can't have an opinion on it.
The best reference for that should be Redrum, who worked a lot on that method with Veqryn.
Since supports are very extensive, I would suggest keeping a "Perfect" method, just in case; but some explanations to the users or even anyone about what the "Slow" method does that the other one don't I would say it is really needed here, seriously. Otherwise LaFayette is right saying what's even the point of this option if you don't even explain it and nobody knows what it does?!
If noone explains it clearly, I suggest to keep it, because having a "Perfect" method sounds useful to future mapmaking, if not current; but I'm just guessing with no clues, on this one only.

Regarding the "cleanup", aside from the general easy disregarding of the work made of these codes by the previous developers, that here are just assumed having coded random superfluous things for not good reasons, seems to me that the only thing that may have any serious impact is "Set Default Casualty Selection Method" and maybe "Set Max Memory Usage", which is very useful (even tho I personally don't use it, but just open "system.ini" with notepad and edit it), as about all things that you are thinking to remove.

In any case, I've no clue on the coding demands that supporting the above things puts on the developers, but since they are all so useful, I suggest to remove any of them only if it appears to be really hardly bearable.

More in detail on the "Default" vs "Perfect but Slow" method, I suppose the code should be changed so to use always the "Perfect but Slow" method upon giving casualty selection (for a single iteration, the delay is really irrelevant) and being selectable directly in the battlecalculator, where, instead, the default should be "Default".
There is absolutely no reason to use anything else but the "Perfect but Slow" outside of the Battlecalculator, since the delay is relevant only and exclusively for the Battlecalculator, not for any other applications of casualties selections.

Generally, if you want to remove any of the above things, you need to open **1 discussion for each of them**, but you can just take my word that they are useful and forget about removing them, without losing time in some long and tiresome discussions about all the reasons why you should not remove them, especially since **everything here has been already at length reasoned upon in the past** (only exceptions, as said, is the "Open REadme / User Manual", that you can remove, and the "Set Default Casualty Selection Method", that I don't know, but just guess it may be useful, since Veqryn and Redrum spent so much on developing it).

Thumb down from me: bad ideas all the way.

You are just going to bring back a lot of major problems that have been already at length addressed in the past, with the above options or other related changes; I suggest you just trust that what is there is there because there are some serious reasons for it to be there, instead of having to rethink from start once again so much that has been already discussed, defined and fixed.

And definitively is nonsensical that so many different things are all put into 1 single discussion; so I think this is going my last contribution to this discussion, as I believe it is going to be dispersive and pointless, and most things have been already discussed so much in the past in sourceforge; so just go read those discussions already is my advice, instead of starting it all up from zero yet again.

On the other hand **1 single discussion for each 1 of the above options only** on how to expand, clarify and improve them might be a good idea, but I think all those options are very good as they are, already (cept need explanations on the Perfect method).

**Comment by DanVanAtta** [comment]
@Cernelius  #835 , not responding to the rant here.

###  "Open User Maps and Savegames folder",

The plan is to have a UI element to be able to specify these locations. I had not considered it, but a button to open up the corresponding folder could be useful.


## XMX Memory

The warning text on this makes this option un-usable to the average user. Given how it is coded, it also does not work quite as expected.  This setting likely should instead control the value in system.ini.  The system.ini file on the other hand I do not think works for all platforms, we should verify the relationship between the system prop and the config in system.ini


## Set Max Host Wait Time For Clients And Observers

There is no guidance as to what good values are for the UI, or what these control.  Which values do you  use @Cernelius? Chances are really good that 95%+ of players do not even know this exists, let alone what it does. We need to come up with ways to make this feature more useful. It is hard to see why there would be much variation in these values, I would like to understand why it is so useful to change the defaults, and if the defaults are ever useful.

## Set Default Casualty Selection Method

Only Veqryn contributed to that code. The code that supports the feature is extremely costly. Note, cost does not always correlate with effort. We can discuss this one more, but since nobody knows or what it does, it already does not seem to be providing much value.

## Proxy Settings

Since this only impacts PBEM posting, and dice roller, I am curious if there is anyone who needs this feature. It would seem that if a proxy were needed for PBEM or dice rollers, than direct network and lobby games would also be broken too.


## Run Map Creator + Console

Moving these to a different menu

**Comment by DanVanAtta** [comment]
@Cernelius - it's simple enough to talk about each one in its own right. See above for links to related issues. Nothing further left in this one that has not been sliced out into it's own issue.
