### ISSUE TITLE
XMX Memory Game Engine Setting

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#836]
The warning text on this makes this option un-usable to the average user. Given how it is coded, it also does not work quite as expected. This setting likely should instead control the value in system.ini. The system.ini file on the other hand I do not think works for all platforms, we should verify the relationship between the system prop and the config in system.ini

![__set_max_memory](https://cloud.githubusercontent.com/assets/12397753/15988127/5b8b2f10-2ff9-11e6-978c-0654ee629fa6.png)

**Comment by RoiEXLab** [comment]
Isn't system.ini a windows only thing?

**Comment by Cernelius** [comment]
First of all, **the ability to set the Xmx at whatever value you wish is a very important feature that should be surely kept.**

The way the text is worded is funny. I would much suggest to add the info that (if you mess with this!) you can safely reset everything by just reinstalling TripleA, anyway; because, as it is now, it reads like you are definitively fucked. I guess whatever normal user opening this would just close it immediately after reading the bold, never to open it again.

Moreover, the "Test" procedure is not actually even safe, because overtime the Xmx level at which TripleA doesn't start may lower, or you may test it with a value so close to your max that it works the time you tested it, but, then, you can't start TripleA anymore, or sometimes.

The way this works can be surely improved, and I just surely ask to upkeep the current ability to set the Xmx at whatever level you want (this is actually possible, because, while that option is capped at 3072, you can set it at whatever, by editing the system.ini).

Myself, I keep it at:

> triplea.memory.useDefault=false
> triplea.memory.Xmx=4096
> triplea.memory.onlineOnly=false

My current user case is playtesting maps with big xml.

I suggest something like this be still possible.

There are several discussions related to this in sourceforge, mostly but not only related to the benefits of increasing it for playing big maps with Hard AI.

The main, but not only use, of a lot of RAM assigned is for playing big maps or maps with big xml with Hard AI. Since there are no limits to xml dimensions, there can be no limits to the max RAM needed.

Also, I believe the current default value (most people are likely to stick with) is too low and significantly detrimental to Hard AI, with reference to playing big maps or maps with big xml with Hard AI, which appears to be a popular choice.

I believe the best would be leaving the users able to set the Xmx at whatever level they wish to, and TripleA automatically lowering it as much as needed to be able to play the game, if they set it too high. If this gets done, I would suggest the default value being increased to 2048 (mostly with reference to Hard AI usage).

**Comment by DanVanAtta** [comment]
Opened: https://github.com/triplea-game/triplea/pull/1863, it does not remove this setting, but it does remove it from GUI. Instead `max_memory` will be specified from `game_engine.properties` as a replacement. Note: `system.ini` is now empty and will be removed with 'xmx' moved to  `game_engine.properties`.

Thanks for the feedback @Cernelius . This feature is being kept, but being moved. For context on the move:
- the current memory option location is a bit buried. Moving this to a property file with the game engine is also buried. In both cases it is the power users that would know/use this feature.
- not obvious, there are some good code simplifications to this move and removing the UI support. 

One note, when you upgrade game engine, users will have to update the property file to re-apply their setting. In the old system the updated memory settings were stored with the OS, that would no longer be the case now (which is actually kind of good, bad values getting stored in system can cause interesting bugs).

Since we'll be keeping the feature for now, it answers the question in this issue - closing.
