### ISSUE TITLE
Max Wait Time Engine Settings

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#837]
Some problems to be solved:
- poor documentation on what the setting does
- no guidance for when and which values should be used

(#834 has screenshot and background context)

**Comment by DanVanAtta** [comment]
Will be solved by moving to new settings menu that has a text area for a more detailed description.

**Comment by Cernelius** [comment]
This is a nice (and almost needed) feature and I definitively suggest not forcing people to being unable to start games, if they are fine at waiting. Meaning you should still allow either having no timeout or setting it at a level so high it is like there is not (like 1 hour).

Having a not editable timeout caused many problems in the past, some of which are documented in sourceforge.

In any case, I suggest the default being kept at current levels. There are not really good reasons to force people to stop their games, if they are fine waiting, since anyway they can close them themselves.

So, I believe it would be fine as well to remove this feature and always allowing waiting forever.

On the other hand, I think the usefulness of the "Max seconds to wait for an observer joining a running game" option is self-explanatory.

The time needed to start games is highly variable amongst users; so setting a fixed timeout would be a bad idea, as it has surely been in the past (this is the story behind having this option).
