### ISSUE TITLE
isAI condition

### ISSUE THREAD

**Issue by RogerCooper** [triplea-game/triplea#8420]
A condition that would show as true if the player is an AI.

For discussion of the details see [https://forums.triplea-game.org/topic/2490/directing-the-ai-with-events](url)

**Comment by Cernelius** [comment]
@RogerCooper I believe the forum is not only for discussing feature requests, but entirely for them.

Since the link you gave would make this issue at best a duplicate, I would close this issue, but, since I'm still seeing feature requests being kept open and labelled as such (the latest case being https://github.com/triplea-game/triplea/issues/8397), I guess I'll let a main developer do it or not.

**Comment by DanVanAtta** [comment]
How and whether to distinguish feature requests, where to track them, where to discuss them, and where to mark them as done are all a bit in the air. Ron was managing that entire process, now that he is no longer, it's an open question. If meriting further discussion, we should certainly discuss it as either a forum post or as a github issue.

**Comment by TheDog-GH** [comment]
Completed
https://github.com/triplea-game/triplea/pull/11979
