### ISSUE TITLE
Battle calc and other improvements

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#859]
Quoting Cernel in from #846 
1.  I've always told Veqryn that the default for dice calculations should be 1,000 (stead 2,000) and the maximum (for both dice and LL) should be 100,000 (stead 20,000), but he always rebuked, so I'm telling you now.
2. I still believe the AI Pause Duration default should be 250 ms.
3. I think the "Odds Calculator" or "Battle Calculator" should be renamed to "Battle Simulator", because, while it does calculations, starting from the raw data obtained from the simulations, its main point is simulating battles, not calculating the outcomes directly.
4. I think it should be possible to set the percentage approssimation (default at 1% is fine, but could be 0.1%) (like having "Attacker Wins: %92.170", by setting it at 3 decimals, instead of "Attacker Wins: %92"); like an option for having decimals, from 0 to 6, with default at 0 or 1.
5. I think the meta-power is dumb and I would remove it and anything related or change it to a decent formula.

**Comment by RuinChristmas** [comment]
My annoyance with the battle calculator is how it deals with multi-national forces.

Let's say you have Germans attacking UK/Russians.  All is fine.  But now you switch sides because you want to see what happens if the Russians or British attack.
1. The attacking power is shown for the total units even though they can't attack together.  Should only show the nationality selected in the dropdown menu.
2. If that nationality in the dropdown menu is British, for example, but I want to see what happens if the Russian troops attack, so I change it to Russian.  All the units disappear from the attacking side!  Why would I want this?  

Apologies if this exact issue was fixed in the betas; I can't run revised bc of Java errors I guess bc I still have 1.8.0.9 on my computer.

**Comment by DanVanAtta** [comment]
Not fixed, this is certainly something that has annoyed me as well. I also think it's interested that you can have a silent bug where if all the attacker units are UK, but the nation selected is Russian, then it automatically excludes those units. Sometimes it can make you think you have 100% odds when you do not.
