### ISSUE TITLE
Map extraction problems (Folder Chaos)

### ISSUE THREAD

**Issue by RogerCooper** [triplea-game/triplea#8679]
The latest version of TripleA(22583) converted the zip files into folders in the downloadedmap folder. Many zip files were not converted and were simply destroyed, not even in the recycle bin. (I have backups). For example, my file AA50-41-Maintenance.zip [link](https://drive.google.com/file/d/1sk85nOG38oDKGElgpxlvYj0bIDGBxr7d/view?usp=sharing) was destroyed.

I understand the advantages to using unzipped folders, but there is no reason that the actual zip files should have deleted. Even worse, the deleted files were sometimes not unzipped before deletion.

I suggest a rollback until this issue is resolved.
[AA50-41-Maintenance.zip](https://github.com/triplea-game/triplea/files/5860377/AA50-41-Maintenance.zip)

**Comment by DanVanAtta** [comment]
Were they moved to a 'bad-zip' folder @RogerCooper ?

**Comment by DanVanAtta** [comment]
The map posted, 'AA50-41-Maintenance.zip', @RogerCooper is not well structured. The first folder in the zip should be a single folder typically matching the map name (EG: AA50-41-Maintenance). The next folder should be called 'map', then under that there would be map files.

What is the background on this map zip file?

**Comment by DanVanAtta** [comment]
@RogerCooper more information and example zips would be really helpful.

**Comment by RogerCooper** [comment]
There is no folder called bad-zip. There is nothing wrong with the file I posted either, I was still using the older file structure which was working fine until the new release. Are double folders now required?

**Comment by RogerCooper** [comment]
I converted AA50-41-Maintenance.zip to the double folder format. It comes up now, with 2 entries in the scenario list for some reason, both of which work. Where are the zip files going? Programs should not delete files from user's computers without permission.

I think it would be better if zip files remained. If the zip file had a more recent date than the folder, the user should be given the option of updating. Consider the problem created if 2 different maps had the same file name. Would the program as it is now, overwrite the existing data without warning and then delete the zip file?

**Comment by DanVanAtta** [comment]
A problem with zip files remaining is the engine will have trouble knowing whether to re-extract it again. That implies the engine would have to examine every zip file every time you select a game.

**Comment by DanVanAtta** [comment]
Extracted zips could perhaps go into an extracted-zips folder so that the engine would know to not look at them. The excessive disk space usage is a concern as the zip files are really not needed post-extraction.

The primary use case overall is for map-downloads done as zips then extracted (so the user never sees the exact files on file system nor do they need to care). It's only a handful of users that manually install maps. The engine has no way to know about manually vs downloaded maps. The mass extraction is really to upgrade existing systems.  Perhaps if it were just made clear to those manually installing that they should keep a copy of the zip files manually then that would be all that we would need.

**Comment by DanVanAtta** [comment]
I think the problem here is that there are too many zip formats and this gets back to whether the map folder should be zipped or the folder contents. AFAIK the engine prefers for it to be the map folder that is zipped but it's been hacked to work with either. This is probably solved by having the engine create a folder and then extracting into that. That would create excessive folder hierarchies, eg: `downloadedMaps/wwii-revised/wwii-revised-master/maps/...`

**Comment by RogerCooper** [comment]
> A problem with zip files remaining is the engine will have trouble knowing whether to re-extract it again. That implies the engine would have to examine every zip file every time you select a game.

It was examining every zip file before and extracting the map name field. I had every triplea mod known installed and it only took 30 seconds. Comparing dates should be much faster.

**Comment by DanVanAtta** [comment]
It can't necessarily just compare dates as the extracted folder name could be different. Though, if we change it to create a "standard-named" folder, then perhaps it could. At the same time, I'm not sure if the extra disk usage is that ideal. We are at a point of doubling map requirements. 

If the extract had been 'correct', would deleting the zip files have been that significant of an issue? Would it have been an issue had you had a heads up to back up the zip files (if you wanted them)?

**Comment by DanVanAtta** [comment]
Comparing dates is not something I really want to have. We'll be generating map.yml files as well which would bump the date timestamp of zips, which could make things look more recent. That is also getting in the way of standard operation to support custom installation. If you a person is manually installing, then deleting the corresponding folder or just letting it be overridden is a simpler way to get the update. Maybe it comes down to it, if you manually install, a person should simply copy instead of 'moving' the zips. With that said, as a migration aid, the engine could/should prompt a user to back up zips before they are extracted. From another perspective, we're moving to a place where no user ever needs to deal with zips (unless you are manually packaging and distributing them, which is not necessarily encouraged but can't be stopped).

**Comment by RogerCooper** [comment]
The wiping out of all the existing zip files without warning created a problem. The user should certainly be prompted and the program should never wipe out the zip file without even creating a folder.

Scenario developers still need to work with zip files, in order to upload them when finished or to make them available to others when testing. There will always be some need for manual installations.

I notice that the selection screen seems it bit slower now, when I would expect it to be faster.

**Comment by DanVanAtta** [comment]
>  The user should certainly be prompted and the program should never wipe out the zip file without even creating a folder.

Agree, though that was because of inconsistent packaging of maps where the contents of the map were expanded directly into the downloadedMaps folder. This meant that various files were then duplicated and overwritten, overall not useful. Had that been fixed though, would it matter?

> I notice that the selection screen seems it bit slower now, when I would expect it to be faster.

This is a different issue and the selection cache was removed. The mechanism for loading available games will change shortly.

**Comment by DanVanAtta** [comment]
> Scenario developers still need to work with zip files, in order to upload them when finished or to make them available to others when testing. 

If uploading to github repositories, that work is not necessary. If manually distributing maps, then yes. A lot of investment has been made to make upload easy, manual distribution is not encouraged.

**Comment by Cernelius** [comment]
> The wiping out of all the existing zip files without warning created a problem. The user should certainly be prompted and the program should never wipe out the zip file without even creating a folder.
> 
> Scenario developers still need to work with zip files, in order to upload them when finished or to make them available to others when testing. There will always be some need for manual installations.
> 
> I notice that the selection screen seems it bit slower now, when I would expect it to be faster.

I completely and strongly agree with all of this. I also wonder if having the ability of deleting files automatically may cause anti-virus and such to see TripleA as a dangerous program?

**Comment by RogerCooper** [comment]
I have been restoring the deleted files without problems.

**Comment by DanVanAtta** [comment]
@Cernelius what exactly are you disagreeing with? What problems do you foresee?

No, deleting files is not going to cause problems with AV. TripleA already deletes and moves various files.

---------------

The main problem that has arisen is the unexpected (but supported) file format of map zip files. Specifically zip files that have no top-level folder in them. Only some 3rd party map zips that have no official support other than legacy are in this format.

At an immediate level, if the engine were to extract maps into a new folder that should solve the bad unzipping problem that occurred. Notably, if there is a top level folder in the zip then there will be redundant folders until we get to a maps 'content root'. If there is no top level folder, then the content root will be the newly created folder. Taking a map names "ww2.zip" as an example, there would be roughly three possible paths to the maps content root after:
- ww2/<content-root>
- ww2/map/<content-root>
- ww2/ww2/map/<content-root>

There is an open question of how to support manual installations. If it's well known that the engine will remove zip files it extracts successfully, or moves zips into a 'bad-zips' folder where it cannot extract, then perhaps it's simply a matter of informing those doing a manual installation that they should keep a copy of the original zip if they want to retain it.

If we were to *not* delete zip files, it inovkes a few problems:
- at least doubles disk space usage for maps
- the engine will be confused about which zips have already been extracted and which have not. Because the contents of a zip are not fully deterministic, this is a problem. If a user manually extracts a zip file, then there is no guarantee that the folder names would be the same
- the extra zips will not be useful, meanwhile the engine will have trouble knowing whether a downloaded zip still needs extraction or is dead-space
- zips can be overwritten, which might not be what a person would want anyways
- processing delays anytime a game file is selected to check zips have been extracted
- overall complexity, it is a good bit more to deal with and there is no current design of how to handle various failure modes. The reason to going to flat folders only was to simplify. I can't emphasize enough how tangled the code is and how that inhibits most meaningful development progress and has for years, to the point that we can't get a development team to stay because nobody can do anything useful (it's all tedious and brittle cleanup work, and years worth of it. The code base might already be effectively dead and the stubborn few of us still working on it are just not admitting that we'll never in our lifetime make meaningful progress).

With respect to manual installs:
- there are relatively few users who do this
- it is discouraged, the desired way to share maps at any point of the map development development is to use the 'experimental' download category and use repositories

The con list of leaving zips is pretty long. If a solution to the drawbacks of removing dead map zips is simply to update expectations for those doing a manual install (the zip file is being manually installed after all, it is easy to keep a copy), then have we solved the problems of dead zip removal?

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/pull/8712 fixes the problem of zips having their contents naively extracted into 'downloadedMaps'. This should fix how the map extraction was done.

It seems there is an impasse (and a lack of suggestions) on the discussion of whether map zips should be removed after extraction. We could move those zip files into an 'extracted-folder', but I'm still not sure if that is wise. The trade-off is handling the common case where users download maps and generally never touch the file system vs the comparatively low fraction of users that do manual map installation. The latter case is arguably the only time one wants to keep original zips (even then, I'm not sure what for), and that could perhaps be solved via user expectation to 'copy' instead 'moving' manual zip installations into the downloaded-maps folder.

**Comment by RogerCooper** [comment]
How about creating a manual-downloads folder. Any zips that TripleA can't resolve could be moved there and the user notified. Users would be responsible for extracting the manual downloads themselves.

My problem was the erasure of files without warning.

**Comment by DanVanAtta** [comment]
If a zip file appears to be extracted already, it will remain untouched (it's an odd state, unexpected, so the engine will favor doing nothing over doing something harmful).

If there are any errors during extraction, the zip will be moved to a 'bad-zip' folder.

Otherwise, if the unzip appears to be successful, only then will the zip be removed. The problem we had was that the contents were directly extracted and given the different layouts of zip's, that resulted in unexpected results with the contents smeared into the 'downloadedMaps' folder (and likely mostly overwrote previous extractions).

FWIW, I'm really happy you reported this problem @RogerCooper , this was a map format I was not expecting and only vaguely recollected, I don't think it would have been tested and we potentially would have released with the same logic in place (which is something of a small disaster for anyone like yourself with "non-standard" maps installed).

**Comment by Cernelius** [comment]
I've not installed 2.6 so far because I'm scared of this. Can I be assured that the program will do nothing at all to everything that is non-zipped? Meaning I'm absolutely safe for anything which is not zipped? I there any risk that, by unzipping somethnig, something else which is already non-zipped might be overwritten by the unzipped content?

**Comment by DanVanAtta** [comment]
The unzip process creates unique folder for each unzipped map, regardless of the original contents of the zip. All extracted contents will go into that folder. If you are scared of this issue simply create a deep copy of 'downloadedMaps', name it something like 'downloadedMaps.bak', and then it will be easy to restore if you are not pleased with the results. Any issues that you observe will be very interesting to know. Without this error report, problems from the unexpected zip formats probably would have made it to release.
