### ISSUE TITLE
Player Default Assignation Does Not Work When Hosting (2.5.22294)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#8808]
The default assignation of players as defined by the `defaultType` in the game file doesn't work when hosting.

Moreover, automated hosts don't support any assigniation but "Human".

In particular, the "270BC Wars" game has the "barbarians" player assigned as default to "DoesNothing". This works when you are playing local but doesn't work in any hosts.

In a way, this is worse than not working at all, since you are used to it working on local, so you easily forget to set it when hosting.

---

I believe @ron-murhammer made this feature but never finished it (unless it was supposed not to work but in local). Reference:
https://forums.triplea-game.org/topic/132/handling-of-ai-players-not-meant-to-be-played-github-request/24?lang=it&page=2

**Comment by DanVanAtta** [comment]
The hosting case could be fixed. Bots not allowing AI player types is by design.

The loading screens between single and multiplayer are completely different code bases (lots of copy/paste between the two). Either some surgery is needed to get the two code paths to be more similar, or this will be fixed when the loading screen is re-written and is no longer two sets of independent code-paths.

**Comment by asvitkine** [comment]
@Cernelius Is this still a problem with 2.6?

**Comment by Cernelius** [comment]
I've tested it with "270BC Wars", and I have not had the issue.
