### ISSUE TITLE
Battle Failure Sound Goes To Everyone (2.5.22294)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#8815]
The sound which is given when a battle is lost (`battle_failure`) is given to everyone. Why am I hearing a battle failure sound if I won the battle as the defender? I suppose only the player making the battle and maybe all other players of the same side should hear the sound. I suppose every defending player or players and every player on the same side should rather hear a victory sound, instead.

**Comment by zlefin** [comment]
Has there been a public discussion about whether to change this?

Regardless of whether or not its 'sensible', it's the sound people are used to hearing for a very long time now.  It has a clear, precise meaning, even if it's not the one a new user might expect.

What sound would observers hear?
Not that it would really matter due to rarity, but what sound should someone hear if they're playing nations on both sides?
What do players in FFA maps hear?

I think the next step should be a public feedback posting to hear about the community opinions on the desired behavior.

From a code perspective; there is a simplicity to "everyone hears the same sounds".  If a change is made here, then there might be a lot of other sounds that should change; and possibly some visuals as well.

**Comment by Cernelius** [comment]
> Has there been a public discussion about whether to change this?

Not at all.

> Regardless of whether or not its 'sensible', it's the sound people are used to hearing for a very long time now. It has a clear, precise meaning, even if it's not the one a new user might expect.

I don't think sounds are that meaningful.

> What sound would observers hear?

If you win as the defender, you would ear a victory sound, in theory. On the sea, there is the "battle_sea_successful" sound. On the land, a "battle_land_successful" sound would need to be added. I suppose both sides losing all units can be considered a defensive victory.

> Not that it would really matter due to rarity, but what sound should someone hear if they're playing nations on both sides?

I would give priority to the turn power (the offender). Giving no sound may be reasonable too (as the player is both winning and losing at the same time): not a strong opinion.

> What do players in FFA maps hear?

I think players not having powers part of the battle should ear nothing. It's not a victory nor a defeat for them. By the way, I don't think that allies should ear anything, either, unless involved.

> I think the next step should be a public feedback posting to hear about the community opinions on the desired behavior.

I think that the concept that, if you win defensively, you should ear a victory sound is obvious enough.

> From a code perspective; there is a simplicity to "everyone hears the same sounds". If a change is made here, then there might be a lot of other sounds that should change; and possibly some visuals as well.

As I said, it is needed to have a "battle_land_successful" sound. Currently, I believe none exists, and I surmise none exists because usually, when you win a land battle as the offender, you take the territory, so you get that sound instead. However, having a "battle_land_successful" sound is already necessary in case no conquests are made (for example, in a FFA, if you attack another player in a territory which is owned by a third player you are not at war with).

---

Currently, since there is no "battle_land_successful" sound, you would simply ear nothing when normally winning as the defender on land unless it counts as a air-only battle (so, as now, this issue equals removing the battle failure sound for the defender when the offender fails on a non-air-only land battle). This is another related issue that exists in any case you win land battles without taking over any territories (you can test it by attacking and eliminating all enemy units in a friendly territory).

**Comment by DanVanAtta** [comment]
@Cernelius, to confirm, are you saying there is no "battle success" battle sound capability?

Otherwise generally, I was thinking this was a very interesting to have open and initially I took it for a bug. After following the discussion it seems like the same sound played to everyone is the more consistent. The same "battle failure" sound always means the same thing, that the attacker did not win, whomever that is. Another case to consider, if playing "hot seat" and there is a human playing each side, does the game play both success and failure sounds? Another case as well, if observing an AI game, having a consistent sound would help follow the game and the battle. Notably, the auditory cue helps re-enforce when watching a battle which side won.

What do others think? My vote here is to keep this behavior.

**Comment by Cernelius** [comment]
> @Cernelius, to confirm, are you saying there is no "battle success" battle sound capability?

There is for sea and air battles, but I'm not aware there is any for non-air-only land battles.

Just test it. Have you ever got a sound at the end of a victorious land offensive, beside the sound for capturing the territory? I assume you never did.

You can test it by starting "Pact of Steel", changing "Anglo Egypt" to "Germans" ownership and attack the territory with "Italians". You should receive no sound at all upon winning the battle.

Or you can take a look at the `TripleA/assets/sounds/generic`. You should see a folder called `battle_air_successful`, a folder called `battle_sea_successful` but no folder called `battle_land_successful` or `battle_successful`.

---

However, the fact that TripleA lacks a sound for non-air-only successfull land offensives is beside the point. As far as this issue goes, that just means that a successfull non-air-only land defence should give no sound if there is no sound for it and give the `battle_land_successful` sound if it exists.

This additional problem should not matter for sea battles, since for them you already have the sound.

---

I reiterate that, if I'm the defender and get invaded and win the battle, it is really wrong that I'm earing a sound making me think that I've lost something. I should be happy, not sad (a trumpet).

I think having no sound upon defensively winning would be still preferable to having a defeat sound.

**Comment by DanVanAtta** [comment]
> I reiterate that, if I'm the defender and get invaded and win the battle, it is really wrong that I'm earing a sound making me think that I've lost something. I should be happy, not sad (a trumpet).

That defeat sound always means the attacker lost. So long as you are aware you were defending, it means you won (the sound played is always from the perspective of the attacker, so the attacker lost). If we were to change this, I don't know how we fix the inconsistency of hotseat, have meaningful sound for spectators, or perhaps the confusion that the victory sound is relative to who you are playing.

If we had no sound for neutral players in a battle or observers, an important auditory cue would be lost IMO.

**Comment by Cernelius** [comment]
If it is officially stated that that sound is meant to signify the battle ends because no offending units remain, this issue can be either closed or repurposed as to make it clear, for example by changing `battle_failure` to something like `defensive_victory` or `offensive_failure`. Similarly, `battle_air_successful` and `battle_sea_successful` could be renamed to something like `offensive_air_victory` and `offensive_sea_victory`.
