### ISSUE TITLE
Having Trouble Getting a Scenario to Display in the List

### ISSUE THREAD

**Issue by RogerCooper** [triplea-game/triplea#8841]
### How can the problem be recreated?

I have been converting mods to the new format. This particular mod will not appear even though I have converted similar xml-only mods without problem.

### Do you have any ideas for an expected fix?
This mod uses variables. I wonder if that is confusing the game engine.

### If playing a prerelease, which version are you using?

Game Version: 2.6.36

### If playing a prerelease, does this happen on the latest release?

- [] yes
- [] no

### Is there anything else we should know?
I tried having this as a stand alone mod and putting it with other xmls using the same map (and which do appear). Nothing helps. I changed the extension for the upload.
[AA50-41-Maintenance.txt](https://github.com/triplea-game/triplea/files/5968968/AA50-41-Maintenance.txt)

**Comment by DanVanAtta** [comment]
I notice:
```
    <property name="mapName" value="AA50-41-Maintenance" editable="false"/>
```
Where can that base-map be obtained? Are you copying the XML into that map, or you are copying the map assets into the XML only mod?

**Comment by RogerCooper** [comment]
I already copied the assets into the folder (from World War II v3). I also tried putting it into folder with other xml's that were displaying and used the same assets and it still did not display. That is why I suspected the variables might be causing a problem. As we discussed extensively before, mapName is deprecated and I have been converting xml-only mods to standalone mods. This is the first one I have been unable to convert.

**Comment by DanVanAtta** [comment]
The folder structure of a map remains complex, for example there must be a polygons.txt and an assets folder for the map to be indexed, and XMLs are searched for only up to a specific depth. If you point me to where I can obtain the map assets, I can try and simulate and will be able to more easily say why the XML is not being indexed.

**Comment by RogerCooper** [comment]
I zipped it and posted it on this link, https://drive.google.com/file/d/1knx5Td99PjDWKj2YR9HKTmBci6e530-l/view?usp=sharing
Note that the other 2 xml's in the folder do appear on the scenario list. That is why I suspect the problem is with the variable lists, as few other xml's use this feature.

**Comment by RogerCooper** [comment]
I having this problem with a different xml. This does not use variables, and has few changes at all. It is variant for the classic game. It does not show up in its own folder with the assets copied over from World War II Classic or it I stick in the games folder for world_war_ii-classic. However, I have converted about 10 mods successfully, I don't see why these are not working.
[AAC-BuildCaps.txt](https://github.com/triplea-game/triplea/files/5975921/AAC-BuildCaps.txt)

**Comment by DanVanAtta** [comment]
@RogerCooper I was not able to access the google drive contents due to permissions. I suspect this problem is because the 'map.yml' file for the respective mod or map was already generated. Can you copy here the contents of the 'map.yml' file for the map that are you are updating?

Assuming such a file exists and the game variant is missing from it, is this problem fixed if you add a line like:
```
- {xml_path: map/games/AAC-BuildCaps.xml, name: AAC-BuildCaps}
```

For context, it will be expected that all maps will contain a 'map.yml' file going forward. To migrate users between 2.5 and 2.6, the file is one-time auto-created for already downloaded maps.

**Comment by DanVanAtta** [comment]
Thanks for enabling access @RogerCooper , I notice a number of problems:
- back slashes in `map.yml`. If you change those back-slashes to forward slashes, do the games still load for you @RogerCooper ? It's an OS variation, backslashes are not valid outside of windows. To avoid this issue it may need to be that the path attribute is solely the game file name and instead we can have the game engine search for a file with that name.

- folder extraction is no longer detecting a single zipped folder. EG: the extracted path of the zip was: `AA50-BuildCaps/AA50-BuildCaps`, instead of just `AA50-BuildCaps/`. The logic here has been painful to get right, if there is a single folder that results from extraction then that folder needs to be renamed and moved to downloadedMaps, otherwise the extracted contents will not work in 2.5. Otherwise if extraction results in many files, then the folder we have extracted into is the right one to move.

- there are still usages of the 'mapName' property from within XMLs. This can lead to bad map-folder lookups. Moving all installed maps to another folder and only looking at just the one, this problem became evident.


Overall, what I suspect happened is that the game entry was missing from the map.yml file that was generated. Perhaps the sequence was this:
- extracted zip moved to downloadedMaps/
- game launched (which extracts)
- select game button clicked (generates a map.yml)
- game is closed
- variant XML is moved to the newly extracted map
- game launches (nothing to extract)
- select game button clicked (map.yml file already exists, not modified)
- the variant XML is not listed because it is not listed in the map.yml file

**Comment by RogerCooper** [comment]
I changed the backslashes to frontslashes and it still did not work.

map_name: AAC-BuildCaps
games:
- {xml_path: AAC-BuildCaps/games/AAC-BuildCaps.xml, name: AAC-BuildCaps}
version: 0

However AAR-BuildCaps does work even with backslashes.

map_name: AAR-BuildCaps
games:
- {xml_path: AAR-BuildCaps\games\AAR-BuildCaps.xml, name: AAR-BuildCaps}
version: 0

I don't think map.yml is the issue. Keep in mind that the map.yml file was generated by TripleA itself.

AAC-BuildCaps is an xml-only mod. It uses only the default units & flags. Can you get it to work in any fashion?

**Comment by DanVanAtta** [comment]
I dropped in the xml-only mod into the map contents (into the games/ folder). I then updated the map.yml file to be as follows:
```
map_name: AA50-BuildCaps
games:
- {xml_path: games/WW2v3-1941-BuildCaps.xml, name: AA50-41-Build Caps}
- {xml_path: games/WW2v3-1942-BuildCaps.xml, name: AA50-42-Build Caps}
- {xml_path: games/AAC-BuildCaps.xml, name: AAC BuildCaps}
version: 0
```

That worked to get the XML variant to then show as a game selection option. There was an error when selecting or starting the game, though that is due to  problem `C` above.

The map.yml is *the* way the game engine finds game files, if the game file is not listed in the map.yml, it will not be listed. The map.yml file is one-time generated, if new XML files are dropped in, the map.yml file is not automatically updated.

**Comment by DanVanAtta** [comment]
The 'xml_path' is relative from the location of the 'map.yml' file. That looks to be the difference between our map.yml snippets.

**Comment by RogerCooper** [comment]
AAC-Buildcaps should not in the AA50-BuildCaps folder. Looking at the yml for AA50-BuildCaps

map_name: AA50-BuildCaps
games:
- {xml_path: AA50-BuildCaps\games\AA50-41-Maintenance.xml, name: AA50-41-Maintenance}
- {xml_path: AA50-BuildCaps\games\WW2v3-1941-BuildCaps.xml, name: AA50-41-Build Caps}
- {xml_path: AA50-BuildCaps\games\WW2v3-1942-BuildCaps.xml, name: AA50-42-Build Caps}
version: 0
So AA50-41-Maintenance is in the yml with the exact same path but it is not in the list.

**Comment by DanVanAtta** [comment]
Is this the rough folder structure?

```
AA50-BuildCaps/AA50-BuildCaps/map.yml
AA50-BuildCaps/AA50-BuildCaps/games/AA50-41-Maintenance.xml
AA50-BuildCaps/AA50-BuildCaps/games/WW2v3-1941-BuildCaps.xml
AA50-BuildCaps/AA50-BuildCaps/games/WW2v3-1942-BuildCaps.xml
```

The path in `map.yml` is relative to that file, ie: relative to `AA50-BuildCaps/AA50-BuildCaps/`
Hence, the path is just `games/AA50-41-Maintenance.xml`

The path in `map.yml` is *not* relative to the downloadedMaps folder.

**Comment by RogerCooper** [comment]
The folder structure as a you say. I tried changing the map.yml file to

```
map_name: AA50-BuildCaps
games:
- {xml_path: games/AA50-41-Maintenance.xml, name: AA50-41-Maintenance}
- {xml_path: AA50-BuildCaps\games\WW2v3-1941-BuildCaps.xml, name: AA50-41-Build Caps}
- {xml_path: AA50-BuildCaps\games\WW2v3-1942-BuildCaps.xml, name: AA50-42-Build Caps}
version: 0

```
The buildcaps scenarios list despite their incorrect references, but AA50-41-Maintenance does not list with its correct reference

**Comment by DanVanAtta** [comment]
The "xml_path" value is simply the path from the 'map.yml' file to the game XML file. So this all depends on where your map.yml file is.  If all 3 of those XMLs are in the same folder, then I would expect their paths to be the same except for the file names.

**Comment by RogerCooper** [comment]
So I made sure that the paths are all identical
`map_name: AA50-BuildCaps
games:
- {xml_path: AA50-BuildCaps\games\AA50-41-Maintenance.xml, name: AA50-41-Maintenance}
- {xml_path: AA50-BuildCaps\games\WW2v3-1941-BuildCaps.xml, name: AA50-41-Build Caps}
- {xml_path: AA50-BuildCaps\games\WW2v3-1942-BuildCaps.xml, name: AA50-42-Build Caps}
version: 0
`
AA50-41-Maintenance still does not show even though it is the same folder and referred to by the same path. I also tried changing the order of entries, but it did not help.

Tried this way as well
`map_name: AA50-BuildCaps
games:
- {xml_path: games/WW2v3-1941-BuildCaps.xml, name: AA50-41-Build Caps}
- {xml_path: games/WW2v3-1942-BuildCaps.xml, name: AA50-42-Build Caps}
- {xml_path: games/AA50-41-Maintenance.xml, name: AA50-41-Maintenance}
version: 0
`
The results are the same, the 2 build caps scenarios appear on the list & AA50-41-Maintenance does not. There must be some issue beyond the yml file.

Here is the folder structure
![image](https://user-images.githubusercontent.com/20504877/108283201-e64c1400-7150-11eb-8d8b-a324de9cea3a.png)

**Comment by RogerCooper** [comment]
I was working the "Age of the Sturlings". I saw that the version from the repository was not the latest, so I copied the latest version into the games folder and changed the yml
`map_name: age_of_the_sturlungs-master
games:
- {xml_path: map\games\Age_Of_Sturlungs_0.0.3.xml, name: Age_Of_The_Sturlungs_0.0.3}
version: 0
`
Version 0.0.2 continues to display even though it is not in the yml at all. There must be somewhere else that the information is being tracked.

**Comment by DanVanAtta** [comment]
'0.0.2' is the game XML version. The 'map.yml' has the version for the map, used to identify when a map is out of date and should be redownladed. The game XML version is not used for anything other than display.

**Comment by DanVanAtta** [comment]
Re: aa-50-maintenance, I am able to get it to load with:
```
map_name: AA50-BuildCaps
games:
- {xml_path: games/WW2v3-1941-BuildCaps.xml, name: AA50-41-Build Caps}
- {xml_path: games/WW2v3-1942-BuildCaps.xml, name: AA50-42-Build Caps}
- {xml_path: games/AAC-BuildCaps.xml, name: AAC BuildCaps}
- {xml_path: games/AA50-41-Maintenance.xml, name: AA50-41-Maintenance}
version: 0
```

![Screenshot from 2021-02-19 15-16-20](https://user-images.githubusercontent.com/12397753/108571630-7317de80-72c5-11eb-8137-8fc3d1e81c7c.png)


You can check the `triplea.log` file to see if it has any information. It is the new 'console'. If the file is still absurdly large, delete it and relaunch the game. The verbose logging was in place to help debug another issue and is turned off now (so the log size should be far more reasonable). The log will mention if there are errors parsing maps. Though, for a file to show up in the select game list, the map XML file is not even read, the select game list is purely based on the contents of map.yml

**Comment by RogerCooper** [comment]
I copied the .yml over but it still did not work. Here is the log file

`1154 18:45:35.276 [main] INFO  o.t.game.client.HeadedGameRunner - Launching game, version: 2.6.69@022639fd8c 
2045 18:45:36.167 [Thread-2] DEBUG g.s.e.data.gameparser.GameParser - Parsing game XML: file:/C:/Users/Roger/triplea/downloadedMaps/anti_imperialism/anti_imperialism/games/anti_imperialism.xml
`
[Anti_imperialism was the scenario I had last run.] I have also converted a dozen scenarios without any trouble. I also tried removing the AAC-Buildcaps line from the yml (that scenario uses a different map) but the AA50-41-Maintenance still did not appear on the list.

The screenshot you posted is not the actual selection screen. Did you actual get it to appear on the selection screen.

**Comment by RogerCooper** [comment]
I tried deleting the map.yml file and letting TripleA regenerate it. It created the following map.yml
`map_name: AA50-BuildCaps
games:
- {xml_path: AA50-BuildCaps\games\AA50-41-Maintenance.xml, name: AA50-41-Maintenance}
- {xml_path: AA50-BuildCaps\games\WW2v3-1941-BuildCaps.xml, name: AA50-41-Build Caps}
- {xml_path: AA50-BuildCaps\games\WW2v3-1942-BuildCaps.xml, name: AA50-42-Build Caps}
version: 0
`
AA50-41-Maintenance still does not appear on the selection screen but other 2 scenarios do appear.

**Comment by DanVanAtta** [comment]
@RogerCooper  give [2.6.56](https://github.com/triplea-game/triplea/releases/tag/2.6.56%40a3cac8b040) a try. I was able to get all 3 to load and was able to start a game on each one.

Steps:
1. Installed 2.6.56
2. Downloaded zip file attached above
3. Launched 2.6.56 
  - ignore invalid map.yml warning
  - map is extracted
4. Closed TripleA
5. Deleted the 'map.yml' in the extracted folders
6. Launched 2.6.56
7."Select game" 
   - engine generated a new map.yml file
   - all 3 games appeared in the selection list

Here is what the folder structure wound up looking like:
```
dan@dan-xps:~/triplea/downloadedMaps$ find AA50-BuildCaps/ | egrep "map.yml|*.xml"
AA50-BuildCaps/map.yml
AA50-BuildCaps/AA50-BuildCaps/games/WW2v3-1941-BuildCaps.xml
AA50-BuildCaps/AA50-BuildCaps/games/WW2v3-1942-BuildCaps.xml
AA50-BuildCaps/AA50-BuildCaps/games/AA50-41-Maintenance.xml
```

(side note, the middle AA50-BuildCaps folder is extraneous, but does not hurt).

The `map.yml` file was generated with these contents:
```
map_name: AA50-BuildCaps
games:
- game_name: AA50-41-Build Caps
  file_name: WW2v3-1941-BuildCaps.xml
- game_name: AA50-42-Build Caps
  file_name: WW2v3-1942-BuildCaps.xml
- game_name: AA50-41-Maintenance
  file_name: AA50-41-Maintenance.xml
version: 0
```

There is some additional logging when the game engine is trying to load a game from map.yml, so if it cannot find something there should be more information now. The game list is completely driven by the contents of a map.yml file, with the above all 3 really ought to be listed.

Please let me know how it goes.

**Comment by DanVanAtta** [comment]
Should mention, the map.yml format is now updated to search for a file given a name rather than specifying a full path. All previously generated map.yml files should be deleted so that they can be regenerated.

The 'map-name' in a mod would match that of the original map. I have a working theory that there were multiple map.yml files with the same map-name causing this problem. Having mods and the original map both in downloaded folders would result in that scenario. The engine needs the map name to be unique, if they are not unique then only one file will be picked up, I think this is likely what is happening. If you update the 'map_name' in one of the 'map.yml' files where you are not seeing a XML show up, that might do the trick.

**Comment by DanVanAtta** [comment]
Closing, Roger stated in forums that this is fixed with latest.
