### ISSUE TITLE
2..6.73 Problems

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#8995]
Testing 2.6.73 with my unpublished Settlers: War of the Lance (same as 2.6.39), the one with no enemy within 3-4 Territories.
A local game with  6AI, 2 Factions of 3 aside

**Speed**
```
v 2.5.22294 43 40 44 40 45 44 45 mean = 43
v2.6.73        60 65 63 62
```
Slower than 2.6.35

For reference here is the old version stats
v 2.6.35    55 51 46 49 48 45 47 mean ~ 49

.
**Cannot exit TripleA with just AI playing.**
When I was testing the above I used to be to press [x} top right to leave the game, with 6 AI playing each other.  This no longer works, it hangs and I have to load Task Manager and end task.

I also tried File> Leave Game, that hangings
I also tried File> Exit Program, that hangings

.
**Errors caused by old map.yml**
Also from a previous test version I had map.yml in map folders for lots of downloaded scenario maps, 2.6.73 produced lots of errors.  
I removed the map.yml inside the map folder and everything worked as expected.
It might be worth checking for old map.yml in map folders and deleting them.

**On the plus side**
I really like the new format for the Download Maps screen.
I hoping we will also get the **era** as a column?   :-)

**Comment by DanVanAtta** [comment]
@TheDog-GH generally best to keep one issue to one problem. That way one fix closes one issue and we don't have issues that have running check lists that can never be closed because there is still something lingering (and then the issue length and text grows to the point where it is even an effort just to *read* the issue and an exercise to know what is even remaining).

For game play speed, 2.6.55 is seemingly the only thing that could have made a difference between *35 and the current. If you could check that version and the one preceding, that will narrow it down, but I don't readily see where the difference would come in. The performance of TripleA is very happenstance, the speed it has is not by design but by careful hacking, at some point we will not be able to maintain it and a rewrite of a much of the engine is needed. It's like peanut brittle in there.

The cannot exit deserves it's own issue and is something to be tracked down. Whenever the game engine freezes a stack trace is key. Launching TripleA from console (on windows) and following the steps here: <https://access.redhat.com/solutions/19170> to obtain that.

Old map.yml files are expected to cause issues. The recommendation is to delete them all and allow the engine to regenerate new ones. Note that the generation is *only* a bridge for players when they upgrade from 2.5 to 2.6. The majority of times map.yml files are expected to be in map folders.

Glad to hear you're liking the new download layout.

**Comment by DanVanAtta** [comment]
@TheDog-GH please create two dedicated issues for the performance problem and the cannot exit problem.
