### ISSUE TITLE
2.6.89 Continue Game Yes or No cannot be entered

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#9020]
With an economic victory I got this, its not a proper dialog box.

![Victory](https://user-images.githubusercontent.com/71022517/110538705-3c8ef000-811c-11eb-986c-0a3e73256de6.png)

**Comment by DanVanAtta** [comment]
Would you mind attaching a save game that is before the economic victory?

**Comment by TheDog-GH** [comment]
Saved Game - should show Economic Victory dialog box after 1-2 turns.  There is only 1 player, the rest are AI.
[SAoT-04.zip](https://github.com/triplea-game/triplea/files/6115823/SAoT-04.zip)

Scenario Map used - 
https://drive.google.com/file/d/18D0bc1ucrQ46ZcwtY6u_ih45mEMEEr2x/view?usp=sharing

**Comment by bkelly1984** [comment]
This is a problem caused by attempting to create a JOptionPane from outside a Swing event thread in EventThreadJOptionPane.showConfirmDialog. Some work was done to render some components within SwingUtilities.invokeLater, but I am guessing Swing in the newer versions of the JVM are less tolerant.

I'll rewrite the method and try my hand at submitting a pull request.

**Comment by TheDog-GH** [comment]
In later versions this has been solved/resolved.
