### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#9043]
### Reproduction Steps

1.Try to access the triplea forum
2.504 Gateway Time-out occurs 
3.Has happened on average once a month or so last 3-4 months

![Screenshot from 2021-03-18 03-20-10](https://user-images.githubusercontent.com/24382682/111594687-61790800-8799-11eb-8c6a-7d5dd5ca06e8.png)

### Engine Version

Engine Version:

**Comment by panther2** [comment]
> 3.Has happened on average once a month or so last 3-4 months

Personally, I experience this regularly.

**Comment by beelee1** [comment]
@panther2 Well I guess I should consider myself lucky then lol Idk if it might have something to do with internet provider, but I kinda doubt it. The other sites, one of them being nodebb doesn't do it, so... At any rate, it's annoying but not unusable.

**Comment by ron-murhammer** [comment]
It seems worse today than usual.

**Comment by beelee1** [comment]
Yes it does. Still can't get on.

**Comment by DanVanAtta** [comment]
Keep in mind 503 vs 504:
- 503 is the forum software shedding load (overloaded, alive but actively refusing)
- 504 is the forum software is dead

cc: @RoiEXLab

**Comment by RoiEXLab** [comment]
@DanVanAtta Thanks for the CC, did you happen to read my ticket I opened at linode? (I think you should be able to see it, but I'm not sure)
It's the same issue again where the kernel log just spams a bunch of 
![grafik](https://user-images.githubusercontent.com/8350879/111704685-dbfc6300-883f-11eb-9b1a-19d2f1779926.png)

**Comment by RoiEXLab** [comment]
@DanVanAtta So a couple of things to note here:
What always seems to work is to simply reboot the machine. Not really desirable but it's a rather simple fix.
The nodejs process is actually still running, it's just unresponsive so that's why we get a 504.
The amount of free memory on the system is rather low, but there are some megabytes left.
Some applications work without problems (like top, grep, python, etc.) but others just hang up when trying to use them, like htop or systemctl status not sure if there's a pattern.
Out of desperation I upgraded the machine from Ubuntu 16.04 to 20.04 maybe this helps. I doubt it.
So we likely need a plan B here.
In my opinion there are 2 options:
1. We try to recreate the server using a fresh machine, basically only copying the files with relevant data but redoing all the configuration stuff. Could work, a very pragmatic approach.
2. We finally try to incorporate nodebb into our server management system using docker or something. This could allow us to streamline the process of updating a little bit and would provide a lot of smaller benefits. Would need some careful planning though, depending on how large we want the scope to be. If I'm not missing anything we need just a couple of things: nginx, nodejs + nodebb files + systemd/docker config, certbot, mongodb.
Thoughts?

**Comment by DanVanAtta** [comment]
- Rebooting is an undesirable mitigation. 
- We did not start seeing this problem until upgrading NodeBB.

The folks at linode recommended upgrading the kernel, going from 16 to 20 is quite a jump in kernel version. I would not be surprised if the version of NodeBB we were using and ubuntu 16 had issues playing together.

The process listing of nodebb would freeze, htop uses the 'ps' command under the hood uses the same command. It was really interesting as 'ps' would report output just until it hit NodeBB, at which point it would hang.

I don't think this is hardware related.

> We finally try to incorporate nodebb into our server management system using docker or something.

We actively should pursue this no matter what. We cannot safely upgrade nodebb right now, all changes are done in production. Furthermore, there is no record of what chnaged, how it is configured, etc.. Essentially you @RoiEXLab are the sole maintainer and all knowledge about the exact configuration is tribal. 

We have a container set up, we only need to get it working really easily (I had issues getting mongo set up with docker). Once that is done, we can script up a clone of the TripleA repo and then run a docker build and run command. That is not quite as ideal as having a docker registry, but nonetheless follows 'infrastructure-as-code' and allows us to demo locally any updates before deploying them.

**Comment by beelee1** [comment]
Any update on this ? Forum was really whacking out with the 503 yesterday. Basically made it unusable. Won't even do that now. Just says "Unable to connect".

**Comment by RoiEXLab** [comment]
I just checked the status and the problem was that this time we simply ran out of disk space. I don't know how to quickly increase the disk plan for our linode, so I just used 1G from swap storage instead. This won't hold for long @DanVanAtta we might need to consider different options in order to fix this.
