### ISSUE TITLE
Issues with Wrong Map Names

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#9398]
### Reproduction Steps

1.Noticed it twice. There's this one

https://github.com/triplea-game/triplea/issues/9396

and this one

https://github.com/triplea-game/triplea/issues/9364

The second one was on a mac and they have been problematic for triplea in the past. At any rate, seems worth a mention.
2.
3.

### Engine Version

Engine Version:

**Comment by DanVanAtta** [comment]
Seemingly it's going to be a game of whack-a-mole until something more systemic is done. Namely maps could use a validator and have all the required names be more explicit and easier to track down.  FWIW the 2.6 map.yml file makes the map name dependency easier to deal with, no longer does the repo and folder and XML have to have an aligned name, so that's a small win..
