### ISSUE TITLE
Show standard deviation in battle simulator

### ISSUE THREAD

**Issue by emmanuel-perlow** [triplea-game/triplea#9489]
The battle simulator (better known as battle calculator) currently only shows the expected value (average) for win%, TUV swing, units left, ... Some battle combinations are quite "unstable", i.e. repeatedly pressing recalculate lets the numbers "jump" around. This is expected as we are rolling a dice and have randomness.
To quantify the uncertainty in the expected value we should also print the standard deviation in the results.

**Comment by Cernelius** [comment]
> Some battle combinations are quite "unstable", i.e. repeatedly pressing recalculate lets the numbers "jump" around. This is expected as we are rolling a dice and have randomness.

This is practically an issue only because TripleA offers an idadequate standard run count (default for dice is 200). With high enough run counts, the average outcome of the simulations is virtually assured always to be as close to the actual average as you possibly need it to be for decision-making purposes while playing.

Reference:
https://forums.triplea-game.org/topic/863/increasing-regular-dice-default-run-count

**Comment by DanVanAtta** [comment]
Closing in favor of the open PR
