### ISSUE TITLE
Exceptions when taking Screenshots of some Maps

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#952]
Just noticed this on WaW and GreatWar... 
[StackTrace](https://gist.github.com/RoiEXLab/2624e7e430d73fa63b702a8262c84fca)

**Comment by RoiEXLab** [comment]
@DanVanAtta Yes, I am using the export Scrrenshot menu, and Yes this can be reproduce consistently

**Comment by DanVanAtta** [comment]
#977 fixes the stack trace.  Though, the screenshot does still happen, so the stack trace does not seem to be of consequence. It is also interesting that for a screenshot we attempt to lock the technology data in game data. 

Otherwise, the screenshots did succeed before hand, just it takes a long time. Also of note, this problem only appears to happen on maps that do not have techs, like WaW. On BW there was no stack trace.

**Comment by RoiEXLab** [comment]
#1001 has a fix!

**Comment by RoiEXLab** [comment]
I guess this can be closed then...
