### ISSUE TITLE
Game Popup and MenuText Fine Details and Inconsistencies

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#958]
### Pre game launch:
- [x] A. “Choose Game…” : Opens window named “Select a Game” (Should stick to either choose OR select term) 
- [x] B. “Load Saved Game…”: Opens window named “Open” (Should stick to either load OR open term) 
- [x] C. “Download Maps” (does not have the “…” in the button name. Should there be some kind of consistency? Or why not remove ALL instances of “…” from all menues?) 

### In game:
- [x]  D. “File” -> “Exit” : Opens window “Exit” (I think the popup should spell out more that you will shot down TripleA game if clicking Yes)   *discussing*
- [x] E. “File” -> “Leave Game” : Opens another window called “Exit” (Obvious the popup name should change to leave game. This popup also gives the exact same description of what will happen if clicking Yes. I think it should spell out more that the player will return to the main game menu.) 

- [ ] F. I would say the game menu named “File” should name change to “Game”. (Save game, leave game and exit)   *discussing*

- [ ] G.  I would say the game menu named “Game” should name change to “Options” as most thing there are options related)   *discussing*

- [x] H. Games” -> “Settings” : Opens window with no name and a Java icon instead of TripleA icon. 

- [x] I.  “Export” -> “Export Setup Chart…” : Open window named “Export Setup Files”. 

- [ ] J. “Web” -> “Bug Report” : Opens https://github.com/triplea-game/triplea/issues/new
“Help” -> “Send Bug Report”: Also opens https://github.com/triplea-game/triplea/issues/new

- [x] K. "Help” -> “Movement/Selection help…” : “Movement Help”

From: http://tripleadev.1671093.n2.nabble.com/Requesting-game-menu-cleanup-of-names-icons-descriptions-tp7592876.html

- [x] L. Remove all "..." from the game menus

**Comment by DanVanAtta** [comment]
#959 address A and C

**Comment by DanVanAtta** [comment]
#960 address F

**Comment by DanVanAtta** [comment]
D, could use some help on wording, any recommendations?

>  D. “File” -> “Exit” : Opens window “Exit” (I think the popup should spell out more that you will shot down TripleA game if clicking Yes)

**Comment by DanVanAtta** [comment]
F+G: The options in the game menu should be migrating to the settings window. The 'Game' menu will then begin to make more sense. I'm curious how that changes the suggestion to rename.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/issues/957 covers H, let's track that issue there.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/pull/961 address point I

**Comment by DanVanAtta** [comment]
#962 address point L

**Comment by FrostionAAA** [comment]
Nice Work! :)
Maybe we should also adress if there should there be capitalization or no capitalization in titles? “Engine Settings” or “Unit help” are examples.

About D and E, what about "Leave Game" and "Exit Program"
maybe followed by...
“Are you sure you want to leave current game?”
“Are you sure you want to exit TripleA?”

I don’t think it would be fitting and visually appealing if the warning popup has a line too long. It should be short and small, as with most other programs. I think this kind of popup is meant more as a chance to change mind than information about what the consequences are.

**Comment by Cernelius** [comment]
The menu Game can stay as it is, because it is supposed to have the "Gameplay Options" inside, while the "Visual Options" are in "View", and it also has many gameplay things that are not options. If changed, then it should be changed to "Game Options", not just "Options". Myself, in the interest to be brief, I'd just leave it as "Game", as it is now.

You are cleaning a lot of rubbish, good job, and, while you are at it, I'd add:

- It makes no sense that inside "Game" you have the sound options too. Those have nothing to do with "Game", as it is not changing your "Game" if you are hearing horses galloping while you blitz or whatnot.
The Sound options are a "skin" thing, just like all the visual custom stuff, so they should rather stay with the current "View" options, or in a separate "Hear" menu.
"Enable Sound" and "Sound Options" should be moved with the "View" option and the "View" menu changed to "Skin" or "Feel" or "View/Hear" or "Visual/Sound" or something the like (my suggestion is "Skin", as it would be the most technically correct name).

- Albeit rarely used, "Map Skins" should be either the very first option or the last one of the skin related ones (in this last case, it should be right before "Edit Map Font and Color", that is the first not-skin related option); being somewhere in between of some and some other skin-dependent (thus, subset) visual options makes no sense at all: it's just random.

- "Show Comment Log" should be moved to "Game", because its only sensible use is to record stuff gameplay related, burning it into the savegame, like the gameplay moves you do. Generally speaking, whatever is recorded in the savegame itself should absolutely stay in "Game". Best position is probably right below "Enable Edit Mode", because this is sort of an edit thing too, and quite related to it (you are eventually going to edit the game based on what you recorded you intended it to be, like in the case of what Fighter is on what Carrier, when the Carrier is lost).

- "Show Chat Times" should be an option of the "Network" menu, that you see only when you are playing a game online, next to "Show Who is Who".

- "Show Battles Between AIs" is a lame name, because the purpose of this option is not that, but to generally show or not to show all battles you are not taking part of (which, of course, includes the battles between AIs, but also battles between other players); thus, it should be changed to something like "Show Battles Between Other Players". Moreover, being not an AI option at all (just indirectly related, like almost everything), it should surely not stay in the AI section of Engine Settings. It is better it stays wherever "User Notifications" is, since it is a similar concept; likely "View".

- "User Notifications" should stay in "View", not in "Game", since it is a visual only option, that in case of the Triggered Notifications is also dependent to what is in the relative Skin's txt, and it is very closely related to the triggered sounds.

- "Focus on own casualties" is a pointless name and the explanation is too long and it goes on three lines on my machine, with the third line being unreadable. Beside renaming, I also suggest expanding this option to confirm or not confirm anything with spacebar (not only casualties selection); since spacebar is also used for chatting, it is a very bad thing to use it for any gameplay purposes when playing online (the most annoying example is that you accept politics with it; thus you will accept politics if you are pressing spacebar for chatting, which usually indeed happens during the Politics phase of games).

- "Default Dice Run Count" and "Default Low Luck Run Count" have 10000 as max, while the battlecalculator has 20000 as max. The max should be the same for both cases. Since I believe 20000 (20,000) is already too low, I suggest you increase them both to 100000 (100,000). If it must be one of 10000 or 20000, then I'd say 20000 for both, definitively (20000 is already too low, so not going down even more).

- "Send Bug Report" in Help should be removed, since it is not a "Help" thing and there is the same in "Web/Bug Report" already. I know you think it is good having this duplication, but I disagree.

- Not many people are going to see the "AI Pause Duration", if you bury it inside the Engine Settings. Moreover, as said, since "Show Battles Between AIs" is an AI option in name only (and the name should be changed), then "AI Pause Duration" would be the the only one option of the AI table of Engine Settings. Moreover, the description goes on three lines and the third line is unreadable.

- On my machine, the majority of the descriptions in Scrolling go to three lines, the third line being unreadable.

- "Start PBEM (Play-By-Email/Forum) Game" should be changed to simply "Start Play-By-E-Mail Game". You can easily explain that this is for Playing-By-Forum too, or whatever, in the tooltip.

- The "Rule Book" tooltip says "(it is also included in the directory TripleA was installed to)"; this is not anymore so, thus update the tooltip too.

Can somebody tell me what "View/Show Production Tabs" does, if anything, please?

**Comment by Cernelius** [comment]
![engine_settings](https://cloud.githubusercontent.com/assets/19562310/17273383/57492e8a-56b3-11e6-9ac1-fbbd73161227.png)

**Comment by DanVanAtta** [comment]
@Cernelius would you mind editing  your last comment and cut/paste the new topics to new issues? I think there are probably 3 or 4 different topics to be discussed.

For the third line being cut off, tracking that in: https://github.com/triplea-game/triplea/issues/1028

**Comment by DanVanAtta** [comment]
For J - It seems to me the web menu is there now more for historical reasons rather than practical. Before things would be tucked in with the game to ensure that someone downloading it would find all the loose ends and pieces. Namely, there was not a good website page that indexed all of the various web links, so it was put in the game engine to give people a place to find it.

Many of the web links do not really make sense in terms of flow. For example, 'how to host', presumably that is information a person would want to know well before they are in a game. It also does not make sense for that info to be in-game, and not instead on the game hosting page, or somewhere near there.

So, the problem that the menu is solving is indexing the various website/pages of interest. We already have this on the game website, and also on various readme's too. Hence, the help > bug report I think should stay, and the whole web menu removed. 

Here is the further rationale. For an index of links, generally it is enough to make someone aware where they are. Most of the links, like how to host, are used in a context that is well before game play. On the other hand, bugs happen in game, and we want to make it as smooth as possible for someone to send a bug report. Ideally we would include a 'submit' bug report button that could be clicked on from the error console.

**Comment by DanVanAtta** [comment]
F, G, J pending discussion, D was done recently.

**Comment by Cernelius** [comment]
@DanVanAtta I'm mostly clueless; please, can you make a list of what you think belongs to this issue and what not? Also, can you make a grouping of the below numbered elements regarding what you think should go into a same new issue (just tell the numbers)?
I believe that more than half of these points actually belong to this issue, being very close in nature to the Frostion's points.

1. Moving sounds to View
2. Moving Map Skins
3. Moving Show Comment Log to Game
4. Moving Show Chat Times to Network
5. Renaming show Battles Between AIs to Show Battles Between Other Players etc.
6. Moving User Notifications to View
7. Renaming Focus on own casualties and moving back to main menu etc.
8. Equalling max for BC
9. Removing duplicate Bug Report
10. Moving AI Pause Duration back to main menu
11. Making descriptions readable
12. Renaming "Start PBEM (Play-By-Email/Forum) Game" to "Start Play-By-E-Mail Game"
13. Updating the "Rule Book" tooltip

Then, I will remove the above listing, update the previous one, and open new issues based on your suggest groups.

Thanks!

p.s.: If some of these issues are not important enough to track them, let me know as well.
p.p.s.: I already know you hopened a issue for 11 and 9 belongs to this issue.

**Comment by DanVanAtta** [comment]
@Cernelius  - goal is for things to be manageable, clear, and ideally summarized. Also desirable to keep issues focused, and not let them expand to cover new and yet more new topics as each day progresses. So multiple, newer smaller issues are preferred if they can be closed more easily. If discussion runs really long on one issue, it's desirable to simply give a link to a new issue, close that issue, and then re-summarize in the new one (and giving a link to the old issue so they are easily referenced).

So with that said, anything new should go to a new  issue please. I'm tempted to take the remaining items here and lump them together with the new issue, so this issue can be closed out.

**Comment by DanVanAtta** [comment]
Also, thanks for numbering the new points, that helps keeps things summarized and easy to talk about.

**Comment by Cernelius** [comment]
> I'm tempted to take the remaining items here and lump them together with the new issue, so this issue can be closed out.

Agree. Call it "Game Popup and MenuText Fine Details and Inconsistencies Part 2".

**Comment by Cernelius** [comment]
And, anyway, I think the items **F** and **G** are better be dropped, as I've explained, and on the **J** I just think there should be no duplicates, but no biggie.

**Comment by DanVanAtta** [comment]
Let's spin up a new github issue for anything remaining that we wish to be done.
