### ISSUE TITLE
Slow map parsing

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#979]
When there are map parse errors (IE: all maps downloaded, and some have errors), the map parsing process takes a long time (on the order of 20 seconds or so). This makes it obvious too that we are doing map parsing on game launch.
1. The map parsing should not take so much longer due to map parse errors
2. The map parsing on game launch is needless. The map parsing will happen again when you click open game button.

**Comment by RoiEXLab** [comment]
@DanVanAtta If substance allows it this time, we might consider adding in a loading screen (for the open game button)

**Comment by DanVanAtta** [comment]
The save screenshot could use a load screen IMO - #982 . It should also be made faster, but it will need a progress indicator regardless unless the time to execute can be made to be sub-second (currently it takes ballpark 10s on WaW to do 'save screenshot')

W.R.T map parsing - we can get the parse time to be faster! Hopefully fast enough it will not come down to adding a load screen.

An interesting previous discover while doing load game timings. I noticed it took about as long to show and display the 'loading game' window as it does to load the game window in the first place. Hence, the 'load game' window needs to be avoided in its current form, as it blocks whatever process you actually want done, and it takes a long time to display itself. So we need to get better at launching a 'load game' window in the background.

**Comment by DanVanAtta** [comment]
war of the new relic takes a long time to parse. 25s
The rest of the maps are relatively fast to parse. The time is spent in attachment processing. Notably the 'invoke' here: https://github.com/triplea-game/triplea/blob/master/src/games/strategy/engine/data/GameParser.java#L1370

That line can be called 45k times to parse the new relic map.  About 4k of the calls take more than a 1ms to complete, often in the ballpark of 10ms to 40ms.  So generally it is fast, but we call the method too much, and at times it is slow.

The code is pretty crufty. Once it is cleaned up we can see further how to improve the load time, I'm sure we can get it down to a few seconds with all maps downloaded.

**Comment by Cernelius** [comment]
> The problem is not that the game takes 30 seconds to load, but the select game screen takes 30 seconds. IE, if:
> 
> someone downloads all maps
> they then click "select game", the select game window takes 30-60 seconds to open.
> there is no way to know which map caused the delay, or even that it was a map. Likely they will be stuck deleting all maps and will then have to be careful about which ones to download.

Since the problem @DanVanAtta describes doesn't exist as long as "Parse Selected" is selected, I request @DanVanAtta or @ron-murhammer readd this map to DL list and make "Parse Selected" default, if it is not already (I don't know).
Almost all regular users never manual install (paste) maps; so, for them, "Parse All" has no value, as long as all maps in DL list are valid, which should be the case.

**Comment by Cernelius** [comment]
I had an idea that I don't know if it makes sense.

In my computer, War of the Relics takes 30 seconds (exactly) to load, but it takes 2 seconds to save and 2 seconds to load the savegame.
So, maybe, instead of directly parsing / loading the xml, you could convert the xml to the save thing, and parse / load that.

Similarly, since saving and loading a savegame is so much faster, maybe when loading the game, instead of doing it directly, converting it to the save thing and load that, instead.

If this makes no sense, nevermind.

**Comment by Cernelius** [comment]
To be clearer, I'm not much a player of this map, and surely won't miss it, and I think hardly anyone will.
The matter is just sort of for principle.
I don't see why "Parse All" should be default, if it is; so I think "Parse Selected" should be default, if it is not already.
Then, as long as "Parse Selected" is default, I see no reasons for removing this map (the mapmaker clearly put a ton of work into), since it is not slowing down anything relevantly, but the people that specifically select it to play it.
Nor I see any reasons for normal users to go change the settings to "Parse All", and I think almost noone would do it, anyways.
But if I'm missing something, no matter.
And, yah, whatever can be done to make parsing of big xml faster and savegames size smaller I'm sure would be a good thing, allowing mapmakers some more free margin of creativity. I recall Humbabba, in the making of this map (he worked a lot on it, as you can easily imagine), had to limit himself, because the parsing etc. was an issue.
Myself I'm not big on this map, and almost never play it, I just think it's a cool idea (all Humbabba maps are, as he is one of the best mapmakers ever) and adds some nice diversity to the list (like all other Humbabba maps).

**Comment by DanVanAtta** [comment]
I did not realize I still had parse all on. I re-timed the select game screen and we get maybe an extra 100ms to the select game screen load time  (2200~2300ms -> 2350-2500ms)

Given this new information, it is clear that a new user who downloads all maps will not see any problems unless they select 'war of the relic'. In that case at least the culprit of the problem will be relatively obvious. If parse-all were turned on by default (it is not), and if a user were to instead a 30sec load time for the select game screen, I could see that looking really broken and leading to new player abandonment

While on that topic, the principle is then that maps must allow for the integrity of the game engine. That means they need to not crash the game, and must be non-offensive for the general public (to the extent reasonably possible for a WWII board game). The second point we mostly agree on, let's not split hairs. In this instance you've shown that in the normal case, the map does not harm the game for normal / general usage. Hence, please note https://github.com/triplea-maps/Project/issues/53 which restored the map to the (live) download list.

-----------

The next steps would likely be to add a status bar for the game. A person could then see that the game was not frozen but was loading the map when a slow loading map is selected. 

Looking at ways to improve map parsing would work too. The XML might  need  better/more compact representation.

**Comment by Cernelius** [comment]
> The next steps would likely be to add a status bar for the game. A person could then see that the game was not frozen but was loading the map when a slow loading map is selected.

I think this is of some importance, and, if it is an easy fix, it would be nice to have it for the next release. Mind you that this has some more general relevance for people on weak systems, like netbooks (I know at least a couple of them had problems playing TWW on netbook), plus in case of more xml very heavy maps being developed in the future (why not?).
Generally, I think the engine should never let you wondering if it is frozen or loading.
Thanks.

**Comment by DanVanAtta** [comment]
Following up with a map loading indicator in https://github.com/triplea-game/triplea/issues/1469
