### ISSUE TITLE
Save Screenshot is slow

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#982]
The time to do a save screenshot on World at War  was roughly 10s. The feature could use a "load screen" to give feedback that the screenshot is happening. We could print a status message somewhere to indicate the screenshot is happening, but a transition from 'loading' to 'screenshot saved' is more consistent with other UI features.

Best yet, determine why the screenshot is slow. See if we can speed it up to be faster. A progress screen/indicator to give feedback should ideally still be incorporated. As a rule of thumb all user actions should give feedback that the user action is being executed.

**Comment by RoiEXLab** [comment]
@DanVanAtta agree on the slowness part...
Normally it shouldn't take longer than loading a map and even if it would be that fast, it would still be too slow, since the Map is already loaded.

**Comment by ssoloff** [comment]
Just wanted to add some metrics I measured while working PR #1419.  These measurements were made while using the _World at War_ map.

I measured the accumulated execution time within the `ScreenshotExporter#save()` method (this code was previously in `ExportMenu#saveScreenshot(HistoryNode, File, TripleAFrame, GameData)` at the time this issue was created).  The only significant delays I observed within this method were the calls to `MapPanel#drawMapImage()` (previously named `print()` at the time this issue was created) and `ImageIO#write()`.  Each of these calls is responsible for approximately 50% of the total execution time.
