### ISSUE TITLE
Time to load main window is dominated by map parsing

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#985]
The time to fetch map data to populate the left hand side of the main window dominates map bootup time. Experimenting with 'war of the relics', which takes 25s to parse, I noticed that it took that long for the main game screen to load.

A) Map parsing should be faster. That is already being tackled though.
B) We could load the map data in a background thread, would allow for the UI to show up much faster

**Comment by DanVanAtta** [comment]
#980 Fixes a double map parse when clicking open game. For this issue, in contrast, we need to avoid or speed up the initial map parsing that is done to populate the main screen UI data.

**Comment by Cernelius** [comment]
This is very nice to see some work in supporting the big xml maps, finally (I've some big xml stuff I hope to finish soon). I wanna add that I think the biggest problem is the startup in lobby, since it takes a big time to load something like "war of the relics", and it gets multiplied by the number of players (this is a big problem for multi, where reloads are more frequent too), plus observers.
I guess this is savegame size?

**Comment by DanVanAtta** [comment]
"war of the relics" is a bit of a pathological case with many attachments. It takes a long time to parse due to that. I measured the parse time at 25s, that is time to just process the XML data. I upgraded to a fast HDD recently, so likely the 25s is going to be a best case.

**Comment by DanVanAtta** [comment]
Remaining task here is: 

> We could load the map data in a background thread, would allow for the UI to show up much faster
