### ISSUE TITLE
Wrap Dice Rolls to a second line

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#992]
In the combat window, when dice are rolled for large armies, there is typically a horizontal scroll bar to see all the dice rolls. We could avoid some scrolling by wrapping the dice rolls around. Perhaps anywhere from 8 to 15 per line. 

For example in the screenshot below, notice that there is plenty of vertical space available. 
![vertical_space](https://cloud.githubusercontent.com/assets/12397753/16940400/73d365b2-4d3e-11e6-987c-ecc1d205d64a.png)

**Comment by ron-murhammer** [comment]
Agree. Though the thing that bothers me even more are the top portion where the units are shown and often you can't see how many of each you have left.

**Comment by Cernelius** [comment]
> Agree. Though the thing that bothers me even more are the top portion where the units are shown and often you can't see how many of each you have left.

+1
And I can tell it gets worse on 64x64 pixels units and 12 dicesides...

All those columns with no units (like 5 or 6 for attack), unless before any columns with units, should be not displayed, leaving more space for the rest, and the stack number should rather be under the unit, to assure it will be visible also in case of over 64 pixels wide units, like the Germans Bomber of WaW.

You have an extreme example of this in "Conquest of the World".

**Comment by Cernelius** [comment]
> the stack number should rather be under the unit

I changed mind, under the unit is not good, especially with reference to supporting 64 or more pixels high units (that are already cut).
Instead, the stack number should be on the left of the units, not on the right, so that, like in the above case, you would see the stack number for sure, plus a portion of the unit image, that will be probably enough to let you get what it is, as long as the stack number isn't pushing it aside too much.
If it is an easy change to have the stack number on the left, instead of on the right, I definitively suggest doing it right away.

**Comment by ron-murhammer** [comment]
@DanVanAtta I'm guessing there were too many merge conflicts to move forward with the old PR?

**Comment by DanVanAtta** [comment]
No, it was actually there were some alignment issues that happened on every other dice roll. The swing code was going to be very difficult to debug, and we were close to 1.9. The actual wrapping logic was not much, but the swing code was not good. Tricky thing is retrofitting that to work well in the UI.
