### ISSUE TITLE
Production Capacity in Econ Tab

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#993]
The econ tab only has a player and PU listing. Would be useful to have an extra column with the total production capacity per player. 

There is code in the purchase dialog window to compute the total production capacity. That would need to be extracted so it could be re-used. Second, the econ table is a copy/paste of the stats table. Those both should be fixed, then this update would become very easy and clean.

**Comment by Cernelius** [comment]
This is an example of the fact that when you see something looking like apparently pointless (like the Economy tab, just telling you what the Stats tab already tells you, in this case), you should research into it (or ask the community what is the point of that, if any), instead of assuming that it is something just limited to what you see in this or that particular case.

**The economy tab hasn't only a player and PUs listing.**

The economy tab has been added to support maps having other resources than PUs and techTokens.

This means that the economy tab is bloody useless indeed for most maps (having only PUs).

Proposals:

- Make the "Economy" tab being absent in all games having no other listed resources but "PUs" and "techTokens".

- Refactor the way to compute the total production capacity, so to be consistent with the full extent of the current engine capabilities, then add this as a column of the "Stats" tab, not of the "Economy" tab, since it wouldn't fit there, especially for maps having a long list of resources, or as yet another tab, so to avoid the "Stats" tab having too many columns (in this last case, I also suggest moving the "Units" column there too, and maybe having all units numbers listed one by one, there).

What I mean with the first point is that it is bad having this normally useless Economy tab everywhere, since well over 90% of games have no use for it at all: useless additional things are bad additions.

What I mean with the last point is that when you have a more complex place situation than the dumb regular one, the total production capacity is not correctly computed. This is why I had to remove the related warning when I made the 1.5 version of 270BC (accepted by Veqryn with a few changes made by him), with reference to the RomanRepublic player having both city and legionaire as factories; take a look at that, please.
On the other hand, just adding the current dumb total production capacity would be bad for games not using the basic elements of production only, like 270BC, since you would see some bad stats showing up.
A simple solution is to make sure that the total production capacity won't be displayed for games not having the property name="Unit Placement Restrictions" value="true", so that it won't show up in all games having it false, as it is the case of 270BC (I've changed it to false in the 1.5, more than two years ago, because it would not work correctly for RomanRepublic).
The second point above would be a nice feature request for 270BC too, since I can tell you that noobs are used to buy too many units than they can place, there, and, anyway, it would be generally good having the warning about the fact that you bought too many units working in 270BC too or in all games using different place dynamics than the basic v2 ones.
Another thing to keep in mind is that you can have mobile factories (like the General of Napoleonic Empires or the legionaire of 270BC), and in these cases the current total production capacity is not much telling (if you have a move phase in between of the purchase and place phases), because it can change, depending on your moves (I can put my General in a production 4 territory or I can leave it loaded on a ship).
It is moreover very important that you don't forget that under the v1 (Classic) ruleset (that is supposed to be the default ruleset of TripleA!) you have unlimited placement in originally owned factories, thus there is no point at all having such a stat in the "World War II Classic" map or other maps having the placement working by v1 rules! You should make sure that this column won't be displayed in Stats or anything, in such cases.
Also, don't forget that under the v1 ruleset factories in production 0 territories can place 1 unit default, while under the v2 and following rulesets factories in production 0 territories can place 0 units default.

Thanks for raising the issue of the Economy tab being currently useless in almost all maps, yet displayed anyway, which is surely bad: useless things should **not** be displayed everywhere just because they might be useful in a few games.

Anyway, I believe this issue should be tagged as "Low Priority".

**Comment by DanVanAtta** [comment]
Cernel - useful feedback, but two points of order.
- Please stop with the lectures. Issues ARE to the community, this is EXACTLY me raising this question to the community. So please don't slap me with "ask the community", when this is exactly what was done here. Notice that no lines of code have yet to be changed..

- Second, only up vote issues. Note down. Just because you find something not important, does not make it so for you. I can attest that every round I have to sum up the total number of factories on WaW, and it is tedious. This should be a relatively easier change, meaning good return for the buck. In fact, I often will do all infantry purposes just so the game can tell me what the production capacity is. The feature does have a use. I would posit even stronger than that, since it is a bit silly to *only* tell someone they over-purchased after the fact. Basically we're addressing the scenario where someone thinks they may have overpurchased, but are not necessarily sure. 

But beyond that, your priorities are different from mine, which are different from yet other peoples. Saying this is "low priority" for you, is a bit meaningless. If you can state a number of effective work arounds, then perhaps you can make the case that the value from this update is not that much.

**Comment by BeornTheBold** [comment]
On the same subject (economy) I posted on another issue but it is related to this one, national objective income is not shown anywhere except in a popup window at the end of the turn, and only to that player.  Including it somewhere in the stats and/or economy tab would be good, especially since it is possible (my map does) to make extensive use of national objectives.

**Comment by Cernelius** [comment]
Wow! Sorry, I didn't mean to lecture; the "you" was generally referred to any new developers (not having all the history, like Veqryn), which in turn means all currently active developers...

I understood that github was for doing stuff while the developer forum was for gathering opinions, that was just meant to be a suggestion to open up a topic in the developer forum with a question like: "I see that the Economy tab only shows up the PUs in all the maps I know, what is even the point of that? Has the economy tab other uses?".

But ok, so I guess this is a duplication of things between sourceforge and github. I always saw this github thing as a developer-only almost thing, for pushing up the tech stuff.

**Overall it is nice to see a lot of development going on after years of stagnation, so I'm surely very grateful to you (and all developers) for all your hard work, DanVanAtta! Never said so because I thought it was pretty obvious!**

And, yes, this being "Low Priority" is just my opinion, and notice it does not mean that this issue is unimportant, but I believe it is averagely less important than many other currently open issues (there are a lot, by now).

So, maybe I guess this should need the "Discussion" tag, then, since this is you raising this question to the community?

I'll make an effort to be less assertive, but not promising anything (I tend to like to just make points directly, I don't see much problem with that).

I just hope you are not angry (?) with me for how I express my opinions, because it almost sounds like that, by reading your last comment (and you using the all uppercase means shouting?)? I tried to help you in what I can do, sometimes, in the past, and I think I have always been respectful...

And sorry, I just don’t get the principle "only up vote issues. Never down." nor the "the subjective valuation is not very welcome."; I just don't think that makes sense at all, sorry; don't take this as a slap too... I would actually think it would be the best having tons of subjective valuations all the times, instead, be them positive or negative.

...

Going back to the actual issue, reading your user case, I tend to think that it might be better having the max placement allowed listed in the "Produce" window; probably something like:

"Total Placement: 4 units", beside the current like "Total Resources: 23 PUs", which would be a way to do the same thing that you do buying all infantry to get told your current max.

This would also avoid adding 1 more column to the Stats tab, which is not really a good thing, since it means having to wide it more each time to see the numbers (not having 1 not particularly useful additional column is why I have implemented the victory conditions of 270BC without using the Victory Cities).

On the other hand, I would not advise to forcefully restrict what you can buy, even tho this should be how the game should work, because there is the case of mobile factories and all other advanced production related things that can hardly be fully supported (and a warning is more bug friendly than a constriction, which is especially relevant for a volunteers based project with few active developers). Anyway, that could be something handy, if related to a settable property (not something mandatory).

Just My Opinion, and sorry again, I guess...

**Comment by DanVanAtta** [comment]
@Cernelius - water under the bridge, your intentions are in the right place. The key is for us to identify common goals and make as much progress towards those goals as possible. 

Your suggestion @Cernelius  was my first approach, to augment the purchase window. The code in purchase window was not very nice, and the data wiring not obvious, so I looked to the econ tab as an alternative. Having the factory production total info in the stats would be nice. Production capacity is a key stat that complement well units, TUV, and income. Perhaps we can make the stats configurable, so you can hide or show the ones you want. 

Regardless, we can likely crib the current player info from the image draw path in the purchase panel. This solves a small missing data challenge, and with some UI code cleanup we could then finally add the info there easily enough. We could then see how things look from there.

**Comment by Cernelius** [comment]
Probably better having right under the Stats table a button with "Show main stats" / "Show all stats", and only the main stats being shown as default.

When only the main stats are shown, you only see "PUs", "Production" and "TUV" (only these 3).

When all stats are shown, you also see "Units", "FPC" (Factory Production Capacity), "VC" (Victory Cities), and eventually other things.

Of course, pointless stats should be never shown, like not showing "VC" if the map has none and not showing "FPC" if the map has the v1 unlimited placement in original factories or uses advanced and not correctly handled placement rules (like 270BC).

And, as I said, the "Economy" tab should not be shown in games having only PUs or techTokens (over 95% of the games), just like the Objective tab is not shown in games having no Objectives.

I still believe the Factory Production Capacity does not belong to the "Economy" tab, and probably the "Economy" tab should be renamed as "Resources" tab, because this is all that it shows. Better having the "Economy" (on whatever) tab as something reserved for display in multiple-resources games only, as it was originally conceived.

**Comment by BeornTheBold** [comment]
If changes are to be made to the stat and economy tabs, it would be very helpful to allow the lists to be ordered by any column's values.  For example, clicking on the column header "Production" would then list the players in order of production, either ascending or descending.  This is especially helpful if there are a large number of players (my map has 60).

**Comment by Cernelius** [comment]
`
> my map has 60

`Holy...!
