### ISSUE TITLE
2.6 beta: Image display in 270BC

### ISSUE THREAD

**Issue by RaiNova** [triplea-game/triplea#9936]
### Reproduction Steps

1. Start 240BC current head of TripleA 2.6 on Windows 10
2. Select View -> Show Map Blends (don't know if this is relevant)
2. Play around a while
3. Navigate via the mini map
4. The screenshot below shows the image display issue hereby eported
5. The second screenshot shows the same issue in the battle display 

### Attach a Save Game

![image](https://user-images.githubusercontent.com/2886662/147383676-9a529072-9923-433f-80f4-b76abf33d516.png)

![image](https://user-images.githubusercontent.com/2886662/147383736-f896181b-271b-4266-bfeb-1927d0983ad9.png)

### Exception
16:34:57.690 [AWT-EventQueue-0] INFO  g.s.e.m.UnifiedInvocationHandler - Blocking network operation performed from EDT
java.lang.Exception: null
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:52)
	at com.sun.proxy.$Proxy21.getPlaceableUnits(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at games.strategy.engine.player.DefaultPlayerBridge$GameOverInvocationHandler.invoke(DefaultPlayerBridge.java:151)
	at com.sun.proxy.$Proxy21.getPlaceableUnits(Unknown Source)
	at games.strategy.triplea.ui.PlacePanel.getUnitsToPlace(PlacePanel.java:249)
	at games.strategy.triplea.ui.PlacePanel$1.territorySelected(PlacePanel.java:58)
	at games.strategy.triplea.ui.panels.map.MapPanel.notifyTerritorySelected(MapPanel.java:490)
	at games.strategy.triplea.ui.panels.map.MapPanel$3.mouseReleased(MapPanel.java:213)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

### Engine Version

Engine Version: current head of 2.6

### Is there anything else we should know?
Windows 10
GTX 1070 Ti

**Comment by Cernelius** [comment]
Five observations.

1. Is it clear to everyone (else than me) what TripleA version the "current head of TripleA 2.6" is? Is it going to be easy for persons reading this issue in the future to know it?
2. I assume you mean "270BC", not "240BC", but this is actually neither of them: this is "270BC Wars" (assuming no-one made a modified version of it).
3. @DanVanAtta ran (with my encouragement) a program to lower the size of the images of this map (https://github.com/triplea-maps/270bc_wars/commit/ff99ed654792fc0c415c9f302edcaadb9e62ff4e). I guess you may try to download the map before that change was made.
3. It looks to me that you have the map's blends showing, have you (View/Show Map Blends)? Just in case it might be relevant.
4. I wonder if you would have this problem on "270BC" too.

**Comment by RaiNova** [comment]
> Is it clear to everyone (else than me) what TripleA version the "current head of TripleA 2.6" is? Is it going to be easy for persons reading this issue in the future to know it?

How shall I tag such alpha test findings?

> DanVanAtta ran (with my encouragement) a program to lower the size of the images of this map (triplea-maps/270bc_wars@ff99ed6). I guess you may try to download the map before that change was made.

How do I determine which version I have (i.e. what's the image size now and before)?
How do I download an older version of the map?

> It looks to me that you have the map's blends showing, have you (View/Show Map Blends)?

I have. I added that to the error description.

**Comment by panther2** [comment]
@RaiNova 
> > Is it clear to everyone (else than me) what TripleA version the "current head of TripleA 2.6" is? Is it going to be easy for persons reading this issue in the future to know it?
> 
> How shall I tag such alpha test findings?

As of writing this, the current prerelease is 2.6.527. 
Just look at the installation file or at the version info given by TripleA itself:
![version](https://user-images.githubusercontent.com/20812775/147406130-350d4264-d5cc-47a8-8752-3fcf0c89ea54.png)

**Comment by panther2** [comment]
@RaiNova 
To me it is not clear what the current "head" is, Is it the current prerelease, that as the time of writing this is 2.6.527 ?

**Comment by Cernelius** [comment]
@RaiNova I assume you are not aware of the existence of "270BC". "270BC" and "270BC Wars" are two different games, each belonging to a different map. "270BC Wars" is a map-modification of "270BC" at a previous state. Thus the title is still wrong: based on your images, this issue is about "270BC Wars" (not "270BC") as far as I can tell.

> > Is it clear to everyone (else than me) what TripleA version the "current head of TripleA 2.6" is? Is it going to be easy for persons reading this issue in the future to know it?
> 
> How shall I tag such alpha test findings?

I don't know. I just tell the version's number when I open an issue about it.

> > DanVanAtta ran (with my encouragement) a program to lower the size of the images of this map ([triplea-maps/270bc_wars@ff99ed6](https://github.com/triplea-maps/270bc_wars/commit/ff99ed6)). I guess you may try to download the map before that change was made.
> 
> How do I determine which version I have (i.e. what's the image size now and before)? How do I download an older version of the map?

https://github.com/triplea-maps/270bc_wars/archive/db599c2c7f3b29eace9799dde7a4f9547c81d77f.zip
Extract the content of the zipped file into your maps' directory and change its name to "270bc_wars".

> > It looks to me that you have the map's blends showing, have you (View/Show Map Blends)?
> 
> I have. I added that to the error description.

I guess the best way to indagate their relevance is by you trying to replicate the problem with blends off.

---

For information, I'm not replicating this problem and I don't recall I have ever had it despite playing the game of this map many times.

**Comment by Cernelius** [comment]
> > How do I determine which version I have (i.e. what's the image size now and before)? How do I download an older version of the map?
> 
> https://github.com/triplea-maps/270bc_wars/archive/db599c2c7f3b29eace9799dde7a4f9547c81d77f.zip Extract the content of the zipped file into your maps' directory and change its name to "270bc_wars".

However, if you are using the latest pre-release or any other pre-release which unzips maps, paste the zip into your maps' directory, thereafter start TripleA, and thereafter rename the now-unzipped folder from `270bc_wars-db599c2c7f3b29eace9799dde7a4f9547c81d77f` to `270bc_wars`.

**Comment by DanVanAtta** [comment]
This is a bear of a problem. I saw it recently as well:

![Screenshot from 2021-12-26 18-18-34](https://user-images.githubusercontent.com/12397753/147435902-0baf4d6e-0c8c-45eb-9203-24299fd45c3b.png)

![Screenshot from 2021-12-26 18-20-07](https://user-images.githubusercontent.com/12397753/147435903-e505138d-b68b-4073-8368-0d002a90c956.png)


The problem was persistent even after toggling "show map details", hence the two screenshots above (taken on BW 1942 v3).

**Comment by DanVanAtta** [comment]
I think we can rule out a few things:
- OS does not matter nor map
- using minimap to scroll around (I saw this after a combat window closed)

Involved in this problem:
- likely some sort of cache is involved. Any image that is not stored in a cache or is always drawn is unlikely to be a culprit
- TimeImageFactory is likely involved. That renders the battle territory image icon and generally deals with square shapes that we see rendered badly

This is going to be tricky to solve:
- without a good repro, we can't bisect the code, it'll be impossible to know when a version is good or bad.
- we can roll back all updates to TileImageFactory, though that is not even guaranteed to fix the problem.

I think we are best off if we find a way to artificially force code to render territories like this. In other words, trigger the engine through hackery and hardcoded statements to render territories in the way we observe. Once we know 'how' the engine can possibly render a territory like this, we'll have a better hope of finding how the engine falls into this pathological path.

Meanwhile, perhaps we can also rip out some of the image caches and we'll likely fix this problem accidentally. Part of the issue is we get a poisoned cache image that is not updated. If we instead had redraws, the problem would be more a glitch and self-correcting or never happening at all. I'm somewhat inclined to take this approach.

**Comment by Cernelius** [comment]
I'm on Windows 10 and I believe I have never had this problem so far.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/pull/9944 could impact this by removing the cache in `TileImageFactory`. Not only is that the cache that is implicated here, but also I've been eyeing it for removal for some time.. Removing that cache could make this completely non-reproducible (or have no effect..)

---------

Side-note: the stack trace in the OP is also unrelated well. That is a warning message that we are doing a network operation on the EDT (which means the UI is completely frozen until, and if, the network operation completes. That is fixed by invoking the network operation off of the EDT in one manner or another, typically by invoking the network op on a new thread [which can take some re-work if the operation is blocking])

**Comment by DanVanAtta** [comment]
I think it is really remarkable as well how the water is drawn to black. I am curious how it would be possible to have the code to do that at all.

**Comment by Cernelius** [comment]
> I think it is really remarkable as well how the water is drawn to black. I am curious how it would be possible to have the code to do that at all.

Unfortunately, that is very easy an achievement: TripleA is completely unable to display water zones (and all zones' borders are black), so I believe that is merely the inevitable effect of not showing both relief and base tiles. If you remove the `baseTiles` folder from any map (or the map has no base tiles) and have "Show Map Details" off (or the map has no relief tiles), all "seas" should be completely black.

**Comment by Cernelius** [comment]
> > I think it is really remarkable as well how the water is drawn to black. I am curious how it would be possible to have the code to do that at all.
> 
> Unfortunately, that is very easy an achievement: TripleA is completely unable to display water zones (and all zones' borders are black), so I believe that is merely the inevitable effect of not showing both relief and base tiles. If you remove the `baseTiles` folder from any map (or the map has no base tiles) and have "Show Map Details" off (or the map has no relief tiles), all "seas" should be completely black.

What is missing (and I suppose most map-makers learn it while making their first maps and seeing all seas being pure black) is the ability to set a colour for water zones in `map.properties` (like you can do for impassable territories). Since TripleA also allows to own and conquer water territories just like land territories, the colourization to display the current ownership is an other thing that is supported for the land but not for the sea. Of course, I'm drifting off-topic.

**Comment by RaiNova** [comment]
Careful to avoid image caching. Image loading ist taking a big share of cpu time. The following was measured by a first autoplay round of 270BC:

![image](https://user-images.githubusercontent.com/2886662/148208673-fcb43f42-a081-4406-a904-70c923bf6fe4.png)


![image](https://user-images.githubusercontent.com/2886662/148208512-ef15f5ee-9ad0-49b9-b6d8-5c66e83cb9bb.png)

**Comment by RaiNova** [comment]
I believe Dan fixed this issue. So I close it.
