### ISSUE TITLE
270BC - walls don't fall (intended?)

### ISSUE THREAD

**Issue by RaiNova** [triplea-game/triplea#9969]
270BC_Wars.xml contains a territory of type wall_fallen.
wall is configured to turn into wall_fallen when damaged.
But as fas as I understand it, this doesn't happen: A damaged wall is simply removed.

What is the intended behaviour?

**Comment by Cernelius** [comment]
Please provide a save game where you are experiencing what you describe and tell which version of TripleA you are using.

As for the rules, walls are always returned to the embattled territory as soon as they are removed from the battle board. There is no "wall fallen" in the rules: that is just a way to implement the rules, so the "wall fallen" is not even drawn in the game.

**Comment by Cernelius** [comment]
To clarify, during the battle, the "wall" is nothing but a defence 0 unit that is removed when receiving 1 damage, so it is pure fodder. What's different with any other unit in the game is that every removed wall is immediately returned to the embattled territory instead of being removed from the game. The "wall fallen" unit is not a unit by rules, but just a way to enforce the rules.

**Comment by RaiNova** [comment]
Understood. Will be a bit of a challenge for my battle calculator 😁

**Comment by Cernelius** [comment]
> Understood. Will be a bit of a challenge for my battle calculator 😁

I'm not seeing why. Every wall simply turns into a completely useless-for-combat unit when destroyed, so nothing should change because of this, unless you plan to account for TUV of capturable units when the offender wins with at least 1 land unit surviving (in which case, the offender should get a bonus TUV equal to the number of walls in the battle).

**Comment by RaiNova** [comment]
The current battle calculator drives the AI in an internal simulation how the battle may proceed when dice fall on certain sides. This makes the battle calculator independent of the details, als long as the involved AI handles them correctly.

The calculator I am working on computes in a completely different way. It works fine and for the core concept. Additional concepts have to be flanged onto the core functionality. I have a solution for the 270bc walls.

To cover everything you can construct by turning units into something else, repairing that and transferring it to the opponent, would be extremely complex: You could configure a Bruce Benner kind of unit turning into a Hulk when scratched. The current ai wouldn't handle such a case well either.
